### ISSUE TITLE
emacs-pdumper-git包不需要紧跟emacs pdumer分支的更新而自动更新

### ISSUE THREAD

**Issue by yqu212** [archlinuxcn/repo#1003]
### 问题类型 / Type of issues

* 打包错误 / packaging error
### 受影响的软件包 / Affected packages

* 无
----

emacs-pdumper-git打包的是emacs的pdumper分支，而该分支仍然在频繁开发中。是否可以撤销最新版本emacs-pdumper-git-27.0.50.135117-1-x86_64.pkg.tar.xz？该版本有bug无法启动。

目前emacs-pdumper-git包定期自动打包pdumper分支的最新版本。是否可以将版本锁定在之前的可用版本？emacs-pdumper-git包不需要紧跟emacs pdumer分支的更新而自动更新。

**Comment by lilydjwg** [comment]
咦，修改之后没有重新打开？看来又是个 bug……
