### ISSUE TITLE
emacs-pdumper-git包不需要紧跟emacs pdumer分支的更新而自动更新

### ISSUE THREAD

**Issue by yqu212** [archlinuxcn/repo#1004]
### 问题类型 / Type of issues

* 打包错误 / packaging error
### 受影响的软件包 / Affected packages

* emacs-pdumper-git
----

emacs-pdumper-git打包的是emacs的pdumper分支，而该分支仍然在频繁开发中。是否可以撤销最新版本emacs-pdumper-git-27.0.50.135117-1-x86_64.pkg.tar.xz？该版本有bug无法启动。

目前emacs-pdumper-git包定期自动打包pdumper分支的最新版本。是否可以将版本锁定在之前的可用版本？emacs-pdumper-git包不需要紧跟emacs pdumer分支的更新而自动更新。

**Comment by farseerfc** [comment]
關於撤銷，我們源中有保留至少一個歷史版本，可以直接
```
pacman -U http://repo.archlinuxcn.org/x86_64/emacs-pdumper-git-27.0.50.132399-1-x86_64.pkg.tar.xz
```
的方式回滾該包。單純撤銷包本身，由於用戶安裝的包版本號更高，pacman 不會自動做降級處理的。

關於自動更新，其實我們有很多包是有同時提供 -git 版本和非 VCS 的普通版本，比如 `glmark2` 和 `glmark2-git` ，所以應該提議增加 `emacs-pdumper` 包，而非改變現有的 `emacs-pdumper-git` 包。一般 -git 的 VCS 包總是時刻跟隨上游的。追求一定程度穩定性的用戶不建議用 -git 包。

不過該如何決定非 VCS 版本的包的更新頻率比較合適呢？

**Comment by yqu212** [comment]
我昨天已经回滚并且在pacman.conf里忽略它的新版本。对我来说问题暂时已经解决。多谢提醒。

我同意你的意见。按惯例git版本应该跟随上游，并且为了稳定性应该增加非VCS版本emacs-pdumper。然而，新的包似乎不再有必要。pdumper分支昨天[刚刚合并进入master分支](https://github.com/emacs-mirror/emacs/commit/02976d67369699660add46d548f0d1593885334b)。而archlinuxcn中存在emacs-git包，打包的正是emacs master分支。现在的问题是emacs-git包并未时刻跟随上游，它的最后更新是2018年11月。因此，我建议立刻更新emacs-git包至最新版本。

如果更新后的emacs-git包仍然带有bug，我会提议增加emacs-pdumer包。更新频率设为一年会比较合适。emacs的pdumper分支不需要频繁更新。

**Comment by farseerfc** [comment]
wow emacs 上游 merge 了 pdumper 了啊。 那是可以扔掉 emacs-pdumper-git 了
@ykelvis 可以考慮讓 emacs-git 的 lilac.yaml 裏面 
```
update_on: 
  - github: emacs-mirror/emacs
```
?

**Comment by farseerfc** [comment]
我在考慮 drop 掉 emacs-pdumper-git 這個包……現在不是進 master 了麼，直接用 emacs-git 就可以了吧。只不過需要 yk 那邊更新一下 emacs-git 。

**Comment by yqu212** [comment]
好的。yk这几天在忙？那就等着呗。

**Comment by yqu212** [comment]
@farseerfc 是不是yk不希望更新emacs-git？其实暂时保留emacs-pdumper-git包也可以啊，只要把包回退到之前的版本，然后锁定，用起来没有任何问题。等emacs-git包更新之后再删除emacs-pdumper-git包。

**Comment by farseerfc** [comment]
@yqu212 抱歉能問一下哪個版本的 emacs-pdumper-git 可以正常使用麼？我手動打包一個 emacs-pdumper 固定在那兒吧

**Comment by yqu212** [comment]
好的。稍等。我马上试。

**Comment by farseerfc** [comment]
奇怪了……之前那個打包的 commit 已經沒用了，因爲打包的時候自動取的最新的 commit ，現在我固定在 132400 了只差了一個 commit 。以及我這邊 135117 也是能正常開的來着……

**Comment by farseerfc** [comment]
這麼奇怪的麼 😅 又往回退了一個 commit ，麻煩試試？

**Comment by ykelvis** [comment]
```
update_on: 
  - github: emacs-mirror/emacs
```
加上了 git包本来也应该跟上游更 以前居然没弄（

**Comment by yqu212** [comment]
@farseerfc 还是有问题。我调试之后也没找到问题在哪里。算了。既然yk已经更新了emacs-git。我就等emacs-git吧。emacs-pdumper包可以直接删除了。谢谢你

**Comment by yqu212** [comment]
@farseerfc emacs-git包的自动更新需要手动trigger一下吗？

**Comment by ykelvis** [comment]
等机器人打包就好 7c5d5a3 已经更好了

**Comment by farseerfc** [comment]
那我就去把 emacs-pdumper 刪掉了
