### ISSUE TITLE
packaging error: chnroutes2-git

### ISSUE THREAD

**Issue by rocka** [archlinuxcn/repo#1005]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* chnroutes2-git

----

打包出来的 chnroutes.txt 是空的 ...

```console
pacman -Ss chnroutes2-git
archlinuxcn/chnroutes2-git 0.18.41f3c2e-1 [installed]
    Better aggregated chnroutes
cat /usr/share/chnroutes2/chnroutes.txt
# 22353342 routes were dumped from us-sjc04-rs02-a at Sun Oct 21 16:04:37 HKT 2018.
# Found 1 routes matching, aggregated to 1.


```

**Comment by felixonmars** [comment]
这个有问题的版本之前撤掉过， @lilydjwg 是不是修复仓库的时候又找回来了……？

**Comment by lilydjwg** [comment]
@felixonmars 是怎么撤掉的呢？如果是 touch 旧包的话，那么是的……我修复的时候把所有包置为最新版本了。

**Comment by felixonmars** [comment]
是上游撤回了有问题的 commit，所以 lilac 打包时应该又打出了一个旧版，最终效果可能和 touch 了一样……

**Comment by lilydjwg** [comment]
啊，那样包的版本号应该更新了吧？要不再 rebuild 一下？

**Comment by lilydjwg** [comment]
把 pkgrel 加一即可。

**Comment by felixonmars** [comment]
我本来想在仓库里改，但是看到迁移 lilac.yaml 的时候仓库里的 PKGBUILD 被删掉了……

**Comment by lilydjwg** [comment]
PKGBUILD 还在啊，没被删掉啊。`aur_pre_build` 的时候，会先读取 pkgrel，从 AUR 更新之后如果版本号没变就会把 pkgrel 改回去的。

**Comment by felixonmars** [comment]
（原来是移了目录，而我本地留下了一个空的 chnroutes2-git 目录，让我一下没明白为啥删掉了……）
