### ISSUE TITLE
plymouth-git 使用 bgrt 主题时显示错乱

### ISSUE THREAD

**Issue by magicshield** [archlinuxcn/repo#1006]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* plymouth-git

----

因为 plymouth 的主题 bgrt 和 spinner 的差别仅仅只是一个配置属性的不同，上游在最近的提交里面把 bgrt 里面的图片都删除了，仅仅留下了 bgrt.plymouth，并将 ImageDir 指向了 spinner。这导致了 mkinitcpio 在生成 initramfs 的时候没有包含 bgrt 需要的图片文件，启动时就会因为缺少图片而显示错乱了。
我觉得应该修改 plymouth.initcpio_install 和 sd-plymouth.initcpio_install，让它们从 plymouth 的主题配置文件里面的 ImageDir 获取需要添加的文件夹并添加到 initramfs 里面。

以下是我自己使用的：
```bash
PLYMOUTH_IMAGE_DIR="$(grep "ImageDir *= *" ${DATADIR}/plymouth/themes/${PLYMOUTH_THEME_NAME}/${PLYMOUTH_THEME_NAME}.plymouth | sed 's/ImageDir *= *//')"
    if [ -d ${PLYMOUTH_IMAGE_DIR} ]; then
        add_full_dir ${PLYMOUTH_IMAGE_DIR}
    fi
```

**Comment by farseerfc** [comment]
抱歉久等了。應該在 d02901e4f34b08682a64134ce94804a5e6f180f3 plymouth-git 0.9.4.r102.ged9f201-1 之後修了。感謝提供細節信息！
