### ISSUE TITLE
Restore files removed during the Grand Move

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#1008]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

- [ ] android-sdk
- [x] deepin-wine-tim
- [x] freeplane
- [x] gitkraken

----

This issue follows up discussions in https://github.com/archlinuxcn/repo/commit/a196851afef8eea02f0e78997b4e9d9751618681#comments. There are still 4 broken packages:

```
==> Making package: android-sdk 26.1.1-1 (Sat Jan 19 17:00:43 2019)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Found sdk-tools-linux-4333796.zip
  -> Found android-sdk.sh
  -> Found android-sdk.csh
  -> Found android-sdk.conf
==> ERROR: license.html was not found in the build directory and is not a URL.
```

```
==> Making package: deepin-wine-tim 2.1.5-4 (Sat Jan 19 17:00:43 2019)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Found deepin.com.qq.office_2.0.0deepin4_i386.deb
  -> Found TIM2.1.5.exe
  -> Found run.sh
==> ERROR: reg_files.tar.bz2 was not found in the build directory and is not a URL.
```

```
==> Making package: freeplane 1.7.3-1 (Sat Jan 19 17:00:43 2019)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Found freeplane_bin-1.7.3.zip
  -> Found freeplane.desktop
==> ERROR: freeplane.run was not found in the build directory and is not a URL.
```

```
==> Making package: gitkraken 4.2.0-1 (Sat Jan 19 17:00:44 2019)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Found gitkraken-4.2.0.tar.gz
  -> Found GitKraken.desktop
  -> Found gitkraken.png
==> ERROR: eula.html was not found in the build directory and is not a URL.
```

Please add those files back with proper reversion entries in `.gitignore` as proposed by lilydjwg.

**Comment by axionl** [comment]
fixed here: https://github.com/archlinuxcn/repo/commit/e9d45b9acd9b275f44bba9a5113918e9d7092382

**Comment by yan12125** [comment]
@petronny Could you add a package-specific .gitignore to avoid future accidents?

**Comment by petronny** [comment]
我一般都是直接通过lilac.py把文件加回来。。。

**Comment by yan12125** [comment]
何不用標準的.gitignore呢？所有git的實做都會參考這個檔案，所以我才說"to avoid future accidents"。

另外，用.gitignore的話，lilac.py就不需要下面這一行：
```
 run_cmd('git add -f reg_files.tar.bz2'.split(' '))
```
如此一來deepin-wine-tim就可以遷移到lilac.yaml了。

**Comment by petronny** [comment]
自从AUR改成每个包一个git仓库后，基本上每个包也都自带.gitignore了，我认为每个包自己的.gitignore的改动权限在AUR上游，要改的话由上游去改。
上游不改的话，我们自己再通过`lilac.py`改。

另外我不想"avoid future accidents"，假如某个版本`reg_files.tar.bz2`没了，我希望能及时收到报错，把这个patch删了。

**Comment by yan12125** [comment]
Well, 將近三年前百合改了lilac，使得archlinuxcn/repo中的.gitignore和AUR中的.gitignore是獨立的，就算上游改了，也不會被加進repo中。不太確定當初這麼做的意圖是什麼，或許可以把lilac的行為改掉。

https://github.com/archlinuxcn/lilac/commit/b3689f713d5d4b2f5ed52200d26f4b84bb448681

> 假如某个版本`reg_files.tar.bz2`没了，我希望能及时收到报错，把这个patch删了。

的確目前lilac不會把archlinuxcn/repo裡刪除的檔案從AUR刪除。有空來把我之前寫的script移植過來 https://gitlab.com/yan12125/aur/blob/master/scripts/local_to_remote.py#L78

**Comment by yan12125** [comment]
啊弄錯了 AUR刪掉的檔案在archlinuxcn/repo應該是會自動刪掉 https://github.com/archlinuxcn/lilac/blob/master/lilac2/api.py#L362 ，是從repo到AUR才沒有處理刪除的檔案。

**Comment by yan12125** [comment]
After I fixed android-sdk, this issue is mostly done. If @petronny is not interested in using .gitignore, this issue can be closed.

**Comment by petronny** [comment]
> AUR repo 的 .gitignore 有时会导致问题

有的会ignore除了它已有的文件以外所有东西，比如lilac.py

> this issue can be closed.

嗯，关吧

**Comment by yan12125** [comment]
> 有的会ignore除了它已有的文件以外所有东西，比如lilac.py

三年前lilac就不會從AUR上同步.gitignore下來。包裡的.gitignore都是archlinuxcn這邊自行維護的，所以不會有lilac.py被ignore的問題。
