### ISSUE TITLE
pyfm & python2-pyfm 已经无法使用，建议删除

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#1009]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

这俩包已经不能用了，删掉吧．

* 上游链接 / Upstream Link

https://github.com/skyline75489/pyfm

**Comment by lilydjwg** [comment]
请按模板修改。

**Comment by petronny** [comment]
这个是我的，他改了现在也assign不到我，放他一马了。
`lilac.yaml`在解决兼容问题前我会加上，不过等几天的
