### ISSUE TITLE
drawio-desktop

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#1010]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

JavaScripts

* 上游链接 / Upstream Link

https://github.com/jgraph/drawio
https://aur.archlinux.org/packages/drawio-desktop/

* 为何需要这个软件包 / Why Need This Package

Diagram drawing application built on web technology, a lightweight replacement of visio.

**Comment by MarvelousBlack** [comment]
5a977ac68d630437ffc52eabf9a5c5a2e341cbe8
