### ISSUE TITLE
vmware-workstation提示missing required signature

### ISSUE THREAD

**Issue by Rabenda** [archlinuxcn/repo#1017]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  vmware-workstation
*  vmware-xkeymaps

----

请在此补充说明。
安装vmware-workstation提示missing required signature

**Comment by farseerfc** [comment]
fixed in 7ab87aaac68fcd7dc946f738897f28aa5cdd6524
