### ISSUE TITLE
请求编译 libqtelegram-bzr 及 cutegram

### ISSUE THREAD

**Issue by dongfengweixiao** [archlinuxcn/repo#102]
libqtelegram-bzr 编译过程中需要去 google 的网站下载 Googletest，导致编译困难。libqtelegram-bzr 又是 cutegram 的依赖。。
cutegram 是 Telegram 的第三方版本。Telegram 官方版因为代码在写的时候就是为 QT 静态编译服务的，所以编译不出来，只能试试 cutegram 了。

**Comment by farseerfc** [comment]
可以試試 aur/telegram-bin ，官方編譯好的二進制版本，目前除了輸入法沒法用之外別的都正常，輸入法的問題見這個 https://github.com/telegramdesktop/tdesktop/issues/375 。（我沒試過源代碼編譯）。

我目前的機器上一直裝着 aur/cutegram-git，目前裝的版本是 v2.1.0.stable.r27.g81eb25d-1 ，不過連着幾個版本都不能用……一開始的界面處會卡住然後就沒下文了……我會不時試試最新版的。

以及目前的 aur/cutegram 在解決了依賴關係之後依然會編譯報錯，這個 aur 包在 2月11日就被標爲 out of date 了然後一直沒有修掉，報錯的內容我沒仔細研究，貌似是依賴庫的 API 變了還沒跟上。

**Comment by dongfengweixiao** [comment]
telegram 跟随mark down中的方法，stepbystep的变异出来了，然后想要做成动态编译的版本，可是一直失败。考虑到静态编译的版本，所以猜测输入法不能和编译方式有关。刚刚在别人帮我编译好libqtelegram-bzr后，我也已经编译出cutegram的2.1版本。telegram的问题，我请求@yuking-net 是否可以关注下这个项目，可是他看到这个编译模式就兴趣索然了。。。

**Comment by farseerfc** [comment]
2015-05-03 1:27 GMT+09:00 东风唯笑 <notifications@github.com>:

> telegram 跟随mark
> down中的方法，stepbystep的变异出来了，然后想要做成动态编译的版本，可是一直失败。考虑到静态编译的版本，所以猜测输入法不能和编译方式有关。刚刚在别人帮我编译好libqtelegram-bzr后，我也已经编译出cutegram的2.1版本。telegram的问题，我请求
> @yuking-net <https://github.com/yuking-net>
> 是否可以关注下这个项目，可是他看到这个编译模式就兴趣索然了。。。
>
這個項目是指 telegram 還是這邊的社區源呀？編譯模式是指靜態編譯？

以及你那邊 cutegram 編譯出來之後能用麼？

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archlinuxcn/repo/issues/102#issuecomment-98375804>.
>



-- 
--------------------------------------------------------------------------------
Jiachen Yang 楊嘉晨
Graduate School of Information Science and Technology, Osaka University
Tel:   080-3853-2770
MSN:   firechildren@hotmail.com
GMail: farseerfc@gmail.com

**Comment by dongfengweixiao** [comment]
编译出来的cutegram是直接可用的。

telegram不能支持中文输入法我怀疑和这个软件是静态编译有关，所以我今天想要尝试对其动态编译，可是最终失败了。。。我只能说，这个作者写的代码太残暴。
 2015年5月3日 上午12:47于 "Jiachen Yang" <notifications@github.com>写道：

**Comment by farseerfc** [comment]
2015-05-03 1:50 GMT+09:00 东风唯笑 <notifications@github.com>:

> 编译出来的cutegram是直接可用的。
>
>
咦爲什麼我的不可以……刪掉.config/Cutegram之後重新運行的話到驗證短信那一步卡住……



> telegram不能支持中文输入法我怀疑和这个软件是静态编译有关，所以我今天想要尝试对其动态编译，可是最终失败了。。。我只能说，这个作者写的代码太残暴。
>
>

的確和編譯方式有關係，不過靜態編譯Qt本身應該沒什麼問題，archlinux的wps包也是自帶了修改的QT然後靜態編譯的，或許可以參考一下。
不過我沒時間仔細研究它了……


> 2015年5月3日 上午12:47于 "Jiachen Yang" <notifications@github.com>写道：
>
> > 2015-05-03 1:27 GMT+09:00 东风唯笑 <notifications@github.com>:
> >
> > > telegram 跟随mark
> > >
> >
> down中的方法，stepbystep的变异出来了，然后想要做成动态编译的版本，可是一直失败。考虑到静态编译的版本，所以猜测输入法不能和编译方式有关。刚刚在别人帮我编译好libqtelegram-bzr后，我也已经编译出cutegram的2.1版本。telegram的问题，我请求
>
> >
> > > @yuking-net <https://github.com/yuking-net>
> > > 是否可以关注下这个项目，可是他看到这个编译模式就兴趣索然了。。。
> > >
> > 這個項目是指 telegram 還是這邊的社區源呀？編譯模式是指靜態編譯？
> >
> > 以及你那邊 cutegram 編譯出來之後能用麼？
> >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/archlinuxcn/repo/issues/102#issuecomment-98375804>.
>
> > >
> >
> >
> >
> > --
> >
> --------------------------------------------------------------------------------
>
> >
> > Jiachen Yang 楊嘉晨
> > Graduate School of Information Science and Technology, Osaka University
> > Tel: 080-3853-2770
> > MSN: firechildren@hotmail.com
> > GMail: farseerfc@gmail.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/archlinuxcn/repo/issues/102#issuecomment-98377485>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archlinuxcn/repo/issues/102#issuecomment-98377693>.
>



-- 
--------------------------------------------------------------------------------
Jiachen Yang 楊嘉晨
Graduate School of Information Science and Technology, Osaka University
Tel:   080-3853-2770
MSN:   firechildren@hotmail.com
GMail: farseerfc@gmail.com

**Comment by dongfengweixiao** [comment]
明天我将cutegram发一份给你。

telegram编译的问题我已经不想了。太折腾。
2015年5月3日 上午1:07于 "Jiachen Yang" <notifications@github.com>写道：

**Comment by farseerfc** [comment]
多謝~

不過我用 devtools 編譯的 aur/cutegram-git ，依賴環境應該是乾淨的…… strace 看到的問題是死鎖……

目前在用chrome插件版。

2015-05-03 2:09 GMT+09:00 东风唯笑 <notifications@github.com>:

> 明天我将cutegram发一份给你。
>
> telegram编译的问题我已经不想了。太折腾。
> 2015年5月3日 上午1:07于 "Jiachen Yang" <notifications@github.com>写道：
>
> > 2015-05-03 1:50 GMT+09:00 东风唯笑 <notifications@github.com>:
> >
> > > 编译出来的cutegram是直接可用的。
> > >
> > >
> > 咦爲什麼我的不可以……刪掉.config/Cutegram之後重新運行的話到驗證短信那一步卡住……
> >
> >
> >
> > >
> >
> telegram不能支持中文输入法我怀疑和这个软件是静态编译有关，所以我今天想要尝试对其动态编译，可是最终失败了。。。我只能说，这个作者写的代码太残暴。
>
> >
> > >
> > >
> >
> > 的確和編譯方式有關係，不過靜態編譯Qt本身應該沒什麼問題，archlinux的wps包也是自帶了修改的QT然後靜態編譯的，或許可以參考一下。
> > 不過我沒時間仔細研究它了……
> >
> >
> > > 2015年5月3日 上午12:47于 "Jiachen Yang" <notifications@github.com>写道：
> > >
> > > > 2015-05-03 1:27 GMT+09:00 东风唯笑 <notifications@github.com>:
> > > >
> > > > > telegram 跟随mark
> > > > >
> > > >
> > >
> >
> down中的方法，stepbystep的变异出来了，然后想要做成动态编译的版本，可是一直失败。考虑到静态编译的版本，所以猜测输入法不能和编译方式有关。刚刚在别人帮我编译好libqtelegram-bzr后，我也已经编译出cutegram的2.1版本。telegram的问题，我请求
>
> >
> > >
> > > >
> > > > > @yuking-net <https://github.com/yuking-net>
> > > > > 是否可以关注下这个项目，可是他看到这个编译模式就兴趣索然了。。。
> > > > >
> > > > 這個項目是指 telegram 還是這邊的社區源呀？編譯模式是指靜態編譯？
> > > >
> > > > 以及你那邊 cutegram 編譯出來之後能用麼？
> > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > https://github.com/archlinuxcn/repo/issues/102#issuecomment-98375804>.
> > >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > >
> > >
> >
> --------------------------------------------------------------------------------
>
> >
> > >
> > > >
> > > > Jiachen Yang 楊嘉晨
> > > > Graduate School of Information Science and Technology, Osaka
> > University
> > > > Tel: 080-3853-2770
> > > > MSN: firechildren@hotmail.com
> > > > GMail: farseerfc@gmail.com
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/archlinuxcn/repo/issues/102#issuecomment-98377485>.
> >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/archlinuxcn/repo/issues/102#issuecomment-98377693>.
>
> > >
> >
> >
> >
> > --
> >
> --------------------------------------------------------------------------------
>
> >
> > Jiachen Yang 楊嘉晨
> > Graduate School of Information Science and Technology, Osaka University
> > Tel: 080-3853-2770
> > MSN: firechildren@hotmail.com
> > GMail: farseerfc@gmail.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/archlinuxcn/repo/issues/102#issuecomment-98380356>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archlinuxcn/repo/issues/102#issuecomment-98380417>.
>



-- 
--------------------------------------------------------------------------------
Jiachen Yang 楊嘉晨
Graduate School of Information Science and Technology, Osaka University
Tel:   080-3853-2770
MSN:   firechildren@hotmail.com
GMail: farseerfc@gmail.com

**Comment by dongfengweixiao** [comment]
同chromeapp 不过chromeapp作者没有提供托盘区驻留。。。
2015年5月3日 上午1:13于 "Jiachen Yang" <notifications@github.com>写道：

**Comment by farseerfc** [comment]
托盤駐留在KDE5裏也沒用了（當然有別的方法支持，不過效果不是很好） >_< 這一點我倒不在意……

2015-05-03 2:14 GMT+09:00 东风唯笑 <notifications@github.com>:

> 同chromeapp 不过chromeapp作者没有提供托盘区驻留。。。
> 2015年5月3日 上午1:13于 "Jiachen Yang" <notifications@github.com>写道：
>
> > 多謝~
> >
> > 不過我用 devtools 編譯的 aur/cutegram-git ，依賴環境應該是乾淨的…… strace 看到的問題是死鎖……
> >
> > 目前在用chrome插件版。
> >
> > 2015-05-03 2:09 GMT+09:00 东风唯笑 <notifications@github.com>:
> >
> > > 明天我将cutegram发一份给你。
> > >
> > > telegram编译的问题我已经不想了。太折腾。
> > > 2015年5月3日 上午1:07于 "Jiachen Yang" <notifications@github.com>写道：
> > >
> > > > 2015-05-03 1:50 GMT+09:00 东风唯笑 <notifications@github.com>:
> > > >
> > > > > 编译出来的cutegram是直接可用的。
> > > > >
> > > > >
> > > > 咦爲什麼我的不可以……刪掉.config/Cutegram之後重新運行的話到驗證短信那一步卡住……
> > > >
> > > >
> > > >
> > > > >
> > > >
> > >
> >
> telegram不能支持中文输入法我怀疑和这个软件是静态编译有关，所以我今天想要尝试对其动态编译，可是最终失败了。。。我只能说，这个作者写的代码太残暴。
>
> >
> > >
> > > >
> > > > >
> > > > >
> > > >
> > > >
> 的確和編譯方式有關係，不過靜態編譯Qt本身應該沒什麼問題，archlinux的wps包也是自帶了修改的QT然後靜態編譯的，或許可以參考一下。
> > > > 不過我沒時間仔細研究它了……
> > > >
> > > >
> > > > > 2015年5月3日 上午12:47于 "Jiachen Yang" <notifications@github.com>写道：
> > > > >
> > > > > > 2015-05-03 1:27 GMT+09:00 东风唯笑 <notifications@github.com>:
> > > > > >
> > > > > > > telegram 跟随mark
> > > > > > >
> > > > > >
> > > > >
> > > >
> > >
> >
> down中的方法，stepbystep的变异出来了，然后想要做成动态编译的版本，可是一直失败。考虑到静态编译的版本，所以猜测输入法不能和编译方式有关。刚刚在别人帮我编译好libqtelegram-bzr后，我也已经编译出cutegram的2.1版本。telegram的问题，我请求
>
> >
> > >
> > > >
> > > > >
> > > > > >
> > > > > > > @yuking-net <https://github.com/yuking-net>
> > > > > > > 是否可以关注下这个项目，可是他看到这个编译模式就兴趣索然了。。。
> > > > > > >
> > > > > > 這個項目是指 telegram 還是這邊的社區源呀？編譯模式是指靜態編譯？
> > > > > >
> > > > > > 以及你那邊 cutegram 編譯出來之後能用麼？
> > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > > https://github.com/archlinuxcn/repo/issues/102#issuecomment-98375804>.
>
> >
> > > > >
> > > > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > >
> > > > >
> > > >
> > >
> >
> --------------------------------------------------------------------------------
>
> >
> > >
> > > >
> > > > >
> > > > > >
> > > > > > Jiachen Yang 楊嘉晨
> > > > > > Graduate School of Information Science and Technology, Osaka
> > > > University
> > > > > > Tel: 080-3853-2770
> > > > > > MSN: firechildren@hotmail.com
> > > > > > GMail: farseerfc@gmail.com
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > https://github.com/archlinuxcn/repo/issues/102#issuecomment-98377485>.
>
> > > >
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > https://github.com/archlinuxcn/repo/issues/102#issuecomment-98377693>.
> > >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > >
> > >
> >
> --------------------------------------------------------------------------------
>
> >
> > >
> > > >
> > > > Jiachen Yang 楊嘉晨
> > > > Graduate School of Information Science and Technology, Osaka
> > University
> > > > Tel: 080-3853-2770
> > > > MSN: firechildren@hotmail.com
> > > > GMail: farseerfc@gmail.com
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/archlinuxcn/repo/issues/102#issuecomment-98380356>.
> >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/archlinuxcn/repo/issues/102#issuecomment-98380417>.
>
> > >
> >
> >
> >
> > --
> >
> --------------------------------------------------------------------------------
>
> >
> > Jiachen Yang 楊嘉晨
> > Graduate School of Information Science and Technology, Osaka University
> > Tel: 080-3853-2770
> > MSN: firechildren@hotmail.com
> > GMail: farseerfc@gmail.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/archlinuxcn/repo/issues/102#issuecomment-98380589>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archlinuxcn/repo/issues/102#issuecomment-98380631>.
>



-- 
--------------------------------------------------------------------------------
Jiachen Yang 楊嘉晨
Graduate School of Information Science and Technology, Osaka University
Tel:   080-3853-2770
MSN:   firechildren@hotmail.com
GMail: farseerfc@gmail.com
