### ISSUE TITLE
重新打包lxd

### ISSUE THREAD

**Issue by PinkD** [archlinuxcn/repo#1020]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

  * 弃置软件包时的issue #843 中提到的问题已经通过 `patchelf` 修改 `lxd` 的 `RPATH` 的方法解决，希望能重新将lxd加入源中

  * 对应aur上的commit：
https://aur.archlinux.org/cgit/aur.git/commit/?h=lxd&id=3aab200b88e4b0407872d259b8413ae4f7f17575

* 上游链接 / Upstream Link

  * https://github.com/lxc/lxd

**Comment by kaseiwang** [comment]
done.
