### ISSUE TITLE
Package Request[darling-git]

### ISSUE THREAD

**Issue by LinArcX** [archlinuxcn/repo#1022]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description : A Darwin/OS X emulation layer for Linux
--

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link : https://aur.archlinux.org/packages/darling-git/

（请在此填写）

* 为何需要这个软件包 / Why Need This Package: This repo has many sub-modules and build process is very long.

（请在此填写）

**Comment by LinArcX** [comment]
Any news about this package request?

**Comment by BruceZhang1993** [comment]
@LinArcX 
It seems this package keeps failing to build on building machine.

**Comment by LinArcX** [comment]
@BruceZhang1993 why?

**Comment by BruceZhang1993** [comment]
@LinArcX 
Building darling-git process is looking for headers same as kernel version on building machine host (which is 4.18.x now). But our chroot building environment is now latest kernel (4.20.x).
So the building wont pass.

This might also happen if your running kernel does not match installed kernel.

**Comment by LinArcX** [comment]
I see. so, what we can do?

**Comment by BruceZhang1993** [comment]
@LinArcX 
If you have any idea to solve this issue, a PR is always welcomed.
