### ISSUE TITLE
The future of mongodb

### ISSUE THREAD

**Issue by felixonmars** [archlinuxcn/repo#1027]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

mongodb

So here is the situation: I have dropped mongodb from [community] because of the license change. The build server lilac currently resides won't be able to build it successfully.

I am listing the related points below:

- In [community]: I build it on my own build server with 512G ram. When upstream dependency changes (especially for a boost rebuild), others in the Arch Linux team help me find a patch or port */me shameless*.
- In AUR: I don't really see anyone interested in maintaining it due to the monstrous resource requirement. If we rely on lilac to follow AUR, this is also a problem.
- In [archlinuxcn] and I still build it myself: I'll have to adapt to the library changes in official repos myself, but I am not really an expert in c++/boost.

So we still have some other options: Drop it and repack mongodb-bin instead; Consider other binaries like Percona Server for MongoDB since it's a drop-in replace...

**Comment by felixonmars** [comment]
@frealgagu Please take a look.

**Comment by yan12125** [comment]
I notice that a large portion of the building process is for the test suite. How about disabling the test suite and `check()` to speed up the build?

**Comment by yan12125** [comment]
By the way, vestigial files from previous failed mongodb build breaks the last two lilac runs (2019-01-30T01:17:02 and 2019-01-30T09:03:02)
```
$ cat /home/lilydjwg/.lilac/log/2019-01-30T01:17:02
[D 01-30 01:17:02.109 cmd:46] running ['git', 'reset', '--hard'], not using pty, showing output
HEAD 现在位于 73ad34e3a auto update for package tidb
[D 01-30 01:17:02.143 cmd:46] running ['git', 'pull', '--no-edit'], not using pty, showing output
来自 github.com:archlinuxcn/repo
   73ad34e3a..527394e99  master     -> origin/master
error: 工作区中下列未跟踪的文件将会因为合并操作而被覆盖：
        archlinuxcn/mongodb/PKGBUILD
        archlinuxcn/mongodb/mongodb.conf
        archlinuxcn/mongodb/mongodb.service
        archlinuxcn/mongodb/mongodb.sysusers
        archlinuxcn/mongodb/mongodb.tmpfiles
请在合并前移动或删除。
终止中
更新 73ad34e3a..527394e99
[E 01-30 01:17:06.146 lilac:368] unexpected error
    Traceback (most recent call last):
      File "/home/lilydjwg/soft/lilac/lilac", line 365, in main
        main_may_raise(D, pkgs_to_build)
      File "/home/lilydjwg/soft/lilac/lilac", line 275, in main_may_raise
        git_pull()
      File "/home/lilydjwg/soft/lilac/lilac2/cmd.py", line 16, in git_pull
        output = run_cmd(['git', 'pull', '--no-edit'])
      File "/home/lilydjwg/soft/lilac/lilac2/cmd.py", line 103, in run_cmd
        raise subprocess.CalledProcessError(code, cmd, outs)
    subprocess.CalledProcessError: Command '['git', 'pull', '--no-edit']' returned non-zero exit status 1.
```
That's because `aur_pre_build` in the last mongodb build downloaded files untracked in git, and later these files are added to git (213bf38fa55ef84524d238cbafbf4179235359bf). I removed them following the advice [in the Wiki](https://github.com/archlinuxcn/repo/wiki/%5BEN%5D-lilac-FAQ#q-lilac-send-me-a-build-log-saying-building-was-fail-due-to-source-file-checksum-mismatch-both-source-files-and-checksums-are-updated-and-it-might-be-due-to-lilac-is-caching-the-old-file-how-can-i-delete-the-cached-files), in the hope that the next lilac run will be fine.
```
$ sudo cleanup-package-files --real mongodb   
rm -rf /home/lilydjwg/archgitrepo/archlinuxcn/mongodb/PKGBUILD
rm -rf /home/lilydjwg/archgitrepo/archlinuxcn/mongodb/mongodb-src-r4.0.5.tar.gz
rm -rf /home/lilydjwg/archgitrepo/archlinuxcn/mongodb/mongodb.sysusers
rm -rf /home/lilydjwg/archgitrepo/archlinuxcn/mongodb/mongodb.conf
rm -rf /home/lilydjwg/archgitrepo/archlinuxcn/mongodb/__pycache__
rm -rf /home/lilydjwg/archgitrepo/archlinuxcn/mongodb/mongodb.tmpfiles
rm -rf /home/lilydjwg/archgitrepo/archlinuxcn/mongodb/mongodb.service
```

**Comment by felixonmars** [comment]
@yan12125 Yes for lilac. The AUR maintainer still needs it to identify compatibility issues though.

**Comment by yan12125** [comment]
Were there cases where mongodb can be built with a new version for some system library but tests failed?

**Comment by felixonmars** [comment]
Yes, and especially in the most time consuming integration tests.

**Comment by frealgagu** [comment]
Should I delete the folder in repo, I'm not going to use mongodb and I don't want to maintain it. Being that lilac can't build it I consider the package could be deleted and if anyone else want to upload it upstream he should create the package again.

**Comment by edward-p** [comment]
> Should I delete the folder in repo, I'm not going to use mongodb and I don't want to maintain it. Being that lilac can't build it I consider the package could be deleted and if anyone else want to upload it upstream he should create the package again.

Just open an issue with "Orphaning" template. If there's no maintainer wants to keep maintaining it, lilac will delete it for you in 20 days.

**Comment by yan12125** [comment]
Well, 14 days actually.

https://github.com/archlinuxcn/misc_scripts/blob/6ec4146a22a44e5bd0ede0e5125f46a68ab1fbeb/issuebot#L15

**Comment by yan12125** [comment]
Given mongodb is removed in https://github.com/archlinuxcn/repo/commit/1f9ab89d1b199bebcc6a71dc4af81b639ba67ca4, this issue is no longer related to [archlinuxcn].
