### ISSUE TITLE
[Out-of-date] iease-music

### ISSUE THREAD

**Issue by axionl** [archlinuxcn/repo#1028]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* iease-music
----

请在此补充说明。
Please describe in detail here.

看 lilac 应该是自动打包出现问题了。

https://build.archlinuxcn.org/packages/#/iease-music

**Comment by heavysink** [comment]
貌似自己又好了...
