### ISSUE TITLE
Package Request: google-chinese-handwriting-ime

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#1032]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Electron 寫的利用 Google Translate 的手寫輸入法

* 主要语言和工具链 / Main Languages and Toolchains
Electron

* 上游链接 / Upstream Link

https://github.com/Saren-Arterius/google-chinese-handwriting-ime

* 为何需要这个软件包 / Why Need This Package

中文觸屏用戶可能需要

**Comment by MarvelousBlack** [comment]
google-chinese-handwriting-ime-git 已加入repo
