### ISSUE TITLE
Orphaning ruby-rake-compiler for it is in [community]

### ISSUE THREAD

**Issue by SilverRainZ** [archlinuxcn/repo#1036]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* ruby-rake-compiler

----
ruby-rake-compiler is already in [community].

**Comment by lilydjwg** [comment]
这个不是已经没了吗？ 39e85d4bd

**Comment by SilverRainZ** [comment]
感觉不通知一下就删包是不是不太好……万一 community 的版本 break 了 cn 源这边的包呢。
