### ISSUE TITLE
Package Request: hlsdl

### ISSUE THREAD

**Issue by amitbha** [archlinuxcn/repo#1037]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description
将 .m3u8 播放列表中的视频流下载为 ts 格式视频

* 主要语言和工具链 / Main Languages and Toolchains
C语言

* 上游链接 / Upstream Link
https://github.com/e2iplayer/hlsdl

* 为何需要这个软件包 / Why Need This Package
有不少网站能解析出视频的m3u8，但没有下载功能

**Comment by BruceZhang1993** [comment]
**All done**
