### ISSUE TITLE
google-chrome not updated by lilac

### ISSUE THREAD

**Issue by xgdgsc** [archlinuxcn/repo#104]
google-chrome 42.0.2311.135-1 not updated

**Comment by lilydjwg** [comment]
lilac is experiencing lots of [corrupted packages errors](https://bbs.archlinux.org/viewtopic.php?id=196895). We're still investigating why.

**Comment by xgdgsc** [comment]
Try deleting  these part files?
$ ls -l /var/cache/pacman/pkg/|grep part
-rw-r--r-- 1 root root    248304 3月  25 10:43 iptables-1.4.21-3-x86_64.pkg.tar.xz.part
-rw-r--r-- 1 root root    136384 2月  17 09:15 libdbus-1.8.16-2-x86_64.pkg.tar.xz.part

from log:
debug: found cached pkg: /var/cache/pacman/pkg/libdbus-1.8.16-2-x86_64.pkg.tar.xz.part
debug: using (package - .part) size
debug: setting download size 0 for pkg libdbus
debug: found cached pkg: /var/cache/pacman/pkg/iptables-1.4.21-3-x86_64.pkg.tar.xz.part
debug: using (package - .part) size
debug: setting download size 0 for pkg iptables

**Comment by lilydjwg** [comment]
On Thu, May 07, 2015 at 09:02:05AM -0700, xgdgsc wrote:
> Try deleting  these part files?
> $ ls -l /var/cache/pacman/pkg/|grep part
> -rw-r--r-- 1 root root    248304 3月  25 10:43 iptables-1.4.21-3-x86_64.pkg.tar.xz.part
> -rw-r--r-- 1 root root    136384 2月  17 09:15 libdbus-1.8.16-2-x86_64.pkg.tar.xz.part
> 
> from log:
> debug: found cached pkg: /var/cache/pacman/pkg/libdbus-1.8.16-2-x86_64.pkg.tar.xz.part
> debug: using (package - .part) size
> debug: setting download size 0 for pkg libdbus
> debug: found cached pkg: /var/cache/pacman/pkg/iptables-1.4.21-3-x86_64.pkg.tar.xz.part
> debug: using (package - .part) size
> debug: setting download size 0 for pkg iptables

deleted.

-- 
Best regards,
lilydjwg

**Comment by xgdgsc** [comment]
Now it doesn' t fail at package checking. Now it fails when extracting files:

debug: extracting /usr/share/man/man3/XtOwnSelection.3.gz
debug: extracting /usr/share/man/man3/XtGetResourceList.3.gz
debug: extracting /usr/share/man/man3/XtAppGetExitFlag.3.gz
debug: extracting /usr/share/man/man3/XtCallbackPopdown.3.gz
debug: extracting /usr/share/man/man3/XtSetSelectionParameters.3.gz
debug: extracting /usr/share/man/man3/XtProcessLock.3.gz
debug: extracting /usr/share/man/man3/XtScreenOfObject.3.gz
debug: extracting /usr/share/man/man3/XtAppError.3.gz
debug: extracting /usr/share/man/man3/XtParseTranslationTable.3.gz
debug: extracting /usr/share/man/man3/XtCallbackExclusive.3.gz
debug: extracting /usr/share/man/man3/XtCallActionProc.3.gz
debug: extracting /usr/share/man/man3/XtDisownSelection.3.gz
debug: extracting /usr/share/man/man3/XtCancelSelectionRequest.3.gz
debug: extracting /usr/share/man/man3/XtBuildEventMask.3.gz
debug: extracting /usr/share/man/man3/XtInsertEventHandler.3.gz
debug: extracting /usr/share/man/man3/XtVaSetSubvalues.3.gz
debug: extracting /usr/share/man/man3/XtSetSelectionTimeout.3.gz
debug: extracting /usr/share/man/man3/XtAppAddInput.3.gz
debug: extracting /usr/share/man/man3/XtDispatchEvent.3.gz
debug: extracting /usr/share/man/man3/XtLastTimestampProcessed.3.gz
debug: extracting /usr/share/man/man3/XtSetEventDispatcher.3.gz
debug: extracting /usr/share/man/man3/XtMergeArgLists.3.gz
debug: extracting /usr/share/man/man3/XtManageChildren.3.gz
debug: extracting /usr/share/man/man3/XtNumber.3
Container gsc failed with error code 2.

**Comment by xgdgsc** [comment]
Build success after cleaning some A character in end of PKGBUILD (might be error when copying paste).

**Comment by lilydjwg** [comment]
It's been updated.
