### ISSUE TITLE
Package Request(Haskell-ide-engine)

### ISSUE THREAD

**Issue by LinArcX** [archlinuxcn/repo#1044]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description: The engine for haskell ide-integration. Not an IDE

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link : https://aur.archlinux.org/packages/haskell-ide-engine

（请在此填写）

* 为何需要这个软件包 / Why Need This Package: downalod and build process is too long.

（请在此填写）

**Comment by dctxmei** [comment]
https://github.com/archlinuxcn/repo/commit/95ced3b48b28585bb0e4ea8a50d9ed65d200383c
