### ISSUE TITLE
youtube-dl-git out of date

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#1045]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* youtube-dl-git

----

It's tens of days behind.

**Comment by lilydjwg** [comment]
No maintainers info?

@colinkeenan You need to place a [lilac.yaml](https://archlinuxcn.github.io/lilac/) with `maintainers` field for each of your packages.

**Comment by SilverRainZ** [comment]
I think it is no longer out-of-date.
34794e0d28758b00a961f59ff297682cdc3fe5a3
