### ISSUE TITLE
php-imagick 打包请求

### ISSUE THREAD

**Issue by lizr2004** [archlinuxcn/repo#1051]
### 问题类型 / Type of issues

* 软件打包请求 / package request

* 简述 / Brief Description

php-imagick 提供 php 的图片处理

* 主要语言和工具链 / Main Languages and Toolchains

C PHP

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/php-imagick
https://aur.archlinux.org/php-imagick.git
https://pecl.php.net/package/imagick

* 为何需要这个软件包 / Why Need This Package

部署WordPress需要，相信很多人也需要吧...

**Comment by BruceZhang1993** [comment]
Done.
