### ISSUE TITLE
orphaning gnome-shell-extension-dash-to-dock because maintainer is unknonwn

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#1053]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* gnome-shell-extension-dash-to-dock

----

这个包由 cda1437408a684cd5de800fb5bcee2747188f395 添加，维护者写的是 nierunjie 但是查无此人。

**Comment by lilydjwg** [comment]
咦，根据 github 的记录，这个提交是 @lanthora 于 #887 产生的。所以， lanthora 还是 @a-wing 来维护这个包，更新一下 lilac.yaml 呀？

**Comment by lanthora** [comment]
@a-wing

**Comment by a-wing** [comment]
看来这锅变成我的了`_(ˊཀˋ」∠)_`
