### ISSUE TITLE
Changing git repository of vlc-git

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#1055]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* vlc-git
----

请问能帮忙把vlc-git的repo换到githttps://git.videolan.org/git/vlc.git吗？

还有，以后类似换repo能否实现自动化？比如说读取lilac.yaml内的信息然后自动删除/重新checkout新repo？不过这个需求量应该不大，只是个微小的建议啊，很惭愧。

谢谢

**Comment by lilydjwg** [comment]
现在可以自行清理的：

```sh
sudo cleanup-package-files --real vlc-git
```

**Comment by heavysink** [comment]
我不能sudo...

**Comment by lilydjwg** [comment]
不会啊，那个命令都是可以的。
