### ISSUE TITLE
python-torchvision: Datasets, transforms, and models specific to computer vision

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#1057]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* python-torchvision

----

I've orphaned [the corresponding aur package](https://aur.archlinux.org/packages/python-torchvision/), too.

**Comment by yan12125** [comment]
Hmm there was no package name in the issue comment but lilac doesn't complain 🤔

**Comment by lilydjwg** [comment]
因为有解析出来的包名的，参见 https://github.com/archlinuxcn/repo/commit/98b63b0ad3a3ed991ea3246c29828499a60d1e1e ……
