### ISSUE TITLE
package request: gnome-shell-pomodoro

### ISSUE THREAD

**Issue by OliverLew** [archlinuxcn/repo#1059]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

[gnome-shell-pomodoro](https://github.com/codito/gnome-pomodoro)，Gnome shell上的时间管理插件，

* 主要语言和工具链 / Main Languages and Toolchains

vala gtk

* 上游链接 / Upstream Link

https://github.com/codito/gnome-pomodoro
http://gnomepomodoro.org/
It is in AUR: https://aur.archlinux.org/packages/gnome-shell-pomodoro/

* 为何需要这个软件包 / Why Need This Package

受欢迎、很实用有效的提高效率的工具。aur中make依赖有点多，打包的话用户安装时会好一点。

**Comment by dctxmei** [comment]
[add for package gnome-shell-pomodoro](https://github.com/archlinuxcn/repo/tree/d4dbcdaad38405c8bcd26a20729dcebca46e03d7)

**Comment by dctxmei** [comment]
https://github.com/archlinuxcn/repo/commit/d4dbcdaad38405c8bcd26a20729dcebca46e03d7
