### ISSUE TITLE
[PKG request] opencv-python

### ISSUE THREAD

**Issue by kmahyyg** [archlinuxcn/repo#1065]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

opencv-python

* 主要语言和工具链 / Main Languages and Toolchains

Opencv Binding in Python

* 上游链接 / Upstream Link

https://pypi.org/project/opencv-python/

* 为何需要这个软件包 / Why Need This Package

A lot of people need that for its famous usage in image processing, check the pypi project page.

**Comment by kmahyyg** [comment]
看到群里有人问，回复一下，Arch 的 opencv 不带 Python Binding，您可以尝试 Fresh install `opencv python` 之后发现 `import cv2` 啥都没有。

**Comment by cuihaoleo** [comment]
带的啊：
```
$ python -c "print(__import__('cv2').__file__)"
/usr/lib/python3.7/site-packages/cv2.cpython-37m-x86_64-linux-gnu.so
$ pacman -Qo /usr/lib/python3.7/site-packages/cv2.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/site-packages/cv2.cpython-37m-x86_64-linux-gnu.so is owned by opencv 4.0.1-5
```

**Comment by kmahyyg** [comment]
发现了，我的 Pycharm 的 Project interpreter 不知道啥时候变成了 remote arch server，那台机器没装...
