### ISSUE TITLE
[Package Request]Fsearch

### ISSUE THREAD

**Issue by LinArcX** [archlinuxcn/repo#1067]
### 问题类型 / Type of issues

* 软件打包请求 / package request: https://aur.archlinux.org/packages/fsearch-git/

----

* 简述 / Brief Description: A fast file search utility for Unix-like systems based on GTK+3

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link: https://github.com/cboxdoerfer/fsearch

（请在此填写）

* 为何需要这个软件包 / Why Need This Package: Build process take time.

（请在此填写）

**Comment by OriginCode** [comment]
https://github.com/archlinuxcn/repo/commit/8156e4427a5f44a5430950698614ca5d5eae8bc9
