### ISSUE TITLE
pulseaudio-modules-bt-git 直接从AUR拉取PKGBUILD

### ISSUE THREAD

**Issue by EHfive** [archlinuxcn/repo#1068]
### 问题类型 / Type of issues

* 软件打包请求 / package request
----

* 简述 / Brief Description

    首先, 感谢 @BruceZhang1993 在 archlinuxcn 维护了 `pulseaudio-modules-bt(-git)`, 我个人也很早就是archlinuxcn 的使用者.

    不确定是否应该用 package request 模板, 如果不符合规范我道歉

    我是 https://github.com/EHfive/pulseaudio-modules-bt 的开发者, 同时 [AUR/pulseaudio-modules-bt-git](https://aur.archlinux.org/packages/pulseaudio-modules-bt-git/) 也是由我维护的. 由于当初我没有规范的编写PKGBUILD, 所以 @BruceZhang1993 没有直接使用AUR上的PKGBUILD.

    现在的话希望 `pulseaudio-modules-bt-git` 直接从AUR拉取 PKGBUILD, 那这边可以更快的响应我的更改以避免 PKGBUILD 过时 或 产生编译错误

    (顺便 `pulseaudio-modules-bt` 可以升级一下到v1.1 )

* 主要语言和工具链 / Main Languages and Toolchains

    C, Cmake

* 上游链接 / Upstream Link

    https://github.com/EHfive/pulseaudio-modules-bt

* 为何需要这个软件包 / Why Need This Package

    pulseaudio A2DP 额外编码支持

**Comment by BruceZhang1993** [comment]
@EHfive 了解，稍后修改为跟随 AUR PKGBUILD

**Comment by lilydjwg** [comment]
不知道用哪个模板好的时候就用「其它」啦。pkgreq 是针对仓库里没有的包，并且是会自动过期的。

**Comment by EHfive** [comment]
Thanks all.
