### ISSUE TITLE
[Package Request] clash

### ISSUE THREAD

**Issue by tkkcc** [archlinuxcn/repo#1069]
### 问题类型 / Type of issues

* 软件打包请求 / package request
https://aur.archlinux.org/packages/clash/

* 简述 / Brief Description
A rule based proxy in Go.

* 主要语言和工具链 / Main Languages and Toolchains
go

* 上游链接 / Upstream Link
https://github.com/Dreamacro/clash

* 为何需要这个软件包 / Why Need This Package
代理路由

**Comment by dctxmei** [comment]
https://github.com/archlinuxcn/repo/commit/edc6745c980e486da67360a9a95e0a36359f26c4
