### ISSUE TITLE
pkgbuild-introspection-git out-of-date

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#107]
```
archlinuxcn/pkgbuild-introspection-git 3.1.g8b84cf9-1
    Tools for generating .AURINFO files and PKGBUILD data extraction (mkaurball)
aur/pkgbuild-introspection-git 6.4.ga135f86-1 (17)
    Tools for generating .SRCINFO files and PKGBUILD data extraction (mkaurball)
```

pkgbuild-introspection-git 6.4 in aur provides `mksrcinfo` cmd which is essential for work with aur4.

**Comment by yuyichao** [comment]
I guess I was assigned because of my commit to clean up `.gitignore`......

Anyway, I just updated it manually .......................

**Comment by farseerfc** [comment]
Sorry, I failed to find its original uploader. And thank you for updating it!
I can take over this package if you didn't upload this.
