### ISSUE TITLE
[Package Request] rxvt-unicode-better-wheel-scrolling

### ISSUE THREAD

**Issue by tkkcc** [archlinuxcn/repo#1070]
### 问题类型 / Type of issues

* 软件打包请求 / package request
https://aur.archlinux.org/packages/rxvt-unicode-better-wheel-scrolling

* 简述 / Brief Description
An unicode enabled rxvt-clone terminal emulator with better wheel scrolling

* 主要语言和工具链 / Main Languages and Toolchains
gcc,perl

* 上游链接 / Upstream Link
https://aur.archlinux.org/packages/rxvt-unicode-better-wheel-scrolling

* 为何需要这个软件包 / Why Need This Package
减少自编译时间

**Comment by dctxmei** [comment]
https://github.com/archlinuxcn/repo/commit/b41571fc059b5bb73f50d86bfb0a7f41af947487
