### ISSUE TITLE
讨论：尽量避免使用 *archlinuxcn*-build

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#1073]
### 问题类型 / Type of issues

* 其它 / other

----

如题，对lilac而言，在repo_depends的加持下，
除了极少手动打包不能写进repo_depends的情况外，
`*archlinuxcn*-build` 相对于 extra- 和 multilib- 并没有什么优势，还有取代了官方源的包的可能。
所以建议尽量把 `*archlinuxcn*-build` 改成 extra- 和 multilib-
除非有不能写进depends的

**Comment by lilydjwg** [comment]
我找出了所有 archlinuxcn- 开头的包，以及它们的维护者。不少呢。

@OriginCode:
* [ ] fcitx5-anthy-git
* [ ] mcpelauncher-ui-git

@Sasasu:
* [ ] mycli
* [ ] python-pipsi
* [ ] uget-integrator-browsers

@SilverRainZ:
* [ ] discord
* [ ] gdm-plymouth
* [ ] jekyll
* [ ] pyenv-virtualenv
* [ ] ruby-benchmark-ips
* [ ] ruby-benchmark_suite
* [ ] ruby-concurrent-ruby
* [ ] ruby-em-websocket
* [ ] ruby-http_parser.rb
* [ ] ruby-i18n-0.9
* [ ] ruby-jekyll-watch
* [ ] ruby-json
* [ ] ruby-listen
* [ ] ruby-yajl-ruby

@VOID001:
* [ ] bilidan-git
* [ ] gnome-vfs-perl

@a-wing:
* [ ] apm_planner
* [ ] ruby-globalid
* [ ] ruby-i18n
* [ ] ruby-rails-dom-testing
* [ ] ruby-sprockets
* [ ] ruby-sprockets-rails

@attenuation:
* [ ] google-earth-pro
* [ ] python2-pwntools

@axionl:
* [ ] signal

@bennyyip:
* [ ] lector-git
* [ ] neovim-qt-git
* [ ] python-cli_helpers

@colinkeenan:
* [ ] stapler-git

@dctxmei:
* [ ] betterlockscreen

@farseerfc:
* [ ] fcitx5-anthy-git
* [ ] glmark2
* [ ] glmark2-git
* [ ] pm2ml

@felixonmars:
* [ ] libtorrent-ipv6
* [ ] pakku
* [ ] php53
* [ ] php53-apc
* [ ] php53-memcache
* [ ] php53-memcached
* [ ] php53-mongo
* [ ] php53-xcache
* [ ] php56-apcu
* [ ] php56-memcache
* [ ] php56-memcached
* [ ] php56-xcache
* [ ] rtorrent-ipv6
* [ ] ruby2.2-bundler
* [ ] uwsgi-plugin-php53
* [ ] uwsgi-plugin-php56
* [ ] uwsgi-plugin-rack22

@frantic1048:
* [ ] plex-hama-bundle-git
* [ ] plex-media-server
* [ ] scrcpy

@heavysink:
* [ ] anbox-git
* [ ] blockify
* [ ] crawl-tiles
* [ ] dbus-cpp
* [ ] eclipse-dltk-core
* [ ] eclipse-dltk-javascript
* [ ] eclipse-dltk-python
* [ ] fs-uae-arcade-devel
* [ ] fs-uae-launcher-devel
* [ ] gegl-git
* [ ] gimp-git
* [ ] i-nex-git
* [ ] kodi-git
* [ ] libopenglrecorder
* [ ] microsoft-r-open
* [ ] moonplayer-plugins
* [ ] process-cpp
* [ ] rpcs3-avx2-git
* [ ] rpcs3-avx-git
* [ ] stone-soup-tiles-git
* [ ] supertuxkart-git
* [ ] vlc-git
* [ ] nvidia-beta
* [ ] libdvdnav-git
* [ ] libdvdread-git

@lijinpei:
* [ ] barvinok
* [ ] cockpit
* [ ] gumbo-git
* [ ] isl
* [ ] pcp
* [ ] polylib

@masakichi:
* [ ] litecli

@petronny:
* [ ] bomi-git
* [ ] bypy-git
* [ ] chromium-dev
* [ ] foxitreader
* [ ] mpv-git
* [ ] python3-aur
* [ ] python-multiprocess

@phoenixlzx:
* [ ] jdk
* [ ] ttf-google-fonts-git

@qwIvan:
* [ ] pgcli
* [ ] pushbullet-cli

@renyuneyun:
* [ ] displaylink

@swordfeng:
* [ ] emacs-evil
* [ ] emacs-undo-tree

@wicast:
* [ ] spice-vdagent-git

@xgdgsc:
* [ ] rstudio-desktop-bin

@ykelvis:
* [ ] anything-sync-daemon
* [ ] baka-mplayer-git
* [ ] clion
* [ ] dockbarx
* [ ] emacs-git
* [ ] firetools
* [ ] go-for-it-git
* [ ] goland
* [ ] grub2-theme-arch-leap
* [ ] kindlegen
* [ ] leanote
* [ ] libgweather2
* [ ] liboobs
* [ ] libui
* [ ] libui-sh
* [ ] mpv-bash-completion-git
* [ ] netatalk
* [ ] obkey-git
* [ ] profile-sync-daemon
* [ ] ruby1.9
* [ ] ruby1.9-bundler
* [ ] smartgit
* [ ] spotify
* [ ] ttf-monaco
* [ ] virtio-win
* [ ] wxgtk2.8
* [ ] wxpython2.8
* [ ] xfce4-dockbarx-plugin
* [ ] xfce4-indicator-plugin
* [ ] xfce4-taskbar-plugin
* [ ] xfce4-volumed
* [ ] yandex-browser-beta

@yuyichao:
* [ ] beignet-git
* [ ] ccnet-server
* [ ] coin
* [ ] devtools-cn-git
* [ ] julia-git
* [ ] julia-pkg-scripts
* [ ] libevhtp-seafile
* [ ] libsearpc
* [ ] med
* [ ] musescore-git
* [ ] oce-git
* [ ] openblas-lapack-git
* [ ] openlibm-git
* [ ] openspecfun-git
* [ ] python2-pivy
* [ ] python2-pyside2
* [ ] python2-shiboken2
* [ ] soqt
* [ ] seafile
* [ ] seafile-client
* [ ] seafile-server

@zsrkmyn:
* [ ] octave-signal

**Comment by axionl** [comment]
signal: https://github.com/archlinuxcn/repo/commit/0c0840d2ac239ac0d161e6e43f0f638de03df5ce

**Comment by Sasasu** [comment]
改了一个，如何测试呢 = =

**Comment by lilydjwg** [comment]
你可以 bump pkgrel 然后看看新包能不能出来。

**Comment by a-wing** [comment]
现在是推荐明确写出 `build_prefix: extra-x86_64` 还是不写 `build_prefix` 用默认的 `extra-x86_64` ？

**Comment by OriginCode** [comment]
2 pkgs above: https://github.com/archlinuxcn/repo/commit/95fc8722d1a64680a2002ee1f8e45e1841cf9634

同時有 ``multilib-archlinuxcn`` 也修改爲 ``multilib``

**Comment by lilydjwg** [comment]
> 同時有 ``multilib-archlinuxcn`` 也修改爲 ``multilib``

啊，我忘记考虑这个了……

-- 
Best regards,
lilydjwg

**Comment by SilverRainZ** [comment]
: ( Jekyll 的依赖树有点多，整个搬到 lilac.yml 里面好累啊。

**Comment by lijinpei** [comment]
gumbo-git, isl, polylib已改为extra-  https://github.com/archlinuxcn/repo/commit/760e23c5ce5903ae03aba0a824e2075e26ad03e0
barvinok依赖polylib, cockpit依赖pcp, pcp依赖systemtap无法更改.
BTW systemtap包的代码似乎不见了(

**Comment by lilydjwg** [comment]
@SilverRainZ 现在只需要写直接依赖了哦～
@lijinpei 为什么无法更改呢？

**Comment by lijinpei** [comment]
@lilydjwg 我的理解是如果cn源中的包只依赖"官方"源中的包，那么使用extra-，如果cn源中的包依赖cn源中的包，那么使用archlinuxcn-.

**Comment by lilydjwg** [comment]
依赖 cn 源里的包，也可以写 depends。而且这是推荐做法。

**Comment by lijinpei** [comment]
@lilydjwg 我没太弄明白，比如这个包pcp依赖cn源里的systemtap https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/pcp/PKGBUILD#L10
如果我extra-x86_64-build的话
```
==> Installing missing dependencies...
error: target not found: systemtap
```

**Comment by lijinpei** [comment]
所以是lilac才有这个加持，我手动打包是没有加持的吗?
(

**Comment by petronny** [comment]
@lijinpei 即使也不是吧

对lilac而言，指定depends后用`extra-`就可以了

然而对手动打包，其实也应该使用`extra-`, 有关依赖问题，应该手动通过
```sh
extra-x86_64-build -- -I /path/to/systemtap.pkg.tar.gz
```
来把依赖传进去。

不过如果你在某些情况下，不想写这么多的参数，并且熟知并准备好应对使用`archlinuxcn-`可能产生的各种bug，那就用吧。

**Comment by lilydjwg** [comment]
对啊，lilac 会使用那个字段，你手动打包就要自己加参数指定了。
不过手动打包的话，还是用 archlinuxcn-* 吧，反正是你自己确定依赖是不是在那里，够不够新。

**Comment by phoenixlzx** [comment]
* jdk: 7a00e8d0775605e27cfcb057567d290db90d8280
* ttf-google-fonts-git: 5be5440beafa31a9e229cadb0be65e6d076b53f6

**Comment by dctxmei** [comment]
betterlockscreen: https://github.com/archlinuxcn/repo/commit/1e6196a2784cafb1a557b2ee0456ad46fa22e73d

**Comment by OriginCode** [comment]
> 同時有 ``multilib-archlinuxcn`` 也修改爲 ``multilib``
> 啊，我忘记考虑这个了……
> […](#)
> -- Best regards, lilydjwg

所以是否要考慮一下重新篩選一次呢？

**Comment by lilydjwg** [comment]
嗯，我更新了一下。

**Comment by yan12125** [comment]
From https://github.com/archlinuxcn/repo/issues/990#issuecomment-480167123:

> build_prefix 现在可以直接省略掉了吧。。。大部分时候都和默认都是 `build_prefix: extra-x86_64`

Maybe let's remove `build_prefix: extra-x86_64` lines?

**Comment by SilverRainZ** [comment]
extra-x86_64 can be a default option here, but I don't think there is any benefit for removing the existing build_preifx.

**Comment by petronny** [comment]
@lilydjwg 求更新一下2L 的list，有好多包现在已经清理了

**Comment by colinkeenan** [comment]
I don't understand what this issue is asking me to do with `stapler-git`. Would somebody explain it to me in English?

**Comment by edward-p** [comment]
@colinkeenan 
We are trying to avoid using `*archlinuxcn*-build` in `lilac.yaml`. Instead, we will use `{extra,multilib}*-build` now. But you don't use lilac, do you?

**Comment by colinkeenan** [comment]
That's right - I don't use lilac.

**Comment by edward-p** [comment]
> That's right - I don't use lilac.

So, there's nothing you need to do. But at least add a `lilac.yaml` with `maintainers` info, so that lilac can know you're maintaining that package. In case, lilac can assign you automatically in corresponding issues.

---

``` yaml
maintainers:
  - github: colinkeenan
```

**Comment by lilydjwg** [comment]
@petronny updated.

**Comment by yan12125** [comment]
> `*archlinuxcn*-build` 相对于 extra- 和 multilib- 并没有什么优势，还有取代了官方源的包的可能。

I proposed https://github.com/yuyichao/devtools-cn/pull/2 to fix this issue. That pull request also fixes an security issue that package signing is not enforced when using `*archlinuxcn*-build`.

**Comment by yan12125** [comment]
@hubutui The package `python-pytorch-lightning` triggers a devtools bug https://bugs.archlinux.org/task/64265. You can either change `archlinuxcn-x86_64` to `extra-x86_64` or remove `repo_depends` from `python-pytorch-lightning/lilac.yaml` if you want to build this package before that bug is fixed.

**Comment by petronny** [comment]
```sh
$ grep -P '.*build_prefix.*archlinuxcn.*' */lilac.*
android-apktool/lilac.yaml:build_prefix: multilib-archlinuxcn
arm-linux-gnueabihf-glibc/lilac.yaml:build_prefix: archlinuxcn-x86_64
armv7l-linux-gnueabihf-glibc/lilac.yaml:build_prefix: archlinuxcn-x86_64
baka-mplayer-git/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
binfmt-qemu-static/lilac.yaml:build_prefix: archlinuxcn-x86_64
clion/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
eclipse-dltk-core/lilac.yaml:build_prefix: archlinuxcn-x86_64
eclipse-dltk-python/lilac.yaml:build_prefix: archlinuxcn-x86_64
emacs-evil/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
emacs-git/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
emacs-native-comp-git/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
emacs-undo-tree/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
fcitx5-pinyin-zhwiki/lilac.yaml:build_prefix: archlinuxcn-x86_64
genie-systemd/lilac.yaml:build_prefix: archlinuxcn-x86_64
glib2-static/lilac.yaml:build_prefix: archlinuxcn-x86_64
go-for-it-git/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
goland/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
google-earth-pro/lilac.yaml:build_prefix: multilib-archlinuxcn
grub2-theme-arch-leap/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
kindlegen/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
lector-git/lilac.yaml:build_prefix: archlinuxcn-x86_64
libevhtp-seafile/lilac.yaml:build_prefix: archlinuxcn-x86_64
libopenglrecorder/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
moonplayer-plugins/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
moonplayer-plugins/lilac.yaml:build_prefix: archlinuxcn-x86_64
mpv-bash-completion-git/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
netatalk/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
nvidia-lily/lilac.yaml:build_prefix: archlinuxcn-x86_64
obkey-git/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
pakku/lilac.yaml:build_prefix: archlinuxcn-x86_64
pcre-static/lilac.yaml:build_prefix: archlinuxcn-x86_64
pgcli/lilac.yaml:build_prefix: archlinuxcn-x86_64
plex-hama-bundle-git/lilac.yaml:build_prefix: archlinuxcn-x86_64
plex-media-server/lilac.yaml:build_prefix: archlinuxcn-x86_64
pm2ml/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
pyqt4/lilac.yaml:build_prefix: archlinuxcn-x86_64
qemu-user-static/lilac.yaml:build_prefix: archlinuxcn-x86_64
rpcs3-git/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
ruby-globalid/lilac.yaml:build_prefix: archlinuxcn-x86_64
ruby-pry/lilac.yaml:#build_prefix: archlinuxcn-x86_64
ruby-rails-dom-testing/lilac.yaml:build_prefix: archlinuxcn-x86_64
ryujinx-git/lilac.yaml:build_prefix: archlinuxcn-x86_64
scrcpy/lilac.yaml:build_prefix: archlinuxcn-x86_64
seafile-client/lilac.yaml:build_prefix: archlinuxcn-x86_64
seafile/lilac.yaml:build_prefix: archlinuxcn-x86_64
smartgit/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
spotify/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
sysdig-lily/lilac.yaml:build_prefix: archlinuxcn-x86_64
teamviewer/lilac.yaml:build_prefix: multilib-archlinuxcn
ttf-monaco/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
virtio-win/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
virtualbox-host-modules-lily/lilac.yaml:build_prefix: archlinuxcn-x86_64
vmware-horizon-client/lilac.yaml:build_prefix: archlinuxcn-x86_64
yandex-browser-beta/lilac.py:#build_prefix = 'archlinuxcn-x86_64'
```

我觉得我们把他们都强制改了吧

**Comment by lilydjwg** [comment]
只是建议避免，并不是不支持呀。这些还在用的，就随它们去吧。

**Comment by yuyichao** [comment]
我的两个-glibc包是工具链有循环依赖，改不了

**Comment by petronny** [comment]
ok...

如果大家已经达成共识了这个就关了？
