### ISSUE TITLE
[package request] dragon-drag-and-drop

### ISSUE THREAD

**Issue by tkkcc** [archlinuxcn/repo#1076]
### 问题类型 / Type of issues

* 软件打包请求 / package request
https://aur.archlinux.org/packages/dragon-drag-and-drop-git/

* 简述 / Brief Description
Simple drag-and-drop source/sink for X

* 主要语言和工具链 / Main Languages and Toolchains
c, gtk

* 上游链接 / Upstream Link
https://github.com/mwh/dragon

* 为何需要这个软件包 / Why Need This Package
配合ranger使用,减少自编译时间

**Comment by petronny** [comment]
等等等等，如何配合ranger使用啊？
ranger不是CLI的么，这个不是GTK的么

**Comment by tkkcc** [comment]
@petronny 
为了从ranger里拖拽图片等到其他gui,可以用这个
```
map <c-d> shell dragon-drag-and-drop -a -x %p
```

**Comment by petronny** [comment]
原来如此
