### ISSUE TITLE
Merge frp frpc frps

### ISSUE THREAD

**Issue by a-wing** [archlinuxcn/repo#1083]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* frp
* frpc
* frps

----
其实这几个都应该算 bin 包，关键是是我不了解 golang 的，就只能先这么放着了

这个应该用一个 pkgbuild 然后 split package

也希望 AUR 的维护者把 lilac 加上 Co-Maintainers 

两位怎么看：
@qwIvan
@vimsucks

**Comment by vimsucks** [comment]
已添加 lilac 为 Co-Maintainer

**Comment by petronny** [comment]
这种去AUR讨论吧？

**Comment by petronny** [comment]
AUR 讨论无果这边自行处理就是了
