### ISSUE TITLE
Orphaning some packages

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#1086]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* chromium-dev
* deepin-qq-im
* deepin-wine-tim
* electronic-wechat-git
* js-beautify-archlinuxcn

----

#1081 

弃置名下所有deepin wine相关、微信相关、firefox和chromium两大浏览器变种以及js-beautify-archlinuxcn

js-beautify-archlinuxcn 若还有人使用请留言。

**Comment by farseerfc** [comment]
我可以接手 firefox-kde-opensuse

**Comment by petronny** [comment]
> 我可以接手 firefox-kde-opensuse

好顶赞~

**Comment by petronny** [comment]
> /me electronic-wechat-git 用户。

我们还有`electronic-wechat`不是
其实我的想法是尽可能的扔掉不必要的git包，除非有明确的需求

**Comment by SilverRainZ** [comment]
> 我们还有electronic-wechat不是

哦哦原来有非 git 包啊，那没问题。

**Comment by heavysink** [comment]
有些release过慢的包还是可以考虑用git包的
