### ISSUE TITLE
virtualbox-ext-oracle: ask Oracle for permissions of redistribution

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#1087]
### 问题类型 / Type of issues
* 其它 / other

### 受影响的软件包 / Affected packages

* virtualbox-ext-oracle

----

As suggested by @petronny in https://github.com/archlinuxcn/repo/issues/1081#issuecomment-474215600.

PUEL does not allow binary redistribution. More details can be found on https://www.virtualbox.org/wiki/Licensing_FAQ. Here's a copy of the relevant Q&A entry:

> Can I redistribute the VirtualBox Extension Pack? 

> Not without a special license from Oracle. Neither the Personal Use and Evaluation License nor the Oracle VM VirtualBox Extension Pack Enterprise license allows you to distribute the VirtualBox Extension Pack binaries. Unless you obtain a separate license from Oracle, you may not make them available on your own websites or other mirrors or distribute them in any other way. If you are interested in obtaining a distribution license, please contact vbox_oem_sales_ww@oracle.com.

**Comment by yan12125** [comment]
教授對這個包也有興趣嗎？

As a record, here are previous discussions about virtual-ext-oracle

https://lists.archlinux.org/pipermail/aur-general/2010-December/012732.html
https://lists.archlinux.org/pipermail/aur-general/2010-December/012740.html
https://lists.archlinux.org/pipermail/aur-general/2010-December/012743.html

Two TUs rejected moving virtualbox-ext-oracle from AUR to [community] due to licensing issues.

**Comment by felixonmars** [comment]
I am not interested in requesting for a license myself. Anyone who are willing to may try, or we would have to remove the package.

**Comment by yan12125** [comment]
I found myself lazy on thinking about such non-technical issues, so I just go ahead and remove it.

/cc @petronny
