### ISSUE TITLE
[Out-of-date] gstreamer0.10 gstreamer0.10-base gstreamer0.10-base-plugins

### ISSUE THREAD

**Issue by capricorn2001** [archlinuxcn/repo#1093]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* gstreamer0.10
* gstreamer0.10-base
* gstreamer0.10-base-plugins

----

**Comment by xgdgsc** [comment]
我不记得维护过这个，应该可以删了吧

**Comment by lilydjwg** [comment]
gsc 是你吧？Packager 字段里写的。

有几个软件依赖它呢。其中 foxitreader @ykelvis 和 vmware-horizon-mmr @farseerfc 还有人要维护，wxgtk2.8 / wxpython2.8 / xfce4-volumed 倒是要被扔掉了。

**Comment by ykelvis** [comment]
那我来整吧, 那三个的依赖一直搞不上还在折腾
lilac.yaml里面的depends好像没被机器人算进去

**Comment by lilydjwg** [comment]
@ykelvis 为避免误解 depends 已经改名 repo_depends 了。pre-commit 没报错么？

**Comment by ykelvis** [comment]
bdc8613 8fb8c19 都好了
