### ISSUE TITLE
Package  Request: wine-osu

### ISSUE THREAD

**Issue by MarvelousBlack** [archlinuxcn/repo#1098]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

A compatibility layer for running Windows programs - Staging branch, optimized for audio low latency on osu! (by ThePooN)

* 主要语言和工具链 / Main Languages and Toolchains

* 上游链接 / Upstream Link

https://blog.thepoon.fr/osuLinuxAudioLatency/
https://aur.archlinux.org/packages/wine-osu/

* 为何需要这个软件包 / Why Need This Package

We need a low audio latency wine to run some rhythm game on linux.

**Comment by OriginCode** [comment]
Here's your OWN POT, go and catch!

**Comment by BruceZhang1993** [comment]
Here's your OWN POT, go and catch!

**Comment by pan93412** [comment]
Here's your OWN POT, go and catch!

**Comment by edward-p** [comment]
Here's your OWN POT, go and catch!
