### ISSUE TITLE
lilac needs to be updated since AUR migrated to AUR4

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#110]
Hi,
  AUR已经升级到[AUR4](https://aur4.archlinux.org)了。

由于，
```
Any changes to the AUR, made after 2015-06-08 will be lost!
```
lilac是不是也应该更改一下了？

另外，

```
the Arch User Repository is being migrated to a Git-based platform
```
所以lilac也应该很方便的自动提交更新到AUR4了

**Comment by farseerfc** [comment]
自動提交aur4如果要實現的話，需要每個包單獨的git repo，repo裏每個commit除了PKGBUILD之外還要有.SRCINFO，貌似不能（還沒找到簡單的方法）直接把這邊的repo的歷史導出到aur4的歷史。

**Comment by lilydjwg** [comment]
谁去看一下 AUR4 支不支持多个 ssh key？

AUR 的 API 有改变吗？如果没有的话 lilac 应该不需要做改变。

**Comment by lilydjwg** [comment]
@petronny 这样子对 Lilac 很不方便的，因为她得为每个包维护一个 git 仓库，虽然如果 AUR4 支持多 ssh key 的话授权会简单，但维护这些 git 仓库会大大地增加工作量。

**Comment by farseerfc** [comment]
@lilydjwg  aur4支持添加co-maintainer，然後每個maintainer一個key。我們大概可以讓一個人申請個 lilacbot 的用戶然後所有想讓 lilacbot 上傳的包都添加它爲 co-maintainer。

下載包的URL從
`https://aur.archlinux.org/packages/cu/cutegram/cutegram.tar.gz`
變成了
`https://aur4.archlinux.org/cgit/aur.git/snapshot/cutegram.tar.gz`
不知道別的地方有沒有變。遷移期結束之後大概域名會變回 `aur.archlinux.org` 。

**Comment by lilydjwg** [comment]
这个特性不错，不过工作量不小啊。

话说我们为什么不去 lilac 那边讨论呢？

**Comment by petronny** [comment]
Ugh..其实一开始我是想说由于AUR4的所有包都必须重新提交，所以可能会出现大规模包缺失或者更名了的问题，所有包都需要检查才能把lilac移到AUR4。所以就发这里来了。

**Comment by farseerfc** [comment]
現有的包的包名大概不會變？aur4上在過渡期間上傳的時候，只有元aur包的維護者有push權限，這一點可以限制包名不變吧。
aur4下載網址的變更現在lilac應該能去aur4的網址找了。或許nvchecker那邊也要跟着變一下？

**Comment by lilydjwg** [comment]
嗯。还不知道 nvchecker 要做怎样的修改呢。

**Comment by farseerfc** [comment]
https://aur4.archlinux.org/rpc.php?type=info&arg=cutegram
這個接口似乎沒變。只是對還沒遷移的包還沒結果。
對比：
https://aur.archlinux.org/rpc.php?type=info&arg=libstdc%2B%2B-doc
https://aur4.archlinux.org/rpc.php?type=info&arg=libstdc%2B%2B-doc
我們是等遷移期過去然後什麼都不改，還是現在兩個URL都試一下？
看aur維護者遷移之後會不會同時維護老aur了…我自己的包是兩邊都上傳了。
對遷移了之後只更新aur4的包來說現在老aur的接口會得到老版本吧。

**Comment by lilydjwg** [comment]
接口没变太棒了～那就都试试呗。

**Comment by petronny** [comment]
現有的包的包名会变啊，因为是重新上传的，有机会改一改自己觉得不好的名字。
比如`eclipse-wtp-wst`就变成了`eclipse-wtp`，不保证其他人会不会变。
并且可以抢别人的包，如果先提交的话。

AUR应该是不会再维护了，现在已经无法向AUR提交`package submissions, comments and votes`了。

**Comment by farseerfc** [comment]
遷移期間不能搶別人的包，只有原有aur的包的維護者有權限push。遷移期結束之後纔能搶。
[eclispse-wtp](https://aur.archlinux.org/packages/eclipse-wtp) 和 [eclispse-wtp-wst](https://aur.archlinux.org/packages/eclipse-wtp-wst) 是兩個不同的人提交的兩個相互衝突的包吧，前者 [遷過去了](https://aur4.archlinux.org/packages/eclipse-wtp) ，後者還沒遷移，並且後者被人標了 out-of-date 了。

**Comment by petronny** [comment]
咦这个包什么时候怎么AUR也有了。。。我上次看AUR里面还没有啊。。
不过这的确是2个完全不同的包，我看错了。

**Comment by lilydjwg** [comment]
变不变无所谓。就算没有 AUR4 想变的还是会变的嘛。

**Comment by lilydjwg** [comment]
已经在 https://github.com/archlinuxcn/lilac/issues/10 里更新了～
