### ISSUE TITLE
chromium-widevine

### ISSUE THREAD

**Issue by alfinbi** [archlinuxcn/repo#1104]
### 问题类型 / Type of issues

* 软件打包请求 / package request

chromium-widevine
----

* 简述 / Brief Description

（请在此填写）

A browser plugin designed for the viewing of premium video content

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

C, chromium

* 上游链接 / Upstream Link

（请在此填写）

https://www.widevine.com/

* 为何需要这个软件包 / Why Need This Package

（请在此填写）

Sometimes chromium user want to access premium content, and this package is needed in order to achieve that

**Comment by MarvelousBlack** [comment]
This package remove in 96ed184 , due to license concerns. see 7cd0e95 comments.
