### ISSUE TITLE
error: android-studio: signature from "lilac (build machine) <lilac@build.archlinuxcn.org>" is invalid

### ISSUE THREAD

**Issue by WordlessEcho** [archlinuxcn/repo#1109]
### 问题类型 / Type of issues
* 其它 / other

### 受影响的软件包 / Affected packages
* Android Studio

**Comment by edward-p** [comment]
> ### 问题类型 / Type of issues
> * 其它 / other
> 
> ### 受影响的软件包 / Affected packages
> * Android Studio

```
sudo pacman -S archlinuxcn-keyring
```

**Comment by WordlessEcho** [comment]
Already installed but problem still exist.

**Comment by BruceZhang1993** [comment]
- First check if your date time is correct
- Then check lilac key using command `pacman-key --list-keys lilac`

**Comment by WordlessEcho** [comment]
```
$ timedatectl
               Local time: Sat 2019-03-30 14:39:50 CST
           Universal time: Sat 2019-03-30 06:39:50 UTC
                 RTC time: n/a
                Time zone: Asia/Shanghai (CST, +0800)
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: no
```
```
$ pacman-key --list-keys lilac
gpg: Note: trustdb not writable
pub   rsa4096 2014-03-21 [SC]
      83F817213361BF5F02E7E124F9F9FA97A403F63E
uid           [  full  ] lilac (build machine) <lilac@build.archlinuxcn.org>
sub   rsa4096 2014-03-21 [E]
```

**Comment by edward-p** [comment]
> ```
> $ timedatectl
>                Local time: Sat 2019-03-30 14:39:50 CST
>            Universal time: Sat 2019-03-30 06:39:50 UTC
>                  RTC time: n/a
>                 Time zone: Asia/Shanghai (CST, +0800)
> System clock synchronized: no
>               NTP service: inactive
>           RTC in local TZ: no
> ```
> ```
> $ pacman-key --list-keys lilac
> gpg: Note: trustdb not writable
> pub   rsa4096 2014-03-21 [SC]
>       83F817213361BF5F02E7E124F9F9FA97A403F63E
> uid           [  full  ] lilac (build machine) <lilac@build.archlinuxcn.org>
> sub   rsa4096 2014-03-21 [E]
> ```

Your clock is about 20 minutes slower.

**Comment by BruceZhang1993** [comment]
```
$ LC_ALL=C pacman-key --verify android-studio-3.3.2.0-1-x86_64.pkg.tar.xz.sig
==> Checking android-studio-3.3.2.0-1-x86_64.pkg.tar.xz.sig...
gpg: assuming signed data in 'android-studio-3.3.2.0-1-x86_64.pkg.tar.xz'
gpg: Signature made Wed Mar  6 01:32:57 2019 CST
gpg:                using RSA key 83F817213361BF5F02E7E124F9F9FA97A403F63E
gpg: Note: trustdb not writable
gpg: Good signature from "lilac (build machine) <lilac@build.archlinuxcn.org>" [full]
```

GPG Signature of android-studio is valid.
If you still have issue, please join our group below:
- Telegram: https://t.me/archlinuxcn_group
- IRC: #archlinux-cn @ chat.freenode.net

**Comment by WordlessEcho** [comment]
> > ```
> > $ timedatectl
> >                Local time: Sat 2019-03-30 14:39:50 CST
> >            Universal time: Sat 2019-03-30 06:39:50 UTC
> >                  RTC time: n/a
> >                 Time zone: Asia/Shanghai (CST, +0800)
> > System clock synchronized: no
> >               NTP service: inactive
> >           RTC in local TZ: no
> > ```
> > ```
> > $ pacman-key --list-keys lilac
> > gpg: Note: trustdb not writable
> > pub   rsa4096 2014-03-21 [SC]
> >       83F817213361BF5F02E7E124F9F9FA97A403F63E
> > uid           [  full  ] lilac (build machine) <lilac@build.archlinuxcn.org>
> > sub   rsa4096 2014-03-21 [E]
> > ```
> 
> Your clock is about 20 minutes slower.

No, my clock is right.

**Comment by WordlessEcho** [comment]
Network problem.

**Comment by Sasasu** [comment]
That's why we using signature 😀

It protected you from evil just now
