### ISSUE TITLE
ccls-git need rebuild

### ISSUE THREAD

**Issue by SilverRainZ** [archlinuxcn/repo#1111]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* ccls-git

----

```
ccls: error while loading shared libraries: libclangIndex.so.7: cannot open shared object file: No such file or directory
```

I think it would be better to add an "alias: clang" in ccls-git's lilac.yaml.

**Comment by SilverRainZ** [comment]
@MaskRay I am interested in maintain ccls packages on both cn repo or aur. If you are too busy to deal with such package issue, I am glad to do it.

**Comment by lilydjwg** [comment]
There is no "clang" alias. You may want to add one in advance.

**Comment by SilverRainZ** [comment]
I thought the value after "alias" is a pkgname...

**Comment by lilydjwg** [comment]
我准备加个 clang 别名。不过它只取版本号的第一位就可以了吗？

**Comment by MaskRay** [comment]
@SilverRainZ I really appreciate your willingness to help me on packaging. Added you to co-maintainers of aur/ccls and aur/ccls-git.

**Comment by SilverRainZ** [comment]
@lilydjwg 看起来它的 so 确实只用了第一位。

**Comment by yssource** [comment]
@SilverRainZ How to install the rebuild version, since it happened to me also. 
 `ccls: error while loading shared libraries: libclangIndex.so.7: cannot open shared object file: No such file or directory`

**Comment by SilverRainZ** [comment]
@yssource Just wait for build machine to build it and you will receive update via `pacman -Syu`.
