### ISSUE TITLE
Use the release based not git based onedrive-abraunegg package

### ISSUE THREAD

**Issue by Modelmat** [archlinuxcn/repo#1115]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

[This](https://aur.archlinux.org/packages/onedrive-abraunegg/) is the release based version of onedrive-abraunegg-git package. The `-git` based version should be removed from the repo (as it it supposed to be built from git), and the onedrive-abraunegg package included instead.

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

D

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/onedrive-abraunegg/
https://github.com/abraunegg/onedrive

**Comment by dctxmei** [comment]
https://github.com/archlinuxcn/repo/commit/b5a837ac1f8318bad9d7c5057dd311cd7c7b2a20

**Comment by Sasasu** [comment]
In fact, `onedrive-abraunegg-git` in archlinuxcn tracking on abraunegg/onedrive's last release, not last commit ...
I will remove -git version since onedrive-abraunegg have a stable version.
