### ISSUE TITLE
CodeLite IDE Editor

### ISSUE THREAD

**Issue by Modelmat** [archlinuxcn/repo#1117]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description
`A cross platform C/C++/PHP and Node.js IDE written in C++`

* 主要语言和工具链 / Main Languages and Toolchains
C++

* 上游链接 / Upstream Link
https://aur.archlinux.org/packages/codelite-git/
http://www.codelite.org/

* 为何需要这个软件包 / Why Need This Package
`codelite` AUR package is out of date, `codelite-bin` is out of date and does not work, and `codelite-git` takes forever to build. Whilst I believe `-git` packages should not be provided by archlinuxcn, I believe it should be built from the `-git` source here and provided as `codelite` in this repo; basically it builds from git and provides the bin version for us.

**Comment by BruceZhang1993** [comment]
Which package do you prefer? `codelite` or  `codelite-git` ?

**Comment by hubutui** [comment]
震惊，Arch Linux 官方源里竟然没有这个包．codelite 这么冷门么？`-git` 包应该没有必要吧，就打最新的 release 就好了．或者 weekly release?

**Comment by BruceZhang1993** [comment]
> 震惊，Arch Linux 官方源里竟然没有这个包．codelite 这么冷门么？`-git` 包应该没有必要吧，就打最新的 release 就好了．或者 weekly release?

好像官方没有给 weekly release tag 或者 publish 源码... weekly build 只看到 bin 包
stable release 倒是落后 1k 多 commits 了...

**Comment by edward-p** [comment]
> > 震惊，Arch Linux 官方源里竟然没有这个包．codelite 这么冷门么？`-git` 包应该没有必要吧，就打最新的 release 就好了．或者 weekly release?
> 
> 好像官方没有给 weekly release tag 或者 publish 源码... weekly build 只看到 bin 包
> stable release 倒是落后 1k 多 commits 了...

诶？lilac也能有个weekly build功能就好了（我也想让kicad-git别每天都build

**Comment by Modelmat** [comment]
I would like to be able to use an up to date package. Whether it be the weekly release from https://downloads.codelite.org, or the `-git` package, I would like to be able to use it precompiled. Unfortunately none of the packages in the AUR provide this.

So, I would prefer this repo to provide a prebuilt `-git` package.

**Comment by BruceZhang1993** [comment]
#1119 is ready to be reviewed.

**Comment by BruceZhang1993** [comment]
`codelite-git` version `12.0.r1361.g8dde394f9-1` now available in archlinuxcn.

**Comment by lilydjwg** [comment]
@edward-p 有了： https://wiki.archlinuxcn.org/wiki/Lilac_%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E9%99%90%E5%88%B6%E6%89%93%E5%8C%85%E9%A2%91%E7%8E%87
