### ISSUE TITLE
RFP: ungoogled-chromium

### ISSUE THREAD

**Issue by outloudvi** [archlinuxcn/repo#1126]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

`ungoogled-chromium` 是一个去 Google 化的 Chromium 重打包版本。

* 主要语言和工具链 / Main Languages and Toolchains

Python, clang, LLVM, yasm, ninja etc. (From [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ungoogled-chromium) on AUR.)

* 上游链接 / Upstream Link

https://github.com/Eloston/ungoogled-chromium/

* 为何需要这个软件包 / Why Need This Package

1. 受众较广：此项目在 GitHub 有 6,900+ star。
2. 编译复杂：编译 target 超过 17,000 个。

**Comment by MarvelousBlack** [comment]
done
