### ISSUE TITLE
[Out of Date] gnome-shell-extension-dash-to-panel-git

### ISSUE THREAD

**Issue by zhmars** [archlinuxcn/repo#1127]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* gnome-shell-extension-dash-to-panel-git

----

**Comment by Xuanwo** [comment]
https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/gnome-shell-extension-dash-to-panel-git

@lilydjwg Looks like `lilac.yaml` is missing?

**Comment by lilydjwg** [comment]
Yes lilac.yaml is missing :-(

**Comment by SilverRainZ** [comment]
cc @swordfeng

**Comment by swordfeng** [comment]
I see. I thought I have all my repos updated though...
