### ISSUE TITLE
[Out of Date] icecat

### ISSUE THREAD

**Issue by misaka00251** [archlinuxcn/repo#1128]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* icecat [60.3.0-1 -> 60.3.0-3]

----

**Comment by Xuanwo** [comment]
https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/icecat

@colinkeenan Please fill the `lilac.yaml`, or we don't know who maintains the package.

**Comment by colinkeenan** [comment]
I am compiling it now. I just mistakenly thought I had already updated it (and even reported it updated on my last commit). I don't use lilac.

**Comment by colinkeenan** [comment]
Sorry, I am having a strange issue compiling this and don't have time to work on it. I stopped using icecat myself, so I won't be maintaining it anymore.

**Comment by SilverRainZ** [comment]
icecat has been dropped due to #1129.
