### ISSUE TITLE
Use qt5 for fqterm-git

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#1134]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* fqterm-git
----

Qt4已经很少人用了...要不改成qt5吧...
参见https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fqterm-qt5-git

**Comment by farseerfc** [comment]
Just pushed fqterm-qt5-git , will try some time and remove qt4 ver afterwards.
