### ISSUE TITLE
Package Request: miktex-git

### ISSUE THREAD

**Issue by 22dm** [archlinuxcn/repo#1135]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

MiKTeX is an up-to-date implementation of TeX/LaTeX and related programs.

* 主要语言和工具链 / Main Languages and Toolchains

C / C++ / Qt 5

* 上游链接 / Upstream Link

https://miktex.org/
https://github.com/MiKTeX/miktex
https://aur.archlinux.org/packages/miktex-git

* 为何需要这个软件包 / Why Need This Package

MiKTeX package manager will auto downloads and installs missing components, which is different from others like Tex Live. This allows you to keep your TeX installation as minimal as possible.

**Comment by heavysink** [comment]
Added
