### ISSUE TITLE
telegram-desktop-cn is out of date

### ISSUE THREAD

**Issue by bigeagle** [archlinuxcn/repo#114]
0.8.24 is released :)

**Comment by xgdgsc** [comment]
去aur页面Flag Out of Date就行，这里会跟aur更新。这个上游似乎是https://github.com/aphuse/tdesktop。

**Comment by farseerfc** [comment]
上游 aphuse 似乎在 github 更新了，我剛 push 了新打包好的到源裏，等源同步好應該就可以了。
aur上似乎的確沒更新，我改讓 lilac/nvchecker 跟蹤 github 的版本而不是 aur 的版本了。
