### ISSUE TITLE
Group lxqt packages to "lxqt-git"

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#1141]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* lximage-qt-git
* lxqt-about-git
* lxqt-admin-git
* lxqt-archiver-git
* lxqt-build-tools-git
* lxqt-config-git
* lxqt-globalkeys-git
* lxqt-notificationd-git
* lxqt-openssh-askpass-git
* lxqt-panel-git
* lxqt-policykit-git
* lxqt-powermanagement-git
* lxqt-qtplugin-git
* lxqt-runner-git
* lxqt-session-git
* lxqt-sudo-git
* lxqt-themes-git
* obconf-qt-git
* pcmanfm-qt-git
* qterminal-git
* screengrab-git
----

Could you please group them to "lxqt-git" by adding a "groups=("lxqt-git")" line? This will be of great convenience for people who want to use the GIT version of lxqt.

**Comment by yan12125** [comment]
Allowing users to install all LXQt packages is great, but I hesitate to add `groups=(lxqt-git)` to all PKGBUILDs as I'd like to keep PKGBUILDs in archlinuxcn the same as those on AUR (possibly different `pkgver=` lines for VCS packages), and some packages on AUR are not maintained/co-maintained by me (e.g., lxqt-build-tools-git, lxqt-panel-git).

How about creating a meta package instead?

**Comment by heavysink** [comment]
Yeah it is fine.

**Comment by yan12125** [comment]
I removed lxqt-build-tools-git and added some other LXQt software. lxqt-build-tools is for LXQt developers and packagers only, anyway.

**Comment by yan12125** [comment]
Done as the lxqt-git-meta package in https://github.com/archlinuxcn/repo/commit/69f1797ec9bf37d1fdf36ef2252cbfcb055f0057.
