### ISSUE TITLE
Add `repo_depends` for packages using qt4

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#1154]
### 问题类型 / Type of issues

* 打包错误 / packaging error

----

* 简述 / Brief Description

Qt 4

* 主要语言和工具链 / Main Languages and Toolchains

C++, Python, ...

* 上游链接 / Upstream Link

https://www.qt.io/

* 为何需要这个软件包 / Why Need This Package

qt4 is [dropped to AUR](https://aur.archlinux.org/packages/qt4/). Several packages in [archlinuxcn] depend directly or indirectly on it, so someone should  bring qt4 and other used qt4 packages into [archlinuxcn].

Here are potentially affected packages, generated with `rg -l -g PKGBUILD qt4 | sed 's|/PKGBUILD||' | sort` and briefly checked false positives:

- [x]  fcitx-lilydjwg-git (@lilydjwg considers dropping qt4 support)
- [x]  fcitx5-qt-git (<del>@farseerfc considers dropping qt4 support</del> done in https://github.com/archlinuxcn/repo/commit/164c27d322b1d33f0a9213aaed71f047f613fd09)
- [x]  fqterm-git (related: #1134, dropped by @farseerfc in e8d421ac17c22226458f39a72c348aa1fe0677fd)
- [x]  <del>google-earth (seems replaced by qt5-compatible google-earth-pro)</del> qt4, which is pulled by qtwebkit, is needed when `_attempt_fix=1` in PKGBUILD, which is not the case in this repo
- [x] <del>hardcode-tray-git</del> qt4, which is pulled by sni-qt-patched-git, is in optdepends.
- [x]  lib32-qt4 (orphaned in https://github.com/archlinuxcn/repo/issues/1146; later adopted by @heavysink)
- [x]  makehuman-hg (@heavysink switched to qt5-compatible makehuman-git in https://github.com/archlinuxcn/repo/commit/901adc5d12b4cdd39452c19cdc65afa992e4f587)
- [x]  python-quamash (Removed python-pyqt4 from optdepends array)
- [x]  <del>qgroundcontrol</del> (@a-wing) - not managed by lilac
- [x]  <del>qtadb</del> (@felixonmars) - not managed by lilac
- [x]  qtwebkit (`repo_depends` added in 6c0a23d67110d0dcd557c7a82c89aa6c978008c7; build issues fixed in a27ab85cdfb550f15d54d1831c98499318c0e2b9)
- [x]  <del>simage</del> (@yuyichao) - not managed by lilac
- [ ]  vidalia (@ykelvis)

Alternatively, if maintainers of those package decide to not maintain packages using Qt 4, I will modify the issue to make it an orphan request.

Assigning maintainers of affected packages. Sorry if I assigned the wrong person.

Update 2019/06/03: qt4 is ready in [archlinuxcn], please add the following section for packages using qt4:
```
repo_depends:
  - qt4
```

**Comment by lilydjwg** [comment]
If you put those package names under "Affected Packages" (and choose an issue type other than pkgreq) lilac can assign for you.

I prefer to remove qt4 support for fcitx-lilydjwg-git so if anyone will be affected, let me know.

**Comment by yan12125** [comment]
I was to use " packaging error", but later I thought it's not an error if qt4\* are added.

Actually assigning maintainers takes much less time than checking whether each package really depends on qt4 or not :)

**Comment by BruceZhang1993** [comment]
python-qumash opt depends on PyQt4 which depends on Qt4.  Should I remove PyQt4 from opt depends array or bring PyQt4 back? 🤣

**Comment by farseerfc** [comment]
I am considering of dropping `fcitx5-qt4-git` and `fqterm-git` instead. They all have qt5 version in repo now.

**Comment by heavysink** [comment]
...Why do they do that? There are still plenty of programs that depends on Qt4.

Anyway, Qt4 fails to compile (see the AUR page. IDK what to do). I am orphaning makehuman-hg since makehuman switches to git (I will create makehuman-git). I think google-earth has stopped developing and switched to google-earth-pro which depends on Qt5.

**Comment by yan12125** [comment]
> python-qumash opt depends on PyQt4 which depends on Qt4. Should I remove PyQt4 from opt depends array or bring PyQt4 back? 🤣

@BruceZhang1993: On AUR, only feeluown{,-git} and qhangups use python-quamash. All of them use Qt5, so it's safe to drop pyqt4 from optdepends. On the other hand, adding python-pyqt4 to [archlinuxcn] means you also need to to add python-sip-pyqt4 and phonon-qt4. If I were the maintainer of python-quamash, I prefer not to bury myself with those qt4 packages :)

**Comment by yan12125** [comment]
Thanks @heavysink! I've also changed the issue description to a TODO list and marked your package as done.

To others: please mark your packages as done if you either drop qt4 support or bring qt4 to [archlinuxcn].

**Comment by yan12125** [comment]
> Anyway, Qt4 fails to compile (see the AUR page. IDK what to do).

FWIW, https://aur.archlinux.org/packages/qt4/ now builds fine with `extra-x86_64-build`.

**Comment by heavysink** [comment]
Done. Let's wait and see whether it builds...

**Comment by yan12125** [comment]
Well, pyqt4 are not needed after python-quamash is updated and makehuman-git replaces makehuman-hg. Of course it's fine if you want to maintain them.

**Comment by yan12125** [comment]
> Done. Let's wait and see whether it builds...

You forgot to add lilac.py for new packages and thus lilac ignores them :O

FYI: after https://github.com/archlinuxcn/repo/issues/990, lilac.py will be optional, but not for now.

**Comment by yan12125** [comment]
qt4 is done. @heavysink Do you still want to add pyqt4 packages?

**Comment by yan12125** [comment]
Hmm pyqt4 failed to build

> 软件包 pyqt4 的 lilac.py 指定了 depends，然而其直接或者间接的依赖项 [Dependency(pkgdir=PosixPath('/home/lilydjwg/archgitrepo/archlinuxcn/python2-sip-pyqt4'), pkgname='python2-sip-pyqt4')] 并不在本仓库中。

(from lilac log file `2019-05-07T09:03:02`)

I guess using the `pkgbase: pkgname` format for repo_depends can fix it.

**Comment by Menci** [comment]
`fcitx-sogoupinyin` depends on `libfcitx-qt.so.0`, which is provided by previous community package `fcitx-qt4` but recently removed. Please add it.

**Comment by yan12125** [comment]
@Menci: See https://github.com/archlinuxcn/repo/issues/1000. The maintainer prefers fixing the package on AUR first.

**Comment by Menci** [comment]
@yan12125 Since `fcitx-sogoupinyin` is included in archlinuxcn, I think we should make sure it can be installed now.

**Comment by yan12125** [comment]
I agree. As fcitx-qt4 will likely be packaged by cuihaoleo, https://github.com/archlinuxcn/repo/issues/1000 is a better place for further discussions IMO.

**Comment by yan12125** [comment]
@heavysink Are you still working on fixing pyqt4? If not I'd suggest dropping all pyqt4-related packages. It's better to not keep broken packages there.

**Comment by yan12125** [comment]
Update 2019/06/03: qt4 is ready in [archlinuxcn], please add the following section for packages using qt4:
```
repo_depends:
  - qt4
```

**Comment by yan12125** [comment]
I've updated the list and mark packages which don't really need qt4 as completed, ping maintainers for remaining packagers and cleanup assignees.

**Comment by yan12125** [comment]
Ah, qgroundcontrol, qtadb and simage are not managed by lilac, so there is nothing to do for those packages, either.
