### ISSUE TITLE
pyenv is now in community

### ISSUE THREAD

**Issue by SilverRainZ** [archlinuxcn/repo#1162]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* pyenv

----

为啥 lilac 没自动开 issue？

**Comment by BruceZhang1993** [comment]
😄️ pyenv 居然才进 official .

**Comment by lilydjwg** [comment]
lilac 还没来得及开 issue 吧。

**Comment by SilverRainZ** [comment]
应该不是？ 从 nvchecker 发报错邮件给我已经过了 27 小时了，按说 lilac 该检查到了。

**Comment by lilydjwg** [comment]
哦，周末 lilac 不检查这些的 O(∩_∩)O~

**Comment by Xuanwo** [comment]
005 工作的 lilac …
