### ISSUE TITLE
tela-icon-theme-git需要更新PKGBUILD

### ISSUE THREAD

**Issue by Robosky** [archlinuxcn/repo#1168]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* tela-icon-theme-git
----
我是这个软件包的AUR维护者，由于上游变化PKGBUILD需要更新。

**Comment by axionl** [comment]
感谢提醒，已修复。
https://github.com/archlinuxcn/repo/commit/621ed22115780060dccd769d4f317f0b0ebf14e2

**Comment by Robosky** [comment]
我忘了把git放到makedepends里了，如果有需要请再更新一下……对不起😂

**Comment by axionl** [comment]
> 我忘了把git放到makedepends里了，如果有需要请再更新一下……对不起joy

https://github.com/archlinuxcn/repo/commit/071396e6c6eec477fa697f7d23cd88788c169866

已经修复，建议反馈上游修一下 Symlink 错误
