### ISSUE TITLE
请求添加dmenu-xft,paper-gtk-theme-git,paper-icon-theme-git,xflux

### ISSUE THREAD

**Issue by inkn** [archlinuxcn/repo#117]
这些aur有，但是国内速度慢，请求添加

**Comment by lilydjwg** [comment]
你可以提供 lilac.py 吗？

**Comment by inkn** [comment]
这些包应该都用最简单的lilac.py就行了。

#!/usr/bin/env python3
#
# This file is the most simple lilac.py file,
# and it suits for most packages in AUR.
#

from lilaclib import *

build_prefix = 'extra-x86_64'
pre_build = aur_pre_build
post_build = aur_post_build

if __name__ == '__main__':
  single_main()

**Comment by lilydjwg** [comment]
请 pull request，然后我点 Merge，没问题的话明天你就可以看到包了。

**Comment by inkn** [comment]
已经pull request，并且在nvchecker.ini里添加了这几个包，不知道有没有问题。

**Comment by lilydjwg** [comment]
有问题你会收到报错邮件的。
