### ISSUE TITLE
Anbox-module 在5.1内核中dkms无法通过编译

### ISSUE THREAD

**Issue by IsoaSFlus** [archlinuxcn/repo#1179]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

anbox-git (包含anbox-modules-dkms-git)

----

参考上游的讨论 https://github.com/anbox/anbox/issues/1130
已经有pr https://github.com/anbox/anbox-modules/pull/19 但还未合并。
由于archlinux内核较新（已经5.1了），所以率先受影响导致无法启动anbox。能否先patch一下？

**Comment by edward-p** [comment]
close by https://github.com/archlinuxcn/repo/commit/b668ee4ea9749c77c55212032c5f064d6fb11107
