### ISSUE TITLE
hplib-plugin 的版本号

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#1187]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* hplip-plugin
----

不是有个 `1:` 前缀么？我记得上一个版本是有的，这个版本就没了．而且 extra 仓库里的版本也是 `1:3.19.5`．

**Comment by edward-p** [comment]
https://aur.archlinux.org/cgit/aur.git/log/?h=hplip-plugin

**Comment by colinkeenan** [comment]
OK. I have uploaded it again with epoch=1 added to the PKGBUILD. It's been a while since I've updated hplip-plugin, so I don't remember doing that before. I must have though, because the previous version didn't have it either on AUR, but did on this repo.

**Comment by colinkeenan** [comment]
I understand now that epoch=1 was added then removed by the AUR maintainer, but we can't get updates automatically without adding it back in there. I don't think epoch can be temporary.

**Comment by edward-p** [comment]
> I understand now that epoch=1 was added then removed by the AUR maintainer, but we can't get updates automatically without adding it back in there. I don't think epoch can be temporary.

Agree.
