### ISSUE TITLE
請求打包：python-requests-cache

### ISSUE THREAD

**Issue by pan93412** [archlinuxcn/repo#1198]
### 问题类型 / Type of issues

* 软件打包请求 / package request
----

* 简述 / Brief Description
    #766 #767 有提到這個問題且曾經打包過，但該軟體包在 #838 遭廢棄。`netease-musicbox` 仍依賴著 `python-requests-cache`，且個人認為**可能有需要重新打包 `python-requests-cache` 的必要。**

    此 Issue 為 #1197 的重新改寫版本。

* 主要语言和工具链 / Main Languages and Toolchains
    Python library (2 or 3)

* 上游链接 / Upstream Link
    [AUR 連結 (git)](https://aur.archlinux.org/packages/python-requests-cache-git/)
    [PyPI 連結](http://pypi.python.org/pypi/requests-cache)
    [GitHub 檔案庫](https://github.com/reclosedev/requests-cache)

* 为何需要这个软件包 / Why Need This Package
    見〈简述 / Brief Description〉

**Comment by SilverRainZ** [comment]
cc @axionl

**Comment by axionl** [comment]
https://github.com/archlinuxcn/repo/commit/f88811e0f9433f742bf469d1d6da50a39c95ec44

**Comment by axionl** [comment]
打包出错了，晚上回来修
