### ISSUE TITLE
i-nex-git need rebuild

### ISSUE THREAD

**Issue by huyizheng** [archlinuxcn/repo#1201]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
*i-nex-git

----

请在此补充说明。
Please describe in detail here.

从源里安装的i-nex-git，它依赖于源里的libcpuid-git。
前者启动时报错“Cannot find dynamic library 'libcpuid.so.14.0.0'”，后者提供了libcpuid.so.14.0.1。

**Comment by heavysink** [comment]
fa2b345
已经trigger rebuild.
