### ISSUE TITLE
where is fcitx-sogoupinyin ?

### ISSUE THREAD

**Issue by dearfad** [archlinuxcn/repo#1202]
### 问题类型 / Type of issues

sudo pacman -S fcitx-sogoupinyin
error: target not found: fcitx-sogoupinyin

* 软件打包请求 / package request

fcitx-sogoupinyin

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/fcitx-sogoupinyin/

**Comment by cuihaoleo** [comment]
emm，因为 #1146 我的编辑失误，被 lilac 删了。

我在 Commit cd473dc 里 checkout 回来了，坐等重新编译以及同步吧……

**Comment by cuihaoleo** [comment]
唔，可能需要 @ykelvis 瞅瞅

> 
> 在成功地编译打包 {'scribus-svn', 'latte-dock-git', 'ppsspp-git', 'tela-icon-theme-git', 'mariadb-git', 'python-git', 'emacs-git', 'vlc-git', 'gimp-git', 'scummvm-git', 'https-everywhere-chrome-git', 'kdeconnect-git', 'chnroutes2-git', 'vim-lily', 'emacs-llvm-mode-git', 'gegl-git', 'rust-nightly', 'intel-opencl-sdk', 'linux-jwrdegoede', 'newaita-icons-git', 'profile-cleaner', 'alacritty-git', 'dosbox-x-git', 'wpa_supplicant-git', 'nvidia-beta', 'wlroots-git', 'ffmpeg-git', 'mkosi', 'firefox-nightly', 'tinc-pre'} 之后，fcitx-sogoupinyin 依旧依赖 {'qtwebkit'}。
> 
> 唔，这些包没能成功打包呢：{'qtwebkit'}
>

**Comment by yan12125** [comment]
> 唔，可能需要 @ykelvis 瞅瞅

Apparently `repo_depends` is missing. I reuse another ticket for this issue: https://github.com/archlinuxcn/repo/issues/1154.

**Comment by cuihaoleo** [comment]
Ok, 我先帮 @ykelvis 加了一下 qt4 的依赖

**Comment by yan12125** [comment]
Well, with `repo_depends`, qtwebkit still fails as the build log goes beyond 1GB, which is prohibited by lilac [1]. I have once used `-Wno-expansion-to-defined` to workaround that in aur/phantomjs [2]. That flag is for the bundled qtwebkit fork in phantomjs, and I guess it will be useful for qtwebkit itself, too.

[1] https://github.com/archlinuxcn/lilac/blob/c62fc3283e6cc27a987340ec01f532fca339e100/lilac2/cmd.py#L93
[2] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=phantomjs#n50

**Comment by cuihaoleo** [comment]
Thanks for the explanation. I added `-w` CFLAGS ( a27ab85 ) and now qtwebkit builds succesfully.

> Well, with `repo_depends`, qtwebkit still fails as the build log goes beyond 1GB, which is prohibited by lilac [1]. I have once used `-Wno-expansion-to-defined` to workaround that in aur/phantomjs [2]. That flag is for the bundled qtwebkit fork in phantomjs, and I guess it will be useful for qtwebkit itself, too.

**Comment by cuihaoleo** [comment]
编译成功了，请等待各镜像站同步。
