### ISSUE TITLE
[package request] waterfox

### ISSUE THREAD

**Issue by hosxy** [archlinuxcn/repo#1205]
### 问题类型 / Type of issues

* 软件打包请求 / package request

    - Waterfox
----

* 简述 / Brief Description

    Waterfox是基于 Mozilla Firefox 的第三方编译版本，针对64位机器进行优化。

* 主要语言和工具链 / Main Languages and Toolchains
    - C/C++，Rust
    - Clang，Cargo 
    - GTK2/GTK3

* 上游链接 / Upstream Link

    - https://www.waterfox.net/
    - https://github.com/MrAlex94/Waterfox

* 为何需要这个软件包 / Why Need This Package 

    Waterfox针对64位系统架构进行优化，并提高浏览器的速度。同时Waterfox还删除了 Firefox 的数据收集组件，并将继续支持 Firefox 57 起移除的XUL和XPCOM附加组件。
    这个包在AUR上的流行度还挺高：
![批注 2019-06-08 133754](https://user-images.githubusercontent.com/17108640/59142563-e646c780-89f2-11e9-9462-886040554bb5.png)

**Comment by dctxmei** [comment]
看起來沒問題。

不過這不正是側面說明了 Firefox 的高度可定製性麼？
要不要考慮使用 Firefox ESR 並通過 [user.js](https://github.com/pyllyukko/user.js) 來自行定製啊？可以看一下我的 [Fork](https://github.com/dctxmei/user.js) :)

**Comment by dctxmei** [comment]
https://github.com/archlinuxcn/repo/commit/71d9a0540147fa87d943e9361973775a9bcf515b
