### ISSUE TITLE
perl 5.30 rebuild

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#1210]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* [ ] gnome-perl
* [ ] gnome-vfs-perl
* [ ] gnomecanvas-perl
* [x] imagemagick-fftw
* [x] libsolv
* [x] perl-goo-canvas

----

Generator command:

```sh
pkgfile -R archlinuxcn -g -d '/usr/lib/perl5/5.28/*' | cut -d/ -f2 | sed 's/^/* [ ] /'
```

**Comment by AstroProfundis** [comment]
`shutter` is broken as well:
```Can't locate Gnome2.pm in @INC (you may need to install the Gnome2 module) (@INC contains: /usr/lib/perl5/5.30/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.30/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.30/core_perl /usr/share/perl5/core_perl) at /usr/bin/shutter line 37.
BEGIN failed--compilation aborted at /usr/bin/shutter line 37.```
I believe this could be fixed by rebuilding after `gnome-perl` is rebuilt.

**Comment by VOID001** [comment]
shutter is still failing because the dependency `gnome-vfs-nosmb` is no longer maintained by @colinkeenan. And I haven't got any reply from him now. See issue #1081

**Comment by yan12125** [comment]
All remaining packages are removed in 8801fa60a8be4bb7ad59fc29e6c85b95fab9c274.
