### ISSUE TITLE
[Package Request] gtk3-mushrooms

### ISSUE THREAD

**Issue by BruceZhang1993** [archlinuxcn/repo#1215]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

GTK3 library patched for classic desktops like XFCE, MATE.

* 主要语言和工具链 / Main Languages and Toolchains

Shell

* 上游链接 / Upstream Link

https://github.com/krumelmonster/gtk3-mushrooms
https://aur.archlinux.org/packages/gtk3-mushrooms

* 为何需要这个软件包 / Why Need This Package

Lots of tweaks for GTK3 to look better on classic desktops.

**Comment by LEXUGE** [comment]
Consider revise the sentence `Lots of tweaks for GTK3 to look better on classic desktops.`
Personally I will use `The package makes a lots of tweaks for GTK 3 look better on classic desktop` instead.
