### ISSUE TITLE
[package request] lightdm-slick-greeter

### ISSUE THREAD

**Issue by hosxy** [archlinuxcn/repo#1218]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

  一个 lightdm 的 greeter, 与之前 ubuntu 的 unity-greeter 很像

* 主要语言和工具链 / Main Languages and Toolchains

   vala

* 上游链接 / Upstream Link

  github：https://github.com/linuxmint/slick-greeter
  aur：https://aur.archlinux.org/packages/lightdm-slick-greeter/

* 为何需要这个软件包 / Why Need This Package

  lightdm 的 gtk greeter 不怎么好看，感觉这个外观还不错

**Comment by dctxmei** [comment]
https://github.com/archlinuxcn/repo/commit/a611fc26decca4717813a33cd53a1bf7ac4b4acf
