### ISSUE TITLE
virtualbox-ext-oracle out of date

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#1219]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages
virtualbox-ext-oracle
### 受影响的软件包 / Affected packages

* virtualbox-ext-oracle

----

**Comment by yan12125** [comment]
virtualbox-ext-oracle has been removed from this repository due to license issues. See https://github.com/archlinuxcn/repo/issues/1087 for previous discussions.
