### ISSUE TITLE
fcitx5 and related packages should use provides= and conflicts=

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#1220]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* fcitx5-git
* xcb-imdkit-git
* fcitx5-gtk-git
* fcitx5-qt-git
* fcitx5-chinese-addons-git

----

I made fcitx5-chewing-git to depend on community/fcitx5 instead of fcitx5-git (220596909eca558b314a1f5d9255afb2779ec255). Aforementioned packages should contain `provides=` and `conflicts=` declarations so that users can continue to use \*git packages.

**Comment by yan12125** [comment]
Noticed a minor issue in 164c27d322b1d33f0a9213aaed71f047f613fd09 - the Qt 5 plugin in [community] is called fcitx5-qt instead of fcitx5-qt5.

**Comment by farseerfc** [comment]
> Noticed a minor issue in 164c27d - the Qt 5 plugin in [community] is called fcitx5-qt instead of fcitx5-qt5.

Right ... We have qt4 in [archlinuxcn] but not in [community] . Will fix in next build.

**Comment by yan12125** [comment]
Well, commit bb0c2ece98dbdaa5dd25308d99d29282479322c2 is ignored by lilac as pkgrel remains the same...

**Comment by farseerfc** [comment]
Should be fixed by 9d3578b6bc3af52fbbe982e1bd68419eed17a2a1
