### ISSUE TITLE
pyqt4-common python2-pyqt4 missing required signature

### ISSUE THREAD

**Issue by junmoxiao** [archlinuxcn/repo#1227]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* pyqt4-common 
* python2-pyqt4

----
eyewitness and fern-wifi-cracker need above two packages

**Comment by SilverRainZ** [comment]
@heavysink signature of python2-pyqt4 is still missing.

**Comment by heavysink** [comment]
I think now it is all good...

**Comment by VanLaser** [comment]
I still have this issue:

`error: python2-pyqt4: signature from "Winston Wu <winstonwu91@gmail.com>" is unknown trust`

**Comment by lilydjwg** [comment]
@heavysink Your key has expired.

**Comment by heavysink** [comment]
I triggered rebuild.

**Comment by VanLaser** [comment]
Do I have to do something, other than wait?

**Comment by xiaozhu1337** [comment]
just disable the trust option
