### ISSUE TITLE
[out-of-date] plasma5-applets-active-window-control-git

### ISSUE THREAD

**Issue by rocka** [archlinuxcn/repo#1230]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* plasma5-applets-active-window-control-git

----

Upstream have been switched to https://phabricator.kde.org/source/plasma-active-window-control/ (or https://github.com/KDE/plasma-active-window-control/commits/master) on [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plasma5-applets-active-window-control-git) .

Version available in archlinuxcn was `1:r17.37b3b2c-1` but `1:r41.684b7b2-1` can already built with AUR PKGBUILD.

**Comment by SilverRainZ** [comment]
@colinkeenan

**Comment by SilverRainZ** [comment]
@colinkeenan

**Comment by colinkeenan** [comment]
Sorry I missed this last time. Since the github switched to KDE, I wasn't seeing that an update was needed with nvchecker. It's updated now, and I'm now checking the KDE/plasma-active-window-control github with nvchecker.
