### ISSUE TITLE
amarok missing dependency "taglib-extras"

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#1232]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* amarok

----

警告：无法解决 "taglib-extras"，"amarok" 的一个依赖关系
:: 因为无法解决依赖关系，以下软件包无法进行更新：
      amarok

:: 您想在本次更新中跳过上述软件包吗？ [y/N]

**Comment by farseerfc** [comment]
Sorry for using Chinese output, below is the English version of the same output:
```
:: Starting full system upgrade...
resolving dependencies...
warning: cannot resolve "taglib-extras", a dependency of "amarok"
:: The following package cannot be upgraded due to unresolvable dependencies:
      amarok

:: Do you want to skip the above package for this upgrade? [y/N]
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'taglib-extras' required by amarok
```

**Comment by frealgagu** [comment]
Missing dependency added to repo, build was successful.
