### ISSUE TITLE
Packaging error: wps-office

### ISSUE THREAD

**Issue by bobby285271** [archlinuxcn/repo#1237]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* wps-office

----

今早升级的时候发现应用程序菜单是多了金山 PDF 这玩意的，但是死活打不开...
后来发现 `/usr/bin/wpspdf` 不存在，而新版 DEB 包中的 `data.tar.xz` 是有这个文件的。
（应该没有其它大的变化了吧...?）

![Screenshot_20190706_092329](https://user-images.githubusercontent.com/20080233/60749700-3c962e80-9fd0-11e9-89b5-d8096f12be3c.png)

**Comment by Universebenzene** [comment]
……不看changelog的我……😭
还有什么问题还望大佬们多多指出😞

**Comment by Universebenzene** [comment]
修复已提交至AUR……
话说有没有菊苣帮忙测试下如果不打patch的话KDE用起来还有问题么（

**Comment by bobby285271** [comment]
> 修复已提交至AUR……

嗯 WPS PDF 能用了。

> 话说有没有菊苣帮忙测试下如果不打patch的话KDE用起来还有问题么（

### **Short：估计没问题。**
Long：我试着将 `add_no_kdialog_variable.patch` 移除，并将 `PKGBUILD` 中的 `source` 和 `sha1sums` 移除，再移除了这两行：
```bash
cd "${srcdir}"
patch -Np1 -i "${srcdir}/add_no_kdialog_variable.patch"
```
用常规方式安装，然后终端中使用 `/usr/bin/wps` 启动 WPS 文字，是可以打开本地文件选择对话框的，但其它的功能未作测试。 
![Screenshot_20190706_173725](https://user-images.githubusercontent.com/20080233/60754557-55750300-a015-11e9-9a13-aa2b4a5115b8.png)

**Comment by Universebenzene** [comment]
嗯……AUR上又更了一发，patch不打了，另外新版WPS里把icons/hicolor下各分辨率的apps文件夹里的图片都搞没了，有菊苣反应没图标……搞得我补习了一下午shell才把图标弄回来……（菜X如我
