### ISSUE TITLE
[package request] Dino IM

### ISSUE THREAD

**Issue by hosxy** [archlinuxcn/repo#1238]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

   Dino是一款使用XMPP协议，面向桌面用户的现代开源聊天客户端。它界面美观，同时支持众多XMPP特性。

* 主要语言和工具链 / Main Languages and Toolchains

    GTK3 / Vala

* 上游链接 / Upstream Link

    github：https://github.com/dino/dino
    AUR：https://aur.archlinux.org/packages/dino/

* 为何需要这个软件包 / Why Need This Package
   这个xmpp客户端功能强，UI设计也很漂亮，在 AUR 流行度也还挺高的。对 gnome/GTK  用户来说应该是个很好的选择。
![2019-07-06_12-30](https://user-images.githubusercontent.com/17108640/60751570-f352d880-9fe9-11e9-95a0-ad743a977539.png)

**Comment by lilydjwg** [comment]
Just tried and dissatistifed -_-

* it doesn't support proxy
* it doesn't support systray
* it doesn't support plugins

In short, it's too gnome3-y.

**Comment by hosxy** [comment]
@lilydjwg，额额额额......，用 KDE 的角度来看的话，的确是有这问题，毕竟GTK3写的，UI也是用的gnome那套，和 gnome3很配，但是 KDE 用户应该不会用这个，毕竟 gtk写的东西，对KDE/qt用户来说并不清真，其实我感觉kde钦定的xmpp客户端Kaidan并不比这个好

**Comment by OriginCode** [comment]
咱的源有 dino-git
```
[origincode]
Server = https://repo.origincode.me/repo/$arch
```
如有需要可暫用
（小聲（被打

**Comment by hosxy** [comment]
@OriginCode thank you啦，我来试试。终于不用装那些编译用的包啦。  (逃
其实主要是官方提供的 OBS 那边的包不能用，动态库错误， AUR 拉代码编译又要装好多用不上包，再加上aur流行度挺高的，所以来请求打包。

**Comment by lilydjwg** [comment]
@OriginCode 你直接收了呗。

**Comment by OriginCode** [comment]
等咱回家？（
（OC 源又要少一個可愛的包了（

**Comment by OriginCode** [comment]
7769970f79b455974a01492006a1418edb8ef5b2
