### ISSUE TITLE
package-reqest: gnome-breeze-git

### ISSUE THREAD

**Issue by 0x01f7** [archlinuxcn/repo#125]
AUR: https://aur.archlinux.org/packages/gnome-breeze-git/
Description: A GTK theme created to match with the new Plasma 5 Breeze.

**Comment by farseerfc** [comment]
Added, the binary package should appear after tonight's build.

**Comment by 0x01f7** [comment]
@farseerfc 
Thank you, i will test it tonight. 
Um, it seems a misspelling in [nvchecker.ini#L955], **dirruke1/gnome-breeze** -> **dirruk1/gnome-breeze** ?

[nvchecker.ini#L955]:https://github.com/archlinuxcn/repo/commit/16f6420db98a96b3d25beef461ab06808eb1725#diff-a22a5c031499450336efb16b527a5e4bR955

**Comment by farseerfc** [comment]
sorry it's a typo, fixed in the following commit https://github.com/archlinuxcn/repo/commit/cff785764976c84742c8f3d80ec2f502a69e9575
