### ISSUE TITLE
Create mpv-git-ffmpeg-git which is built against ffmpeg-git

### ISSUE THREAD

**Issue by 86423355844265459587182778** [archlinuxcn/repo#1250]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

Since fff7f9e, mpv-git in [archlinuxcn] must be used with ffmpeg-git, and it does not work if the stable version of ffmpeg is used.
I hope the maintainer can consider adding a variant of mpv-git (e.g. mpv-git-ffmpeg-git) which is built against ffmpeg-git (and states ffmpeg-git as a dependency in PKGBUILD), and then build mpv-git against ffmpeg stable. 

Related: #754 
CC: @petronny

**Comment by petronny** [comment]
fff7f9e4099d97e57a270d22b8a8df86912f062

It's already build against `ffmpeg-git` now. But you need to install `ffmpeg-git` to replace `ffmpeg` yourself.

> and states ffmpeg-git as a dependency in PKGBUILD

Sorry I won't do this unless the AUR upstream does. It's easy enough to install ffmpeg-git.

> mpv-git-ffmpeg-git) which is built against ffmpeg-git, and then build mpv-git against ffmpeg stable.

It's a little annoying that sometimes mpv-git needs ffmpeg and sometimes ffmpeg-git.
But mpv-git only builds agaist neither ffmpeg nor ffmpeg-git. Not both.
So mpv-git-ffmpeg-git and mpv-git can't exist and be up to date at the same time.
So we can only keep 1, mpv-git, and manually adjust the dependeny to the correct one.

**Comment by 86423355844265459587182778** [comment]
Oh, I found that mpv-player/mpv@1638fa7 requires a newer version of libavutil, so I see why we have to use ffmpeg-git.
