### ISSUE TITLE
Mailspring

### ISSUE THREAD

**Issue by Modelmat** [archlinuxcn/repo#1252]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

（请在此填写）`A beautiful, fast and maintained fork of Nylas Mail by one of the original authors.`

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）TypeScript

* 上游链接 / Upstream Link

（请在此填写）https://aur.archlinux.org/packages/mailspring/
https://github.com/Foundry376/Mailspring

* 为何需要这个软件包 / Why Need This Package

（请在此填写）Great email client.

**Comment by dctxmei** [comment]
https://github.com/archlinuxcn/repo/commit/40940b0a1f70f85930ec26203dc435933f5dc602
