### ISSUE TITLE
discord-canary 

### ISSUE THREAD

**Issue by kuasha420** [archlinuxcn/repo#1261]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

All-in-one voice and text chat for gamers that's free and secure.

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

C++ / glibc / libc++
（请在此填写）

* 上游链接 / Upstream Link

https://discordapp.com/
（请在此填写）

* 为何需要这个软件包 / Why Need This Package

You can have 2 instances of discord running on same system with discord canary and regular discord. I need it for multiseat usage. Also it receives update more often than discord, can be useful when things break on main version!!  Please consider!!! 
（请在此填写）

**Comment by dctxmei** [comment]
https://github.com/archlinuxcn/repo/commit/5e0ff251e54567a614fd17a78c5b902e8229f1a8
