### ISSUE TITLE
firefox-kde-opensuse need rebuild

### ISSUE THREAD

**Issue by ivlioioilvi** [archlinuxcn/repo#1270]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* firefox-kde-opensuse

----

Run firefox command and output the following error:

```
XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
libevent-2.1.so.6: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

**Comment by farseerfc** [comment]
Waiting for testing/libevent 2.1.11-1 to land in core

**Comment by ivlioioilvi** [comment]
That sounds depressing, i'm using firefox-developer-edition for the time being

**Comment by farseerfc** [comment]
Here is a rebuild version against testing: https://build.archlinuxcn.org/~farseerfc/firefox-kde-opensuse/firefox-kde-opensuse-68.0.1-4-x86_64.pkg.tar.xz

**Comment by yan12125** [comment]
libevent is moved to [core] [1]. However, firefox-kde-opensuse is still broken due to dav1d
```
$ readelf -d usr/lib/firefox/libxul.so | grep dav1d
 0x0000000000000001 (NEEDED)             共享函式庫：[libdav1d.so.1]

$ pacman -Ql dav1d | grep libdav1d
dav1d /usr/lib/libdav1d.so
dav1d /usr/lib/libdav1d.so.2
dav1d /usr/lib/libdav1d.so.2.0.0
```
This package appears to be another example for the necessity of [archlinuxcn-testing] (https://github.com/archlinuxcn/repo/issues/976).

[1] https://git.archlinux.org/svntogit/packages.git/commit/?h=packages/libevent&id=9a874baeacc33aca2a25e061039a990e1963abed

**Comment by Digitalone1** [comment]
I downgraded to

```
dav1d-0.3.0-1  ffmpeg-1:4.2-2  libevent-2.1.10-1
```

to get  **firefox-kde-opensuse** working.

**Comment by Digitalone1** [comment]
I had to downgrade also `qt5-webengine` to get akregator work. It's a break.

**Comment by farseerfc** [comment]
`firefox-kde-opensuse 68.0.1-6` now in repo. This should fix the broken ABI.
