### ISSUE TITLE
julia-git 长期打包错误

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#1273]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* julia-git

----

这个包都好久没有成功打包了吧，版本号也落后与官方仓库里的了．不维护的话建议丢掉．

**Comment by yuyichao** [comment]
https://github.com/archlinuxcn/repo/issues/696
https://github.com/JuliaLang/julia/pull/32712

**Comment by yuyichao** [comment]
And then dup of https://github.com/archlinuxcn/repo/issues/839
