### ISSUE TITLE
seafile requires an older version of libevent causing client to fail to start

### ISSUE THREAD

**Issue by sunziping2016** [archlinuxcn/repo#1276]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* `seafile`
----

运行`seaf-daemon`得到如下错误：
```
seaf-daemon: error while loading shared libraries: libevent-2.1.so.6: cannot open shared object file: No such file or directory
```

检查`/usr/lib`下的`libevent`版本，只有`/usr/lib/libevent-2.1.so.7`，

**Comment by yuyichao** [comment]
I'm hopting https://github.com/archlinuxcn/repo/commit/125a06c34c5329890194947d09e5162b39781a35 will do it. I lost track of the current update time/what triggers an update. I hope bumping pkgrel still triggers the update....
