### ISSUE TITLE
Rebuild needed: freshplayerplugin

### ISSUE THREAD

**Issue by 86423355844265459587182778** [archlinuxcn/repo#1277]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* freshplayerplugin

----
Rebuilding freshplayerplugin is needed due to the [libevent upgrade to 2.1.11](https://www.archlinux.org/packages/core/x86_64/libevent/).

**Comment by farseerfc** [comment]
lilac did a rebuild. close for now.
