### ISSUE TITLE
vscode in official repos now

### ISSUE THREAD

**Issue by Cool-Pan** [archlinuxcn/repo#1281]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* visual-studio-code-bin

----

In ``Community`` repository, the package name is ``code``.

**Comment by BruceZhang1993** [comment]
community/code is code oss which is a vscode without ms brand. But vscode-bin is a bin package which includes ms brand.

**Comment by farseerfc** [comment]
The 3 packages, `code` (aka. Code OSS) and `visual-studio-code-bin` and `vscodium-bin` contains slightly different content, therefore we have the later 2 in `[archlinuxcn]`. 
Closing this issue for now.
