### ISSUE TITLE
Packaging error: ekho

### ISSUE THREAD

**Issue by lizr2004** [archlinuxcn/repo#1282]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

`ekho`

----

ekho 的依赖 festival 已经更新到 2.5.0，而 ekho 仍需要 libFestival.so.2.4.0，要重新打包？
运行报错：
```
$ ekho
ekho: error while loading shared libraries: libFestival.so.2.4.0: cannot open shared object file: No such file or directory
```
目前包版本：
```
ekho 7.5-2
festival 2.5.0-1
```

**Comment by lizr2004** [comment]
ekho 还依赖 
```
libFestival.so.2.4.0
libestbase.so.2.4.1
libestools.so.2.4.1
```
这些库均属于旧版的 festival

**Comment by lizr2004** [comment]
extra/festival 中的 libFestival.so 指向 libFestival.so.2.4.0，
而 libFestival.so.2.4.0 已经不存在，取而代之的是 libFestival.so.2.5.0.0

疑似官方源中 festival 包打包错误

**Comment by farseerfc** [comment]
ekho 7.7.1-2 released after festival fixed the soname link in 2.5.0-2
