### ISSUE TITLE
Orphaning conky-nvidia

### ISSUE THREAD

**Issue by kaseiwang** [archlinuxcn/repo#1288]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* conky-nvidia

----

**Comment by kaseiwang** [comment]
Nvidia support has been enabled in conky-1.11.5-2 in [extra].
https://bugs.archlinux.org/task/62385
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/conky&id=2a4c9e29fa27e8fc6bc68aab153eeabc5f9c8247

**Comment by yan12125** [comment]
PKGBUILD of conky-nvidia is removed and 5b915e2a3afeacbbdc8b5442ae31a0c3d73213c4, and the package is no longer available in [archlinuxcn], either.
