### ISSUE TITLE
lxd 应该依赖 lxcfs

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#1289]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  lxd

----

lxd 应该依赖 lxcfs 吧，否则在容器内查看到的信息还是宿主的，而不是容器本身．比如限制了 CPU 核心数量之后没有正确显示．

**Comment by kaseiwang** [comment]
Please report to the aur maintainers. https://aur.archlinux.org/packages/lxd

**Comment by kaseiwang** [comment]
https://github.com/maikelwever/lxd/pull/28
