### ISSUE TITLE
package gnome-shell-extension-gsconnect seems broken

### ISSUE THREAD

**Issue by weearc** [archlinuxcn/repo#1300]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* gnome-shell-extension-gsconnect

----

This copy of extension does not work on gnome. But the one that download from extension.gnome.org do. And this one cannot connect to the device and repeat network error.

**Comment by SilverRainZ** [comment]
@PeterCxy 问题还存在么？

**Comment by weearc** [comment]
@SilverRainZ 问题已经不存在了似乎
