### ISSUE TITLE
[Package Request]  bitwarden

### ISSUE THREAD

**Issue by FlyGoat** [archlinuxcn/repo#1310]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

跨平台的密码管理工具。

* 主要语言和工具链 / Main Languages and Toolchains

Node.JS + Electron

* 上游链接 / Upstream Link

https://github.com/bitwarden/desktop
https://aur.archlinux.org/packages/bitwarden/

* 为何需要这个软件包 / Why Need This Package

较为实用的密码管理工具。

**Comment by dctxmei** [comment]
https://github.com/archlinuxcn/repo/commit/2d733d57a0a58c6eeb0ab1ddb6aac6795de94dd7
