### ISSUE TITLE
nvchecker.ini pkg option: use github rather than aur if possible?

### ISSUE THREAD

**Issue by 0x01f7** [archlinuxcn/repo#132]
nvchecker 似乎无法处理 AUR 的自动更新，例如 python2-powerline-git；鉴于其软件仓库存储于 GitHub 之上，能否改用 github 参数，以便构建出最新副本？

存储于 GitHub 的 AUR 列表如下（部分可能需要修改 PKGBUILD 文件）： 

+ [ ] dnsmasq-china-list-git, felixonmars/dnsmasq-china-list, [aur](https://aur.archlinux.org/packages/dnsmasq-china-list-git) ---- @felixonmars 
+ [x] nyancat-git, klange/nyancat, [aur](https://aur.archlinux.org/packages/nyancat-git) ---- @felixonmars 
+ [x] mitmproxy-git
+ [x] python-http-parser-git
+ [x] zsh-completions-git
+ [ ] python2-powerline-git, powerline/powerline, [aur](https://aur.archlinux.org/packages/python2-powerline-git) ---- @mapleray 
+ [ ] libqtxdg-git, baumgarr/nixnote2, [aur](https://aur.archlinux.org/packages/nixnote2-git) ---- @ykelvis 
+ [ ] libsysstat-git, lxde/libsysstat, [aur](https://aur.archlinux.org/packages/libsysstat-git) ---- @ykelvis 
+ [ ] obkey-git, stevenhoneyman/obkey, [aur](https://aur.archlinux.org/packages/obkey-git) ---- @ykelvis  
+ [ ] corebird-git, baedert/corebird, [aur](https://aur.archlinux.org/packages/corebird-git) ---- @ykelvis 
+ [x] ~~GGLucas/eminent~~ , [aur](https://aur.archlinux.org/packages/eminent-awesome34-git) ---- @farseerfc 
+ [x] goimports-git
+ [x] okular-backend-mupdf-git
+ [ ] mkinitcpio-colors-git, EvanPurkhiser/mkinitcpio-colors, [aur](https://aur.archlinux.org/packages/mkinitcpio-colors-git) ---- @colinkeenan  
+ [ ] setcolors-git, EvanPurkhiser/linux-vt-setcolors, [aur](https://aur.archlinux.org/packages/setcolors-git) ---- @colinkeenan 
+ [ ] numix-icon-theme-circle, numixproject/numix-icon-theme-circle, [aur](https://aur.archlinux.org/packages/numix-circle-icon-theme-git) ---- @colinkeenan 
+ [ ] numix-icon-theme-git, numixproject/numix-icon-theme, [aur](https://aur.archlinux.org/packages/numix-icon-theme-git) ---- @colinkeenan 
+ [ ] paper-gtk-theme-git, snwh/paper-gtk-theme, [aur](https://aur.archlinux.org/packages/paper-gtk-theme-git) ---- @inkn 
+ [ ] paper-icon-theme-git, snwh/paper-icon-theme, [aur](https://aur.archlinux.org/packages/paper-icon-theme-git) ---- @inkn 
+ [ ] spek-git, alexkay/spek, [aur](https://aur.archlinux.org/packages/spek-git) ---- @inkn 
+ [ ] baka-mplayer-git, u8sand/Baka-MPlayer, [aur](https://aur.archlinux.org/packages/baka-mplayer-git) ---- ???
+ [ ] pcmanfm-qt-git, lxde/pcmanfm-qt, [aur](https://aur.archlinux.org/packages/pcmanfm-qt-git) ---- ???
+ [ ] go-for-it-git, mank319/Go-For-It, [aur](https://aur.archlinux.org/packages/go-for-it-git) ---- ??? 
+ [ ] libwebqq-git, wxjeacen/libwebqqboost, [aur](https://aur.archlinux.org/packages/libwebqq-git) ---- ???
+ [x] pdf2htmlex-git, coolwanglu/pdf2htmlEX, [aur](https://aur.archlinux.org/packages/pdf2htmlex-git) ---- ???
+ [ ] pkgbuild-introspection-git, falconindy/pkgbuild-introspection, [aur](https://aur.archlinux.org/packages/pkgbuild-introspection-git) ---- ???
+ [ ] plasma-next-icons-git, NitruxSA/plasma-next-icons, [aur](https://aur.archlinux.org/packages/plasma-next-icons-git) ---- ???
+ [ ] qterminal-git, qterminal/qterminal, [aur](https://aur.archlinux.org/packages/qterminal-git) ---- ??? 
+ [ ] qtermwidget-git, qterminal/qtermwidget, [aur](https://aur.archlinux.org/packages/qtermwidget-git) ---- ??? 
+ [ ] telegram-git, vysheng/tg, [aur](https://aur.archlinux.org/packages/telegram-git) ---- ??? 
+ [ ] webogram-git, zhukov/webogram, [aur](https://aur.archlinux.org/packages/webogram-git) ---- ??? 
+ [ ] xiami-downloader-git, timothyqiu/xiami-downloader.git, [aur](https://aur.archlinux.org/packages/xiami-downloader-git) ---- ???
+ [ ] screengrab-git, QtDesktop/screengrab, [aur](https://aur.archlinux.org/packages/screengrab-git) ---- ???
+ [ ] systemtap-git, fche/systemtap, [aur](https://aur.archlinux.org/packages/systemtap-git) ---- ???

----------------------

附录：获取上述列表的相关代码：

```ruby
require 'httparty'
require 'inifile'


aur_in_github = []
file = IniFile.load('./nvchecker.ini')
file.each_section do |sec|
  next if sec == '__config__'

  print "processing: #{sec} :: "

  unless file[sec].key?('aur') && sec.end_with?('-git')
    puts "skip"
    next
  end

  resp = HTTParty.get('https://aur.archlinux.org/rpc.php', query: { type: 'info', arg: sec })
  unless resp.code == 200
    puts "resp_code_error :: #{resp.code}"
    next
  end

  body = JSON.parse(resp.body)
  unless body['type'] == 'info'
    puts "resp_type_error :: #{resp.body}"
    next
  end

  resultcount = body['resultcount']
  unless resultcount == 1
    puts "resp_rcnt_error :: #{resp.body}"
    next
  end

  uri = body['results']['URL']
  unless uri.start_with?('https://github.com/')
    puts "ignore :: #{uri}"
    next
  end

  puts "add :: #{uri}"
  aur_in_github << { name: sec, uri: uri }
end

puts ''; puts ''; puts '-' * 120; puts '-' * 120
aur_in_github.each do |aur|
  puts "+ #{aur[:name]}"
end
```

**Comment by 0x01f7** [comment]
BTW: 依据 Wiki 获取 new_ver.txt 存在一些错误信息，似乎在将软体移除仓库时未更新 nvchecker.ini 导致，信息如下：

```
[E 08-04 05:55:09.932 vcs:38] lib32-pypy-hg: command exited with 1.
[E 08-04 05:55:35.362 aur:39] AUR upstream not found for python2-pint
[E 08-04 05:55:35.586 aur:39] AUR upstream not found for python-split
[E 08-04 05:55:35.595 aur:39] AUR upstream not found for kivy
[E 08-04 05:55:35.755 aur:39] AUR upstream not found for obfsproxy
[E 08-04 05:55:35.979 aur:39] AUR upstream not found for openvpn-obfs-boypt
[E 08-04 05:55:36.375 aur:39] AUR upstream not found for sysdig
[E 08-04 05:55:36.936 aur:39] AUR upstream not found for qbittorrent
[E 08-04 05:55:37.712 aur:39] AUR upstream not found for python2-mimerender
[E 08-04 05:55:37.996 aur:39] AUR upstream not found for python-qiniu
[E 08-04 05:55:38.062 aur:39] AUR upstream not found for python2-mimeparse
[E 08-04 05:55:38.072 aur:39] AUR upstream not found for xfce4-whiskermenu-plugin
[E 08-04 05:55:38.594 aur:39] AUR upstream not found for xfce4-kdbleds-plugin
[E 08-04 05:55:38.646 aur:39] AUR upstream not found for isatapd
[E 08-04 05:55:38.660 aur:39] AUR upstream not found for python-pyside-tools
[E 08-04 05:55:38.712 aur:39] AUR upstream not found for python2-pyptlib
[E 08-04 05:55:39.302 aur:39] AUR upstream not found for scrapy
[E 08-04 05:55:39.600 aur:39] AUR upstream not found for python-braintree
[E 08-04 05:55:39.695 aur:39] AUR upstream not found for piep
[E 08-04 05:55:40.124 aur:39] AUR upstream not found for linux-mainline-header
[E 08-04 05:55:40.177 aur:39] AUR upstream not found for badvpn
[E 08-04 05:55:40.361 aur:39] AUR upstream not found for python2-phonenumbers
```

**Comment by farseerfc** [comment]
Fixed:
- [x] goimports-git
- [x] okular-backend-mupdf-git

**Comment by lilydjwg** [comment]
的确，VCS 包上游用 AUR 很难得到更新的。求 PR 啦=w=

那些报错的包如果不在仓库里的话就删掉吧。删包的时候没删 nvchecker 配置导致的……

**Comment by 0x01f7** [comment]
暂且没有细看 nvchecker 部分，下述只是推测，不知是否正确：

部分 VCS 包的构建脚本可能并不经常更新，这使得 aur 参数难以获得最新 git 副本，以至于用户从此仓库下载下来的可能是几个月前的数据，并且安装后无法从仓库获取更新，以至于最终还是得从 aur 自行构建？

鉴于速度和便利的考量，个人还是希望能够从仓库获取最新数据，而非自行构建。不过，改用 github 参数可能存在若干问题，主要出现在上游进行大版本更新，以致需要针对 aur 进行某些修正时，仓库维护者可能需要花费额外的工作做些检查。不过，多数情况应该还是没有问题的。（PS: 也许可以扩展 nvchecker 的 aur 做些额外工作来解决）

个人以为，并非上述所有包均适合从 aur 修改为 github，尤其是一些构建比较复杂的脚本，还是由当前对应仓库维护人员根据实际情况处理为好，谢谢。

**Comment by lilydjwg** [comment]
是对的。

lilac 的更新和更新检查是分开的。也就是是，完全可以在 github 上有更新的时候，去 AUR 取脚本。

反正包是谁维护的，谁决定怎么做。另外有计划做更新检查和通知，这样就不用手动报告 out-of-date 了。

**Comment by farseerfc** [comment]
eminent-awesome34-git (包括這兒和aur上的包)是停留在 awesome 3.4 能用的最後版本永遠不會更新了，所以不需要檢查更新。（其實不知道除了我還有誰在用它了）
