### ISSUE TITLE
ccls 错误

### ISSUE THREAD

**Issue by dogname** [archlinuxcn/repo#1323]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* ccls
* ccls-git
----

请在此补充说明。
Please describe in detail here.
ccls: error while loading shared libraries: libclangIndex.so.9: cannot open shared object file: No such file or directory
构建的机器上是不是打开了testing, 怎么clang都到9了

**Comment by SilverRainZ** [comment]
```
$ pacman -Si clang
软件库         : extra
名字           : clang
版本           : 9.0.0-2
描述           : C language family frontend for LLVM
...
```

**Comment by dogname** [comment]
我换了一个镜像站, 现在好了. neusoft 落后的有点多啊
