### ISSUE TITLE
fstrcmp missing PGP signature

### ISSUE THREAD

**Issue by gregoirefavre** [archlinuxcn/repo#1324]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* fstrcmp
----

I can't install fstrcmp due to invalid or corrupted package (PGP signature)

```
error: fstrcmp: signature from "Winston Wu <winstonwu91@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/fstrcmp-0.7.D001-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).、
```

**Comment by SilverRainZ** [comment]
Please follow the issue template.

**Comment by lilydjwg** [comment]
This package doesn't have a `lilac.yaml`...

**Comment by heavysink** [comment]
Just wait for it to update following AUR...

**Comment by SilverRainZ** [comment]
@heavysink you should bump pkgrel.

**Comment by heavysink** [comment]
> @heavysink you should bump pkgrel.

@SilverRainZ AUR side has a higher pkgrel so I think it will automatically update... I manually bumped it.

**Comment by gregoirefavre** [comment]
Thank you very much for all !!!
