### ISSUE TITLE
add lilac.yaml to remaining packages

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#1325]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* [ ] arm-linux-gnueabihf-binutils
* [ ] arm-linux-gnueabihf-glibc
* [ ] arm-linux-gnueabihf-linux-api-headers
* [x] auracle-git
* [ ] coccinelle
* [ ] freecad
* [x] fstrcmp (cc007092f7b3178bfbb96b7c932605af2f5532f8)
* [ ] gottet
* [x] gradio
* [ ] hplip-plugin
* [ ] ispin
* [ ] lib32-gdbm
* [ ] lib32-tk
* [ ] libgit2-julia
* [x] linux-lily
* [ ] llvm-julia
* [ ] llvm-svn
* [ ] lumina-desktop
* [x] nodejs-tiddlywiki
* [x] numix-circle-icon-theme-git
* [x] numix-icon-theme-git
* [ ] openvdb3
* [x] revoke-disputable-ca
* [x] simage (fa0916f3a0da7ab88e10f24a3b3cbb8672f3ed62)
* [ ] spin
* [x] stapler-git
* [x] supertux-git
* [x] systemd-rc-local
* [ ] uksmtools
* [ ] xfce4-mpc-plugin-update
* [x] xrdp
* [x] youtube-dl-git

----

Let's require that every package have its `lilac.yaml`. For packages not built by lilac, we can add `managed: false` to it as added by https://github.com/archlinuxcn/lilac/pull/118.

Also, after this issue is resolved, we'll want the pre-commit hook to check for this. Cc @farseerfc.

**Comment by yan12125** [comment]
I remember some of those packages are maintained by @yuyichao or @colinkeenan.

**Comment by farseerfc** [comment]
Now `pre-commit` can check for these packages with `--check-managed-false` option. We shall turn this on by default after this issue is resolved.

**Comment by yan12125** [comment]
@farseerfc The check can be turned on by default now :)

**Comment by farseerfc** [comment]
now checking this by default  🎊

**Comment by farseerfc** [comment]
@colinkeenan Please add a `lilac.yaml` that containing the maintainer infomation for the following packages:

- [ ] auracle-git
- [ ] stapler-git
- [ ] supertux-git

**Comment by colinkeenan** [comment]
OK. did that.
