### ISSUE TITLE
update freecad-oce

### ISSUE THREAD

**Issue by demolg** [archlinuxcn/repo#1326]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* freecad-oce
----

**Comment by yuyichao** [comment]
I assume you meant boost update.

**Comment by demolg** [comment]
@yuyichao , I could install the new version. but when I run `freecad`, it shows an error message "No module named 'StartGui' ".

**Comment by yuyichao** [comment]
Fixed.
