### ISSUE TITLE
wps-office 打包问题

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#1334]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* wps-office

----

文件 /usr/share/applications/appurl.desktop 引用了不存在的文件 /opt/kingsoft/wps-office/office6/parsecloudfiletool。

（总体而言这次检查看起来比上次要干净了许多呢。）

**Comment by petronny** [comment]
@Universebenzene

**Comment by Universebenzene** [comment]
咦？？还有这种事……我看看

**Comment by Universebenzene** [comment]
说起来这个东西是干啥的我也没弄清楚所以可能我就没去查……

**Comment by Universebenzene** [comment]
刚开始还觉得是路径错了……闹半天这玩意压根哪都没有……所以作法应该是把这个desktop给删了？还是说应该把 `Exec` 改成别的东西？

**Comment by lilydjwg** [comment]
要是找不到那个程序的话就删了吧。可以顺便再报告给 wps？

**Comment by Universebenzene** [comment]
把那个文件删了……然后邮件反馈了下 😷
