### ISSUE TITLE
Android Studio 缺少 which 依赖

### ISSUE THREAD

**Issue by xz-dev** [archlinuxcn/repo#1338]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* android-studio

----

![图片](https://user-images.githubusercontent.com/32761048/67163462-b4cb0900-f3a1-11e9-85a5-7de4bd6c169f.png)
android-studio 应该添加 which 为依赖
因为 which 已经被移除出 [base 元组](https://www.archlinux.org/groups/x86_64/base/)

**Comment by cuihaoleo** [comment]
namcap 跑了一下 [1]，可能还缺其他依赖。但我觉得这个算写 PKGBUILD 的锅吧，我先报到 AUR 上了。先凑合着用吧 = =

[1] https://cfp.vim-cn.com/cbf3N

**Comment by kordianbruck** [comment]
Should be fixed with the latest release for 3.5.2.0
