### ISSUE TITLE
orphaning s-tui

### ISSUE THREAD

**Issue by Sasasu** [archlinuxcn/repo#1339]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* s-tui

----

fix #1337

**Comment by lilydjwg** [comment]
呃， in-official-repo 的包不需要走这个流程的（因为 orphan 的流程很长，而 in-official-repo 不到一周就会自动被 lilac 处理掉）。

**Comment by SilverRainZ** [comment]
Q~Q

**Comment by Sasasu** [comment]
Q_Q

**Comment by yan12125** [comment]
Lilac already removed it in 6af3d8b772b7969eabd1b1ffc0a8fc4420f32694.
