### ISSUE TITLE
请求打包linuxqq

### ISSUE THREAD

**Issue by DennisZY** [archlinuxcn/repo#1343]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

linux版qq

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link

https://im.qq.com/linuxqq/download.html

* 为何需要这个软件包 / Why Need This Package

（请在此填写）

**Comment by OriginCode** [comment]
429fe98f80

**Comment by SilverRainZ** [comment]
吐槽一下包名…… linux 源里的包何苦叫 `xx-linux`，它自己提供的 pacman 包里不也是 `tencent-qq` ？

**Comment by edward-p** [comment]
> 吐槽一下包名…… linux 源里的包何苦叫 `xx-linux`，它自己提供的 pacman 包里不也是 `tencent-qq` ？

还好是 `xx-linux` 不是 `linux-xx` , 不然让人以为是个linux内核呢（x

**Comment by OriginCode** [comment]
因為有個 linuxqq 的包在 AUR，所以我只好起了個 qq-linux（Best regards!From Jack Wu <self@origincode.me>GPG Fingerprint: 0A5B AD44 5D80 C1CCWebsite: https://origincode.me/On Oct 26, 2019 11:51 PM, 谷月轩 <notifications@github.com> wrote:吐槽一下包名…… linux 源里的包何苦叫 xx-linux，它自己提供的 pacman 包里不也是 tencent-qq ？
