### ISSUE TITLE
vim-youcompleteme-git 上游更新，打包需修改

### ISSUE THREAD

**Issue by Universebenzene** [archlinuxcn/repo#1344]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* vim-youcompleteme-git

----

ycm最新的更新在ycmd的jedi下加了一个新的submodule [typeshed](https://github.com/davidhalter/typeshed/) ，目前打包里没有包含这个，结果实际使用的时候会报错有文件不存在。我也没经验打-git包的时候应该怎么管理submodule，也就只能提这么一句了，如果菊苣们能解决再好不过

说起来AUR上的维护者上次jdtls链接出问题的时候就没给修复所以我来这提的issue，这次又有新问题要修复，看AUR上无望所以我就又来这了……不过今天有人在AUR上提了Orphan request，也不知道多久之后能通过有人接手。是观望AUR上的状况还是咱这自己修复掉就菊苣们决定罢（

**Comment by Universebenzene** [comment]
@dctxmei 还是自己动手试了下……貌似能用：http://fars.ee/d5n1 这是diff

**Comment by dctxmei** [comment]
> @dctxmei 还是自己动手试了下……貌似能用：http://fars.ee/JBtw 这是diff

檢查了一下，缺了一個 source 呢，並且那個 cp 是多餘的，和前面 cp 的內容重複啦。

多謝幫助了，已在此基礎上添加：https://github.com/archlinuxcn/repo/commit/360b4605a9ac380676d9279b91f4490b720b7f10

**Comment by Universebenzene** [comment]
我好像还忘了改pkgrel来着……😷

**Comment by dctxmei** [comment]
> 我好像还忘了改pkgrel来着……😷

我也忘啦，所以追加了一個嘛：https://github.com/archlinuxcn/repo/commit/a41d5f3498483dda555dd21638763ef9d087f1cf
