### ISSUE TITLE
请求打包 texlive-most-doc 

### ISSUE THREAD

**Issue by specter119** [archlinuxcn/repo#1345]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Most TeXLive documentation 较全的 tex 文档 + 数据库

* 主要语言和工具链 / Main Languages and Toolchains

无

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/texlive-most-doc/

* 为何需要这个软件包 / Why Need This Package

texlive-core 的 texdoc 无法使用，本地文档和数据库好像都没有。我本地在装这个包，貌似很大的样子。

**Comment by hubutui** [comment]
这个包太大了吧．不如直接打个 `texlive-full`? see https://aur.archlinux.org/packages/texlive-full/

**Comment by specter119** [comment]
本地打完了，压缩后1.8G，压缩前2.5G，可以考虑么。

**Comment by hubutui** [comment]
https://build.archlinuxcn.org/~hubutui/ 你看看我打包好的，6G，未压缩．感觉太大了不适合．

**Comment by specter119** [comment]
@hubutui 装了 texlive-full 了，我觉得这个更香，要不我下需求打 texlive-full ？

**Comment by hubutui** [comment]
@specter119 我觉得打这个包丢 cn repo 不太合适啊，太大了啊。

**Comment by specter119** [comment]
好的
