### ISSUE TITLE
没有包的维护者 / maintainers without packages

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#1347]
### 问题类型 / Type of issues

* 其它 / other

----

The following maintainers in this organization have no packages currently, or haven't fill in `lilac.yaml` correctly:

* [ ] @houbaron
* [ ] @hzy199411
* [ ] @lijinpei
* [x] @qwIvan
* [ ] @slarsar
* [ ] @wicast

For people in the list:

Please show up and correct anything that was wrong, and speak up if you still want to maintain packages in the near future, or you will be removed from this organization. (You can still apply or contribute via pull requests in the future.)

The removal will take place after 30 days.

**Comment by yan12125** [comment]
Is this list correct? For example, `rg -l 'github: colinkeenan' | wc -l` prints 27.

**Comment by lilydjwg** [comment]
Oops, there seems to be a bug. Will check tomorrow...

**Comment by lilydjwg** [comment]
It's been fixed.

**Comment by qwIvan** [comment]
Added package to maintain: caddy httpry ptpython rofi-greenclip

**Comment by lilydjwg** [comment]
GitHub 权限和编译机用户已经移除。

请 @farseerfc 删除相关 gpg key。
请 @phoenixlzx 注销相关社区邮箱。

**Comment by farseerfc** [comment]
從 archlinuxcn-keyring 刪除了以下維護者的 key：

- [x] houbaron
- [x] hzy
- [x] lijinpei
- [x] wicast

沒有添加過以下維護者的 key：

- [ ] slarsar
