### ISSUE TITLE
systemtap: File conflict w/ glibc

### ISSUE THREAD

**Issue by outloudvi** [archlinuxcn/repo#1354]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* systemtap

----

The following files in archlinuxcn/systemtap 4.1-2 are conflicting with glibc 2.30-2:

* /usr/include/sys/sdt-config.h
* /usr/include/sys/sdt.h

Related log:
```
error: failed to commit transaction (conflicting files)
glibc: /usr/include/sys/sdt-config.h exists in filesystem (owned by systemtap)
glibc: /usr/include/sys/sdt.h exists in filesystem (owned by systemtap)
```

**Comment by SilverRainZ** [comment]
cc @ideal
