### ISSUE TITLE
Protobuf 3.10 rebuilds

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#1357]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* [x] anbox-git (8053ac840d343db5a8488b349d7fb4618090754c)
* [x] mcpelauncher-ui-git (manually rebuilt)
* [x] mxnet
* [x] mxnet-cuda
* [x] mxnet-cuda-mkl
* [x] mxnet-mkl
* [x] mysql
* [x] python-nvidia-dali
* [x] python-onnx
* [x] python-onnxruntime
* [x] python-onnxruntime-cuda
* [x] sysdig-lily

----

Packages that depend on `libproto{c,buf,buf-lite}.so.18` should be rebuilt to use `libproto{c,buf,buf-lite}.so.21` from protobuf 3.10.0. Note that protobuf might change SOVERSION in a patch release (e.g., 3.6.1 changes from `libprotobuf.so.16` to `libprotobuf.so.17` [1][2]). If you are going to use nvchecker for auto rebuilding, the current best practice might be rebuilding for all protobuf versions. See https://github.com/archlinuxcn/repo/commit/c180f539f2cd4da7115e55486d7601c8534d03d0#diff-9f50dc09cd4a694585d2bf4427fed517R14-R15 for an example.

[1] https://www.archlinux.org/todo/protobuf-361-rebuild/
[2] https://abi-laboratory.pro/index.php?view=timeline&l=protobuf

The package list is generated with my fork of who_depends_this_lib at https://github.com/archlinuxcn/misc_scripts/pull/15, using the following command:

```
$ env PYTHONPATH=$HOME/tmp/winterpy/pylib python who_depends_this_lib /data/repo/x86_64/archlinuxcn.files libproto protobuf
(..the checking process omitted...)
anbox-git-1:1121.33b0654-2: usr/bin/anbox (libprotobuf-lite.so.18)
criu-3.13-1: usr/lib/libcriu.so.2.0 (libprotobuf-c.so.1)
mcpelauncher-ui-git-v0.1.beta.1.r8.g92d286a-1: usr/bin/mcpelauncher-ui-qt (libprotobuf.so.18)
mxnet-1:1.5.1-4: usr/lib/libmxnet.so (libprotobuf.so.18)
mxnet-cuda-1:1.5.1-4: usr/lib/libmxnet.so (libprotobuf.so.18)
mxnet-cuda-mkl-1:1.5.1-4: usr/lib/libmxnet.so (libprotobuf.so.18)
mxnet-mkl-1:1.5.1-4: usr/lib/libmxnet.so (libprotobuf.so.18)
mysql-8.0.17-2: usr/lib/mysqlrouter/routing.so (libprotobuf-lite.so.18)
ocserv-0.12.4-1: usr/bin/ocserv (libprotobuf-c.so.1)
python-nvidia-dali-0.14.0-1: usr/lib/python3.7/site-packages/nvidia/dali/test/libcustomdummyplugin.so (libprotobuf.so.18)
python-onnx-1.5.0-4: usr/lib/python3.7/site-packages/onnx/onnx_cpp2py_export.cpython-37m-x86_64-linux-gnu.so (libprotobuf.so.18)
python-onnxruntime-0.5.0-1: usr/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so (libprotobuf.so.18)
python-onnxruntime-cuda-0.5.0-1: usr/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so (libprotobuf.so.18)
sysdig-lily-0.26.4-1: usr/bin/sysdig (libprotobuf.so.18)
vlc-git-4.0.0.r9902.gcf14bc8f63-1: usr/lib/vlc/plugins/stream_out/libstream_out_chromecast_plugin.so (libprotobuf-lite.so.21)
```

criu and ocserv depend on `libprotobuf-c.so`, which is from protobuf-c, and vlc-git is already rebuilt. They are not included in the package list.

As a reference, here is the TODO for official packages that needs to be rebuilt with protobuf 3.10: https://www.archlinux.org/todo/protobuf-39-rebuild/

**Comment by lilydjwg** [comment]
I've added a `protobuf` alias to lilac.

**Comment by snnn** [comment]
Hi,

We are going to release onnxruntime 1.0 this week. Would you help us if you have any issue with building it on Arch?  The source code is ready at: https://github.com/microsoft/onnxruntime/tree/rel-1.0.0

Thanks

**Comment by OriginCode** [comment]
0a74e22449

**Comment by yan12125** [comment]
Thanks everyone! All packages are triggered for rebuilds, while 3 of them failed. I unchecked them and added notes.

**Comment by OriginCode** [comment]
`mcpelauncher-ui-git` rebuild failed due to a dependency's building failure.

**Comment by yan12125** [comment]
Looks like the blocker is lib32-check? From lilac logs, I guess adding `vcs_update()` into `pre_build()` will fix it. I got a similar issue with python-onnxruntime and fix it in https://github.com/archlinuxcn/repo/commit/4786b9bc7f59af023381683748131914e5f7b62c#diff-e97fdd5b25b5602931b1ff13bd912233R11.

**Comment by OriginCode** [comment]
@yan12125 c63217d3f0

**Comment by yan12125** [comment]
Status of remaining packages:

* lib32-check: fails as keys in lilac.yaml has higher priority than those in lilac.py, and thus the fix https://github.com/archlinuxcn/repo/commit/c63217d3f074b645c91950aa6b4251fbe6bf942b has no effects.
* mysql: still synced from AUR, and thus the fix at https://github.com/archlinuxcn/repo/commit/072197620b8dc89c726b0257642b025c62546c55 is overridden
* anbox-git: https://github.com/anbox/anbox/pull/1280 seems a possible fix.

/cc @OriginCode @heavysink 

Sometimes I feel that there are too many magic tricks in lilac...

**Comment by lilydjwg** [comment]
There is a lot of things undocumented. Would you like to help with our wiki at https://wiki.archlinuxcn.org/wiki/ ?

**Comment by yan12125** [comment]
Indeed. I added two tricks mentioned above to https://wiki.archlinuxcn.org/wiki/%E6%89%93%E5%8C%85.

**Comment by OriginCode** [comment]
> Status of remaining packages:
> 
>     * lib32-check: fails as keys in lilac.yaml has higher priority than those in lilac.py, and thus the fix [c63217d](https://github.com/archlinuxcn/repo/commit/c63217d3f074b645c91950aa6b4251fbe6bf942b) has no effects.
> 
>     * mysql: still synced from AUR, and thus the fix at [0721976](https://github.com/archlinuxcn/repo/commit/072197620b8dc89c726b0257642b025c62546c55) is overridden
> 
>     * anbox-git: [anbox/anbox#1280](https://github.com/anbox/anbox/pull/1280) seems a possible fix.
> 
> 
> /cc @OriginCode @heavysink
> 
> Sometimes I feel that there are too many magic tricks in lilac...

b71749b877 Hmm

**Comment by MakiseKurisu** [comment]
anbox-git's fix is merged today.

**Comment by yan12125** [comment]
Great, and the rebuild passes https://build.archlinuxcn.org/packages/#/anbox-git. I'll mark anbox-git as done.

**Comment by yan12125** [comment]
Investigating build issues round 2:

* mysql: `aur_post_build()` fails if `aur_pre_build()` is not called. As the protobuf fix is applied on AUR (https://aur.archlinux.org/cgit/aur.git/commit/?h=mysql&id=843e0888d2febb0501ccc63b98f8ae5732a1b620), you may want to revert changes to `mysql/lilac.*` in 5b8abf79ca5082e379af7b53aec5502433d457cb and 072197620b8dc89c726b0257642b025c62546c55. @heavysink 
```
[I 11-17 03:22:05.902 lilac:100] building mysql
[E 11-17 03:36:58.605 lilac:163] packaging error
    Traceback (most recent call last):
      File "/home/lilydjwg/soft/lilac/lilac", line 120, in build_package
        bindmounts = BIND_MOUNTS,
      File "/home/lilydjwg/soft/lilac/lilac2/building.py", line 113, in lilac_build
        post_build()
      File "/home/lilydjwg/soft/lilac/lilac2/api.py", line 426, in aur_post_build
        git_rm_files(_g.aur_pre_files)
    AttributeError: 'types.SimpleNamespace' object has no attribute 'aur_pre_files'
```
* lib32-check: in update_pkgver_and_pkgrel(_G.newver), `pkgver=0.13.1-1` is written, so the build fails:
```
[D 11-15 03:47:48.157 cmd:49] running ['updpkgsums'], not using pty, showing output
==> 错误： pkgver 不允许包含冒号、斜杠、连字符或空白符。
==> ERROR: Failed to generate new checksums
```
For packages following AUR, `aur_pre_build()` should be used instead. @OriginCode

**Comment by lilydjwg** [comment]
Those `xxx_pre_build` and `xxx_post_build` should always be used in pairs, or unexpected things may happen.

**Comment by yan12125** [comment]
All package are done. mcpelauncher-ui-git is rebuilt manually

> mcpelauncher-ui-git-v0.1.beta.1.r12.g98ac412-2: usr/bin/mcpelauncher-ui-qt (libprotobuf.so.21)

As a side note, the lib32-check failure will be fixed once https://github.com/archlinuxcn/repo/issues/1391 is implemented and `lib32-check/lilac.*` switches back to `aur_pre_build`/`aur_post_build`.

**Comment by yan12125** [comment]
protobuf 3.11 is moved to [testing], and python-onnx will need https://github.com/onnx/onnx/pull/2482 to build.
