### ISSUE TITLE
[变更上游地址] fcitx 的仓库已经迁回github了

### ISSUE THREAD

**Issue by hosxy** [archlinuxcn/repo#1367]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* fcitx5-git
* fcitx5-anthy-git
* fcitx5-chinese-addons-git
* fcitx5-gtk-git
* fcitx5-mozc-git
* fcitx5-qt-git
* fcitx5-rime-git

----
done

* fcitx-lilydjwg-git
----
fcitx 的上游已经迁回了 github ，现在 gitlab 只是作为镜像了，希望将上游地址改回 github
由于受影响软件包较多，我列的可能不全。

补充：gitlab 仓库里的 fcitx5, fcitx5-chinese-addons设置了作为 github 的镜像，但是fcitx5-gtk，fcitx5-qt 却没有设置为 github 的镜像，以至于目前gitlab 仓库的fcitx5-gtk，fcitx5-qt等项目的代码是落后github上的。
由于目前 fcitx5 的dbus路径更改，fcitx5-gtk，fcitx5-qt急需拉取上游更新，重新编译

**Comment by yan12125** [comment]
Assigned myself for chewing-related IMEs.

**Comment by axionl** [comment]
The following packages have been migrated.

- fcitx5-git
- fcitx5-qt-git
- fcitx5-gtk-git
- fcitx5-rime-git
- fcitx5-mozc-git
- fcitx5-anthy-git
- fcitx5-chinese-addons-git

https://github.com/archlinuxcn/repo/commit/324c793b5c0af19d725d3799e73dd4a9e207c418
