### ISSUE TITLE
内核不能启动

### ISSUE THREAD

**Issue by alvin998179** [archlinuxcn/repo#1368]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
linux-zencjk can not boot up. And  grub-mkconfig can not make boot up menue for it .

请在此补充说明。
Please describe in detail here.

**Comment by edward-p** [comment]
`mkinitcpio` has been upgraded to 27-1.  Please update your `mkinitcpio`.

**Comment by OriginCode** [comment]
Please update your `mkinitcpio` to the latest version.
