### ISSUE TITLE
mentohust.service should not be marked as executable.

### ISSUE THREAD

**Issue by edward-p** [archlinuxcn/repo#1369]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* mentohust

----

`/usr/lib/systemd/system/mentohust.service` should not be marked as executable.

```
systemd[1]: Configuration file /usr/lib/systemd/system/mentohust.service is marked executable. Please remove executable permission bits. Proceeding anyway.
```

**Comment by SilverRainZ** [comment]
FYI: https://github.com/archlinuxcn/repo/commit/11c955e848183e8f0ec3bcf5654a36ef487019f0
