### ISSUE TITLE
Package request: autojump

### ISSUE THREAD

**Issue by Universebenzene** [archlinuxcn/repo#1371]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

  Shell 的快捷目录跳转工具（A faster way to navigate your filesystem from the command line）

* 主要语言和工具链 / Main Languages and Toolchains

   python

* 上游链接 / Upstream Link

   https://github.com/wting/autojump

* 为何需要这个软件包 / Why Need This Package

   询问了下菊苣们好像用 autojump 的并不少，但听官方的 Packager 讲貌似常出问题所以被官方仓库 drop 了……虽然不知道常出啥问题不过既然有人用就在 cn 这里打一下罢。官方的最后一版 [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/autojump/trunk/PKGBUILD?id=1ae4ee2ecfa318e9ff25a0777253b5d8ba356ef6)。另外还有个AUR上的 [autojump-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=autojump-git) 打包策略好像略有点不一样，菊苣们再行决定就好

**Comment by lilydjwg** [comment]
我目前的计划是先等 wting 的回应。如果他不准备解决文件乱放的问题的话，我打算用 Rust 重写一个完全兼容的版本。

**Comment by lilydjwg** [comment]
see also https://github.com/wting/autojump/issues/591

**Comment by SilverRainZ** [comment]
https://github.com/archlinuxcn/repo/commit/4c18a7720edf7f1595923d3a8e90b682b6ce4344
