### ISSUE TITLE
citra-qt-git conflicts with extra/fmt

### ISSUE THREAD

**Issue by smallst** [archlinuxcn/repo#1376]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* citra-qt-git

----

`archlinuxcn/citra-qt-git` want to install fmt files which owned by `extra/fmt`:
> error: failed to commit transaction (conflicting files)
citra-qt-git: /usr/include/fmt/chrono.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/include/fmt/color.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/include/fmt/compile.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/include/fmt/core.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/include/fmt/format-inl.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/include/fmt/format.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/include/fmt/locale.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/include/fmt/ostream.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/include/fmt/posix.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/include/fmt/printf.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/include/fmt/ranges.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/include/fmt/safe-duration-cast.h exists in filesystem (owned by fmt)
citra-qt-git: /usr/lib/cmake/fmt/fmt-config-version.cmake exists in filesystem (owned by fmt)
citra-qt-git: /usr/lib/cmake/fmt/fmt-config.cmake exists in filesystem (owned by fmt)
citra-qt-git: /usr/lib/cmake/fmt/fmt-targets-release.cmake exists in filesystem (owned by fmt)
citra-qt-git: /usr/lib/cmake/fmt/fmt-targets.cmake exists in filesystem (owned by fmt)
citra-qt-git: /usr/lib/pkgconfig/fmt.pc exists in filesystem (owned by fmt)

where `extra/fmt` is required by `archlinuxcn/fcitx5-git`

by the way, `aur/citra-qt-git` builds fine with `archlinuxcn/fcitx5-git`

**Comment by farseerfc** [comment]
`fmt` is a package in extra, shouldn't this issue be `citra-qt-git` conflicts with `fmt` ?
You should report to AUR maintainer for `citra-qt-git`, may let the said maintainer consider to depend on `fmt` instead of bundle in the `fmt` headers.
`citra-qt-git` is not in `archlinuxcn` so we have nothing can do about this.

**Comment by yan12125** [comment]
citra-qt-git _is_ in this repo

https://github.com/archlinuxcn/repo/blob/e6053aeb63f0144abaf65e34c15e501644f8743a/archlinuxcn/citra-git/PKGBUILD#L61

and it does not follow AUR.

**Comment by yan12125** [comment]
After https://github.com/archlinuxcn/repo/commit/b5bae259f36da92b38df4250e1f21549fc171d02, citra-qt-git is gone, and citra-git does not conflict with extra/fmt.

```
$ pacman -Fl citra-git 
citra-git usr/
citra-git usr/bin/
citra-git usr/bin/citra
citra-git usr/bin/citra-qt
citra-git usr/bin/citra-room
citra-git usr/share/
citra-git usr/share/applications/
citra-git usr/share/applications/citra.desktop
citra-git usr/share/icons/
citra-git usr/share/icons/hicolor/
citra-git usr/share/icons/hicolor/scalable/
citra-git usr/share/icons/hicolor/scalable/apps/
citra-git usr/share/icons/hicolor/scalable/apps/citra.svg
citra-git usr/share/man/
citra-git usr/share/man/man6/
citra-git usr/share/man/man6/citra-qt.6.gz
citra-git usr/share/man/man6/citra.6.gz
citra-git usr/share/mime/
citra-git usr/share/mime/packages/
citra-git usr/share/mime/packages/citra.xml
```
