### ISSUE TITLE
systemd-git conflicts with filesystem

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#1380]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* systemd-git

----

/usr/share/factory/etc/issue exists in both 'filesystem' and 'systemd-git'

Can try to fix like the official systemd:
  rm "$pkgdir"/usr/share/factory/etc/{issue,nsswitch.conf}
  sed -i -e '/^C \/etc\/nsswitch\.conf/d' \
    -e '/^C \/etc\/issue/d' "$pkgdir"/usr/lib/tmpfiles.d/etc.conf

**Comment by axionl** [comment]
https://github.com/archlinuxcn/repo/commit/31e69ae6ecb4a5b9fd45806cbc20cb9e5caecb7e
