### ISSUE TITLE
youtube-dl-git is out of date.

### ISSUE THREAD

**Issue by compliment** [archlinuxcn/repo#1382]
### 问题类型 / Type of issues
youtube-dl-git  is out of date. 2019.09.12.1.r0.e1f692f0b-1 in repo.

* 过期软件包 / out-of-date packages
youtube-dl-git 
### 受影响的软件包 / Affected packages
youtube-dl-git 
* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
youtube-dl-git 
----
I think it doesn't trigger because the PKGBUILD in aur never changes.

**Comment by colinkeenan** [comment]
done

**Comment by edward-p** [comment]
Also mention #1378 here.
