### ISSUE TITLE
fava dependency issues

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#1385]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* fava

----

* It needs python-jaraco
* I don't understand why it needs python-pip. Maybe it should be a makedepends?

请在此补充说明。
Please describe in detail here.

**Comment by Xuanwo** [comment]
已经反馈给 AUR 的维护者了

**Comment by wzyboy** [comment]
感谢反馈。

python-jaraco 是 python-cheroot 的缺失依赖，上游已有 bug report： https://bugs.archlinux.org/task/64181?project=5&string=python-cheroot

python-pip 已经移到 makedepends 了。
