### ISSUE TITLE
Upstream disappeared -- linux-apparmor

### ISSUE THREAD

**Issue by renyuneyun** [archlinuxcn/repo#1388]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  linux-apparmor-{,docs,headers}

----

曾經在AUR的這個包（`linux-apparmor`）消失了，而且我沒找到任何的關於它是爲什麼消失的消息。
最後一個版本是`5.1.14`；而今天（我得到lilac通知說它消失後不到一週）看，`core/linux`包已經是`5.3.11.1`。

有人有任何建議或者相關消息麼？
沒的話過一段只能棄置這個包了……
（其實我一直很奇怪，爲什麼`apparmor`進了`community`，但內核卻不……）

**Comment by yan12125** [comment]
From https://lists.archlinux.org/pipermail/aur-requests/2019-November/034958.html

> All official kernels support AppArmor for a year now. This package not
updated since June.

**Comment by renyuneyun** [comment]
問題解決，`core/linux`已經開啓`apparmor`支持。

見[此評論（archive.org上的存檔）](https://web.archive.org/web/20190522074125/https://aur.archlinux.org/packages/linux-apparmor/#comment-663288)以及[arch wiki](https://wiki.archlinux.org/index.php/AppArmor#Installation)。

唯一要注意的是需要額外設置參數。

**Comment by renyuneyun** [comment]
@yan12125 噫，我居然還晚了一步……
不過這個列表我還真沒注意過。
