### ISSUE TITLE
scp to build.archlinuxcn.org:repo not working?

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#140]
A couple days ago, I updated `drive` and `xfdashboard`. Those updates still aren't visible in http://repo.archlinuxcn.org/x86_64/. I tried to `scp` them again, and there is no error on the `scp`, but they still don't show up at http://repo.archlinuxcn.org/x86_64/.

**Comment by phoenixlzx** [comment]
The main repo server is down. I'm waiting for new service for setup.

**Comment by phoenixlzx** [comment]
The new sync server is ready, waiting for repopull to be deployed.
cc @lilydjwg
