### ISSUE TITLE
ruby-i18n out of date

### ISSUE THREAD

**Issue by poscat0x04** [archlinuxcn/repo#1403]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

*  ruby-i18n

----

ruby-i18n has an invalid dependency `ruby-concurrent-ruby`.

**Comment by SilverRainZ** [comment]
很早之前已经在 https://aur.archlinux.org/packages/ruby-i18n/#comment-715440 汇报过但是 maintainer 并没有响应。

@a-wing 看起来只改这边的 PKGBUILD 没有用，或者让源里的 ruby-i18n 不再 tack AUR？

**Comment by a-wing** [comment]
[ruby-sprockets](https://aur.archlinux.org/packages/ruby-sprockets/) 也有相同的问题。。

我想直接 tack gems

**Comment by a-wing** [comment]
才发现 `ruby-i18n` 原来是我的包。。。
- ruby-i18n 3fc1ef76a613abe04e581ab08d7e4b1a71fda475
- ruby-sprockets 56d3478acecd22cdc8ab0c227cdfca7a83ed6bd5

**Comment by lilydjwg** [comment]
On Sun, Nov 24, 2019 at 06:30:37PM -0800, metal A-wing wrote:
> 才发现 `ruby-i18n` 原来是我的包。。。
> - ruby-i18n 3fc1ef76a613abe04e581ab08d7e4b1a71fda475
> - ruby-sprockets 56d3478acecd22cdc8ab0c227cdfca7a83ed6bd5

这里只剩下你在用 Ruby 了吧。我之前还用 screenruler 后来实在更不动了……

-- 
Best regards,
lilydjwg
