### ISSUE TITLE
ulauncher 无法运行

### ISSUE THREAD

**Issue by johncyuan** [archlinuxcn/repo#1409]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages
       ulauncher
----

Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 27, in <module>
    from ulauncher.main import main
ModuleNotFoundError: No module named 'ulauncher'

**Comment by lilydjwg** [comment]
你没更新到 Python 3.8 吧？

**Comment by johncyuan** [comment]
> 你没更新到 Python 3.8 吧？

是没有更新到3.8
