### ISSUE TITLE
更新deepin wine时，汇入密钥失败

### ISSUE THREAD

**Issue by AkariMarisa** [archlinuxcn/repo#1413]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* deepin.com.qq.office
* deepin-wine
----
最近更新Deepin Wine与Deepin Tim的时候，总是提示需要汇入一个新的密钥，然而新密钥每次都无法汇入。更新过程报错如下:

```
:: 正在同步软件包数据库...
 core                                                                                            134.8 KiB  1389 KiB/s 00:00 [---------------------------------------------------------------------------] 100%
 extra                                                                                          1646.6 KiB  7.51 MiB/s 00:00 [---------------------------------------------------------------------------] 100%
 community                                                                                         4.7 MiB  4.16 MiB/s 00:01 [---------------------------------------------------------------------------] 100%
 multilib                                                                                        164.8 KiB  12.4 MiB/s 00:00 [---------------------------------------------------------------------------] 100%
 archlinuxcn                                                                                    1274.4 KiB  8.30 MiB/s 00:00 [---------------------------------------------------------------------------] 100%
:: 正在进行全面系统更新...
警告：anbox-git：忽略软件包升级 (1:r1121.33b0654-1 => 1:1126.0a49ae0-2)
警告：anbox-modules-dkms-git：忽略软件包升级 (1:r1121.33b0654-1 => 1:1126.0a49ae0-2)
警告：ovmf：本地 (1:r26214.20d2e5a125-2) 比 extra 的版本更新 (1:r26214.20d2e5a125-1)
正在解析依赖关系...
正在查找软件包冲突...
:: lib32-freetype2-infinality-ultimate 与 lib32-freetype2 有冲突。删除 lib32-freetype2 吗？ [y/N] y

软件包 (4) deepin-wine-2.18_22-2  deepin.com.qq.office-2.0.0_4-2  lib32-freetype2-2.10.1-1 [删除]  lib32-freetype2-infinality-ultimate-2.9.1-3

全部安装大小：  84.41 MiB
净更新大小：  -0.06 MiB

:: 进行安装吗？ [Y/n] 
(3/3) 正在检查密钥环里的密钥                                                                                                 [---------------------------------------------------------------------------] 100%
正在下载所需的密钥......
:: 匯入 PGP 金鑰 26D9876AC0719A0B，「Unknown Packager」？ [Y/n] 
错误：无法远程查找到密钥 "26D9876AC0719A0B"
:: 匯入 PGP 金鑰 26D9876AC0719A0B，「Unknown Packager」？ [Y/n] 
错误：无法远程查找到密钥 "26D9876AC0719A0B"
错误：所需的密钥不在密钥环中
错误：无法提交处理 (未预期的错误)
发生错误，没有软件包被更新。
```

**Comment by myl7** [comment]
Same on Manjaro.
Except for cleaning all keys, every method in https://wiki.archlinux.org/index.php/Pacman/Package_signing#Cannot_import_keys has been tried and none of them works.

**Comment by edward-p** [comment]
Those packages in repo are very suspicious. Signed by unknown key `BEA7E7644AE093AB557E521A26D9876AC0719A0B` and without packager info.

**Comment by lilydjwg** [comment]
Those packages were uploaded by @Skywol  with an unregistered key.

**Comment by Skywol** [comment]
我这有两个gpg的key但是我忘记记录的gpg是哪个了，lilac打包失败了我就手动传上去了，要不lilac重新打包一下吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"依云"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 中午1:36
收件人:&nbsp;"archlinuxcn/repo"<repo@noreply.github.com&gt;;
抄送:&nbsp;"skywol"<Skywol@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [archlinuxcn/repo] 更新deepin wine时，汇入密钥失败 (#1413)




Those packages were uploaded by @Skywol  with an unregistered key.

**Comment by lilydjwg** [comment]
pacman-key --list-keys skywol 就能看到是哪个了。你可以重新签一下名，然后把签名传上去。让 lilac 再打包也行，需要等而已。

**Comment by richwxd** [comment]
能不能更新一下，今天怎么也不能安装成功了

**Comment by edward-p** [comment]
> 能不能更新一下，今天怎么也不能安装成功了

请耐心等待重新打包或签名，等不及要滚包可以暂时跳过这两个包，先滚其他包：
`sudo pacman -Syu --ignore deepin-wine,deepin.com.qq.office`

**Comment by Skywol** [comment]
我原来在archcn记录的gpg签名私钥丢了，无法重新签了，我就说为什么签名是另一个的，新的gpg已经发送给依云了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Edward P"<notifications@github.com&gt;; 
发送时间: 2019年12月3日(星期二) 凌晨0:25
收件人: "archlinuxcn/repo"<repo@noreply.github.com&gt;; 
抄送: "skywol"<Skywol@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [archlinuxcn/repo] 更新deepin wine时，汇入密钥失败 (#1413)



 
能不能更新一下，今天怎么也不能安装成功了
  
请耐心等待重新打包或签名，等不及要滚包可以暂时跳过这两个包，先滚其他包：
 sudo pacman -Syu --ignore deepin-wine,deepin.com.qq.office
 
&mdash;

**Comment by richwxd** [comment]
就是说新签名了，快可以pacman了？

**Comment by farseerfc** [comment]
更新到 archlinuxcn-keyring 20191203 應該就有新 key 啦。

**Comment by ron159** [comment]
已经可以更新了，辛苦大佬们了

**Comment by genelocated** [comment]
```bash
sudo pacman -S archlinuxcn-keyring  
```
