### ISSUE TITLE
包签名无效

### ISSUE THREAD

**Issue by amitbha** [archlinuxcn/repo#1419]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* treesheets-git

----

请在此补充说明。

错误：treesheets-git: 来自 "lilac (build machine) <lilac@build.archlinuxcn.org>" 的签名无效
:: 文件 /var/cache/pacman/pkg/treesheets-git-r271.b737e40-1-x86_64.pkg.tar.xz 已损坏 (无效或已损坏的软件包 (PGP 签名)).
打算删除吗？ [Y/n] n
错误：无法提交处理 (无效或已损坏的软件包)

**Comment by edward-p** [comment]
包下坏了吧，删除重下试试？

**Comment by lilydjwg** [comment]
在 lilac 打包之后， @Rasphino 上传了同一版本的新包但是没有签名。

**Comment by Rasphino** [comment]
已更新 pkgrel
