### ISSUE TITLE
ptpython outdated

### ISSUE THREAD

**Issue by poscat0x04** [archlinuxcn/repo#1425]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

*  ptpython

----

outdated dependencies:
```
pkg_resources.DistributionNotFound: The 'prompt_toolkit<2.1.0,>=2.0.8' distribution was not found and is required by ptpython
```

**Comment by SilverRainZ** [comment]
2bd5a2c2a769f522a7b519e1e6451332ecd4f468
