### ISSUE TITLE
[Packaging] Unneeded depends on package solaar-git

### ISSUE THREAD

**Issue by BruceZhang1993** [archlinuxcn/repo#1427]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* solaar-git

----

Maybe some unneeded depends on this package.

`python  python-pyudev  python-gobject  pygtk  python-six libappindicator-gtk3(opt)`

community/solaar: `gtk3  libnotify  python-dbus  python-gobject  python-pyudev`
aur/solaar-git: `gtk3  libnotify  python-dbus  python-gobject  python-pyudev`

**Comment by yan12125** [comment]
pygtk is removed from [extra] [1] and thus solaar-git is now broken.

[1] https://git.archlinux.org/svntogit/packages.git/commit/?id=53f6f71a3102f498e37ce3b8c0635a8146a8d02a

**Comment by heavysink** [comment]
修好了，等更新吧

**Comment by yan12125** [comment]
Thanks. The fix is confirmed by lilac in e1cee10803ccd47947162843dc5f699af53bfa48.
