### ISSUE TITLE
Orphaning netease-cloud-music

### ISSUE THREAD

**Issue by PeterCxy** [archlinuxcn/repo#1428]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* netease-cloud-music

----
Orphaned in AUR too. If anyone is interested please take over. There are just too many strange issues about this package that I am not able to maintain anymore.

**Comment by BruceZhang1993** [comment]
接锅

https://github.com/archlinuxcn/repo/commit/48235fc6fb38764b86157c4f494616c58b617464
