### ISSUE TITLE
lindict-git was dropped from aur

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#143]
please change the following line in `nvchecker.ini` from
```
[lindict-git]
aur =
```
to
```
[lindict-git]
gitcafe=Jactry/LinDict
```
if you still want to maintain this package

**Comment by xgdgsc** [comment]
Sorry. I somehow missed this notification. I think this can be removed. Seems there is now an official youdao available http://cidian.youdao.com/index-linux.html

**Comment by lilydjwg** [comment]
@xgdgsc 不一样。官方版本包含不开源的二进制文件，只支持 x86 和 x86_64 平台的。
