### ISSUE TITLE
[packaging error] 有几个grub theme里面缺少 theme.txt

### ISSUE THREAD

**Issue by hosxy** [archlinuxcn/repo#1430]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* grub-theme-slaze-git
* grub-theme-stylish-git
* grub-theme-vimix-git

----

缺少文件 theme.txt ，主题无法使用

**Comment by dctxmei** [comment]
已進行重建：
https://github.com/archlinuxcn/repo/commit/ccca57a5cb52270091dd5868517511a13d39956c

請重新安裝軟件包 :)
