### ISSUE TITLE
ykdl-git 缺少依赖

### ISSUE THREAD

**Issue by chenjunyu19** [archlinuxcn/repo#1432]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* ykdl-git

----

ykdl 需要 `python-setuptools` 才能正常运行，但 `archlinuxcn/ykdl-git 1.6.3.r137.7b0482c-1` 包没有对其进行依赖。

**Comment by BruceZhang1993** [comment]
9a5fe9cb2949eb4e84a2ffc9a4ce3a5f245ae655
