### ISSUE TITLE
Tizonia: Cloud music from the Linux terminal

### ISSUE THREAD

**Issue by poscat0x04** [archlinuxcn/repo#1435]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

The most powerful cloud music player for the Linux terminal, with support for Spotify (Premium), Google Play Music (free and paid tiers), SoundCloud, YouTube, Plex servers and Chromecast devices.

* 主要语言和工具链 / Main Languages and Toolchains

Python, GCC

* 上游链接 / Upstream Link

http://tizonia.org

* 为何需要这个软件包 / Why Need This Package

**Comment by poscat0x04** [comment]
依赖比较多

**Comment by edward-p** [comment]
https://github.com/archlinuxcn/repo/commit/c3b07dca14333ea72061a4f755ba846c37ca43d5 等 lilac 下一波打包

**Comment by edward-p** [comment]
https://build.archlinuxcn.org/packages/#/tizonia-all
Close.
