### ISSUE TITLE
pid_children: dependency of lilac

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#1439]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

> A simple program outputs descendant process ids for each pid given on the command line

* 主要语言和工具链 / Main Languages and Toolchains

Rust

* 上游链接 / Upstream Link

https://github.com/lilydjwg/pid_children

* 为何需要这个软件包 / Why Need This Package

To make local installation of [lilac](https://github.com/archlinuxcn/lilac) easier.

Here is a PKGBUILD that makes lilac happy, but far from a good PKGBUILD:
```
pkgname=pid_children-git
pkgver=r9.d27761d
pkgrel=1
pkgdesc="A simple program outputs descendant process ids for each pid given on the command line"
arch=('x86_64')
depends=('gcc-libs')
makedepends=('git' 'rust')
conflicts=("pid_children")
provides=("pid_children=$pkgver")
url="https://github.com/lilydjwg/pid_children"
license=('custom:Unknown')
source=(git+https://github.com/lilydjwg/pid_children.git)
sha256sums=('SKIP')

pkgver() {
  cd pid_children
  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
  cd pid_children
  cargo build --release --locked
}

package() {
  cd pid_children
  install -Dm755 target/release/{kill_children,pid_children} -t "$pkgdir"/usr/bin
}
```

Some issues:
* Upstream does not declare a license
* What should be the owner/group and the permission of `kill_children`?

/cc @lilydjwg

**Comment by lilydjwg** [comment]
`kill_children` should be 4754 owned by root:pkg.

**Comment by lilydjwg** [comment]
License has been added to pid_children.
