### ISSUE TITLE
vim-youcompleteme-git: AUR 打包有修改，是否跟进一下？

### ISSUE THREAD

**Issue by Universebenzene** [archlinuxcn/repo#1445]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* vim-youcompleteme-git

----

ycm最近在 [AUR](https://aur.archlinux.org/cgit/aur.git/log/?h=vim-youcompleteme-git) 上的打包做了些修改，解除了对python2的依赖，咱们这是不是也跟进一下？
（话说这个问题我也不知道应该算过期还是算打包错误……先用这个类别提交了😷

**Comment by dctxmei** [comment]
已跟進 AUR：https://github.com/archlinuxcn/repo/commit/a2ffc2693f931b3662b3f2310cc7cc13968ddaf1
