### ISSUE TITLE
请求添加fcitx-qt4 到fcitx-sogoupinyin 的依赖中

### ISSUE THREAD

**Issue by louchenyao** [archlinuxcn/repo#1449]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

fcitx-sogoupinyin

----

感谢维护这个包。

需求：请求增加fcitx-qt4到这个fcitx-sogoupinyin的依赖里面。现有依赖不包含`libfcitx-qt.so` ，直接运行会报错。

类似问题被其他人反应过[https://www.jianshu.com/p/e8fff0c7c3d2](https://www.jianshu.com/p/e8fff0c7c3d2)

**Comment by yan12125** [comment]
Duplicate of https://github.com/archlinuxcn/repo/issues/1000 (a great issue number!)
