### ISSUE TITLE
请求打包 WPS 国内版

### ISSUE THREAD

**Issue by ShuiHuo** [archlinuxcn/repo#1451]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link

https://www.wps.cn/product/wpslinux

* 为何需要这个软件包 / Why Need This Package

国内版有中文语言包

**Comment by SilverRainZ** [comment]
中文语言包是指啥，拼写检查？archlinuxcn/wps-office 也有中文啊。

**Comment by ShuiHuo** [comment]
@SilverRainZ 就是将界面显示成中文那些文件（好像不应该用“语言包”这样的说法……）

**Comment by SilverRainZ** [comment]
@ShuiHuo archlinuxcn/wps-office 本来就支持中文的，感觉你给的链接和源里的一样。

**Comment by ShuiHuo** [comment]
@SilverRainZ 本来支持中文的，但 11.1.0.9080 版本国际版不带中文了，源里面的是国际版的链接。

**Comment by ShuiHuo** [comment]
国内版有：
1. 中文语言界面
2. 应用（团队功能和云空间）
3. 各类模板

**Comment by Universebenzene** [comment]
我的锅，刚发现国际版连登录功能都没了……原本国际版功能也挺全也有中文的，就是少了一堆mui文件，没想到这次缩水了这么多……
要不我上AUR再打一个cn版的然后再找菊苣放到这里？

**Comment by whour** [comment]
先下载个国内版，把中文的mui放到 `/usr/lib/office6/mui/`去

**Comment by Universebenzene** [comment]
[AUR](https://aur.archlinux.org/packages/wps-office-cn) 上提交了新的cn版包了。有菊苣原意打进cn源就直接加罢（当然顺便检查下更好
