### ISSUE TITLE
python-torchvision GPU 支持未生效

### ISSUE THREAD

**Issue by laper** [archlinuxcn/repo#1457]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*python-torchvision
----

依据 https://github.com/pytorch/vision Installation 部分：
> By default, GPU support is built if CUDA is found and torch.cuda.is_available() is true. It's possible to force building GPU support by setting FORCE_CUDA=1 environment variable, which is useful when building a docker image.

由于构建时 `torch.cuda.is_available()` 可能是 False，导致这种构建的包并不支持 GPU，编译时需要添加环境变量 `FORCE_CUDA=1`

**Comment by simonsmh** [comment]
@hubutui 你能更新pkgrel并重新打包上传吗？

**Comment by yan12125** [comment]
After f00e515, python-torchvision can no longer be used without CUDA (e.g., via python-pytorch-opt).

**Comment by simonsmh** [comment]
It might be better with a separate package like `python-torchvision-cuda` for different usage.
