### ISSUE TITLE
systemd[1]: Failed to start Repartition Root Disk

### ISSUE THREAD

**Issue by alvin998179** [archlinuxcn/repo#1476]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----
终端下输入dmesg为什么会出现这个? 什么原因? 怎样解决? 能开机也能正常使用.
请在此补充说明。
Please describe in detail here.

**Comment by oldherl** [comment]
你在问什么？
好像和本仓库没什么关系，先关了。有事欢迎来论坛或 irc/telegram 群组来讨论。

**Comment by alvin998179** [comment]
我不懂, 但我用其他内核不会出现这个? 你知道吗?

**Comment by alvin998179** [comment]
我以前同样的硬件环境下用linux-zen不会出现这个问题.

**Comment by oldherl** [comment]
此处不是 systemd 的 bug tracker。
如果你用的是 archlinuxcn 仓库中的某个内核，并且认为是它引发的问题，请指出所用内核包名和版本号。
