### ISSUE TITLE
请求打包fcitx5

### ISSUE THREAD

**Issue by alvin998179** [archlinuxcn/repo#1477]
### 问题类型 / Type of issues

* 软件打包请求 / package request
请求打包fcitx5
----

* 简述 / Brief Description

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link

（请在此填写）

* 为何需要这个软件包 / Why Need This Package

（请在此填写）

**Comment by oldherl** [comment]
fcitx5 尚未发布正式版。
本仓库已有 fcitx5-git 包。

**Comment by Rasphino** [comment]
community里不是已经有fcitx5了吗？
