### ISSUE TITLE
fakeroot-tcp 请支持aarch64架构

### ISSUE THREAD

**Issue by FlyInWind1** [archlinuxcn/repo#1480]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

aur已经添加了aarch64架构,但现在fake-tcp似乎只打包了x64的

* 主要语言和工具链 / Main Languages and Toolchains

c语言

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/fakeroot-tcp

* 为何需要这个软件包 / Why Need This Package

安卓下chroot跑arch,正常的fakeroot用不了,可以用tcp版,如果有打包好的fakeroot-tcp真是方便很多很多

**Comment by oldherl** [comment]
archlinuxcn 目前并不支持 aarch64 架构。aarch64 目录里面只有 any 包而已。

**Comment by lilydjwg** [comment]
也可以打，如果有人能打出来的话。交叉编译一个大约可行。

**Comment by FlyInWind1** [comment]
> archlinuxcn 目前并不支持 aarch64 架构。aarch64 目录里面只有 any 包而已。

我在aarch64下看到了aarch64专属的架构的包,
https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/aarch64/julia-git-1%3A0.7.0.DEV.2244.g4253e5622e-2-aarch64.pkg.tar.xz

如果我想将这个包收进源,有什么办法,找官方arm的维护者算一个

**Comment by MarvelousBlack** [comment]
```
$ Si fakeroot-tcp 
Repository      : archlinuxcn
Name            : fakeroot-tcp
Version         : 1.24-2
Description     : Tool for simulating superuser privileges,with tcp ipc
Architecture    : aarch64
URL             : http://packages.debian.org/fakeroot
Licenses        : GPL
Groups          : None
Provides        : fakeroot=1.24-2
Depends On      : glibc  filesystem  sed  util-linux  sh
Optional Deps   : None
Conflicts With  : fakeroot
Replaces        : None
Download Size   : 70.36 KiB
Installed Size  : 134.07 KiB
Packager        : Megumi Fox <i@megumifox.com>
Build Date      : Sat 01 Feb 2020 04:31:57 PM HKT
Validated By    : MD5 Sum  SHA-256 Sum
```
打好了，但因爲我對這個包沒有需求，我不能保證這個包是最新的。

**Comment by FlyInWind1** [comment]
> 也可以打，如果有人能打出来的话。交叉编译一个大约可行。



> 也可以打，如果有人能打出来的话。交叉编译一个大约可行。

如果可以收录,我可以用手机打

> ```
> $ Si fakeroot-tcp 
> Repository      : archlinuxcn
> Name            : fakeroot-tcp
> Version         : 1.24-2
> Description     : Tool for simulating superuser privileges,with tcp ipc
> Architecture    : aarch64
> URL             : http://packages.debian.org/fakeroot
> Licenses        : GPL
> Groups          : None
> Provides        : fakeroot=1.24-2
> Depends On      : glibc  filesystem  sed  util-linux  sh
> Optional Deps   : None
> Conflicts With  : fakeroot
> Replaces        : None
> Download Size   : 70.36 KiB
> Installed Size  : 134.07 KiB
> Packager        : Megumi Fox <i@megumifox.com>
> Build Date      : Sat 01 Feb 2020 04:31:57 PM HKT
> Validated By    : MD5 Sum  SHA-256 Sum
> ```
> 
> 打好了，但因爲我對這個包沒有需求，我不能保證這個包是最新的。

谢拉

**Comment by isjerryxiao** [comment]
@FlyInWind1 我有一个 [个人源](https://archlinux.jerryxiao.cc) 会收集一些常用的 aarch64 架构的包 你可以看看

**Comment by FlyInWind1** [comment]
> @FlyInWind1 我有一个 [个人源](https://archlinux.jerryxiao.cc) 会收集一些常用的 aarch64 架构的包 你可以看看

居然有yay，非常感谢。不过呢，我挂了梯才打开网站。不知道网络，宣传，或者放进archlinuxcn，有没有考虑

**Comment by isjerryxiao** [comment]
> > @FlyInWind1 我有一个 [个人源](https://archlinux.jerryxiao.cc) 会收集一些常用的 aarch64 架构的包 你可以看看
> 
> 居然有yay，非常感谢。不过呢，我挂了梯才打开网站。不知道网络，宣传，或者放进archlinuxcn，有没有考虑

另一个域名 国内可以正确解析  
https://archlinux.meson.cc/README.html

**Comment by FlyInWind1** [comment]
> > > @FlyInWind1 我有一个 [个人源](https://archlinux.jerryxiao.cc) 会收集一些常用的 aarch64 架构的包 你可以看看
> > 
> > 
> > 居然有yay，非常感谢。不过呢，我挂了梯才打开网站。不知道网络，宣传，或者放进archlinuxcn，有没有考虑
> 
> 另一个域名 国内可以正确解析
> https://archlinux.meson.cc/README.html

用上了，谢谢
