### ISSUE TITLE
[out-of-date] python2-pika

### ISSUE THREAD

**Issue by lanthora** [archlinuxcn/repo#1504]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* python2-pika

现在的[1.1.0](https://pika.readthedocs.io/en/1.1.0/)版本支持Python3

----

**Comment by yan12125** [comment]
python2-pika is dropped in 331b9d35f8809f1918a692d47f1c6f14a8d909c2.
