### ISSUE TITLE
[out-of-date] visual-studio-code-insiders

### ISSUE THREAD

**Issue by intrnl** [archlinuxcn/repo#1507]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* visual-studio-code-insiders

Insiders builds of Visual Studio Code usually updates on weekdays, and the AUR package is usually very late when it comes to updating the version to reflect that.

----

**Comment by poscat0x04** [comment]
Yep. I wasn't aware of this when adding the package. I think I'll drop this package since it seems to be impossible to use current date as version number in nvchecker.

**Comment by poscat0x04** [comment]
nvm It's possible. Will update the config file asap.

**Comment by poscat0x04** [comment]
lets see if this works: https://github.com/archlinuxcn/repo/commit/c3e69af7afaa79d4ef1ce0336b170a4e032e17c2

**Comment by poscat0x04** [comment]
Yep it worked
