### ISSUE TITLE
求讯飞输入法

### ISSUE THREAD

**Issue by liyuxi** [archlinuxcn/repo#1510]
### 问题类型 / Type of issues

* 软件打包请求 / package request
iflyime
----

* 简述 / Brief Description

讯飞输入法Linux版

* 主要语言和工具链 / Main Languages and Toolchains

未知（专有软件）

* 上游链接 / Upstream Link

http://mirrors.ustc.edu.cn/deepin/pool/non-free/i/iflyime/

* 为何需要这个软件包 / Why Need This Package

搜狗输入法年久失修

**Comment by weizhizhu** [comment]
我想知道现在arch上添加了没？？？？

**Comment by dctxmei** [comment]
> 我想知道现在arch上添加了没？？？？

沒有添加，看起來暫時沒有人願意接手。

可以考慮通過 IBus 或 Fcitx 來使用 RIME：

https://wiki.archlinux.org/index.php/IBus
https://wiki.archlinux.org/index.php/fcitx
https://wiki.archlinux.org/index.php/Rime

也可直接通過官方軟體倉庫安裝並使用 Fcitx5。

**Comment by weizhizhu** [comment]
但是我看yay上有iflyime的包啊  这个可以用吗？？？

**Comment by dctxmei** [comment]
> 但是我看yay上有iflyime的包啊 这个可以用吗？？？

看起來可行，但並不建議使用。

**Comment by weizhizhu** [comment]
那上面的会有什么问题吗？？ 还是你已经发现问题啦

**Comment by dctxmei** [comment]
> 那上面的会有什么问题吗？？ 还是你已经发现问题啦

首先，這是一個閉源軟體，這個 AUR 上的 PKGBUILD 也只是把 `iflyime_*_amd64.deb` 拿來解壓後再打包罷了。

其次，既然都用 Linux 了，使用閉源輸入法是完全沒有必要的，不過，這也僅僅是我的個人觀點。

Arch Linux 本就是一個注重實用性並且以用戶為中心的發行版，所以你完全可以自己決定是否安裝並使用 iflyime。

**Comment by weizhizhu** [comment]
好的 感谢

**Comment by liyuxi** [comment]
> > 那上面的会有什么问题吗？？ 还是你已经发现问题啦
> 
> 首先，這是一個閉源軟體，這個 AUR 上的 PKGBUILD 也只是把 `iflyime_*_amd64.deb` 拿來解壓後再打包罷了。
> 
> 其次，既然都用 Linux 了，使用閉源輸入法是完全沒有必要的，不過，這也僅僅是我的個人觀點。
> 
> Arch Linux 本就是一個注重實用性並且以用戶為中心的發行版，所以你完全可以自己決定是否安裝並使用 iflyime。

使用闭源输入法不就是为了他们的云词库嘛。。。不然我也觉得libpinyin挺好用的

**Comment by dctxmei** [comment]
> > > 那上面的会有什么问题吗？？ 还是你已经发现问题啦
> > 
> > 
> > 首先，這是一個閉源軟體，這個 AUR 上的 PKGBUILD 也只是把 `iflyime_*_amd64.deb` 拿來解壓後再打包罷了。
> > 其次，既然都用 Linux 了，使用閉源輸入法是完全沒有必要的，不過，這也僅僅是我的個人觀點。
> > Arch Linux 本就是一個注重實用性並且以用戶為中心的發行版，所以你完全可以自己決定是否安裝並使用 iflyime。
> 
> 使用闭源输入法不就是为了他们的云词库嘛。。。不然我也觉得libpinyin挺好用的

我個人傾向於養成自己的詞庫，如確有必要，我會導入從「清華大學開放中文詞庫」和「搜狗詞庫」收集好的內容，同時，也要去使用不同輸入方案，因此，我選擇使用 Rime :)

**Comment by dctxmei** [comment]
> > > > > 那上面的会有什么问题吗？？ 还是你已经发现问题啦
> > > > 
> > > > 
> > > > 首先，這是一個閉源軟體，這個 AUR 上的 PKGBUILD 也只是把 `iflyime_*_amd64.deb` 拿來解壓後再打包罷了。
> > > > 其次，既然都用 Linux 了，使用閉源輸入法是完全沒有必要的，不過，這也僅僅是我的個人觀點。
> > > > Arch Linux 本就是一個注重實用性並且以用戶為中心的發行版，所以你完全可以自己決定是否安裝並使用 iflyime。
> > > 
> > > 
> > > 使用闭源输入法不就是为了他们的云词库嘛。。。不然我也觉得libpinyin挺好用的
> > 
> > 
> > 我個人傾向於養成自己的詞庫，如確有必要，我會導入從「清華大學開放中文詞庫」和「搜狗詞庫」收集好的內容，同時，也要去使用不同輸入方案，因此，我選擇使用 Rime :)
> 
> 我認為主要是為了避免 LICENSE (Proprietary) 的問題而不打包（
> 我是覺得沒必要就這麼大力鼓動他去用 Rime，畢竟每個人的選擇不同

你好， OriginCode :)

對於輸入法來說，我個人僅熟悉 Rime，因此無法為其提供更為廣泛的建議，請見諒。

**Comment by weizhizhu** [comment]
我用了这个包大概一个礼拜了，起初是用搜狗输入法的，但是我有用微信、QQ等WINE应用的习惯，有些时候搜狗输入法就是突然发神经或者系统更新后就在用wine 微信 wine QQ 就输入不了中文，能让人抓狂的那种。但是用这讯飞输入法，暂时没发现有输入不了的现象。

**Comment by yan12125** [comment]
Per https://srf.xunfei.cn/linux/help/agreement.html, this software cannot be packaged in archlinuxcn. Feel free to leave a comment if the license is changed or an exception is granted to archlinuxcn and mirrors.
