### ISSUE TITLE
请求打包 迷雾通

### ISSUE THREAD

**Issue by ghos443** [archlinuxcn/repo#1512]
### 问题类型 / Type of issues

* 软件打包请求 / package request

迷雾通 geph

* 简述 / Brief Description

一个翻墙工具

* 主要语言和工具链 / Main Languages and Toolchains

不用编译

* 上游链接 / Upstream Link

https://dl.geph.io/desktop-builds/geph-linux64-3.4.4.tar.bz2

* 为何需要这个软件包 / Why Need This Package

客户端开源，免费版稳定性较好，可以备用防止失联，付费版本也还行

**Comment by poscat0x04** [comment]
这是个 binary package 吧..

**Comment by dctxmei** [comment]
> 这是个 binary package 吧..
> nvm 找到 source 了

不是二進制包哦。

參見：https://pincong.rocks/article/10365
源碼：https://github.com/geph-official/geph2

**Comment by dctxmei** [comment]
皆已打包：

* https://aur.archlinux.org/packages/geph-client/
* https://aur.archlinux.org/packages/geph-client-git/
* https://aur.archlinux.org/packages/gephgui-git/
