### ISSUE TITLE
[package request] plasma5-applets-window-appmenu

### ISSUE THREAD

**Issue by AliTajelsir** [archlinuxcn/repo#1517]
### 问题类型 / Type of issues
* 软件打包请求 / package request

plasma5-applets-window-appmenu

----

* 简述 / Brief Description

A Plasma 5 applet that shows the current window appmenu in your panels

* 主要语言和工具链 / Main Languages and Toolchains

1. Qt 
2. KF5 
3. Plasma

* 上游链接 / Upstream Link

https://github.com/psifidotos/applet-window-appmenu

* 为何需要这个软件包 / Why Need This Package

To use Latte Dock in a Unity or MAC style, and it works better with [plasma5-applets-window-buttons](https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/plasma5-applets-window-buttons) (already in the repo)

**Comment by edward-p** [comment]
Close via 27e4b55e88723f05fdba016d4366c032bf365180
