### ISSUE TITLE
[package request] plasma5-applets-window-title

### ISSUE THREAD

**Issue by AliTajelsir** [archlinuxcn/repo#1518]
### 问题类型 / Type of issues

* 软件打包请求 / package request

plasma5-applets-window-title

----

* 简述 / Brief Description

A Plasma 5 applet that shows the current window title and icon in your panels

* 主要语言和工具链 / Main Languages and Toolchains

1. Plasma
2. KDeclarative

* 上游链接 / Upstream Link

https://github.com/psifidotos/applet-window-title

* 为何需要这个软件包 / Why Need This Package

To use Latte Dock in a Unity or MAC style, and it works better with [plasma5-applets-window-buttons](https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/plasma5-applets-window-buttons) (already in the repo)

**Thanks for your efforts. Really Much appreciated.**

**Comment by edward-p** [comment]
Close via a9137f7dd0e404b0049a312199e095ef50051cb9
