### ISSUE TITLE
Replace gtk-theme-arc-git with arc-gtk-theme-jnsh-git

### ISSUE THREAD

**Issue by bobby285271** [archlinuxcn/repo#1539]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

  * [horst3180/arc-theme](https://github.com/horst3180/arc-theme) 和 [arc-design/arc-theme](https://github.com/arc-design/arc-theme) 目前都没有人维护，目前只有 [jnsh/arc-theme](https://github.com/jnsh/arc-theme) 还在活跃开发中。

* 主要语言和工具链 / Main Languages and Toolchains

  * n/a

* 上游链接 / Upstream Link

  * https://github.com/jnsh/arc-theme
  * https://aur.archlinux.org/packages/arc-gtk-theme-jnsh-git/

* 为何需要这个软件包 / Why Need This Package

  * n/a

**Comment by SilverRainZ** [comment]
我觉得还是避免 replace，直接加这么个包也可以，毕竟不是同一个 upstream？

**Comment by SilverRainZ** [comment]
NOTE: jnsh/arc-theme now becames offical upstream of archlinux's arc-gtk-theme, so we replace arc-gtk-theme-jnsh-git with arc-gtk-theme-git

**Comment by bobby285271** [comment]
> ~~居然是华师的~~

SCNU 软工 19 级的 // 是遇到校友了吗（

**Comment by SilverRainZ** [comment]
> SCNU 软工 19 级的 // 是遇到校友了吗（

隔壁华隆的。
