### ISSUE TITLE
打包请求 Source Han Mono

### ISSUE THREAD

**Issue by linux40** [archlinuxcn/repo#1540]
### 问题类型 / Type of issues

* 软件打包请求 / package request

### 受影响的软件包 / Affected packages

* `AUR/adobe-source-han-mono-otc-fonts`

----

[AUR](https://aur.archlinux.org/packages/adobe-source-han-mono-otc-fonts/)

中文字体，体积比较大，上游是github，下载慢。

**Comment by dctxmei** [comment]
已添加。
