### ISSUE TITLE
plymouth-git 需要更新 plymouth-start.service

### ISSUE THREAD

**Issue by magicshield** [archlinuxcn/repo#1545]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* plymouth-git
----

aur 上的已经更新了。这里的 plymouth-start.service 没有跟进上游，少了 RemainAfterExit=yes，systemd 245 后，会重复启动 plymouth-start.service。

**Comment by farseerfc** [comment]
lilac 應該在 6459ed02b12b0f8a1a23d636486c4007365179ab 之後修復了。如果還有問題請 reopen
