### ISSUE TITLE
Package Request: ttf-hack

### ISSUE THREAD

**Issue by lijunle** [archlinuxcn/repo#155]
Please add the [chrissimpkins/Hack](https://github.com/chrissimpkins/Hack) font to the repo. It is available in AUR as [ttf-hack](https://aur.archlinux.org/packages/ttf-hack/).

**Comment by kasei-wang** [comment]
done

**Comment by kasei-wang** [comment]
closed by commit e4f871f35cb3a2cc17f5a4931a1df1244d68f132

**Comment by lijunle** [comment]
Thanks @kasei-wang ! BTW, when will it be available in repo?

**Comment by kasei-wang** [comment]
Tomorrow morning if there is no errors . Build bot start at 4:00 am every day.

**Comment by lijunle** [comment]
Awesome! :tada:

**Comment by lilydjwg** [comment]
@kasei-wang no, it starts at 01:00 CST. It may build packages that late because there are some packages require a lot of time to build.

**Comment by kasei-wang** [comment]
Oh, sorry. It's my fault.
