### ISSUE TITLE
移除 anydesk

### ISSUE THREAD

**Issue by Sherlock-Holo** [archlinuxcn/repo#1550]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* anydesk

----

如果有人想维护，就改成 AUR 上的 `anydesk-debian`

**Comment by lilydjwg** [comment]
User reported spam, package immediately removed and packager permanently removed.

https://t.me/archlinuxcn_group/1625993
