### ISSUE TITLE
[package request] wine-x64

### ISSUE THREAD

**Issue by minas1618033** [archlinuxcn/repo#1556]
### 问题类型 / Type of issues

* 软件打包请求 / package request
wine-x64
----

* 简述 / Brief Description

A compatibility layer for running Windows programs. This only configured with x64 support.

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link

[https://aur.archlinux.org/wine-x64.git](https://aur.archlinux.org/wine-x64.git)

* 为何需要这个软件包 / Why Need This Package

一个相当优异的wine分支，仅包含x64依赖，对于无需32位软件的wine用户而言，安装后仅官方源一半大小的体积十分具有吸引力。

**Comment by imlonghao** [comment]
https://aur.archlinux.org/wine-x64.git
404 - Page Not Found

**Comment by minas1618033** [comment]
sorry, I don't understand how to package source from AUR
This is the source in PKGBUILD
[https://dl.winehq.org/wine/source/5.x/](https://dl.winehq.org/wine/source/5.x/)

and this's aur address
[https://aur.archlinux.org/packages/wine-x64/](https://aur.archlinux.org/packages/wine-x64/)

Should I provide any more?

**Comment by imlonghao** [comment]
```
Repository      : archlinuxcn
Name            : wine-x64
Version         : 5.4-3
Description     : A compatibility layer for running Windows programs. This only configured with x64 support.
Architecture    : x86_64
URL             : http://www.winehq.com
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : libx11  fontconfig  lcms2  sdl2  libxcursor  libjpeg  libxslt  libxrandr  libxi  freetype2  libxinerama  libxcomposite  glu
Optional Deps   : v4l-utils
                  opencl-headers
                  opencl-icd-loader
                  libpulse
                  gsm
                  libgphoto2
                  sane
                  libcups
                  openal
                  faudio
                  mpg123
                  vkd3d
                  vulkan-icd-loader
                  vulkan-headers
Conflicts With  : None
Replaces        : None
Download Size   : 28.14 MiB
Installed Size  : 263.10 MiB
Packager        : lilac (on behalf of Dct Mei) <dctxmei@gmail.com>
Build Date      : Mon 06 Apr 2020 03:41:13 AM CST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
