### ISSUE TITLE
firefox-kde-opensuse过期

### ISSUE THREAD

**Issue by maz-1** [archlinuxcn/repo#156]
archlinuxcn的版本为40，最新版为41
40版本存在稳定性问题，在我的系统上经常崩溃

**Comment by JiajunW** [comment]
写了 lilac 的配置文件，但是貌似机器人没有自动更新…

没看出来写的配置有啥问题，@lilydjwg 能帮忙看下配置文件有没有错误吗？

**Comment by lilydjwg** [comment]
上个版本打包失败了呀。之后检查到更新或者 PKGBUILD / lilac.py 被修改才会重新打包的。

**Comment by maz-1** [comment]
这里有编译好的版本
http://download.opensuse.org/repositories/home:/denkad/ArchLinux/x86_64/firefox-kde-opensuse-41.0.1-1-x86_64.pkg.tar.xz
自己编译也是不过，很迷

**Comment by petronny** [comment]
现在repo里面个那个我用archlinuxcn-x86_64-build可以构建出来啊

**Comment by lilydjwg** [comment]
@petronny 那你构建出来的东西呢？
上次 lilac 不知道是为什么没打包成功，你可以更新 pkgrel 让 lilac 重新试一次。

**Comment by farseerfc** [comment]
值得小心一點是那些下載的 patch 的內容變了但是文件名沒變， AUR 裏的 PKGBUILD 的 sha256sum 更新過了， lilac 執行的時候可能不會試圖重新下載那些文件，然後可能報 checksum 不匹配的錯。

**Comment by lilydjwg** [comment]
@farseerfc 那个操作是 makepkg 做的。应当在 PKGBUILD 里为不同内容的文件指定不同的文件名。

**Comment by farseerfc** [comment]
嗯嗯，我的意思是因爲 lilac 有之前下載到的 patch ，本地的乾淨環境下 archlinuxcn-x86_64-build
編譯的結果有可能和編譯機上 lilac 編譯的結果不一樣。最好改 lilac.py 讓 lilac 把那幾個文件刪掉重新下載。

> On Oct 15 2015, at 7:21 pm, 依云 <notifications@github.com> wrote:  

>

> [@farseerfc](https://github.com/farseerfc) 那个操作是 makepkg 做的。应当在 PKGBUILD
里为不同内容的文件指定不同的文件名。

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/archlin
uxcn/repo/issues/156#issuecomment-148344034).![](https://github.com/notificati
ons/beacon/AA0lex9mlLB5vKlU3mc44HYxquStRxhWks5o73WWgaJpZM4GOWyH.gif)

**Comment by JiajunW** [comment]
@farseerfc 对，报错就是 checksum 检查没过= =我还觉得奇怪，明明我自己编译是可以的。

所以要如何写 lilac.py 把这些文件删了重新下？

**Comment by lilydjwg** [comment]
@JiajunW 在 pre_build 函数里对那几个文件调 os.unlink 就可以了。记得要抓住 `FileNotFoundError` 异常。

**Comment by lilydjwg** [comment]
仓库中已经更新了。
