### ISSUE TITLE
Barrier

### ISSUE THREAD

**Issue by Modelmat** [archlinuxcn/repo#1567]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

（请在此填写）Open-source KVM software based on Synergy (GUI)

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）Qt5

* 上游链接 / Upstream Link

（请在此填写）https://aur.archlinux.org/packages/barrier/

* 为何需要这个软件包 / Why Need This Package

（请在此填写）compiling is slow :P

**Comment by yan12125** [comment]
Oops didn't notice this icket. Already added in 30ce961715c70376a8d6bb6cc5f2d74b41b5024d.

**Comment by Modelmat** [comment]
Thanks :)
