### ISSUE TITLE
broken package: rxvt-unicode-better-wheel-scrolling

### ISSUE THREAD

**Issue by DuckSoft** [archlinuxcn/repo#1569]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* rxvt-unicode-better-wheel-scrolling

----

```shell
$ sudo pacman -S rxvt-unicode-better-wheel-scrolling
$ urxvt
urxvt: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
```

**Comment by dctxmei** [comment]
`libperl.so` is provided by the`perl` package, which is an optional dependency of `rxvt-unicode-better-wheel-scrolling`.

**Comment by DuckSoft** [comment]
after a rebuild this works fine. thanks for your timely response!
