### ISSUE TITLE
[RFC] 用 github actions 自动化构建包

### ISSUE THREAD

**Issue by holymonson** [archlinuxcn/repo#1575]
### 问题类型 / Type of issues

* 其它 / other

----

devtools 是十年前开发的工具了，目的是为了创建独立的 chroot 去构建包。但现在 container 已经非常成熟，坚持用自己的木轮子不如用别人的钢轮子。而且现在的 CI 工具也已经非常成熟，我常用的 homebrew 和 conda-forge 都是通过 github actions 自动化构建。所以自己试了一下，几十行配置就可以弄个原型。

仓库见 https://github.com/holymonson/repo ，构建日志见 https://github.com/holymonson/repo/actions 。主要是以下两个文件：
1. [watch-repo.yml](https://github.com/holymonson/repo/blob/workflow/.github/workflows/watch-repo.yml)，每10分钟同步upstream，若有 PKGBUILD 改动则除触发下面的 build workflow。改成直接对 AUR 同步也是可以的。
2. [build-package.yml](https://github.com/holymonson/repo/blob/workflow/.github/workflows/build-package.yml)，开一个 archlinux 的 container，构建包，然后上传到远端 https://monson.bintray.com/alcn/ 。

---

总的来说比较简单，粗略想想可以改进的点：
1. 提交 PR 时就可以过一遍编译测试，貌似这才是一般 github actions 的用法。
1. 可以写自己的 Dockerfile，就不用每次拿官方的 image 然后装 base-devel 之类的准备环境了。
2. 可以多架构，甚至可以多起个 container 作为交叉编译的 host。
3. 如果有云存储 CDN 或者国内有写权限的接口（TUNA貌似挺好说话的？），构建完后直接推送回国内，那么打包机和仓库服务器都省了。

大概就是想分享一下这些，希望大家有空也可以玩玩。

**Comment by lilydjwg** [comment]
做过可行性研究了吗？

* 性能如何？
* 依赖如何处理？
* 定向报错邮件如何发送？

**Comment by holymonson** [comment]
> 做过可行性研究了吗？

已经把原型配置好了，可以看看一个日志 https://github.com/holymonson/repo/runs/580527409?check_suite_focus=true

> 
> * 性能如何？

github actions 是可以配置成 self-hosted，就是在自己的机器上跑。但几乎没有必要，因为其他更大型的仓库都是在云上跑的，毕竟云计算资源可用性高，人家 github 也是专业靠这个赚钱的。

> * 依赖如何处理？

依赖？没什么依赖啊。

> * 定向报错邮件如何发送？

github 本身就直接有失败任务发提醒和邮件的选项。或者可以加个 issue comment 或者其他，额外发送邮件也是可以的，能调 API 就可以。

**Comment by yan12125** [comment]
> 依赖如何处理？

我想依云指的是對彼此有依賴關係的包做拓樸排序這一段：https://github.com/archlinuxcn/lilac/blob/master/lilac2/packages.py

**Comment by yuyichao** [comment]
> devtools 是十年前开发的工具了

= = ArchLinux 还是 18 年前开发的发行版呢....

**Comment by lilydjwg** [comment]
On Sun, Apr 12, 2020 at 04:53:36AM -0700, Monson Shao wrote:
> > 做过可行性研究了吗？
> 
> 已经把原型配置好了，可以看看一个日志 https://github.com/holymonson/repo/runs/580527409?check_suite_focus=true
> 
> > 
> > * 性能如何？
> 
> github actions 是可以配置成 self-hosted，就是在自己的机器上跑。但几乎没有必要，因为其他更大型的仓库都是在云上跑的，毕竟云计算资源可用性高，人家 github 也是专业靠这个赚钱的。

是的，人家靠这个赚钱，所以你用免费款的肯定跟收费版本的一样。

你一个 vnote-git 就花了11分钟。你知道它在我们编译机上花了多久吗？才一分
钟。按这个比例的话，半小时的内核上云就五小时了，三个接连更新大半天就过去
了。编译个 chromium-vaapi 一整天就没了……

> > * 依赖如何处理？
> 
> 依赖？没什么依赖啊。

包之间的依赖。

> > * 定向报错邮件如何发送？
> 
> github 本身就直接有失败任务发提醒和邮件的选项。或者可以加个 issue comment 或者其他，额外发送邮件也是可以的，能调 API 就可以。

github 在任务失败时能发给指定的人吗？调自己的 API 的话，那不还是要自己的
服务器吗？

另外你可能不知道，Arch Linux 官方包也有些是在我们编译机上打包的。

-- 
Best regards,
lilydjwg

**Comment by yan12125** [comment]
如果lilac開一個API，在GitHub Actions裡面呼叫，我倒覺得是個好主意。PR可以手動trigger (ex: specific comments)以避免malicious code在編譯機上自動執行。之前好多PR merge的時候都是壞的...

**Comment by holymonson** [comment]
1. 依赖关系我不明白为什么需要处理。因为 makepkg 自己自动会根据 PKGBUILD 里的处理，只要 pacman.conf 里配置的 repo 有对应的包就可以。而每个 PKGBUILD 又是独立的，不影响啊。
2. 用随用随开的云服务器跟实体机比性能没啥意义的，任务可以并行执行，而且整个云计算池人少时也会多开不用排队。打包本来就只是个批处理任务，不需要实时，能够合理时间完成就可以了。而且真的不满意云计算，github actions 是可以跑在你实体机上的，配置一下就可以。
3. 发邮件完全不需要自己服务器啊，去申请个 gmail，就可以调用 gmail 的 API 发邮件了。像我上面例子，用 github actions 的虚拟机编译，用的 bintray 的 API 存放打好的包，压根儿就没有需要自己的服务器。

**Comment by lilydjwg** [comment]
On Sun, Apr 12, 2020 at 07:26:28AM -0700, Monson Shao wrote:
> 1. 依赖关系我不明白为什么需要处理。因为 makepkg 自己自动会根据 PKGBUILD 里的处理，只要 pacman.conf 里配置的 repo 有对应的包就可以。而每个 PKGBUILD 又是独立的，不影响啊。
> 2. 用随用随开的云服务器跟实体机比性能没啥意义的，任务可以并行执行，而且整个云计算池人少时也会多开不用排队。打包本来就只是个批处理任务，不需要实时，能够合理时间完成就可以了。而且真的不满意云计算，github actions 是可以跑在你实体机上的，配置一下就可以。

你没发现你这两条是相互矛盾的吗？你都并行了，还想着让 makepkg 处理依赖？

如果选择在实体机上跑的话，那干嘛用 github actions 呢？

> 3. 发邮件完全不需要自己服务器啊，去申请个 gmail，就可以调用 gmail 的 API 发邮件了。像我上面例子，用 github actions 的虚拟机编译，用的 bintray 的 API 存放打好的包，压根儿就没有需要自己的服务器。

都用别人的 API，人家 API 升个级、收个费，就够你忙的。你知道 Google
AppEngine 为什么没火起来吗？

另外，你那个 bintray 只是个存放包的地方，并不是软件仓库，因为没有 .db 文
件。你也没法提供 rsync 服务。

你标题写着 RFC，而实际上你连个完善一点的构想都没有，各种权衡利弊也完全没
有考虑过。你去读读 Python 的 PEP 或者 Rust 的 RFC？

-- 
Best regards,
lilydjwg

**Comment by lilydjwg** [comment]
On Sun, Apr 12, 2020 at 07:01:54AM -0700, Chih-Hsuan Yen wrote:
> 如果lilac開一個API，在GitHub Actions裡面呼叫，我倒覺得是個好主意。PR可以手動trigger (ex: specific comments)以避免malicious code在編譯機上自動執行。之前好多PR merge的時候都是壞的...

是说检查 PR 能不能出包么？这个不如审阅完先合并了，有问题再提 PR 修。另外
只是触发操作的话也完全用不着 GitHub Actions，直接用 webhook 就能收到了呀。

-- 
Best regards,
lilydjwg

**Comment by lilydjwg** [comment]
On Sun, Apr 12, 2020 at 07:26:28AM -0700, Monson Shao wrote:
> 2. 用随用随开的云服务器跟实体机比性能没啥意义的，任务可以并行执行，而且整个云计算池人少时也会多开不用排队。打包本来就只是个批处理任务，不需要实时，能够合理时间完成就可以了。而且真的不满意云计算，github actions 是可以跑在你实体机上的，配置一下就可以。

所以你觉得打一个包需要一整天属于「合理时间」？

人少时不用排队，也就是说人多的时候你就完全不知道你的包什么时候能出了，是吗？

-- 
Best regards,
lilydjwg

**Comment by lilydjwg** [comment]
On Sun, Apr 12, 2020 at 10:53:41PM +0800, 依云 wrote:
> On Sun, Apr 12, 2020 at 07:26:28AM -0700, Monson Shao wrote:
> > 2. 用随用随开的云服务器跟实体机比性能没啥意义的，任务可以并行执行，而且整个云计算池人少时也会多开不用排队。打包本来就只是个批处理任务，不需要实时，能够合理时间完成就可以了。而且真的不满意云计算，github actions 是可以跑在你实体机上的，配置一下就可以。
> 
> 所以你觉得打一个包需要一整天属于「合理时间」？

况且还根本无法确定像内核、浏览器这样的包在免费版本的 GitHub Actions 上能
不能打得出来。要不你先试试？

-- 
Best regards,
lilydjwg

**Comment by yan12125** [comment]
> 是说检查 PR 能不能出包么？这个不如审阅完先合并了，有问题再提 PR 修。另外 只是触发操作的话也完全用不着 GitHub Actions，直接用 webhook 就能收到了呀。

Oops 剛剛沒想到webhook。的確這比較適合用webook。

從PR出包應該是可行的。不過滿多細節我還要再想想。如果覺得可行我再開一個新issue，就不拉長戰線了。

**Comment by holymonson** [comment]
> 你没发现你这两条是相互矛盾的吗？你都并行了，还想着让 makepkg 处理依赖？

没发现矛盾，我一开始就说没什么依赖关系所以可以并行啊。`makepkg -s`会自己安装需要的包，请问到底有什么依赖关系需要处理？一直没有人回答我这个问题。

> 都用别人的 API，人家 API 升个级、收个费，就够你忙的。你知道 Google AppEngine 为什么没火起来吗？

云计算发展也不是这一两年的事情，AppEngine现在也不差啊。担心 API 是杞人忧天了，这么多人依赖这个吃饭，这么多人陪葬，这点小项目怕什么。。

> 另外，你那个 bintray 只是个存放包的地方，并不是软件仓库，因为没有 .db 文件。你也没法提供 rsync 服务。

我只是说自动化构建，拿 bintray 只是做个原型，没说  github actions 可以提供这些。但是，提供 rsync 服务的很好找啊，国内那么多镜像，找个大学商量一下让他们做主镜像，不就解决了？.db 周期跑个脚本就可以了，完全不是瓶颈吧。

> 所以你觉得打一个包需要一整天属于「合理时间」？

一个软件发布了新版本，AUR上打 out-of-date 可能要几天时间，维护者更新 PKGBUILD 可能又要几天，即使你们自己从 AUR 同步印象中也只是一天3次吧？包同步回国内镜像也是一天一两次吧？所以，如果“打个包需要一整天”，真的这么“不合理”、这么迫不及待？

再说，github 提供的虚拟机配置是 2-core CPU、7 GB of RAM memory、14 GB of SSD disk space，可以并发20个实例，我觉得这点计算资源完全足够。

> 况且还根本无法确定像内核、浏览器这样的包在免费版本的 GitHub Actions 上能
不能打得出来。要不你先试试？

我的repo盯着 archlinuxcn 已经一天多了，lilacbot 构建的包我这边都会同步构建。刚看了下，最久的是 [linux-next-git 用时 3h 47m 30s](https://github.com/holymonson/repo/runs/580527357?check_suite_focus=true)，我个人觉得是可以接受的。

> 你标题写着 RFC，而实际上你连个完善一点的构想都没有，各种权衡利弊也完全没有考虑过。你去读读 Python 的 PEP 或者 Rust 的 RFC？

抱歉，标题乱写的。我提出了个想法，尽我能力考虑了没有发现瓶颈的点。而且你们可以 challenge，我也乐意解答，可目前似乎没有发现什么重大缺陷，只是在我看来。

---

我之所以说这个，是因为我看过 devtools 和 lilac 的代码，也提出些补丁，但后来觉得不该修小 bug 而跳出来看看，发现可能有更好的工具，于是花了大半天时间、几十行配置代码，就实现了 devtools 和 lilac 八成的功能。我没有说马上下架打包机，只是介绍给大家的想法，完全可以两个方案并行，就花费的时间配置而已，不花钱又不影响现有的服务；即使最后不采用，各位当志愿者，也是想折腾点新东西的吧，不然为啥呢？

在我看来，这里有个木轮子，也一直在转着，只是不时会有缺损，需要打打补丁；然后我到外面去找找，发现了个钢轮子，自己试用了下觉得挺好的，招呼大家来看看，仅此而已。

**Comment by holymonson** [comment]
> > devtools 是十年前开发的工具了
> 
> = = ArchLinux 还是 18 年前开发的发行版呢....

那就有点抬杠了，linux 还30年呢。十年前容器技术还不成熟（chroot其实也算容器），但现在容器已经很成熟，基于容器的工具也很成熟，但 devtools 还是十年前依赖 chroot (systemd-nspawn) 的小工具（就几个 bash 脚本），还阻碍了我构建 arm 的包，所以我才提议用 docker 换掉它。

**Comment by oldherl** [comment]
> 没发现矛盾，我一开始就说没什么依赖关系所以可以并行啊。`makepkg -s`会自己安装需要的包，请问到底有什么依赖关系需要处理？一直没有人回答我这个问题。
同一批次的包之间的相互依赖问题。

> 一个软件发布了新版本，AUR上打 out-of-date 可能要几天时间，维护者更新 PKGBUILD 可能又要几天，即使你们自己从 AUR 同步印象中也只是一天3次吧？包同步回国内镜像也是一天一两次吧？所以，如果“打个包需要一整天”，真的这么“不合理”、这么迫不及待？
archlinuxcn不是只打一两个包，如果一个大包就要打一整天，那其他包还打不打了？现在lilac的工作频率是一天打三次。

> 即使最后不采用，各位当志愿者，也是想折腾点新东西的吧，不然为啥呢？
我不是来折腾的，我是为了打我自己需要的、且有可能有其他人也需要的包，才来打包的

**Comment by oldherl** [comment]
另外，archlinuxcn 虽然名字叫 cn，打包者也大多数在国内，但是并非只服务国内用户。只靠国内的某个大学镜像恐怕不行。
当然在哪里打包和在哪里存放没有必然关系。

**Comment by lilydjwg** [comment]
14g 硬盘，7g 内存有些少了。你 chromium-vaapi
打得出来吗？我在手机上不太方便看。不过最近24小时，已用内存有好几个接近7g的峰，有一个冲到了十g左右。磁盘占用方面，超过14g的大概有三个，其中一个超过20g。

实现了八成的功能，所以剩下的两成呢？是不花钱，可是花时间啊。说得好像时间不值钱似的。

我不想折腾新东西。我只是有些包自己需要，打出来了之后连包带打包程序分享出来，让效用最大化而已。

包是每天打三次，但一次又不是只打一个包。20并发听起来不错，但是调度起来……我不知道咋调度，我对算法设计不熟，只会用现成的。

至于是什么依赖，yan12125 一早就回答你了，你没看而已。

Monson Shao <notifications@github.com> 于 2020年4月13日周一 01:13写道：

**Comment by oldherl** [comment]
其实如果 @holymonson 你的主要目的是打ARM包，那也许可以自己另外维护一个 archlinuxcn-armport 源？里面就用 archlinuxcn 的 PKGBUILD 来打包。反正如你所说，这些服务器硬件资源都是不要钱的。
这样万一有什么东西打坏了也不会影响 archlinuxcn 。

**Comment by MarvelousBlack** [comment]
打一天合理嗎？一點也不，chromium-vaapi 因為某些包更新需要 rebuild  的時候，這意味著你要等一天的時間去等他完成構建，也就是一天裡你都沒法用這個瀏覽器。而現在的情況下，最壞也只是半天的時間。而且 chromium-vaapi 丟內存裡面編譯的話，7G內存完全不夠用。

**Comment by oldherl** [comment]
可是ARM用户可能也不需要 chromium-vaapi 这种大包？所以我提议分成两个源（毕竟arch和alarm也是两个发行版），那些ARM用户不需要的包就可以不打了。

**Comment by MarvelousBlack** [comment]
chromium-vaapi 這只是個例子， ungoogled-chromium 說不准就有人用了呢？順帶一提，在某些小的只有2G內存 arm 的板子上構建 chromium 是需要3天的時間。

**Comment by oldherl** [comment]
我知道只是例子，其他的包比如 supertuxkart-git 或者一些机器学习的包之类大概也可以去掉。

**Comment by yan12125** [comment]
如果要開archlinuxcn-armport，用白名單的方式，把想要打的包加上標注吧。我對於我維護的包能不能在ARM上面打出來沒有興趣。

**Comment by yuyichao** [comment]
> 那就有点抬杠了，linux 还30年呢。

没错, 说的就是提这点完全没有任何意义. 你遇到什么问题想解决当然可以, 但是你一上来就说 devtools 太老这就啥意义都没有. devtools 并不是十年前写完了就一直没变, 最近几年也都加了打包检查之类的功能 (对调试包的支持也比手动打要好)

**Comment by holymonson** [comment]
> 同一批次的包之间的相互依赖问题。

1. 依赖问题应该是写在PKGBUILD的，包括版本依赖。
2. github actions 没有批次的概念，只要一个 push commit 就可以触发构建，每个构建都是独立的。我写的样例就是10分钟同步一次。
3. 如果构建一个包时，发现依赖失败是由于其依赖的包未完成构建，那设个 delay 十分钟之后再重跑，这个逻辑很容易实现呀。

> archlinuxcn不是只打一两个包，如果一个大包就要打一整天，那其他包还打不打了？现在lilac的工作频率是一天打三次。

二十个实例并发，同时可以打二十个包。。二十车道还堵车，那就得找交警了。。

> 我不是来折腾的，我是为了打我自己需要的、且有可能有其他人也需要的包，才来打包的

那这句话确实不是对你说的；但如果你只是关心喂个 PKGBUILD 、就得到个包，那这里讨论的用什么 CI 工具、用云主机还是实体机构建，似乎你也不会在意吧。。

> 可是ARM用户可能也不需要 chromium-vaapi 这种大包？所以我提议分成两个源（毕竟arch和alarm也是两个发行版），那些ARM用户不需要的包就可以不打了。

AUR 就一个。。而且 PKGBUILD 里本来就有 arch 指定。。没人会往那些包里加 arm 。。

> 其实如果 @holymonson 你的主要目的是打ARM包，那也许可以自己另外维护一个 archlinuxcn-armport 源？里面就用 archlinuxcn 的 PKGBUILD 来打包。反正如你所说，这些服务器硬件资源都是不要钱的。

其实我没有什么目的，也不怎么需要 ARM 包；我就只是最近被隔离，闲·得·非·常·蛋·疼！而且，我主力机用的是 macos，之前调试 devtools 还得开虚拟机装 archlinux 。。

如果 archlinuxcn 没兴趣的话，arch4edu 可有兴趣试试？@petronny

**Comment by yuyichao** [comment]
> 如果构建一个包时，发现依赖失败是由于其依赖的包未完成构建，那设个 delay 十分钟之后再重跑，这个逻辑很容易实现呀。

依赖的问题不是打包不成功, 是打包错误. 如果一个包改了 soname, 另一个包可能需要改 pkgrel 重新编译, 如果重新编译的包抓了错的依赖, 编译基本上也出不了问题, 就是编出来的包是坏的.

**Comment by holymonson** [comment]
> > 那就有点抬杠了，linux 还30年呢。
> 
> 没错, 说的就是提这点完全没有任何意义. 你遇到什么问题想解决当然可以, 但是你一上来就说 devtools 太老这就啥意义都没有. devtools 并不是十年前写完了就一直没变, 最近几年也都加了打包检查之类的功能 (对调试包的支持也比手动打要好)

我说 devtools 十年了不是说太老了，而是十年前不成熟的技术（container），现在已经很成熟，已经有更好的替代品了（docker等）。archlinux有更好的替代品吗？我觉得没有，对于Linux明显也没有。你只看到我说时间，却没有看到后面接着的解释。

devtools 只是构造打包环境，真正实现打包的是 makepkg。

> > 个包时，发现依赖失败是由于其依赖的包未完成构建，那设个 delay 十分钟之后再重跑，这个逻辑很容易实现呀。
> 
> 依赖的问题不是打包不成功, 是打包错误. 如果一个包改了 soname, 另一个包可能需要改 pkgrel 重新编译, 如果重新编译的包抓了错的依赖, 编译基本上也出不了问题, 就是编出来的包是坏的.

检查一个包，判断有没有需要触发重新打其他包，这段代码逻辑，本身不就是独立的么？写成一个脚本，是 lilac 调用，还是 github actions 调用，有任何区别？我这里只是对比 CI 工具，其他能 share 的东西本身就不构成 bottle neck。

**Comment by yuyichao** [comment]
> 而是十年前不成熟的技术（container），现在已经很成熟，已经有更好的替代品了（docker等）

十年前的技术成熟了跟要不要用有啥关系? devtools 现在重写一遍也不一定要用docker的. 对于本地打包来讲我没看出来docker有啥好处, 相反 devtools 还更快更方便.

> 检查一个包，判断有没有需要触发重新打其他包，这段代码逻辑，本身不就是独立的么？写成一个脚本，是 lilac 调用，还是 github actions 调用，有任何区别？我这里只是对比 CI 工具，其他能 share 的东西本身就不构成 bottle neck。

所以说没人提检测更新顺序的逻辑, 一直说的是你怎么保证并发的构建间处理依赖关系. lilac 是单个服务可以处理全局依赖关系.

**Comment by holymonson** [comment]
> 十年前的技术成熟了跟要不要用有啥关系? devtools 现在重写一遍也不一定要用docker的. 对于本地打包来讲我没看出来docker有啥好处, 相反 devtools 还更快更方便.

我没有讨论本地打包啊。。
现在 github 提供虚拟机、里面还有 docker 环境，直接 makepkg 就完事了，不再需要 devtools 去弄个干净环境。我自己搭了个原型试试，觉得挺好，仅此而已。


> 所以说没人提检测更新顺序的逻辑, 一直说的是你怎么保证并发的构建间处理依赖关系. lilac 是单个服务可以处理全局依赖关系.

一个底层包，打包好上传放进 stage 仓库之后，再触发其他依赖它的包重新构建。并行又不是说你得所有包一起开工，像之前说的，没有批次、集合的概念了，直接细粒度的链表式触发。

**Comment by yuyichao** [comment]
> 我没有讨论本地打包啊。。
> 现在 github 提供虚拟机、里面还有 docker 环境，直接 makepkg 就完事了，不再需要 devtools 去弄个干净环境。我自己搭了个原型试试，觉得挺好，仅此而已。

所以说的就是这些跟 "十年前" 一点关系也没有. devtools 不用 docker 有他的原因. 我上面就说了你有什么技术上的问题 (比如 github 对 docker 的支持, 比如 arm 打包) 提出来都一点问题都没有. 我说的就是这自始至终跟工具的新旧半点关系都没有 (老工具也可以用新技术, 如果没用多半不是因为工具老). 一上来这 "十年" 摆在这里纯粹误导人.

> 一个底层包，打包好上传放进 stage 仓库之后，再触发其他依赖它的包重新构建。并行又不是说你得所有包一起开工，像之前说的，没有批次、集合的概念了，直接细粒度的链表式触发。

1. 所以说大家问的就是你打算怎么实现这个. 目测你目前的实现没这功能.
2. 批次的感念是必须的, 这种依赖的更新必须是一起干的 (当然我们没有对官方库集成的很紧密所以 python/boost 这种更新做不到一次搞定) 否则照样会出现坏包.

**Comment by yan12125** [comment]
> 其实我没有什么目的，也不怎么需要 ARM 包；我就只是最近被隔离，闲·得·非·常·蛋·疼！

浪費大家的時間。

不同意我的做法的再reopen+unlock吧。每個member都有權限的。
