### ISSUE TITLE
软件打包请求:iflyime input

### ISSUE THREAD

**Issue by wszqkzqk** [archlinuxcn/repo#1576]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

iflyime Chinese input method

* 主要语言和工具链 / Main Languages and Toolchains

unknown

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/iflyime/

* 为何需要这个软件包 / Why Need This Package

a convinent and popular Chinese input method

**Comment by oldherl** [comment]
又是个闭源输入法……

协议：
https://srf.xunfei.cn/linux/help/agreement.html
不能自由地重打包和分发。

而且AUR里面那个上游链接点进去根本没有Linux版的相关信息（那个页面还不让用键盘滚动）。看起来对Linux不怎么友好。建议放弃。

**Comment by yan12125** [comment]
Duplicate of https://github.com/archlinuxcn/repo/issues/1510.
