### ISSUE TITLE
out-of-date systemtap

### ISSUE THREAD

**Issue by attenuation** [archlinuxcn/repo#1577]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages
* systemtap

----

**Comment by attenuation** [comment]
看起来维护者不在社区里 我先更新了 @ideal

**Comment by ideal** [comment]
@attenuation Thanks.

**Comment by attenuation** [comment]
@ideal 我可以加一个共同 maintainers 么，收 lilac 的告警

**Comment by ideal** [comment]
@attenuation 可以的，感谢。
