### ISSUE TITLE
vim-youcompleteme-git没用新版clang和llvm编译

### ISSUE THREAD

**Issue by oakszyjrnrdy** [archlinuxcn/repo#1583]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* vim-youcompleteme-git
* llvm-libs
* clang
----

请在此补充说明。
Please describe in detail here.
以下更新:
	lib32-llvm-libs (9.0.1-2 -> 10.0.0-1)
	llvm-libs (9.0.1-3 -> 10.0.0-1)
	clang (9.0.1-1 -> 10.0.0-2)
	kdevelop (5.5.0-1 -> 5.5.0-2)
会导致
	archlinuxcn/vim-youcompleteme-git r2631.dd4a583e-1
启动失败。

**Comment by oakszyjrnrdy** [comment]
build一直在失败：https://build.archlinuxcn.org/packages/#/vim-youcompleteme-git
还请看一下 @dctxmei

**Comment by dctxmei** [comment]
這次是手動推包，新包已經在源裡了。

**Comment by oakszyjrnrdy** [comment]
谢谢
