### ISSUE TITLE
aur/minecraft already updated to web-based (non-java) launcher

### ISSUE THREAD

**Issue by Nullizer** [archlinuxcn/repo#1590]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
minecraft
----

请在此补充说明。
Please describe in detail here.
https://aur.archlinux.org/packages/minecraft/

**Comment by petronny** [comment]
e6d16a2
