### ISSUE TITLE
[fcitx5-git] error while loading libjson-c.so

### ISSUE THREAD

**Issue by rocka** [archlinuxcn/repo#1593]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* fcitx5-git

----

请在此补充说明。
Please describe in detail here.

```console
$ fcitx5
fcitx5: error while loading shared libraries: libjson-c.so.4: cannot open shared object file: No such file or directory
```

`core/json-c` updated to 0.14-1 and `libjson-c.so.4` does not exist any more, it's now `libjson-c.so.5`. Maybe rebuild needed?

**Comment by escape0707** [comment]
今天更新了一下已经好了。
