### ISSUE TITLE
[fcitx-lilydjwg-git]please update fcitx-lilydjwg-git to use libjson-c.so.5

### ISSUE THREAD

**Issue by taolin96** [archlinuxcn/repo#1594]
### 问题类型 / Type of issues
fcitx-lilydjwg-git stopped working after core/json-c updated from 0.13.1-3 -> 0.14-1
which change libjson-c.so.4 to libjson-c.so.5

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages
*  fcitx-lilydjwg-git

----

请在此补充说明。
Please describe in detail here.

> error while loading shared libraries: libjson-c.so.4: cannot open shared object file: No such file or directory

**Comment by lilydjwg** [comment]
A rebuild should be coming this night CST.
