### ISSUE TITLE
installing archlinuxcn-keyring with error: target not found

### ISSUE THREAD

**Issue by Aeonage** [archlinuxcn/repo#1595]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

New for Arch Linux. When i am trying using yay and archlinuxcn repo, i encounter an error follow.
```
[aeon@Archlinux tmp]$ sudo pacman -Syy && sudo pacman -S archlinuxcn-keyring
:: Synchronizing package databases...
 ... procedure here...
error: target not found: archlinuxcn-keyring
```
Here is my /etc/pacman.d/mirrorlist
```
## China
Server = http://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.zju.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.aliyun.com/archlinux/$repo/os/$arch
Server = http://mirrors.163.com/archlinux/$repo/os/$arch
```
And here is my /etc/pacman.conf
```
#[archlinuxcn]
SigLevel = Optional TrustAll
Server = http://mirrors.cloud.tencent.com/archlinuxcn/$arch
```
It will be appreciated if the issue could get a response soon.

**Comment by lilydjwg** [comment]
Wrong config. Try:

```
 [archlinuxcn]
Server = https://mirrors.cloud.tencent.com/archlinuxcn/$arch
```

**Comment by Aeonage** [comment]
Thanks for your help.&nbsp; i am the guy who asking on zhihu: ). But the error still occur after I fix the problem. I am sure my arch is running on x86_64 architect. I realized that the Terminator output nothing with $arch. could it be the reason?


 
---Original---

**Comment by lilydjwg** [comment]
> I realized that the Terminator output nothing with $arch. could it be the reason?

It's expected.

**Comment by oldherl** [comment]
Seems no issue here.
