### ISSUE TITLE
solve the resource-exhaustion issue with ninja

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#1598]
### 问题类型 / Type of issues
* 其它 / other

----

Update: there is a new way to this issue at https://github.com/archlinuxcn/repo/issues/1598#issuecomment-626573927 and I'm going to implement it.

----

#1597 doesn't work. kicad-git timed out because all CPU resources was occupied by ninja and our make is too kind! And possibly other timed out packages too. We need a hack!

* Create a wrapper for ninja with kind args
* Create a packge to install this wrapper and in post-install hook, replace `ninja` with the wrapper
* Install (`repo_depends`) the package for packages that use ninja

I'll implement the first two later.

See also:

* We waited: #635 
* samurai seems good but doesn't work for us: https://github.com/ninja-build/ninja/issues/1482#issuecomment-574142694
* ninja decided not to add the support: https://github.com/ninja-build/ninja/pull/1399

**Comment by lilydjwg** [comment]
We may want a pre-commit check for packages that neither mention `ninja -l` nor install our wrapper package.

**Comment by lilydjwg** [comment]
Or maybe we can create a package replacing ninja in a local repo? Will pacman install it instead?

**Comment by yan12125** [comment]
How about using systemd to limit CPU usage of processes under user.slice?

Ref: https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html

**Comment by lilydjwg** [comment]
> How about using systemd to limit CPU usage of processes under user.slice?

This seems to be good, except that it doesn't work well with `make -l`. There will be a lot of running processes when multiple users are compiling. What bad will this situation bring to us?

**Comment by yan12125** [comment]
I guess most make flags uses `$(nproc)`? If so, systemd's `CPUAffinity=` should help. I've just tried it - `CPUAffinity=` changes the value returned by `nproc`. Commands in `extra-x86_64-build` are also affected.

**Comment by lilydjwg** [comment]
I mainly concern that under high load (say 2-3x of # of cpu cores) will other services be affected? i.e. sshd, nginx, collectd & grafana, etc. I'm going to do some tests.

**Comment by lilydjwg** [comment]
I'm finally done with the cgroups test. Here's the steps to take:

1. remove any `-l` arguments we've put into environmental variables and PKGBUILDs
2. set kernel parameter `systemd.unified_cgroup_hierarchy=1`
3. set `CPUWeight=100` in `/etc/systemd/system/user-.slice.d/resources.conf`
4. reboot

This will distribute CPU time evenly to all user-XXX.slice. It will also distribute CPU time evenly to user.slice and system.slice so system services should have enough time to do their work.

Also, observations show that, with `make -l` and `ninja -l` the CPU is under-utilized, and distributed coarsely (sometimes there are only 4 makes but a lot of ninjas; however the build time halved as expected).

I'll wait some more days before moving this forward.

**Comment by lilydjwg** [comment]
The cgroups way has been implemented.
