### ISSUE TITLE
tizonia-all - error, can't import python modules: pafy, youtube-dl, fuzzywuzzy

### ISSUE THREAD

**Issue by nod3man** [archlinuxcn/repo#1618]
### 问题类型 / Type of issues
* 打包错误 / packaging error

### 受影响的软件包 / Affected packages
* tizonia-all

----

请在此补充说明。

tizonia can't find python modules.
```
➜  ~ tizonia --youtube-audio-search "darude sandstorm"
tizonia 0.21.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

[Youtube] [Connecting] : 'darude sandstorm'.
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ValueError

Python modules 'pafy', 'youtube-dl' or 'fuzzywuzzy' not found.
Please make sure these are installed correctly.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```
Reproducable either with zsh+oh-my-zsh and system's unmodified bash.
All packages is latest version/
Dependcencies is installed and system's python interpreter can import them.
```
➜  ~ python
Python 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pafy
>>> import youtube_dl
>>> import fuzzywuzzy
```

**Comment by edward-p** [comment]
Just figure out what's happening here.  :disappointed: 
https://github.com/tizonia/tizonia-openmax-il/blob/fdc313874a91870d182577d55a8f42a3276a95b6/clients/youtube/libtizyoutube/src/tizyoutube.cpp#L106
Should fix by https://github.com/archlinuxcn/repo/commit/9aead05c4220c1736a077f7d46a1e76794466b92.
Please wait for the next build or install `python-joblib` manually.
