### ISSUE TITLE
linux-lily 在 tty 下无法显示中文

### ISSUE THREAD

**Issue by Laoyian** [archlinuxcn/repo#1620]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* linux-lily
----
例如，“桌面”被显示为 ''$'\346\241\214\351\235\242'

**Comment by lilydjwg** [comment]
没有设置一个合适的 locale。试试 `export LANG=zh_CN.UTF-8`。

**Comment by Laoyian** [comment]
> 没有设置一个合适的locale。试试`export LANG=zh_CN.UTF-8`。

显示正常了，谢谢你的帮助！
