### ISSUE TITLE
Package request: ttf-cascadia-code

### ISSUE THREAD

**Issue by brilliant116** [archlinuxcn/repo#1624]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

* 主要语言和工具链 / Main Languages and Toolchains

* 上游链接 / Upstream Link

https://github.com/microsoft/cascadia-code

* 为何需要这个软件包 / Why Need This Package

I don't want to download the .ttf file, and then install it. Just `sudo pacman -S ttf-cascadia-code` will be fine.

**Comment by oldherl** [comment]
It's available in [community]
community/ttf-cascadia-code 1910.04-1
    A monospaced font by Microsoft that includes programming ligatures
