### ISSUE TITLE
flutter: cache shouldn't be in the package

### ISSUE THREAD

**Issue by outloudvi** [archlinuxcn/repo#1625]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* flutter

----

In `archlinuxcn/flutter` 1.17.1-1, there are a lot of cache-like files, which seems abnormal. The related directories included in the package are:
* `/opt/flutter/bin/cache`
* `/opt/flutter/.pub-cache`

**Comment by frealgagu** [comment]
/opt/flutter/bin/cache and /opt/flutter/.pub-cache are being deleted in the package step.
The following lilac build will have those changes.
