### ISSUE TITLE
wine-x64 needs update

### ISSUE THREAD

**Issue by demolg** [archlinuxcn/repo#1628]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* wine-x64

**Comment by demolg** [comment]
@dctxmei 从CN源里安装的audio driver不能正常工作，我自行使用yay安装的没有问题。是不是哪里出错了？

**Comment by dctxmei** [comment]
I have decided to discard this package, see: https://github.com/archlinuxcn/repo/issues/1846 .

**Comment by yan12125** [comment]
Sorry didn't notice that.

**Comment by dctxmei** [comment]
It doesn't matter.
