### ISSUE TITLE
parsoid: previous config lost after installing

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#1629]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* parsoid
* parsoid-git

----

If you switch from parsoid to parsoid-git, or vice-versa, or uninstall and install again, you'll lose your config files at `/usr/share/webapps/parsoid/localsettings.js` and `/usr/share/webapps/parsoid/config.yaml`. 

Pacman will backup these files, but the install script will remove them with `userdel -rf parsoid`.

I suggest that these files be kept in `/etc/webapps/parsoid` and symlinked to `/usr/share/webapps/parsoid`.

**Comment by KenOokamiHoro** [comment]
moved in https://github.com/archlinuxcn/repo/commit/0274c6df0d76ca94d26724f3a501ae726d01fe3b and https://github.com/archlinuxcn/repo/commit/074a9db4b048b4a8e4d42179920511acd5afde89 .
