### ISSUE TITLE
haskell-language-server-git: built binary contains reference to the build dir

### ISSUE THREAD

**Issue by Matelasse** [archlinuxcn/repo#1633]
### 问题类型 / Type of issues
haskell language server malfunctions when installed from archlinuxcn repos
* 打包错误 / packaging error
not sure
### 受影响的软件包 / Affected packages
haskell-language-server-git
----

请在此补充说明。
Please describe in detail here.
First of all thanks for precompiling things for us. Now to get to the problem, first I would like to mention that I am not the only person experiencing this problem. The other person, uses AUR package for haskell-language-server and they faced the same issue as I did with HLS from archlinuxcn repos. The exact issue is documented here https://github.com/haskell/haskell-language-server/issues/47:
for some reason HLS resolves to a compile-time GHC installation `
Step 4/6, Cradle 1/1: Loading GHC Session
haskell-language-server: /build/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/settings: openFile: does not exist (No such file or directory)`. The `/build/.stack/...` seems like a Pacman thing to me. I think HLS picks up compile-time paths as it installs itself. I''m not sure how this can be fixed from Arch packaging side, but for what's it worth git cloning the HLS and building it myself fixed that very issue.

**Comment by poscat0x04** [comment]
I think this is a bug of hls itself, the produced binary should not contain any references to the build directory.

**Comment by poscat0x04** [comment]
Closed due to stalement
