### ISSUE TITLE
hplip lilac nvchecker error

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#1634]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
hplip
----

请在此补充说明。
Please describe in detail here.

I was asked to review https://github.com/archlinuxcn/repo/pull/1631 since I am the maintainer of hplip. I don't know anything about how lilac works though, so I just merged the pull request thinking that whoever wrote it knew what they were doing. Since then, lilac has been emailing me about the following error:

{"logger_name": "nvchecker.get_version", "name": "hplip-plugin:1", "event": "no idea to get version info.", "level": "error"}
{"logger_name": "nvchecker.core", "name": "hplip-plugin:1", "event": "no-result", "level": "warning"}

Will this error prevent lilac from maintaining the package? If so, I would like someone who knows how to fix this to take over the package.

**Comment by edward-p** [comment]
Added my review here: https://github.com/archlinuxcn/repo/pull/1631#discussion_r428271089

**Comment by hubutui** [comment]
@edward-p 直接修改更新一下？我发 pr 就是希望有人 review 的啊，当时还奇怪怎么就直接 merge 了。。。

**Comment by hubutui** [comment]
@edward-p 我感觉是不是我不会用 github 啊，怎么点开看不到你的 comment？

**Comment by lilydjwg** [comment]
又是这个问题。我记得之前谁犯过的……

Butui Hu <notifications@github.com> 于 2020年5月21日周四 08:52写道：

**Comment by edward-p** [comment]
> @edward-p 我感觉是不是我不会用 github 啊，怎么点开看不到你的 comment？

忘记点提交了。。。
