### ISSUE TITLE
optimus-manager-qt-kde: empty package

### ISSUE THREAD

**Issue by katherlee** [archlinuxcn/repo#1638]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* optimus-manager-qt-kde

----

I think the reason is on this line: https://github.com/archlinuxcn/repo/blob/0a508e5f0ceb2c1cf44caeb2210809d173a512b9/archlinuxcn/optimus-manager-qt/PKGBUILD#L36

While the PKGBUILD creates split packages for both `optimus-manager-qt` and `optimus-manager-qt-kde`, in `build()` their installation path is set to be the same. In fact, according to the [man page](https://www.archlinux.org/pacman/PKGBUILD.5.html), the `$pkgdir` variable "should only be used in the package() function."

**Comment by Rasphino** [comment]
Thanks and sorry for my fault :(

**Comment by katherlee** [comment]
No worries! Thanks for maintaining!
