### ISSUE TITLE
openblas-lapack-git & openblas-git & openblas-git-debug pkgver with prepend 'v'

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#1644]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* openblas-lapack-git
* openblas-git
* openblas-git-debug
----

`v` should be stripped from pkgver.

**Comment by yuyichao** [comment]
.... forgot to close by commit message. https://github.com/archlinuxcn/repo/commit/6d787ebeb4aba8793ae01c3a297d2b32a84acfa9
