### ISSUE TITLE
linux-macbook replaces virtualbox-guest-modules-arch wireguard-arch

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#1646]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* linux-macbook
----

这咋回事啊……
包我先删掉了。正在改 lilac，以防类似的事情再次发生。

**Comment by yan12125** [comment]
After 90 days, this package appeared again cd51fc3544da192c8852db39a0d8232421245e15
