### ISSUE TITLE
更新时jfbview一直提示Replace jfbview with archlinuxcn/jfbview

### ISSUE THREAD

**Issue by OliverLew** [archlinuxcn/repo#1647]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* jfbview

----

（对不起我对arch的包管理的原理一点都不了解，不清楚这是我的问题，还是其他原因，问题类型就选了最接近的“打包错误”。）

现象是我装了archlinuxcn/jfbview之后，再`sudo pacman -Syu`，总会有下列提示
```
Replace jfbview with archlinuxcn/jfbview? [Y/n]
```
然后原封不动升级一遍，什么都没改，紧接着Syu还会有这个。

不知道这个你们能复现吗？不能的话，会不会是我之前装过旧版本（之前装过aur/jfbview和aur/jfbview-git），有什么文件残留导致pacman误判之类的，应该检查哪些地方？实在不清楚应该从哪里查起，需要额外信息的话我会尽量提供。

**Comment by lilydjwg** [comment]
自己 replace 自己……这是打包的问题啦。

**Comment by farseerfc** [comment]
打包問題，我馬上修
（最近一次 AUR 更新是 jfbview 上游作者，他讓 jfbview 自己 conflict 了自己……）

**Comment by OliverLew** [comment]
@farseerfc 我看你在AUR提交了修复，archlinuxcn库也已经自动更新，我就把issue关掉吧。谢谢！
