### ISSUE TITLE
python-scikit-image缺少依赖python-tifffile

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#1648]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* python-scikit-image

----

AUR 上有 https://aur.archlinux.org/packages/python-tifffile/. 不过版本也需要更新吧。而且 python-scikit-image 也过期了，AUR 上有标注，但是打包者没有更新。

**Comment by Universebenzene** [comment]
这不是我不想更新，是因为新版的skimage依赖的tifffile版本高，AUR上的这包版本不够，我去flag out of date过了，但人家不更，我没办法

**Comment by oldherl** [comment]
@Universebenzene 你可以选择不再跟踪AUR，自己更新版本

**Comment by oldherl** [comment]
或者跟踪上游版本号

**Comment by Universebenzene** [comment]
那得找 @MarvelousBlack 菊苣来办了，我不是cn源的打包者，这包是惠狐菊苣帮忙搬来的……另外新版skimage还缺个依赖poosh，我看tifffile不更我也就没去AUR打新的

**Comment by oldherl** [comment]
你可以PR一个 python-tifffile 的新版PKGBUILD……

**Comment by hubutui** [comment]
这样子么？那我来更吧。诶。自己用就得自己更啊。

**Comment by oldherl** [comment]
@hubutui 注意看tg

**Comment by hubutui** [comment]
fix by https://github.com/archlinuxcn/repo/pull/1650
