### ISSUE TITLE
unarchiver: 因为 icu 升级而需要重新编译

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#165]

**Comment by petronny** [comment]
感觉类似问题总是会出现呢 自动检测可行吗？

On 周二, 11月 10, 2015 at 16:44, archlinuxcn/repo
<reply@reply.github.com>
wrote:

**Comment by lilydjwg** [comment]
可行。求 PR。

**Comment by cuihaoleo** [comment]
额，交给 lilac 了…… 明天要是重新编译好了就关了吧。

**Comment by lilydjwg** [comment]
@cuihaoleo 好棒！
