### ISSUE TITLE
deepin-wine 希望升级 2.18.24~rc3

### ISSUE THREAD

**Issue by abcfy2** [archlinuxcn/repo#1656]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

deepin-wine

### 受影响的软件包 / Affected packages

- deepin-fonts-wine
- deepin-libwine
- deepin-wine-binfmt
- deepin-wine32-preloader
- deepin-wine32-tools
- deepin-wine32
- deepin-wine

----

deepin-wine迎来了一波更新，希望可以跟进：[系统公告](https://www.deepin.org/2020/06/04/deepin-system-updates%ef%bc%882020-06-04%ef%bc%89/)

Deepin官方deepin-wine安装包地址： https://community-packages.deepin.com/deepin/pool/main/d/deepin-wine/

**Comment by abcfy2** [comment]
@Skywol @SilverRainZ 已经在PR #1688 解决，看看有什么问题没？希望可以合并

**Comment by SamLukeYes** [comment]
最近发现deepin的仓库里出现了deepin-wine5：[](https://community-packages.deepin.com/deepin/pool/main/d/deepin-wine5/)

**Comment by abcfy2** [comment]
> 最近发现deepin的仓库里出现了deepin-wine5：https://community-packages.deepin.com/deepin/pool/main/d/deepin-wine5/

已经开新的issue #1715 记录了，等我回去评测下deepin-wine5，看看能否搞一个。如果可以的话我考虑把这个接起来，正好最近在用Manjaro做工作系统和日常使用，平时也在用TIM和微信和客户沟通，算是重度使用了，我考虑把这个维护接起来

**Comment by abcfy2** [comment]
archlinuxcn已经更新，这个issue关闭
