### ISSUE TITLE
Package request: slack-desktop

### ISSUE THREAD

**Issue by oldherl** [archlinuxcn/repo#1657]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Slack Desktop (Beta) for Linux

* 主要语言和工具链 / Main Languages and Toolchains

electron

* 上游链接 / Upstream Link

https://slack.com/downloads
https://aur.archlinux.org/packages/slack-desktop/

* 为何需要这个软件包 / Why Need This Package

collaboration software for enterprise

**Comment by oldherl** [comment]
兔兔来打一个？

**Comment by whriedplanck** [comment]
使用系统电子包试验包：https://aur.archlinux.org/packages/slack-electron/
@BruceZhang1993 和 @oldherl 目前发现的一个问题是，抽出自带电子包的 Slack 似乎无法自动捕获浏览器发出的验证链接，且难以修复。

**Comment by BruceZhang1993** [comment]
这个问题目前看来无法解决，暂时放 AUR 直到有解决方案或者官方处理好以后再进源。
