### ISSUE TITLE
wxmedit 真的需要依赖 boost 吗？

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#166]
boost 包里只是一堆头文件。我看到 wxmedit 有 include boost 的东西，那也只是编译期依赖吧。
而且 wxmedit 编译出来的可执行文件似乎也不依赖 boost-libs。

**Comment by petronny** [comment]
呃。。的确是卸了boost也能运行的样子。。
去给AUR汇报一下？
https://aur.archlinux.org/packages/wxmedit/
