### ISSUE TITLE
[package request] ytop

### ISSUE THREAD

**Issue by minas1618033** [archlinuxcn/repo#1666]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Another TUI based system monitor, this time in Rust!

* 主要语言和工具链 / Main Languages and Toolchains

rust

* 上游链接 / Upstream Link

https://github.com/cjbassi/ytop.git

* 为何需要这个软件包 / Why Need This Package

原作者的gotop已停止維護，轉向開發ytop

**Comment by yuyichao** [comment]
把名字看成 typo 的一定不只有我一个人....

**Comment by SilverRainZ** [comment]
ytop 也停更了，这个作者是坑了多少个项目啊。
