### ISSUE TITLE
webkitgtk is out of date

### ISSUE THREAD

**Issue by mrksr** [archlinuxcn/repo#1667]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* webkitgtk

----

Similar to #1130 and #1384, `core/icu` has been updated with the current version being `67.1-1`.
Could you please rebuild `webkitgtk`? Thanks! :)

**Comment by frealgagu** [comment]
I've bumped up the version and the package was built by lilac in June 20th. Have you upgraded and continued receiving the same error?

**Comment by mrksr** [comment]
@frealgagu: Seems to work again, thank you very much! :)
@oldherl: Thanks for the suggestion and sorry for my late reply. The older package (`-18` that is) indeed works with `icu65`.

So `-18` works with `icu65` and `-19` works with current `icu` which is version 67.

**Comment by oldherl** [comment]
> I've bumped up the version and the package was built by lilac in June 20th. Have you upgraded and continued receiving the same error?

I am pretty sure that you didn't mean June 20th.
😀
