### ISSUE TITLE
Emacs27-git

### ISSUE THREAD

**Issue by yqu212** [archlinuxcn/repo#1671]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Emacs27-git是Emacs即将发布的最新版。

* 主要语言和工具链 / Main Languages and Toolchains

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/emacs27-git/

* 为何需要这个软件包 / Why Need This Package

emacs-git打包的一直是Emacs的最新开发版，目前不稳定。现在Emacs 27已经进入发布流程，单独在Emacs 27分支中维护。如果能够在Emacs 27正式版发布之前将Emacs 27单独打包，可以兼顾Emacs 27的新特性和稳定性。

**Comment by linux40** [comment]
其实我不希望任何 emacs 包出现在源中。这些包都是高度可定制的，我要稍微改一下 PKGBUILD。每次更新时要排除源中的这个包的话很烦。如果你显 clone 时间长的话，这个包的 AUR 版本不怎么更新，你拿一天花点时间单独 clone，改 source 为 file://，之后就不用怎么管它了。27也不会改很多东西了，不用追求最新。

**Comment by lilydjwg** [comment]
> 每次更新时要排除源中的这个包的话很烦

`IgnorePkg` ?

**Comment by yqu212** [comment]
还是希望能打包一下emacs 27。这只是一个过渡性质的包（时间要视emacs 27的发布进程了，目前看来还不知道要等多久）。等emacs 27发布之后可以用回官方仓库的emacs包。

最近一年多我一直使用emacs-git。相信很多人使用emacs-git的原因和我一样，是希望能够使用emacs27的新特性。可是现在emacs-git版本号进入28，出现了有好多问题。导致现在使用emacs-git变得不太合适，而切换回官方仓库的emacs包又要改动很多配置，得不偿失。

emacs27迟迟不发布。如果没有emacs 27的包，那么每次安装emacs就只能重新编译。也不是每个人都希望编译安装emacs。否则emacs-git包就没有存在的意义了。

请打包一下Emacs 27。谢谢。

**Comment by linux40** [comment]
> 如果没有emacs 27的包，那么每次安装emacs就只能重新编译。也不是每个人都希望编译安装emacs。
指正一下，不是每次，一次就行，这个包的AUR不怎么更新。而且编译起来很快的，我笔记本4代i5，4G DDR3内存加机械硬盘无压力。
> 否则emacs-git包就没有存在的意义了。
我个人是觉得没必要。

当然感谢提醒有 `IgnorePkg` 这个功能。

**Comment by yqu212** [comment]
@lilydjwg 你好，如果能够打包就请帮我打下包，如果不行我就直接关掉这个Issue了。

**Comment by oldherl** [comment]
lilydjwg 不是 emacs-git 包的维护者。
应该请 emacs-git 包的维护者 @ykelvis 来判断是否需要打包。

**Comment by oldherl** [comment]
@linux40 如果你不希望自己打的包被cn替换，那你可以在自己打包时在后面加个后缀之类来区分。
比如 emacs-git-linux40 这样就不会被 emacs-git 替换了

**Comment by yqu212** [comment]
@oldherl 谢谢你。我知道以后该怎么提交打包申请了。

**Comment by yqu212** [comment]
@ykelvis 多谢。
