### ISSUE TITLE
Vote: How to handle orphaned packages that are still used?

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#1676]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

----

In some cases, orphaned packages are listed in `repo_depends` of other packages. With current lilacbot, orphaned packages are just removed if nobody adopts them in 14 days, and thus packages using them are broken. Users can no longer install broken packages solely from [archlinuxcn], and the `repo_depends` field become invalid - it contains non-existent packages.

For example, lib32-libmng is orphaned and then removed on May 20, 2019 [1]. After that date, lib32-qt4 is broken until lib32-libmng is re-added on Apr 10, 2020 [2].

I'd like to propose changes to the policy and code, so that packages depending on orphaned packages will continue to work. Here are some possible approaches:

* Keep orphaned packages and make the `maintainers` field an empty list
* Transfer maintainership automatically. For example, if A is in `repo_depends` of B and C, the maintainers of A will become union of maintainers of B and C.
* (any other options...?)

Please discuss and vote for the option you prefer or propose other options, thanks!

Related issues and pull requests:
* https://github.com/archlinuxcn/misc_scripts/pull/17
* https://github.com/archlinuxcn/repo/pull/1574
* https://github.com/archlinuxcn/repo/issues/1414

[1] dedbaec
[2] 8f535d9

**Comment by yuyichao** [comment]
Leaving the package up for adoption while in the meantime send any build failures to the maintainer of the dependent?

**Comment by yan12125** [comment]
> Leaving the package up for adoption while in the meantime send any build failures to the maintainer of the dependent?

Sounds good!

**Comment by oldherl** [comment]
I would like lilac to comment on the orphaning request (github issue) about any `repo_depends` on it and don't delete the package until all dependencies are removed or the orphaning package is now maintained by others.
Lilac should notify all the maintainers of packages that depends on the orphaning package as soon as the orphaning starts, because some packages might not get update and/or rebuilds in the 14-day period,

**Comment by lilydjwg** [comment]
Things to do when the package being orphaned is dependent:

* on issue submission mention all maintainers of dependent packages
* on expiration remove maintainers from the package
* on packaging errors send reports to dependent packages maintainers
* daily check if there are packages without maintainers not required any more, and delete them if so
* on new issue comment about unmaintained packages

Anything else?

**Comment by yan12125** [comment]
"packaging errors" include build failures and nvchecker errors, right?

**Comment by lilydjwg** [comment]
On Sat, Jun 13, 2020 at 10:07:36PM -0700, Chih-Hsuan Yen wrote:
> "packaging errors" include build failures and nvchecker errors, right?

Yes.

-- 
Best regards,
lilydjwg

**Comment by lilydjwg** [comment]
I'm starting working on this, tracked by https://github.com/archlinuxcn/misc_scripts/issues/18.
