### ISSUE TITLE
555-555-0199@example.com

### ISSUE THREAD

**Issue by sometymesibelief** [archlinuxcn/repo#1680]
### 问题类型 / Type of issues

&lt;!--
请只保留符合的行，删掉其它行。
Please keep only the line that suits and delete others.
--&gt;

* 软件打包请求 / package request
* 过期软件包 / out-of-date packages
* 弃置软件包 / orphaning packages
* 软件包被官方仓库收录 / available in official repos
* 打包错误 / packaging error
* 其它 / other

### 受影响的软件包 / Affected packages

&lt;!--
请每行一个包基础名（对应仓库中的目录名），
开头加上 `* `（注意星号后有一个空格）。

Please write one package base name (i.e. the directory name in this repo) per
line, prefixing with `* ` (Note there is a space after the star).

对于软件打包请求，此项可不填。
Not necessary for package requests.
--&gt;

----
&lt;!--
补充信息请写在此处。
Write other details here.

对于软件打包请求，请额外提供以下信息：
For package requests, please add the following info:
* 简述 / Brief Description
* 主要语言和工具链 / Main Languages and Toolchains
* 上游链接 / Upstream Link
* 为何需要这个软件包 / Why Need This Package
--&gt;

**Comment by MarvelousBlack** [comment]
No useful information, close.
