### ISSUE TITLE
有些包把文件装进/usr/local里了

### ISSUE THREAD

**Issue by huyz-git** [archlinuxcn/repo#1684]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* kernelshark (a split package of trace-cmd maintained by @Sasasu)

----

* ~eternalterminal~ (intended, see below)
* ~eternalterminal-client~ (intended, see below)
* ~xinput_calibrator~ (removed in ff9033c9b04d7a345f15daaa49989da1b3dccfb1)
* ~onedrive-abraunegg~ (fixed in 27053b6dad3)

请在此补充说明。
Please describe in detail here.

按照[wiki](https://wiki.archlinux.org/index.php/Arch_package_guidelines)里的说法，软件包不应该安装到/usr/local里。但是，通过`sudo pacman -Fy usr/local/ | grep archlinuxcn`发现，有以上5个包有文件装在/usr/local里：
```
$ pacman -Fl eternalterminal | grep usr/local 
eternalterminal usr/local/
eternalterminal usr/local/bin/
eternalterminal usr/local/bin/et
```
```
$ pacman -Fl eternalterminal-client | grep usr/local 
eternalterminal-client usr/local/
eternalterminal-client usr/local/bin/
eternalterminal-client usr/local/bin/et
```
```
$ pacman -Fl kernelshark | grep usr/local
kernelshark usr/local/
kernelshark usr/local/bin/
kernelshark usr/local/bin/kernelshark
kernelshark usr/local/bin/kshark-record
kernelshark usr/local/bin/kshark-su-record
kernelshark usr/local/lib/
kernelshark usr/local/lib/kshark/
kernelshark usr/local/lib/kshark/libkshark-gui.so.0.9.8
kernelshark usr/local/lib/kshark/libkshark-plot.so.0.9.8
kernelshark usr/local/lib/kshark/libkshark.so.0.9.8
kernelshark usr/local/lib/kshark/plugin-missed_events.so
kernelshark usr/local/lib/kshark/plugin-sched_events.so
```
```
$ pacman -Fl onedrive-abraunegg | grep usr/local
onedrive-abraunegg usr/local/
onedrive-abraunegg usr/local/share/
onedrive-abraunegg usr/local/share/zsh/
onedrive-abraunegg usr/local/share/zsh/site-functions/
onedrive-abraunegg usr/local/share/zsh/site-functions/_onedrive
```
```
$ pacman -Fl xinput_calibrator | grep usr/local
xinput_calibrator usr/local/
xinput_calibrator usr/local/bin/
xinput_calibrator usr/local/bin/xinput_calibrator
xinput_calibrator usr/local/share/
xinput_calibrator usr/local/share/applications/
xinput_calibrator usr/local/share/applications/xinput_calibrator.desktop
xinput_calibrator usr/local/share/pixmaps/
xinput_calibrator usr/local/share/pixmaps/xinput_calibrator.svg
xinput_calibrator usr/local/share/pixmaps/xinput_calibrator.xpm
```

**Comment by colinkeenan** [comment]
I don't know why lilacbot assigned me. Which package does it want me to work on and why?

**Comment by lilydjwg** [comment]
@colinkeenan xinput_calibrator is under your name.

**Comment by yuyichao** [comment]
eternalterminal 有特殊需要, 不会改

https://aur.archlinux.org/packages/eternalterminal/#comment-748752
https://github.com/MisterTea/EternalTerminal/issues/316

**Comment by colinkeenan** [comment]
Is anyone using xinput_calibrator? I'm not anymore. I would like to drop the package if nobody needs it.

**Comment by yan12125** [comment]
@colinkeenan You may want to open an orphaning issue like [this one](https://github.com/archlinuxcn/repo/issues/1129)

**Comment by oldherl** [comment]
onedrive-abraunegg fixed

**Comment by yan12125** [comment]
Closing as all issues that can be fixed here are resolved.
