### ISSUE TITLE
 fcitx5-pinyin-zhwiki-rime fcitx5-pinyin-moegirl-rime

### ISSUE THREAD

**Issue by h0cheung** [archlinuxcn/repo#1686]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

两个词库包。
前者 cn 源里有 fcitx5-pinyin-zhwiki 包，可以考虑 split package，AUR 里有 rime-pinyin-zhwiki 包。
后者 fork 自前者，结构和前者类似。

* 主要语言和工具链 / Main Languages and Toolchains

python

* 上游链接 / Upstream Link

https://github.com/felixonmars/fcitx5-pinyin-zhwiki
https://github.com/outloudvi/fcitx5-pinyin-moegirl

* 为何需要这个软件包 / Why Need This Package

扩展 rime 的词库

**Comment by h0cheung** [comment]
[fcitx5-pinyin-zhwiki-rime](https://aur.archlinux.org/packages/fcitx5-pinyin-zhwiki-rime/)
[fcitx5-pinyin-moegirl-rime](https://aur.archlinux.org/packages/fcitx5-pinyin-moegirl-rime/)

已打包在 AUR，前者按照肥猫的包修改。

后者去掉 25 行和 30 行的 -o 参数可从 zh.moegirl.org 拉取最新词条，source 中的 moegirl.raw 也不再需要。
网络不稳定时不会自动重试，对网络稳定性要求较高，故上传 AUR 时使用了 release 中的文件。

**希望可以加入 cn 源（后者建议去掉 -o 参数每周更新）。**

**Comment by Xuanwo** [comment]
目前看来没有人愿意维护这个包，可以提一个 PR 来自行维护。

**Comment by outloudvi** [comment]
附注：后者已由 archlinuxcn/repo@6ca3779 完成。

**Comment by h0cheung** [comment]
@outloudvi 我也比较喜欢这种 split packages，但是 fcitx5-pinyin-zhwiki 的维护者似乎没有想改的意思

**Comment by Xuanwo** [comment]
@h0cheung fcitx5-pinyin-zhwiki 维护者不愿意拆包是他的个人决定，你可以决定的是要不要把 fcitx5-pinyin-zhwiki-rime 提交进入 cn 源

如果要的话可以提交 PR，如果不的话就到这里结束，无论何种情形，这个 issue 都将被关闭。
