### ISSUE TITLE
trojan-go-git 的 service 执行了错误的文件

### ISSUE THREAD

**Issue by woshiluo** [archlinuxcn/repo#1690]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* trojan-go-git
----

请在此补充说明。
Please describe in detail here.

`trojan-go-git` 的 `usr/lib/systemd/system/trojan-go.service` 中的 `ExecStart` 运行了 `/usr/lib/trojan-go`

但是 `/usr/lib/trojan-go` 是一个目录

```
$ pacman -Fl trojan-go-git | grep usr/lib/trojan-go
trojan-go-git usr/lib/trojan-go/
trojan-go-git usr/lib/trojan-go/geoip.dat
trojan-go-git usr/lib/trojan-go/geosite.dat
trojan-go-git usr/lib/trojan-go/trojan-go
```

```
$ pacman -Fl trojan-go-git | grep service
trojan-go-git usr/lib/systemd/system/trojan-go.service
trojan-go-git usr/lib/systemd/system/trojan-go@.service
```

**Comment by DuckSoft** [comment]
6d8540d151eee0b39b41f181a51b5235ef9fd5f7
