### ISSUE TITLE
请求打包 mpv-git

### ISSUE THREAD

**Issue by ayalhw** [archlinuxcn/repo#1691]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

mpv 的 git 版本

* 主要语言和工具链 / Main Languages and Toolchains

c++

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/mpv-git/
https://github.com/mpv-player/mpv

* 为何需要这个软件包 / Why Need This Package

MPV 的发布策略是每个版本号只是仓库的每月快照，git 版本可以使用最新的feature和bug fix

**Comment by yan12125** [comment]
I'm not sure if upstream mpv has changed a lot or not. If not, mpv-git needs to be built against ffmpeg-git as mpv often uses features not available in the latest stable release of ffmpeg, and mpv-git should be re-built whenever ffmpeg-git is updated (#1251). See b70397add1a8b00a60b5eeba534cd5546c9b871d.

**Comment by DuckSoft** [comment]
thanks for the hint. that sounds like hell...
I will do it when the compilation breaks/package dysfunctions.

> I'm not sure if upstream mpv has changed a lot or not. If not, mpv-git needs to be built against ffmpeg-git as mpv often uses features not available in the latest stable release of ffmpeg, and mpv-git should be re-built whenever ffmpeg-git is updated (#1251). See [b70397a](https://github.com/archlinuxcn/repo/commit/b70397add1a8b00a60b5eeba534cd5546c9b871d).

**Comment by DuckSoft** [comment]
```
❰ducksoft❙~❱✔≻ pacman -Ss mpv-git
archlinuxcn/mpv-git 0.32.0_567_gafe2b83183-1
    Video player based on MPlayer/mplayer2 (git version)
```
