### ISSUE TITLE
Add my updated gpg key to archlinuxcn-keyring

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#170]
My key expired 2 days ago so I extended it another year. I didn't realize I also needed to send the key to a public keyserver, but did that today. Now, I think archlinuxcn-keyring also has to be updated.

My updated key can be retrieved with `gpg --keyserver pgp.mit.edu --search-keys 0940E3F9`

**Comment by colinkeenan** [comment]
Seems like this request was misguided. I am not having any issues on machines I have access to. I made this request due to an issue raised in https://github.com/archlinuxcn/repo/issues/167.

**Comment by colinkeenan** [comment]
I just installed archlinux on a new older machine for somebody & ran into the issue with my key still. Packages I uploaded months ago work fine, but recent packages (numix-circle-icon-theme-git) see the signature as corrupt. It's possible for the user to get around this by manually updating keys, but it seems the archlinuxcn-keyring should include my updated key to expire in November this year instead of showing already expired last year. I don't know how that's tracked, but something needs to be done.

**Comment by colinkeenan** [comment]
Please update archlinuxcn-keyring to include my key as expiring November 2016 instead of already expired last November.

**Comment by farseerfc** [comment]
Sorry for the delay. Finally I have time to figure out how to build the keyring package.
I have built and uploaded a new release of `archlinuxcn-keyring` and it's now in our repo. Now your packages signed with the new key should be normal for every user.

Unfortunately you may need to rebuild all your old packages that signed by your old key, here is a list of these packages (I got the list with `pacman -Slq archlinuxcn | LANG=C pacman -Si - | grep "Unknown Packager" -B20 | grep "^Name\s*:" | cut -d":" -f2` , they may contain some other people's packages):

- [ ] acroread
- [ ] acroread-fonts-systemwide
- [ ] assimp-net
- [ ] bbswitch-dkms
- [ ] binx32-python2
- [ ] brother-hl2140
- [ ] ccal
- [ ] cdu
- [ ] cla
- [ ] clup
- [ ] cower
- [ ] danmaku2ass-git
- [ ] gcc-ada-multilib-x32
- [ ] gcc-fortran-multilib-x32
- [ ] gcc-go-multilib-x32
- [ ] gcc-libs-multilib-x32
- [ ] gcc-multilib-x32
- [ ] gcc-objc-multilib-x32
- [ ] gcc-x32-seed
- [ ] glibc-x32-seed
- [ ] gnome-search-tool-no-nautilus
- [ ] gtk-theme-config
- [ ] gvfs-no-bluray
- [ ] hplip-plugin
- [ ] kdeplasma-applets-menubar
- [ ] ld-lsb
- [ ] lib32-dbus-glib
- [ ] lib32-gconf
- [ ] lib32-glew1.10
- [ ] lib32-jansson
- [ ] lib32-kmod
- [ ] lib32-libappindicator-gtk2
- [ ] lib32-libappindicator-gtk3
- [ ] lib32-libappindicator-sharp
- [ ] lib32-libcurl-gnutls
- [ ] lib32-libdaemon
- [ ] lib32-libgcrypt15
- [ ] lib32-libgnutls28
- [ ] lib32-libindicator-gtk2
- [ ] lib32-libindicator-gtk3
- [ ] lib32-libjpeg6-turbo
- [ ] lib32-libmbim
- [ ] lib32-libmm-glib
- [ ] lib32-libndp
- [ ] lib32-libnewt
- [ ] lib32-libqmi
- [ ] lib32-libudev0
- [ ] lib32-pangox-compat
- [ ] lib32-slang
- [ ] libx32-acl
- [ ] libx32-attr
- [ ] libx32-bzip2
- [ ] libx32-cracklib
- [ ] libx32-curl
- [ ] libx32-db
- [ ] libx32-e2fsprogs
- [ ] libx32-expat
- [ ] libx32-flex
- [ ] libx32-fontconfig
- [ ] libx32-freetype2
- [ ] libx32-gcc-libs
- [ ] libx32-gdbm
- [ ] libx32-geoip
- [ ] libx32-glib2
- [ ] libx32-glibc
- [ ] libx32-harfbuzz
- [ ] libx32-icu
- [ ] libx32-jansson
- [ ] libx32-jemalloc
- [ ] libx32-keyutils
- [ ] libx32-krb5
- [ ] libx32-libcap
- [ ] libx32-libdbus
- [ ] libx32-libffi
- [ ] libx32-libgcrypt
- [ ] libx32-libgpg-error
- [ ] libx32-libidn
- [ ] libx32-libldap
- [ ] libx32-libpng
- [ ] libx32-libssh2
- [ ] libx32-libtirpc
- [ ] libx32-libx11
- [ ] libx32-libxau
- [ ] libx32-libxcb
- [ ] libx32-libxdmcp
- [ ] libx32-libxext
- [ ] libx32-libxft
- [ ] libx32-libxml2
- [ ] libx32-libxrender
- [ ] libx32-libxslt
- [ ] libx32-libxss
- [ ] libx32-libyaml
- [ ] libx32-mpdecimal
- [ ] libx32-ncurses
- [ ] libx32-nginx
- [ ] libx32-openssl
- [ ] libx32-pam
- [ ] libx32-pcre
- [ ] libx32-postgresql
- [ ] libx32-postgresql-libs
- [ ] libx32-python
- [ ] libx32-python-greenlet
- [ ] libx32-readline
- [ ] libx32-redis
- [ ] libx32-sqlite
- [ ] libx32-systemd
- [ ] libx32-tcl
- [ ] libx32-tk
- [ ] libx32-util-linux
- [ ] libx32-uwsgi
- [ ] libx32-uwsgi-plugin-cgi
- [ ] libx32-uwsgi-plugin-python
- [ ] libx32-uwsgi-plugin-webdav
- [ ] libx32-xz
- [ ] libx32-yajl
- [ ] libx32-zlib
- [ ] mkinitcpio-colors-git
- [ ] monogame
- [ ] mozplugger
- [ ] nautilus-data
- [ ] nodejs-tiddlywiki
- [ ] nvidia-texture-tools
- [ ] opentk
- [ ] opentk-docs
- [ ] plasmate
- [ ] python-more_itertools
- [ ] python2-more_itertools
- [ ] python2-pypdf2
- [ ] qsanguosha
- [ ] ruby-json_pure
- [ ] ruby-rgen
- [ ] setcolors-git
- [ ] sharpfonts
- [ ] silentcast
- [ ] simage
- [ ] simage-debug
- [ ] simple-mtpfs
- [ ] tchrome
- [ ] ttf-monaco
- [ ] ttf-ms-fonts
- [ ] vertex-themes
- [ ] vokoscreen
- [ ] vokoscreen-git
- [ ] wallch
- [ ] wordbiz
- [ ] xfce4-pulseaudio-plugin
- [ ] xinput_calibrator
- [ ] xrdp
- [ ] xz-git

**Comment by lilydjwg** [comment]
@farseerfc most packagers don't set their `PACKAGER` variable...

**Comment by farseerfc** [comment]
@lilydjwg good point .. I just don't know other way to pin point these packages.

@colinkeenan Sorry for the misleading information. Please ignore my package list above (that I have deleted) and rebuild your packages that signed with your old key.

**Comment by colinkeenan** [comment]
OK. I hadn't looked all the way through it, but most of it looked right anyway. I know how to figure it out for myself though. I have only recently set my `PACKAGER` variable in `makepkg.conf`

**Comment by colinkeenan** [comment]
I have been using nvchecker. Not long after I started packaging for archlinuxcn, I translated the wiki page for nvchecker and added some of my own ideas (https://github.com/archlinuxcn/repo/wiki/use-nvchecker-to-check-new-version). One of those was a command to generate `old_ver.txt`. For me, that command is `git whatchanged --author=colin | grep "^:" | cut -f2 | cut -f1 -d'/' | uniq | xargs -I% pacman -Ss "^%" | grep "^archlinuxcn/" | cut -f2 -d'/' | cut -f1,2 -d' ' | sort | uniq > ~/old_ver.txt`

Now, starting from old_ver.txt, I generated a list of my packages: `cut -f1 -d' ' old_ver.txt > packages`

I've decided to just rebuild all the packages that don't have the `PACKAGER` variable set to my name and email. I'm not sure what the best way to see that is, but here's what I did:

`while read package; do printf "%s\t\t\t\t\t%s\n" $package "$(pacman -Si $package | grep Packager)">>packagers.txt; done < packages`

Which created a kind of messy text file `packagers.txt`:
[packagers.txt](https://github.com/archlinuxcn/repo/files/183537/packagers.txt)

I was surprised to see Felix Yan on one of them, but anyway, it's enough for me to see what packages to rebuild.

**Comment by colinkeenan** [comment]
I used vim to delete all the lines with Colin on them, and then finally created the list with `cut -f1 packagers.txt > needbuild.tx`. This produced the following list of 52 packages:

acroread
assimp-net
cdu
cla
clup
cower
gnome-search-tool-no-nautilus
gtk-theme-config
hplip-plugin
lib32-dbus-glib
lib32-gconf
lib32-glew1.10
lib32-jansson
lib32-kmod
lib32-libappindicator-gtk2
lib32-libappindicator-gtk3
lib32-libcurl-gnutls
lib32-libdaemon
lib32-libgcrypt15
lib32-libgnutls28
lib32-libindicator-gtk2
lib32-libindicator-gtk3
lib32-libjpeg6-turbo
lib32-libmbim
lib32-libmm-glib
lib32-libndp
lib32-libnewt
lib32-libqmi
lib32-libudev0
lib32-pangox-compat
lib32-slang
mkinitcpio-colors-git
nant
nautilus-data
nodejs-tiddlywiki
nvidia-texture-tools
opentk
opentk-docs
python2-more_itertools
python2-pypdf2
setcolors-git
sharpfonts
silentcast
simple-mtpfs
tchrome
ttf-ms-fonts
vertex-themes
wallch
wordbiz
xfce4-pulseaudio-plugin
xinput_calibrator
xrdp

**Comment by zsrkmyn** [comment]
On Mon, Mar 21, 2016 at 10:34:48AM -0700, Jiachen Yang wrote:
> Sorry for the delay. Finally I have time to figure out how to build the keyring package.
> I have built and uploaded a new release of `archlinuxcn-keyring` and it's now in our repo. Now your packages signed with the new key should be normal for every user.
> 
> Unfortunately you may need to rebuild all your old packages that signed by your old key, here is a list of these packages (I got the list with `pacman -Slq archlinuxcn | LANG=C pacman -Si - | grep "Unknown Packager" -B20 | grep "^Name\s*:" | cut -d":" -f2` , they may contain some other people's packages):
> 

It's not hard to find who are the owners of these packages using the
one-line script based on @farseerfc's:

```
cd gitrepo; for i in $(pacman -Slq archlinuxcn | pacman -Si - | grep "Unknown Packager" -B20 | grep "^Name\s*:" | cut -d":" -f2); do au=$(git log -1 --pretty=format:'%an' -- "$i"/PKGBUILD); echo -e "$i\t$au"; done
```

-- 
Regards,
Stephen

**Comment by farseerfc** [comment]
As no further problems, I will close this issue for now.
