### ISSUE TITLE
请求添加ffmpeg-full和ffmpeg-full-git

### ISSUE THREAD

**Issue by abcfy2** [archlinuxcn/repo#1702]
### 问题类型 / Type of issues

* 软件打包请求 / package request

- ffmpeg-full
- ffmpeg-full-git

AUR仓库地址: 

- https://aur.archlinux.org/packages/ffmpeg-full/
- https://aur.archlinux.org/packages/ffmpeg-full-git/

----

* 简述 / Brief Description

ffmpeg 上有版本按照GPL协议编译，缺失太多的编解码器，而AUR仓库已经有了ffmpeg-full包，可以提供非常完整的ffmpeg体验

* 主要语言和工具链 / Main Languages and Toolchains

gcc

* 上游链接 / Upstream Link

https://www.ffmpeg.org/

* 为何需要这个软件包 / Why Need This Package

ffmpeg 上有版本按照GPL协议编译，缺失太多的编解码器，而AUR仓库已经有了ffmpeg-full包，可以提供非常完整的ffmpeg体验。而AUR仓库的投票数和维护度都不错，应该可以直接拿来构建。

**Comment by oldherl** [comment]
按照AUR作者标注，
许可协议: custom: nonfree and unredistributable

所以不可进入ArchCN源分发。
