### ISSUE TITLE
acpitool

### ISSUE THREAD

**Issue by KiteAB** [archlinuxcn/repo#1707]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

用于代替 apm 的工具

* 主要语言和工具链 / Main Languages and Toolchains

C++

mpv-ahjolinna (make)

mpv-ahjolinna (optional)

mpv-ahjolinna-git (optional)

mpv-ahjolinna-git (make)

gcc-libs (gcc-libs-multilib-x32, fastgcc, gcc-libs-git, gcc-libs-multilib-git)

* 上游链接 / Upstream Link

http://sourceforge.net/projects/acpitool/

* 为何需要这个软件包 / Why Need This Package

AUR 中的此包位于 SourceForge，下载速度慢，提速

**Comment by DuckSoft** [comment]
这个包的最后一次更新时间是 2016 年……看起来不会再更新了。
我就脏一点，直接把 AUR 上所有文件都梭过来，不再跟随 AUR 了，免得包被有心人接走乱打一些不好的东西。

**Comment by KiteAB** [comment]
所以说什么时候提交到正式源里？

**Comment by DuckSoft** [comment]
2abb202b506679a56e22e91f642fe067b589795c

**Comment by KiteAB** [comment]
➜ ~ sudo pacman -Sy
[sudo] password for kiteab:
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archlinuxcn is up to date
➜ ~ sudo pacman -S acpitool
error: target not found: acpitool
还是等明天吧 /哭笑
