### ISSUE TITLE
terminus-font-ttf is out of date

### ISSUE THREAD

**Issue by CoelacanthusHex** [archlinuxcn/repo#1708]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* terminus-font-ttf

----

4.47.0 and new depends

Upstream: https://aur.archlinux.org/packages/terminus-font-ttf/

**Comment by oldherl** [comment]
https://github.com/archlinuxcn/repo/pull/1706

**Comment by yan12125** [comment]
Fixed for a while https://build.archlinuxcn.org/packages/#/terminus-font-ttf
