### ISSUE TITLE
PR: ksnip

### ISSUE THREAD

**Issue by amitbha** [archlinuxcn/repo#1714]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description  
一个基于QT的跨平台截屏工具，具有丰富的图片标注功能

* 主要语言和工具链 / Main Languages and Toolchains
C++

* 上游链接 / Upstream Link
https://github.com/ksnip/ksnip

* 为何需要这个软件包 / Why Need This Package
linux截屏工具很多，但从图片标注功能来衡量，泛善可呈，比windows平台差太远，甚至连qq截屏都不如

**Comment by DuckSoft** [comment]
aur dependency chain detected: `ksnip` -> `kimageannotator` -> `kcolorpicker`
wip.

**Comment by DuckSoft** [comment]
Done. Please wait for the package being processed by lilac automatically.
