### ISSUE TITLE
adobe-source-han-mono 系列 LICENSE.md 文件冲突

### ISSUE THREAD

**Issue by edward-p** [archlinuxcn/repo#1722]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* adobe-source-han-mono-fonts

----

例如同时装有 `adobe-source-han-mono-cn-fonts` 和 `adobe-source-han-mono-tw-fonts` 时出现报错：
```
/usr/share/licenses/adobe-source-han-mono-otc-fonts/LICENSE.md exists in both 'adobe-source-han-mono-hk-fonts' and 'adobe-source-han-mono-cn-fonts'
```

**Comment by lilydjwg** [comment]
呃，包名得写 pkgbase，不然 lilac 不认得。

**Comment by dctxmei** [comment]
已經向上游反應情況。

**Comment by dctxmei** [comment]
已經向上游反映情況。

**Comment by dctxmei** [comment]
上游已經修復：
[ed0344bc3e628f29cb1781fa7ab7d4196a7248cd](https://aur.archlinux.org/cgit/aur.git/commit/?h=adobe-source-han-mono-fonts&id=ed0344bc3e628f29cb1781fa7ab7d4196a7248cd)
