### ISSUE TITLE
xorg-font-utils should be removed from ttf-wps-fonts's dependency list

### ISSUE THREAD

**Issue by Aloxaf** [archlinuxcn/repo#1729]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* ttf-wps-fonts

----

`xorg-font-utils` [has been removed](https://www.archlinux.org/todo/removal-of-xorg-font-utils-transitional-package/) and this package can't be installed now.

**Comment by Aloxaf** [comment]
光速修复，tql

**Comment by petronny** [comment]
@DuckSoft 4583a4a 会被lilac覆盖掉的

已反馈至AUR

**Comment by Aloxaf** [comment]
AUR 已修复
