### ISSUE TITLE
add vscode-bin

### ISSUE THREAD

**Issue by Arondight** [archlinuxcn/repo#173]
[喵喵喵][ID]
[ID]: https://aur.archlinux.org/packages/vscode-bin/ "跳AUR"

**Comment by farseerfc** [comment]
I have added `visual-studio-code` and it should be built tonight.
For the requested `vscode-bin`, it is a duplicate with the added package, and should be removed from aur soon.
Please reopen this issue if `vscode-bin` is more desirable than `visual-studio-code`.
