### ISSUE TITLE
chromium-vaapi上游已经包含补丁

### ISSUE THREAD

**Issue by abcfy2** [archlinuxcn/repo#1743]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

*  chromium-vaapi

----

Archlinux官方仓库已经给chromium打上了vaapi补丁: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/chromium&id=0cbb8c4205a73ceb76066477fef42e55ae5aa394

所以现在直接从archlinux官方装chromium就带有这个效果了

**Comment by MarvelousBlack** [comment]
官方源引入支援 vaapi 的 flag 是在
 https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/chromium&id=0cbb8c4205a73ceb76066477fef42e55ae5aa394 
而 修復 intel 部分集顯 vp9 的修復補丁是在
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/chromium&id=93b5b90621b4827084288197c6e0e09b987b372a 。
這個比你提到的 
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/chromium&id=0cbb8c4205a73ceb76066477fef42e55ae5aa394 要早差不多兩個星期。
我在官方源的 chromium 啓用 use_vaapi=true 的 flag 的時候就和肥貓聊過這個。現在這個包（chromium-vaapi）和官方源的 chromium 還是有兩個不同的地方，chromium-vaapi 帶有支持 nvidia 和 wayland 下啓用 vaapi 的補丁，因此還是有保留的意義。至於這個包是不是應該改名，這個我還在考慮中。
