### ISSUE TITLE
intellij-idea-community-edition-no-jre

### ISSUE THREAD

**Issue by Trumeet** [archlinuxcn/repo#1746]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

`community/intellij-idea-community-edition` 总是依赖 Java 11，AUR 里的 `intellij-idea-community-edition-no-jre` 不依赖 Java 11，所以会比较方便。 

* 主要语言和工具链 / Main Languages and Toolchains

Java

* 上游链接 / Upstream Link

[intellij-idea-community-edition-no-jre](https://aur.archlinux.org/packages/intellij-idea-community-edition-no-jre/)

* 为何需要这个软件包 / Why Need This Package

同简述，
`community/intellij-idea-community-edition` 总是依赖 Java 11，AUR 里的 `intellij-idea-community-edition-no-jre` 不依赖 Java 11，所以会比较方便。

**Comment by Xuanwo** [comment]
Java 11 是 IDEA 推荐的 JRE runtime，有什么特别的理由不用吗

**Comment by Xuanwo** [comment]
@Trumeet Any update on this issue？

**Comment by Trumeet** [comment]
> Java 11 是 IDEA 推荐的 JRE runtime，有什么特别的理由不用吗

@Xuanwo 我个人平时更多用 Java 8，而且个人使用的 Gradle 版本在 11 上经常有一些奇妙的问题。个人觉得作为包还是给用户一个选择比较好。
11 对于 Idea 是必须的吗？

**Comment by Xuanwo** [comment]
啊，原来 intellij-idea-community-edition 在社区源，我个人用的是 aur 的 intellij-idea-ultimate-edition。

现在有两个选择

- 自己切换 IDEA 的 runtime
- 提 PR 来维护 intellij-idea-community-edition-no-jre

**Comment by Trumeet** [comment]
> 啊，原来 intellij-idea-community-edition 在社区源，我个人用的是 aur 的 intellij-idea-ultimate-edition。
> 
> 现在有两个选择
> 
> * 自己切换 IDEA 的 runtime
> * 提 PR 来维护 intellij-idea-community-edition-no-jre

如果能维护就更好了，我看一下如何 PR，多谢！
