### ISSUE TITLE
lazydocker

### ISSUE THREAD

**Issue by KiteAB** [archlinuxcn/repo#1747]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

The lazier way to manage everything docker

* 主要语言和工具链 / Main Languages and Toolchains

Docker >= 1.13 (API >= 1.25)

Docker-Compose >= 1.23.2 (optional)

* 上游链接 / Upstream Link

https://github.com/jesseduffield/lazydocker

* 为何需要这个软件包 / Why Need This Package

docker manage

**Comment by KiteAB** [comment]
14 days ago??? r u kidding me??

**Comment by oldherl** [comment]
Don't be mad. Seams that no maintainer is interested in this package. Sorry.

**Comment by DuckSoft** [comment]
Be polite. If you can, you up. If no can, don't shout.

**Comment by lilydjwg** [comment]
Don't bump package requests. New information, or wait until it's closed.

**Comment by KiteAB** [comment]
I'm not sad, just want to sigh /Laugh and cry
