### ISSUE TITLE
onedrive-abraunegg缺少systemd配置

### ISSUE THREAD

**Issue by dianlujitao** [archlinuxcn/repo#1748]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* onedrive-abraunegg

----

请在此补充说明。
Please describe in detail here.

该软件包使用 autoconf 检测 systemd 是否存在并动态打包相关配置 https://github.com/abraunegg/onedrive/blob/2b7e36d57fba30341f2075cc90581d78dfd5e105/configure#L2381-L2417 ，是否由于编译的 chroot 过于干净导致没有检测到？ps：archcn以前打的包有这些配置，不知道更新到哪个版本后就消失了

**Comment by dctxmei** [comment]
的確如你所說。

在手動添加 systemd 包後再進行編譯就會出現 .service 文件了，我會將此反饋給該 AUR 包的維護者。

**Comment by dctxmei** [comment]
該問題已經解決。
