### ISSUE TITLE
vim-plug should not  depend on vim 

### ISSUE THREAD

**Issue by oakszyjrnrdy** [archlinuxcn/repo#1750]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* vim-plug

----

Thank you for your work and here is my question. 

I use neovim and vim-plug and I don't want to install vim. However, vim-plug is now dependent on vim. Since vim-plug can be used with vim or neovim, it's not reasonable to make it depend on vim. Will you modify the vim-plug package or is there any workaround I can use?

**Comment by SilverRainZ** [comment]
Hello, vim-plug tracks vim-plug on AUR, please report this issue to AUR

**Comment by oakszyjrnrdy** [comment]
I see. Thank you and I'll close this issue.
