### ISSUE TITLE
Ventoy

### ISSUE THREAD

**Issue by SamLukeYes** [archlinuxcn/repo#1754]
### 问题类型 / Type of issues

* 软件打包请求 / package request

> ventoy

---- 

* 简述 / Brief Description

> Ventoy是一个制作可启动U盘的开源工具。有了Ventoy你就无需反复地格式化U盘，你只需要把ISO文件拷贝到U盘里面就可以启动了，无需其他操作。 你可以一次性拷贝很多个不同类型的ISO文件，在启动时Ventoy会显示一个菜单来选择。 无差异支持Legacy BIOS和UEFI模式。

* 主要语言和工具链 / Main Languages and Toolchains

> GNU工具链

* 上游链接 / Upstream Link

[https://ventoy.net](url)

* 为何需要这个软件包 / Why Need This Package

> 目前Manjaro已经将ventoy收入了community仓库，而Arch用户仍然只能通过AUR获取这个软件包。不如将其收入CN源，方便Arch用户安装和更新ventoy。

**Comment by DuckSoft** [comment]
979d75f6a7320c21c5000823d63a60d343f35495
