### ISSUE TITLE
stapler-git depends on python-pypdf2 which is not in the repo

### ISSUE THREAD

**Issue by oldherl** [archlinuxcn/repo#1758]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* stapler-git

----

请在此补充说明。
Please describe in detail here.

stapler-git depends on python-pypdf2 which is not in the official archlinux repo nor in archlinuxcn repo.

Either python-pypdf2 should be included or stapler-git should be discarded as well.

**Comment by yan12125** [comment]
stapler-git is removed in ff9033c9b04d7a345f15daaa49989da1b3dccfb1.
