### ISSUE TITLE
ttf-cascadia-code-new

### ISSUE THREAD

**Issue by CamberLoid** [archlinuxcn/repo#1762]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

由于官方仓库 `community/ttf-cascadia-code` (版本号 1910.04-2) 无非连字的字体   
而上游自版本号1911开始提供非连字字体`Cascadia Mono` ([Reference](https://github.com/microsoft/cascadia-code/releases/tag/v1911.21))   
另外, 想着自己提个PR, 但是碍于目前并不了解 archlinuxcn/repo 的工作流    
故提出本Issue

* 主要语言和工具链 / Main Languages and Toolchains

* 上游链接 / Upstream Link

https://github.com/microsoft/cascadia-code/
https://aur.archlinux.org/packages/ttf-cascadia-code-new/

* 为何需要这个软件包 / Why Need This Package

(See Brief Descrption)

**Comment by CamberLoid** [comment]
PS:  
`community/ttf-cascadia-code` 的版本号为 1910.04. 该版本于去年10月发布, `pacman -Si` 显示的编译日期为2020-06-29.  
目前上游最新为今年7月初发布的 2007

**Comment by CamberLoid** [comment]
已经创建PR #1765

**Comment by axionl** [comment]
或许应该想办法通知一下 community 的维护者进行更新

**Comment by CamberLoid** [comment]
[community/ttf-cascadia-code](https://www.archlinux.org/packages/community/any/ttf-cascadia-code) has been updated 
Closing issue now.
