### ISSUE TITLE
twemoji-color-font

### ISSUE THREAD

**Issue by KiteAB** [archlinuxcn/repo#1766]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

A color and B&W emoji SVG-in-OpenType font by Twitter with support for ZWJ, skin tone modifiers and country flags

* 主要语言和工具链 / Main Languages and Toolchains

#### Dependencies (2)
fontconfig (fontconfig-srb, fontconfig-infinality-ultimate, fontconfig-ubuntu, fontconfig-infinality, fontconfig-infinality-remix, fontconfig-git)

ttf-bitstream-vera (optional) – default fallback font used for configuration

#### Required by (6)
discord-ptb (requires emoji-font) (optional)

dmenu-ekollof-git

dwm-ekollof-git

hydrus (requires emoji-font)

nodejs-gitmoji-cli (optional)

wire-desktop-git (requires emoji-font) (optional)

* 上游链接 / Upstream Link

https://github.com/eosrei/twemoji-color-font

* 为何需要这个软件包 / Why Need This Package

none

**Comment by KiteAB** [comment]
refresh

**Comment by lilydjwg** [comment]
As I've said, do not bump package requests. Don't force me to ban you.

**Comment by KiteAB** [comment]
I just make it display to my GitHub main page...
