### ISSUE TITLE
baidunetdisk-bin 3.3.2-1: Executable is missing

### ISSUE THREAD

**Issue by outloudvi** [archlinuxcn/repo#1769]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* baidunetdisk-bin

----

The package`baidunetdisk-bin` 3.3.2-1 does not contain `/usr/bin/baidunetdisk`.

SHA-1 as below:

```
37ff3fabe198e388d39f0288595f74d68264e99b  baidunetdisk-bin-3.0.1.2-10-x86_64.pkg.tar.zst
9d88aec9dba43b6bbb36b4c452c7f7c787b4174b  baidunetdisk-bin-3.3.2-1-x86_64.pkg.tar.zst
```

**Comment by panjk0518** [comment]
My `baidunetdisk-bin` is able to startup and its main program is in `/usr/lib/baidunetdisk/baidunetdisk`. 
![2020-08-06_13-10](https://user-images.githubusercontent.com/50908468/89493244-4d722e80-d7e6-11ea-9367-72bf31e4ec6c.png)

**Comment by outloudvi** [comment]
Oh... I see that. It turned out that somehow the original `/usr/share/applications` desktop file is masked by one in `~/.local/share/applications` (IDK why there's one), resulting in a failure to update the bin path. Thank you @panjk0518!
