### ISSUE TITLE
rebuild linux-pf against gcc 5

### ISSUE THREAD

**Issue by SolarAquarion** [archlinuxcn/repo#177]

**Comment by hzy199411** [comment]
Did you mean rebuild linux-pf against gcc 5.3.0? I will rebuild it later.
As the gcc 5.3.0 is in [testing] repo now, I will push the rebuilt version to archlinux after the gcc 5.3.0 going to [core] repo.

**Comment by SolarAquarion** [comment]
Ok,  thanks

**Comment by hzy199411** [comment]
@SolarAquarion , I find that we don't need rebuild linux-pf after upgrading gcc 5.2.0  to gcc 5.3.0. Did you have some problem when using gcc 5.x with linux-pf?

**Comment by SolarAquarion** [comment]
No. But I currently use testing.

**Comment by hzy199411** [comment]
In the [testing] repo, After they bumped the gcc version, they didn't rebuild the linux package, So I think that we don't need to rebuild linux-pf because all gcc 5.x are compatible. 
If you don't have other problems, I will close this issue.

**Comment by SolarAquarion** [comment]
Close it then
