### ISSUE TITLE
Zoom package is still not available after included in git repo for a month

### ISSUE THREAD

**Issue by cuihaoleo** [archlinuxcn/repo#1775]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* zoom

----

For unknown reason, Zoom package is still not available after included in our git repo (0a28b07770c02dcbbf70fe1c94874d9c34b29919) for a month. Please inspect it.

```
$ pacman -Si archlinuxcn/zoom
error: package 'archlinuxcn/zoom' was not found
```

**Comment by yuyichao** [comment]
Do we need/have permission to redistribute the package?

**Comment by cuihaoleo** [comment]
Maybe yes?

According to https://zoom.us/terms:

> Limitations on Use.You may not reproduce, resell, or distribute the Services or any reports or data generated by the Services for any purpose unless You have been specifically permitted to do so under a separate agreement with Zoom.

Here, "Services" is defined as:

> ......THE WEBSITE AND PRODUCTS AND SERVICES AND ASSOCIATED SOFTWARE (COLLECTIVELY, THE "SERVICES") OF ZOOM VIDEO COMMUNICATIONS, INC. AND ITS AFFILIATES ("ZOOM")

**Comment by colinkeenan** [comment]
Should I just remove it from the repo then?

**Comment by colinkeenan** [comment]
Could the reason it's not available be that I'm uploading the "orig" file included from Zoom and not the package built by the PKGBUILD: `zoom-5.1.422789.0705_orig . . .`. I did that because the package built by PKGBUILD doesn't work on my machine, but the binary labeled "orig" works fine. I have not actually been building it, just using `makepkg -o` to download source files and run prepare.

**Comment by colinkeenan** [comment]
I just realized that the `orig` file is `xz` but we've just recently switched to `zst`. For the latest update, I ran `makepkg -o`, `xz -d . . .`, and `zstd -z . . .`. I also renamed the package removing `orig` from the name. I tested and it works fine on my machine, so uploaded it. I think this will make the package available.
