### ISSUE TITLE
megasync: error while loading shared libraries: libraw.so.19: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SamLukeYes** [archlinuxcn/repo#1780]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* megasync

----

megasync-4.3.1.0-1 需要 libraw.so.19，安装 AUR 上的 libraw19 后才可以正常运行。

PS：我目前使用的发行版是 Manjaro (unstable branch)，稳妥起见还是在此声明一下

**Comment by MarvelousBlack** [comment]
libraw 已經進入 extra 倉庫，需要到對 megasync 進行rebuild。
```
$ Si libraw
Repository      : extra
Name            : libraw
Version         : 0.20.0-1
Description     : A library for reading RAW files obtained from digital photo cameras (CRW/CR2, NEF, RAF, DNG, and others)
Architecture    : x86_64
URL             : https://www.libraw.org/
Licenses        : CDDL  LGPL
Groups          : None
Provides        : None
Depends On      : lcms2  jasper
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 421.63 KiB
Installed Size  : 2583.78 KiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Fri Jul 24 00:18:21 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
[archlinuxcn] 仓库只支持 Arch Linux，在衍生发行版上使用可能出现问题。

**Comment by lilydjwg** [comment]
megasync 打包连续失败四次了。

**Comment by yan12125** [comment]
megasync has `libpdfium-nojs` in `repo_depends`. The former is built and pushed manually

```
$ pacman -Si libpdfium-nojs | grep Packager
Packager        : yk <yk@build.archlinuxcn.org>
```
As a result, lilac cannot find the package file for `repo_depends` as it finds packages in the local git repo only [1], not the [archlinuxcn] repository.

[1] https://github.com/archlinuxcn/lilac/blob/4e116c43f4bc2895b77f75b11cf68eb6e6cfbdf1/lilac2/packages.py#L92

**Comment by lilydjwg** [comment]
I've linked them into lilac's directory and hope it will work on next build.

**Comment by SamLukeYes** [comment]
4.3.3.0-1 已经不需要 libraw19 了
