### ISSUE TITLE
[package request] gron

### ISSUE THREAD

**Issue by yejingchen** [archlinuxcn/repo#1788]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

From its description:

Make JSON greppable!

gron transforms JSON into discrete assignments to make it easier to `grep` for what you want and see the absolute 'path' to it.
It eases the exploration of APIs that return large blobs of JSON but have terrible documentation.

<pre>
▶ <b>gron</b> "https://api.github.com/repos/tomnomnom/gron/commits?per_page=1" | fgrep "commit.author"
json[0].commit.author = {};
json[0].commit.author.date = "2016-07-02T10:51:21Z";
json[0].commit.author.email = "mail@tomnomnom.com";
json[0].commit.author.name = "Tom Hudson";
</pre>

* 主要语言和工具链 / Main Languages and Toolchains

go 1.7+

* 上游链接 / Upstream Link

https://github.com/tomnomnom/gron

* 为何需要这个软件包 / Why Need This Package

easy manipulating json

**Comment by yuyichao** [comment]
https://github.com/archlinuxcn/repo/pull/1761 clearly doesn't work ....
