### ISSUE TITLE
Can you update all the *-git packages to the latest git revisions

### ISSUE THREAD

**Issue by SolarAquarion** [archlinuxcn/repo#179]

**Comment by lilydjwg** [comment]
Can you tell us which are out of date? Most active ones should be updated automatically.

**Comment by SolarAquarion** [comment]
Well, a non git package, byobu is out of date. I used libfm-gtk3-git as
libfm-git so I can use pcmanfm gtk3 version. So pcmanfm qt version is out
of date.

**Comment by lilydjwg** [comment]
So these two are out-of-date:

* [ ] byobu @phoenixlzx 
* [ ] pcmanfm-qt-git @ykelvis

**Comment by SolarAquarion** [comment]
Probably more.  I'll update the list once I get a list via a pacman update
