### ISSUE TITLE
anaconda 图形界面程序问题

### ISSUE THREAD

**Issue by silkriver** [archlinuxcn/repo#1794]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* anaconda

----

anaconda-navigator 无法启动，看起来是因为其中推荐的 vscode 和 pycharm 的 deb 和 rpm 包在 arch 下其实不能装，这个是 sudo vim /opt/anaconda/lib/python3.8/site-packages/anaconda_navigator/api/external_apps/__init__.py 设置 apps = {} 就好了

spyder 无法启动，报错信息如下
Qt WebEngine ICU data not found at /build/anaconda/pkg/anaconda/opt/anaconda/resources. Trying parent directory...
Qt WebEngine ICU data not found at /build/anaconda/pkg/anaconda/opt/anaconda. Trying application directory...
Qt WebEngine ICU data not found at /opt/anaconda/libexec. Trying fallback directory... The application MAY NOT work.
Path override failed for key base::DIR_QT_LIBRARY_DATA and path '/home/leo/.QtWebEngineProcess'

**Comment by petronny** [comment]
6906cb993d41c945cacadc5a736225cdc25957da
