### ISSUE TITLE
SDK Platforms和Android SDK Build Tools在Android Studio中显示过期

### ISSUE THREAD

**Issue by Galaxy0419** [archlinuxcn/repo#1795]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* android-platform
* android-sdk-build-tools
----

**Comment by yan12125** [comment]
這三個包都是跟隨AUR。我已經將 https://aur.archlinux.org/packages/android-sdk-build-tools/ 以及 https://aur.archlinux.org/packages/android-platform/ flag out-of-date。下次你可以直接到AUR回報。

android-sdk-platform-tools 在我這邊顯示 30.0.4 已經是最新版。

**Comment by yan12125** [comment]
android-sdk-build-tools 與 android-platform 已更新 (31b5db2fcb7fc0f06fd07dcbb898b36c8160c251, 2e678385f5be5a181c96a4b271c363eb297c0f33)。
