### ISSUE TITLE
打包请求:deepin-wine-wechat

### ISSUE THREAD

**Issue by hehelego** [archlinuxcn/repo#1798]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

  打包aur:deepin-wine-wechat

* 主要语言和工具链 / Main Languages and Toolchains

   deepinwine

* 上游链接 / Upstream Link

https://github.com/countstarlight/deepin-wine-wechat-arch

* 为何需要这个软件包 / Why Need This Package

  archlinuxcn repo中收录的wine-wechat bug非常多,而且使用者很少,可以查找到的问题解决方案大都过期。  
  archlinuxcn repo收录的deepin-wine-qq,deepin-wine-TIM有理由再收录一个deepin--wine-wechat.

**Comment by whriedplanck** [comment]
>     * archlinuxcn repo中收录的wine-wechat bug非常多

Bug 具体是指什么呢？我这里体验还算良好。

**Comment by ayalhw** [comment]
>       archlinuxcn repo中收录的wine-wechat bug非常多

请指出 bug 是什么，据我所知，Arch CN 中的 wine-wechat 的维护者 lilydjwg 并未收到任何 bug report.
