### ISSUE TITLE
qml-material-git-0.1.r57.g42da3ad-1-x86_64 打包问题

### ISSUE THREAD

**Issue by dongfengweixiao** [archlinuxcn/repo#182]
qml-material-git-0.1.r57.g42da3ad-1-x86_64的代码中跟随一个测试示例，作为库，不应该打包其产生的二进制文件：/usr/tests/....

**Comment by petronny** [comment]
唔。。到AUR去反应一下？
https://aur.archlinux.org/packages/qml-material-git/

**Comment by lilydjwg** [comment]
话说 Python 那边一堆测试用的东西的说，都被我 `NoExtract` 掉了。nodejs 那边有些库更甚，测试文件比真正给人用的代码还多出几倍来。

**Comment by farseerfc** [comment]
我等兩天上游，如果上游沒反映我就手動 hack PKGBUILD 吧
