### ISSUE TITLE
'dmenu-xft' should be removed from nvchecker.ini

### ISSUE THREAD

**Issue by zsrkmyn** [archlinuxcn/repo#183]
Although `nvchecker` is very smart, but since it seems this package has no long existed in AUR, `nvchecker` cannot find the version infomation and keeps contaminate our mailbox every day.

I think it should be repaired OuO

Since @inkn is not a member of this repo, removal of `dmenu-xft` from `nvchecker.ini` may result in lacking maintenance of the package. So what should we do? ╮(╯▽╰)╭

**Comment by zsrkmyn** [comment]
Why don't @inkn join the repo? Pushing directly will be much more convinient to maintain packages than sending PR, I think... OvO

(But I think I'd better ask @lilydjwg @felixonmars for advice...

**Comment by lilydjwg** [comment]
因为他没发邮件请求加入。他还没回应，所以我打算删掉这个包了，见 #184。
