### ISSUE TITLE
youtube-dl-git is outdated

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [archlinuxcn/repo#1870]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* youtube-dl-git
----

上游倉庫最近一次 commit 在五天前，hash 值爲 `f5863a3`，但 CN 源上 git 包的版本號似乎是 [兩個月前的 commit](https://github.com/ytdl-org/youtube-dl/commit/a115e0759)，並且大版本號甚至比官方源的更舊（2020.07.28）

**Comment by oldherl** [comment]
As the maintainer @colinkeenan doesn't speak Chinese, I'm using English here.

Translation of this issue: 
> Latest upstream commit happened 5 days ago, hash value f5863a3. But this `youtube-dl-git` package on ArchCN has a version of a commit 2 months ago, and even the version tag is older than `youtube-dl` (2020.07.28) in the official repo!

This package is maintained manually, so it would likely not be updated to the latest git commit. I advise you to not use this `-git` package unless some maintainer adopts this package and use lilac-automated packaging in the future.

**Comment by MarvelousBlack** [comment]
Hey bro, this package has been flagged out-of-date long time age.  So, if you no respond, I will adopt this package.

**Comment by yuyichao** [comment]
> Hey bro, this package has been flagged out-of-date long time age.

It has been out of date for a long time but it has not been flagged as such for very long at all. Please be slightly more patient.

**Comment by hubutui** [comment]
any one would like to review https://github.com/archlinuxcn/repo/pull/1871?
