### ISSUE TITLE
Package Request: Authy

### ISSUE THREAD

**Issue by CrankySupertoon** [archlinuxcn/repo#1879]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Two factor authentication desktop application
--

* 主要语言和工具链 / Main Languages and Toolchains

JavaScript, Electron

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/authy-snap/
Priopatory

* 为何需要这个软件包 / Why Need This Package

2FA Applications

**Comment by BruceZhang1993** [comment]
此包已被合并到 https://aur.archlinux.org/packages/authy
打包也将会用 authy 包名

**Comment by BruceZhang1993** [comment]
New package in commit 9a3e365a29ca61cc7241716b74301d6cf75c61dd
