### ISSUE TITLE
Package Request: zoom

### ISSUE THREAD

**Issue by CrankySupertoon** [archlinuxcn/repo#1882]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Video Conferencing and Web Conferencing Service
--

* 主要语言和工具链 / Main Languages and Toolchains

C++

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/zoom

* 为何需要这个软件包 / Why Need This Package

Because i dont want to use AUR to connect to my school

**Comment by yuyichao** [comment]
Dup of https://github.com/archlinuxcn/repo/issues/1775

It's unclear if it is legal to do so.

**Comment by SamLukeYes** [comment]
Zoom exists in this repo:

    [herecura]
    # packages built against stable
    Server = https://repo.herecura.be/herecura/x86_64
    
    [herecura-testing]
    # packages built against testing
    Server = https://repo.herecura.be/herecura-testing/x86_64

**Comment by lilydjwg** [comment]
It's available in [chaotic-aur] too.
