### ISSUE TITLE
gnome-breeze-git will be replaced by breeze-gtk

### ISSUE THREAD

**Issue by 0x01f7** [archlinuxcn/repo#189]
, use [extra/breeze-gtk](https://www.archlinux.org/packages/extra/x86_64/breeze-gtk/) instead. Just drop the package. :-)

**Comment by farseerfc** [comment]
Great! I will exam them tomorrow and decide whether to remove gnome-breeze-git from this repo.
Not a "out-of-date" issue tho.

**Comment by farseerfc** [comment]
Indeed breeze-gtk is more preferable than gnome-breeze-git. I will remove the latter from this repo in 1 week.
