### ISSUE TITLE
Orphaning mozjpeg

### ISSUE THREAD

**Issue by ykelvis** [archlinuxcn/repo#1899]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* mozjpeg

----

46c92bb122b610b8e9181d857a8fad8a4da49fa5

**Comment by lilydjwg** [comment]
咦，你这是要删还是要留它呀。
没有维护者的包，如果没有包依赖它会被自动删除的。

**Comment by ykelvis** [comment]
> 咦，你这是要删还是要留它呀。
> 没有维护者的包，如果没有包依赖它会被自动删除的。

原来有自动啊，我怕改了之后机器人不管所以（
