### ISSUE TITLE
PCSX2, update for x64 build, missing lib32-wxgtk2 in arch repos

### ISSUE THREAD

**Issue by aphirst** [archlinuxcn/repo#1910]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* pcsx2-avx2-git

----

I notice that due to recent upstream updates, PCSX2 can be built and run as x64, which promises minor but worthwhile performance benefits.

This is now being done in the main arch package `community/pcsx2`: https://github.com/archlinux/svntogit-community/commit/e62daa7d4e63de74e73ad37eda720f1659d3575f

Is this going to be considered for the archlinuxcn PCSX2 packages too?
EDIT: This may not yet be a great idea, as the community/pcsx2 build has (after some inspection) some surprising performance problems.

As an aside, when running the current archlinuxcn/pcsx2-* executables, the file selector windows (e.g. ISO, BIOS) don't follow my GTK/QT themes, whereas the arch community/pcsx2 packages do. I suspect this is related to the 32/64 bit difference, and I'm probably missing some important lib32 package or environment variable, but if this can be independently confirmed, perhaps I should open another ticket?

**Comment by aphirst** [comment]
It seems there is actually a more pressing issue.

lib32-wxgtk2 is currently a dependency of archlinuxcn/pcsx2-* just as it was in the arch repositories when it was still in multilib/pcsx2. As arch has shifted to the x64 build, they have removed the lib32-wxgtk2 package, which now makes it impossible to install pcsx2 from here. Unless upstream arch can be pursuaded to reverse their decision, I think this means that archlinuxcn will need to provide their own lib32-wxgtk2 build.

**Comment by heavysink** [comment]
I don't understand why main repo changed to 64 bit... The performance is bad under 64-bit build for both clang and gcc. I am gonna try lib32 build again with lib32-wxgtk3 into the repo. If the performance is better then I think I will keep 32bit build.

**Comment by aphirst** [comment]
In the long run (i.e. eventually) I think the 64-bit builds are supposed to become better, but at the moment there do seem to be problems yeah.

Great, I'll try it out once I see it in the repo!

**Comment by heavysink** [comment]
I think it is good now. Btw, now GSdx plugin can be selected to use SSE2/SSE4/AVX/AVX2 so separate build for avx-avx2 is no longer needed anymore.
