### ISSUE TITLE
i-nex-git need legacy dependency

### ISSUE THREAD

**Issue by 0kaguya** [archlinuxcn/repo#1913]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* i-nex-git

----
i-nex-git 依赖的 libcpuid-git 已经更新，i-nex-git 需要旧的版本。

`MLibcpuid14.Main.80: #60: Cannot find dynamic library 'libcpuid.so.14.0.1': libcpuid.so.14.0.1: 无法打开共享对象文件: 没有那个文件或目录`

**Comment by heavysink** [comment]
Done
