### ISSUE TITLE
为什么移除了部分常用的包

### ISSUE THREAD

**Issue by Brx86** [archlinuxcn/repo#1915]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* deepin.com.qq.im
* oh-my-zsh-git

----

部分常用的包近期在archlinuxcn源里被移除了，在一些方面带来了不便

**Comment by cuihaoleo** [comment]
就……没人维护了。欢迎加入成为 packager，维护这些包呀。

PS：这个问题类型是用来丢软件包的，不是咨询有关丢包的事情的。

**Comment by SamLukeYes** [comment]
`deepin.com.qq.im` 已经不再更新了，在上游已经被 `com.qq.im.deepin` 取代
不过移除了 `vivaldi` 确实有点糟心

**Comment by SilverRainZ** [comment]
oh-my-zsh-git 在 daafa87197 加回来了。
