### ISSUE TITLE
nvchecker can't import "six" anymore (maybe a python-setuptools pkg bug)

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#192]
After `pacman -Syu` updated `python-setuptools` and `python2-setuptools`, I ran `nvchecker my.ini` and got this error:

```
Traceback (most recent call last):
  File "/usr/bin/nvchecker", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 48, in <module>
    from pkg_resources.extern import six
  File "/usr/lib/python3.5/site-packages/pkg_resources/extern/__init__.py", line 60, in load_module
    "distribution.".format(**locals())
ImportError: The 'six' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

**Comment by colinkeenan** [comment]
I have opened a bug against `extra/python-setuptools`: https://bugs.archlinux.org/task/47776

**Comment by lilydjwg** [comment]
But why nvchecker needs six...

**Comment by colinkeenan** [comment]
It was python-setuptools that needed it and even before I filed the bug, a 2nd release had been done that included python-six as a dependency. I wasn't getting it because it's still not in the mirror I was using. Just edited /var/log/pacman.d/mirrorlist to uncomment the first U.S. mirror and then upgrading the system included python-six. Problem solved.
