### ISSUE TITLE
pkg request: surface-control

### ISSUE THREAD

**Issue by berberman** [archlinuxcn/repo#1921]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Control various aspects of Microsoft Surface devices from the Command-Line

* 主要语言和工具链 / Main Languages and Toolchains

Rust

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/surface-control/

* 为何需要这个软件包 / Why Need This Package

useful for surface book users

**Comment by SamLukeYes** [comment]
要不干脆把 `[linux-surface]` 仓库里的东西都搬过来吧，国内访问这个仓库太慢了

**Comment by berberman** [comment]
> 要不干脆把 `[linux-surface]` 仓库里的东西也都搬过来吧，国内访问这个仓库太慢了
> https://github.com/linux-surface/linux-surface/wiki/Package-Repositories#arch-linux-repository

感觉没必要把人家现成二进制源的包只为了加速下载重打一遍；而且我这边儿访问还挺快的，大概能到 10M/s。
