### ISSUE TITLE
bear contains /usr/libexec

### ISSUE THREAD

**Issue by hexchain** [archlinuxcn/repo#1925]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* bear

----

Package contains directory `/usr/libexec`, which is advised against in the [official guideline](https://wiki.archlinux.org/index.php/Arch_package_guidelines#Package_etiquette).

**Comment by SilverRainZ** [comment]
ref: https://github.com/rizsotto/Bear/issues/285#issuecomment-701567317

**Comment by xythrez** [comment]
Bear-3.0.0 AUR PKGBUILD原作者,感谢各位指出该问题。我已更新AUR中的PKGBUILD使用/usr/lib/bear，同步即可解决该issue了。

Bear-3.0.0 AUR PKGBUILD original maintainer here. Thanks for pointing out the issue. I've just updated the PKGBUILD in the AUR to use /usr/lib/bear. You should be able to resolve this issue by syncing against that. Let me know if there are other issues with the package.
