### ISSUE TITLE
godot

### ISSUE THREAD

**Issue by Modelmat** [archlinuxcn/repo#1926]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    An advanced, feature packed, multi-platform 2D and 3D game engine

* 主要语言和工具链 / Main Languages and Toolchains

    C++

* 上游链接 / Upstream Link

    http://www.godotengine.org/ / https://aur.archlinux.org/packages/godot

* 为何需要这个软件包 / Why Need This Package

    （Building this locally is a pain

**Comment by wfxr** [comment]
Added. Please wait for the package being built. Reopen it if you find any problem.
