### ISSUE TITLE
linux-zencjk: orphaning the package

### ISSUE THREAD

**Issue by OriginCode** [archlinuxcn/repo#1929]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* linux-zencjk
----
Upstream end the development. FTBFS

**Comment by lilydjwg** [comment]
linux-lily 可能也要被扔掉或者放弃 cjktty 补丁了……
