### ISSUE TITLE
添加一个lib32:lib32-orbit2

### ISSUE THREAD

**Issue by dongfengweixiao** [archlinuxcn/repo#193]
添加一个lib32:lib32-orbit2，谢谢

**Comment by petronny** [comment]
如果2016-12-01前这个request获得的![thumbup](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)比![thumbdown](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44e.png)多5个，我们就添加这个包，否则就不添加了。

**Comment by cuihaoleo** [comment]
简要介绍一下用途呗。为啥要加？

**Comment by dongfengweixiao** [comment]
一个叫Code Composer Studio 6.1.3的软件依赖这个东西。我打算给他打个包。
