### ISSUE TITLE
Package Request: Microsoft Edge (Dev)

### ISSUE THREAD

**Issue by intrnl** [archlinuxcn/repo#1949]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Microsoft Edge browser, dev channel

* 上游链接 / Upstream Link

https://www.microsoftedgeinsider.com/en-us/
https://aur.archlinux.org/packages/microsoft-edge-dev-bin/

* 为何需要这个软件包 / Why Need This Package

Development channel for previewing and testing latest features

**Comment by DDoSolitary** [comment]
Microsoft's license doesn't allow redistributing Edge.


> 2.8.        Scope of License. The Software is licensed, not sold. This agreement gives you only some rights to use the Software. Microsoft reserves all other rights. Unless applicable law gives you more rights despite this limitation, you will not (and have no right to):
> 
> (a)   work around any technical limitations in the Software that only allow you to use it in certain ways;
> 
> (b)   reverse engineer, decompile, disassemble, decrypt or otherwise attempt to derive the source code of the Software, except and only to the extent that the foregoing restriction is (i) permitted by applicable law; (ii) required by third party licensing terms governing the use of certain open-source components that may be included with the Software; or (iii) required to debug changes to any libraries licensed under the GNU Lesser General Public License which are included with and linked to by the Software.
> 
> (c)   remove, minimize, block, or modify any notices of Microsoft or its suppliers in the Software;
> 
> (d)   when using Internet-based features, you may not use those features in any way that could interfere with anyone else’s use of them or to try to gain access to or use any service, data, account, or network, in an unauthorized manner;
> 
> (e)   use the Software in any way that is against the law or to create or propagate malware; or
> 
> (f)    share, publish, distribute, or lend the Software, provide the Software as a stand-alone hosted solution for others to use, or transfer the Software or this agreement to any third party.
> 
> (g)    use tokens the Software uses to call into a Microsoft Azure service separate from the Software.

**Comment by intrnl** [comment]
that's pretty unfortunate, we'll have to see until later i suppose.

**Comment by c02y** [comment]
chaotic-aur里面有，不过chaotic-aur老是抽风而且速度慢，如果可以的话还是希望archlinuxcn能够上
```
chaotic-aur microsoft-edge-stable-bin 138.0.3351.95-1
```

**Comment by lilydjwg** [comment]
上不了，授权的问题。建议直接从 AUR 安装，反正是 -bin 包。

**Comment by c02y** [comment]
> 上不了，授权的问题。建议直接从 AUR 安装，反正是 -bin 包。

那行吧，刚简单试了下发现几个问题十分不爽，Wayland还得加启动参数否则scale很大(Chrome一样问题，但是Brave正常)，VSCode之类的环境变量就解决了但是对Edge无效，右键菜单也是很短显示不全每次得滑动，设置切换黑白主题每次都会恢复New Tab界面显示背景图片，卸载回到了Firefox
