### ISSUE TITLE
v2raya打包错误

### ISSUE THREAD

**Issue by mzz2017** [archlinuxcn/repo#1950]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* v2raya

----

根据日志 https://build.archlinuxcn.org/packages/#/v2raya/logs/1603571391 发现在执行yarn build时出现错误
```
ERROR  Error: Cannot find module 'node-libs-browser/mock/empty'
```
本地使用相同版本的nodejs(v14.14.0)未复现该错误。

根据 https://github.com/ant-design/ant-design-pro/issues/6920#issuecomment-662434671 ，执行yarn cache clean后重新打包或许能解决问题。

**Comment by lilydjwg** [comment]
头疼，又是 nodejs 的工具搞坏了缓存么？它的缓存文件在哪里呢？

`yarn cache clean` 这个得在打包环境里边执行。如果 yarn 没法保证缓存的完整性的话，我考虑想办法不让它缓存。

**Comment by mzz2017** [comment]
yarn可以增加参数--check-files来保证一致性

**Comment by mzz2017** [comment]
https://github.com/yarnpkg/yarn/issues/5299
可能可以解决新出现的打包问题
