### ISSUE TITLE
numix-circle-icon-theme-git's dependency is broken

### ISSUE THREAD

**Issue by crab2313** [archlinuxcn/repo#1952]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  numix-circle-icon-theme-git

----

numix-icon-theme-git is missing in [archlinuxcn] as a dependency of numix-circle-icon-theme-git.

**Comment by colinkeenan** [comment]
Added numix-icon-theme-git and updated numix-circle-icon-theme-git
