### ISSUE TITLE
microsoft-edge-dev-bin

### ISSUE THREAD

**Issue by Galaxy0419** [archlinuxcn/repo#1960]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description
微软新版Edge开发版

* 主要语言和工具链 / Main Languages and Toolchains
无, 二进制文件包

* 上游链接 / Upstream Link
AUR: https://aur.archlinux.org/packages/microsoft-edge-dev-bin
Microsoft Edge Dev: https://www.microsoftedgeinsider.com/en-us/download

* 为何需要这个软件包 / Why Need This Package
Edge现在成为windows默认浏览器且几乎支持所有平台，可以为浏览器生态提供更多选择

**Comment by edward-p** [comment]
根据微软的许可条例，该软件不允许分发：
>Scope of License. The Software is licensed, not sold. This agreement gives you
only some rights to use the Software. Microsoft reserves all other rights. Unless
applicable law gives you more rights despite this limitation, you will not (and have
no right to):
>...
>(f) share, publish, distribute, or lend the Software, provide the Software as a
stand-alone hosted solutxuon for others to use, or transfer the Software or this
agreement to any third party.

**Comment by lilydjwg** [comment]
dup of #1949.
