### ISSUE TITLE
mpdscribble packaging error

### ISSUE THREAD

**Issue by hexchain** [archlinuxcn/repo#1971]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

* mpdscribble

----

请在此补充说明。
Please describe in detail here.

There are several problems with this package.

- The systemd service files should not be installed from the source directory as they still contain `@prefix@`.
- `systemd` needs to be in `makedepends`. The meson build script detects systemd and enables `sd_notify` support and processes .service files accordingly. The AUR package has `libsystemd`, which is also wrong.

**Comment by ykelvis** [comment]
1c9eff5690d9962ea4a8016c8786490dc8ae2348
