### ISSUE TITLE
[打包请求] Transmission-web-control （附可用的PKGBUILD）

### ISSUE THREAD

**Issue by OliverLew** [archlinuxcn/repo#1979]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    第三方transmission web-ui

* 主要语言和工具链 / Main Languages and Toolchains

    html/css/js

* 上游链接 / Upstream Link

    https://github.com/ronggang/transmission-web-control

* 为何需要这个软件包 / Why Need This Package

    挺好用的，不知道为什么这么久没人制作AUR/archlinuxcn包，现在请求一下，下面gist是我自己写的可以用的PKGBUILD，供参考。

    https://gist.github.com/OliverLew/15dcf3f7861877e65a97e235062a6369

**Comment by hubutui** [comment]
可以直接发起 PR，让其他人来审核．
