### ISSUE TITLE
dropping vita3k-git

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#1986]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

*  vita3k-git

----

It depends on gcc8 to build, which is now in AUR. I don't want to bring in another gcc just for a -git package, thus dropping it.

**Comment by DDoSolitary** [comment]
It seems that there's no need to use gcc8. I just tried to build it locally with latest gcc only the errors are from discord_game_sdk, which uses the std namespace but only includes C headers. I guess it's pretty easy to patch it.

**Comment by farseerfc** [comment]
Any patch is welcomed to keep it

**Comment by DDoSolitary** [comment]
I just posted the patch to AUR: https://aur.archlinux.org/packages/vita3k-git/#comment-777358

**Comment by farseerfc** [comment]
Thanks for the patch! Actually it can build without clang as well, updated in this repo, thus closing this orphaning issue.

**Comment by DDoSolitary** [comment]
When building locally with gcc it got stuck at about 60% but clang doesn't have this issue. This is why I used clang, though I don't know what actually went wrong with gcc.

**Comment by farseerfc** [comment]
I tested a local build with gcc, it took dozens of minutes at 
`[ 61%] Linking CXX static library librenderer.a`
and later
`[ 99%] Linking CXX static library libmodules.a`
nevertheless it finished packaging at last
`==> Finished making: vita3k-git r1776.146fd1c2-1 (Thu 26 Nov 2020 11:38:59 AM JST)`
