### ISSUE TITLE
[Package Request] gcc9

### ISSUE THREAD

**Issue by dianlujitao** [archlinuxcn/repo#1989]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    gcc9

* 主要语言和工具链 / Main Languages and Toolchains

    C/C++

* 上游链接 / Upstream Link

    https://aur.archlinux.org/packages/gcc9/
    https://aur.archlinux.org/packages/gcc9-libs/
    https://aur.archlinux.org/packages/gcc9-fortran/

* 为何需要这个软件包 / Why Need This Package

    是matlab的依赖项，最近从官方源移到aur了，编译很慢

**Comment by edward-p** [comment]
诶？arch4edu 没有这个包么？

**Comment by dianlujitao** [comment]
> ~诶？arch4edu 没有这个包么？~ 康了一下， 5, 6, 7 都有，没有9

因为之前一直在 core 里，这周才移到 aur 的

**Comment by petronny** [comment]
AUR 上最早第一版 gcc8 还是我交的。。。后来被斯温君挪进官方源了。。。

**Comment by edward-p** [comment]
看来 arch4edu 那边已经有了，这边就先关了？

**Comment by dianlujitao** [comment]
https://github.com/arch4edu/arch4edu/commit/33db7d8f88f7fd34531ad499eee8db1409a9d849
