### ISSUE TITLE
Introducing CDN domain for our repos

### ISSUE THREAD

**Issue by felixonmars** [archlinuxcn/repo#199]
We have now enabled KeyCDN on a new domain, please give it a try and let me know if it's faster for you:

```
Server = https://cdn.repo.archlinuxcn.org/$arch
```

**Comment by colinkeenan** [comment]
`sudo pacman -Syy` was definitely faster. Haven't needed to install/update anything from archlinuxcn after this change yet.

**Comment by zsrkmyn** [comment]
It‘s much slower than 163 mirror here, approximately 10~100K/s, and not stable.

I am in Kunming, using 铁通, not using any multi-thread download tool.

**Comment by farseerfc** [comment]
It's pretty faster here. 3MB/s now vs 500KB/s before.
I am in Japan, tested with NTT Hikari West Japan and Osaka University
Network.

On Mon, Feb 15, 2016 at 3:57 AM, Stephen <notifications@github.com> wrote:

> It‘s much slower than 163 mirror here, approximately 10~100K/s, and not
> stable.
>
> I am in Kunming, using 铁通, not using any multi-thread download tool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archlinuxcn/repo/issues/199#issuecomment-183949743>.
>



-- 
--------------------------------------------------------------------------------
Jiachen Yang 楊嘉晨
Graduate School of Information Science and Technology, Osaka University
Tel:   080-3853-2770
MSN:   firechildren@hotmail.com
GMail: farseerfc@gmail.com

**Comment by colinkeenan** [comment]
It's way faster in Kansas City, Missouri, USA. Everything is faster by far. It was painfully slow on the 163 mirror. Now, it's just as fast as, or faster than, the archlinux repo mirrors.

**Comment by cuihaoleo** [comment]
Already documented in https://github.com/archlinuxcn/mirrorlist-repo
