### ISSUE TITLE
搜狗输入法过期

### ISSUE THREAD

**Issue by maoxuner** [archlinuxcn/repo#1993]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* fcitx-sogoupinyin
----
aur当前是`2.4.0.2732-1`

**Comment by DDoSolitary** [comment]
这包早就被删了 #1000

**Comment by maoxuner** [comment]
> 这包早就被删了 #1000

啊，是的。抱歉，我看错了，我是从本地源安装的。
