### ISSUE TITLE
netease-musicbox, netease-musicbox-git didn't auto update to python3.9

### ISSUE THREAD

**Issue by oldherl** [archlinuxcn/repo#1999]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* netease-musicbox
* netease-musicbox-git
----
netease-musicbox, netease-musicbox-git didn't auto update to python3.9

They failed to build due to unknown reasons.

**Comment by axionl** [comment]
https://github.com/archlinuxcn/repo/commit/88f90df577c2d0da47ec9e544a36bc3bf19f96ff

**Comment by axionl** [comment]
https://github.com/archlinuxcn/repo/commit/88f90df577c2d0da47ec9e544a36bc3bf19f96ff
