### ISSUE TITLE
请求加入vokoscreen 录屏软件

### ISSUE THREAD

**Issue by Arondight** [archlinuxcn/repo#201]
[vokoscreen](http://www.kohaupt-online.de/hp) 是一个优秀的屏幕录制软件，基于Qt5。

AUR 上有两个项目：

1. [vokoscreen](https://aur.archlinux.org/packages/vokoscreen)
+ [vokoscreen-git](https://aur.archlinux.org/packages/vokoscreen-git)

两者源文件获取方式稍有区别。

**Comment by farkasity** [comment]
这个 AUR 上有，而且目前还在维护，所以我也不清楚要不要加入，怎么加入。还是等 @lilydjwg @felixonmars @phoenixlzx 来说说。

**Comment by lilydjwg** [comment]
我觉得 [simplescreenrecorder](http://www.maartenbaert.be/simplescreenrecorder/) 也挺好的说。

**Comment by farkasity** [comment]
包我打好了，但是我的公钥还没有加入 keyring，所以也没法装。

**Comment by Arondight** [comment]
阿狸么么哒
