### ISSUE TITLE
Prepare for upcoming boost rebuild

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#2012]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* [x] emulationstation-git @heavysink
* [x] kicad-git @edward-p
* [x] process-cpp @heavysink
* [x] qv2ray-plugin-trojan-dev-git @DuckSoft
* [x] rstudio-desktop-git @heavysink
* [x] vim-youcompleteme-git @dctxmei
* [x] yuzu-early-access-kiku233-git @heavysink
* [x] yuzu-mainline-git @heavysink

----

The above packages have `depends=(boost-libs)` in their `PKGBUILD` but do not have `update_on: - alias: boost` in their `lilac.yaml` . During boost-libs soname rebuild, these packages will not be automatically rebuild by lilac.

以上包的 PKGBUILD 文件中写有 `depends=(boost-libs)` ，但 `lilac.yaml` 中没有写 `update_on: - alias: boost` 。在 boost-libs 更新 soname 需要重新打包时，这些包不会被 lilac 自动重新打包。

Please check whether it is needed and add
请手动检查确认并添加
```
update_on:
    - alias: boost
```
to their `lilac.yaml` file.
到对应的 `lilac.yaml` 文件中。

The package list is generated by:
以上包列表是通过命令
```
comm -23 =(rg "depends=.*boost-libs" -c | cut -d"/" -f1 | sort) =(rg "alias.*boost" -c | cut -d"/" -f1 | sort)
```
and then manually filter out false positives.
生成后再手动筛选掉错误的结果产生的。

如果您确认无需添加，可以直接在这个 issue 的包名上打勾。

**Comment by lilydjwg** [comment]
以后这种待勾选的列表都要等 lilac assign 之后打加 no-lilac 标记。
