### ISSUE TITLE
yay-git 能改用 pacman-git 编译么

### ISSUE THREAD

**Issue by huyz-git** [archlinuxcn/repo#2019]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* yay-git

----

请在此补充说明。
Please describe in detail here.

目前 aur 上的 yay-git 是依赖于 `pacman>5` 的（即依赖于 `pacman-git`），而 cn 源里的 yay-git 则还是依赖于 `pacman`。

**Comment by axionl** [comment]
https://github.com/archlinuxcn/repo/commit/6f9e9da9273653408fbd9c599f85be547d5721a8
