### ISSUE TITLE
Gtk 4 缺少更新模块 cache 的对应 hook

### ISSUE THREAD

**Issue by wengxt** [archlinuxcn/repo#2024]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* gtk4

----

gtk4 虽然没有 gtk-query-immodules 但是需要使用另一个 glib 提供的统一插件架构来更新 
例如 gio-querymodules /usr/lib/gtk-4.0/4.0.0/immodules
推测同目录下的   /usr/lib/gtk-4.0/4.0.0/media 和  /usr/lib/gtk-4.0/4.0.0/printbackends 也需要

**Comment by AlynxZhou** [comment]
```

**Comment by AlynxZhou** [comment]
diff --git a/archlinuxcn/gtk4/gtk4-query-immodules.hook b/archlinuxcn/gtk4/gtk4-query-immodules.hook
index c81e3f9a86..c5c88e2f6a 100644
--- a/archlinuxcn/gtk4/gtk4-query-immodules.hook
+++ b/archlinuxcn/gtk4/gtk4-query-immodules.hook
@@ -8,4 +8,4 @@ Target = usr/lib/gtk-4.0/4.0.0/immodules/*.so
 [Action]
 Description = Probing GTK4 input method modules...
 When = PostTransaction
-Exec = /usr/bin/gtk4-query-immodules --update-cache
+Exec = /usr/bin/gio-querymodules /usr/lib/gtk-4.0/4.0.0/immodules
```
是这个意思吗？不过我看现在的 `PKGBUILD` 并没有打包这个文件耶

**Comment by SilverRainZ** [comment]
See #2051.
