### ISSUE TITLE
add arkane-systems/genie(already have PKGBUILD)

### ISSUE THREAD

**Issue by rayfalling** [archlinuxcn/repo#2025]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    用于在Windows subsystem for Linux 下启动systemd相关工具链

* 主要语言和工具链 / Main Languages and Toolchains

    C# .NetCore/.Net5.0

* 上游链接 / Upstream Link

    https://github.com/arkane-systems/genie

* 为何需要这个软件包 / Why Need This Package

    AUR删除了WSL相关的所有包，没有更新源了

**Comment by DuckSoft** [comment]
Packaging dependency package `daemonize`...

**Comment by DuckSoft** [comment]
Done.
