### ISSUE TITLE
genie-systemd 坏包

### ISSUE THREAD

**Issue by rayfalling** [archlinuxcn/repo#2032]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  genie-systemd

----

请在此补充说明。
Please describe in detail here.

dotnet single file打包模式strip会导致文件无法执行

**Comment by DuckSoft** [comment]
大意了，上个版本还没这样，立刻改～

**Comment by DuckSoft** [comment]
整好了，等下次打包吧！
