### ISSUE TITLE
megasync requires icu67

### ISSUE THREAD

**Issue by SamLukeYes** [archlinuxcn/repo#2038]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* megasync

----

`megasync` refuses to start and says it lacks libicuuc.so.67. Installing `icu67` from AUR solves this problem. Maybe it needs to be rebuilt against icu 68.

**Comment by DDoSolitary** [comment]
What acutally depends on icu is libpdfium.so, which is provided by libpdfium-nojs
