### ISSUE TITLE
[Build Fail] kicad-git build 失败

### ISSUE THREAD

**Issue by RigoLigoRLC** [archlinuxcn/repo#2067]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* kicad-git

----

KiCad 近日对翻译文件(i18n)的编译方式做了更改，导致ArchLinuxCN上的kicad-git近日无法正常编译。

[上游更改](https://gitlab.com/kicad/code/kicad/-/commit/e9fa9f68b293225f63bdb3aa495bb471c85aaac1)

**Comment by edward-p** [comment]
close via https://github.com/archlinuxcn/repo/commit/d53b152a625661ef3aa3f3bdf8b7f3510853da62
