### ISSUE TITLE
[package request] microsoft-edge

### ISSUE THREAD

**Issue by amitbha** [archlinuxcn/repo#2085]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

  microsoft-edge 浏览器

* 主要语言和工具链 / Main Languages and Toolchains

    C++

* 上游链接 / Upstream Link

   https://aur.archlinux.org/packages/microsoft-edge-dev-bin/

* 为何需要这个软件包 / Why Need This Package

   微软在chromium的基础上出的改进版，希望能与google-chrome势均力敌

**Comment by imlonghao** [comment]
dup of #1949.

**Comment by DDoSolitary** [comment]
Duplicate of #1949
