### ISSUE TITLE
clang40 needs rebuild

### ISSUE THREAD

**Issue by SamLukeYes** [archlinuxcn/repo#2095]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* llvm40 (clang40)

----

> clang-4.0: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory

**Comment by SilverRainZ** [comment]
@hea

**Comment by SilverRainZ** [comment]
@heavysink

**Comment by SilverRainZ** [comment]
@heavysink

**Comment by heavysink** [comment]
#2527
