### ISSUE TITLE
netease-cloud-music imfix

### ISSUE THREAD

**Issue by sihuan** [archlinuxcn/repo#2096]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* netease-cloud-music

----

请在此补充说明。
Please describe in detail here.
可能提打包错误不太合适，（但是也想不到更合适的了
AUR 里 [netease-cloud-music-imfix](https://aur.archlinux.org/packages/netease-cloud-music-imfix/) 以很简单的方式修复了网易云音乐不能使用输入法的问题，希望可以跟进一下。

**Comment by ykelvis** [comment]
去aur上报给netease-cloud-music吧 不想为小fix单独打包
