### ISSUE TITLE
[打包请求] LXGW New Clear Gothic

### ISSUE THREAD

**Issue by tomyangsh** [archlinuxcn/repo#2097]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    A Simplified Chinese sans-serif font derived from IPAex Gothic. 一款衍生于「IPAexゴシック」的简体中文黑体字型。

* 主要语言和工具链 / Main Languages and Toolchains

    N/A

* 上游链接 / Upstream Link

    https://github.com/lxgw/LxgwNewClearGothic

* 为何需要这个软件包 / Why Need This Package

    补全霞鹜系列字体

**Comment by oldherl** [comment]
此字体和 Noto Sans CJK SC 相比，有什么明显的特点/优势吗？

**Comment by tomyangsh** [comment]
细看好像区别不大。。
