### ISSUE TITLE
nvchecker can't find AUR upstream for any packages

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#210]
Something's gone completely wrong with nvchecker on my machine. After updating icecat, adopting that package, and installing it on my machine, nvchecker stopped finding AUR upstream. I tried both my.ini that I maintain for myself, and nvchecker.ini. Just got tons of error messages saying "AUR upstream not found for..."

nvchecker --version
nvchecker v0.4.1

pacman -Qi nvchecker-git | grep Version
Version         : v0.4.r18.g7209189-1

grep nvchecker /var/log/pacman.log
.
.
.
[2016-01-01 21:31] [ALPM] upgraded nvchecker-git (v0.4.r16.gf7e8f3b-1 -> v0.4.r18.g7209189-1)

So, I have the most recent version of nvchecker, and it has not been updated for a couple of months.

If this is only happening to me, how can I track down what's gone wrong? If this is happening to everyone, there must have been a change with the AUR and nvchecker needs to be updated.

I have double checked that the AUR is still accessible by other command line tools, namely cower.

**Comment by petronny** [comment]
I can't find any package in AUR using yaourt either.
On 周一, 2月 29, 2016 at 16:32, Colin Keenan <notifications@github.com> wrote:
Something's gone completely wrong with nvchecker on my machine. After updating
icecat, adopting that package, and installing it on my machine, nvchecker
stopped finding AUR upstream. I tried both my.ini that I maintain for myself,
and nvchecker.ini. Just got tons of error messages saying "AUR upstream not
found for..."

nvchecker --version
nvchecker v0.4.1

pacman -Qi nvchecker-git | grep Version
Version : v0.4.r18.g7209189-1

grep nvchecker /var/log/pacman.log
.
.
.
[2016-01-01 21:31] [ALPM] upgraded nvchecker-git (v0.4.r16.gf7e8f3b-1 ->
v0.4.r18.g7209189-1)

So, I have the most recent version of nvchecker, and it has not been updated for
a couple of months.

If this is only happening to me, how can I track down what's gone wrong? If this
is happening to everyone, there must have been a change with the AUR and
nvchecker needs to be updated.

**Comment by lilydjwg** [comment]
AUR's API has gone wrong.

**Comment by colinkeenan** [comment]
`cower` works though. Maybe just use `curl` in `nvchecker`?

**Comment by lilydjwg** [comment]
It seems that AUR has removed support for API version 1 today. I'll update nvchecker soon.

**Comment by lilydjwg** [comment]
I've updated nvchecker on GitHub. It should have been fixed.

PS: PyPI is down, oh....

**Comment by petronny** [comment]
yaourt is fine now, since package-query has been updated to 1.8.
