### ISSUE TITLE
fiji-bin version no longer exists

### ISSUE THREAD

**Issue by JOT85** [archlinuxcn/repo#2100]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  fiji-bin

----

It appears that the 20201104-2027 directory has disappeared and the latest version is instead 20201104-1356.

See https://downloads.imagej.net/fiji/archive/

The current source responds with a 404.

Is it possible to manually intervene and correct this? I think the version needs to be switched from 20201104.2027 to 20201104.1356.

Thanks

**Comment by hubutui** [comment]
If you install `fiji-bin` from ArchLinux CN repo, it doesn't affect you. Is there any differences between these two version number? You could use the [PKGBUILD](https://aur.archlinux.org/packages/fiji-bin/) from AUR if you'd like to create this pkg.
I don't wanna set `epoch=3`.
