### ISSUE TITLE
besttrace no longer works

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#2110]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* besttrace

----

It shows `http: json  http: json` in place of geo infomation. The API seems to be taken down. I've checked the latest version on their website doesn't work either.

**Comment by attenuation** [comment]
this tool seem depressed by ipip.net,  btapi is not stable in recent days

**Comment by lilydjwg** [comment]
It's been updated.
