### ISSUE TITLE
ccls: error while loading shared libraries: libclang-cpp.so.11

### ISSUE THREAD

**Issue by yssource** [archlinuxcn/repo#2112]
### 问题类型 / Type of issues
ccls: error while loading shared libraries: libclang-cpp.so.11: cannot open shared object file: No such file or directory

没有链接到 libclang-cpp.so.11.1

```
ls /usr/lib/libclang-cpp*
/usr/lib/libclang-cpp.so  /usr/lib/libclang-cpp.so.11.1
```

```
clang++ --version

clang version 11.1.0
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```

* 过期软件包 / out-of-date packages
ccls-git
### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----

**Comment by SilverRainZ** [comment]
奇怪，为什么没有出发 clang 的 alias，我来手动 rebuild 一下。

**Comment by DDoSolitary** [comment]
之前版本 clang 的库的 soname version 都是和 major version 同步的（clang 11 的是 `libclang-cpp.so.11`）， lilac 的 alias 也是取了 major version ，但是 clang 11.1 不知道为什么 soname version 改成了用 minor version （`libclang-cpp.so.11.1`）

**Comment by SilverRainZ** [comment]
> 之前版本 clang 的库的 soname version 都是和 major version 同步的（clang 11 的是 `libclang-cpp.so.11`）， lilac 的 alias 也是取了 major version ，但是 clang 11.1 不知道为什么 soname version 改成了用 minor version （`libclang-cpp.so.11.1`）

原来如此……学习了。

**Comment by yssource** [comment]
Thanks, It works now.
