### ISSUE TITLE
linux-lily启动后出现initramfs的unpacking error

### ISSUE THREAD

**Issue by Superkeyv** [archlinuxcn/repo#2113]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* linux-lily

----

请在此补充说明。

通过Arch的Pacman=5.2.2-2安装archlinuxcn/linux-lily和linux-lily-headers，安装过程正常，dkms执行正常，使用zstd-compress生成initramfs，启动后出现initramfs的解包错误。

初步判断是linux-lily不支持zstd的压缩方式，修改/etc/mkinitcpio.conf，修改设置COMPRESSION="lzop"，最后Pacman重新安装linux-lily后成功启动。

建议通知linux-lily的维护者处理该问题

**Comment by zhullyb** [comment]
https://www.archlinuxcn.org/moving-to-zstandard-images-by-default-on-mkinitcpio/

**Comment by lilydjwg** [comment]
linux-liily 5.10.19 is available.
