### ISSUE TITLE
.DS_Store files found in packages

### ISSUE THREAD

**Issue by oldherl** [archlinuxcn/repo#2143]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* [x] ekho
* [x] motrix-git
* [x] parsoid-git
* [x] poi
* [x] vue-cli
* [x] thelounge-git
----

Those packages contain one or more `.DS_Store` files.

**Comment by hubutui** [comment]
motrix-git 修了，see https://github.com/archlinuxcn/repo/commit/75a38db79a3e81ee510431da4c8c89f8c7233cc4

**Comment by swordfeng** [comment]
Any guideline for this?

**Comment by KenOokamiHoro** [comment]
Applied fixes like https://github.com/archlinuxcn/repo/commit/75a38db79a3e81ee510431da4c8c89f8c7233cc4  in https://github.com/archlinuxcn/repo/commit/7f7c0ee73c39d07dfc6334996a0d0dbb253e77c4 .

**Comment by swordfeng** [comment]
Applied fix to poi: 7f7d82c5126346590cf0bcc3004cc73e0cf38c0d

**Comment by Xuanwo** [comment]
Dropped in #2145

**Comment by ykelvis** [comment]
71b8cac8e68c9d2e1ed2bf2baa9be82f6b86b44d 更新了，新包装完已经没有.DS_Store了

**Comment by SilverRainZ** [comment]
Since all task have done, closed.
