### ISSUE TITLE
libtinfo: signature from "lilac (build machine) <lilac@build.archlinuxcn.org>" is invalid

### ISSUE THREAD

**Issue by bigeagle** [archlinuxcn/repo#215]
lilac 的签名坏掉了？

**Comment by bigeagle** [comment]
seems to be my ISP's fault.

**Comment by Toocc** [comment]
How did you fix it ? I encounter a similar problem that I can't install ncurses5-compat-libs with "pacman -Syu"

**Comment by bigeagle** [comment]
直接从 http://repo.archlinuxcn.org/ 安装 ncurses5-compat-libs 失败，`rm -rf /etc/pacman.d/gnupg` `pacman-key --init` 重新初始化keyring，照样不行。

**Comment by Toocc** [comment]
嗯，我之前也是： 直接从 https://mirrors.tuna.tsinghua.edu.cn/ 或 http://repo.archlinuxcn.org/ 或 https://cdn.repo.archlinuxcn.org/ 安装ncurses5-compat-libs都不行。然后我换到163（http://mirrors.163.com/archlinux-cn）的后，就可以了。

现在我改回到Tuna，把ncurses5-compat-libs卸掉重装，不用改到163也可以装，不知道为什么。

**Comment by bigeagle** [comment]
那是因为你从163下的包没被删掉，还在缓存里。163有问题啊，上游都错了，它怎么能对……

**Comment by Toocc** [comment]
![ncurses5](https://cloud.githubusercontent.com/assets/11392909/15069457/46f14c16-13b0-11e6-8853-5e7c48f7478d.png)

这是安装的截图。我觉得可能是163还没有和上游更新，保持了原来的状态，所以没有出现这个问题

**Comment by Toocc** [comment]
![tunancurses5](https://cloud.githubusercontent.com/assets/11392909/15069637/a5520f42-13b1-11e6-8ea0-f15fb2510281.png)

这是我把ncurses5 163缓存删掉后重新安装的图，用的是tuna的源

**Comment by lilydjwg** [comment]
PIA @felixonmars

**Comment by petronny** [comment]
@Toocc ncurses5的那个重新安装一下archlinuxcn-keyring就好了
至少我这里是的

**Comment by bigeagle** [comment]
并不行，整个 keyring reset 重建都不行
 
--
Justin Wong
 
 
On Fri, May 13, 2016, at 20:19, Petron wrote:
> @Toocc[1] ncurses5的那个重新安装一下archlinuxcn-keyring就好了
>  至少我这里是的
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub[2]
>
 

Links:

  1. https://github.com/Toocc
  2. https://github.com/archlinuxcn/repo/issues/215#issuecomment-219027657

**Comment by petronny** [comment]
@Toocc 是我昨天撤回这句了。。
所以我rebuild了一下这个包，现在签名应该没问题了

**Comment by petronny** [comment]
这个issue应该解决了吧？

**Comment by lilydjwg** [comment]
关了先。有问题再开。
