### ISSUE TITLE
font-symbola license issue

### ISSUE THREAD

**Issue by SamLukeYes** [archlinuxcn/repo#2152]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* ttf-symbola
* otf-symbola

----

According to its [license](https://dn-works.com/wp-content/uploads/2020/UFAS-Docs/License.pdf), this font does not allow redistribution. There's an older but redistributable version [here](https://aur.archlinux.org/packages/ttf-symbola-free/).

**Comment by oldherl** [comment]
Removed the package in 581936e0a6. Free old version not added.
