### ISSUE TITLE
some signature of packages from Colin Keenan is invalid or corrupted.

### ISSUE THREAD

**Issue by fqj1994** [archlinuxcn/repo#216]
error: acroread: signature from "Colin Keenan <colinnkeenan@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/acroread-9.5.5-6-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: lib32-pangox-compat: signature from "Colin Keenan <colinnkeenan@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/lib32-pangox-compat-0.0.2-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).

**Comment by colinkeenan** [comment]
Try updating/re-installing the `archlinuxcn-keyring` first. It was recently updated to include my key that was updated last November. So, I've been busy updating all my packages to have the same updated key.

If after updating `archlinuxcn-keyring`, you are still having the same problem
You can get my key that was updated last November by running this command:

`sudo pacman-key --refresh-keys`

Please report back here whether or not you had to refresh-keys. I want to know if the new keyring fixed this problem or not.

**Comment by farseerfc** [comment]
This should be fixed now.
