### ISSUE TITLE
timeshift should depend on which

### ISSUE THREAD

**Issue by SamLukeYes** [archlinuxcn/repo#2167]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* timeshift

----

I'm making an archiso with `timeshift` from this repo. When testing my iso, `timeshift` failed to start, complaining `which` is missing in stderr.

**Comment by DuckSoft** [comment]
```
core/which 2.21-5 (base-devel)
```

**Comment by SamLukeYes** [comment]
> ```
> core/which 2.21-5 (base-devel)
> ```

Thanks for the information. So, this is not an issue for the AUR package. Does [archlinuxcn] also require users to have all the packages in `base-devel` installed?

**Comment by lilydjwg** [comment]
On Mon, Mar 29, 2021 at 09:04:21AM -0700, SamLukeYes wrote:
> > ```
> > core/which 2.21-5 (base-devel)
> > ```
> 
> Thanks for the information. So, this is not an issue for the AUR package. Does [archlinuxcn] also require users to have all the packages in `base-devel` installed?

No. It's a missing dependency that should be added.

-- 
Best regards,
lilydjwg

**Comment by DuckSoft** [comment]
Update: I've filed a pull request to the upstream fixing that issue.
But, this package is following AUR updates, which means that this is an AUR package.
By convention, when the package is contained in `base-devel` (`which` is), the dependency gets automatically ignored.

So I think that we should make some black magic to our packaging process. Let's say, to add `which` as a dependency after pulling from AUR?

**Comment by lilydjwg** [comment]
> Let's say, to add which as a dependency after pulling from AUR?

Yes, there is a [`add_depends`](https://github.com/archlinuxcn/lilac/blob/81c1896bd7b0a315944e9e07d4f4a762611e35ae/lilac2/api.py#L87) function to use.

**Comment by SamLukeYes** [comment]
Wait, is this really fixed?

```
$ yay -Qi timeshift
名字           : timeshift
版本           : 20.11.1+3+g08d0e59-4
描述           : A system restore utility for Linux
架构           : x86_64
URL            : https://github.com/teejee2008/timeshift
软件许可       : GPL
组             : 无
提供           : 无
依赖于         : gtk3  libsoup  cronie  rsync  libgee  vte3  xapp
                 xorg-xhost
可选依赖       : btrfs-progs: BTRFS support [已安装]
依赖它         : 无
被可选依赖     : 无
与它冲突       : 无
取代           : 无
安装后大小     : 3.82 MiB
打包者         : lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>
编译日期       : 2021年03月31日 星期三 04时30分05秒
安装日期       : 2021年03月31日 星期三 12时30分28秒
安装原因       : 单独指定安装
安装脚本       : 是
验证者         : 数字签名
```
