### ISSUE TITLE
(aarch64) qv2ray-dev-git outdated

### ISSUE THREAD

**Issue by yujantime** [archlinuxcn/repo#2176]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

*aarch64/qv2ray-dev-git-2.7.0.6051.r2757.2e44f185-1

----
由于protobuf更新到 3.15.6,运行aarch64/qv2ray报错:error while loading shared libraries: libprotobuf.so.23: cannot open shared object file: No such file or directory.

**Comment by DuckSoft** [comment]
aarch64 包是手打的，暂时没办法自动化。我空了搞一下，你若等不及也可以自己构建，并不难（跑）。

**Comment by DuckSoft** [comment]
done（树莓派上打了40分钟）
https://repo.archlinuxcn.org/aarch64/qv2ray-dev-git-2.7.0.6179.r2949.5238c214-1-aarch64.pkg.tar.zst
