### ISSUE TITLE
desktop-naotu-3.2.3-5 failed to launch due to libicui18n soversion bump

### ISSUE THREAD

**Issue by DuckSoft** [archlinuxcn/repo#2181]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* desktop-naotu

----
```console
$ desktop-naotu 
electron4: error while loading shared libraries: libicui18n.so.67: cannot open shared object file: No such file or directory
```

```
core/icu 68.2-1 [已安装]
    usr/lib/libicui18n.so.68
```

**Comment by BruceZhang1993** [comment]
Not a packaging error. Please update electron4-bin to 4.2.12-6.

**Comment by DuckSoft** [comment]
```
软件包 (2)              旧版本  新版本  净变化    下载大小

electron4                  4.2.12-6            -134.07 MiB           
archlinuxcn/electron4-bin            4.2.12-6   156.12 MiB  46.98 MiB

下载大小：   46.98 MiB
全部安装大小：  156.12 MiB
净更新大小：   22.05 MiB
```

strange... seemed that the pkgrel is same and pacman didn't realized that there was an upgrade.

**Comment by BruceZhang1993** [comment]
> ```
> 软件包 (2)              旧版本  新版本  净变化    下载大小
> 
> electron4                  4.2.12-6            -134.07 MiB           
> archlinuxcn/electron4-bin            4.2.12-6   156.12 MiB  46.98 MiB
> 
> 下载大小：   46.98 MiB
> 全部安装大小：  156.12 MiB
> 净更新大小：   22.05 MiB
> ```
> 
> strange... seemed that the pkgrel is same and pacman didn't realized that there was an upgrade.

will bump pkgrel for electron4-bin (
