### ISSUE TITLE
"bsnes" is built with non-portable flag

### ISSUE THREAD

**Issue by ktamp** [archlinuxcn/repo#2190]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* bsnes

----

Running "bsnes" executable on an older processor (Intel Core 2 Duo) results in a "Illegal instruction (core dumped)" error.

Installing "bsnes" from AUR fixes this issue.

This error is caused by the "flags += -march=native" instruction in "GNUmakefile" file.
Please consider removing it.

**Comment by lilydjwg** [comment]
That should be removed. `-march=native` should not be used for our distributed packages.

**Comment by DuckSoft** [comment]
bf725c1136f3a03f04d3df2a82ee9eb342f6234f
