### ISSUE TITLE
some PKGBUILDs are not compiled & packaged

### ISSUE THREAD

**Issue by cuihaoleo** [archlinuxcn/repo#220]
There are 15 PKGBUILDs in this git repo that have not yet been compiled & packaged.

Seems the submitters of them are mostly not developer in this git repo. If anybody interested, please adopt these packages.

 - [x] armadillo @kasei 
 - [ ] broadcom-wl
 - [x] coursera-dl-git (lilacbot committed it firstly, how could she?) @zsrkmyn
 - [x] devtools-lilac @farseerfc 
 - [x] iksemel
 - [x] muttils-hg
 - [x] pyfm @petronny
 - [x] python2-pyfm @petronny
 - [ ] python-flask-peewee
 - [ ] python-wtf-peewee
 - [ ] spek-git
 - [x] sysdig-git
 - [x] vidalia @ykelvis 
 - [x] vivaldi @phoenixlzx 
 - [x] xiami-downloader-git

Generated by:
```bash
for d in `ls`; do
    (cd $d && bash --restricted -c "source PKGBUILD; echo \${pkgname[@]}")
done 2>/dev/null | grep -v '[A-Z]' | xargs pacman -Si > /dev/null
```

**Comment by lilydjwg** [comment]
coursera-dl-git is by @zsrkmyn, see the committer, not message: 4a3aebf

**Comment by farseerfc** [comment]
devtools-lilac is intended to be used only by lilac itself for debugging purpose. @lilydjwg do we need to keep this? or else I will remove it.

**Comment by zsrkmyn** [comment]
On Tue, Apr 05, 2016 at 06:31:05AM -0700, 依云 wrote:
> coursera-dl-git is by @zsrkmyn, see the committer, not message: 4a3aebf
> 
Sorry, I just forgot to bump pkgrel to trigger rebuilding...
Thanks for reminding me!

-- 
Regards,
Stephen

**Comment by lilydjwg** [comment]
@farseerfc no need to keep it. Next time when we need it, we can package a new one (and we don't need to put it in the repo).

**Comment by zsrkmyn** [comment]
I don't know why, I've modified lilac.py and PKGBUILD (including pkgrel) of coursera-dl-git several times to trigger lilac's rebuilding, but none of those times succeeded.

Finally, I build the package manully and copyed it (and the .sig file) to ~/repo on build machine. However, I find it the package was remoeved from ~/repo but not pushed into archlinuxcn repo (pacman -Ss coursera-dl-git showed nothing).

**Comment by lilydjwg** [comment]
@zsrkmyn you should report the issue. Unknown issues are unlike to get fixed.

**Comment by zsrkmyn** [comment]
Thanks @lilydjwg, I found the problem just now, and I am doing some further test.

**Comment by ykelvis** [comment]
Vidalia is packaged now.

**Comment by zsrkmyn** [comment]
@ykelvis 快去签名你的包啦 >.< #218

**Comment by ykelvis** [comment]
@zsrkmyn 已经在搞了今晚能弄好_(:3」 ∠)_

**Comment by lilydjwg** [comment]
@zsrkmyn 我升级了服务器上的 repo-add 命令，现在 coursera-dl-git 应该已经有了（请给 rsync 一些时间）。

**Comment by zsrkmyn** [comment]
@lilydjwg, 已经好了呢！谢谢仙子！

**Comment by xgdgsc** [comment]
vivaldi是什么情况@phoenixlzx

**Comment by phoenixlzx** [comment]
抱歉，更新了一下，应该会自动更新&编译了

@lilydjwg 麻烦盯一下今晚的编译日志...

**Comment by phoenixlzx** [comment]
AUR 上的包维护者往里面扔了太多东西... 而且为什么有 gitignore
总之不能自动从 AUR 更新的话只好删掉了，谁有兴趣更新的话就重新加进去吧。我表示没时间天天盯着。

**Comment by lilydjwg** [comment]
为什么会有 .INSTALL 和 .MTREE 文件…………

**Comment by xgdgsc** [comment]
vivaldi从AUR更新的时候报什么错？要删的话nvchecker.ini里也删一下。

**Comment by petronny** [comment]
I will remove all the unchecked packages on the list on 9/9.

**Comment by petronny** [comment]
先删了一波，剩下的都是`Inkn <i@inkn.ml>`这个人的包
但是这个github id也不复存在了。。。

怎么办？删吗？

**Comment by petronny** [comment]
话说上面那个命令现在在chromium-dev会卡住。。

**Comment by petronny** [comment]
除broadcom-wl外的PKGBUILD均已修正
broadcom-wl我就drop了
它只能编译出对最新的kernel，这样每次kernel更新都要手动指定depends=('linux=$kernel_ver')并bump pkgrel
坑太大不想填了
