### ISSUE TITLE
python-torchvision-cuda out of date

### ISSUE THREAD

**Issue by xsxun** [archlinuxcn/repo#2204]
### 问题类型 / Type of issues
python-torchvision-cuda out of date because of the update of cuda 11.3, a related commit has been made but with no new package build

* 过期软件包 / out-of-date packages
python-torchvision-cuda, python-torchvision

### 受影响的软件包 / Affected packages

* python-pytorch-cuda

----

**Comment by hubutui** [comment]
最近 cuda 更新到 11.3 之后，编译有问题呀。编译日志见 https://build.archlinuxcn.org/~imlonghao/log/python-torchvision/2021-04-23T04%3A17%3A01.html。建议有空的话给上有报 bug，他们修好了我们才能打包成功。

**Comment by hubutui** [comment]
fixed by https://github.com/archlinuxcn/repo/commit/cbcf74f92b1f83194e9dc417e397553e629e1c5f

参考上游 issue 中的讨论，给 pytorch 打了 patch，现在应该可以正常打包了。等着 lilac 更新吧。
