### ISSUE TITLE
archlinuxcn/vim-youcompleteme-git 1765.41e4886-1 使用 extra/clang 3.7.1-1 中 /usr/lib/libclang.so.3.7 不存在的符号

### ISSUE THREAD

**Issue by MaskRay** [archlinuxcn/repo#221]
1763.1b76af4-1
% nm -CD /usr/share/vim/vimfiles/third_party/ycmd/ycm_core.so G clang_parseTranslationUnit                                           
                 U clang_parseTranslationUnit2    // 在/usr/lib/libclang.so.3.7 

1765.41e4886-1
% nm -CD /usr/share/vim/vimfiles/third_party/ycmd/ycm_core.so G clang_parseTrans
                 U clang_parseTranslationUnit2FullArgv   // 不在 /usr/lib/libclang.so.3.7

**Comment by zsrkmyn** [comment]
Orz... vim-youcompleteme-git is really hard to maintain, I may need a co-maintainer.

**Comment by zsrkmyn** [comment]
这还能 auto close 啊……
我重新打了包，但是依赖于 llvm 为 ubuntu 预编译好的 libclang.so，我已经关闭了 lilac 对 vim-youcompleteme-git 自动打包。
等待一个更好的解决方法……

**Comment by MaskRay** [comment]
lilac 上没有用 extra/clang 3.7.1-1   ?

**Comment by farseerfc** [comment]
> 这还能 auto close 啊……

Github 的 [feature](https://help.github.com/articles/closing-issues-via-commit-messages/) 233

**Comment by zsrkmyn** [comment]
@MaskRay lilac 最早使用的是 AUR 的 PKGBUILD, 用的 libclang.so 是 llvm 为 ubuntu 预先编译好的，但是我感觉这样做有点 dirty, 而且会让包的体积增大，所以改用了 extra/clang。但实际上 extra/clang 提供的 libclang.so 好像功能不全，补全和检查 C++ 的时候会有 bug，我又一直没找到更好的解决方案。
这次 ycm 上游升级之后改用了 libclang.so.3.8.0，extra/clang 版本 3.7.1，API 变化导致 ycm 直接崩溃了，所以我只能又手动打了一个带 llvm 预编译好的 libclang.so.3.8.0 的包发布了……

@farseerfc 明明是 bug >.<
