### ISSUE TITLE
[Package Request] Apostrophe

### ISSUE THREAD

**Issue by Atreyu-94** [archlinuxcn/repo#2226]
### 问题类型 / Type of issues

* 软件打包请求 / package request

-----https://aur.archlinux.org/packages/apostrophe/

* 简述 / Brief Description

    Apostrophe: A clean and intuitive Markdown editor designed for those of you who love a distraction-free writing environment.
https://somas.pages.gitlab.gnome.org/apostrophe/

* 主要语言和工具链 / Main Languages and Toolchains

    Python and GTK

* 上游链接 / Upstream Link

    https://aur.archlinux.org/packages/apostrophe/

* 为何需要这个软件包 / Why Need This Package

    A text editor with Markdown and math support without the overhead of Electron-based ones.

**Comment by axionl** [comment]
https://github.com/archlinuxcn/repo/commit/c5fd7b3aa7eb1052c2a0259b61140889b241ad99

- 上游的几种 markdown preview 模式还有点问题，可以先用 plain text markdown
- 目前的压缩包内带了 commit 版本号作为文件名，暂时使用手动更新
