### ISSUE TITLE
qv2ray:libprotobuf.so.26: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lu0se** [archlinuxcn/repo#2235]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* qv2ray 2.6.3-24 

----

在升级
[2021-05-11T17:17:32+0800] [ALPM] upgraded protobuf (3.15.8-1 -> 3.16.0-1)
后，无法运行qv2ray
在konsole中运行qv2ray时，提醒错误
qv2ray: error while loading shared libraries: libprotobuf.so.26: cannot open shared object file: No such file or directory

**Comment by axionl** [comment]
> 依云姐姐说[已经在队列里了](https://t.me/archlinuxcn_group/1982066)，就先等等吧……
> 这个包你可以先用着：[qv2ray-2.6.3-24-x86_64.pkg.tar.zst.zip](https://github.com/archlinuxcn/repo/files/6460068/newpack.zip)

建议也带个签名
