### ISSUE TITLE
chromium-dev patch to enable vaapi has changed

### ISSUE THREAD

**Issue by axfelix** [archlinuxcn/repo#224]
https://aur.archlinux.org/cgit/aur.git/diff/enable_vaapi_on_linux-r6.diff?h=chromium-dev&id=b5a14d11a111cdc7d2600868d439435f5f8eda2c

It wasn't working in your chromium-dev-50 build, I'm not sure if you can pull down the changes directly from the AUR the way you've done things. Worked in 49 and below.

**Comment by fqj1994** [comment]
Since a month ago, the chromium-dev is now just a build of AUR version. There is no longer my personal changes.
The community build server's CPU is not good enough to build chromium-dev under 30 minutes. Thus, I'm building this on my own device, where there's no key to push to github. I'll update github later in this month myself.
Regarding the not-updating in past days, it was due to no space left on disk. I forgot to remove older version source code and binaries before building new ones.
Now the rebuilding is running. A newer version of chromium-dev from AUR should land to archlinuxcn repo in less than 1 hour if there's no future error.

**Comment by axfelix** [comment]
Great, thanks! Hopefully vaapi is working again, I think your last build happened to occur right before the patch was updated to reflect newer Chromium source.

**Comment by lilydjwg** [comment]
WOW, you can build a browser within 30 minutes!

**Comment by fqj1994** [comment]
It looks something is wrong again, I'll take a look tomorrow.

**Comment by axfelix** [comment]
Thanks. You're the only ones who make prebuilt packages of chromium-dev so I really appreciate it.

**Comment by fqj1994** [comment]
Anybody know this before I take the time to start to inspect it on weekends?
http://img.vim-cn.com/65/0857062312a3a8fbb035620e65f09ad0764898.png

**Comment by axfelix** [comment]
There's a patch suggested as the top comment on the AUR package

**Comment by fqj1994** [comment]
ignore my comment above. Saw that on AUR comment

**Comment by axfelix** [comment]
Buld worked! thanks!! vaapi still seems broken but I just left a comment on the AUR and now that I know you're building directly from the AUR I won't bug you about it anymore.

**Comment by axfelix** [comment]
FYI, the minizip patch is in the AUR now, so you shouldn't have to tweak anything in the future.

**Comment by fqj1994** [comment]
I'll take a look at the VA-API at the end of this month, but no guarantee on results.

**Comment by axfelix** [comment]
It's fixed, actually, as of the last build you did! Looks like it was patched again between 2700 and 2704.

**Comment by fqj1994** [comment]
Oh, that's good news. I haven't upgraded the system yet today. As for 2700, it's only working for flash StageVideo.

**Comment by axfelix** [comment]
I noticed that after you built 2700. In 2704 it works with HTML5 video again.

**Comment by axfelix** [comment]
FYI -- I think the buildscript changed again, it was broken for 54 and it seems to be working now in 55. The archlinuxcn package is still on 53, the last time the old one worked.

**Comment by fqj1994** [comment]
It still fails the build at my place.
The error message is attached (in screenshot not text, sorry).
If you have idea on how to fix it please let me know. or I have to wait for next national holiday to have a look.

![screenshot 2016-09-26 at 10 34 13 pm](https://cloud.githubusercontent.com/assets/1436410/18850834/91c2cefa-8439-11e6-999e-51f07ebeaf6c.png)

**Comment by fqj1994** [comment]
Look like there are new build dependencies introduced. I'll have a look.

**Comment by fqj1994** [comment]
done

**Comment by axfelix** [comment]
Thanks a ton!

**Comment by axfelix** [comment]
FYI, just installed and it looks like the VAAPI patch for h264 hardware decoding has gone missing again ... but I suspect that the AUR maintainer probably just forgot to include it when he had to change the script to get 55 building. I've left a comment and I expect it'll be patched soon, I'm not sure if your buildsystem will automatically pull in the fix.
