### ISSUE TITLE
shadowsocks-rust{,-opt}-git packaging issues

### ISSUE THREAD

**Issue by rocka** [archlinuxcn/repo#2246]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* shadowsocks-rust-git
* shadowsocks-rust-opt-git

----

请在此补充说明。
Please describe in detail here.

In PKGBUILD, example configuration files are installed into `/etc/shadowsocks-rust/`,

https://github.com/archlinuxcn/repo/blob/06dd7dc54e696459ac74278f796a5ae1e8b837bc/archlinuxcn/shadowsocks-rust-opt-git/PKGBUILD#L31

but systemd service uses `/etc/shadowsocks/%i.json` as configuration path. 

https://github.com/archlinuxcn/repo/blob/06dd7dc54e696459ac74278f796a5ae1e8b837bc/archlinuxcn/shadowsocks-rust-opt-git/shadowsocks-rust-server%40.service#L8

Also, please consider enabling `local-redir` feature in shadowsocks-rust, like

https://github.com/shadowsocks/shadowsocks-rust/blob/98833da94ab7484f32fa872ac6865b4681762754/.github/workflows/build-and-test.yml#L47

which comes handy for client usage.

**Comment by DuckSoft** [comment]
ff161fe7d452f78d5fec19813a475cf801a21c95, 3708c97ddc2405db03b195dd81b7b3e3beea8c7e
