### ISSUE TITLE
pycharm-professional: start failed in zsh

### ISSUE THREAD

**Issue by wangjiezhe** [archlinuxcn/repo#226]
In zsh shell, when I start pycharm, it gives me:
```
/usr/share/doc/pkgfile/command-not-found.bash: line 7: syntax error near unexpected token `<'
/usr/share/doc/pkgfile/command-not-found.bash: line 7: `  mapfile -t pkgs < <(pkgfile -bv -- "$cmd" 2>/dev/null)'
```
since I source `command-not-found.bash` in my `.bashrc`, and then in `.bash_profile`, which is not compatible with zsh.

Changing `/bin/sh -l` to `/bin/bash -l` in `pycharm` can fix this problem.

**Comment by xgdgsc** [comment]
So you linked /bin/sh to zsh?

**Comment by wangjiezhe** [comment]
No, `/bin/sh` is linked to `bash`.
The default desktop file does not help.

**Comment by xgdgsc** [comment]
I tried to launch pycharm in my zsh and didn' t have this problem. Why would you source `/usr/share/doc/pkgfile/command-not-found.bash`?

**Comment by xgdgsc** [comment]
I also tried adding `source /usr/share/doc/pkgfile/command-not-found.bash` to `.bashrc` and it is fine to launch in zsh. I have pycharm-community instead.

**Comment by wangjiezhe** [comment]
There is no problem for pycharm-community, for it just links `/bin/pycharm` to `/opt/pycharm-community/bin/pycharm.sh`, unlike pycharm-professional, which use an additional start script.

I tried to start `/opt/pycharm-professional/bin/pycharm.sh` directly, and there is no problem, too.
BTW, I don't know the usage of souce `.bash_profile` in the start file.

**Comment by xgdgsc** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/pycharm?h=pycharm-professional I think you should report this to AUR package maintainer.

**Comment by petronny** [comment]
Is this still a problem?
