### ISSUE TITLE
shadowsocks-rust{,-opt}-git packaging issues

### ISSUE THREAD

**Issue by puxxustc** [archlinuxcn/repo#2260]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* shadowsocks-rust-git
* shadowsocks-rust-opt-git

----

Recent commit https://github.com/archlinuxcn/repo/commit/3708c97ddc2405db03b195dd81b7b3e3beea8c7e (which fixed this issue  https://github.com/archlinuxcn/repo/issues/2246), that changed configuration path to `/etc/shadowsocks-rust/`, will break existed shadowsocks-rust service.

Users need to move there config file from `/etc/shadowsocks/` to `/etc/shadowsocks-rust/` manually to fix this issue.

It would be better to print a notice in post-install hook.

**Comment by DuckSoft** [comment]
Good idea. Will put a notice in `postinstall`.
