### ISSUE TITLE
archlinuxcn/python-pytorch-lightning cannot be imported properly

### ISSUE THREAD

**Issue by showgood163** [archlinuxcn/repo#2262]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

archlinuxcn/python-pytorch-lightning 1.3.1-1

----

请在此补充说明。
Please describe in detail here.

archlinuxcn/python-pytorch-lightning cannot be imported properly

Software stack: archlinuxcn/python-pytorch-lightning 1.3.1-1 and other up-to-date packages

problem reproduce procedure:

Run `ipython` to import pytorch lightning and the error shows up like:

```
In [3]: import pytorch_lightning as pl
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-efd8697dde72> in <module>
----> 1 import pytorch_lightning as pl

/usr/lib/python3.9/site-packages/pytorch_lightning/__init__.py in <module>
     18 _PROJECT_ROOT = os.path.dirname(_PACKAGE_ROOT)
     19 
---> 20 from pytorch_lightning import metrics  # noqa: E402
     21 from pytorch_lightning.callbacks import Callback  # noqa: E402
     22 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402

/usr/lib/python3.9/site-packages/pytorch_lightning/metrics/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from pytorch_lightning.metrics.classification import (  # noqa: F401
     16     Accuracy,
     17     AUC,

/usr/lib/python3.9/site-packages/pytorch_lightning/metrics/classification/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
     15 from pytorch_lightning.metrics.classification.auc import AUC  # noqa: F401
     16 from pytorch_lightning.metrics.classification.auroc import AUROC  # noqa: F401

/usr/lib/python3.9/site-packages/pytorch_lightning/metrics/classification/accuracy.py in <module>
     16 from torchmetrics import Accuracy as _Accuracy
     17 
---> 18 from pytorch_lightning.metrics.utils import deprecated_metrics
     19 
     20 

/usr/lib/python3.9/site-packages/pytorch_lightning/metrics/utils.py in <module>
     16 
     17 import torch
---> 18 from deprecate import deprecated
     19 from torchmetrics.utilities.data import dim_zero_cat as _dim_zero_cat
     20 from torchmetrics.utilities.data import dim_zero_mean as _dim_zero_mean

ModuleNotFoundError: No module named 'deprecate'
```

**Comment by showgood163** [comment]
Why do you close this issue?

Other information about this problem:

pytorch-lightning 1.3.1 requires pyDeprecate==0.3.0, which is not installed.
pytorch-lightning 1.3.1 requires fsspec[http]>=2021.4.0, but you have fsspec 0.8.7 which is incompatible.
pytorch-lightning 1.3.1 requires tensorboard!=2.5.0,>=2.2.0, but you have tensorboard 2.5.0 which is incompatible.

**Comment by hubutui** [comment]
* `python-pydeprecate` is added to deps.
* `python-fsspec` is from [official repo](https://archlinux.org/packages/community/any/python-fsspec/), and it's marked out-of-date.
* `tensorboard` is from [official repp](https://archlinux.org/packages/community/x86_64/tensorboard/). ArchLinux will always install the latest release. I you need a specific version, check [Arch Linux Archive](https://wiki.archlinux.org/title/Arch_Rollback_Machine)
