### ISSUE TITLE
anaconda 过期

### ISSUE THREAD

**Issue by taotieren** [archlinuxcn/repo#2272]
### 问题类型 / Type of issues
anaconda 过期
```bash
https://repo.anaconda.com/archive/Anaconda3-2021.05-Linux-x86_64.sh
```
* 过期软件包 / out-of-date packages
anaconda

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----

**Comment by xgdgsc** [comment]
@petronny

**Comment by yan12125** [comment]
2021.05 has been available for a while https://build.archlinuxcn.org/packages/#/anaconda
