### ISSUE TITLE
[build fail] kicad-git编译失败

### ISSUE THREAD

**Issue by RigoLigoRLC** [archlinuxcn/repo#2284]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* kicad-git

----

kicad-git近日由于不明原因，CMake找不到合适的wxwidgets导致构建在早期失败。

[KISS2UI上的build log](https://build.archlinuxcn.org/packages/#/kicad-git/logs/1621084838)

**Comment by RigoLigoRLC** [comment]
初步确认是kicad上游使用了最新的wxwidgets3.1.5开发版本，此版本并未被Arch提供。将联系Arch上游确认更新、kicad上游关于wx版本情况。与ArchCN编译无关。

**Comment by RigoLigoRLC** [comment]
经进一步检查，发现问题源于[ArchLinux打包错误](https://bugs.archlinux.org/task/70908?project=5&string=python-wxpython)，wxpython错误打包导致编译时找不到最新的wxWidgets。

**Comment by taotieren** [comment]
@edward-p 仔细检查是 wxpython 版本过高。现已降级。请重新触发一下 kicad-git 的编译。
