### ISSUE TITLE
115wangpan 官方已经挂了啊

### ISSUE THREAD

**Issue by Ray2xiao** [archlinuxcn/repo#229]
如题

**Comment by petronny** [comment]
115yun_linux_v4.0.1.deb这个文件仍然可以被下载，这个包也可以正常被打包。
是115关闭了登录接口吗？

**Comment by Ray2xiao** [comment]
我这并不能登陆，一直密码错误，有条件的在试试看吧

**Comment by Ray2xiao** [comment]
刚去官方看并没有 linux 版本，只有 win 和 mac，可能已经不支持 linux 了。

**Comment by petronny** [comment]
嗯那我先清理掉这个包好了，你也可以去AUR汇报一下
