### ISSUE TITLE
yay-git is not built against pacman-git

### ISSUE THREAD

**Issue by SamLukeYes** [archlinuxcn/repo#2296]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* yay-git
* pacman-git

----

```bash
$ yay
yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory

$ pacman -Qi yay-git
名字           : yay-git
版本           : 10.2.2.r0.g4993e4d-1
描述           : Yet another yogurt. Pacman wrapper and AUR helper written
                 in go. (development version, build for pacman-git)
架构           : x86_64
URL            : https://github.com/Jguer/yay
软件许可       : GPL3
组             : 无
提供           : yay
依赖于         : pacman>5  git  sudo
可选依赖       : 无
依赖它         : 无
被可选依赖     : 无
与它冲突       : yay-bin  yay
取代           : 无
安装后大小     : 10.08 MiB
打包者         : lilac (on behalf of ArielAxionL) <i@axionl.me>
编译日期       : 2021年05月10日 星期一 22时07分27秒
安装日期       : 2021年05月26日 星期三 08时40分43秒
安装原因       : 单独指定安装
安装脚本       : 否
验证者         : 数字签名
```

**Comment by axionl** [comment]
`yay-git` is currently not built on `pacman-git`

**Comment by SamLukeYes** [comment]
> `yay-git` is currently not built on `pacman-git`

But the package description says it is built for `pacman-git` :confused:

**Comment by axionl** [comment]
> > `yay-git` is currently not built on `pacman-git`
> 
> But the package description says it is built for `pacman-git` confused

The current problem is that the build parameters cannot be passed by the lilac, `pacman-git` will not replace `pacman` by default. :laughing: 

https://github.com/archlinuxcn/repo/commit/457146e77febff9cad3e03377dc6bba8a5534ea0

**Comment by SamLukeYes** [comment]
OK, I'll build yay from AUR :sweat_smile:
