### ISSUE TITLE
MimeType is missing in chromium-dev

### ISSUE THREAD

**Issue by wicast** [archlinuxcn/repo#230]
It should batter add this line  `MimeType=text/html;text/xml;application/xhtml+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
` to chromium-dev.desktop.

chromium-dev is not working fine with xdg-open,please fix it @fqj1994.

**Comment by fqj1994** [comment]
Please leave comment on aur/chromium-dev to its maintainer
This package is just a binary build of it.
