### ISSUE TITLE
code-transparent

### ISSUE THREAD

**Issue by caigoul** [archlinuxcn/repo#2335]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* code-transparent 1.56.2-1

----

请在此补充说明。

从 archlinuxcn 安装 code-transparent 时，依赖的 electron 版本为 13.1.4-1，但是版本太新了，导致 vscode 无法启动。
安装 electron12，并将 `/usr/bin/code` 里的 `electron` 替换成 `electron12`后，vscode 成功启动。

**Comment by frantic1048** [comment]
刚刚更新了一波：

- https://github.com/frantic1048/pkgbuilds/commit/0936bc42f93da0adf152644966c8d723cd15d18a
- https://aur.archlinux.org/cgit/aur.git/commit/?h=code-transparent&id=93f02d3722c064d98df37c1f63dab34b1b1d60b3

同时目前 cn 源的 `code-transparent` 应该正常依赖 `electron12` 且能正确工作了，可以滚一下 code-transparent 到 1.56.2-2 试试

由于已经在最新的 Arch 上测过能工作了，所以这个 issue 我先 close 了，如果发现有这个问题的后续问题请重新 open 这个 issue

**Comment by frantic1048** [comment]
@SamLukeYes 这个 issue 是记录旧的 code-transparent 1.56.2-1 的打包问题的，如果是遇到 code-transparent 这个包的新问题，比较建议开一个单独的 issue

> 上游更新 1.59.1 了，目前 vscode 默认的 electron 版本已经是 13（然而用官方仓库中的 electron 构建出来的无法启动，用 electron12 构建反而可以）

感谢反馈，请问尝试的时候具体是通过什么操作来进行「用官方仓库中的 electron 构建」的呢？

关于 electron 方面的话，目前 electron v13 尚未有单独的包（类似 electron10 electron11 electron12 这样的固定大版本的包），如果把依赖改回到 electron 的话，很可能在 Arch 这边 electron 升 14 的时候遇到这个 issue https://github.com/archlinuxcn/repo/issues/2335#issue-929743556 一样的问题。

以及我确实还没有测试过以 electron13 做依赖构建新的 1.59.1 是否工作，如果这个组合能用的话，兴许可以糊一个 electron13 的包放在 CN 源里（直到官方源有 electron13 的包）来避免 electron 升级的问题 :thinking:

**Comment by SamLukeYes** [comment]
我试过用官方仓库的 electron 13.2.3 编译的 code 1.60.0 是能跑起来的。另外，python2 的依赖应该改成 python 了，相应的要把 build() 中把 python2 链接为 python 的部分删掉。
