### ISSUE TITLE
outdated packages

### ISSUE THREAD

**Issue by zhmars** [archlinuxcn/repo#2339]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

- gnome-shell-extension-appindicator-git
- gnome-shell-extension-dash-to-dock
- gnome-shell-extension-volume-mixer-git
- pidgin-wechat-git
- fprintd-git

----

**Comment by swordfeng** [comment]
lilac 打包失败几次 没时间看……

**Comment by axionl** [comment]
`fprintd-git`: https://github.com/archlinuxcn/repo/commit/5522532db2a1c799df0f366f4ccd7704a67a8aff

**Comment by zhmars** [comment]
Same of #2341.
