### ISSUE TITLE
deepin-fonts-wine: license issue

### ISSUE THREAD

**Issue by zhmars** [archlinuxcn/repo#2343]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* deepin-fonts-wine

----

**Comment by lilydjwg** [comment]
These fonts come from the Wine project, thus the license should be LGPL. The copyright file within the package says this too. The license field of PKGBUILD seems to be wrong.

**Comment by zhmars** [comment]
@Skywol It has been seven months since your last activity. I hope everything is fine with you. 

When you have time, please also check packages below. Their source urls return `404 Not Found`.

- deepin-wine-helper
- deepin-wine32
- deepin-wine32-tools
- deepin-wine32-preloader
- deepin-wine-binfmt
- deepin-wine-uninstaller

**Comment by zhmars** [comment]
All packages have been removed, see https://github.com/archlinuxcn/repo/issues/2403.
