### ISSUE TITLE
wine-wayland 打包请求

### ISSUE THREAD

**Issue by demolg** [archlinuxcn/repo#2353]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    Wine-wayland allows running DX9/DX11/DX12 and Vulkan games using pure Wayland and Wine/DXVK.

* 主要语言和工具链 / Main Languages and Toolchains

    C, CSS, Meson, JS, HTML

* 上游链接 / Upstream Link

    https://github.com/varmd/wine-wayland

* 为何需要这个软件包 / Why Need This Package

  上游仓库内提供了PKGBUILD文件，release页面也提供了archlinux二进制包。该项目对wine增加了wayland支持，本体纯x86_64构架，并附加了一个可选的lib32的整合包，避免了启用multilib仓库。最新版本分离了wineland（一个启动器），可以在用户级别下安装wine-wayland。

**Comment by lilydjwg** [comment]
既然上游都提供现成的包了，就不需要再另外打了呀？

**Comment by demolg** [comment]
用包管理器方便啊
