### ISSUE TITLE
bcc 提示 CommandLine Error

### ISSUE THREAD

**Issue by condy0919** [archlinuxcn/repo#2355]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* bcc-tools-git

----

```
condy@Youmu ~ % bcc exitsnoop
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
[1]    843304 abort (core dumped)  bcc exitsnoop
```

https://github.com/iovisor/bcc/issues/3333 在这里提示说是需要在构建 bcc 的时候加上 `ENABLE_LLVM_SHARED` 参数

**Comment by lilydjwg** [comment]
I've also uploaded a new build (but unfortunately I forgot to update the version number). You can redownload and reinstall the package, or wait lilac to rebuild.

**Comment by condy0919** [comment]
经验证，确实修复了
