### ISSUE TITLE
Some packages Request

### ISSUE THREAD

**Issue by HighIO** [archlinuxcn/repo#236]
https://aur.archlinux.org/packages/'$package_name'

Theme/Style:  adapta-gtk-theme, grub2-theme-arch-leap
Security: firejail, firetools
Multimedia:  gnome-mpv, mpv-bash-completion-git
Utilities: anything-sync-daemon, keepassx-http, lostfiles, profile-cleaner, profile-sync-daemon, virtio-win

ps:  python-aiohttp  is required by archsocks

THX

**Comment by lilydjwg** [comment]
python-aiohttp is required by archsocks. However newer versions of python-aiohttp is broken as it requires a package that doesn't have a download link on PyPI. Do you meet any problem with archsocks?

**Comment by HighIO** [comment]
Archsocks works fine with python-aiohttp AUR version by downloading from https://gemnasium.com/pypi/aiohttp/versions/0.21.5

**Comment by lilydjwg** [comment]
It works with current [archlinuxcn] version too.

**Comment by lastavenger** [comment]
`adapta-gtk-theme` in repo now.

**Comment by ykelvis** [comment]
- [ ] adapta-gtk-theme
- [ ] grub2-theme-arch-leap
- [ ] firejail
- [ ] firetools
- [ ] gnome-mpv
- [ ] mpv-bash-completion-git
- [ ] anything-sync-daemon
- [ ] keepassx-http
- [ ] lostfiles
- [ ] profile-cleaner
- [ ] profile-sync-daemon
- [ ] virtio-win
- [ ] python-aiohttp

**Comment by ykelvis** [comment]
最后一个 `python-aiohttp` 看起来也加了lilac让机器人来更新，没有其它问题这个issue就关啦？
