### ISSUE TITLE
gnome-shell-extension-gsconnect-git doesn't exist in [archlinuxcn] repo

### ISSUE THREAD

**Issue by SamLukeYes** [archlinuxcn/repo#2367]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* gnome-shell-extension-gsconnect-git

----

This package seems to be maintained by archlinuxcn, but doesn't exist in the repo.

https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/gnome-shell-extension-gsconnect-git
https://github.com/archlinuxcn/repo/issues/2364#issuecomment-881847697

**Comment by KenOokamiHoro** [comment]
It should available in the repo after https://github.com/archlinuxcn/repo/commit/53a4c252652fd29ed687ae577b23aadacc8780dd#diff-042dd2beb5f7e55972dda8e46f8f92947e49108c7d029feabd36dc2d7e6f99d8 .

**Comment by SamLukeYes** [comment]
> It should available in the repo after https://github.com/archlinuxcn/repo/commit/53a4c252652fd29ed687ae577b23aadacc8780dd#diff-042dd2beb5f7e55972dda8e46f8f92947e49108c7d029feabd36dc2d7e6f99d8 .
> 

Confirmed.
