### ISSUE TITLE
pkgtools缺少依赖pacman-contrib

### ISSUE THREAD

**Issue by amaothree** [archlinuxcn/repo#2368]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  pkgtools

----

缺少依赖pacman-contrib。`pkgtools`中的`whoneeds`命令需要`pacman-contrib`中的`pactree`命令才可以正常运行。

**Comment by farseerfc** [comment]
Added on AUR
