### ISSUE TITLE
欧路词典eudic打包请求

### ISSUE THREAD

**Issue by w594833736** [archlinuxcn/repo#2375]
### 问题类型 / Type of issues

* 软件打包请求 / package request
eudic
----

* 简述 / Brief Description
Proprietary English dictionary software for linux

* 主要语言和工具链 / Main Languages and Toolchains

* 上游链接 / Upstream Link
https://aur.archlinux.org/packages/eudic/

* 为何需要这个软件包 / Why Need This Package
study tools

**Comment by oldherl** [comment]
此软件包的许可证 (license) 是什么？是否允许 ArchCN 重打包和重分发？

如果你认为可以，请附上 license 的链接或全文，再 reopen。
