### ISSUE TITLE
missing i686 ver for libappindicator-activate-gtk{2,3}

### ISSUE THREAD

**Issue by ykelvis** [archlinuxcn/repo#238]
I checked there are x86_64 ver for them, but not i686.

**Comment by farseerfc** [comment]
Most packages built by lilac have x86_64 but no i686 counterparts.
I can build and upload them manually, but I cannot guarantee to update them as lilac does.
Is it OK?

**Comment by farseerfc** [comment]
see also #52

**Comment by ykelvis** [comment]
That's ok, please upload them, thanks.

**Comment by farseerfc** [comment]
`libappindicator-activate-{gtk2,gtk3,sharp}-12.10.0-7-i686.pkg.tar.xz` are now in `~/repo` waiting for sync.
