### ISSUE TITLE
 paru 构建时没有执行 scripts/mkmo

### ISSUE THREAD

**Issue by peng1999** [archlinuxcn/repo#2388]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* paru

----

paru 1.8.0 已经支持多语言，参见 https://aur.archlinux.org/cgit/aur.git/commit/?h=paru&id=656778d6f4886a79bec2483da0e55248742d57d2

**Comment by axionl** [comment]
https://github.com/archlinuxcn/repo/commit/e3047b3c09872dc075bde7c43e01fc4dfbf4d95f
