### ISSUE TITLE
Where is linux-surfacepro3-headers ?

### ISSUE THREAD

**Issue by KenOokamiHoro** [archlinuxcn/repo#239]
`linux-surfacepro3` in AUR includes `linux-surfacepro3-headers `and `linux-surfacepro3-docs` but these are not in [archlinuxcn] repository. It may cause some error like could not install DKMS module, please add them :-)

**Comment by lilydjwg** [comment]
@petronny 我想你需要编写 package.list 了。

**Comment by petronny** [comment]
正@你准备问应该怎么做呢。。

**Comment by petronny** [comment]
除了添加package.list外还有其他要修改的吗？

**Comment by lilydjwg** [comment]
没有了。不过你得重新上传一次不在了的包，因为之前的已经被删掉了……

**Comment by KenOokamiHoro** [comment]
`linux-surfacepro3-docs` and` linux-surfacepro3-headers `are in repository,but they seem doesn't have 
dependencies :joy:

```
(1/1) 正在更新 linux-surfacepro3                                          [#########################################] 100%
(1/1) Install DKMS modules
==> No kernel 4.6.0-2-surfacepro3 headers. You must install them to use DKMS!
```

**Comment by petronny** [comment]
`linux-headers` is not a dependency  or optional dependency of `linux`.
So `linux-surfacepro3-headers` should not be a dependency of `linux-surfacepro3` either.
Just install it manually.

**Comment by KenOokamiHoro** [comment]
I see :-)
