### ISSUE TITLE
anbox-git pkgver

### ISSUE THREAD

**Issue by T2hhbmEK** [archlinuxcn/repo#2394]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* anbox-git

----

21dce8933ae8e9fa313c047fe50baf46e004cf14
这个 commit 改了 pkgver，把 r 去掉了，导致 archlinuxcn 过期的包比 aur 编译的包版本高。
暂时需要在 `/etc/pacman.conf` 忽略才不会被错误升级
```bash
$ sudo pacman -Syu
警告：anbox-git：忽略软件包升级 (1:r1353.fb67729-1 => 1:1346.7d1930c-2)
```

**Comment by oldherl** [comment]
我不觉得这是个问题。archlinuxcn 上面的包本来就和 aur 上面的同名包没有关系，即使是从那里拿的 PKGBUILD 也不代表支持能互相替代着用。

如果你的问题是 anbox-git 没有成功打包，那倒是一个问题。

**Comment by T2hhbmEK** [comment]
> 我不觉得这是个问题。archlinuxcn 上面的包本来就和 aur 上面的同名包没有关系，即使是从那里拿的 PKGBUILD 也不代表支持能互相替代着用。
> 
> 如果你的问题是 anbox-git 没有成功打包，那倒是一个问题。

针对这种情况是否有好的解决方案，还是只有 `IgnorePkg` 这一种

**Comment by oldherl** [comment]
两种方法：
1. 等 archlinuxcn 源里面的 anbox-git 修好

**Comment by oldherl** [comment]
我在尝试修复了： a294f732
