### ISSUE TITLE
please update atom-editor

### ISSUE THREAD

**Issue by sbwtw** [archlinuxcn/repo#240]
the last release is v1.7.4

**Comment by farseerfc** [comment]
Strange enough I have configured lilac to follow AUR for atom-editor, but it didn't build, and no errors.
Try to trigger it using a git commit, I will see the result tonight.

**Comment by farseerfc** [comment]
Found out that AUR/atom-editor pushed 1.7.4 only 3 hours ago. So we should wait...

**Comment by farseerfc** [comment]
Updated by lilac automatically b9ca28311aa3eb093c23ba6ecbfa0e90be25b982
