### ISSUE TITLE
`google-chrome` and `libcurl-compat` are out-of-date

### ISSUE THREAD

**Issue by FiveYellowMice** [archlinuxcn/repo#242]

**Comment by lilydjwg** [comment]
Is `google-chrome` still out of date?

**Comment by ykelvis** [comment]
No. google-chrome is updated by lilac automatically.

**Comment by zsrkmyn** [comment]
`google-chrome` was owned by @phoenixlzx first, and then maintained by  @ykelvis. Later I saw the topic [here](http://bbs.archlinuxcn.org/viewtopic.php?id=2084), but didn't realize that @ykelvis was the maintainer so I added a `lilac.py` to it. I am sorry...

**Comment by FiveYellowMice** [comment]
They look up today now, closing this.
