### ISSUE TITLE
orphaning python-onnxconverter-common, python-fire, python-keras2onnx for yan12125

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#2429]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* python-onnxconverter-common
* python-fire
* python-keras2onnx

----

These packages were cleaned up during the 2021 cleanup (#2364). If any maintainers want to adopt any of them, it's time to take action!

**Comment by yan12125** [comment]
I orphaned python-onnxconverter-common and python-keras2onnx on AUR.
