### ISSUE TITLE
chromium-dev OUT-OF-DATE

### ISSUE THREAD

**Issue by BigEars431** [archlinuxcn/repo#243]
First of all thank you guys so much for the consistent maintenance of this repo, the package chromium-dev is OUT-OF-DATE

**Comment by fqj1994** [comment]
building....


忘记开机了。。

**Comment by fqj1994** [comment]
clang built.
building chromium

**Comment by fqj1994** [comment]
done. it should be landed at next push cycle.

**Comment by BigEars431** [comment]
thanks, i really rely a lot on your repo, I am a Web-Developer and google-chrome, chromium etc. doesn't have the patches chromium-dev has (VAVDA implementation etc.), not having to compile chromium-dev every nightly release (which takes a long time) really helps my productivity, hope the archlinuxcn repo stays up =)) Thanks again =))

**Comment by BigEars431** [comment]
Thank you so much =))
