### ISSUE TITLE
orphaning 6 packages for zsrkmyn

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#2431]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* coursera-dl-git
* picom-git
* sqlmap-git
* universal-ctags-git

----

These packages were cleaned up during the 2021 cleanup (#2364). If any maintainers want to adopt any of them, it's time to take action!

----

* archlinuxcn-mirrorlist-git taken by @lilydjwg
* nvchecker-git taken by @yan12125

**Comment by yan12125** [comment]
I will take over nvchecker-git if the original maintainer does not pop up.

**Comment by zsrkmyn** [comment]
Thanks for taking the maintainer-ship. I haven't powered on my personal laptop for very long time and thus have little chance to use Arch. It's hard for me to maintain Arch packages. I apologize for my absence from duty.
