### ISSUE TITLE
Please add linux-lts419 and linux-lts54

### ISSUE THREAD

**Issue by Red54** [archlinuxcn/repo#2437]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

   Please add linux-lts419 and linux-lts54

* 主要语言和工具链 / Main Languages and Toolchains

    C and GCC

* 上游链接 / Upstream Link

    https://aur.archlinux.org/packages/linux-lts419/
    https://aur.archlinux.org/packages/linux-lts54/

* 为何需要这个软件包 / Why Need This Package

    Some specific versions of the kernel are required to debug some drivers

**Comment by oldherl** [comment]
cc @felixonmars as he is maintaining linux-lts4{4,9,14}
