### ISSUE TITLE
atom-editor-bin CRASH

### ISSUE THREAD

**Issue by Arondight** [archlinuxcn/repo#244]
1. [atom-editor-bin](https://github.com/archlinuxcn/repo/tree/6f564641557e5664e852321ec9865f216c71ae8c/atom-editor-bin) 崩的妈都不认识了
+ [atom-editor](https://github.com/archlinuxcn/repo/tree/6f564641557e5664e852321ec9865f216c71ae8c/atom-editor) 一切正常

多台机器出现此现象。

**Comment by farseerfc** [comment]
已知現象，這就是爲什麼我們有兩個包在源裏。
atom-editor-bin 是上游給 debian 編譯的包重新打包，之前一段時間工作得挺好，最近和 arch 貌似不太融洽的樣子。
atom-editor 是源代碼編譯的包，最近工作得不錯，以前有段時間編譯過程一直崩……

反正選一個你能用的就好啦，我還在考察這倆包哪個更穩定一點。

參見 #231 #91 和 atom/atom#11198
