### ISSUE TITLE
Heroku CLI

### ISSUE THREAD

**Issue by mahmoudhossam** [archlinuxcn/repo#2442]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

The Heroku CLI enables access to [Heroku](https://www.heroku.com/home)

* 主要语言和工具链 / Main Languages and Toolchains

It's written in Node.js and can also be installed like so (although it's not recommended):

```bash
$ npm install -g heroku
```

* 上游链接 / Upstream Link

https://devcenter.heroku.com/articles/heroku-cli

* 为何需要这个软件包 / Why Need This Package

It's a developer tool that'd be helpful to anyone looking to quickly deploy an app.

**Comment by zjuyk** [comment]
Done with 132f94e
