### ISSUE TITLE
fcitx-sogoupinyin OUT-OF-DATE

### ISSUE THREAD

**Issue by bianjp** [archlinuxcn/repo#245]
Hi, I'm the maintainer of [fcitx-sogoupinyin](https://aur.archlinux.org/packages/fcitx-sogoupinyin/) AUR package.
I've updated it to 2.0.0.0078-3 two days ago, but it's still 2.0.0.0078-1 in this repo.

Is something wrong?

By the way, how frequently do you check for new versions?

**Comment by cuihaoleo** [comment]
lilac should have upgraded the package automatically. I didn't receive error reports from her, so I just edited the pkgrel manually to trigger a upgrade.

Maybe a bug of lilac or nvchecker.

**Comment by bianjp** [comment]
@cuihaoleo 
Thanks. But you should not just update `pkgrel`. Please update the full `PKGBUILD` file.

**Comment by farseerfc** [comment]
@bianjp lilac will update the whole directory from AUR when she saw a bump of `pkgrel` in git history. Usually she wakes up every 8 hours.

**Comment by bianjp** [comment]
Seems that it's still not updated.

**Comment by lilydjwg** [comment]
@bianjp lilac met a race condition bug....

**Comment by cuihaoleo** [comment]
New version has been built successfully by lilac~
