### ISSUE TITLE
ntfs3-dkms build failed ?

### ISSUE THREAD

**Issue by Nullizer** [archlinuxcn/repo#2451]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* ntfs3-dkms

----

https://repo.archlinuxcn.org 上没有更新到aur上的最新版，但 https://build.archlinuxcn.org 显示是编译过最新版的，怀疑打包出错。

**Comment by DDoSolitary** [comment]
https://aur.archlinux.org/packages/ntfs3-dkms/?O=10&PP=10#comment-819483

> Seems like the only change in v27 is for 5.14 kernel version. Backporting is literally equal to reverting back to v26 state.
So the package update to v27 is not possible until Arch mainstream kernel will be updated to 5.14.

根据 aur 维护者的说法 v27 仅包含针对 5.14 内核的更改，所以我没有放新版

**Comment by Nullizer** [comment]
了解了
