### ISSUE TITLE
升级 xrdp 0.9.17-1 后无法登录远程桌面了

### ISSUE THREAD

**Issue by silkriver** [archlinuxcn/repo#2456]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* xrdp

----

after upgraded to xrdp 0.9.17-1 remote desktop connection is broken，xrdp.log shows message "error loading libvnc.so specified in xrdp.ini"
downgraded to xrdp 0.9.16-2 solve the problem

**Comment by hubutui** [comment]
I think you should report this to xrdp upstream first, not here. And BTW, @colinkeenan doesn't speak Chinese.

**Comment by yan12125** [comment]
xrdp is removed along with xorgrdp (#2469, #2411)
