### ISSUE TITLE
google-chrome{,-beta,-dev} isnt allowed to be redistributed and modified

### ISSUE THREAD

**Issue by fabiscafe** [archlinuxcn/repo#2458]
### 问题类型 / Type of issues
The following packages are not allowed to be made available in archlinuxcn and be modified by the packagers because of googles Terms of Service

* google-chrome-$VER-$ARCH.pkg.tar.zst
* google-chrome-beta-$VER-$ARCH.pkg.tar.zst
* google-chrome-dev-$VER-$ARCH.pkg.tar.zst

S: https://policies.google.com/terms#toc-software
```
You may not copy, modify, distribute, sell, or lease any part of our services or software.
```

### 受影响的软件包 / Affected packages

*  google-chrome
* google-chrome-beta
* google-chrome-dev

----

**Comment by oldherl** [comment]
That URL is a general terms for all Google products. Do you have a specific license text of Google Chrome?

**Comment by imi415** [comment]
According to the license section of the "About Google Chrome" menu, it has the following statements:
```
Google Chrome and Chrome OS Additional Terms of Service
Last modified: 01 January, 2021

By using Chrome or Chrome OS, you agree to the Google Terms of Service located at https://policies.google.com/terms and these Google Chrome and Chrome OS Additional Terms of Service.
...
```
So yes, I think the policies mentioned above applies to Chrome.

**Comment by lilydjwg** [comment]
@phoenixlzx

**Comment by petronny** [comment]
> 您不得复制、修改、分发、出售或出租我们的服务或软件的任何部分，也不得进行反向工程或试图提取该软件的源代码，除非法律允许您这么做或您已获得 Google 的书面许可。

以下是我的个人观点，不代表 archlinuxcn 的书面回复。

我认为我们目前的分发行为是在法律允许的范围内的，因为我们主观上没有恶意使用，也没有看到潜在的道德或法律风险。

法律是个客观的事，我就不说了。道德上说，的确有第三方重新打包会增加原开发人员工作量的问题，但目前这两个包仅仅是简单的复制文件，我认为没有道德上的风险。

如果你认为有潜在的道德或法律风险，或者我们违反了哪些法律，请指出，我们会立刻移除这个包。

**Comment by imi415** [comment]
> > 您不得复制、修改、分发、出售或出租我们的服务或软件的任何部分，也不得进行反向工程或试图提取该软件的源代码，除非法律允许您这么做或您已获得 Google 的书面许可。
> 
> 以下是我的个人观点，不代表 archlinuxcn 的书面回复。
> 
> 我认为我们目前的分发行为是在法律允许的范围内的，因为我们主观上没有恶意使用，也没有看到潜在的道德或法律风险。
> 
> 法律是个客观的事，我就不说了。道德上说，的确有第三方重新打包会增加原开发人员工作量的问题，但目前这几个包仅仅是简单的复制文件，我认为没有道德上的风险。（反之，如果重打包过程中有较为复杂的修改，我认为道义上是过不去的。）
> 
> 如果你认为有潜在的道德或法律风险，或者我们违反了哪些法律，请指出，我们会立刻移除这个包。

计算机软件保护条例（2013年1月30日第二次修订） 第十六条第三款［1］：
```
为了把该软件用于实际的计算机应用环境或者改进其功能、性能而进行必要的修改；但是，除合同另有约定外，未经该软件著作权人许可，不得向任何第三方提供修改后的软件。
```
客观上确实不允许向第三方提供修改后的软件，假定前提是适用中华人民共和国法律的情况下。
［1］:http://www.gov.cn/zwgk/2013-02/08/content_2330130.htm

**Comment by phoenixlzx** [comment]
我们以前得到过 Google 工作人员“在小范围内分发”的许可，其中“小范围”指小于 1000 用户。但是我现在找不到这封邮件了...

但是考虑到目前 repo 的知名度和访问量来看，应该不再属于“小范围”，所以除非获得新的许可，需要 drop 这些包。
