### ISSUE TITLE
 visual-studio-code-insiders-bin: license issue

### ISSUE THREAD

**Issue by zhmars** [archlinuxcn/repo#2461]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  visual-studio-code-insiders-bin

----

Similar of #2460. 

Plus the PKGBUILD not found from `master` branch, but  the package can be downloaded from [repository](https://repo.archlinuxcn.org/x86_64/). @poscat0x04

**Comment by yan12125** [comment]
It's orphaned in #2425. PKGBUILDs removed from this git repo will be removed from the binary repo [archlinuxcn] by https://github.com/archlinuxcn/misc_scripts/blob/master/repocleaner. There is a delay, though. Now visual-studio-code-insiders-bin does not exist in [archlinuxcn].
