### ISSUE TITLE
linuxqq: license issue

### ISSUE THREAD

**Issue by zhmars** [archlinuxcn/repo#2462]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  linuxqq

----

QQ软件许可及服务协议

```
8.2.2 软件使用
除非法律法规允许或腾讯书面许可，您不得从事下列行为：
（1）删除本软件及其副本上关于著作权的信息。
（2）对本软件进行反向工程、反向汇编、反向编译，或者以其他方式尝试发现本软件的源代码。
（3）对腾讯拥有知识产权的内容进行使用、出租、出借、复制、修改、链接、转载、汇编、发表、出版、建立镜像站点等。
（4）对本软件或者本软件运行过程中释放到任何终端内存中的数据、软件运行过程中客户端与服务器端的交互数据，以及本软件运行所必需的系统数据，进行复制、修改、增加、删除、挂接运行或创作任何衍生作品，形式包括但不限于使用插件、外挂或非腾讯经授权的第三方工具/服务接入本软件和相关系统。
（5）通过修改或伪造软件运行中的指令、数据，增加、删减、变动软件的功能或运行效果，或者将用于上述用途的软件、方法进行运营或向公众传播，无论这些行为是否为商业目的。
（6）通过非腾讯开发、授权的第三方软件、插件、外挂、系统，登录或使用本软件和/或本服务，或制作、发布、传播上述工具。
（7）自行、授权他人或利用第三方软件对本软件和/或本服务及其组件、模块、数据等进行干扰。
（8）其他可能影响、干扰本软件和/或本服务正常运行的行为。
```

**Comment by petronny** [comment]
> （3）对腾讯拥有知识产权的内容进行使用、出租、出借、复制、修改、链接、转载、汇编、发表、出版、建立镜像站点等。

2333 使用都不允许。

我觉得看怎么理解，大前提是"除非法律法规允许或腾讯书面许可"，也就是说在法律允许的范围内是可以的。

我觉得根据信息blahblah法，只要不是恶意使用或者法律禁止都可以的。（需考证）

也就是说我们并没有**非法使用**腾讯拥有知识产权的内容，也就是说我们没有违反（3）

**Comment by BruceZhang1993** [comment]
按照个人解读，只要法律法规允许或腾讯书面许可满足其中任意一项即可

**Comment by oldherl** [comment]
> 我觉得根据信息blahblah法，只要不是恶意使用或者法律禁止都可以的。（需考证）

中国法律里面没有规定你可以自由传播软件

**Comment by OriginCode** [comment]
379bfdbb3d
