### ISSUE TITLE
orphaning xorgxrdp

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#2469]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* xorgxrdp

----

#2411 It seems we need to manually remove xrdp too? @lilydjwg

**Comment by lilydjwg** [comment]
No.

**Comment by hubutui** [comment]
@lilydjwg Are you sure? xrdp should be removed in https://github.com/archlinuxcn/repo/issues/2411, but https://github.com/archlinuxcn/repo/commit/7132e2844bc1d66c7b16bc3527dd6339d2a54f97 just set maintainer to empty.

**Comment by lilydjwg** [comment]
It should be deleted by lilac once xorgxrdp is deleted.
