### ISSUE TITLE
关于分发许可问题的处理流程

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#2473]
### 问题类型 / Type of issues

* 其它 / other

----

最近我们仓库有很多包被指出有分发许可的问题，但维护者们疏于回应，因此我打算让 lilac 自动删除14天无新消息的、具有「license」标签的 issue 下的包。

大家有任何意见和建议吗？如果没有的话我就去实现了。

**Comment by Sasasu** [comment]
我建议换成空包，在 `pre_install` 里报错，打出 issue 的链接。

**Comment by lilydjwg** [comment]
这样会影响用户自行安装的同名包的。
