### ISSUE TITLE
没有包的维护者 / maintainers without packages (2021)

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#2484]
### 问题类型 / Type of issues

* 其它 / other

----
The following maintainers in this organization have no packages currently:

* [ ] ~~@bennyyip~~
* [ ] ~~@colinkeenan~~
* [ ] ~~@frealgagu~~
* [x] @justforlxz
* [ ] ~~@poscat0x04~~
* [x] @qwIvan
* [ ] ~~@Rasphino~~
* [ ] ~~@Skywol~~
* [ ] ~~@zsrkmyn~~

For people in the list:

Please show up and correct anything that was wrong, and speak up if you still want to maintain packages in the near future, or you will be removed from this organization. (You can still apply or contribute via pull requests in the future.)

The removal will take place after 30 days.

**Comment by justforlxz** [comment]
I am fixing the PKGBUILD error and will re-upload soon.

**Comment by zsrkmyn** [comment]
`rm zsrkmyn` seems fine to me. I'm tired in struggling for life. I really appreciate the time working with you.

**Comment by SilverRainZ** [comment]
> `rm zsrkmyn` seems fine to me. I'm tired in struggling for life. I really appreciate the time working with you.

Q_Q 阿森汪不要走。

**Comment by qwIvan** [comment]
我有包了

**Comment by lilydjwg** [comment]
Unchecked maintainers have been removed. @phoenixlzx could you check and disable @archlinuxcn.org for them?
