### ISSUE TITLE
软件打包请求: multimc-bin

### ISSUE THREAD

**Issue by kuolemax** [archlinuxcn/repo#2506]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

   Free, open source launcher and instance manager for Minecraft.

* 主要语言和工具链 / Main Languages and Toolchains

    - java-runtime
    - wget
    - libgl
    - qt5-base
    - qt5-svg
    - qt5-x11extras
    - xorg-xrandr
    - zenity
    - zlib

* 上游链接 / Upstream Link

    - 上游: http://multimc.org/
    - AUR: https://aur.archlinux.org/multimc-bin.git

* 为何需要这个软件包 / Why Need This Package

    这个包比`multimc5`更加贴近上游，已有的`multimc5`这个包对上游做了修改，导致其无法使用微软帐号登陆

**Comment by asura99** [comment]
> 你搞错了，是上游在发布的开源 multimc5 的基础上做了（未开源的）修改而成了 multimc5-bin

但是`multimc5`和从github上下载的打包好的包不一样，因为直接从multimc的github上下载的包是可以使用微软登陆且有更新功能的，但是aur和cn中的`multimc5`没有这两项功能，而`multimc-bin`是有的，我不太明白

**Comment by oldherl** [comment]
开源的multimc5相当于chromium，上有发布的二进制里面加了私货相当于chrome

**Comment by asura99** [comment]
> 开源的multimc5相当于chromium，上有发布的二进制里面加了私货相当于chrome

明白了，感谢解答
