### ISSUE TITLE
android-sdk 和 android-sdk-platform-tools冲突

### ISSUE THREAD

**Issue by wongsyrone** [archlinuxcn/repo#251]
android-sdk-25.1.7-2
android-sdk-platform-tools-r24-1

android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/AUTHORS 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/LICENSE 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/README.md 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/__init__.py 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/agents/__init__.py 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/agents/atrace_agent.py 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/agents/atrace_agent_unittest.py 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/agents/ftrace_agent.py 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/agents/ftrace_agent_unittest.py 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/prefix.html 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/suffix.html 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/systrace-legacy.py 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/systrace.py 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/systrace_agent.py 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_data 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_data_raw 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_data_stripped 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_data_thread_fixed 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_data_with_thread_list 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_extracted_tgids 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_extracted_threads 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_fixed_tgids 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_missing_tgids 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_procfs_dump 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_ps_dump 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/test_data/atrace_thread_names 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/update_systrace_trace_viewer.py 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/util.py 
android-sdk-platform-tools: 文件系统中已存在 /opt/android-sdk/platform-tools/systrace/catapult/systrace/systrace/util_unittest.py 
发生错误，没有软件包被更新。

**Comment by farseerfc** [comment]
貌似和 archlinuxcn/android-sdk-platform-tools  r23.1.0-4 是沒衝突的，和 AUR 裏的 r24-1 有衝突？
等 AUR 裏的升級到 r25 吧。

**Comment by wongsyrone** [comment]
我看了一下AUR和这边的PKGBUILD，是一样的啊，都是r24-1
https://github.com/archlinuxcn/repo/blob/master/android-sdk-platform-tools/PKGBUILD#L6
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=android-sdk-platform-tools

**Comment by farseerfc** [comment]
好像肥貓剛推了一個新的 r24-1 ，貌似沒有衝突
android-sdk-platform-tools-r24-1-x86_64.pkg.tar.xz 30-Jun-2016 01:00             2228316

**Comment by farseerfc** [comment]
這邊 repo 裏的 PKGBUILD 不一定和源裏的二進制同步，有的時候忘記推某一邊了……

**Comment by wongsyrone** [comment]
我这边安装的好像就是肥猫打包的版本：

pkgname = android-sdk-platform-tools
pkgver = r24-1
pkgdesc = Platform-Tools for Google Android SDK (adb and fastboot)
url = http://developer.android.com/sdk/index.html
builddate = 1466410095
packager = Felix Yan <felixonmars@archlinux.org>
size = 12817408
arch = x86_64

builddir = /tmp/yaourt-tmp-felix/aur-android-sdk-platform-tools
pkgbuild_sha256sum = 4cf30833020e0e7e3c4b57d0b0ece66df6ce1faeca10af4b5b829383ba92fcc5

**Comment by wongsyrone** [comment]
android-sdk

builddir = /tmp/yaourt-tmp-felix/aur-android-sdk
pkgbuild_sha256sum = 543716fadeb5243d568725ae3059f493ea8ec9a7eb78fedd8f67e81df7816df3

pkgname = android-sdk
pkgver = 25.1.7-2
pkgdesc = Google Android SDK
url = http://developer.android.com/sdk/
builddate = 1465130602
packager = Felix Yan <felixonmars@archlinux.org>
size = 383264768
arch = x86_64

**Comment by farseerfc** [comment]
> builddir = /tmp/yaourt-tmp-felix/aur-android-sdk

這是 AUR 自己打包的？
我這邊
96a1cb9e2738d19b9e3cf448ebd50cd80ff8d8a0e2799bdca72808f809ecdfe6  android-sdk-25.1.7-2-x86_64.pkg.tar.xz

**Comment by wongsyrone** [comment]
sha256sum android-sdk-25.1.7-2-x86_64.pkg.tar.xz                                                                                                       
96a1cb9e2738d19b9e3cf448ebd50cd80ff8d8a0e2799bdca72808f809ecdfe6  android-sdk-25.1.7-2-x86_64.pkg.tar.xz
sha256sum android-sdk-platform-tools-r24-1-x86_64.pkg.tar.xz                                                                                           
08d542a8a1fa7dd0f02ece7446897c73c41a0cb8079022c85d3fca8f8bc93cf3  android-sdk-platform-tools-r24-1-x86_64.pkg.tar.xz

**Comment by farseerfc** [comment]
sha 看起來是一樣的，奇怪了……
你去那些衝突的地方找個衝突的文件看一下 pacman -Qo 是不是真的屬於 android-sdk ？
會不會是用 android-sdk 提供的工具手動裝的 platform-tools 。

**Comment by wongsyrone** [comment]
的确是手动装的锅
