### ISSUE TITLE
rstudio-desktop-git 过期

### ISSUE THREAD

**Issue by CyrusYip** [archlinuxcn/repo#2510]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* rstudio-desktop-git（请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----

似乎 lilac 一直在以这个 commit [0420c874af](https://github.com/rstudio/rstudio/commit/0420c874af) 来编译，pkgrel 都到 216 了。

**Comment by lilydjwg** [comment]
BLM 太坑 lilac 啦……
我就知道这事儿会在各种地方 break，所以才一直对换主分支为 main 无动于衷的。然而很多上游换主分支的时候是不是根本没想过会 break 掉多少东西，连个通知都不发的。

**Comment by lilydjwg** [comment]
我把缓存的仓库删掉了， lilac 下次应当能取到新提交。
这已经不是第一次 lilac 被 BLM 坑到了 QAQ
