### ISSUE TITLE
visual-studio-code-bin 已过期

### ISSUE THREAD

**Issue by g-plane** [archlinuxcn/repo#2511]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* visual-studio-code-bin（请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----

目前最新版为 1.61.2；而最后一次打包的版本是 1.60.2，时间是 2021/9/23。

**Comment by sophgn** [comment]
visual-studio-code-bin is orphaned in #2460.

**Comment by AImixAE** [comment]
补药啊～

**Comment by oldherl** [comment]
> 补药啊～

补什么？这包license不允许重分发，没得补
