### ISSUE TITLE
软件打包请求：python2-gobject2（pygtk的依赖）

### ISSUE THREAD

**Issue by Dringsim** [archlinuxcn/repo#2514]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    Legacy Python 2 bindings for GObject

* 主要语言和工具链 / Main Languages and Toolchains

    Python

* 上游链接 / Upstream Link

    * 上游：https://wiki.gnome.org/Projects/PyGObject
    * AUR：https://aur.archlinux.org/packages/python2-gobject2/

* 为何需要这个软件包 / Why Need This Package

    archlinuxcn仓库中的包pygtk依赖python2-gobject2（官方仓库未收录）

**Comment by SilverRainZ** [comment]
Please reopen issue if you still suffer it.
