### ISSUE TITLE
打包请求：anki

### ISSUE THREAD

**Issue by CyrusYip** [archlinuxcn/repo#2515]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    基于间隔重复的记忆软件。

* 主要语言和工具链 / Main Languages and Toolchains

    Python、Rust

* 上游链接 / Upstream Link

    - 上游：<https://github.com/ankitects/anki>
    - AUR：<https://aur.archlinux.org/packages/anki-release-source/>
    - 还有其他 [AUR 包](https://aur.archlinux.org/packages/?O=0&K=anki)，但这个更新比较快

* 为何需要这个软件包 / Why Need This Package

   - Anki 十分适合机械记忆，比如学语言和准备考试。把需要背的内容丢进去，它会帮你安排学习与复习间隔，每天打开学就可以了。比自己安排记忆间隔轻松多了。
   - 相关帖子：
       - [Anki - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/Anki)
       - [怎样用anki背考研专业课？ - 知乎](https://www.zhihu.com/question/64980120)
       - [Anki 怎么用？ - 知乎](https://www.zhihu.com/question/28335314/answer/428970652)

**Comment by SilverRainZ** [comment]
看了几个 aur 包：
- anki：打包不规范，而且应该编译不过了
- anik-git：看起来也编译不过
- anki-release-source：感觉是因为前两个包不争气搞的，不喜欢这个名字。

所以决定根据 anki-release-source 改一个 anki-git 放在 cn 源里维护，改了差不多一半，package 还有点问题。

另外需要加几个依赖，mark 一下：

-  [ ] python-mypy-protobuf
-  [ ] python-stringcase

**Comment by SilverRainZ** [comment]
https://github.com/archlinuxcn/repo/commit/abfcc137bfe83ea642bb910f4c60d92dc5da2177

**Comment by CyrusYip** [comment]
@SilverRainZ 谢谢你！
