### ISSUE TITLE
telegram-desktop is out of date

### ISSUE THREAD

**Issue by KenOokamiHoro** [archlinuxcn/repo#252]
https://aur.archlinux.org/packages/telegram-desktop

The latest version of telegram-desktop is 0.9.56 and updated at 2016-06-27 14:27 on AUR .

😂😂

**Comment by cuihaoleo** [comment]
lilac failed to build telegram-desktop the other day. Maybe due to invalid signature of some dependencies built by lilac.

Just now I tried to built it customly and succeeded. I've bump the pkgrel to ask lilac to rebuild it.
