### ISSUE TITLE
Increase build task frequency

### ISSUE THREAD

**Issue by phoenixlzx** [archlinuxcn/repo#253]
We may increase lilac build task to 4 times per day as the build machine is mostly idle.

**Comment by lilydjwg** [comment]
I've decided that three times a day is enough (too many error mails sent to repo@). Maybe we can add a button / link for the inpatient to click.

**Comment by petronny** [comment]
所以现在具体是几点会跑呢？

**Comment by lilydjwg** [comment]
1, 9, 17 点。

**Comment by petronny** [comment]
👌🏻
