### ISSUE TITLE
ds9 打包错误，建议改为使用二进制软件

### ISSUE THREAD

**Issue by Firestar-Reimu** [archlinuxcn/repo#2531]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

*  ds9

ds9用archlinuxcn的显示是这样的：（改不了丑陋的点阵字体，中文显示为方块，在高分辨率屏幕下显示很小）

![Screenshot_20211107_221119](https://user-images.githubusercontent.com/65082432/140649184-498adfe7-8696-44d2-824c-5aca75cd7cd1.png)

用[官网](https://ds9.si.edu/download/ubuntu20/ds9.ubuntu20.8.3rc.tar.gz)上的预编译版本（二进制bin）是这样的：（字体显示正确，支持中文，在高分辨率屏幕下字体大小正常）

![Uploading Screenshot_20211107_221221.png…]()

**Comment by Firestar-Reimu** [comment]
```
# Maintainer:  <Firestar-Reimu>

pkgname=ds9-bin
_pkgname=ds9
pkgver=8.3rc
pkgrel=1
pkgdesc="SAOImage DS9: Astronomical Data Visualization Application"
url="http://hea-www.harvard.edu/RD/ds9/"
arch=('x86_64')
license=('GPL2')
options=(!strip)
provides=(${_pkgname})
depends=()
makedepends=()
conflicts=()
replaces=()
backup=()
source=(https://ds9.si.edu/download/ubuntu20/${_pkgname}.ubuntu20.${pkgver}.tar.gz
        ds9.desktop
        ds9.png)
md5sums=('SKIP'
         'f1738e4ec665ae9afd1b65b86e6a07f1'
         '9297d5738f5f462831075c483dc785d5')

package() {
  cd ${srcdir}

  install -Dm755 ds9 ${pkgdir}/usr/bin/${_pkgname}
  install -Dm644 ${_pkgname}.desktop ${pkgdir}/usr/share/applications/${_pkgname}.desktop
  install -Dm644 ${_pkgname}.png ${pkgdir}/usr/share/pixmaps/${_pkgname}.png
}
```

**Comment by lilydjwg** [comment]
你给出的 ubuntu 包是 rc 版本。
你的第二张截图还没上传好你就提交了。

**Comment by oldherl** [comment]
ds9 是我在维护啊，并没有缺少维护者。
我不打算采用 bin 包，如果你想要 ds9-bin 那你可以另外申请一个新包（使用新申请打包的 issue 模板）。
另外我也不打算打包 rc 版本。

**Comment by oldherl** [comment]
这是现在 archlinuxcn 中的 ds9-8.3-1 在我这里的效果截图，看起来并不比你那个 ubuntu 的二进制差。那个设置框的左侧也都是一样有问题的，应该需要在上游代码里处理。
![image](https://user-images.githubusercontent.com/172495/141161285-f70028f7-a3be-4cb1-884c-d45292e4c58b.png)
