### ISSUE TITLE
asciinema is out of date

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#254]
asciinema 1.3 is out and has [switched back to Python](http://blog.asciinema.org/post/and-now-for-something-completely-different/)!

**Comment by farseerfc** [comment]
奇怪， lilac 爲什麼不編譯也不報錯呢……先同步一下 AUR 上的 PKGBUILD 看看

**Comment by lilydjwg** [comment]
呃，看起来是因为 AUR 当时还没更新……

**Comment by farseerfc** [comment]
這次 lilac 報錯了……好像 AUR 上的漏寫依賴了，先跟 AUR 的 maintainer 反應下看看
