### ISSUE TITLE
shadowsocks-rust-opt-git use unsafe user

### ISSUE THREAD

**Issue by CoelacanthusHex** [archlinuxcn/repo#2542]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

shadowsocks-rust-opt-git

----

请在此补充说明。
Please describe in detail here.

This package use nobody user for service, it's not safe.
ss-rust will print a warning:
```
systemd[1]: [🡕] /usr/lib/systemd/system/shadowsocks-rust@.service:7: Special user nobody configured, this is not safe!
```
**nobody is user of NFS service, not general service user.**

**Comment by DuckSoft** [comment]
@CoelacanthusHex Thanks for pointing that out. I'd like to review a Pull Request on this issue.

**Comment by SilverRainZ** [comment]
@DuckSoft
