### ISSUE TITLE
[emacs-git] 能否打开emacs-git的XWIDGETS选项？

### ISSUE THREAD

**Issue by yqu212** [archlinuxcn/repo#2550]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    现在Emacs的xwidgets特性的闪烁问题已经解决，功能也在增强，这个特性已经可用。能否在emacs-git里面打开XWIDGETS选项，以便更多Emacs用户尽快用上这个新特性？

相关讨论可以查看[沉寂 2 年多的 xwidget 迎来了 Po Lu 大神的大量更新](https://emacs-china.org/t/2-xwidget-po-lu/18956) 。

谢谢

* 主要语言和工具链 / Main Languages and Toolchains

    

* 上游链接 / Upstream Link

    

* 为何需要这个软件包 / Why Need This Package

**Comment by SilverRainZ** [comment]
看起来已经启用了。

**Comment by yqu212** [comment]
谢谢 @ykelvis @SilverRainZ
