### ISSUE TITLE
Typora正式版 许可变动

### ISSUE THREAD

**Issue by nwntech** [archlinuxcn/repo#2557]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
typora
----

请在些补充说明。
Please describe in detail here.

众所周知，typora更新1.0正式版后采用了新的收费授权模式，没有收费的旧版本依旧保持免费的模式。
请求对最后一版免费typora单独打包，与收费的正式版typora分开

**Comment by cuihaoleo** [comment]
旧版本“保持免费”来源请求？看起来许可丝毫没有发生变化（1.0.2 vs 0.11.18）：

```
$ diff pkg/typora/usr/share/typora/LICENSE /usr/share/typora/LICENSE
$ diff pkg/typora/usr/share/typora/LICENSES.chromium.html  /usr/share/typora/LICENSES.chromium.html
$ cat /usr/share/typora/LICENSE
Copyright (c) 2015~2019 Abner Lee

All Rights Reserved.

-----

Typora is powered by Electron (MIT License, Github Inc) and several open source project

See `Help` -> `Credits` for full license text
```

---

通常来讲，既然 All Rights Reserved，分发权也没有，删包就行了。

**Comment by yan12125** [comment]
Note that packages with the "license" label will be removed after 14 days if no further actions are taken.

**Comment by nwntech** [comment]
> 旧版本“保持免费”来源请求？看起来许可丝毫没有发生变化（1.0.2 vs 0.11.18）：
> 
> ```
> $ diff pkg/typora/usr/share/typora/LICENSE /usr/share/typora/LICENSE
> $ diff pkg/typora/usr/share/typora/LICENSES.chromium.html  /usr/share/typora/LICENSES.chromium.html
> $ cat /usr/share/typora/LICENSE
> Copyright (c) 2015~2019 Abner Lee
> 
> All Rights Reserved.
> 
> -----
> 
> Typora is powered by Electron (MIT License, Github Inc) and several open source project
> 
> See `Help` -> `Credits` for full license text
> ```
> 
> 通常来讲，既然 All Rights Reserved，分发权也没有，删包就行了。

https://support.typora.io/purchase/#can-i-use-typora-for-free-

**Comment by cuihaoleo** [comment]
读了一下，并没有哪里说旧版保持免费。

If you use dev version or Linux version, you will have unlimited trial time
if you keep Typora updated.

原文是说新版 / dev 版可以无限期试用，并且条件是“保持 Typora 更新”。

官方给出的“免费”的路子，显然是继续使用最新版嘛。

**Comment by hubutui** [comment]
建议丢包，表示已卸载。以后用 vs code 吧。

**Comment by yan12125** [comment]
補充說明一下：「能否免費使用」與「能否在archlinuxcn打包」是兩個不同的問題。後者另外需要分發的授權 - 通常會在使用者條款中以distribute或redistribute註明。
