### ISSUE TITLE
软件打包请求: wezterm-git

### ISSUE THREAD

**Issue by peeweep** [archlinuxcn/repo#2558]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    A terminal emulator implemented in Rust, using OpenGL ES 2 for rendering.

* 主要语言和工具链 / Main Languages and Toolchains

    Rust

* 上游链接 / Upstream Link

    Upstream: https://github.com/wez/wezterm
    AUR: https://aur.archlinux.org/packages/wezterm-git

* 为何需要这个软件包 / Why Need This Package

    Build based on daily commits.

**Comment by ykelvis** [comment]
bfd7350e5ca8cb9f2a9e4797668c1bb7625af0cc

**Comment by peeweep** [comment]
谢谢~
