### ISSUE TITLE
Huge package request that might benefit Arch Linux users (MATE 1.15 - GTK3)

### ISSUE THREAD

**Issue by BigEars431** [archlinuxcn/repo#256]
Hi, To start, I would like to thank you guys for the awesome maintainance of your repo, I heavily rely on your repo when it comes to some of the daily apps I use.

I am using the MATE Desktop under Arch Linux, however Mate is now unmaintained under archlinux, it's stuck on version 1.12. The mate-meta-1.15-gtk3 package (Latest version) is available in the AUR, and I've built on my fast machine, my main problem is that I wont be able to build this lightweight desktop environment on my slower machine(s).

I know this wont be easy, or practical for you guys, but if you guys include MATE 1.15 - GTK3 to your repo it will be insanely beneficial to all Arch Linux users around the world. =))

**Comment by farseerfc** [comment]
The official repo lacks MATE maintainer currently. They are waiting for someone to show up to take over MATE packages.
Maybe applying a TU will benefit more Arch Linux users?

**Comment by petronny** [comment]
Hi,
I have found that now mate 1.14 series is in [community]. So is this still a problem?

**Comment by BigEars431** [comment]
not a problem anymore, looks the MATE Desktop on Arch Linux has a maintainer now =)
