### ISSUE TITLE
archlinuxcn/qv2ray-dev-git 2.7.0.7000.r3037.a35ce6fb-4  打不开（2021/11/30）

### ISSUE THREAD

**Issue by chenyuxi2002** [archlinuxcn/repo#2560]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

*  qv2ray-dev-git

----

[2021-11-30T09:47:04+0800] [ALPM] upgraded qv2ray-dev-git (2.7.0.7000.r3037.a35ce6fb-3 -> 2.7.0.7000.r3037.a35ce6fb-4)

升级后无法启动。

不知道是不是我自己的问题，大家注意。

**Comment by SilverRainZ** [comment]
尝试命令行启动，贴一下输出。

**Comment by SilverRainZ** [comment]
未能复现 + 未收到反馈，close 了。

如果还有问题请 reopen。

**Comment by K-gihu** [comment]
使用 qv2ray-dev-git 2.7.0.7000.r3037.a35ce6fb-5 出现相同问题，是 grpc 版本问题所致，最新的 grpc版本是 1.43.0，而 qv2ray 需要 1.42.0，降级之后可以正常打开。

**Comment by SilverRainZ** [comment]
> 使用 qv2ray-dev-git 2.7.0.7000.r3037.a35ce6fb-5 出现相同问题，是 grpc 版本问题所致，最新的 grpc版本是 1.43.0，而 qv2ray 需要 1.42.0，降级之后可以正常打开。

官方源 grpc 先更新了，cn 源没来得及打包同步：https://github.com/archlinuxcn/repo/commit/3e012596a29d417bdab8495700a23ab69c274df2

等一两个小时应该就好。
