### ISSUE TITLE
deadbeef 和 deadbeef-git 缺少 opus 支持

### ISSUE THREAD

**Issue by q234rty** [archlinuxcn/repo#2569]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* deadbeef
* deadbeef-git

----

这两个包需要 opusfile 提供的 libopusfile.so 来打开 opus 支持，否则即使运行时能找到这一依赖也无法播放 opus 文件。
构建时存在这一依赖但运行时不存在的情况下，这两个包仍能正常工作，但不能打开 opus 文件。
因此我建议把 opusfile 加入这两个包的 makedepends 和 deadbeef 的 optdepends （deadbeef-git 已有这一 optdepends 故无需再加入）。

**Comment by heavysink** [comment]
ffb1349
