### ISSUE TITLE
Rebuild python-astropy and ptpython

### ISSUE THREAD

**Issue by MrAru** [archlinuxcn/repo#2577]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* python-astropy
* ptpython

----
These two packages should rebuild with Python 3.10 to drop out its own files in `/usr/lib/python3.9`.

**Comment by yuyichao** [comment]
python-astropy should be automatically rebuilt, ptpython is missing python update trigger though.

**Comment by lilydjwg** [comment]
python-astropy is on the building list and is expected to be rebuilt over the coming night. There are a lot of packages being rebuilt so it takes time.

**Comment by MrAru** [comment]
Rebuilding finished and everything goes well now. Issue closed.
