### ISSUE TITLE
建议将`python-cupy`包中部分依赖变更为可选依赖

### ISSUE THREAD

**Issue by 8ar10der** [archlinuxcn/repo#2583]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* archlinuxcn/python-cupy
* community/cudnn
* community/nccl 

----

根据[cupy官网doc](https://docs.cupy.dev/en/stable/install.html)，cudnn与nccl应该为可选依赖。

**Comment by hubutui** [comment]
cudnn 和 nccl 也没多大啊，cuda 都装了，cudnn 能不装？

**Comment by 8ar10der** [comment]
> cudnn 和 nccl 也没多大啊，cuda 都装了，cudnn 能不装？

我个人项目只需要基础的cupy，不需要cudnn，nccl，不想为此浪费空间。

**Comment by SilverRainZ** [comment]
个人觉得在没有特别麻烦的情况下，还是尽量按按上游的要求打包吧。

**Comment by hubutui** [comment]
我觉得可以测试一下把这几个 CUDA 依赖设置为可选，在运行的时候没有的话是否可以正确使用。
