### ISSUE TITLE
Dropping atom-editor{-bin} in favor of community/atom

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#260]
atom-editor and atom-editor-bin will be dropped in two weeks from the repo in favor of the newly added community/atom.

**Comment by xgdgsc** [comment]
I' m considering adding atom-editor-bin back. Because using the latest version of electron isn' t recommended by atom developers and you would always expect bugs from using it. What do you think?

**Comment by farseerfc** [comment]
Is there any known bugs related to Arch Linux using latest electron?
I think in general we should trust decisions of archlinux packagers and report bugs to http://bugs.archlinux.org/ if we have seen packaging issues. By doing this we can benefit all archlinux users, not just our users.
Only when we observed the dereliction of the packager we should do things differently.

**Comment by xgdgsc** [comment]
https://bugs.archlinux.org/task/50357 This bug might be endless.

**Comment by farseerfc** [comment]
Most issues in that bug report seem to be fixed, and the packager (tensor5) seems to be responsible and fully aware what he is doing.
I am ok with providing atom-editor/atom-editor-bin in this repo, though. (As long as the fcitx issue is fixed and the building is stable)
