### ISSUE TITLE
emacs-git 截至 2021-12-28 已 8 天未重新 rebuild

### ISSUE THREAD

**Issue by condy0919** [archlinuxcn/repo#2607]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* emacs-git

----

目前 https://repo.archlinuxcn.org/x86_64/ 目录下的软件包，还是有一些包的日期比 2021-12-20 新。而且所使用的上游 https://github.com/emacs-mirror/emacs 在过去8天里也都有更新。

**Comment by lilydjwg** [comment]
这个包最近一直在失败： https://build.archlinuxcn.org/packages/#/emacs-git

**Comment by condy0919** [comment]
我在本地测试了一下，发现如果同时指定了 `PGTK="YES"` 和 `XWIDGETS="YES"` 的话就会编译失败，这也在 Emacs Telegram 频道里得到了近期提交大量 xwidget patch 的 t.me/oldosfan 的确认。

所以可能得取舍一下，是想使用 PGTK 还是开启 XWIDGETS？

注: `PGTK="YES"` 在这里已被默认打开
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=emacs-git#n49

**Comment by condy0919** [comment]
cc https://github.com/archlinuxcn/repo/issues/2550 @yqu212

**Comment by yqu212** [comment]
我倾向于不打开pgtk。如果默认打开pgtk，不用Wayland的用户会遇到大麻烦。

**Comment by condy0919** [comment]
![image](https://user-images.githubusercontent.com/4024656/147618889-163bb976-8bee-4220-8f98-3e8ba46ca823.png)

Po Lu 现在搞 xwidgets 在 PGTK 下的实现，到时候就可以不用改 flags 了

**Comment by VitalyAnkh** [comment]
已经完成了，好耶

**Comment by VitalyAnkh** [comment]
拉取[最新的提交](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=8be5b08bb576fbf20feae6417b4069de2cf69781)再build就不会失败了

**Comment by condy0919** [comment]
好，就等待下一次 rebuild 了！

**Comment by condy0919** [comment]
已经成功 rebuild 了！
