### ISSUE TITLE
License problem of ttf-consolas-with-yahei-powerline-git

### ISSUE THREAD

**Issue by oldherl** [archlinuxcn/repo#2609]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* ttf-consolas-with-yahei-powerline-git

----

This package is made by mixing Consolas and Yahei fonts. Both are proprietary fonts by Microsoft so that the result is not distributable. Please remove it.

To maintainers: when you write `license="custom"`or `unknown` in PKGBUILD, please check the license manually to confirm whether it is redistributable.

**Comment by heavysink** [comment]
c3264f0
