### ISSUE TITLE
[emacs-git] 能否不再跟随上游打包？

### ISSUE THREAD

**Issue by yqu212** [archlinuxcn/repo#2613]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

*  emacs-git

----

请在此补充说明。
Please describe in detail here.

近期[上游添加了对pgtk的支持](https://aur.archlinux.org/cgit/aur.git/commit/?h=emacs-git&id=c2216b91960d0dfb822f5fe41ac764e1e63544d2) ，不知出于什么原因默认打开了pgtk特性。这其实也是[issue 2607](https://github.com/archlinuxcn/repo/issues/2607)出现的根本原因。这给不使用Wayland的用户带来了困扰。能否考虑关闭这一特性？可以只在emacs-native-comp-git包中打开它。谢谢

**Comment by CoelacanthusHex** [comment]
其实如果没有 pgtk，部分 X11 Emacs 用户是没办法正常使用输入法的

**Comment by yqu212** [comment]
谢谢反馈。这方面我了解不够。刚才想到似乎wslg用户也需要pgtk才能正常高清显示。

我会等等看有没有其他用户反映其他方面的问题。如果大多数用户都需要pgtk，那我会关闭这个issue。

**Comment by lyjdwh** [comment]
开了pgtk后，dwm没法正常使用 eaf了 -_-

**Comment by CoelacanthusHex** [comment]
> 开了pgtk后，dwm没法正常使用 eaf了 -_-

那你不该在这里说，你该去给 eaf 报bug

**Comment by lyjdwh** [comment]
只是反馈下嘛，我也不是很懂

> 部分 X11 Emacs 用户是没办法正常使用输入法的

那这个是不是输入法的问题呢。

据Po Lu 讲，没有用 wayland 就没必要开启 pgtk，X11 上使用 X 版本用户体验会好很多。

**Comment by CoelacanthusHex** [comment]
> 那这个是不是输入法的问题呢。

可以确定是 Emacs 的bug和xim的限制共同作用的结果，具体情况可以去看 fcitx 作者的博客 csslayer.info

**Comment by CoelacanthusHex** [comment]
简单来说这个问题如果 Emacs 上游不修，就只能使用 PGTK 编译的 Emacs，通过 GTK 的输入法模块来避免

**Comment by yuyichao** [comment]
Emacs 用xim的问题应该已经修好了。

**Comment by yqu212** [comment]
Po Lu已经证实，这个问题已经解决。

请看他的回复。https://emacs-china.org/t/emacs-linux-windows-mac/6199/2181?u=yqu212

**Comment by manateelazycat** [comment]
第一、X11版本非常早就可以使用 xim 和 fcitx 了
第二、pgtk默认打开，对于非Wayland用户非常不友好，用户要在Emacs29和X11特性之间做选择
第三、我觉得Arch应该遵守上游社区的默认设置，Emacs默认没有开 pgtk 是Emacs开发者深思熟虑的考量，发行版开发者不应该按照自己的理解去修改默认编译参数

**Comment by oldherl** [comment]
提醒，这里不是 arch，这里是 archlinuxcn，一个第三方仓库。很多 emacs 用户是因为 emacs 迟迟不发正式版才使用 emacs-git 的，建议去催促上游尽快发版。

**Comment by yqu212** [comment]
昨天上游又打开了jit。archlinuxcn里面已经有了emacs-git和emacs-native-comp-git两个包，后者最初正是为了jit特性而设。随着上游打开jit，实质上这两个包已经没有差异。

https://aur.archlinux.org/cgit/aur.git/commit/?h=emacs-git&id=6e9083d579b5f010eb00158629184a9f8a926848

考虑到大家的多种需求，能否不再跟随上游，仍然维持两个包，emacs-git只打开默认特性，emacs-native-comp-git则可以打开pgtk,jit等新的实验特性，至于没有争议的xwidget特性，则两个包都打开。诸位，这样是否可行？

**Comment by yuyichao** [comment]
> 第一、X11版本非常早就可以使用 xim 和 fcitx 了

但是在 csslayer 提到的那个问题修掉之前有很多情况是用不了的. 而且即使现在修了以后依然比pgtk的版本差很多.

> 第二、pgtk默认打开，对于非Wayland用户非常不友好，用户要在Emacs29和X11特性之间做选择

这个我没用过特别的x11特性所以不做评论, 但是,

> 第三、我觉得Arch应该遵守上游社区的默认设置，Emacs默认没有开 pgtk 是Emacs开发者深思熟虑的考量，发行版开发者不应该按照自己的理解去修改默认编译参数

从输入法的角度来讲, 基本上可以确定 emacs 上游对输入法完全不在意. 上面提到的 XIM 问题报上去十几年都没有修就是根据. 因此虽然 emacs 上游因为他自己的考虑设置了一些选项的默认值, 这些默认值完全是可以/应该按照发行版维护着的理解去修改的. 即使是一般的来讲, 不限于 emacs, 不限于输入法的考虑, 要修改默认选项的包也多了去了....

> emacs-native-comp-git则可以打开pgtk,jit等新的实验特性

至少改个名字吧 = = .... 如果不仅限于名字里面提到的一个特性的话...

**Comment by manateelazycat** [comment]
> > 第一、X11版本非常早就可以使用 xim 和 fcitx 了
> 
> 但是在 csslayer 提到的那个问题修掉之前有很多情况是用不了的. 而且即使现在修了以后依然比pgtk的版本差很多.
> 
> > 第二、pgtk默认打开，对于非Wayland用户非常不友好，用户要在Emacs29和X11特性之间做选择
> 
> 这个我没用过特别的x11特性所以不做评论, 但是,
> 
> > 第三、我觉得Arch应该遵守上游社区的默认设置，Emacs默认没有开 pgtk 是Emacs开发者深思熟虑的考量，发行版开发者不应该按照自己的理解去修改默认编译参数
> 
> 从输入法的角度来讲, 基本上可以确定 emacs 上游对输入法完全不在意. 上面提到的 XIM 问题报上去十几年都没有修就是根据. 因此虽然 emacs 上游因为他自己的考虑设置了一些选项的默认值, 这些默认值完全是可以/应该按照发行版维护着的理解去修改的. 即使是一般的来讲, 不限于 emacs, 不限于输入法的考虑, 要修改默认选项的包也多了去了....
> 
> > emacs-native-comp-git则可以打开pgtk,jit等新的实验特性
> 
> 至少改个名字吧 = = .... 如果不仅限于名字里面提到的一个特性的话...

你们知道真正的Emacser其实用的是 emacs-rime 这种插件来实现输入法的吗？emacs-rime 是 rime 在Emacs的前端，后端可以用 fcitx 的任意后端, emacs-rime 可以保留任意Buffer的Local Status, 详细的可以看我的博客关于 emacs-rime 的论述：https://manateelazycat.github.io/emacs/2020/03/22/emacs-rime.html

为啥Emacser自己不在意的事情，archlinuxcn的开发者要根据自己的感觉来认为Emacser真的需要啥呢？

现在默认打开 pgtk 的选项，对于真正在用X11桌面环境的Emacser非常不友好，默认这样打包导致用户要不选择X11要不选择Emacs29, 但是Emacs29的性能确实要比 Emacs 27 (Arch 默认的 emacs 包）提升太多了。

**Comment by manateelazycat** [comment]
> 提醒，这里不是 arch，这里是 archlinuxcn，一个第三方仓库。很多 emacs 用户是因为 emacs 迟迟不发正式版才使用 emacs-git 的，建议去催促上游尽快发版。

这个不是git不git的问题，而是请按照上游的默认选项编译Emacs, 默认打开 pgtk 导致X11桌面环境的用户问题很多。

**Comment by yqu212** [comment]
@yuyichao 请移步看一下emacs开发者 Po Lu的评论。谢谢。

https://emacs-china.org/t/emacs-linux-windows-mac/6199/2188

**Comment by ykelvis** [comment]
囧，emacs-git连jit都开了啊那真没啥差别了。既然开新特性争议大的话，emacs-git以后除非有人提（比如xwidgets），默认不打开任何新特性这样？以后用emacs-native-comp-git来follow aur上的emacs-git，可能改个名叫emacs-experimental-git啥的吧。

**Comment by manateelazycat** [comment]
> 囧，emacs-git连jit都开了啊那真没啥差别了。既然开新特性争议大的话，emacs-git以后除非有人提（比如xwidgets），默认不打开任何新特性这样？以后用emacs-native-comp-git来follow aur上的emacs-git，可能改个名叫emacs-experimental-git啥的吧。

是呀，最少要有一个包是和Emacs上游一模一样的呀。如果开新特性，重新改个其他名字的包就可以了，要不大家都认为 emacs-git 就是原版的Git, 安装以后发现和上游选项不一样，都傻傻分不清到底是上游还是archlinuxcn的锅啊。

**Comment by yuyichao** [comment]
> 你们知道真正的Emacser其实用的是 emacs-rime 这种插件来实现输入法的吗

我知道我用emacs但是不用emacs-rime, 而且我知道现在还是时不时地收到emacs输入法相关的问题报告。
。。。而且这种真正的xxx都用yyy之类的说法基本上都完全没有什么意义。。。

> 请移步看一下emacs开发者 Po Lu的评论。谢谢。

我说了是基于之前的问题下的这个结论。如果真的在意的话就不会在我修之前十几年都没人处理了。。。。 
 而且xim本身就有很大的限制，比如说卡死，比如说没有预编辑+光标跟随。而且现在也还有一个用户遇到xim输入的问题用pgtk就没有问题https://github.com/fcitx/fcitx5/issues/419

**Comment by manateelazycat** [comment]
> > 你们知道真正的Emacser其实用的是 emacs-rime 这种插件来实现输入法的吗
> 
> 我知道我用emacs但是不用emacs-rime, 而且我知道现在还是时不时地收到emacs输入法相关的问题报告。 。。。而且这种真正的xxx都用yyy之类的说法基本上都完全没有什么意义。。。
> 
> > 请移步看一下emacs开发者 Po Lu的评论。谢谢。
> 
> 我说了是基于之前的问题下的这个结论。如果真的在意的话就不会在我修之前十几年都没人处理了。。。。 而且xim本身就有很大的限制，比如说卡死，比如说没有预编辑+光标跟随。而且现在也还有一个用户遇到xim输入的问题用pgtk就没有问题[fcitx/fcitx5#419](https://github.com/fcitx/fcitx5/issues/419)

能不能 emacs 这个包就是正式版， emacs-git 就是 Emacs git版，如果你做了啥增强就叫 emacs-git-pgtk ? 最起码名字不要让 arch 用户产生歧义吧？

大家看到 emacs-git 这个名字认为就是原滋原味的Emacs git版本，至于大家喜欢 pgtk 还是喜欢 X11， 这个萝卜白菜，但是名字上不要让大家误解吧？

**Comment by manateelazycat** [comment]
> > 你们知道真正的Emacser其实用的是 emacs-rime 这种插件来实现输入法的吗
> 
> 我知道我用emacs但是不用emacs-rime, 而且我知道现在还是时不时地收到emacs输入法相关的问题报告。 。。。而且这种真正的xxx都用yyy之类的说法基本上都完全没有什么意义。。。
> 
> > 请移步看一下emacs开发者 Po Lu的评论。谢谢。
> 
> 我说了是基于之前的问题下的这个结论。如果真的在意的话就不会在我修之前十几年都没人处理了。。。。 而且xim本身就有很大的限制，比如说卡死，比如说没有预编辑+光标跟随。而且现在也还有一个用户遇到xim输入的问题用pgtk就没有问题[fcitx/fcitx5#419](https://github.com/fcitx/fcitx5/issues/419)

emacs-rime 你说的输入法卡死、预编辑和光标跟随都没问题，一劳永逸的解决问题，下次再有人给 fcitx 报bug, 你就说 emacs-rime 就是最好的 fcitx 在Emacs里面的前端。

**Comment by yuyichao** [comment]
> emacs-rime 你说的输入法卡死、预编辑和光标跟随都没问题，一劳永逸的解决问题，下次再有人给 fcitx 报bug, 你就说 emacs-rime 就是最好的 fcitx 在Emacs里面的前端

但是界面跟桌面不符。选词界面看上去也会受emacs窗口本身的限制。可以说是绕开emacs自己的问题的较好的方法。

**Comment by yqu212** [comment]
@ykelvis 已经在commit [064952bd](https://github.com/archlinuxcn/repo/commit/064952bdab85f697f97f110113eeca5ac40151ac) 里面关闭了近期上游打开的实验特性（除xwidget外），这个issue中涉及的问题已经解决。感谢各位。我先关闭这个issue，如果还有后续问题再打开。pgtk和jit用户请使用emacs-native-comp-git包。

**Comment by manateelazycat** [comment]
@ykelvis 感谢补丁，现在 emacs-git 默认是 X11， 也没有默认开启JIT, 解决了X11桌面环境兼容性和启动不卡Emacs的问题（开了JIT会导致Emacs启动编译 el 成 eln, 十几分钟没法用Emacs），现在 emacs29 已经非常好用了，感谢。
