### ISSUE TITLE
wine-wechat-setup描述是中文版的却中文乱码？

### ISSUE THREAD

**Issue by ding-f** [archlinuxcn/repo#2614]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
wine-wechat-setup
wine-for-wechat
----

请在此补充说明。
Please describe in detail here.

wine-wechat-setup不是Chinese版本吗,只要是中文就是正方形
Wechat全不显示图标
可能是我的系统是英文版原因
但希望可以更好，毕竟是中国的软件，总不能聊天全用英文吧

**Comment by oldherl** [comment]
wechat 微信 是腾讯公司的专有软件，开源社区无法提供支持。您要是让腾讯把它开源了，保证会有人帮您做一个 linux 原生的第三方客户端。

另外，archlinuxcn 从来没有宣传过本软件源适合一点英语都不懂的用户。

**Comment by lilydjwg** [comment]
你使用的是 1.2 版本吗？（1.2 版本在安装步骤时会按照你系统上有的字体来设置字体替换）你启用了简体中文的 locale 吗？（使用命令 `locale -a` 检查有没有 `zh_CN.utf8` 项。）

我不知道「不懂英文」和乱码有什么关系。难道你如果懂英文就能看懂乱码了吗？

最好将乱码截个图，因为乱码有很多种。

我们无法分发安装、配置好的软件包，因为微信的文件版权属于腾讯公司、微软的文件版权属于微软公司。它们都没有允许我们再分发他们的这些文件。当然我们也不能分发微软雅黑或者 simsun 字体。

**Comment by ding-f** [comment]
Immortal-Arch ॐ  ~:
186 ◯  locale -a
C
en_US.utf8
POSIX
zh_CN
zh_CN.gb2312
zh_CN.gbk
zh_CN.utf8

都有的，之前都开了的

**Comment by ding-f** [comment]
![Screenshot_20220104_224630](https://user-images.githubusercontent.com/49016478/148076702-79e72e25-49da-4e5a-a0b6-9e89a8e1b581.png)
Immortal-Arch ॐ  ~:
194 ◯  yay -Qi wine-wechat-setup
名字           : wine-wechat-setup
版本           : 1.1-2
描述           : Setup and run WeChat Windows version with Wine (Chinese version)
架构           : any
URL            : https://weixin.qq.com/
软件许可       : GPL3
组             : 无
提供           : wine-wechat
依赖于         : libarchive  zstd  python  winetricks  zenity  wine  lib32-libldap  wine_gecko  lib32-libpulse
可选依赖       : wine-for-wechat: get rid of those border shades
                 lib32-v4l-utils: for video chat
                 lib32-nvidia-utils: x11 on nvidia card needs this
依赖它         : 无
被可选依赖     : 无
与它冲突       : wine-wechat
取代           : wine-wechat
安装后大小     : 12.11 KiB
打包者         : lilydjwg <lilydjwg@gmail.com>
编译日期       : Thu 16 Dec 2021 10:48:26 PM CST
安装日期       : Tue 04 Jan 2022 10:43:10 PM CST
安装原因       : 单独指定安装
安装脚本       : 是
验证者         : 数字签名

**Comment by lilydjwg** [comment]
是 1.1 创建的。这个脚本里写死了使用文泉驿正黑字体。你安装 wqy-zenhei 这个包然后重新打开 wechat 应该就好了（注意从微信中退出之后可能会有残留进程需要手动杀掉）。

1.2 会自动找你的中文字体，但是仅在安装微信的时候会设置。

如果你会用注册表的话，你可以执行命令 `WINEPREFIX=$HOME/.local/lib/wine-wechat/default wine regedit` 来打开注册表编辑器，在 `HKEY_CURRENT_USER\Software\Wine\Fonts\Replacements` 下修改字体替换项。

**Comment by ding-f** [comment]
非常感谢大佬的指导！

**Comment by w934423231** [comment]
你好，我是使用的1.2的版本，但是我安装出来的微信依然是乱码的，请问有什么办法能够解决这个问题吗

、

**Comment by 67906980725** [comment]
**中文口口口或不显示**
安装 msyh.ttc msyhl.ttc msyhbd.ttc (可以复制到 ~/.local/share/fonts 下
**wine 设置中 显示-屏幕分辨率 下描述文字口口口**
安装 simsun.ttc simsunb.ttc (可以复制到 ~/.local/share/fonts 下

**Comment by colawithsauce** [comment]
补充：如果只有聊天输入框里面是乱码的话，请改动 /usr/share/applications/wine-wechat.desktop 中 Exec 行的内容如下：
```
Exec=env WINEDEBUG=-all LC_ALL="zh_CN.utf8" LANG="zh_CN.utf8" wechat
```
