### ISSUE TITLE
emacs-native-comp-git 截至 2022-01-05 已 15 天未更新

### ISSUE THREAD

**Issue by lyjdwh** [archlinuxcn/repo#2616]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* emacs-native-comp-git

----

https://repo.archlinuxcn.org/x86_64/ 目录下的软件包，emacs-native-comp-git 到目前为止半个月没有未更新了，上一次更新是2021-12-20。emacs-git 一直在更新。

**Comment by lilydjwg** [comment]
更新了，但是名字是 emacs-git……

因为 [AUR 那边的更新](https://aur.archlinux.org/cgit/aur.git/commit/?h=emacs-git&id=c2216b91960d0dfb822f5fe41ac764e1e63544d2)造成 lilac.py 中的改名未生效。

**Comment by lilydjwg** [comment]
像 qt6-base-24h 这样编辑更好，有效避免因为来源 PKGBUILD 变动过大导致编辑未生效：

https://github.com/archlinuxcn/repo/blob/50e185f23fc9aedbeac2bd47daa61eed37b9cc7a/archlinuxcn/qt6-base-24h/lilac.py#L72-L73

**Comment by lyjdwh** [comment]
确实诶，我自己编译出来包名是emacs-git。另外aur 上  emacs-native-comp-git 被删掉了，不知道会不会有影响

**Comment by ykelvis** [comment]
对哦还能raise error，抄个作业

**Comment by lyjdwh** [comment]
现在能正常更新啦，感谢
