### ISSUE TITLE
`aria2-fast` 缺失 `enable-libaria2`

### ISSUE THREAD

**Issue by rhjdvsgsgks** [archlinuxcn/repo#2617]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* aria2-fast

----

lilac 没有正确合并上游的更改，导致 `aria2.h` 缺失

https://github.com/archlinux/svntogit-community/commit/6c8ba1fd46717c25404a854918c0085db2ed389e

https://github.com/archlinuxcn/repo/commit/7d7d357960f898f16111bf469873a63a25404c1a

**Comment by lilydjwg** [comment]
lilac 没有出错。此软件包使用的 PKGBUILD [来自于 AUR](https://github.com/archlinuxcn/repo/blob/7d7d357960f898f16111bf469873a63a25404c1a/aria2-fast/lilac.yaml#L8)。而 [AUR 上的版本并没有启动这个选项](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aria2-fast#n26)。

**Comment by rhjdvsgsgks** [comment]
原来是来自 aur ，那我在这提好像没什么用的样子，是不是可以 close 了？

**Comment by pandada8** [comment]
aur 的版本已经[启用](https://aur.archlinux.org/cgit/aur.git/commit/?h=aria2-fast&id=4ee56d67fb0b5be016147aa16ce14f73163a159a)，等待 lilac 同步即可

**Comment by SilverRainZ** [comment]
https://github.com/archlinuxcn/repo/commit/ec6767745f32d03c0436692ee9d98e844ebc97b5
