### ISSUE TITLE
The version of foxitreader in archlinuxcn behind same one in aur

### ISSUE THREAD

**Issue by chih7** [archlinuxcn/repo#262]
```
$ yaourt foxitreader
1 archlinuxcn/foxitreader 1:1.1.0.0225-1 [installed]
    A fast, secure and complete PDF viewer
2 aur/foxitreader 2.1.0805-1 [installed: 1:1.1.0.0225-1] (384) (3.96)
    A fast, secure and complete PDF viewer
```

**Comment by petronny** [comment]
Updated in e7383ac8de

**Comment by JiajunW** [comment]
@petronny Thanks

**Comment by farseerfc** [comment]
See #270 
AUR upstream seems to go back to 2.1.0805-1 again...

**Comment by farseerfc** [comment]
This package may need a manually update

**Comment by petronny** [comment]
等等我有点不理解
AUR的foxitreader从8月15日起就没有变过了
我3天前触发的lilac rebuild，这样oldver应该已经是2.1.0805-1了啊
之后[repo/foxitreader](https://github.com/archlinuxcn/repo/tree/master/foxitreader)也没有变回1:1.1.0.0225-1

然后
```
rm test.db*
repo-add -n -R test.db.tar.gz testpkg-1:1.0-1-x86_64.pkg.tar.xz
repo-add -n -R test.db.tar.gz testpkg-2.0-1-x86_64.pkg.tar.xz
```
也能删掉testpkg-1:1.0-1-x86_64.pkg.tar.xz

所以问题出在哪了呢。。

**Comment by lilydjwg** [comment]
@petronny 问题出在 AUR 进行了降级。archlinuxcn 的维护脚本只支持、不支持降级。
建议：放弃 AUR，自己直接从上游获取新版本并打包。

**Comment by lilydjwg** [comment]
@farseerfc manual update won't work. You must upload a **newer** version.

**Comment by farseerfc** [comment]
@lilydjwg sorry I misunderstood how archrepo2 works

**Comment by Universebenzene** [comment]
那如果AUR的维护者不打算以后加回epoch的话就只能咱们自己搞PKGBUILD单独维护咯……？

**Comment by lilydjwg** [comment]
是的。

**Comment by Universebenzene** [comment]
@petronny 话说ttf-wps-fonts也落后了两个release……

**Comment by petronny** [comment]
那如果我们
* 手动repo-remove foxitreader
* 把foxitreader*.pkg.tar.xz删了
* 从oldver里面把foxitreader的记录删了

此时lilac再重新build foxitreader呢？会解决问题吗

**Comment by petronny** [comment]
另外@lilydjwg我问一下。。
我昨天于afe55154266653c让lilac build ttf-wps-fonts了
当时源里的ttf-wps-fonts是1.0-1，aur是1.0-3
但是为什么今天源里的居然是1.0-2的ttf-wps-fonts...

**Comment by lilydjwg** [comment]
@petronny 啊，我也清楚……不过 lilac 的逻辑好像也没大问题呢 =w=

foxitreader 那个是可以手动操作的。但是我还是建议 PKGBUILD 使用良好的来源。

**Comment by petronny** [comment]
现在看起来foxitreader 2.1.0805 不会被原来的替换掉了
关于有没有epoch我的倾向还是和AUR保持一致，以避免对那些直接从AUR打包的人造成困扰

**Comment by Universebenzene** [comment]
好的罢……我已经卸载掉旧的重装cn源里新的了……
