### ISSUE TITLE
[Package Request] linux-xanmod, linux-xanmod-edge

### ISSUE THREAD

**Issue by lyjdwh** [archlinuxcn/repo#2634]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

   XanMod is a general-purpose Linux kernel distribution with custom settings and new features. Built to provide a stable, responsive and smooth desktop experience.

* 主要语言和工具链 / Main Languages and Toolchains

    C
* 上游链接 / Upstream Link

   https://aur.archlinux.org/packages/linux-xanmod/
   https://aur.archlinux.org/packages/linux-xanmod-edge/
   https://xanmod.org/

* 为何需要这个软件包 / Why Need This Package

   linux-xanmod 集成了很多提高性能降低延迟的pathches, ，更适合linux 日常桌面使用。archlinuxcn 已经有了linux-zen，据网上评测，linux-xanmod比 linux-zen延迟更低。

**Comment by lyjdwh** [comment]
现在 https://repo.archlinuxcn.org/x86_64/ 还没有这个软件诶，是遇到了什么问题嘛

**Comment by lyjdwh** [comment]
现在没问题啦，感谢！

**Comment by CoelacanthusHex** [comment]
@ykelvis I think enabling module zstd compress following Arch Official is better.
Arch official has CONFIG_MODULE_COMPRESS_ZSTD=y now, you can simply change this option to enable it: https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/linux-xanmod-edge/PKGBUILD#L41
