### ISSUE TITLE
Changes in `bypy-git`

### ISSUE THREAD

**Issue by loynoir** [archlinuxcn/repo#2638]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* bypy-git

----

请在此补充说明。
Please describe in detail here.

```txt
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.10/site-packages/bypy/res/auth.json
```

https://github.com/houtianze/bypy/issues/606

**Comment by SilverRainZ** [comment]
Do you mean bypy-git?

**Comment by SilverRainZ** [comment]
@petronny

**Comment by SilverRainZ** [comment]
@petronny

**Comment by SilverRainZ** [comment]
@petronny

**Comment by oldherl** [comment]
I don't have interest in this package. Sorry.

**Comment by petronny** [comment]
那你从AUR orphan一下？
