### ISSUE TITLE
[emacs-git] 重新打开 Xinput2 支持

### ISSUE THREAD

**Issue by q234rty** [archlinuxcn/repo#2639]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* emacs-git
----

目前 emacs-git 包在 gnome xorg 下无法使用 fcitx5 ，测试发现仅打开 Xinput2 支持即可以解决。

不打开 Xinput2 支持就无法使用输入法可能是上游的问题，但既然 arch 下不存在老版本 xorg-server 不支持 xinput2 的问题，能否默认打开该选项？

**Comment by q234rty** [comment]
> 如果是输入法的话应该有解决方案吧，可以看看 #2613 ，另外搜了一下xinput2看起来会break EAF的东西，emacs-china有相关帖子。2613的issue里面最后的结论也是不要在额外开flag，免得造成break。 cc一下 @yqu212

打开这个 issue 的时候 x-gtk-use-native-input 在有缩放的环境下是坏的，现在这个问题是修了。

**Comment by q234rty** [comment]
> 另外搜了一下xinput2看起来会break EAF的东西
看那个讨论串的结尾似乎是已经有解决方案了？另外 xinput2 本身可以通过 `GDK_CORE_DEVICE_EVENTS=1` 关掉。

**Comment by yqu212** [comment]
这个问题最好请eaf的维护者 @manateelazycat 来看看。从[Emacs-china上的讨论](https://emacs-china.org/t/emacs-29-xinput2-eaf/19274/45?u=yqu212) 看来打开xinput2还是会break eaf，目前eaf应该还没有相关的改动。

**Comment by manateelazycat** [comment]
我的意见是，最少要有一个包要和官方的默认配置一模一样，如果要打开选项请新创建一个包。

要不是总是会出现打开一个选项让一部分人happy了，然后另一部分人挂了。

我不反对自定义选项，我只是反对arch官方没有一个包和emacs上游配置完全一致，最后大家都要去自己编译源代码。

**Comment by manateelazycat** [comment]
> ### 问题类型 / Type of issues
> 
>     * 其它 / other
> 
> 
> ### 受影响的软件包 / Affected packages
> 
>     * emacs-git
> 
> 
> 目前 emacs-git 包在 gnome xorg 下无法使用 fcitx5 ，测试发现仅打开 Xinput2 支持即可以解决。
> 
> 不打开 Xinput2 支持就无法使用输入法可能是上游的问题，但既然 arch 下不存在老版本 xorg-server 不支持 xinput2 的问题，能否默认打开该选项？

我一直用gnome xorg，可以用fcitx5。

我个人强烈建议用emacs-rime这个包一劳永逸解决问题，只用花emacser 10分钟时间，为啥要让emacs和输入法代码死磕呢？

**Comment by q234rty** [comment]
现在既然 x-gtk-use-native-input 那部分修了我先暂时把这个 issue 关了。
