### ISSUE TITLE
kdeconnect-git out of date, use vcs in nvchecker.ini

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#264]
**kdeconnect** has reached the 1.0 milestone recently, (their first stable release, I guess) but it's not in **community** yet. 

I was glad to see **kdeconnect-git** in archlinuxcn, but it's way out of date. That's because it's tracking AUR instead of the Version Control System (git). 

In order to be alerted as new commits are made, the relevant lines in **nvchecker.ini** should be changed to:

```
[kdeconnect-git]
vcs = git://anongit.kde.org/kdeconnect-kde.git
```

**Comment by farseerfc** [comment]
Wow thank you! Let's wait for next lilac's build.
