### ISSUE TITLE
gdb-multiarch 依赖错误

### ISSUE THREAD

**Issue by Y7n05h** [archlinuxcn/repo#2643]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* gdb-multiarch

----

请在此补充说明。
Please describe in detail here.

`gdb-multiarch` 依赖 `gdb-common=11.1` 但 `gdb-common` 已更新至 `11.2`

**Comment by jdw1023** [comment]
I think this is fixed in https://github.com/archlinuxcn/repo/commit/4ef2621c40b731984a35a229fbbb7794a01de866?

**Comment by Y7n05h** [comment]
> I think this is fixed in [4ef2621](https://github.com/archlinuxcn/repo/commit/4ef2621c40b731984a35a229fbbb7794a01de866)?

哦，是的，原来只是 lilac 慢了．
