### ISSUE TITLE
[REBUILD] lib32-gst-plugins-bad

### ISSUE THREAD

**Issue by ahmubashshir** [archlinuxcn/repo#2647]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* lib32-gst-plugins-bad
* lib32-soundtouch

----

请在此补充说明。
Please describe in detail here.

lib32-soundtouch was dropped from official repo.

**Comment by DDoSolitary** [comment]
07ffa7fa337fc83115bff1340b8c03f518aab40b

Just made the packages available
