### ISSUE TITLE
Clipman: saving clipboard contents after window closes in Wayland

### ISSUE THREAD

**Issue by linux40** [archlinuxcn/repo#2650]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

  Clipman is [useful](https://wiki.archlinux.org/title/Sway#Clipboard), and currently the only program serves as a clipboard manager for Wayland in AUR. However it is written in Golang, and hard to build for the GFW.

* 主要语言和工具链 / Main Languages and Toolchains

    Golang

* 上游链接 / Upstream Link

    https://github.com/yory8/clipman

* 为何需要这个软件包 / Why Need This Package

    Described above.

**Comment by Y7n05h** [comment]
大概搞定了，等 lilac 自动打完这个包之后我测试一下，应该没什么问题

**Comment by lilydjwg** [comment]
这这个程序做的事情好简略，感觉一小时就能写出来。沁细看，不知道能不能支持图片等非文本类型？

**Comment by Y7n05h** [comment]
> 这这个程序做的事情好简略，感觉一小时就能写出来。沁细看，不知道能不能支持图片等非文本类型？

clipman 本身只支持纯文本。
https://github.com/yory8/clipman#known-issues
