### ISSUE TITLE
postman 9.13.0-1 无法正常显示主页面

### ISSUE THREAD

**Issue by WAAutoMaton** [archlinuxcn/repo#2657]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* postman

----

请在此补充说明。
Please describe in detail here.

![image](https://user-images.githubusercontent.com/24771667/152666688-fddbe327-0901-46bd-b819-9f580eca4fee.png)

如图，启动后主页面停留在加载页面。

尝试过清理配置文件夹，可以加载登录页面，登录后仍无法加载主页面。

postman 9.12.0 工作正常，另外 postman-bin 9.13.0 也工作正常

**Comment by SilverRainZ** [comment]
@BruceZhang1993

**Comment by BruceZhang1993** [comment]
似乎是 Postman 在进行检查更新会卡在这里，确保网络正常多等一会儿就可以了
