### ISSUE TITLE
Cleaning up nvchecker.ini

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#266]
Here is the list of packages in `nvchecker.ini` but no folder has the same name in the repo.

- [ ] mkinitcpio-dkms
- [x] coffee-script
- [ ] nyancat-git
- [x] nodejs-mkdirp
- [ ] google-appengine-python
- [ ] underscorejs
- [ ] ironpython
- [x] evince-nodbus
- [x] keynav-lily
- [x] ruby-yard
- [x] ruby-maruku
- [x] ruby-sass
- [x] zsh-completions-git
- [x] vim-nim-git
- [x] rust-git
- [x] cargo-git
- [x] debootstrap
- [ ] autodkms
- [ ] vim-neocomplcache
- [ ] kfaenza-icon-theme
- [x] linux-mainline-docs
- [x] linux-mainline-headers
- [x] nvidia-mainline-dkms
- [x] pamixer
- [x] firefox-always-nightly
- [x] lib32-libappindicator-gtk2
- [x] lib32-libappindicator-gtk3
- [x] lib32-libappindicator-sharp
- [x] lib32-libdbusmenu-glib
- [x] lib32-libdbusmenu-gtk2
- [x] lib32-libdbusmenu-gtk3
- [x] lib32-libindicator-gtk2
- [x] lib32-libindicator-gtk3
- [x] opentk-docs
- [x] python2-more_itertools
- [ ] ruby-bundler
- [ ] dmenu-xft
- [x] binx32-postgresql
- [x] binx32-redis
- [x] binx32-tcl
- [x] binx32-tk
- [ ] fontconfig-ubuntu-zh-cn
- [ ] libcgns-paraview
- [ ] libwebqq-git
- [ ] ndiswrapper-dkms
- [ ] node-webkit
- [ ] plasma-next-icons-git
- [x] plasmate
- [ ] python2-jieba
- [x] python-pyftpdlib
- [x] python-setproctitle
- [x] systemtap-git

Generated by
```
cd repo;for i in `sed -n 's/^\[\(.*\)\]/\1/p' nvchecker.ini`;do [ ! -d $i ] && echo $i;done|tail -n +2
```

Most of them is deprecated.

**Comment by colinkeenan** [comment]
The lib32 stuff needs to stay in there:

`/home/colin %grep pkgname repo/lib32-libappindicator/PKGBUILD 
pkgname=("lib32-${_pkgbase}-gtk2" "lib32-${_pkgbase}-gtk3" "lib32-${_pkgbase}-sharp")
	cd "${srcdir}/${pkgname}"
	cd "${srcdir}/${pkgname}"
 /home/colin %grep pkgname repo/lib32-libdbusmenu/PKGBUILD 
pkgname=("lib32-${_pkgbase}-glib" "lib32-${_pkgbase}-gtk"{2,3})
	cd "${srcdir}/${pkgname}"
	cd "${srcdir}/${pkgname}"
 /home/colin %grep pkgname repo/lib32-libindicator/PKGBUILD 
pkgname=('lib32-libindicator-gtk2' 'lib32-libindicator-gtk3')
`

For these lib32 packages, there are 2 or 3 in the same PKGBUILD. The repo directory is named after the common part of the package names instead of the full package names.

**Comment by petronny** [comment]
This would be solved if we can using pkgname in nvchecker.ini
@lilydjwg could we add an entity in nvchecker.ini like following?
```
[pkgbase]
aurpkgbase=
```
So it will treat the string as a pkgbase but not a pkgname.

**Comment by petronny** [comment]
I have a temporary workaround.

```
[lib32-libappindicator]
aur=lib32-libappindicator-gtk2
```

**Comment by colinkeenan** [comment]
Do you mean like this?

```
[lib32-libappindicator]
aur=lib32-libappindicator-gtk2

[lib32-libappindicator]
aur=lib32-libappindicator-gtk3

[lib32-libappindicator]
aur=lib32-libappindicator-sharp

[lib32-libdbusmenu]
aur=lib32-libdbusmenu-glib

[lib32-libdbusmenu]
aur=lib32-libdbusmenu-gtk2

[lib32-libdbusmenu]
aur=lib32-libdbusmenu-gtk3

[lib32-libgcrypt15]
aur=

[lib32-libindicator]
aur=lib32-libindicator-gtk2

[lib32-libindicator]
aur=lib32-libindicator-gtk3
```

**Comment by petronny** [comment]
I guess we can just use the 1st pkgname to check update for each pkgbase and drop the others in nvchecker.ini

**Comment by lilydjwg** [comment]
You should put whatever your directory name is in nvchecker.

**Comment by colinkeenan** [comment]
Ok, I will put the directory name and 1st package name in nvchecker.ini for these lib32 packages.

**Comment by petronny** [comment]
I will remove all the unchecked packages on the list on 9/9.
