### ISSUE TITLE
[package request] extension-manager

### ISSUE THREAD

**Issue by SamLukeYes** [archlinuxcn/repo#2668]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    A native tool for browsing, installing, and managing GNOME Shell Extensions

* 主要语言和工具链 / Main Languages and Toolchains

    Gtk4

* 上游链接 / Upstream Link

    https://github.com/mjakeman/extension-manager
    https://aur.archlinux.org/packages/extension-manager

* 为何需要这个软件包 / Why Need This Package

    This application allows GNOME users to install GNOME extensions from extensions.gnome.org without a web browser.

**Comment by SilverRainZ** [comment]
Done.
