### ISSUE TITLE
What should we do to the packages not in AUR?

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#267]
Here is the list of packages which doesn't exist in AUR.
- [x] appmenu-qt5
- [x] archlinuxcn-keyring
- [x] archlinuxcn-mirrorlist-git
- [x] bedup-git
- [x] binx32-python2
- [x] coin
- [x] devtools-cn-git
- [x] emacs-julia-mode-git
- [x] fcitx-lilydjwg-git
- [x] flashplugin-10
- [x] fortune-zh
- [ ] fpp
- [x] freecad
- [x] garcon-devel
- [x] gnome-globalmenu-xfce4
- [x] gogoc
- [x] julia-pkg-scripts
- [x] jython27
- [x] lib32-libappindicator
- [x] lib32-libdbusmenu
- [x] lib32-libindicator
- [x] lib32-libpng12
- [x] lib32-nss-no-cnnic
- [x] lib32-python-cffi
- [x] lib32-python-ply
- [x] lib32-python-pycparser
- [x] lib32-python-setuptools
- [x] libappindicator-activate
- [x] libcurl-gnutls
- [x] libdbusmenu
- [x] libgit2-julia
- [x] libindicator
- [x] libjpeg6
- [x] libpng12
- [x] libstdc++-doc
- [x] libx32-libxslt
- [x] libxfce4util-devel
- [ ] libyubikey
- [x] linux-lily
- [x] llvm-julia
- [x] mentohust
- [x] muttils-hg
- [x] nginx-subs
- [x] oce-git
- [x] openlibm-git
- [x] openspecfun-git
- [x] pidgin-blinklight
- [ ] python2-pivy-hg
- [x] python2-wand
- [x] python-bonsai
- [ ] python-flask-peewee
- [x] python-multidict-git
- [x] python-pygal-git
- [ ] python-wtf-peewee
- [x] ruby-facter
- [x] ruby-hiera-json
- [x] simage
- [x] sysdig
- [x] systemd-rc-local
- [x] telegram-git
- [x] tpfan-admin
- [x] tpfand-no-hal
- [x] tpfand-profiles
- [x] uksmtools
- [x] vim-lily
- [x] vim-minimal-with-x
- [x] virtualbox-pf-modules
- [x] webogram-git
- [x] wget-lily
- [x] xfce4-volumed-pulse
- [x] xfce4-xfapplet-plugin
- [x] xiami-downloader-git
- [ ] ykpers

Generated by

```
cd repo;for i in *;do [ -d $i ] && [ `wget -q -O - "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=$i"|grep '"resultcount":1'|wc -l` -eq 0 ] && echo $i;sleep 1;done
```

Maybe we should sumbit them to AUR or remove them?

**Comment by farseerfc** [comment]
I think three of them `archlinuxcn-keyring` `archlinuxcn-mirrorlist` and `devtools-cn-git` should be kept in this repo only.

`libappindicator-activate` is a false positive as it is the name for a pkgbase: https://aur.archlinux.org/pkgbase/libappindicator-activate/
The same for [libdbusmenu](https://aur.archlinux.org/pkgbase/libdbusmenu) and [libindicator](https://aur.archlinux.org/pkgbase/libindicator)
`libstdc++-doc` is also a false positive as it needs encoding URL for plus sign: https://aur.archlinux.org/packages/libstdc%2B%2B-doc/

(I just checked the packages that seems to be maintained by myself)

**Comment by yuyichao** [comment]
I don't see why all packages have to be in AUR.

**Comment by petronny** [comment]
My original purpose is checking all packages track the right source in nvchecker.ini
Some of the packages have been moved to the official repositories, so we definely cannot find them in AUR.
Some of them may be out-of-date since their source in AUR have been removed, maybe we should remove them either.

Of course not all the packages have to be in AUR.

**Comment by KaseiWang** [comment]
There are some package tracking git(or some else source) but not AUR. Nvchecker support many kind of source. Should find another method to mark out-of-data packages.

**Comment by petronny** [comment]
Okay, I know this list has many false positive entities.
So please check if these packages:

1. is false positive
1. is moved to the official repositories
1. can be found in the archlinuxcn repository
1. track a non-AUR source in nvchecker.ini
1. have no `aur_pre_build` or `aur_post_build` in their lilac.py
1. should be submitted to AUR to benefit more uses

If you done these, please check out them above.
Thank you all

**Comment by lilydjwg** [comment]
* sysdig isn't in archlinuxcn.
* systemd-rc-local is deleted in AUR because admins there saw no external
  sources code.
* linux-lily is too complex to be yaourted
* vim-lily has git push operations so can't be yaourted

**Comment by lilydjwg** [comment]
Also, there are some packages that have the same name in AUR but are actually different, like:
* firefox-gtk2
* imagemagick-fftw
* rust-nightly series

**Comment by petronny** [comment]
上述一些包在nvchecker.ini中仍然在track AUR

- [ ] flashplugin-10
- [ ] garcon-devel
- [ ] gogoc
- [ ] jython27
- [ ] libjpeg6
- [ ] libstdc++-doc
- [ ] libxfce4util-devel
- [ ] lwjgl
- [ ] pidgin-blinklight
- [ ] python2-wand
- [ ] ruby-facter
- [ ] ruby-hiera-json
- [ ] tpfan-admin
- [ ] tpfand-no-hal
- [ ] tpfand-profiles
- [ ] uksmtools
- [ ] webogram-git
- [ ] xfce4-volumed-pulse

请大家处理一下

**Comment by lilydjwg** [comment]
uksmtools 没有上游了……

**Comment by farseerfc** [comment]
libstdc++-doc is a false positive as I have mentioned above ...

**Comment by petronny** [comment]
@farseerfc sry,sry...

**Comment by petronny** [comment]
没人处理的话我16日就把他们都清了

**Comment by LastAvenger** [comment]
感觉 mentohust 还是需要的，我修了一下加回来了。

**Comment by petronny** [comment]
列表中剩下的几个刚才lilac都删了
