### ISSUE TITLE
软件打包请求: nvidia-vaapi-driver

### ISSUE THREAD

**Issue by RiverOnVenus** [archlinuxcn/repo#2671]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    This is an VA-API implementation that uses NVDEC as a backend.

* 主要语言和工具链 / Main Languages and Toolchains

    C

* 上游链接 / Upstream Link

    [https://github.com/elFarto/nvidia-vaapi-driver](https://github.com/elFarto/nvidia-vaapi-driver)
	[https://aur.archlinux.org/packages/nvidia-vaapi-driver-git](https://aur.archlinux.org/packages/nvidia-vaapi-driver-git)

* 为何需要这个软件包 / Why Need This Package

    It's specifically designed for Firefox to acceleration decode web content using Nvidia.

**Comment by edward-p** [comment]
新上游？好耶！

**Comment by edward-p** [comment]
close via [2fd3b7666282315d6b4d9131354098a0e40a7a33](https://github.com/archlinuxcn/repo/commit/2fd3b7666282315d6b4d9131354098a0e40a7a33)
