### ISSUE TITLE
软件打包请求:paru-git

### ISSUE THREAD

**Issue by NextAlone** [archlinuxcn/repo#2672]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    paru-git

* 主要语言和工具链 / Main Languages and Toolchains

    rust cargo

* 上游链接 / Upstream Link

    https://aur.archlinux.org/packages/paru-git
    https://github.com/Morganamilo/paru

* 为何需要这个软件包 / Why Need This Package

    跟随上游更改

**Comment by Y7n05h** [comment]
paru release 挺频繁的，真的需要一个 -git 吗

**Comment by NextAlone** [comment]
> paru release 挺频繁的，真的需要一个 -git 吗

fish-git也有啦，打一个吧
