### ISSUE TITLE
adb SEGFAULT

### ISSUE THREAD

**Issue by rany2** [archlinuxcn/repo#2674]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* android-sdk-platform-tools

----

The `adb` command that is provided by `android-sdk-platform-tools` SEGFAULTs.

**Comment by rany2** [comment]
It appears that Google released a bad update. 31.0.0 works fine

**Comment by rany2** [comment]
The issue is caused by https://issuetracker.google.com/issues/217049285.

It is fixed by this patch: https://android-review.googlesource.com/c/platform/packages/modules/adb/+/1927562

**Comment by yan12125** [comment]
The issue is gone with android-sdk-platform-tools 33.0.0-1 ae3221b85ee86ae1969784e36f631750ed35bb5c
