### ISSUE TITLE
chromium-dev needs to be rebuilt 

### ISSUE THREAD

**Issue by BigEars431** [archlinuxcn/repo#268]
There has been some recent changes in the PKGBUILD of the development channel of chromium (chromium-dev) in the AUR, I believe it's being compiled differently now to give way for the release of the latest version. Since chromium-dev is in your awesome repo, I think it would be nice if you guys would rebuild it for the sake of safety and security =), if you guys have a bot that is doing your updates, it may not update chromium-dev because the version number is still the same

Thank you for the continuous maintenance of this repo, I might donate/contribute soon =)

**Comment by fqj1994** [comment]
done
