### ISSUE TITLE
dnsmasq-china-list-git 和 oh-my-zsh-git 缺失签名

### ISSUE THREAD

**Issue by tategotoazarasi** [archlinuxcn/repo#2683]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* dnsmasq-china-list-git
* oh-my-zsh-git

----

更新 `dnsmasq-china-list-git` 和 `oh-my-zsh-git` 这两个软件包时 pacman 提示

> (2/2) 正在检查软件包完整性                                                  [##########################################] 100%
错误：GPGME 错误：无数据
错误：GPGME 错误：无数据
错误：dnsmasq-china-list-git：缺失签名
:: 文件 /var/cache/pacman/pkg/dnsmasq-china-list-git-0.136921.7411cb2c5a-1-any.pkg.tar.zst 已损坏 (无效或已损坏的软件包 (PGP 签名)).
打算删除吗？ [Y/n] Y
错误：oh-my-zsh-git：缺失签名
:: 文件 /var/cache/pacman/pkg/oh-my-zsh-git-r6553.99460351eb-1-any.pkg.tar.zst 已损坏 (无效或已损坏的软件包 (PGP 签名)).
打算删除吗？ [Y/n] Y
错误：无法提交处理 (无效或已损坏的软件包 (PGP 签名))
发生错误，没有软件包被更新。

`/var/cache/pacman/pkg/` 目录下 `dnsmasq-china-list-git-0.136921.7411cb2c5a-1-any.pkg.tar.zst.sig` 和 `oh-my-zsh-git-r6553.99460351eb-1-any.pkg.tar.zst.sig` 这两个文件大小为0

**Comment by lilydjwg** [comment]
应该已经修好了。

**Comment by lilydjwg** [comment]
除了几个同步比较慢的商业公司镜像，大家应该都好了。
