### ISSUE TITLE
wayfire 依赖错误

### ISSUE THREAD

**Issue by ajian2002** [archlinuxcn/repo#2688]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* wayfire 

----

请在此补充说明。

wlroots 版本过旧

**Comment by yan12125** [comment]
This cannot be fixed at the Arch Linux side. Upstream explicitly requires wlroots<0.15 https://github.com/WayfireWM/wayfire/blob/v0.7.2/meson.build#L31. Please check out relevant issues on their GitHub repo instead, thanks!

**Comment by yan12125** [comment]
On the other hand, I'm going to drop wayfire-related packages from [archlinuxcn]. Please pick them up if you wish to keep them https://github.com/archlinuxcn/repo/issues/2690

**Comment by yan12125** [comment]
wayfire is removed from [archlinuxcn].
