### ISSUE TITLE
[软件打包请求] act

### ISSUE THREAD

**Issue by loynoir** [archlinuxcn/repo#2689]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

   Repo: [nektos/act](https://github.com/nektos/act) 
   
   Brief: Run your GitHub Actions locally
  
   Stars: 22k

* 主要语言和工具链 / Main Languages and Toolchains

    Go

* 上游链接 / Upstream Link

    https://github.com/nektos/act
    https://aur.archlinux.org/packages/act
    https://aur.archlinux.org/packages/act-bin

* 为何需要这个软件包 / Why Need This Package

    Run your GitHub Actions locally

**Comment by SilverRainZ** [comment]
这个有意思，这几天看看。
