### ISSUE TITLE
Orphaning wayfire and dependencies

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#2690]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* wayfire
* wf-config

----

I'm no longer interested in Wayland (maybe only in near future)

**Comment by SilverRainZ** [comment]
cc: 我记得 @lilydjwg 在用？

**Comment by lilydjwg** [comment]
我用的自己的修改版，并且暂时没空打包。

**Comment by lilydjwg** [comment]
我打包了 wayfire-lily-git 及其依赖。
