### ISSUE TITLE
About the new version of foxitreader

### ISSUE THREAD

**Issue by Universebenzene** [archlinuxcn/repo#270]
Several days ago foxitreader in AUR updated from 1:1.1.0.0225-1 to 2.1.0805-1, which got rid of the epoch (1:). Last week this update came to the archlinuxcn repo and pacman produced a warning. I asked about the warning in the #archlinux-cn channel and they told me about the epoch. Then I decided to update the package next day, but next day the version 2.1.0805-1 removed from the repo... So are there any problems which make you decide not to update the package?

**Comment by Universebenzene** [comment]
Well maybe it's an old problem that reappeared...

**Comment by farseerfc** [comment]
It's the fault of the AUR maintainer who plays around with epoch...

**Comment by Universebenzene** [comment]
@farseerfc Yes...I told the maintainer about that and he said just ignore the warning and update it...
https://aur.archlinux.org/packages/foxitreader

**Comment by lilydjwg** [comment]
@Universebenzene The problem is, version strings should only be updated to newer values, just as time always goes forward into the future. If you set time to the past, most software will just break like this.

I will never implement a way to "update into the past", which would defeat all the meaning epochs bring.

Older versions get purged, newer versions remain. That it.

**Comment by Universebenzene** [comment]
@lilydjwg I see... As it was the maintainer's fault, how about changing the epoch in PKGBUILD before rebuilding it? Will it create another problem?

**Comment by lilydjwg** [comment]
@Universebenzene that will work until next time the version strings on AUR goes backwards.

**Comment by Universebenzene** [comment]
@lilydjwg OK... I may try to continue talking to the maintainer...

**Comment by Universebenzene** [comment]
Well the version 2.1.0805-1 came back again...Still don't have the epoch.
