### ISSUE TITLE
nvm 在 devtools 中无法正常使用

### ISSUE THREAD

**Issue by Y7n05h** [archlinuxcn/repo#2702]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* nvm
----

nvm 存在 bugs 会在 devtools 中无法正常使用。
nvm 上游已在 https://github.com/nvm-sh/nvm/commit/1875fe8b40dbe69e2c5f7e6175cdc82a167eb072 修复该问题，但尚未 release。能否考虑通过 patch 提前合并这次 commit ?
nvm 作为 makedepends 无法运行，将影响别的包无法打包，希望能提前修复。

**Comment by frantic1048** [comment]
目前临时打了 `nvm-0.39.1-2`，在 `0.19.1` 之上加了这两个 patch：

0. https://github.com/nvm-sh/nvm/commit/fb4538b360a4ddd5d390442f3bfde9b3239b4413 ，后者的依赖
0. https://github.com/nvm-sh/nvm/commit/1875fe8b40dbe69e2c5f7e6175cdc82a167eb072 ，上游的实际修复

可以试试是否已经好了。

**Comment by Y7n05h** [comment]
> 目前临时打了 `nvm-0.39.1-2`，在 `0.19.1` 之上加了这两个 patch：
> 
> 0. [nvm-sh/nvm@fb4538b](https://github.com/nvm-sh/nvm/commit/fb4538b360a4ddd5d390442f3bfde9b3239b4413) ，后者的依赖
> 1. [nvm-sh/nvm@1875fe8](https://github.com/nvm-sh/nvm/commit/1875fe8b40dbe69e2c5f7e6175cdc82a167eb072) ，上游的实际修复
> 
> 可以试试是否已经好了。

辛苦了。不过，不知道为什么 lilacbot 这么用 https://github.com/archlinuxcn/repo/commit/df58aa81ba8e8ce054dba2f72c131e27cab4d2cd 覆盖了这一次的改动。现在的 nvm-0.39-3 不包含 patch 了。

**Comment by lilydjwg** [comment]
因为是从 AUR 获取打包脚本的呀。

**Comment by Y7n05h** [comment]
> 因为是从 AUR 获取打包脚本的呀。

哦对。那不如手动塞一个包？这样不必取消从 aur 获取 `PKGBUILD`，等到上游新版的 `release` 也不必在把 patch 取消掉。
@frantic1048

**Comment by frantic1048** [comment]
> 辛苦了。不过，不知道为什么 lilacbot 用 https://github.com/archlinuxcn/repo/commit/df58aa81ba8e8ce054dba2f72c131e27cab4d2cd 覆盖了这一次的改动。现在的 nvm-0.39-3 不包含 patch 了。

看了下目前 AUR 还是 nvm 0.39.1-1，可能是别的因素触发了 lilac 的 rebuild ？

或者临时整个 0.39.1-fix-abcde 这种的 :thinking:

**Comment by lilydjwg** [comment]
On Fri, Mar 25, 2022 at 03:17:06AM -0700, Jiahao Guo wrote:
> > 辛苦了。不过，不知道为什么 lilacbot 用 https://github.com/archlinuxcn/repo/commit/df58aa81ba8e8ce054dba2f72c131e27cab4d2cd 覆盖了这一次的改动。现在的 nvm-0.39-3 不包含 patch 了。
> 
> 看了下目前 AUR 还是 nvm 0.39.1-1，可能是别的因素触发了 lilac 的 rebuild ？

是 pkgrel 被更新触发的。

**Comment by frantic1048** [comment]
抱歉久等了，上游看起来还没 release，手动塞了个 `nvm-0.39.1.nvm_install_fix-1`  ，用 `vercomp` 检查了下这样的版本是 >0.39.1 （有问题的版本）且 <0.39.2 （预期上游的新 release 最小的版本）的，希望这次不会被 lilac 覆盖了（

**Comment by Y7n05h** [comment]
辛苦啦～我测试一下，它现在在 devtools 中运行的很好。十分感谢。
