### ISSUE TITLE
drop r-* pkgs and move to bioarchlinux

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#2707]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* r-abind
* r-ade4
* r-annotationdbi
* r-ape
* r-askpass
* r-assertthat
* r-backports
* r-balcony
* r-base64enc
* r-bayestestr
* r-bh
* r-biobase
* r-biocfilecache
* r-biocgenerics
* r-biocio
* r-biocparallel
* r-biomart
* r-biostrings
* r-bit
* r-bit64
* r-bitops
* r-blob
* r-brew
* r-brio
* r-broom
* r-bsgenome
* r-bslib
* r-cachem
* r-callr
* r-car
* r-cardata
* r-caret
* r-cellranger
* r-cli
* r-clipr
* r-collections
* r-colorspace
* r-commonmark
* r-conquer
* r-corrplot
* r-cowplot
* r-cpp11
* r-crayon
* r-crosstalk
* r-curl
* r-cyclocomp
* r-data.table
* r-datawizard
* r-dbi
* r-dbplyr
* r-delayedarray
* r-desc
* r-diffobj
* r-digest
* r-doparallel
* r-dplyr
* r-dt
* r-dtplyr
* r-e1071
* r-effectsize
* r-ellipsis
* r-evaluate
* r-fansi
* r-farver
* r-fastmap
* r-filelock
* r-fontawesome
* r-forcats
* r-foreach
* r-formatr
* r-fs
* r-futile.logger
* r-futile.options
* r-future
* r-future.apply
* r-gargle
* r-genbankr
* r-generics
* r-genomeinfodb
* r-genomeinfodbdata
* r-genomicalignments
* r-genomicfeatures
* r-genomicranges
* r-ggplot2
* r-ggpubr
* r-ggrepel
* r-ggsci
* r-ggsignif
* r-globals
* r-glue
* r-googledrive
* r-googlesheets4
* r-gower
* r-gridextra
* r-gtable
* r-hardhat
* r-haven
* r-here
* r-highr
* r-hms
* r-htmltools
* r-htmlwidgets
* r-httpuv
* r-httr
* r-ids
* r-insight
* r-ipred
* r-iranges
* r-irdisplay
* r-irkernel
* r-isoband
* r-iterators
* r-jquerylib
* r-jsonlite
* r-keggrest
* r-knitr
* r-labeling
* r-lambda.r
* r-languageserver
* r-later
* r-lava
* r-lazyeval
* r-lifecycle
* r-lintr
* r-listenv
* r-lme4
* r-logger
* r-lubridate
* r-magrittr
* r-manipulatewidget
* r-maptools
* r-markdown
* r-matrixgenerics
* r-matrixmodels
* r-matrixstats
* r-memoise
* r-mime
* r-miniui
* r-minqa
* r-modelmetrics
* r-modelr
* r-msa
* r-msar
* r-munsell
* r-nloptr
* r-numderiv
* r-openssl
* r-openxlsx
* r-parallelly
* r-parameters
* r-pbdzmq
* r-pbkrtest
* r-performance
* r-pillar
* r-pixmap
* r-pkgconfig
* r-pkgload
* r-plogr
* r-plotly
* r-plyr
* r-png
* r-polynom
* r-praise
* r-prettyunits
* r-proc
* r-processx
* r-prodlim
* r-progress
* r-progressr
* r-promises
* r-proxy
* r-ps
* r-purrr
* r-quantreg
* r-r6
* r-rappdirs
* r-r.cache
* r-rcolorbrewer
* r-rcpp
* r-rcpparmadillo
* r-rcppeigen
* r-rcpptoml
* r-rcurl
* r-readr
* r-readxl
* r-recipes
* r-rematch
* r-rematch2
* r-remotes
* r-report
* r-repr
* r-reprex
* r-reshape2
* r-restfulr
* r-reticulate
* r-rex
* r-rgl
* r-rhtslib
* r-rio
* r-rjava
* r-rjson
* r-rlang
* r-rmarkdown
* r-r.methodss3
* r-r.oo
* r-roxygen2
* r-rpdb
* r-rprojroot
* r-rsamtools
* r-rsqlite
* r-rstatix
* r-rstudioapi
* r-rtracklayer
* r-r.utils
* r-rvest
* r-s4vectors
* r-sass
* r-scales
* r-segmented
* r-selectr
* r-seqinr
* r-shiny
* r-shinycustomloader
* r-shinydashboard
* r-shinyjs
* r-snow
* r-sourcetools
* r-sp
* r-sparsem
* r-squarem
* r-stringi
* r-stringr
* r-styler
* r-summarizedexperiment
* r-svmisc
* r-svsocket
* r-sys
* r-testthat
* r-tibble
* r-tidyr
* r-tidyselect
* r-tidyverse
* r-timedate
* r-tinytex
* r-tzdb
* r-utf8
* r-uuid
* r-variantannotation
* r-vctrs
* r-viridislite
* r-vroom
* r-vscdebugger
* r-waldo
* r-webshot
* r-withr
* r-xfun
* r-xml
* r-xml2
* r-xmlparsedata
* r-xtable
* r-xvector
* r-yaml
* r-zip
* r-zlibbioc

----

These pkgs are available at [BioArchLinux](https://github.com/BioArchLinux/Packages) now.

**Comment by lilydjwg** [comment]
这么多包， lilac 表示累坏了（花了十分钟处理）～

**Comment by hubutui** [comment]
是啊，我一开始还以为我提交错了模板。

**Comment by SilverRainZ** [comment]
Orz 居然有这么多 r 的包。
