### ISSUE TITLE
Packager: Unknown Packager

### ISSUE THREAD

**Issue by ykelvis** [archlinuxcn/repo#271]
Is this some sort of bug? There are many packages with "Unknown Packager", should we re-package them? List as below.
- [x] binx32-python2
- [x] ccal **wych42 <ellrywych@gmail.com>**
- [x] danmaku2ass-git @fqj1994 
- [x] gcc-ada-multilib-x32
- [x] gcc-fortran-multilib-x32
- [x] gcc-go-multilib-x32
- [x] gcc-libs-multilib-x32
- [x] gcc-multilib-x32
- [x] gcc-objc-multilib-x32
- [x] gcc-x32-seed
- [x] glibc-x32-seed
- [x] julia-pkg-scripts
- [x] ld-lsb **Unknown**
- [x] libx32-acl
- [x] libx32-attr
- [x] libx32-bzip2
- [x] libx32-cracklib
- [x] libx32-curl
- [x] libx32-db
- [x] libx32-e2fsprogs
- [x] libx32-expat
- [x] libx32-flex
- [x] libx32-fontconfig
- [x] libx32-freetype2
- [x] libx32-gcc-libs
- [x] libx32-gdbm
- [x] libx32-geoip
- [x] libx32-glib2
- [x] libx32-glibc
- [x] libx32-harfbuzz
- [x] libx32-icu
- [x] libx32-jansson
- [x] libx32-jemalloc
- [x] libx32-keyutils
- [x] libx32-krb5
- [x] libx32-libcap
- [x] libx32-libdbus
- [x] libx32-libffi
- [x] libx32-libgcrypt
- [x] libx32-libgpg-error
- [x] libx32-libidn
- [x] libx32-libldap
- [x] libx32-libpng
- [x] libx32-libssh2
- [x] libx32-libtirpc
- [x] libx32-libx11
- [x] libx32-libxau
- [x] libx32-libxcb
- [x] libx32-libxdmcp
- [x] libx32-libxext
- [x] libx32-libxft
- [x] libx32-libxml2
- [x] libx32-libxrender
- [x] libx32-libxslt
- [x] libx32-libxss
- [x] libx32-libyaml
- [x] libx32-mpdecimal
- [x] libx32-ncurses
- [x] libx32-nginx
- [x] libx32-openssl
- [x] libx32-pam
- [x] libx32-pcre
- [x] libx32-postgresql
- [x] libx32-postgresql-libs
- [x] libx32-python-greenlet
- [x] libx32-readline
- [x] libx32-redis
- [x] libx32-sqlite
- [x] libx32-systemd
- [x] libx32-tcl
- [x] libx32-tk
- [x] libx32-util-linux
- [x] libx32-uwsgi
- [x] libx32-uwsgi-plugin-cgi
- [x] libx32-uwsgi-plugin-python
- [x] libx32-uwsgi-plugin-webdav
- [x] libx32-xz
- [x] libx32-yajl
- [x] libx32-zlib
- [x] python2-more_itertools @colinkeenan 
- [x] ruby-json_pure **wych42 <ellrywych@gmail.com>**
- [x] ruby-rgen **wych42 <ellrywych@gmail.com>**
- [x] tinc-pre @fqj1994 
- [x] ttf-monaco **Unknown**

**Comment by lilydjwg** [comment]
很多旧包都这样，之前编译机上没有默认的 PACKAGER 设置，又或者是维护者没有配置直接打包的。联系维护者改吧……

**Comment by petronny** [comment]
我们把libx32*都drop了吧。。
这些包在nvchecker里面都是unknown

**Comment by lilydjwg** [comment]
@petronny x32 的都 drop 掉吧。好像已经很久没有人维护了。

**Comment by petronny** [comment]
这个`wych42 <ellrywych@gmail.com>`究竟是哪位啊..
github上已经没有这个id了

**Comment by fqj1994** [comment]
我这几个都是liliac自动打包的表示不明真相。

**Comment by zsrkmyn** [comment]
wych42应该能在IRC上找到，微信里好像也见过，我去问问

2016年9月8日 22:21，"Jingbei Li" <notifications@github.com>写道：

**Comment by colinkeenan** [comment]
I recognized one packages: *python2-more_itertools*. It gets packaged under
the same PKGBUILD as *python-more_itertools*. I had forgotten to upload
*python2-more_itertools* the last time I updated these packages. I uploaded
it just now (built back in March). Now it will show me as the packager.

Is there any easy way to find out if any of these other packages are listed
under my name in nvchecker. ini?

**Comment by petronny** [comment]
@colinkeenan I have checked the rest of them manually since all the x32 packages is dropped.
Only python2-more_itertools is yours.

**Comment by colinkeenan** [comment]
thanks

**Comment by ykelvis** [comment]
@lilydjwg 话说我给ttf-monaco加了lilac.py，lilac也和上游aur同步重新打包了，但是唯独PKGBUILD里面的pkgrel没更新，导致版本号不一样...为啥啊

**Comment by petronny** [comment]
大家要认领趁现在啊，下周我就把剩下的都鸽了啊
还有#220和#218中的也是啊

**Comment by lilydjwg** [comment]
@ykelvis 大概是 bug 吧……

**Comment by MarloweW** [comment]
我来了 ccal 是我的。

**Comment by lilydjwg** [comment]
@MarloweW 你换名字了？

**Comment by petronny** [comment]
@ykelvis @lilydjwg 
有关ttf-monaco的情况和#262中后面ttf-wps-fonts的情况类似

原因是lilaclib.py中的aur_pre_build()中
如果本地PKGBUILD的pkgver和aur的PKGBUILD的pkgver一样
那么就使用本地的pkgrel
```
def aur_pre_build(name=None, *, do_vcs_update=True):
  if os.path.exists('PKGBUILD'):
    pkgver, pkgrel = get_pkgver_and_pkgrel()
  else:
    pkgver = None

  _g.aur_pre_files = clean_directory()
  if name is None:
    name = os.path.basename(os.getcwd())
  _g.aur_building_files = download_aur_pkgbuild(name)

  new_pkgver = get_pkgver_and_pkgrel()[0]
  if pkgver and pkgver == new_pkgver:
    # change pkgrel to what specified in PKGBUILD
    update_pkgrel(pkgrel)
```

**Comment by lilydjwg** [comment]
那改成 <=？

**Comment by petronny** [comment]
如果repo里的pkgrel比aur的小，则说明aur的新版本没有构建成功过(？)所以不用考虑有同名包但是内容不同的问题

如果repo里的pkgrel比aur的大，说明这个包有我们自己的patch?

那么就是pkgver == new_pkgver的情况下:
如果pkgrel>new_pkgrel那么update_pkgrel(pkgrel)

**Comment by ykelvis** [comment]
```

不对啊， `pkgver and pkgver == new_pkgver` 这个条件只有pkgver == new_pkgver才会返回true，进而执行那个`update_pkgrel(pkgrel)`，在理想情况下这个pkgrel代表的是new_pkgrel，但是它其实是那个old_pkgrel，所以导致了pkgrel最终没有被更新。

**Comment by lilydjwg** [comment]
@petronny @ykelvis https://github.com/archlinuxcn/lilac/commit/c9b2ce1c8f5794104a8218c967329a24b71747e2

**Comment by petronny** [comment]
等等我上面的逻辑还有一个问题
如果repo里的pkgrel比aur的大，说明这个包有我们自己的patch，但同时也说明有来自aur的patch
此时pkgrel应该+1以避免有同名包但是内容不同的问题

**Comment by lilydjwg** [comment]
@petronny 好复杂……等出了问题再研究一下该怎么做吧。

**Comment by petronny** [comment]
如有下列情形
aur有包test-1.0-1
然后我们也添加了test-1.0-1, 然后我们发现了问题a, 汇报给aur无下文，于是我们手动做了a.patch然后发布test-1.0-2
一段时间后aur维护者回来了，打了a.patch的同时又做了一个b.patch，发布test-1.0-2
此时lilac会打一个新的test-1.0-2，然后就出现了同名包但是内容不同的问题
此时应该打一个test-1.0-3才是

如果是下面的情形
aur有包test-1.0-1
然后我们也添加了test-1.0-1, 然后我们发现了问题a, 汇报给aur无下文，于是我们手动做了a.patch然后发布test-1.0-2
然后又发现了问题b, 汇报给aur无下文，于是我们手动做了b.patch然后发布test-1.0-3
一段时间后aur维护者回来了，做了一个c.patch，发布test-1.0-2
此时lilac应该发布test-1.0-4

**Comment by lilydjwg** [comment]
@petronny 使用 pkgrel=0 来触发会有问题：

1. 打包有问题，设置 pkgrel=0
2. lilac 重新打包，还是有问题
3. pkgrel 已经是 0 了。再怎么触发呢？

不如这样，如果是由更新触发的，那么 `max(pkgrel+1, new_pkgrel)`，否则 `pkgrel`。

**Comment by petronny** [comment]
那么test-1.0-1直接就打包失败了呢。。
按理说我们也应该出打1.0-1才对

除了0以外，不填呢？这样get_pkgver_and_pkgrel应该会返回None
处理一下就有两个触发的标记了

**Comment by ykelvis** [comment]
其实我觉得我们在加custom patch的时候可以给pkgrel加个小数点，比如aur_pkgrel=2，repo里面加了patch后改成pkgrel=2.1，这样可以避免之后aur_pkgrel=3的时候和repo里面的版本号一致而检测不到更新的问题。

不过pkgrel是int才比较符合arch官方的文档...虽然我试了一下pkgrel=2.4的话pacman是可以知道这个相对pkgrel=2是一个升级包...

```
Package (1)       Old Version  New Version  Net Change

libqtshadowsocks  1.9.0-2      1.9.0-2.4      0.00 MiB

Total Installed Size:  0.38 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
```

**Comment by farseerfc** [comment]
pkgrel 不需要是 int ，是和 pkgver 一樣的格式，lilac 和 archrepo2 貌似也支持了。
官方源打包的時候 pkgrel 不是 int 的用法在 ArchWiki 上有提到的一點是，如果某個 PKGBUILD 打出來的針對某個 arch （比如 i686）需要更新而對別的 arch 不影響的時候，可以只升級某個 arch 的 pkgrel 的小版本，這樣下次更新 PKGBUILD 的時候可以一起更新。
https://wiki.archlinux.org/index.php/AUR_Trusted_User_Guidelines#Accessing_and_Updating_the_Repository

**Comment by petronny** [comment]
所以我们就用1.0, 1.1什么的trigger rebuild就行了？

**Comment by farseerfc** [comment]
嗯我覺得可以

**Comment by petronny** [comment]
贴一下查找该问题的命令
```
pacman -Slq archlinuxcn | LANG=C pacman -Si - | grep "Packager.*Unknown" -B16 | grep 'Name' | cut -d":" -f2
```
现在只有ccal了。。

**Comment by ykelvis** [comment]
@lilydjwg 话说还是有很多包lilac并没有跟进aur的更新啊

 cataclysm-dda-ncurses 0.C-3 -> 0.C-5 lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
cdate 1.0.5-1 -> 1.0.5-2 lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
dee 1.2.7-5 -> 1.2.7-9 lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>
flann 1.8.4-2 -> 1.8.4-3 lilac (on behalf of kasei) <cnsdwpc@gmail.com>
foxitreader 1:1.1.0.0225-1 -> 2.1.0805-1 lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
gitter 3.1.0-1 -> 3.1.0-2 lilac (on behalf of lilydjwg) <lilydjwg@gmail.com>
google-chrome-dev 55.0.2859.0-1 -> 55.0.2868.3-1 lilac (on behalf of lilydjwg) <lilydjwg@gmail.com>
i3blocks 1.4-2 -> 1.4-3 lilac (on behalf of inkn) <i@inkn.ml>
kreogist-mu 1:0.9.9.1-1 -> 1:0.9.9.3-1 lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
libnatspec 0.3.0-1 -> 0.3.0-2 lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
libtinfo 6-6 -> 6-14 lilac (on behalf of Jingbei Li) <i@jingbei.li>
libunity 7.1.4-2.1 -> 7.1.4-2 lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>
llvm-pypy-stm 201645-2 -> 201645-3 lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
lxd 2.1-1 -> 2.1-2 lilac (on behalf of kasei) <cnsdwpc@gmail.com>
masterpdfeditor 3.7.10-1 -> 3.7.10-2 lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>
megasync 2.9.8.0-1 -> 2.9.8.0-2 lilac (on behalf of yk) <yk@archlinuxcn.org>
musescore-git 1:11186.b88ff97-1 -> 1.1.b88ff9754f943716d38cad7c6074e5857f5b913e lilac (on behalf of lilydjwg) <lilydjwg@gmail.com>
onedrive 1.1-2 -> 1.1-3 lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>
opsu 0.12.1-1 -> 0.12.1-3 lilac (on behalf of Jingbei Li) <i@jingbei.li>
paman 0.9.4-5 -> 0.9.4-6 lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
pasystray 0.6.0-1 -> 0.6.0-3 lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>
pavumeter 0.9.3-6 -> 0.9.3-7 lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
princexml 10r7-1 -> 10r7-2 lilac (on behalf of lilydjwg) <lilydjwg@gmail.com>
python-aiohttp 1.0.1-2 -> 1.0.2 lilac (on behalf of 依云) <lilydjwg@gmail.com>
python-libclang 3.8.2-1.2 -> 3.8.2 lilac (on behalf of wicast) <wicastchen@hotmail.com>
python-regex-hg 225.2c8d7cb10e4f-1 -> 20160922 lilac (on behalf of lilydjwg) <lilydjwg@gmail.com>
python2-lz4 0.7.0-1 -> 0.7.0-2 lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>
qt-installer-framework 2.0.3-1 -> 2.0.3-2 lilac (on behalf of Jiajun Wang) <amesists@gmail.com>
qt5-quick1 5.7.0-2 -> 5.7.0-3 lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>
ruby-gettext 3.2.1-1 -> 3.2.2 lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
rust-nightly 1.13.0_20160922-1 -> 2016-09-22 lilac (on behalf of lilydjwg) <lilydjwg@gmail.com>
spice-vdagent-git 0.16.0.25.gec843a2-1 -> 1.1.2192414c403e3f24292472e702e2f69849244cee lilac (on behalf of wicast) <wicastchen@hotmail.com>
sublime-text-dev 3.3124-1 -> 3.3126-1 lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>
superlu 5.2.0-1 -> 5.2.0-2 lilac (on behalf of kasei) <cnsdwpc@gmail.com>
telegram-desktop 0.10.1-1 -> 0.10.7-1 lilac (on behalf of CUI Hao) <cuihao.leo@gmail.com>
texlive-dummy 0.0.4-1 -> 2016.41843 lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>
ttf-ancient-fonts 2.59-1 -> 2.59-2 lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
wget-lily 1.17.1-2 -> 1.18-1 lilac (on behalf of lilydjwg) <lilydjwg@gmail.com>
xflux 20130901-3 -> 20130901-5 lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
xpra-winswitch 0.17.4-1 -> 0.17.5-1 lilac (on behalf of Jiachen Yang) <farseerfc@gmail.com>

**Comment by lilydjwg** [comment]
@ykelvis 这些包怎么了？

**Comment by petronny** [comment]
有一些是之前那个pkgrel的bug导致的落后，实际上这些pkgrel落后的包我觉得其实都是最新的了
我们rebuild一下吧

**Comment by ykelvis** [comment]
33/49 都是aur的
baka-mplayer-git aur =
beignet-git vcs =
cataclysm-dda-ncurses aur=
cdate aur=
dee aur=
emacs-julia-mode-git vcs =
flann aur =
foxitreader aur =
gitter aur =
go-for-it-git aur =
google-chrome-dev aur = google-chrome-dev
i3blocks aur =
julia-git vcs =
kdeconnect-git vcs=git://anongit.kde.org/kdeconnect-kde.git
kreogist-mu aur =
libnatspec aur=
libtinfo aur=
libunity aur=
libunwind-git vcs =
llvm-pypy-stm aur=
lxd aur =
masterpdfeditor aur=
megasync aur =
musescore-git vcs =
oce-git vcs =
onedrive aur=
openblas-lapack-git vcs =
opsu aur=
paman aur=
pasystray aur=
pavumeter aur=
princexml aur =
python-aiohttp pypi = aiohttp
python-libclang pypi = libclang-py3
python-regex-hg bitbucket = mrabarnett/mrab-regex
python2-lz4 aur=
qt-installer-framework aur =
qt5-quick1 aur=
ruby-gettext gems = gettext
rust-nightly url = https://static.rust-lang.org/dist/index.html
spice-vdagent-git vcs =
sublime-text-dev aur=
superlu aur =
telegram-desktop aur =
texlive-dummy archpkg = texlive-core
ttf-ancient-fonts aur=
wget-lily archpkg = wget
xflux aur =
xpra-winswitch aur=

**Comment by lilydjwg** [comment]
python-aiohttp 好像是因为 PyPI API 没返回正确的信息所以上次打包失败了。wget-lily 的情况不清楚我去查一下。ruby-gettext 上次打包失败了。

**Comment by petronny** [comment]
话说Unknown Packager这个问题已经解决了
有关有些包比aur落后这个问题另开issue吧

**Comment by petronny** [comment]
@fqj1994 chromium-dev{,-vaapi}两个包`Unknown Package`了，请处理一下

**Comment by fqj1994** [comment]
@petronny 我现在手上没ssh的key。麻烦帮忙把 repo 里面的 chromium-dev-vaapi 删了吧（已deprecated）。chromium-dev 我过两天弄。

**Comment by fqj1994** [comment]
chromium-dev 的编译机现在设了 packager 呢。下次 aur 上有 update 的时候应该就好了

**Comment by petronny** [comment]
> 下次 aur 上有 update 的时候应该就好了

chromium-dev是自动更新的包吗。。。为什么我既没有看到chromium-dev/lilac.py, 也没有看到nvchecker.ini中有chromium-dev...

**Comment by fqj1994** [comment]
我这边机器跑着的 cronjob。liliac 那机器编译 chrome 的话一下午就别编译别的东西了

**Comment by lilydjwg** [comment]
chromium 应该没有那么难以编译的吧，会比火狐慢很多么？

**Comment by fqj1994** [comment]
会。。。fresh build 我笔记本一晚上。火狐我还在用的时候大概那时候我的渣笔记本就三四个小时。

**Comment by lilydjwg** [comment]
按比例算的话，火狐12分钟，chromium 36分钟？比 llvm-svn 慢一点的样子。

**Comment by fqj1994** [comment]
36 分钟现在真编不完。我 e5-2692 的 u 都得（chromium） 20+ 分钟。aur 那个包最开始还会自己编译一个 clang 就更慢了。

**Comment by fqj1994** [comment]
要是编得完我一开始就 liliac 了也不会现在这么折腾。

**Comment by lilydjwg** [comment]
这也不是很慢嘛。lilac 有六小时时间来编译一个包呢。

**Comment by fqj1994** [comment]
那我有空再加一个把 😂

**Comment by petronny** [comment]
编译机上我试了一下用了100分钟编译了chromium-dev，用的clang。果然够慢的

**Comment by lilydjwg** [comment]
还好啊。以前 rust-git 也要50分钟呢。

**Comment by fqj1994** [comment]
竟然只要100分钟了。。那我周末移到liliac上？

**Comment by fqj1994** [comment]
oh aur上那包现在竟然是直接下clang的binary了。。
以前是svn checkout出来先gcc build clang。。

**Comment by renyuneyun** [comment]
所以都解決了？issue不關麼？
