### ISSUE TITLE
[Package Request] stellarium

### ISSUE THREAD

**Issue by Universebenzene** [archlinuxcn/repo#2715]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    [Stellarium](https://stellarium.org/) 天文星空模拟软件

* 主要语言和工具链 / Main Languages and Toolchains

    * C/C++
    * Qt

* 上游链接 / Upstream Link

    https://github.com/Stellarium/stellarium
    https://aur.archlinux.org/packages/stellarium

* 为何需要这个软件包 / Why Need This Package

    原为官方仓库里的包，多年来一直在用，结果这两天突然被打到AUR去了。这玩意挺大的，我电脑配置没那么顶，编译一遍蛮费时间的，希望cn源能收录打包

**Comment by oldherl** [comment]
我看看

**Comment by oldherl** [comment]
Done in [45b2acd](https://github.com/archlinuxcn/repo/commit/45b2acd09af985e6893334ec00705efba52a4371)
