### ISSUE TITLE
使用webhooks做代码检查

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#272]
额。。我没接触过github webhooks
不知道能不能实现pre-commit的功能呢..
我看了一下[events list](https://developer.github.com/webhooks/#events)
貌似是没有能pre-recieve的功能的？

那么下面这个思路行不行？
大家还是向master推，但是创建一个新分支lilac
webhook hook push，内容是
服务器端pull新的提交，做代码检查，通过则merge进lilac分支
不通过则不merge进lilac分支，然后通过某种方式通知提交者出错了
build机的lilac则使用lilac分支来build包

**Comment by lilydjwg** [comment]
这个是要解决什么问题呢？

**Comment by petronny** [comment]
nvchecker.ini语法不对 https://github.com/archlinuxcn/repo/blob/master/pre-commit
语法对但是中列出的包但是并没有与之对应的文件夹 #266 
有文件夹但是下面没有lilac.py (这个还是有很多的。。)
PKGBUILD的source是vcs但是nvchecker中指定的aur #264 
如果nvchecker中可以有manual项的话，那么每一个文件夹都要对应到nvchecker.ini的某一个人下面

**Comment by lilydjwg** [comment]
1. 只有配置没有包的，这个确实用处不大
2. 有配置但是没有 lilac.py，是留着以后通过 lilac 发 out-of-date issue 用的
3. manual 是给人用的，不是给机器用的

**Comment by petronny** [comment]
2. 我是指nvchecker.ini中列出的包有对应文件夹但是下面没有lilac.py(忘了加了)这种情况
3. 我的想法是这样就比较方便查那些包归谁管了。。就像nvchecker.ini最后
```
# Others {{{1
; [archlinuxcn-keyring]

; [systemd-rc-local]
; by lilydjwg, manually update
```
这样

**Comment by lilydjwg** [comment]
@petronny 查包的维护者用 git log 啊。

**Comment by farseerfc** [comment]
能不能直接在現在的 pre-commit 裏面加幾條命令來檢查呢？感覺 nvchecker.ini 有但是沒文件夾這種情況可以檢查出來

**Comment by lilydjwg** [comment]
@farseerfc 加呗。

**Comment by farseerfc** [comment]
還是沒考慮清楚需要檢查哪些情況，先大體寫了一下，然後把現在會報錯的兩種情況註釋掉了

**Comment by farseerfc** [comment]
這個我先關了吧，有新的要檢查的東西再提新 issue 。
