### ISSUE TITLE
[Package Request] linux-libre

### ISSUE THREAD

**Issue by zaaurus** [archlinuxcn/repo#2720]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Linux-libre is a modified version of the Linux kernel that contains no binary blobs, obfuscated code, or code released under proprietary licenses.

* 主要语言和工具链 / Main Languages and Toolchains

    （请在此填写）

* 上游链接 / Upstream Link

https://www.fsfla.org/ikiwiki/selibre/linux-libre/
https://aur.archlinux.org/packages/linux-libre/

* 为何需要这个软件包 / Why Need This Package

Use a kernel that is free of binaries, obfuscated code, or code released under proprietary licenses.

**Comment by zaaurus** [comment]
And linux-libre-headers
https://aur.archlinux.org/packages/linux-libre-headers

**Comment by zaaurus** [comment]
Excuse me, any news?

**Comment by SilverRainZ** [comment]
It seems that no any packager interested on it.

**Comment by Y7n05h** [comment]
I don't use this package, but I think it's of great importance. So I will finish it later.

**Comment by z36r2850o** [comment]
@Y7n05h, Thank you very much!

Could you add the `linux-libre-headers`?

https://aur.archlinux.org/packages/linux-libre-headers

**Comment by Y7n05h** [comment]
> @Y7n05h, Thank you very much!
> 
> Could you add the `linux-libre-headers`?
> 
> https://aur.archlinux.org/packages/linux-libre-headers

Thanks for the feedback. I had thought linux-libre-headers had been successfully added, until your feedback I didn't realize it hadn't. This is a bug. I will fix it.

**Comment by Y7n05h** [comment]
@z36r2850o The bug has now been fixed. You can try it.

**Comment by z36r2850o** [comment]
Great, I can use! Thanks again!
