### ISSUE TITLE
electron-netease-cloud-music 不支持electron18

### ISSUE THREAD

**Issue by alca7raz** [archlinuxcn/repo#2721]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* electron-netease-cloud-music
----

请在此补充说明。
Please describe in detail here.

这个包依赖电子17,不支持电子18，但是他依赖的是电子18。

**Comment by a-wing** [comment]
@rocka 要考虑支持一下吗

**Comment by rocka** [comment]
arch 打的 electron 18.0.1-1 有问题 https://bugs.archlinux.org/task/74328

我本地用 npm 安装的 electron 18.0.1 可以正常运行

**Comment by rocka** [comment]
要不还是先换成 electron17 吧 ... 好像没人想修这个东西 ...

**Comment by a-wing** [comment]
#2722

**Comment by rocka** [comment]
为什么没有重新打包啊，需要手动 bump pkgrel 吗？

**Comment by lilydjwg** [comment]
如果上次打包成功，那么需要触发才会打新包。可以在 lilac.yaml 里加一项：

```yaml
update_on:
  - source: manual
    manual: 1
```

以后再 rebuild 就改这个数字。

**Comment by rocka** [comment]
我加好了，这次总该没问题了吧 ...
