### ISSUE TITLE
virtualbox-svn requires qt5-tools

### ISSUE THREAD

**Issue by SamLukeYes** [archlinuxcn/repo#2742]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* virtualbox-svn

----

```sh
$ virtualbox
/usr/lib/virtualbox/VirtualBox: error while loading shared libraries: libQt5Help.so.5: cannot open shared object file: No such file or directory
```

**Comment by heavysink** [comment]
[5029a40](https://github.com/archlinuxcn/repo/commit/5029a40a26c484d87b4a66acc9a7d27ee280eaae)
