### ISSUE TITLE
Package request: resp-app

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [archlinuxcn/repo#2751]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    Open source cross-platform Redis Desktop Manager GUI based on Qt 5

* 主要语言和工具链 / Main Languages and Toolchains

    Qt, cmake, qmake

* 上游链接 / Upstream Link

    - [AUR](https://aur.archlinux.org/packages/resp-app)
    - [GitHub](https://github.com/uglide/RedisDesktopManager)

* 为何需要这个软件包 / Why Need This Package

    偶尔需要检查 Redis 数据库，它先前叫做 `redis-desktop-manager` ，但似乎在一次 [大扫除中被清除掉了](https://github.com/archlinuxcn/repo/issues/1857)

**Comment by sihuan** [comment]
a55c0c2608c16de870d545985409b36ad0fe0734
