### ISSUE TITLE
[Package Request] fleet-rust

### ISSUE THREAD

**Issue by yilozt** [archlinuxcn/repo#2752]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    Fleet is the blazing fast build tool for Rust. Compiling with Fleet is up-to 5x faster than with cargo.

* 主要语言和工具链 / Main Languages and Toolchains

    Rust / Cargo

* 上游链接 / Upstream Link

    - [AUR](https://aur.archlinux.org/packages/fleet-rust)
    - [Github](https://github.com/dimensionhq/fleet)

* 为何需要这个软件包 / Why Need This Package

    可以用来加快编译 Rust 代码的速度

**Comment by Y7n05h** [comment]
上游暂未使用 git tag 或 release，因此目前只能打包 `fleet-rust-git` （ https://github.com/archlinuxcn/repo/commit/695e7b72c3b130a6afaf5fd12d79e2c3fe6de0db ）。
话说这个包是不是叫 `rust-fleet-git`更合适啊?

**Comment by yilozt** [comment]
感觉 `rust-fleet-git` 会好一点。

**Comment by yilozt** [comment]
已经可以从 archlinux 里安装 `fleet-rust-git` 了，非常感谢。

**Comment by Y7n05h** [comment]
> 已经可以从 archlinux 里安装 `fleet-rust-git` 了，非常感谢。

我最终还是修改了这个包的名字为 `rust-fleet-git` ( https://github.com/archlinuxcn/repo/commit/90e7a4e9f400425d1f40acab13aa14e4881c9633 ) 。等到这个修改了名字的包被自动构建后，若 `pacman -Syu` 会自动替换旧包。
