### ISSUE TITLE
v2raya 不该在更新时覆盖 v2raya.service

### ISSUE THREAD

**Issue by Tadion** [archlinuxcn/repo#2756]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* v2raya

----

能否将`v2raya.service`加入`backup`？
我的不想让我的修改在每次更新时都会被`pacman`覆盖。

**Comment by lilydjwg** [comment]
https://wiki.archlinux.org/title/Systemd#Editing_provided_units

**Comment by Tadion** [comment]
> https://wiki.archlinux.org/title/Systemd#Editing_provided_units

感谢依云老师。
