### ISSUE TITLE
请求将mpv-git改为mpv-full-git

### ISSUE THREAD

**Issue by OliverLew** [archlinuxcn/repo#2761]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* mpv-git

----

AUR上既有mpv-git，也有mpv-full，archlinuxcn仓库里的mpv-git实际和AUR的同名包不一样，后者只有很少的依赖。我装了AUR的包，升级的时候会出现pacman想升级到archlinuxcn同名包的问题。

**Comment by CoelacanthusHex** [comment]
事实上此包系单独的包，与 AUR 并无任何关系。我不认为一个第三方仓库的包必须优先遵守 AUR 的命名。
此外，如果照你的理由，我更不能将其更改为 mpv-full-git，因为此包相比 AUR 的 mpv-full-git 缺少功能，且 AUR 使用 ffmpeg-git 但是这个包没有。多安装依赖一般不是什么大问题，但是如果和预期的缺少功能则是大问题。
综合以上原因，恕我拒绝这个请求。

**Comment by OliverLew** [comment]
从包维护者的角度确实有道理，但是在用户的角度：
1. 它确实和AUR的包冲突了，安装了AUR中mpv-git包的用户便会遇到在日常`pacman -Syu`的时候被提示升级到第三方仓库的版本。AUR是几乎所有Arch Linux用户都会用到的，还是希望站在用户的角度，考虑包名冲突的问题。（另，pacman不会告诉用户这些信息，用户会更困惑）
2. 作为一个用户，我对`*-git`包的理解就是几乎和相应非git包一样，只是用最新的master代码编译，而改变了依赖/功能的变种都会增加后缀说明。但是这里的mpv-git却和AUR的mpv-full描述一致`(with all possible libs)`，相比官方仓库的mpv包多了如libsixel、vapoursynth等依赖。

**Comment by CoelacanthusHex** [comment]
如果我改名，会影响我的用户，他们会突然发现无法升级，因为新版本改名了。
在 Arch 里，标准的更名处置流程叫 replace，但是在这里我不能采取这个手段，否则对于你来说，等于没有更名：所有安装 mpv-git 包并且使用 archlinuxcn 的用户，mpv-git 都会被替换为更名后的包。
而如果我不使用 replace，我的用户会遇到麻烦，他们无法顺利的升级到新版本，并且如果没人告知，他们将永远不知道这个包被更名了。

这是我为什么不能改名。
而下面我从我个人理解的角度反驳你的这两条：

> 1. 它确实和AUR的包冲突了，安装了AUR中mpv-git包的用户便会遇到在日常`pacman -Syu`的时候被提示升级到第三方仓库的版本。AUR是几乎所有Arch Linux用户都会用到的，还是希望站在用户的角度，考虑包名冲突的问题。（另，pacman不会告诉用户这些信息，用户会更困惑）

但是，事实上，Arch 的行事风格就是用户知道自己的行为的后果，用户在使用第三方仓库的时候应当知道自己的野包有可能会被第三方仓库的同名包覆盖，这是预期行为。据我所知相当多的大型第三方仓库都是不关注 AUR 的，他们的 PKGBUILD 是自己写的，在各种 feature 取舍上有很大可能与 AUR 不同。

> 2. 作为一个用户，我对`*-git`包的理解就是和相应非git包几乎一样，只是用最新的master代码编译，而改变了依赖/功能的变种都会增加后缀说明。但是这里的mpv-git却和AUR的mpv-full描述一致`(with all possible libs)`，相比官方仓库的mpv包多了如libsixel、vapoursynth等依赖。（Edit：不清楚是新版本新增依赖，还是依然为可选依赖？）

事实上，Arch 并没有做出这种规定。只是规定了 -git 表明是从最新的源码树直接编译的。举个例子，你可以看看 AUR 的 emacs-git 包和 Arch 的 emacs 差距有多大。
同时就 mpv 这个包来说，根据 Arch 推荐的 arch-meson 构建工具的行为，我启用的除 libsixel 以外的依赖都会在 Arch 切换到 Meson 构建的时候被打开，现在没有打开很大程度上是因为 Arch 还在用 waf（0.34 时还未添加 Meson 支持），所以这些变化也是使用新版本的预期行为。
并且，事实上，https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mpv-git 这个包默认启用的功能远少于官方启用的功能，这与你的观点也是不符的。

**Comment by q234rty** [comment]
>     1. 它确实和AUR的包冲突了，安装了AUR中mpv-git包的用户便会遇到在日常`pacman -Syu`的时候被提示升级到第三方仓库的版本。AUR是几乎所有Arch Linux用户都会用到的，还是希望站在用户的角度，考虑包名冲突的问题。（另，pacman不会告诉用户这些信息，用户会更困惑）
请直接使用 pacman.conf 的 IgnorePkg

**Comment by OliverLew** [comment]
大家说的很清楚，很有道理。在尝试楼上的建议之前，我试着把本地的pkgbuild改个包名吧。

也容我以愚蠢小白用户的视角吐槽一下。aur也算是Arch用户形成广泛共识的（间接，因为只提供pkgbuild）包来源了，在我看来和cn库都是社区维护。并且大部分用户就是单纯的用户，就是无脑的使用aur helper安装。如果第三方库同名包使用和aur一样的pkgbuild，那对用户没有影响，但不一样的话，用户就会困惑。

从上面目前3个点赞可以看到，开发者群体是了解怎么应对这种问题的，并且不觉得不妥。但是用户们没有想这么多，用户就是想我要用什么软件，要装什么软件。我最开始想打开gpu-next的vo选项，调研了半天发现需要mpv和libplacebo都使用最新代码编译。但我不想要其他依赖，就从aur装了相应的两个包，这时并没有相较官方mpv多出我不知情的依赖。系统升级时（其实不是我第一次看到）却弹出100+的tesseract包选项让我选（这是vapoursynth依赖的）。我人差点傻了，视频播放器为什么需要文本识别的依赖？这就是用户的境况，用户朴素的困惑。我吐槽并不是说我还不服，只是希望开发者在解决问题的同时，至少尝试一点点和用户的共情。

**Comment by CoelacanthusHex** [comment]
> 也容我以愚蠢小白用户的视角吐槽一下。aur也算是Arch用户形成广泛共识的（间接，因为只提供pkgbuild）包来源了，在我看来和cn库都是社区维护。并且大部分用户就是单纯的用户，就是无脑的使用aur helper安装。如果第三方库同名包使用和aur一样的pkgbuild，那对用户没有影响，但不一样的话，用户就会困惑。

无脑安装不是 Arch 用户该有的行为。事实上，Arch Wiki 上关于 AUR 和 AUR helpers 的页面就有提到，他们都是用户产出的内容，使用需要风险自负。隐含的意思便是对 AUR 的安全性不做任何保证，也就是在使用 AUR 的时候，你需要自己审阅代码避免风险。事实上，AUR 历史上确实发生过数次投毒事件。所以，「无脑的使用aur helper安装」在 Arch 是一种非常危险且不被鼓励的事情，也正是因为这点，一些 AUR helper（比如 paru）选择默认给用户展示AUR的内容，但是按你的描述，你们恐怕也是直接跳过或者关掉的……

> 从上面目前3个点赞可以看到，开发者群体是了解怎么应对这种问题的，并且不觉得不妥。但是用户们没有想这么多，用户就是想我要用什么软件，要装什么软件。我最开始想打开gpu-next的vo选项，调研了半天发现需要mpv和libplacebo都使用最新代码编译。但我不想要其他依赖，就从aur装了相应的两个包，这时并没有相较官方mpv多出我不知情的依赖。系统升级时（其实不是我第一次看到）却弹出100+的tesseract包选项让我选（这是vapoursynth依赖的）。我人差点傻了，视频播放器为什么需要文本识别的依赖？这就是用户的境况，用户朴素的困惑。我吐槽并不是说我还不服，只是希望开发者在解决问题的同时，至少尝试一点点和用户的共情。

打包者之所以这么处理，其实是无奈的举措，你们有这样的需求，他们有那样的需求，我们是难以同时满足的。所以我们只能选择相对好的一个方式：上面我也提到了，多安装依赖的负面影响对大多数 Arch 用户是要比缺少功能小的，同时上游机制的限制使得我们无法把这些转化成可选依赖。
其实 Arch 官方仓库里的很多包也是这么处理的，AUR上为数众多的 dmmuy 包很多就是应对这个问题的。不是我们不能共情，而是现实让我们只能这样做。
或者说，正是因为我们需要对所有用户共情，才产生了这样的决定。

**Comment by OliverLew** [comment]
平复了一下心情，还是感谢你回复哈，也算是用户和开发者之间互相了解。上述观点我都是理解，我也不再反驳。

我本地的PKGBUILD暂时这么改了，等着新版本发布吧：
```diff
-pkgname=mpv-git
+pkgname=mpv-temp-git
```

另外你们也可以考虑把gpu-next打开，我就是播放Dolby Vision格式视频产生的需求。不过鉴于我没在用这边的包，不用考虑我的需求。（难道用得到vapoursynth脚本的人更多？😕）

**Comment by CoelacanthusHex** [comment]
> （难道用得到vapoursynth脚本的人更多？😕）

很多人用vs脚本给视频插帧

**Comment by lilydjwg** [comment]
没办法，不同的第三方来源之间就是会有冲突。总不可能把我们仓库里的包加个特定的前缀吧。不这样的话，同名不同内容的包总是可以产生，比如：

* AUR 那边失去了维护
* cn 仓库这边进行了修正与扩充
* AUR 维护者与 cn 维护者的需求发生了分歧
* AUR 那边新出现的包刚好与 cn 这边同名

而 pacman 并不能跟踪包的来源。因为不能指定来源仓库，给包重命名也很容易给已有用户带来问题。

> 如果第三方库同名包使用和aur一样的pkgbuild，那对用户没有影响

不，也会有影响，比如依赖的库更新 soname 的时候。
