### ISSUE TITLE
Dependency issues with python-torchvision

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#2762]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* python-torchvision

----

1. python-requests is needed since torchvision 0.12.0 https://github.com/pytorch/vision/pull/5047
```
$ python -c 'import torchvision'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets
  File "/usr/lib/python3.10/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import KittiFlow, Sintel, FlyingChairs, FlyingThings3D, HD1K
  File "/usr/lib/python3.10/site-packages/torchvision/datasets/_optical_flow.py", line 13, in <module>
    from .utils import verify_str_arg
  File "/usr/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
2. As per [upstream setup.py](https://github.com/pytorch/vision/blob/main/setup.py), torchvision requires typing_extensions, numpy, requests and torch, and scipy is an extra dependency. You may want to also add `python-typing_extensions` to depends. It's a dependency of python-pytorch, while transitive dependencies are discouraged in Arch Linux.
3. `python-tqdm` and `python-six` are not needed since version 0.3.0 and 0.6.0, respectively https://github.com/pytorch/vision/pull/768 https://github.com/pytorch/vision/pull/2017. Both can be removed from depends.

**Comment by hubutui** [comment]
I thought `typing_extensions` is for "Enable use of new type system features on older Python versions". ArchLinux ships python 3.10, so we don't need it? But according to [this](https://pypi.org/project/typing-extensions/), it also enable experimentation with new type system PEPs before they are accepted and added to the `typing` module.

**Comment by yan12125** [comment]
Thanks for the update!

> we don't need it?

Theoretically yes. Per https://github.com/pytorch/vision/search?q=typing_extensions, only `typing_extensions.Literal` is used, and it is available as `typing.Literal` since Python 3.8. Anyway, upstream needs to change setup.py and replace `typing_extensions` with something like `typing_extensions; python_version<"3.8"` first.
