### ISSUE TITLE
firefox-esr doesn't recognize firefox-esr-i18n-zh-cn

### ISSUE THREAD

**Issue by DLslime** [archlinuxcn/repo#2782]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* firefox-esr-i18n-zh-cn

----

$ pacman -Ql firefox-esr-i18n-zh-cn
firefox-esr-i18n-zh-cn /usr/
firefox-esr-i18n-zh-cn /usr/lib/
firefox-esr-i18n-zh-cn /usr/lib/firefox-esr/
firefox-esr-i18n-zh-cn /usr/lib/firefox-esr/extensions/
firefox-esr-i18n-zh-cn /usr/lib/firefox-esr/extensions/langpack-zh-CN@firefox.mozilla.org.xpi

**Comment by dctxmei** [comment]
I have reported this to the firefox-esr maintainer at AUR, please wait for a fix
