### ISSUE TITLE
emacs-git 应该默认打开native-compile

### ISSUE THREAD

**Issue by yangsheng6810** [archlinuxcn/repo#2786]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

*  emacs-git

----

在native-compile已经被收入Emacs 28的现在，几乎找不到emacs-git不默认打开native-compile的理由了。至于是否AOT编译所有包，可以视情况而定。这大概也是emacs-native-comp-git没有更新的原因。#2616

**Comment by q234rty** [comment]
我觉得还是另外打个 emacs-native-comp-nopgtk 好一点

**Comment by q234rty** [comment]
现在的 emacs-native-comp-git 因为 https://aur.archlinux.org/packages/emacs-git 的改动又把 pgtk 关掉了。。

**Comment by ykelvis** [comment]
archlinux官方的包分成了两个emacs和emacs-nativecomp，所以这里也继续保持分开吧，emacs-git就不开nativecomp了

**Comment by yangsheng6810** [comment]
按照Emacs维护者的意思，native-comp基本可以无脑开，pgtk则不是。在X下，pgtk可能有很多大大小小的问题，因此除非使用Wayland，否则不建议使用pgtk。所以个人倾向于使用：`emacs-native-comp-git` 和 `emacs-native-comp-pgtk-git`的分开方式。

**Comment by ykelvis** [comment]
唉，这是因为年初有一次讨论，最后结论是把nativecomp和pgtk扔给emacs-native-comp-git这个包，所以才有现在的nopgtk这样的分包（
#2613

**Comment by yangsheng6810** [comment]
草，原来这么多大佬讨论过类似问题……所以是不是应该去re-open那个issue，在那边讨论？

**Comment by chuxubank** [comment]
emacs-native-comp-git 目前似乎又没有开启 pgtk 了（在 wslg 下显示模糊）
而目前还有一个 emacs-native-comp-nopgtk-git

但是 aur 上的 https://aur.archlinux.org/packages/emacs-native-comp-git 实际默认没有开启 pgtk
而是 https://aur.archlinux.org/packages/emacs-pgtk-native-comp-git 开启了 pgtk

我们能否 follow 这种命名方式，并且在 emacs-pgtk-native-comp-git 中确实开启 pgtk 呢？

**Comment by q234rty** [comment]
> emacs-native-comp-git 目前似乎又没有开启 pgtk 了

似乎是因为同时设置了 `GTK3="YES"` 和 `PGTK="YES"` 而 PKGBUILD 中 https://github.com/archlinuxcn/repo/blob/697808ef595cfa49de5a339d84fdf0b66f32e530/archlinuxcn/emacs-native-comp-git/PKGBUILD#L269-L272 这里第 272 行只有在 `GTK3="YES"` 没有设置的时候才可能执行。

**Comment by ykelvis** [comment]
看了下这几天打包没啥问题了，新的逻辑也不怕aur上再开什么flag搞出问题了。以后是emacs-native-comp-git和emacs-native-comp-pgtk-git，emacs-native-comp-nopgtk-git过些天会被机器人删掉。
