### ISSUE TITLE
gammaray-qt6-git (probably) needs rebuild

### ISSUE THREAD

**Issue by moodyhunter** [archlinuxcn/repo#2793]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* gammaray-qt6-git

----

请在此补充说明。
Please describe in detail here.

`gammaray: symbol lookup error: /usr/bin/../lib/libgammaray_common-qt6_2-x86_64.so.3.0.0: undefined symbol: _ZN18QMutableEventPoint12setTimestampEm, version Qt_6_PRIVATE_API`

**Comment by moodyhunter** [comment]
`gammaray-qt6-git` should also "conflicts" `gammaray`, but it didn't

**Comment by SilverRainZ** [comment]
Rebuilt by https://github.com/archlinuxcn/repo/commit/efd4902c0f21d8d60805cefbce373f461c9e2a15 , can we close this issue now?

**Comment by moodyhunter** [comment]
for more information, the upstream has had the `work/qt6-support` branch merged late in March, so the build script should use `master` directly.
