### ISSUE TITLE
devtools-archlinuxcn: should it claim compatibility with official devtools?

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#2798]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* devtools-archlinuxcn

----

## Background

Arch Linux is trying to [make packages reproducible](https://reproducible.archlinux.org). As part of the efforts, devtools version is recorded in built packages via two shell variables `$BUILDTOOL` and `$BUILDTOOLVER` [1][2], so that compiler/linker flags can be inferred. All official packages are required to have valid `$BUILDTOOL` and `$BUILDTOOLVER` [3]. Currently, `$BUILDTOOL` is hard-coded as `devtools` [4] and `$BUILDTOOLVER` is `${pkgver}-${pkgrel}-${arch}` (ex: `20220207-2-any`) [5].

## Issue

Those shell variables appear in devtools 20211129. When upgrading devtools-archlinuxcn from current 20200407 to 20220207, should it use the same set of `$BUILDTOOL` and `$BUILDTOOLVER` as devtools? Here are some pros/cons for either direction. If devtools-archlinuxcn uses the same set of `$BUILDTOOL` and `$BUILDTOOLVER`,

* build.archlinuxcn.org can be used to build official packages. I remember @felixonmars once said that he cannot use build.archlinuxcn.org due to mismatching `$BUILDTOOL` and `$BUILDTOOLVER`.

On the other hand, if devtools-archlinuxcn uses a different set of `$BUILDTOOL` and `$BUILDTOOLVER`,

* Maintaining this package is simpler. It can be managed by lilac easily, as we don't care about the value of `$pkgrel` (used in `$BUILDTOOLVER`)
* It will be fine to carry patches that change built packages. Current patches, including those proposed for ARM [6], seem unrelated to contents of built packages. I'm not sure if we will need such patches in the future.
* It might be necessary to replace `export BUILDTOOL=devtools` with something like `export BUILDTOOL=devtools-archlinuxcn` to avoid confusing scenarios where the same set of `$BUILDTOOL` and `$BUILDTOOLVER` can generate different packages for the same PKGBUILD.

[1] https://lists.archlinux.org/pipermail/pacman-dev/2021-April/025044.html
[2] https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/63
[3] https://archlinux.org/todo/packages-with-invalid-buildtoolver-in-buildinfo/
[4] https://gitlab.archlinux.org/archlinux/devtools/-/blob/20220207/lib/common.sh#L19
[5] https://github.com/archlinux/svntogit-packages/blob/5d06d725c2470be02e750e0fece82d7eaf4ec7b2/trunk/PKGBUILD#L42
[6] https://github.com/archlinuxcn/repo/pull/2795

**Comment by lilydjwg** [comment]
I prefer to declare our own $BUILDTOOL. I don't think we'll need patches that modifies built packages, but it could happen somehow in the future in an unexpected way.

To build official packages on build.archlinuxcn.org, we could install a standalone copy of Arch in a systemd-nspawn container. I can try to setup one if that is desired.

**Comment by yuyichao** [comment]
It should also be possible to have devtools-archlinuxcn respect externally set BUILDTOOL. If there's any patches that we'll carry in the future that changes how the packages are built, they could condition on the right BUILDTOOL.

**Comment by yuyichao** [comment]
> Do you mean making devtools-archlinuxcn use BUILDTOOL=devtools for now and switch to something else when necessary?

Assuming this is asking me. No I meant that setting BUILDTOOL to something else by default. But if you run it with `BUILDTOOL=devtools`, it'll respect that setting and also any future patches we carry that affect the package being built should respect such a setting and revert back to the upstream behavior.

**Comment by yan12125** [comment]
> No I meant that setting BUILDTOOL to something else by default...

Got it, thanks! That's an interesting idea. I can give a try if there are no other opinions.

**Comment by yan12125** [comment]
Implemented as part of https://github.com/archlinuxcn/repo/pull/2795. Thanks for constructive suggestions!
