### ISSUE TITLE
与 [community] 重复的包 / Packages that exist in [community]

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#280]
* [x] multilib/lib32-libpng12
* [x] community/libcurl-gnutls
* [x] community/libpng12
* [x] community/libtiff4
* [x] multilib/steam-native-runtime (取代 steam-libs)

**Comment by lilydjwg** [comment]
@colinkeenan @felixonmars @renyuneyun

**Comment by colinkeenan** [comment]
I have removed libcurl-gnutls

**Comment by renyuneyun** [comment]
community中的libtiff4應該是當時aur中那個，由於ldconfig的存在會同時提供libtiff{,xx}.so.3。

而maya2015依賴libtiff3，libtiff3又依賴libtiff4，但libtiff3安裝時候也會再創建一次上述符號鏈接，所以會產生文件衝突。
之前在archlinuxcn中提供libtiff4就是爲了避免用戶手動解決這個問題。
（僅存底，萬一有人碰巧遇到這個問題呢）

不過現在aur中沒有maya2015了，新的maya（2016）也不再依賴這些東西了。我會將libtiff4和libtiff3一同刪除。（aur中依然有這兩個包，但是我很久沒用過maya也沒碰過它們了，不知道現在這兩個包是否還會衝突）

另外奇怪的是，community的包不應該是從aur移過去的麼？爲什麼現在libtiff4既在community中也在aur中呢……

在 2016年09月28日 15:16, 依云 写道:

**Comment by farseerfc** [comment]
我去問問 libtiff4 爲什麼還在 AUR 。
其實所謂的移動只是手動添加到 community 然後手動從 AUR 刪掉，有的時候可能忘記刪。

**Comment by farseerfc** [comment]
> alucryd: basically there was an abi change during the libtiff3's life, and an unofficial libtiff4 was born
> alucryd: currently libtiff 4.x is actually libtiff5
> alucryd: I didn't remove the aur package because it was a split package, but it seems I should have his libtiff3 is too recent and is actually the unofficial libtiff4

順便移動 libtiff4 貌似是爲了 steam-libs ，近期他們會將 steam-libs 放入官方源，期間可能改個包名。

**Comment by farseerfc** [comment]
https://www.archlinux.org/packages/multilib/x86_64/steam-native-runtime/

now that we can append `steam-libs` to this list.

**Comment by felixonmars** [comment]
{lib32-,}libpng12 removed.

**Comment by petronny** [comment]
贴一下检测该问题的命令，只能检测[community]的。。
```
for i in `pacman -Slq archlinuxcn`;do LANG=C pacman -Si community/$i 2>&1 | grep -v '^error' | grep '^Name'; done
```
[extra] [core]等等的请大家自行再写一个for。。

现在又有包和[community]重复了
```
Name            : python-wtforms
Name            : spice-vdagent
```

**Comment by lilydjwg** [comment]
```
>>> which duppkg4repo 
duppkg4repo () {
        local repo=$1
        [[ -z $repo ]] && {
                echo 'which repository to examine?' >&2
                return 1
        }
        local pkgs
        pkgs=$(comm -12 \
    <(pacman -Sl $repo|awk '{print $2}'|sort) \
    <(pacman -Sl|awk -vrepo=$repo '$1 != repo {print $2}'|sort) \
  )
        [[ -z $pkgs ]] && return 0
        LANG=C pacman -Si ${=pkgs} | awk -vself=$repo '/^Repository/{ repo=$3; } /^Name/ && repo != self { printf("%s/%s\n", repo, $3); }'
}
```

```
>>> duppkg4repo archlinuxcn | grep -v 'archlinuxfr\|blackarch\|markzz' | sed 's/^/* [ ] /'
* [ ] community/python-wtforms
* [ ] community/spice-vdagent
```
