### ISSUE TITLE
python-mediapipe needs rebuild

### ISSUE THREAD

**Issue by renyuneyun** [archlinuxcn/repo#2800]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* python-mediapipe

----

由于opencv和python-opencv从4.5.5更新到4.6.0，本包无法正确查找到对应的`.so`文件。故而本包需要重新打包。

**Comment by hubutui** [comment]
你确定这个包rebuild能用？我记得好像不行的，正准备删掉呢。

**Comment by renyuneyun** [comment]
我以前的经验是需要rebuild，然后就可以了的。[AUR上`-git`包的评论](https://aur.archlinux.org/packages/python-mediapipe-git)可以做侧面证据。
不过最近我开的程序比较多，还没找到机会在本地尝试。

**Comment by hubutui** [comment]
我的意思是这个包本来就坏了的。你可以试试。或者修复一下。

**Comment by renyuneyun** [comment]
检查了一下，现在的确好了。
这个包应该是没问题的吧？我之前是自己编译的，一直在用（是fake-background-webcam的依赖），后来发现cn仓库里有就不再自己编译了。上面的「经验」也是自己用这个包的经验。

**Comment by hubutui** [comment]
@renyuneyun 你确定能用的话我就留着吧，我最近没有用它．我记得 `import mediapipe` 就直接 segment fault 的啊．

**Comment by renyuneyun** [comment]
有意思……的确会segment fault。但更新了之后`fake-background-webcam`也的确可以正常使用了（没更新之前报找不到`.so`）。
也许是使用的姿势不对？……

**Comment by hubutui** [comment]
反正你能用就用，不能用的话，我也修不了。
