### ISSUE TITLE
feishu-bin 在 KDE Plasma 下图标问题

### ISSUE THREAD

**Issue by choyy** [archlinuxcn/repo#2806]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* feishu-bin

----

kde plasma 下飞书关闭后，固定在启动器的图标就不显示 icon 了

需要在`feishu.desktop`里加入`StartupWMClass=bytedance-feishu`才正常

**Comment by Xuanwo** [comment]
Already reported by https://aur.archlinux.org/packages/feishu-bin#comment-868998.

Closing this issue.

**Comment by choyy** [comment]
@Xuanwo `Icon`又写错了，文件名是`bytedance-feishu`，`.desktop`中只写了`feishu`

**Comment by Xuanwo** [comment]
> @Xuanwo `Icon`又写错了，文件名是`bytedance-feishu`，`.desktop`中只写了`feishu`

请反馈给 AUR 的维护者
