### ISSUE TITLE
Orphaning isso

### ISSUE THREAD

**Issue by PeterCxy** [archlinuxcn/repo#2807]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* isso

----

**Comment by SilverRainZ** [comment]
Peter 是因为不用了还是打包出了啥问题？

**Comment by oldherl** [comment]
我看到最后一次是失败。
我打算看一看，能修好的话我打算捡起来。

**Comment by PeterCxy** [comment]
@SilverRainZ 我已经至少一年没用过这个包了

**Comment by PeterCxy** [comment]
@oldherl 如果打算捡的话麻烦把 AUR 上的也捡一下，我一会儿去把 AUR 上的也 Orphan 掉

**Comment by lilydjwg** [comment]
有人把 AUR 上的包捡起来了。
