### ISSUE TITLE
nginx-mod-fancyindex 0.5.2-2未编译

### ISSUE THREAD

**Issue by Gaojianli** [archlinuxcn/repo#2817]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* nginx-mod-fancyindex 

----
此软件包PKGBUILD 在https://github.com/archlinuxcn/repo/commit/c97abef5a4b837424bfa51698b2550f2d5b39e96 已经升级到`0.5.2-2` ，但是源里面依旧只提供`0.5.2-1`，手动编译升级后每次滚动系统的时候会造成降级

**Comment by oldherl** [comment]
@DDoSolitary please don't use 'staging' if you can't manage some time to check it

**Comment by SilverRainZ** [comment]
Related to https://github.com/archlinuxcn/repo/issues/2857
