### ISSUE TITLE
zeronet has syslog identifier "env"

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#282]
每次我看到有个叫「env」的服务在打日志我都觉得奇怪，现在才知道原来它在 ExecStart 里用了 env 命令。我们不用这个命令可好？另外默认的日志级别是不是应该改高一点？

**Comment by farseerfc** [comment]
日誌級別怎麼改呢？我在 zeronet 的文檔裏沒找到

**Comment by lilydjwg** [comment]
而且它还会往 /var/log/zeronet 下写日志……只写一个地方就好了吧。

你可以 pr 他们。

**Comment by farseerfc** [comment]
找到了，命令行選項 `--debug` 會用 logging.DEBUG https://github.com/HelloZeroNet/ZeroNet/blob/3331e2305b02c660736c8c6970ffb561e6e85e39/src/main.py#L79

日誌的目錄倒是可以在 zeronet.conf 裏直接改，不過貌似沒法關掉，他們拿 debug.log 作爲 process file lock 了的樣子
https://github.com/HelloZeroNet/ZeroNet/blob/3331e2305b02c660736c8c6970ffb561e6e85e39/src/main.py#L47

**Comment by lilydjwg** [comment]
锁应该放 /run 下边啊……

**Comment by farseerfc** [comment]
log文件同時作爲鎖……怪偷懶的……

**Comment by farseerfc** [comment]
百合看 9780a82 這樣可以了麼？

**Comment by lilydjwg** [comment]
应该没问题了～
