### ISSUE TITLE
Depends update in panoply

### ISSUE THREAD

**Issue by desertstsung** [archlinuxcn/repo#2821]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* panoply

----

https://www.giss.nasa.gov/tools/panoply/changelog.html

**Comment by oldherl** [comment]
updated to java-runtime>=11 in 71acf670e766abf277e88119c65026eae35e6bde.
Closing for now. Please reopen if not fixed.
