### ISSUE TITLE
arm-linux-gnueabihf-*过期

### ISSUE THREAD

**Issue by Galaxy0419** [archlinuxcn/repo#2823]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

arm-linux-gnueabihf-gcc
arm-linux-gnueabihf-binutils
arm-linux-gnueabihf-glibc
arm-linux-gnueabihf-linux-api-headers

----

**Comment by Galaxy0419** [comment]
@yuyichao 你好，arm-linux-gnueabihf-gcc好像没有build log，库里似乎也没有更新。

**Comment by yuyichao** [comment]
等更新。
