### ISSUE TITLE
[OUT OF DATE]: extension-manager (0.2.3-1 -> 0.3.1-1)

### ISSUE THREAD

**Issue by 0xMRTT** [archlinuxcn/repo#2827]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

extension-manager

**Comment by 0xMRTT** [comment]
Try to build with the PKGBUILD from the AUR

https://aur.archlinux.org/packages/extension-manager

**Comment by SilverRainZ** [comment]
Actually, this package is already built with PKGBUILD from AUR.

0.3.1 introduce a new dependency text-engine, which only exists on AUR, I will add it soon.
