### ISSUE TITLE
Orphaning hmcl 

### ISSUE THREAD

**Issue by imlonghao** [archlinuxcn/repo#2838]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* hmcl 

----

没有 Microsoft Client ID，编译版本（非官方构建）无法支持 微软登陆

close #2837

**Comment by isjerryxiao** [comment]
反对弃置，理由如下：
* 维护从源码编译的hmcl包，而不是二进制包，对archlinuxcn用户来说更加负责。
* hmcl支持通过property设置 -Dhmcl.microsoft.auth.id=xxx -Dhmcl.microsoft.auth.secret=xxx 来使非官方构建支持微软登陆，如果担心命令行参数会泄露id和secret，也可以用java的@argument files语法，至于用户不会用那是用户的问题，与打包者无关。
* 不应当因为用户经常开issue弃置软件包，可以考虑折衷办法，如更改包名 (e.g. hmcl-unofficial)，或者在.install中说明如何登陆微软账户
