### ISSUE TITLE
Arch's python-magic changed to ahupp fork now

### ISSUE THREAD

**Issue by CoelacanthusHex** [archlinuxcn/repo#2842]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* python-magic-ahupp
* beancount

----

python-magic-ahupp needs removed.
beancount needs to update the dependency.

**Comment by Xuanwo** [comment]
Closed for already reported to https://aur.archlinux.org/packages/beancount
