### ISSUE TITLE
Require manually downgrading gnome-shell-extension-gsconnect

### ISSUE THREAD

**Issue by AlynxZhou** [archlinuxcn/repo#2844]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* gnome-shell-extension-gsconnect

----

请在此补充说明。
Please describe in detail here.

According to AUR history, the AUR packager wrongly chose v53 to package, which is not for latest gnome-shell but for gnome-shell 3.36, and the AUR packager then downgraded to v50 (which is for gnome-shell 42), but no epoch is attached. So lilac picks v53 as latest version, which is unable to use for gnome-shell 42.

I've already asked AUR packager to add epoch for it, and I think we should fix this by manually add v50's PKGBUILD into this repo. Ping @PeterCxy because you are in the maintainer list.

**Comment by AlynxZhou** [comment]
v53 is wrongly chosen: https://aur.archlinux.org/cgit/aur.git/commit/?h=gnome-shell-extension-gsconnect&id=9ef8f1e9e9671d5d9739500562f608275f87f8dc

downgrading to v49 without epoch: https://aur.archlinux.org/cgit/aur.git/commit/?h=gnome-shell-extension-gsconnect&id=754d870d1a404d65905a843f8bbcb608fcb61f47

**Comment by SilverRainZ** [comment]
@PeterCxy

**Comment by PeterCxy** [comment]
@SilverRainZ Can you take over the package if you are using it right now? I have not been using gnome for a long while and I think it's not the best idea for me to continue maintaining this package, especially when the versioning involved is important to the functionality.

**Comment by SilverRainZ** [comment]
> @SilverRainZ Can you take over the package if you are using it right now? I have not been using gnome for a long while and I think it's not the best idea for me to continue maintaining this package, especially when the versioning involved is important to the functionality.

I am not GNOME user too, if you can't maintain it anymore, I think orphaning it is OK.

**Comment by AlynxZhou** [comment]
And the AUR packager already added epoch, so this can be closed now.
