### ISSUE TITLE
orphaning vscodium

### ISSUE THREAD

**Issue by Y7n05h** [archlinuxcn/repo#2847]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* vscodium

----

打包超时，耗时过多。
https://build.archlinuxcn.org/~imlonghao/#vscodium

**Comment by Y7n05h** [comment]
> 超时的话，设置一下 `time_limit_hours` 就好了啊。

嗯，你说的对。但这个包的打包时间从日志看是翻了 3 倍的。目前已经需要一个小时以上来完成打包了。这包还更新挺频繁的。
最关键的是 ArchLinuxCN 目前也还有 `vscodium-bin`，如果花这么长的时间只为了打包一个非 `-bin` 的包，我个人感觉不是很值得。

我会继续关注这个包，看看有没有别的方案来解决这个问题。

**Comment by hubutui** [comment]
反正是机器人打包，不用担心超时的问题啊，有必要的包就打呗。

**Comment by Y7n05h** [comment]
我手动打包了一下，花了近 2 hours 也没打包完成。确认是上游问题。等上游修复吧。https://github.com/VSCodium/vscodium/issues/1165
