### ISSUE TITLE
latte-dock-git: pkgver 格式修改

### ISSUE THREAD

**Issue by edward-p** [archlinuxcn/repo#2849]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* latte-dock-git

----

请在此补充说明。

0.10.9 发布后修改 pkgver()

**Comment by axionl** [comment]
mark

**Comment by axionl** [comment]
万万没想到一年过去都没发 0.10.9 版本，先关了
