### ISSUE TITLE
请认领nvchecker.ini中unknown下面的包

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#285]
如题
比如那个libpng12已经在community但是没人管了。。

- [x] acpi_call-pf
- [x] bbswitch-pf
- [x] beautifuldnsd
- [x] binfmt-wine
- [x] codecs64 @phoenixlzx 
- [ ] coq @fbq 
- [x] gcc-gcj
- [x] gcc-gcj-ecj
- [x] hydroxygen-iconset @phoenixlzx 
- [x] ld-lsb
- [x] lib32-libpng12
- [x] libpng12
- [x] newrelic-php5
- [x] newrelic-php53
- [x] newrelic-sysmond
- [x] nvidia-pf
- [x] openvpn-obfs
- [x] paraview
- [x] php53
- [x] php53-apc
- [x] php53-memcache
- [x] php53-memcached
- [x] php53-mongo
- [x] php53-xcache
- [x] pkgbuild-introspection-git 
- [ ] pycharm-professional @JiajunW 
- [x] python2-bjoern
- [x] python2-dict2xml
- [x] python2-gcm
- [x] python2-gevent-websocket
- [x] python2-newrelic
- [x] python2-pika
- [x] python2-py-bcrypt
- [x] python2-topia.termextract
- [x] python2-wand
- [ ] reaver-wps-svn @lilydjwg 
- [x] rubymine @ykelvis 
- [x] shadowvpn
- [x] sniproxy
- [ ] telegram-git @felixonmars 
- [ ] unarchiver @felixonmars 
- [x] uwsgi-plugin-php53
- [ ] nginx-subs @felixonmars 
- [ ] vim-minimal-with-x @fbq 

10月8日仍然unknown的我就都drop了

**Comment by petronny** [comment]
@hzy199411 认领一下nvidia-pf?

**Comment by hzy199411** [comment]
@petronny , 已经认领完成了.

**Comment by petronny** [comment]
@phoenixlzx @fbq @JiajunW @lilydjwg @ykelvis @felixonmars
各位再认领一下？

**Comment by felixonmars** [comment]
我昨天已经认领完成了 :)

**Comment by ykelvis** [comment]
原来rubymine在unknown下....已经改好啦

**Comment by lilydjwg** [comment]
reaver-wps-svn 是我的么……

**Comment by phoenixlzx** [comment]
最近忙飞了_(:з」∠) `codecs64` 和 `hydroxygen-iconset` 已经认领，希望我 nvchecker 没写错... (/ω＼)
