### ISSUE TITLE
rust-nightly: license issues

### ISSUE THREAD

**Issue by Y7n05h** [archlinuxcn/repo#2852]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* rust-nightly
* rustfmt-nightly
* cargo-nightly
* rust-clippy-nightly
* rust-analyzer-nightly
* rust-miri-nightly
* rust-src-nightly
* rust-docs-nightly
* rust-std-nightly-arm-unknown-linux-gnueabihf
* rust-std-nightly-armv7-unknown-linux-gnueabihf
* rust-std-nightly-x86_64-unknown-linux-gnu
* rust-std-nightly-i686-unknown-linux-gnu
* rust-std-nightly-i686-pc-windows-gnu
* rust-std-nightly-x86_64-pc-windows-gnu
* rust-std-nightly-wasm32-unknown-unknown
* rust-std-nightly-aarch64-linux-android
* rust-std-nightly-x86_64-unknown-linux-musl

----

根据 https://foundation.rust-lang.org/policies/logo-policy-and-media-guide/

> Distributing a modified version of the Rust programming language or the Cargo package manager, provided that the modifications are limited to:
> - porting the software to a different architecture
> - fixing local paths
> - adding patches that have been released upstream, or
> - adding patches that have been reported upstream, provided that the patch is removed if it is not accepted upstream

> Distributing a modified version of the Rust programming language or the Cargo package manager **with modifications other than those permitted above** and calling it Rust or Cargo requires explicit, written permission from the Rust Foundation. We will usually allow these uses as long as the modifications are (1) relatively small and (2) very clearly communicated to end-users.

我们从 Rust 官方发布的包含大量二进制文件的压缩包，选择性的打包部分文件的行为 **可能** 构成上述规则中禁止的 **modified** 行为。我们可能违反了 Rust 和 Cargo 的商标的 License。

**Comment by lilydjwg** [comment]
拆包应该不算吧？

**Comment by Y7n05h** [comment]
纯拆包大概不算。但有删掉一些内容，就不知道算不算了。不如和 Rust 基金会那边联系一下吧？他们在文档里说小修改会允许。

https://github.com/archlinuxcn/repo/blob/1cf8ea4292aaab2a56d39522391ceb46604f944d/archlinuxcn/rust-nightly/PKGBUILD#L112-L122

**Comment by CoelacanthusHex** [comment]
文档被拆进下面的包
下面的是c++标准库，不是 Rust 项目的一部分
唯一的问题就安装时用的脚本和元数据算不算 Rust 项目的一部分

**Comment by lilydjwg** [comment]
我觉得安装元数据、日志和卸载脚本应该属于安装过程中使用的文件。我们使用替代的安装方法，所以不需要这些文件。rustup 安装的也是没有这些文件的。

**Comment by lilydjwg** [comment]
我更新了一下，现在安装的文件更全面了： c368a63cd2ef326c84b1bfdcd2cb2f1d051001ec

**Comment by Y7n05h** [comment]
> 我更新了一下，现在安装的文件更全面了： [c368a63](https://github.com/archlinuxcn/repo/commit/c368a63cd2ef326c84b1bfdcd2cb2f1d051001ec)

辛苦啦～
