### ISSUE TITLE
fcitx5-git installs files into /usr/libexec

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#2853]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* fcitx5-git

----

/usr/libexec/fcitx5-wayland-launcher

**Comment by farseerfc** [comment]
fcitx5-git should be fixed in [88fc1e2](https://github.com/archlinuxcn/repo/commit/88fc1e2586ea0885cb102b8e25c9b20d8638dcdc)

**Comment by lilydjwg** [comment]
/usr/lib/fcitx5/libexec/comp-spell-dict 是在它自己的目录里边，Arch 那个打包标准应该不管的？

**Comment by farseerfc** [comment]
fixed
