### ISSUE TITLE
coredns: add aarch64 arch

### ISSUE THREAD

**Issue by SilverRainZ** [archlinuxcn/repo#2854]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

*  coredns

----

Hi @xuanwo, 我看 cn 源和 AUR 的 coredns 都是你在维护，能否加一个  `aarch64` 的架构？然后添加到 alarmcn 里面去呢？

**Comment by Xuanwo** [comment]
Hi, 已经把你添加为 AUR 包的维护者了，欢迎增加～

**Comment by Xuanwo** [comment]
BTW，我记得 coredns 包的架构很久之前已经被改成 any 了

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=coredns#n8

**Comment by SilverRainZ** [comment]
> Hi, 已经把你添加为 AUR 包的维护者了，欢迎增加～

感谢～

---

any 只适用于平台无关的架构 [1]：

> arch=('any') indicates the package can be built once on any architecture, and once built, is architecture-independent in its compiled state (shell scripts, fonts, themes, many types of extensions, etc.).

coredns 应该显式地列举所有能支持的架构  x86_64, aarch64, etc

---

我看 cn 源里的 lilac.yaml [2] 并没有追踪 AUR，且两者的 PKGBUILD [3] 已经分叉了，是否统一成一个呢？


[1] https://wiki.archlinux.org/title/PKGBUILD#arch
[2] https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/coredns/lilac.yaml#L7
[3] https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/coredns/PKGBUILD#L9

**Comment by SilverRainZ** [comment]
我个人是建议统一使用 AUR 的，毕竟我看 AUR 那边有另一个不在 cn 社区的维护者。

**Comment by SilverRainZ** [comment]
Done in https://github.com/archlinuxcn/repo/commit/fce3f2bbe3d03e1d0129cc8cc990355f834f39d0
