### ISSUE TITLE
`postman` 和 `postman-bin` 有什么区别

### ISSUE THREAD

**Issue by puzzle9** [archlinuxcn/repo#2855]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* `postman`
* `postman-bin`

----

一个是引用的在线网页版一个是用的官方包吗

**Comment by SilverRainZ** [comment]
postman-bin 和 AUR 同名包保持一致，而 postman 是 @BruceZhang1993 单独维护的。

从内容上看两者没有什么差距，postman 的打包更加规范一些，我会 drop 掉前者。

**Comment by puzzle9** [comment]
我发现 `postman` 引用的是 `electron` 这个组件，以至于在 `postman` 登录界面弹出需要用浏览器登录时候是进不去的，而 `postman-bin` 没这个问题。。。

**Comment by SilverRainZ** [comment]
> 我发现 `postman` 引用的是 `electron` 这个组件，以至于在 `postman` 登录界面弹出需要用浏览器登录时候是进不去的，而 `postman-bin` 没这个问题。。。

这个问题似乎在 https://github.com/archlinuxcn/repo/issues/2657 报告过，Bruce 说多等一会能进去，实际上是不可以的？

**Comment by puzzle9** [comment]
> > 我发现 `postman` 引用的是 `electron` 这个组件，以至于在 `postman` 登录界面弹出需要用浏览器登录时候是进不去的，而 `postman-bin` 没这个问题。。。
> 
> 这个问题似乎在 #2657 报告过，Bruce 说多等一会能进去，实际上是不可以的？

我等待了大概1分钟吧，没什么反映， 也可能确实因为这个神奇的网络吧， 而另一个包是直接可以进去的

**Comment by SilverRainZ** [comment]
> 我等待了大概1分钟吧，没什么反映， 也可能确实因为这个神奇的网络吧， 而另一个包是直接可以进去的

cc @BruceZhang1993

**Comment by BruceZhang1993** [comment]
我也改用 postman-bin 了，保留吧 @SilverRainZ 
postman 总是莫名其妙的问题，如果问题太多了就 drop 了

**Comment by SilverRainZ** [comment]
不然就 drop 掉 postman 吧？
