### ISSUE TITLE
请求将软件包hmcl更换至更稳定的上游分支

### ISSUE THREAD

**Issue by ngdngdc** [archlinuxcn/repo#2867]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* hmcl

----

archlinuxcn中打包的hmcl是基础功能不完善的快照版本，请求更换至开发版本或稳定版本。
[Manjaro下添加微软账户时无法拉起浏览器 #1615](https://github.com/huanghongxun/HMCL/issues/1615#issuecomment-1204877188)

**Comment by imlonghao** [comment]
使用微软账号登陆需要配置登陆相关的 appid 以及 appsecret，这边的 hmcl 是从源代码构建的，没有预设 appid，需要您启动时配置

例如，

```
hmcl -Dhmcl.microsoft.auth.id=<appid> -Dhmcl.microsoft.auth.secret=<secret>
```

**Comment by ngdngdc** [comment]
> 使用微软账号登陆需要配置登陆相关的 appid 以及 appsecret，这边的 hmcl 是从源代码构建的，没有预设 appid，需要您启动时配置
> 
> 例如，
> 
> ```
> hmcl -Dhmcl.microsoft.auth.id=<appid> -Dhmcl.microsoft.auth.secret=<secret>
> ```

所已不能换成从二进制文件构建吗？

**Comment by yuyichao** [comment]
https://github.com/archlinuxcn/repo/issues/2838
