### ISSUE TITLE
gnome-browser-connector 打包失败

### ISSUE THREAD

**Issue by q234rty** [archlinuxcn/repo#2869]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* gnome-browser-connector

----

目前 lilac 会在进入 devtools 安装依赖之前跑 `pkgver()` ，导致 gnome-browser-connector 打包失败。对于这个包来说 `pkgver()` 实际上是没有必要的（aur 更新的时候就会更新 pkgver），所以可以考虑直接删去。

**Comment by ykelvis** [comment]
aur上修了，变回了只用git
