### ISSUE TITLE
broadcom-wl-dkms out-of-date

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#287]
`broadcom-wl-dkms 6.30.223.271-9` is incompatible with linux 4.8.x ,  `6.30.223.271-10` ported a fix from debian bugtracker.

**Comment by farseerfc** [comment]
@felixonmars 肥貓要是忙的話我接手吧

**Comment by felixonmars** [comment]
吼，拜托 fc 前辈啦～

**Comment by farseerfc** [comment]
`6.30.223.271-10` 打包好了
