### ISSUE TITLE
wlroots-hidpi-git need additional patch to work properly

### ISSUE THREAD

**Issue by AngeloChen14** [archlinuxcn/repo#2871]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* wlroots-hidpi-git
----

请在此补充说明。
Please describe in detail here.
According to this [aur comment](https://aur.archlinux.org/packages/wlroots-hidpi-git#comment-871925) and real test, `wlroots-hidpi-git` needs reverting commit 18595000f3a21502fd60bf213122859cc348f9af to work properly with some application (fcitx5, Android Studio, etc.)

**Comment by PeterCxy** [comment]
Patch added.
