### ISSUE TITLE
Dropping qtwebkit ?

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#2874]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* qtwebkit

----

qtwebkit 已经在2013年就被上游弃置了，AUR 上这个包也从18年起就基本没有维护了

qt 貌似从 qt5 开始捡了一份 webkit ，就是现在的 qt5-webkit

查了一下，源里也没有依赖这个包的

https://lists.webkit.org/pipermail/webkit-qt/2013-October/003878.html

**Comment by yuyichao** [comment]
从上游移除的 qt 支持应该已经说的是 qt5 的版本了, qtwebkit 这个包是 qt4 的. 跟从上游移除不移除没有什么直接的关系.

**Comment by petronny** [comment]
webkit 时代的 qtwebkit 就已经扔掉 qt4 支持了：
https://trac.webkit.org/wiki/BuildingQtOnLinux?action=diff&version=75&old_version=74

webkit 在自己的 wiki 上也做了弃置 qt port 的声明：
https://trac.webkit.org/wiki/BuildingQtOnLinux#READMEFIRST

总之现在完全不存在有 qt4 支持的 webkit 的上游。

**Comment by yuyichao** [comment]
我说的意思就是这些上游的变化都跟qtwebkit这个包没有任何关系。 qtwebkit是qt4里面的版本，跟上游有没有弃置qt5没有关系。

> 总之现在完全不存在有 qt4 支持的 webkit 的上游。

这个的意思跟说已经没有受支持的qt4上游是一样的。我并不是说这个包一定不能丢掉，如果没有人想用/维护者不想继续维护，丢掉它当然是没有问题的。但不过作为一个本来就是因为qt4停止支持而加到cn仓库的包，用上游之不支持来判断实在是没啥意义。。。

**Comment by petronny** [comment]
那就如果还有需要这个包的就留言吧

**Comment by ykelvis** [comment]
好像过了15天（没有被lilac移除），我应该remove assign吗..

**Comment by petronny** [comment]
在这多等会儿吧，我的想法是1个月以后还没回复就扔，不过决定权还是在你。

**Comment by oldherl** [comment]
ping

**Comment by ykelvis** [comment]
删了，这里也关了吧
