### ISSUE TITLE
python-nvidia-dali has bug

### ISSUE THREAD

**Issue by Freed-Wu** [archlinuxcn/repo#2877]
### 问题类型 / Type of issues

<https://github.com/NVIDIA/DALI/issues/4145> has a code snippet to reproduce the bug.

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

* python-nvidia-dali

**Comment by hubutui** [comment]
Could you rebuild it and try again?

**Comment by Freed-Wu** [comment]
Yes.

The step to reproduce:

1. `sudo pacman -S python-nvidia-dali`
2. Try <https://github.com/NVIDIA/DALI/issues/4145#issuecomment-1208986473>

**Comment by hubutui** [comment]
I check https://github.com/NVIDIA/DALI/issues/4145#issuecomment-1208986473, but still not sure how to reproduce it.

**Comment by Freed-Wu** [comment]
I have reedited <https://github.com/archlinuxcn/repo/issues/2877#issuecomment-1211548931>. Thanks!

**Comment by hubutui** [comment]
Maybe we need to rewrite the PKGBUILD according to [the doc](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html). Would you like to create a pull request?

**Comment by Freed-Wu** [comment]
> 也许我们需要根据 [文档 ](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html)。 您要创建拉取请求吗？

When I have free time, I am glad to do some little work:smile:

**Comment by hubutui** [comment]
I have tried it, replace the current cmake opts according to the doc, still no work. I have no idea how to fix it.

**Comment by Freed-Wu** [comment]
> I have tried it, replace the current cmake opts according to the doc, still no work. I have no idea how to fix it.

Can I take a look at your change?

**Comment by hubutui** [comment]
[PKGBUILD.txt](https://github.com/archlinuxcn/repo/files/9312952/PKGBUILD.txt)

**Comment by yan12125** [comment]
> `/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/c++/bits/stl_vector.h:1063: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = long int; _Alloc = std::allocator<long int>; std::vector<_Tp, _Alloc>::const_reference = const long int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.`

From the assertion message, this issue seems another case of https://github.com/archlinuxcn/repo/discussions/2815. Check `_GLIBCXX_ASSERTIONS` there for more details.
