### ISSUE TITLE
chromium-dev now has vaapi enabled by default (chromium-dev-vaapi may be unecessary?)

### ISSUE THREAD

**Issue by BigEars431** [archlinuxcn/repo#288]
Hi, 

I noticed that the package chromium-dev-vaapi was made due to how you have to manually edit the PKGBUILD for the chromium-dev snapshot 55.0.2873-4-1 because the argument "_patch_vaapi" was set to 0 instead of 1; however; it looks like in 55.0.2882.4-1,the vaapi patch has been enabled by default again, because the argument "_patch_vaapi" is absent in the PKGBUILD and yes chromium-dev is out-of-date in the repo =))

EDIT: vaapi seems to be enabled by default because of this reply by the package author, sl1pkn07 to user prazola

-----------------------------------------------------------------------------------------

**prazola**
Still software only in chrome:gpu for me. :(

**sl1pkn07**
nvidia user? install 'libva-vdpau-driver-chromium'

------------------------------------------------------------------------------------------

Thank you again for the continual maintenance of this repository =))

Much appreciated,
Kyle Javier

**Comment by fqj1994** [comment]
Updated chromium-dev.
chromium-dev-vaapi pending removal.
