### ISSUE TITLE
Orphaning android-*-strace

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#2881]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* android-aarch64-strace
* android-x86-64-strace
----

Building is often broken for new versions of strace. I seldom use them recently, either.

**Comment by yan12125** [comment]
I orphaned both packages on AUR. However, lilac now becomes the maintainer - filed orphan requests.

**Comment by lilydjwg** [comment]
lilac has disowned these packages.

**Comment by yan12125** [comment]
Nice, thanks!
