### ISSUE TITLE
wob软件增加`config`功能

### ISSUE THREAD

**Issue by nsfoxer** [archlinuxcn/repo#2882]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* wob

----
wob软件，来源 https://github.com/francma/wob ，github当前版本支持config配置，即允许`wob -c`参数，指定配置路径。当前`archlinuxcn`库并不支持配置文件读取，希望可以增加该功能。

软件详情：
![图片](https://user-images.githubusercontent.com/32675834/184796348-a7ef3248-169d-4e29-9d6f-85e3713d72cf.png)

**Comment by SilverRainZ** [comment]
cn 源中的 wob 是稳定版，`wob -c` 的支持在 0.13 里包含了么？如果没有的话请要求上游发布新版本。

**Comment by nsfoxer** [comment]
抱歉，没有细看。在`0,13`版本中，的确没有支持

**Comment by SilverRainZ** [comment]
wob 没有兼容旧选项，升级后被 [坑](https://github.com/SilverRainZ/dotfiles/commit/ce74e23ab9a390d90ddb73246c3a5e7ed85f15a7) 了一把，原来在这个时候就挖下了 :joy:

**Comment by lilydjwg** [comment]
我也被这个坑过。
