### ISSUE TITLE
软件打包请求：clash-verge-bin和clash-for-windows-chinese

### ISSUE THREAD

**Issue by xiaozixun** [archlinuxcn/repo#2885]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

  两个都是Clash的GUI

* 主要语言和工具链 / Main Languages and Toolchains

    前者（clash-verge-bin）：tauri
    后者（clash-for-windows-chinese）：Electron

* 上游链接 / Upstream Link

    clash-verge-bin：https://github.com/zzzgydi/clash-verge 和 https://aur.archlinux.org/packages/clash-verge-bin

    clash-for-windows-chinese：https://github.com/Fndroid/clash_for_windows_pkg https://github.com/BoyceLig/Clash_Chinese_Patch 和 https://aur.archlinux.org/packages/clash-for-windows-chinese

* 为何需要这个软件包 / Why Need This Package

    v2ray因为不像clash一样可以自动切换节点，导致其对速度不佳的vpn一直不甚如人意；而现有的cn源中的clash都无图形操作界面，配置不如有GUI的方便。
    所以希望能够加入。

**Comment by HowardZorn** [comment]
我觉得 clash-for-windows 和 clash-for-windows-chinese-translation 应该分开打包。
clash-for-windows的AUR地址: https://aur.archlinux.org/packages/clash-for-windows-bin

**Comment by SilverRainZ** [comment]
:joy: Clash for windows 居然支持 Linux 么

**Comment by SilverRainZ** [comment]
后者不开源，前者只有一个 bin 包，有人愿意写个基于源码构建的 PKGBUILD 么？
