### ISSUE TITLE
wine-wechat-setup 安装的微信无法通过设置dpi来缩放

### ISSUE THREAD

**Issue by devome** [archlinuxcn/repo#2899]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* wine-wechat-setup

----
使用的桌面是plasma。

archlinuxcn/wine-for-wechat版本升级到7.16-1出现的问题，在7.15-1时无此问题。

当通过“wine 微信配置”修改显示DPI为144后，再次打开“wine 微信配置”就变成下图这个样子了，此时移动这个窗口，窗口会随着移动越变越小：

![image](https://user-images.githubusercontent.com/93664269/187895770-1c3ce583-c195-47b3-b008-a773f3497358.png)

此时打开“wine 微信”只能看见一个黑色的方块在桌面，并且此时该方块无法选中：

![image](https://user-images.githubusercontent.com/93664269/187896022-125ee2c7-7d69-44c1-926a-abeded821ec6.png)

删除`~/.local/lib/wine-wechat`后重新安装微信，保持默认的96DPI可以正常打开微信。

**Comment by hubutui** [comment]
是的，我也发现了。我还以为我自己的出错l额，然后删掉了微信的目录，聊天记录也没了。

**Comment by lilydjwg** [comment]
直接使用全新的 wine 环境亦能复现。请向 wine 上游报告问题。

**Comment by devome** [comment]
> 直接使用全新的 wine 环境亦能复现，不是 wine 微信独有的问题。请向 wine 上游报告问题。

好吧

**Comment by q234rty** [comment]
据称 wine-for-wechat 7.16-2 已经修复了这个问题？

**Comment by lilydjwg** [comment]
是的，肥猫 backport 了上游的补丁。
