### ISSUE TITLE
litecli  is out of date

### ISSUE THREAD

**Issue by sdvcrx** [archlinuxcn/repo#2906]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* litecli

----

**Comment by masakichi** [comment]
Hello @sdvcrx 
A new version(1.9.0-1) of `litecli` has been built successfully, let me close this issue.
sorry for the inconvenience.

ref: https://build.archlinuxcn.org/packages/#/litecli
