### ISSUE TITLE
qv2ray无法使用

### ISSUE THREAD

**Issue by qxqzx3489** [archlinuxcn/repo#2920]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

*qv2ray-dev-git

打不开

![Screenshot_20220923_192924](https://user-images.githubusercontent.com/45313133/191951013-fcc367c9-e379-40a2-bbc3-7baff8c09491.png)

软件均是最新版

**Comment by Y7n05h** [comment]
这并不是一个打包错误。请向上游反馈。
