### ISSUE TITLE
cgproxy-git 因为 libbpf.so 的 soname bump 需要 rebuild

### ISSUE THREAD

**Issue by unknowndevQwQ** [archlinuxcn/repo#2945]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* cgproxy-git

----

libbpf 更新到 1.0 后再使用 cgorpxy 会在日志中看到以下内容
```
10月 13 14:21:25 arch cgproxyd[1947]: info: loading /usr/lib/cgproxy/libexecsnoop.so
10月 13 14:21:25 arch cgproxyd[1947]: error: dlopen /usr/lib/cgproxy/libexecsnoop.so failed: libbpf.so.0: cannot open shared object file: No such file or directory
10月 13 14:21:25 arch cgproxyd[1947]: error: execsnoop not ready to start, maybe missing libbpf
```
这会导致 cgproxy 根据进程绕过代理的功能不按预期工作

**Comment by sihuan** [comment]
abd54c1b140c471976a1d9909e9b86c1a53ddea3

**Comment by CoelacanthusHex** [comment]
> [abd54c1](https://github.com/archlinuxcn/repo/commit/abd54c1b140c471976a1d9909e9b86c1a53ddea3)

还需要打个 patch 才能正常编译 https://github.com/springzfx/cgproxy/pull/47

**Comment by sihuan** [comment]
> > [abd54c1](https://github.com/archlinuxcn/repo/commit/abd54c1b140c471976a1d9909e9b86c1a53ddea3)
> 
> 还需要打个 patch 才能正常编译 [springzfx/cgproxy#47](https://github.com/springzfx/cgproxy/pull/47)

现在打上这个 patch 了，lilac 那边已经打出包了😀

**Comment by black-desk** [comment]
这个当patch维护是不是, patch得有点大(
