### ISSUE TITLE
So every time when clang and llvm-libs get updated then ycm's dependencies will be broke...

### ISSUE THREAD

**Issue by Universebenzene** [archlinuxcn/repo#295]
Last time was #257 , and now llvm-libs and clang are going to update to 3.9.0-1. then...
error: failed to prepare transaction (could not satisfy dependencies)
:: vim-youcompleteme-git: installing clang (3.9.0-1) breaks dependency 'clang=3.8.1'
Maybe it's time for update the dependencies again...

**Comment by lilydjwg** [comment]
要加紧开发 trigger 功能了……

**Comment by zsrkmyn** [comment]
Thanks for reporting, I'll update it later.

**Comment by Universebenzene** [comment]
突然發現我語法錯誤連篇……

**Comment by Universebenzene** [comment]
……clang居然又更新了……@zsrkmyn
