### ISSUE TITLE
arm-linux-gnueabihf-gcc 软件包中未包含静态库 libstdc++.a

### ISSUE THREAD

**Issue by Donlon** [archlinuxcn/repo#2956]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* `arm-linux-gnueabihf-gcc`

----

`arm-linux-gnueabihf-gcc` 软件包中未包含静态库 `libstdc++.a`，这让交叉编译易于分发的静态编译产物变得困难。

与此相比，Arch Linux 仓库中的 `aarch64-linux-gnu-gcc` 软件包包含该静态库。
```
$ pacman -Ql aarch64-linux-gnu-gcc | grep 'libstdc++.a'
aarch64-linux-gnu-gcc /usr/aarch64-linux-gnu/lib64/libstdc++.a
```

**Comment by yuyichao** [comment]
拆包删东西删多了 ...
