### ISSUE TITLE
chromium-dev-vaapi

### ISSUE THREAD

**Issue by BigEars431** [archlinuxcn/repo#296]
may I humbly request for chromium-dev with the vaapi patch enabled, to be available in the repo? the patch is not enabled by default anymore in PKGBUILD the line "_enable_vaapi" has to be set to 1. It takes too long to compile on my laptop =(( you guys would really help =)

**Comment by petronny** [comment]
@fqj1994 Please add a lilac.py for chromium-dev and set `_enable_vaapi` to 1

**Comment by fqj1994** [comment]
... the aur maintainer added _enable_vaapi back again.....................
It was _patch_vaapi and then removed, and now _enable_vaapi ..

building at my place. should take 30 mintues or so.

**Comment by fqj1994** [comment]
When it was done, it will show up in archlinuxcn repo as chromium-dev-vaapi. You can use this to replace archlinuxcn chromium-dev.
