### ISSUE TITLE
Orphaning pnmixer-gtk3

### ISSUE THREAD

**Issue by SilverRainZ** [archlinuxcn/repo#2970]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* pnmixer-gtk3

----

PNMixer does not support Wayland (https://github.com/nicklan/pnmixer/issues/190) so I no longer use it.

**Comment by anarcat** [comment]
i'm curious: do you have an alternative tray you use instead?

**Comment by SilverRainZ** [comment]
I only use pnmixer's volume adjustment function, on Wayland, I use [waybar](https://github.com/Alexays/Waybar) to have a tray for displaying the current volume and media keys for volume adjustment (bind by sway).

**Comment by anarcat** [comment]
oh that's fascinating, i also use waybar! but i am not a fan of the modules I put there, so I was looking for alternatives. i found [pasystray](https://github.com/christophgysin/pasystray) which also doubles as a notification daemon which is really nice, so I'll probably switch to that. otherwise I'm curious: what is your waybar configuration?

**Comment by anarcat** [comment]
interesting, mine looks like:

```
    "pulseaudio": {
        // "scroll-step": 1, // %, can be a float
        "format": "{volume}% {icon} {format_source}",
        "format-bluetooth": "{volume}% {icon} {format_source}",
        "format-bluetooth-muted": " {icon} {format_source}",
        "format-muted": " {format_source}",
        "format-source": "{volume}% ",
        "format-source-muted": "{volume}% ",
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", "", ""]
        },
        "max-volume": 150,
        "on-click": "i3-pa-mixer.py mute-mic",
        "on-click-right": "pavucontrol"
    }
```

maybe i should look at wireplumber instead!

i find that having a bar item just for volume, permanently present, is kind of silly. i really like the "pop up on state change" and "mouse-over on icon to change" UI instead...

**Comment by SilverRainZ** [comment]
you might need wob (or any other similar project)? it will pop up a progress bar when the volume changes. Of course, you need some configuration: https://github.com/SilverRainZ/dotfiles/blob/master/.config/sway/config#L315

**Comment by anarcat** [comment]
yeah nah... not a fan of those socket-based approaches, because then you need to hook up *everything* onto this. i prefer to have daemons reacting to dbus events that push standard notifications instead, which is how poweralertd and pasystray work...
