### ISSUE TITLE
numix-circle-icon-theme-git, numix-icon-theme-git are broken

### ISSUE THREAD

**Issue by bianjp** [archlinuxcn/repo#298]
Package `numix-circle-icon-theme-git` and `numix-icon-theme-git` seem broken. Pacman cannot find them.

**Comment by colinkeenan** [comment]
Thanks for letting me know. I rebuilt both packages and uploaded them to build.archlinuxcn.org:repo. I don't know what was wrong with the previous build that got it removed, but it should be working again within an hour.

**Comment by lilydjwg** [comment]
You uploaded:

* numix-circle-icon-theme-git-0.r12.bcd1317-1-any.pkg.tar.xz
* numix-icon-theme-git-0.r1888.e03eb71-1-any.pkg.tar.xz

On server:

* numix-circle-icon-theme-git-0.r3552.565ecfd-1-any.pkg.tar.xz
* numix-circle-icon-theme-git-0.r3564.ae60cea-1-any.pkg.tar.xz
* numix-icon-theme-git-0.r1918.a0a7548-1-any.pkg.tar.xz
* numix-icon-theme-git-0.r1974.294ec8e-1-any.pkg.tar.xz

The versions you uploaded are older, and [the cleanup script](https://github.com/archlinuxcn/misc_scripts/blob/master/repocleaner) will only keep two latest versions (by its version string, not by date).

Should I remove those "newer versions" for you?

**Comment by colinkeenan** [comment]
Yes. Please do. 

I don't know why the version counting isn't working right. I deleted the old, downloaded from AUR and built just before uploading. What I just uploaded is the newest possible.

**Comment by lilydjwg** [comment]
I've removed them. Next time if you find the version strings go backwards, you can increase "epoch" so version comparison will still work.

**Comment by colinkeenan** [comment]
Ok. I'm not sure how to discover it other than somebody noticing the package is missing after the cleanup script does it's job.
