### ISSUE TITLE
{paraview, cgns} out-of-date

### ISSUE THREAD

**Issue by panda-z** [archlinuxcn/repo#301]
paraview: 5.0.1-1 -> 5.2
cgns: 3.2.1-1 -> 3.3.0-2

**Comment by petronny** [comment]
Please inform the maintainers of these 2 pkgs on AUR.
PS. paraview is already marked out of date, but please add a new comment to inform the maintainer again.

**Comment by petronny** [comment]
cgns has been updated by 9397b60abb40f4

@hzy199411 paraview的aur上游更新了
另外你可以考虑为这两个包添加lilac.py这样下次aur上游更新的时候就不用手动更新了

**Comment by hzy199411** [comment]
@petronny ,谢谢提醒,正在编译中.

**Comment by petronny** [comment]
cgns has been updated by ad25b82bf611cf6bfee572a04ec065e0513689ac
