### ISSUE TITLE
"downgrade" & "dropbox" are out of date

### ISSUE THREAD

**Issue by francistw** [archlinuxcn/repo#302]
New version:
downgrade 5.3.1-1
dropbox 14.4.19-1
By the way, dropbox has not been updated for months. I wonder whether the maintainer could write an autoupdate script or not. Thank you!

**Comment by petronny** [comment]
Updated in 
0c289f20435a1058be6cdd3f54e383eab2dfdd52
and
3266b2bb09fd747655902589a8a55fc323ea1e0c
