### ISSUE TITLE
ydcv-rs-git need libssl.so.1 which is outdated

### ISSUE THREAD

**Issue by Freed-Wu** [archlinuxcn/repo#3030]
### 问题类型 / Type of issues

* 打包错误 / packaging error
```
❯ sudo pacman -S ydcv-rs-git
❯ ydcv --help
ydcv: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----

请在此补充说明。
Please describe in detail here.

**Comment by q234rty** [comment]
已经在 #3014 中包含。
