### ISSUE TITLE
ttf-plangothic 建议用 release 里的 ttf 打包，而非用 tarball 打包

### ISSUE THREAD

**Issue by huyz-git** [archlinuxcn/repo#3039]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  ttf-plangothic

----

如图，上游发版的时候，tarball 有可能没有及时更新
![image](https://user-images.githubusercontent.com/22879638/202847890-bdafcadc-b137-4dee-a29c-c5e99dfbe1e3.png)

**Comment by CoelacanthusHex** [comment]
什么鬼，怎么 release 和 tag 还能差一个星期的
