### ISSUE TITLE
maddy 打包错误

### ISSUE THREAD

**Issue by linsein** [archlinuxcn/repo#3043]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* maddy
----

本地尝试编译错误日志截取如下
```
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat 'build/maddyctl': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
```

### 问题原因分析
maddy 开发者去掉了 `maddyctl` 指令，已经将其和 `maddy` 指令合并，故尝试 `install` 时因不存在而失败报错。  

如果从 maddy 提供的 [第三方源](https://maddy.email/archlinux/) 中安装，`maddyctl` 指令仅为 `/usr/bin/maddy` 的软链接。

**Comment by axionl** [comment]
https://github.com/archlinuxcn/repo/commit/46dba16f27fa187aa40788759c5e7133c68b654a 看看修好没
