### ISSUE TITLE
[package-requests] qt5-webkit, python-pyqt5-webkit

### ISSUE THREAD

**Issue by Universebenzene** [archlinuxcn/repo#3046]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    qt5-webkit
    python-pyqt5-webkit

* 主要语言和工具链 / Main Languages and Toolchains

    * Qt
    * Python

* 上游链接 / Upstream Link

    https://github.com/qtwebkit/qtwebkit
    https://aur.archlinux.org/packages/qt5-webkit

    https://riverbankcomputing.com/software/pyqt/intro
    https://aur.archlinux.org/packages/python-pyqt5-webkit

* 为何需要这个软件包 / Why Need This Package

   官方仓库已移除qt5-webkit包，但cn源里的[goldendict-git](https://github.com/archlinuxcn/repo/blob/e57544e2aa5a7a4708cdc6d96d55c1f10f4fd103/archlinuxcn/goldendict-git/PKGBUILD#L15)仍依赖此包。且qtwebkit编译相当花时间，本地自己从AUR build实在太费劲了，希望cn源能一起打包

   另一个包[python-pyqt5-webkit]( https://aur.archlinux.org/packages/python-pyqt5-webkit)实际上就是官方仓库在移除了pyqt5的webkit支持后在AUR重新把webkit支持添加回来的包。主要是有些软件依赖 `PyQt5.QtWebKit` 相关的模块，因此官方移除之后就不能用了。pyqt5也是个烧编译的大包，希望cn也源能帮忙打一个

**Comment by ykelvis** [comment]
67c5a3d9713eb7d1f32e1088ce1923f6bbe9abff 5d8e5fd11a34ead3a1d3ed19619d0927be2e493f 都有了
