### ISSUE TITLE
Invalid or corrupted package on steamdeck.

### ISSUE THREAD

**Issue by gylove1994** [archlinuxcn/repo#3047]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* archlinuxcn-keyring

----

When I try to install archlinuxcn-keyring to my steamdeck, it seems to have some problem here.

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/47300853/204160155-601af376-49f9-4216-901d-333d0030edb6.png">

### some info:

<img width="753" alt="image" src="https://user-images.githubusercontent.com/47300853/204160049-cc3762f6-a302-4fb3-acbb-cf0fb8791550.png">

<img width="837" alt="image" src="https://user-images.githubusercontent.com/47300853/204160257-310990bb-20f0-459b-9076-38f6f110e26e.png">

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/47300853/204160476-4935049b-17ba-4705-a7c7-f8189e53c710.png">

**Comment by gylove1994** [comment]
related issue: #430

**Comment by lilydjwg** [comment]
The `archlinux-keyring` is still version `20220125` which is too old. You can manually import and `--lsign` the key, but our repo is built again latest Arch. You may find a lot of required library files missing.

**Comment by gylove1994** [comment]
A way to avoid it is by adding ``SigLevel = Optional TrustAll``
<img width="516" alt="image" src="https://user-images.githubusercontent.com/47300853/204686302-3204a1ba-4356-4e38-a8ab-4be4eb88b96e.png">
But it may cause some security Issues.
