### ISSUE TITLE
neovim-coc的版本号错了

### ISSUE THREAD

**Issue by cnjhb** [archlinuxcn/repo#3053]
### 问题类型 / Type of issues
* 打包错误 / packaging error
### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* neovim-coc

----

请在此补充说明。
Please describe in detail here.
虽然包的版本号是0.0.82但是实际上是0.0.81
aur上同版本号的neovim-coc-bin没有问题

**Comment by yan12125** [comment]
這個包是跟隨 https://aur.archlinux.org/packages/neovim-coc ，請問能否到那邊反應？

**Comment by cnjhb** [comment]
> 這個包是跟隨 https://aur.archlinux.org/packages/neovim-coc ，請問能否到那邊反應？

我已经在那个包下评论了，这样就可以了吧？

**Comment by yan12125** [comment]
謝謝。等 AUR 包更新，這邊的包也會跟著更新。
