### ISSUE TITLE
zeronet 权限问题

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#306]
1. 代码目录 /opt/zeronet 由 zeronet 用户所有，可能通过漏洞被修改，从来执行任意代码
2. /opt/zeronet 里的 .py 文件没有预先编译（python2 -m compileall /opt/zeronet）

另外建议启用 systemd 对于 /usr、/home、/tmp 等的保护机制。

**Comment by lilydjwg** [comment]
哦还有，

```
StandardOutput=/dev/null
StandardError=/dev/null
```

是不对的。它们的值应该是 `null`。

**Comment by lilydjwg** [comment]
```ini
PrivateTmp=true
PrivateDevices=true
ProtectSystem=full
ProtectHome=true
NoNewPrivileges=true
CapabilityBoundingSet=
```

**Comment by farseerfc** [comment]
這樣可以了麼 https://github.com/archlinuxcn/repo/compare/02ae6b932dddaa0b9fe1a3f34256105ce3dfa03e...37aea251221e3769a305232a64bc136ae6ae7c9a

**Comment by lilydjwg** [comment]
还需要调整：

```
Server error
Err: IOError: [Errno 2] No such file or directory: 'src/Ui/template/wrapper.html' in UiServer.py line 81 > UiRequest.py line 82 > UiRequest.py line 209 > UiRequest.py line 289 > UiRequest.py line 167
```

**Comment by farseerfc** [comment]
百合這個報錯是哪兒看到的呀，爲什麼我這兒沒報錯

**Comment by lilydjwg** [comment]
网页上。你卸载干净之后再安装呢？

**Comment by farseerfc** [comment]
我卸載了然後刪了 /var/log/zeronet 和 /var/lib/zeronet 然後還是正常的唔

**Comment by lilydjwg** [comment]
我这里好像也正常了……

**Comment by leeolliet** [comment]
怎么搞

**Comment by ttlygw2018** [comment]
服务器错误
Err：IOError：[Errno 5] UiServer.py中的I / O错误第95行> UiRequest.py行130> MutePlugin.py行137> SiteManagerPlugin.py行71> SiteManagerPlugin.py行46> SiteStorage.py行294> __init__ .py第274行

**Comment by farseerfc** [comment]
剛剛打包了 zeronet 0.6.1 歡迎測試。
直接 `systemctl start zeronet` 然後瀏覽器打開 http://localhost:43110/ 應該就能用了，還有問題請開新 issue 。

**Comment by ttlygw2018** [comment]
Thank you!!

2018/2/3 下午6:15，"Jiachen Yang" <notifications@github.com>寫道：
