### ISSUE TITLE
deadbeef 可以使用 ffmpeg 5 

### ISSUE THREAD

**Issue by q234rty** [archlinuxcn/repo#3061]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* deadbeef
* deadbeef-git

----
根据 https://github.com/DeaDBeeF-Player/deadbeef/pull/2861 来看 deadbeef 的 ffmpeg 插件已经兼容 ffmpeg 5，aur 上 https://aur.archlinux.org/cgit/aur.git/commit/?h=deadbeef&id=286002a62dc54215e69252b857e0de1848e51f63 也已经切换回 ffmpeg 5。

**Comment by heavysink** [comment]
Done
