### ISSUE TITLE
clash-geoip 更新之后内容没有改变

### ISSUE THREAD

**Issue by q234rty** [archlinuxcn/repo#3083]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* clash-geoip

----

clash-geoip 20221212-1 内含的 `Country.mmdb` 文件和 20221112-1 完全一致，原因是 `source`  中文件名没有包含实际版本。

**Comment by hubutui** [comment]
我记得好像打包检查可以检查到source tarball的名字不够unique的问题的来着？
