### ISSUE TITLE
python-pypdf2 should follow 2.x branch

### ISSUE THREAD

**Issue by duament** [archlinuxcn/repo#3092]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* python-pypdf2
* python-camelot

----

`python-pypdf2` has been updated to 3.2.0.

It results in `camelot` failing to import `PyPDF2`.

**Comment by hubutui** [comment]
According to https://github.com/py-pdf/pypdf/issues/1488, `PyPDF2` is renamed back to `pypdf`. Did this cause the error? Maybe you could report to the camelot upstream.

**Comment by hubutui** [comment]
See also https://github.com/camelot-dev/camelot/issues/339, does this https://github.com/camelot-dev/camelot/pull/307 fix it?

**Comment by duament** [comment]
That rename in pypdf 3.1.0 breaks `import PyPDF2`. https://github.com/camelot-dev/camelot/pull/307 does not fix it.

And PyPDF2 on [PyPi](https://pypi.org/project/PyPDF2/) noted `PyPDF2==3.0.X will be the last version of PyPDF2`.

**Comment by hubutui** [comment]
hmmm, maybe we could add another pkg, `python-pypdf`, and keep `python-pypdf2` to `3.0.1` from PyPi?

**Comment by duament** [comment]
> hmmm, maybe we could add another pkg, `python-pypdf`, and keep `python-pypdf2` to `3.0.1` from PyPi?

It might be the best option until someone ports camelot to the new pypdf.

**Comment by hubutui** [comment]
@duament Could you check if this https://github.com/archlinuxcn/repo/commit/22de344406efd9c18fd75ca559f8d3a47c17f2c3 works?

**Comment by duament** [comment]
```
>>> import camelot
>>> camelot.read_pdf('/tmp/test.pdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/camelot/io.py", line 113, in read_pdf
    tables = p.parse(
  File "/usr/lib/python3.10/site-packages/camelot/handlers.py", line 172, in parse
    self._save_page(self.filepath, p, tempdir)
  File "/usr/lib/python3.10/site-packages/camelot/handlers.py", line 112, in _save_page
    if infile.isEncrypted:
  File "/usr/lib/python3.10/site-packages/pypdf/_reader.py", line 1955, in isEncrypted
    deprecation_with_replacement("isEncrypted", "is_encrypted", "3.0.0")
  File "/usr/lib/python3.10/site-packages/pypdf/_utils.py", line 369, in deprecation_with_replacement
    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))
  File "/usr/lib/python3.10/site-packages/pypdf/_utils.py", line 351, in deprecation
    raise DeprecationError(msg)
pypdf.errors.DeprecationError: isEncrypted is deprecated and was removed in pypdf 3.0.0. Use is_encrypted instead.
```

**Comment by hubutui** [comment]
ok, it seems we need `python-pypdf2`.

**Comment by duament** [comment]
I replaced that `isEncrypted` with `is_encrypted`. And now it works.

**Comment by hubutui** [comment]
Ok, I add `python-pypdf`, and keep `python-pypdf2` to the legacy 2.12.1 release.
`python-camelot` now depends on `python-pypdf` with this patch: https://github.com/camelot-dev/camelot/pull/307.
It should work as expected now.
