### ISSUE TITLE
emacs-git 开启 tree-sitter

### ISSUE THREAD

**Issue by condy0919** [archlinuxcn/repo#3094]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* emacs-git

----

如果系统存在 tree-sitter 包，那么编译 emacs-git 就会自动开启 tree-sitter 集成功能，这样也就可以使用它来 font-locking. 对于其他不使用 tree-sitter 的用户也不会爱影响。

**Comment by ykelvis** [comment]
pull request里面是makedepends，但是aur上面可是直接的depends，前者可考虑加入（就像上面说的不影响现状）。如果真是makedepends而不是强制依赖，建议也同时提交给aur。

**Comment by condy0919** [comment]
:sob: 原来 aur 上已经支持 tree-sitter 了，我再改一下对应的 patch.

**Comment by noalias** [comment]
请问下，卫什么`emacs-native-comp-pgtk-git`这个包不支持`tree-sitter`啊？

**Comment by ykelvis** [comment]
@noalias 因为一般是不开不相关的新特性的，怕break掉正常使用（见隔壁pgtk的issue）。

但是我看了一下文档是需要配置里面用到tree-sitter才会启用，否则不会影响（多了一个安装依赖虽然比较hmm），而且看起来tree-sitter也是被很多人期待的新东西，灵活一点来讲先开起来吧（希望不要搞出问题...）

PR那个只是emacs-git的，emacs-native-comp-git和emacs-native-comp-pgtk-git的我晚上弄。
