### ISSUE TITLE
nerd-fonts-hack: 与`community/ttf-hack-nerd`重复

### ISSUE THREAD

**Issue by wszqkzqk** [archlinuxcn/repo#3106]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* nerd-fonts-hack
----

`archlinuxcn/nerd-fonts-hack`与`community/ttf-hack-nerd`重复

**Comment by SilverRainZ** [comment]
包名没有冲突，感觉不会引发什么问题。

nerd-fonts-hack 是从一个 pkgbase nerd-fonts 打出来的，pkgbase 还包含了很多 commuinty 没有的变种，所以感觉单独去掉重复的几个意义也不大。
