### ISSUE TITLE
bilibili-bin 打包请求

### ISSUE THREAD

**Issue by xiao-k233** [archlinuxcn/repo#3110]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    bilibili官方客户端的linux移植版

* 主要语言和工具链 / Main Languages and Toolchains

    electron，JavaScript

* 上游链接 / Upstream Link

    github:[here](https://github.com/msojocs/bilibili-linux)
    aur:[here](https://aur.archlinux.org/packages/bilibili-bin)
* 为何需要这个软件包 / Why Need This Package

    国内用户在ArchLinux下观看bilibili使用

**Comment by hubutui** [comment]
bilibili 官方客户端有 Linux 版本了？

**Comment by xiao-k233** [comment]
> bilibili 官方客户端有 Linux 版本了？

这个是社区移植的

**Comment by oldherl** [comment]
一边说自己是 MIT License，一边又说

> 本项目旨在交流学习之用，请使用者在下载后24小时内删除相关程序。

这项目看起来不能够在 archcn 中分发。

**Comment by xiao-k233** [comment]
> 一边说自己是 MIT License，一边又说
> 
> > 本项目旨在交流学习之用，请使用者在下载后24小时内删除相关程序。
> 
> 这项目看起来不能够在 archcn 中分发。

看来是为了躲避叔叔的律师函喽，就当这是MIT吧。后面那句就算是保命用的
当然您认为不妥的话就算了

**Comment by xiao-k233** [comment]
> 一边说自己是 MIT License，一边又说
> 
> > 本项目旨在交流学习之用，请使用者在下载后24小时内删除相关程序。
> 
> 这项目看起来不能够在 archcn 中分发。

![](https://s2.loli.net/2023/01/16/nmXSIquiwV7RW2B.png)

**Comment by Y7n05h** [comment]
bilibili-bin 这个能不能打包并不只受 [bilibili-linux](https://github.com/msojocs/bilibili-linux) 项目的 license 影响。
[bilibili-linux](https://github.com/msojocs/bilibili-linux) 中的脚本在执行过程中获取并修改了专有内容：

https://github.com/msojocs/bilibili-linux/blob/c9eaaa27308440e6c3af21768e759e282c127845/tools/update-bilibili#L20

因此，即使 [bilibili-linux](https://github.com/msojocs/bilibili-linux) 项目本身是自由的，其运行得到的产物也是专有的。
我们无权分发。

**Comment by hubutui** [comment]
@Y7n05h 去下载了官方的 exe？是 bilibili 的 Windows 客户端改用电子包了，然后这个项目做了一些修改，让这个电子包也能在 Linux 下使用么？那看起来的确不能放在这里分发的。丢 AUR 问题倒是不大吧。

**Comment by Y7n05h** [comment]
> 是 bilibili 的 Windows 客户端改用电子包了，然后这个项目做了一些修改，让这个电子包也能在 Linux 下使用么？

我也只是大概看了一下这个项目，但我感觉是的。

> 丢 AUR 问题倒是不大吧。

嗯。不过 aur 已经有了。
