### ISSUE TITLE
wayfire-git 不应该提供 wlroots-git

### ISSUE THREAD

**Issue by q234rty** [archlinuxcn/repo#3119]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* wayfire-git

----

archcn 的 wayfire-git 提供的是上游 git submodule 的 wlroots，从 https://github.com/WayfireWM/wayfire/commits/master/subprojects 来看，大部分时间 wayfire 上游提供的是稳定版 wlroots 而非 wlroots-git，导致真正需要 wlroots-git 的软件包编译不通过。

**Comment by yan12125** [comment]
wayfire-git and some other related packages are removed: https://github.com/archlinuxcn/repo/commit/c8c3bdd22471a9a313c2f0433e8a848be56b8a36
