### ISSUE TITLE
cndrvcups-common-lib depends on a removed package

### ISSUE THREAD

**Issue by EzioisAwesome56** [archlinuxcn/repo#3121]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* cndrvcups-common-lb
* cndrvcups-lb

----

attempting to install cndrvcups-lb also attempts to install cndrvcups-common-lib, which then attempts to resolve its dependency of "libglade", however it appears to have been removed from the official repos at some point in 2021 (best-guess it was because it relies on python 2). as a result, neither of these packages install anymore

(ignore the fact it says apt, that is a simple wrapper I wrote around pacman)
![image](https://user-images.githubusercontent.com/21185626/214143195-898f30f4-b68e-45b7-abf3-85667e6e3e62.png)

**Comment by Dringsim** [comment]
also affects pygtk

**Comment by oldherl** [comment]
Package was removed.
