### ISSUE TITLE
`fcitx5-chinese-addons-git` packaging error

### ISSUE THREAD

**Issue by JimMoen** [archlinuxcn/repo#3122]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*fcitx5-chinese-addons-git

----

related issue: fcitx/fcitx5-chinese-addons#5

It works After I reinstall `fcitx5-chinese-addons` (rebuild) it from aur on my local environment.

**Comment by JimMoen** [comment]
[build history](https://build.archlinuxcn.org/~imlonghao/#fcitx5-chinese-addons-git)

**Comment by farseerfc** [comment]
fixed
