### ISSUE TITLE
nheko-git 应该依赖 cmark 的 patch version 而不是 minor version 并随之 rebuild

### ISSUE THREAD

**Issue by q234rty** [archlinuxcn/repo#3123]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* nheko-git

----

目前 nheko-git 依赖的 cmark 仅精确到 minor release, 但事实上 cmark 的 soname 每次 patch release 都会变。

**Comment by yuyichao** [comment]
Fixed in https://github.com/archlinuxcn/repo/commit/2aff1ceee25fa44fd090eb1475883cd3a2df5b2e
