### ISSUE TITLE
php-swoole 依赖 nhttp2 找不到

### ISSUE THREAD

**Issue by aixiangfei** [archlinuxcn/repo#3132]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* php-swoole 

----

请在此补充说明。

warning: cannot resolve "nghttp2", a dependency of "php-swoole"

在 aur 里面可以找到 nghttp2，但是编译得花很长时间，能否把 nghttp2 加到仓库里面去呢？

**Comment by BruceZhang1993** [comment]
@aixiangfei php-swoole 5.x no longer depends on nghttp2 now, so maybe we should wait for #3114 to be fixed.
