### ISSUE TITLE
ttf-maple 加入  MapleMono-SC-NF 支持

### ISSUE THREAD

**Issue by everyx** [archlinuxcn/repo#3145]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* ttf-maple

----

请在此补充说明。
Please describe in detail here.

对 libac 不太了解，看起来只需要增加对应的文件链接以及加入 `package_ttf-maple-sc-nerd()`？

**Comment by CoelacanthusHex** [comment]
之前感觉不是很需要所以没加，等会儿加上

**Comment by everyx** [comment]
> 之前感觉不是很需要所以没加，等会儿加上

用这个字体就是因为中文会严格对齐两个英文字符，本来是 AUR 的，但是因为和 cn 重名了，结果更新后中文的没了 😂

**Comment by everyx** [comment]
@CoelacanthusHex 你好，看 archlinuxcn 里面还是搜不到 `ttf-maple-sc-nerd`，请问是要多长时间才会进入源啊？

**Comment by CoelacanthusHex** [comment]
> @CoelacanthusHex 你好，看 archlinuxcn 里面还是搜不到 `ttf-maple-sc-nerd`，请问是要多长时间才会进入源啊？

哦，没触发构建，等会我手动触发一下
