### ISSUE TITLE
Changes in sway 1.8

### ISSUE THREAD

**Issue by Y7n05h** [archlinuxcn/repo#3152]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* sway-im
* sway-hidip-git

----

In [sway 1.8](https://github.com/swaywm/sway/releases/tag/1.8)：

> - On Linux, `CAP_SYS_NICE` can be set to improve scheduling: https://github.com/swaywm/sway/pull/6994
> - The pcre dependency has been replaced with pcre2: https://github.com/swaywm/sway/pull/6883

PKGBUILD needs to be updated due to changes in sway 1.8.

**Comment by lilydjwg** [comment]
很怪，compositor 竟然需要比音频更高优先级。他们是不是不明白什么叫音频、什么叫实时啊……

**Comment by SilverRainZ** [comment]
说起来 swaymsg 还改了输出格式，我说我的多屏幕设置脚本怎么炸了。

**Comment by PeterCxy** [comment]
By the way, this issue has been fixed in `sway-hidpi-git` since `r7072.4cda9ee3a-2`.

**Comment by Zenvie** [comment]
sway-im: No maintainer available, see https://github.com/archlinuxcn/repo/issues/3232.
sway-hidip-git: Fixed, see https://github.com/archlinuxcn/repo/commit/9f49f380354e7e2302cb1aa5a40f52a7c096b6bd and https://github.com/archlinuxcn/repo/commit/94c7f97b685d8bf6e7984dc69e3f4bff235c98c2.
