### ISSUE TITLE
collected 可选依赖 rrdtool

### ISSUE THREAD

**Issue by colorsakura** [archlinuxcn/repo#3162]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* collectd

----

请在此补充说明。
Please describe in detail here.

collected 配置默认启用了 rrdtool 这个插件，但是 rrdtool 这个依赖包是可选的，
导致第一次默认安装后，无法启动服务。希望能修改一下。

**Comment by lilydjwg** [comment]
呃，我觉得你启动不了挺好的，因为你根本就没有配置嘛。

**Comment by oldherl** [comment]
Not a packaging problem.
