### ISSUE TITLE
pikaur-git config.py patching out of date

### ISSUE THREAD

**Issue by yuyichao** [archlinuxcn/repo#3190]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* pikaur-git

----

Since https://github.com/actionless/pikaur/commit/7b8bb681d0f09a5d84bbd141b4acad731ed040ea#diff-ad113e8a76d53552ce5c7dd8f7153b2049964ff330431c776421cb97be9376c6, the VERSION line in config.py contains a `VERSIONDIFF ... = ` line that is accidentally patched by the the VERSION patching which breaks the package. It also seems that the VERSION line no longer contain a string that has to be replaced so it may or may not still be necessary to keep that line at this point.

**Comment by axionl** [comment]
Thanks~ https://github.com/archlinuxcn/repo/commit/7f435f04c786490172ecc0c20e84c5d59360c9e8
