### ISSUE TITLE
Package-repacking request

### ISSUE THREAD

**Issue by JimMoen** [archlinuxcn/repo#3201]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* telegram-desktop-megumifox
* telegram-desktop-megumifox-debug

----

请在此补充说明。
因依赖库更新需要重新打包
```
$ telegram-desktop        
telegram-desktop: error while loading shared libraries: libavcodec.so.59: cannot open shared object file: No such file or directory
```

**Comment by MarvelousBlack** [comment]
8854bfaab17e8e8d4b96a8899522c67a8af80610

**Comment by lilydjwg** [comment]
@MarvelousBlack 你加个 update_on 吧。
