### ISSUE TITLE
orphaning 18 packages for DuckSoft

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#3224]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* pingtunnel-git
* qv2ray-plugin-trojan-go-dev-git
* qv2ray-dev-git
* trojan-git
* qv2ray-plugin-naiveproxy-dev-git
* trojan-go-git
* qv2ray-plugin-command-dev-git
* qv2ray-plugin-ssr-dev-git
* qv2ray-plugin-trojan-dev-git
* fgit-go
* daemonize
* genie-systemd
* trojan-r-git
* leaf
* ca-certificates-vsign-universal-root
* shadowsocks-rust-git
* shadowsocks-rust-opt-git

----

These packages were cleaned up during the 2023 cleanup (#3181). If any maintainers want to adopt any of them, it's time to take action!

**Comment by zjuyk** [comment]
adopt ventoy-bin by zjuyk
