### ISSUE TITLE
Update linux kernel-pf to latest update v4.9-pf2 out-of-date

### ISSUE THREAD

**Issue by MatheusViGo** [archlinuxcn/repo#325]
https://pf.natalenko.name/news/?p=231

**Comment by MatheusViGo** [comment]
https://aur.archlinux.org/packages/linux-pf/

**Comment by petronny** [comment]
linux-pf 4.9.3 is out.
it's now out of date again..

**Comment by MatheusViGo** [comment]
Now is linux-pf 4.9.4-pf4 
https://pf.natalenko.name/news/?p=238
