### ISSUE TITLE
eternalterminal-*packages have file conflicts

### ISSUE THREAD

**Issue by fsxitutu** [archlinuxcn/repo#3259]
### 问题类型 / Type of issues

* 打包错误 / packaging error
* file conflicts

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* eternalterminal
* eternalterminal-client
* eternalterminal-htm

----

请在此补充说明。
Please describe in detail here.

eternalterminal-client和eternalterminal-htm包同时存在/usr/bin/htm文件，而eternalterminal包缺少/usr/bin/htmd文件，导致系统无法同时使用et和htmd。
eternalterminal-client和eternalterminal-htm包之间会有文件冲突(/usr/bin/htm)，无法同时安装。

Both the eternalterminal-client and eternalterminal-htm packages exist in the /usr/bin/htm file,and the eternalterminal package lacks the /usr/bin/htmd file, so the system cannot use et and htmd at the same time.
There will be file conflicts(/usr/bin/htm) between the eternalterminal-client and eternalterminal-htm packages, and they cannot be installed at the same time.

**Comment by yuyichao** [comment]
Already fixed.
