### ISSUE TITLE
请求添加Leanote开源云笔记客户端

### ISSUE THREAD

**Issue by Bangjie** [archlinuxcn/repo#326]
Leanote是一个GPL-2.0协议下的开源云笔记，支持自定服务器部署。支持Markdown及latex公式。支持html，为知笔记，Evernote导入导出，支持pdf导出。（为知不是开始收费了么。）

请求添加其客户端：[Leanote Desktop App](https://github.com/leanote/desktop-app)
Leanote主页：https://leanote.com/

万分感谢。

**Comment by Bangjie** [comment]
万分感谢。 但是似乎有点问题。

Archlinuxcn中安装leanote，似乎是用electron封装了一个网页。截图如下：
![bad](https://cloud.githubusercontent.com/assets/18102885/21953018/f008e056-da67-11e6-9a35-250c4cd4443c.png)

从Leanote托管在[sourceforge](https://sourceforge.net/projects/leanote-desktop-app/?source=typ_redirect)的二进制包执行的截图如下：
![good](https://cloud.githubusercontent.com/assets/18102885/21953029/30078586-da68-11e6-8825-7eace6e19660.png)

能不能直接拖二进制包到仓库里，命名为Leanote-bin之类的。
多谢，祝好。

**Comment by petronny** [comment]
现在这就是官方提供的APP版本
参考
https://github.com/electron/electron#downloads
可知这个项目就是由electron搭建的

**Comment by petronny** [comment]
sorry看错了

**Comment by ykelvis** [comment]
已换sourceforge源，试了一下应该没问题了...aur更了 archcn打包好了但是机器人貌似坏掉了？repo里好几十个包了... @lilydjwg

**Comment by lilydjwg** [comment]
嗯坏了……刚应该修好了，但是那些打出了多个版本的包可能会出问题……

**Comment by Bangjie** [comment]
大好人，十万个赞了。万分感谢。



dengbangjie@foxmail.com
 
发件人： 依云
发送时间： 2017-01-21 17:04
收件人： archlinuxcn/repo
抄送： Bangjie; Author
主题： Re: [archlinuxcn/repo] 请求添加Leanote开源云笔记客户端 (#326)
嗯坏了……刚应该修好了，但是那些打出了多个版本的包可能会出问题……

**Comment by Bangjie** [comment]
运行完美，感谢帮忙，辛苦了。
