### ISSUE TITLE
nheko-git 現在依賴 gst-plugin-pipewire

### ISSUE THREAD

**Issue by foxB612** [archlinuxcn/repo#3261]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* nheko-git

----

此 [commit](https://github.com/Nheko-Reborn/nheko/commit/5de730830a0e4bba32a1e571787a4e3fdb5f2e1a) 之後 nheko 需要 gst-plugin-pipewire ，否則無法啓動：

```
[ui] [error] Missing GStreamer elements: pipewiresrc
```

**Comment by yuyichao** [comment]
看提交说明是可选的... 不过懒得测试了就他吧......
