### ISSUE TITLE
将所有依赖 libdisplay-info-git 的包迁移回 community/libdisplay-info 并添加 soname depends

### ISSUE THREAD

**Issue by q234rty** [archlinuxcn/repo#3263]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* wlroots-hidpi-git 
* hyprland-hidpi-xprop-git
* hyprland-git
* hyprland-nvidia-hidpi-git
* hyprland-nvidia-git

----

目前这些包需要 libdisplay-info 的原因都是 wlroots，但 wlroots 的 [CI](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/.builds/archlinux.yml) 使用的是已发布版本的 libdisplay-info，并且 wlroots 的主要开发者之一已经[明确表示](https://matrix.to/#/%23wlroots%3Alibera.chat/%24Xn49Gc4MXLYDyEmBjY29_ULNVVttAlSCe2lgrb8tZok?via=libera.chat&via=matrix.org&via=envs.net)不会要求未发布版本的 libdisplay-info：
![图片](https://user-images.githubusercontent.com/11485439/230050450-5d4bb947-aa6c-4754-aaca-9891475c7644.png)

现在这样会导致（比如说）archlinuxcn/wlroots-hidpi-git 无法与 community/hyprland 共存，且 community/libdisplay-info 已经有了 soname provides，在迁移的同时添加 soname depends 可以防止突然滚挂。

**Comment by lilydjwg** [comment]
终于有 libdisplay-info 了啊。那 libdisplay-info-git 是不是也加一下 so provides 比较好？

**Comment by lilydjwg** [comment]
![图片](https://user-images.githubusercontent.com/440661/230056459-9fe6c24e-10ac-4288-99bb-aa6b4d945e70.png)
呃……

**Comment by q234rty** [comment]
（我不太懂有啥地方可以查询 #wlroots 的 irc log...）

**Comment by Integral-Tech** [comment]
已发 Pull Request

**Comment by q234rty** [comment]
已完成。
