### ISSUE TITLE
signature from "lilac-alarm <lilac@build.archlinuxcn.org>" is unknown trust

### ISSUE THREAD

**Issue by hongy19** [archlinuxcn/repo#3266]
### 问题类型 / Type of issues
* 打包错误 / packaging error
* PGP signature error: signature from "lilac-alarm <lilac@build.archlinuxcn.org>" is unknown trust

### 受影响的软件包 / Affected packages
* yay

----
<img width="899" alt="Screenshot 2023-04-07 192429" src="https://user-images.githubusercontent.com/7909177/230601067-550a555f-7339-4b0e-abbf-d44642c20a2e.png">

请在此补充说明。
Please describe in detail here.
hongy19@PI ~$ sudo pacman -S yay
resolving dependencies...
looking for conflicting packages...

Packages (1) yay-12.0.3-1

Total Download Size:   2.70 MiB
Total Installed Size:  8.58 MiB
Net Upgrade Size:      0.01 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 yay-12.0.3-1-aarch64                                                  2.7 MiB  2.89 MiB/s 00:01 [#########################################################] 100%(1/1) checking keys in keyring                                                                   [#########################################################] 100%
(1/1) checking package integrity                                                                 [#########################################################] 100%
error: yay: signature from "lilac-alarm <lilac@build.archlinuxcn.org>" is unknown trust
:: File /var/cache/pacman/pkg/yay-12.0.3-1-aarch64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.

**Comment by oldherl** [comment]
Have you installed archlinuxcn-keyring?

**Comment by hongy19** [comment]
> Have you installed archlinuxcn-keyring?

sorry for my stupid mistake. issue solved after installing archlinuxcn-keyring
