### ISSUE TITLE
telegram-desktop-megumifox need rebuild

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [archlinuxcn/repo#3273]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* telegram-desktop-megumifox

----

Looks like need rebuild due to Qt 6 upgrade recently.

```
% telegram-desktop 
telegram-desktop: symbol lookup error: telegram-desktop: undefined symbol: _ZN13QUnicodeTools11initScriptsE11QStringViewP15QVarLengthArrayINS_10ScriptItemELx64EE, version Qt_6
```

**Comment by MarvelousBlack** [comment]
https://github.com/archlinuxcn/repo/pull/3272
