### ISSUE TITLE
Build script of package 'gdb-multiarch' is not auto-updating

### ISSUE THREAD

**Issue by Donlon** [archlinuxcn/repo#3278]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* `gdb-multiarch`

----

In [lilac.yaml](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/gdb-multiarch/lilac.yaml#L12-L14) of package `gdb-multiarch`, the update source has been set to `aur` however the `PKGBUILD` file of it hasn't been updated since [12.1-2](https://aur.archlinux.org/cgit/aur.git/log/PKGBUILD?h=gdb-multiarch). Is this situation related to its orphaning (#3233)?

**Comment by lilydjwg** [comment]
No, it's because [it failed to build](https://build.archlinuxcn.org/~imlonghao/#gdb-multiarch) (and the logs have been cleaned up).

**Comment by Donlon** [comment]
So to investigate this problem, should I update the PKGBUILD file in the repo manually to trigger a rebuild and to get the build logs again? I have tested the script and it works on my system.

**Comment by lilydjwg** [comment]
Yes.
