### ISSUE TITLE
Python 3.6 rebuild

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#328]
Python 3.6 has entered `extra`. We need to rebuild all packages linked to python.
Here is a list of packages generated by:
```
pkgfile -d "/usr/lib/python3.5/site-packages/" 
```
Check them after rebuilding is done.

- [x] archsocks
- [x] bedup-git
- [x] bypy-git
- [x] coursera-dl-git
- [x] kwplayer
- [x] leo
- [x] libunity
- [x] nvchecker-git
- [x] pacvis-git
- [x] pm2ml
- [x] powerpill
- [x] pyfm
- [x] python-aiohttp
- [x] python-aiosocks  @PeterCxy 
- [x] python-alembic
- [x] python-async_timeout
- [x] python-cld2-git
- [x] python-curio
- [x] python-editor
- [x] python-flask-peewee @petronny 
- [x] python-gcp-git
- [x] python-http-parser-git
- [x] python-libclang @wicast 
- [x] python-lupa
- [x] python-lz4
- [x] python-memory_profiler
- [x] python-multidict-git
- [x] python-notify2
- [x] python-objgraph
- [x] python-plotly
- [x] python-pygal-git
- [x] python-pytoml
- [x] python-regex-hg
- [x] python-rpweibo
- [x] python-stagger-git
- [x] python-svgwrite
- [x] python-tldextract
- [x] python-wand
- [x] python-wtf-peewee @petronny 
- [x] python-yarl
- [x] python3-aur
- [x] python3-memoizedb
- [x] python3-xcgf
- [x] python3-xcpf
- [x] qtile
- [x] remarkable  @cuihaoleo 
- [x] yamllint
- [x] you-get-git

**Comment by petronny** [comment]
如果通过bump pkgver来rebuild的话，现在应该不会产生任何commit
希望可以把build的log也加进repo，这样lilac就会产生一个commit，这样就可以通过这个commit确认rebuild成功了

**Comment by farseerfc** [comment]
我是 pacman -Ss 確認的……

**Comment by lilydjwg** [comment]
@petronny log 会非常大的。
确认直接看 pacman -Si 的版本就好。

**Comment by lilydjwg** [comment]
@petronny log 会非常大的。
确认直接看 pacman -Si 的版本就好。

**Comment by SilverRainZ** [comment]
这样的话依赖 libpython3.so 的包是查不出来的？

**Comment by farseerfc** [comment]
嗯查不出來……需要別的方法查依賴 libpython3.so 的包。
我寫了個 PKGBUILD 依賴幾乎所有 archlinuxcn 的包，然後忽略了一堆包之後打包出的結果貌似只有 srain 依賴。
PKGBUILD: https://cfp.vim-cn.com/cbcNG
pkglist: https://cfp.vim-cn.com/cbcNJ
執行結果: https://cfp.vim-cn.com/cbcNH

**Comment by SilverRainZ** [comment]
居然能这样查…… 好厉害。

**Comment by lilydjwg** [comment]
sed 还能这样用～

我所知道的，vim-lily 是可选依赖 Python 的，然而因为是使用 dlopen 所以这样并查不了（所以版本不对 Vim 还是能跑起来～）。

**Comment by zsrkmyn** [comment]
其实 vim-youcompleteme-git 也是要 rebuild 的但是不知道为啥没人报 bug。

**Comment by petronny** [comment]
现在应该都rebuild了
