### ISSUE TITLE
fakeroot-tcp package in repo.achlinux.org is not created automatically

### ISSUE THREAD

**Issue by ktamp** [archlinuxcn/repo#3280]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
fakeroot-tcp

----

请在此补充说明。
Please describe in detail here.

Version of package fakeroot-tcp in repo.archlinuxcn.org/x86_64/ is still 1.25.3-2 since September 06, 2021.

Version of this package in archlinuxcn/repo is 1.31-1 since February 16, 2023.
It had been 1.30.1-1 since December 22, 2022.
And it had been 1.29-1 since May 23, 2022.

**Comment by lilydjwg** [comment]
It's up-to-date now.
