### ISSUE TITLE
WeChat 微信输入法问题修复

### ISSUE THREAD

**Issue by buttergrillcorn** [archlinuxcn/repo#3282]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
wine-wechat-setup

----

请在此补充说明。
Please describe in detail here.

Path: archlinuxcn/wine-wechat-setup/wechat

`env['LANG'] = 'zh_CN.UTF-8'`

安装之后出现了fcitx5输入中文有输入框但是无法上词到微信里的问题。
我在加上 `env['LOCALE'] = 'zh_CN.UTF-8'` 之后好像是解决了这个问题。

**Comment by lilydjwg** [comment]
没有 `LOCALE` 这个环境变量吧？你可能之前没生成 `zh_CN.UTF-8` 这个 locale？

**Comment by buttergrillcorn** [comment]
> 没有 `LOCALE` 这个环境变量吧？你可能之前没生成 `zh_CN.UTF-8` 这个 locale？

是这样的吗，不好意思linux新手一个hh。我确实是修改了locale.conf并生成了。
