### ISSUE TITLE
The following packages cannot be upgraded due to unresolvable dependencies

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#329]
These packages cannot be installed due to unresolvable dependencies.
Consider drop them from the repo?

- [x] balsamiqmockups
- [x] cuda_memtest
- [x] freecad-oce
- [x] newrelic-php5
- [x] nvidia-mainline
- [x] nvidia-mainline-dkms
- [x] okular-backend-mupdf-git
- [x] stapler-git
- [x] virtualbox-pf-guest-modules
- [x] virtualbox-pf-host-modules
- [x] xfce4-taskbar-plugin

**Comment by petronny** [comment]
I suggest dropping them if these packages are still un-fixed in Feb and no user complain about them.

**Comment by petronny** [comment]
* aur上游out of date:  
balsamiqmockups @felixonmars 
nvidia-mainline @ykelvis 
nvidia-mainline-dkms @ykelvis 

* 和aur pkgrel不一致(落后):  
cuda_memtest @yuyichao (Your TODO?)
xfce4-taskbar-plugin @ykelvis 

* 和aur 一致:  
newrelic-php5 @felixonmars 
okular-backend-mupdf-git @farseerfc 
stapler-git @colinkeenan

**Comment by farseerfc** [comment]
dropped okular-backend-mupdf-git

**Comment by ykelvis** [comment]
- [x] nvidia-mainline
- [x] nvidia-mainline-dkms
all solved now.

**Comment by petronny** [comment]
话说balsamiqmockups依赖的adobe-air-sdk和newrelic-php5依赖的php56 aur都有，我们是添加这两个包的依赖还是drop这两个包呢？

**Comment by petronny** [comment]
@colinkeenan Please rebuild stapler-git using the latest PKGBUILD from AUR. (The maintainer updated it without bumping pkgrel)
