### ISSUE TITLE
rust-nightly的proc-macro server无法被rust-analyzer识别

### ISSUE THREAD

**Issue by 91khr** [archlinuxcn/repo#3298]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* rust-nightly
* rust-analyzer

----

zulip上的讨论链接: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/proc.20macro.20not.20expanded.20for.20locally.20defined.20macros

`rust-analyzer-proc-macro-srv` 被放到了 `/usr/lib/rust-nightly` 目录下, rust-analyzer 不会在此目录中寻找proc-macro server, 因而会抱怨找不到proc-macro server.

**Comment by lnicola** [comment]
Hello from the `rust-analyzer` side. We look for server under `/usr/lib` (for Arch) and `/usr/libexec` (for other distros).

I think the client can configure the path (e.g. `rust-analyzer.procMacro.server`), but `rust-nightly` already conflicts with `rust`, so there's probably no reason why it couldn't install the server under `/usr/lib`.

**Comment by lilydjwg** [comment]
Fix committed. [The Arch package guidelines](https://wiki.archlinux.org/title/Arch_package_guidelines#Package_etiquette) suggest that directory but it doesn't work with prebuilt binaries.
