### ISSUE TITLE
android-ndk is out of date

### ISSUE THREAD

**Issue by wongsyrone** [archlinuxcn/repo#330]
https://aur.archlinux.org/packages/android-ndk/

**Comment by farseerfc** [comment]
The problem is that pacman thinks r13b < r13 < r13.b according to `man pacman` and `man vercmp`.
I have reported this to AUR.

**Comment by wongsyrone** [comment]
Thanks.

**Comment by farseerfc** [comment]
manually pushed fec51e5ffd07966062a1a6f226f37a23a22d2138

**Comment by wongsyrone** [comment]
Does this related to PKGBUILD or mirror

```
(1/1) 正在安装 android-ndk                                                                                         [####################################################################] 100%
错误：无法解压缩 /opt/android-ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/aarch64-linux-android/bin/ld.gold (Lzma library error:  No progress is possible)
错误：安装 android-ndk 时出现错误
Source /etc/profile.d/android-ndk.sh or login again to add the
Android NDK tools to your path.
错误：无法交付处理
错误：无法提交处理 (处理已放弃)
发生错误，没有软件包被更新。
```

**Comment by wongsyrone** [comment]
I tried both USTC and TUNA mirrors, neither works.

**Comment by lilydjwg** [comment]
I encountered the same and retried, and it succeeded.

**Comment by wongsyrone** [comment]
After a failed transaction, it leaves an uncompleted installation. It may break integrity if you install it again. Thus I simply delete it and revert to the previous version.

**Comment by lilydjwg** [comment]
I tried `tar tf` and it ended with:
```
opt/android-ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/aarch64-linux-android/bin/ld.gold
xz: (stdin): Unexpected end of input
tar: 归档文件中异常的 EOF
tar: Error is not recoverable: exiting now
```
 seems that the file is trnncated.

**Comment by lilydjwg** [comment]
The file is significantly smaller:

```
>>> pacman -Si android-ndk | grep '软件库\|大小'
软件库         : archlinuxcn
下载大小       : 169.50 MiB
安装后大小     : 2217.49 MiB
软件库         : blackarch
下载大小       : 369.28 MiB
安装后大小     : 2232.70 MiB
```

@farseerfc seems that you signed an incomplete package.

**Comment by farseerfc** [comment]
Sorry for all, I will sign and upload a new package as soon as possible.

**Comment by farseerfc** [comment]
Uploaded f6c9c18a636833a3d7bebfbbb6bb18f4d26a3c48
