### ISSUE TITLE
[out of date] chromium-dev-vaapi

### ISSUE THREAD

**Issue by BigEars431** [archlinuxcn/repo#331]
....and may I also suggest using these build options for a better chromium-dev experience

#########################
#########################

_use_clang=0           # Use clang compiler (downloaded binaries from google). Results in faster build and smaller chromium.
_use_ccache=0          # Use ccache when build.
_use_pax=0             # Set 1 to change PaX permisions in executables NOTE: only use if use PaX environment.
_use_gtk3=0            # If set 1, then build with GTK3 support, if set 0, then build with GTK2.
_debug_mode=0          # Build in debug mode.
_enable_vaapi=1        # Patch for VAAPI HW acceleration NOTE: don't work in some graphic cards, for example, NVIDIA

**Comment by fqj1994** [comment]
It out of date because the patch in aur is broken. Once it's fixed by the AUR maintainer, it will be automatically updated. If you want up-to-date chrome, please use google official chrome dev or chromium-dev as vaapi patch is not in a in-time maintenance. 
Closing this issue.
