### ISSUE TITLE
Request for rust-llvm-git 

### ISSUE THREAD

**Issue by meerfrau** [archlinuxcn/repo#3316]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* rust

----

When I have installed llvm-git (and clang-git) for building my own mesa-git Rust fails `rustc: error while loading shared libraries: libLLVM-15.so`. At the same time a working Rust is necessary for rusticl.

May you please be so kind to package a rust version built against llvm-git?

**Comment by Zenvie** [comment]
Please edit your request to make it easier for the relevant maintainers to handle.

**Comment by oldherl** [comment]
This looks like a package request rather than a bug report.
