### ISSUE TITLE
Request to build yuzu-early-access with Qt6

### ISSUE THREAD

**Issue by sukanka** [archlinuxcn/repo#3320]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* yuzu-early-access
----

Yuzu can now be built with Qt6. We only need to replace `qt5-*` with `qt6-*` and add `-DENABLE_QT6=ON` to cmake flags.
ref: https://github.com/yuzu-emu/yuzu/blob/master/CMakeLists.txt#L27

**Comment by heavysink** [comment]
恕拒绝。

1. 上游yuzu emulator所有打包都是基于Qt5
2. Qt6会导致相机功能被禁。
