### ISSUE TITLE
請求打包 netdata-go-plugins

### ISSUE THREAD

**Issue by NeoChen1024** [archlinuxcn/repo#3322]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

netdata 的額外 plugin 集合

* 主要语言和工具链 / Main Languages and Toolchains

Go 語言

* 上游链接 / Upstream Link

https://github.com/netdata/go.d.plugin

* 为何需要这个软件包 / Why Need This Package

netdata 許多資料收集功能都在這個套件內，少了這些 plugin，它的實用性會下降不少

**Comment by Integral-Tech** [comment]
Fixed in commit https://github.com/archlinuxcn/repo/commit/a7a319c3603fb217a847aeaa69c505bd13b61379.
