### ISSUE TITLE
miniconda uses bundled old root ca certificates

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#3335]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* miniconda

----

`/opt/miniconda/ssl/cacert.pem` is more than one year old and doesn't repsect users' trust / distrust configuration. Better to symlink it to `/etc/ssl/certs/ca-certificates.crt` as per https://archlinux.org/todo/use-system-ca-store/.

There are also

* /opt/miniconda/lib/python3.9/site-packages/certifi/cacert.pem
* /opt/miniconda/lib/python3.9/site-packages/pip/_vendor/certifi/cacert.pem

**Comment by hubutui** [comment]
How to check if a certificate is too old? All these files should symlink to `/etc/ssl/certs/ca-certificates.crt`?
```text
pacman -Ql miniconda|grep cacert.pem 
miniconda /opt/miniconda/lib/python3.10/site-packages/certifi/cacert.pem
miniconda /opt/miniconda/lib/python3.10/site-packages/pip/_vendor/certifi/cacert.pem
miniconda /opt/miniconda/pkgs/ca-certificates-2023.01.10-h06a4308_0/ssl/cacert.pem
miniconda /opt/miniconda/pkgs/certifi-2022.12.7-py310h06a4308_0/lib/python3.10/site-packages/certifi/cacert.pem
miniconda /opt/miniconda/pkgs/pip-23.0.1-py310h06a4308_0/lib/python3.10/site-packages/pip/_vendor/certifi/cacert.pem
miniconda /opt/miniconda/ssl/cacert.pem
```

**Comment by lilydjwg** [comment]
The file has date in its header.

Yes, you can do with all those files, but some may be unused.
