### ISSUE TITLE
wine-wechat-setup 安装从官网下载的安装包时提示 32 位系统不能安装 64 位应用 

### ISSUE THREAD

**Issue by everyx** [archlinuxcn/repo#3336]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* wine-wechat-setup

----

使用的微信安装包链接：https://ccb517c72d6b12c55354b0a7a4cd4e1c.rdt.tfogc.com:49156/dldir1.qq.com/weixin/Windows/WeChatSetup.exe?mkey=6486528cda111efc032308fcafc7779b&arrive_key=311171888621&cip=113.77.193.0&proto=https

`wechat -i` 安装时报错如下图
![image](https://github.com/archlinuxcn/repo/assets/1665522/8d28513b-1382-4d93-ba94-5352d44758ec)

**Comment by lilydjwg** [comment]
微信竟然支持64位了。

**Comment by lilydjwg** [comment]
如果是新装，可以把 `/usr/bin/wechat` 的第95行去掉。更新的话，需要迁移 `~/.local/lib/wine-wechat/*/drive_c/users/$USER/我的文档/WeChat Files` 下的文件。
