### ISSUE TITLE
wine-wechat-setup输入问题

### ISSUE THREAD

**Issue by devome** [archlinuxcn/repo#3338]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

*  wine-wechat-setup 1.4-1, wechat 3.9.5

----

fcitx5能正常弹出输出法的文字候选框，但在微信中无法在聊天输入框键入中文（也完全看不见文字光标）。以命令行启动时，在键入中文时，控制台一直输出大量的错误：
```
00d0:fixme:richedit:editor_handle_message EM_SETLANGOPTIONS: stub
00d0:fixme:richedit:fnTextSrv_OnTxSetCursor Ignoring most params
00d0:fixme:richedit:ME_GetTextEx GETTEXTEX flags 0x00000004 not supported
```
这个时候在空白输入框上点一下微信的“发送”按钮，然后虽然也看不见文字光标，但是可以键入中文。然后发送出去后又得按此操作才能再次键入中文，期间控制台一直出现大量的上述错误。

找到一篇文章：https://www.jianshu.com/p/3a7ef39412bc ，看样子这是wine本身的问题？

**Comment by lilydjwg** [comment]
`wechat -c` 看看 riched20.dll 是不是「原装先于内建」？

**Comment by devome** [comment]
> 



> `wechat -c` 看看 riched20.dll 是不是「原装先于内建」？

是的。

**Comment by devome** [comment]
将riched20.dll改为“内建先于原装”，问题依旧复现。

**Comment by hubutui** [comment]
我的设置是“内建先于原装”，聊天框不会有光标提示，可以正常输入中文．但是输入法候选框是不跟随的．

**Comment by hubutui** [comment]
换成“原装先于内建”也是一样的．看起来不影响啊．

**Comment by devome** [comment]
> 换成“原装先于内建”也是一样的．看起来不影响啊．

我要在空白文字框时鼠标点一下“发送”按钮，再鼠标点一下输入框，然后才能如你所说的那样，也看不见光标，但能输入文字。

**Comment by lilydjwg** [comment]
好耶，看来是 wine 给修好了。

**Comment by luxinghong** [comment]
输入法不跟随的问题要怎么解决呀

**Comment by lilydjwg** [comment]
解决不了。
