### ISSUE TITLE
请求添加mpv前端 bomi

### ISSUE THREAD

**Issue by imzf** [archlinuxcn/repo#335]
功能强大，界面美观
 [项目主页](https://github.com/xylosper/bomi)
[AUR地址](https://aur.archlinux.org/packages/bomi)
截图
![image](https://cloud.githubusercontent.com/assets/3401994/21770667/32f857e0-d6bf-11e6-9db4-4cf5b7448800.png)

**Comment by farseerfc** [comment]
AUR package built with error.
```
g++: error: /build/bomi/src/bomi-0.9.11/build/lib/libmpv.a: No such file or directory
```
no idea how to fix ...

**Comment by petronny** [comment]
我也不知道这个编译错误怎么办是好。。。
但是我看bomi-git这个包没编译问题。。所以我就先加进repo了

@imzf 你试一下bomi-git这个包可以替代吗？

**Comment by farseerfc** [comment]
@petronny 你是用 extra-x86_64-build 編譯的還是 makepkg 編譯的？

**Comment by petronny** [comment]
archlinuxcn-x86_64-build，libchardet我已经加进repo了

**Comment by farseerfc** [comment]
好棒！（爲什麼我這邊 devtools 會報錯找不到 libmpv.a 呢……不糾結了）

**Comment by imzf** [comment]
@farseerfc @petronny  謝謝你們的付出
