### ISSUE TITLE
qv2ray-plugin-ss-dev-git缺少依赖项mbedtls2

### ISSUE THREAD

**Issue by ngdngdc** [archlinuxcn/repo#3350]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* qv2ray-plugin-ss-dev-git

----

qv2ray-plugin-ss-dev-git现在依赖于mbedtls2中的libmbedcrypto.so.7
![截图 2023-06-25 17-23-43](https://github.com/archlinuxcn/repo/assets/61965178/43f70a0b-6c58-4d03-8d82-d3a805f77608)

**Comment by oldherl** [comment]
Package was removed.
