### ISSUE TITLE
uksmd 快于内核版本更新

### ISSUE THREAD

**Issue by zjuyk** [archlinuxcn/repo#3351]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* uksmd
----

需要延迟打包直到内核进 stable, 对应内核 Provides 为 UKSMD-BUILTIN

**Comment by zjuyk** [comment]
上游现在开始打 tag 了，也许我们可以考虑版本号来限制？

**Comment by CoelacanthusHex** [comment]
> 上游现在开始打 tag 了，也许我们可以考虑版本号来限制？

如上所述，没法限制，因为 Arch 没有形如 `UKSMD-BUILTIN=6.4` 的依赖，如果直接使用内核的版本，就必定要强制依赖某个内核，更不要说不同的内核离开 testing 和更新新版本的时间并不一致。

**Comment by zjuyk** [comment]
那我自己来维护一个 uksmd-zen 好了，因为 6.4 版本有 break change，免得有影响
