### ISSUE TITLE
genymotion 软件包出现问题

### ISSUE THREAD

**Issue by weearc** [archlinuxcn/repo#3375]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* genymotion
----

CN 源中的 genymotion 安装后并运行会出现 coredump 的情况，aur 中同名包则不会出现问题，且打包后的体积大概有 0.1 mb 差距

**Comment by heavysink** [comment]
CN源里面的genymotion会跟随AUR update, 不知道怎么回事...现在还有问题吗？

**Comment by weearc** [comment]
> CN源里面的genymotion会跟随AUR update, 不知道怎么回事...现在还有问题吗？

对的目前仍然存在 core dump 的问题，但从 aur clone 到本地构建没有问题

**Comment by tkkcc** [comment]
这问题我记得有几个月了，我也要强制到aur才正常。

**Comment by Zenvie** [comment]
See https://github.com/archlinuxcn/repo/issues/3600. This software package is not officially authorized for distribution, so the issue is closed.
