### ISSUE TITLE
因为 yuzu-emu 项目在代码里搞台独，请求删除所有 yuzu-emu 开源项目有关的软件包

### ISSUE THREAD

**Issue by cookieiz** [archlinuxcn/repo#3382]
### 问题类型 / Type of issues

* 其它 / other
* 因为 yuzu-emu 项目在代码里搞台独，请求删除所有 yuzu-emu 开源项目有关的软件包

### 受影响的软件包 / Affected packages

* yuzu-early-access
* yuzu-early-access-debug
* yuzu-git
* yuzu-git-debug
* yuzu-mainline-git
* yuzu-mainline-git-debug
----

请在此补充说明。
Please describe in detail here.

根据联合国第2758号决议，台湾不是一个国家，而是一个地区政治实体，世界上没有所谓的“Taiwansk”。

根据台湾和中国大陆现行的法律架构，台湾地区不是一个国家：

台湾是中国的一部分，世界上没有所谓的“Taiwansk”。

在台湾虽然支持发展少数民族语言，原住民语言有:阿美语、泰雅语、布农语、卑南语、邹语、鲁凯语、排湾语等。但是繁体中文被用于法律条文、政府文件和路标。这也反映了传统汉语的官方语言地位。根本就没有所谓名叫 ”Taiwanese“ 的语言

开源项目 ：

https://github.com/yuzu-emu

yuzu-emu/yuzu: Nintendo Switch emulator (github.com)

yuzu is the world's most popular, open-source, Nintendo Switch emulator — started by the creators of Citra.

就是不少人在玩的一个开源的 Nintendo Switch 模拟器

yuzu-emu 仓库的管理员FernandoS27把我github 账号 提交到 yuzu 仓库的Pull request 和 issuse权限锁了，原因是我提交的 Pull request 里删除了 ”Taiwansk” 和 ”Taiwanese” 字眼

https://github.com/search?q=repo%3Ayuzu-emu%2Fyuzu%20taiwansk&type=code

https://github.com/search?q=repo%3Ayuzu-emu%2Fyuzu%20taiwanese&type=code

跟他们讲道理 他们回复什么 "No politics here. Thank you."删掉了我的PR

无论是国际法、中国大陆还是台湾的法律制度，这种说法都是非法的。这也违反了世界上大多数与中国大陆建立外交关系时做出的承诺。

我也不想谈论政治，我一直认为开源社区应该是一个基于国际法律规则和相互尊重的和谐国际社区，但在 yuzu 项目的代码中最近出现 “Taiwansk” 这样的带有极端恶意的政治倾向词令人失望，这是极其恶意和灾难性的，说什么开源项目 "No politics here. Thank you." 代码里却本身包含这种恶意的政治倾向，只能说明yuzu-emu 项目的开发者虚伪而且恶心。 

请不要说什么 开源社区政治中立，什么不讨论政治 ，人家在代码里就在和你恶意的讨论政治

他为什么不写”康涅迪格斯克“，”夏威夷斯坦“，”西雅图斯坦“，”纽约共和国“和”夏威夷语“，分明就是故意的搞台独

所以我希望 ArchLinuxCN社区 删除有关 yuzu-emu 的软件包

**Comment by oldherl** [comment]
Not a valid request.

**Comment by YisuiDenghua** [comment]
6

**Comment by lilydjwg** [comment]
有点莫名其妙。「Taiwanese」看起来就是指「Taiwanese Hokkien」（台湾闽南语）而已。而「Taiwansk」是书面挪威语中的「Taiwanese」。至于为什么不写夏威夷语，可能是在等一位夏威夷人去贡献翻译吧。

[archlinuxcn] 不是越南。我们没有「项目中有我们不喜欢的东西所以要禁掉」的政策。如果你不喜欢一个开源项目，你可以去 fork 它，就像 multimc 所发生的事件那样。

**Comment by UjuiUjuMandan** [comment]
**光復台灣 時代革命**
**台灣獨立 唯一出路**
**拒絕沉淪 唯有獨立**
**台灣自決 刻不容緩**
**一個台灣 兩個國家**
