### ISSUE TITLE
mpv-git 遇到动态链接库问题导致成品无法启动

### ISSUE THREAD

**Issue by txyyh** [archlinuxcn/repo#3386]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  mpv-git

----

请在此补充说明。
Please describe in detail here.

glslang 12.3.1 中移除了 libglslang-default-resource-limits.so.12 导致编译成品无法成功启动

**Comment by CoelacanthusHex** [comment]
https://github.com/archlinuxcn/repo/commit/b6dcece0e5126b853386f98ad0702431f7585491
今天下午修復就推送了，請耐心等待構建完成
