### ISSUE TITLE
请求打包switchhosts

### ISSUE THREAD

**Issue by FortiterInRe** [archlinuxcn/repo#3394]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    请求打包aur中已有的switchhosts包

* 主要语言和工具链 / Main Languages and Toolchains

    js nodejs electron

* 上游链接 / Upstream Link

    https://github.com/oldj/SwitchHosts

* 为何需要这个软件包 / Why Need This Package

    可自动更新host,便于国内连接github,然而aur中提供的需要从github中下载，速度较慢，故请求打包

**Comment by Integral-Tech** [comment]
已打包 https://github.com/archlinuxcn/repo/commit/086efecbe899d6125b6565de2ab67f4c2a9c6237
