### ISSUE TITLE
joplin-desktop 依赖 electron19 已弃置，现无法使用

### ISSUE THREAD

**Issue by zhaose233** [archlinuxcn/repo#3398]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* joplin-desktop

----

electron19 已被弃置，无法及时收到更新以保证动态库链接正常，应当换用其它版本 electron 或者直接包含至包內？

**Comment by outloudvi** [comment]
目前确实已经出现了动态库链接问题：

```
$ joplin-desktop
/usr/lib/electron19/electron: error while loading shared libraries: libicui18n.so.72: cannot open shared object file: No such file or directory
$ pacman -Fl icu | grep libicui18n.so
icu usr/lib/libicui18n.so
icu usr/lib/libicui18n.so.73
icu usr/lib/libicui18n.so.73.2
```

**Comment by cuihaoleo** [comment]
其实从 cn 源装一下 `electron19-bin` 可解。

确实该打新版了…… 不过最新 2.11 版本依赖的还是 electron 19。我正在测试用新版 electron 行不行。

**Comment by cuihaoleo** [comment]
`2.11.11-2` 打包成功了（ 5f6df3886d46149ea571dd321cc4fb6478ca1631 & 1714b540c88efdff844e920b8941ffd82464ddea），改为依赖最新的 electron25。
