### ISSUE TITLE
Ruby 2.4.0 rebuild

### ISSUE THREAD

**Issue by SilverRainZ** [archlinuxcn/repo#340]
ruby 2.4.0 in `extra` now, the following packages need rebuild:

- [ ] rak
- [x] ruby-text
- [x] ruby-getext
- [x] ruby-colorator
- [x] ruby-ffi
- [x] ruby-forwardable-extended
- [x] ruby-jekyll
- [x] ruby-jekyll-paginate
- [x] ruby-jekyll-sass-converter
- [x] ruby-jekyll-watch
- [ ] ruby-json_pure
- [x] ruby-kramdown
- [x] ruby-liquid-3
- [x] ruby-listen
- [x] ruby-maruku
- [x] ruby-mercenary
- [x] ruby-pathutil
- [x] ruby-rb-fsevent
- [x] ruby-rb-inotify
- [ ] ruby-rgen
- [x] ruby-rouge
- [x] ruby-safe_yaml
- [x] ruby-sass
- [x] ruby-yard

generated by:

```bash
for p in $(pkgfile -d "/usr/lib/ruby/gems/2.3.0/" | grep archlinuxcn); do echo ${p#archlinuxcn/}; done
```

**Comment by lilydjwg** [comment]
啊我 rebuild 了几个，没想到还有……我看看还有我的包么。

**Comment by SilverRainZ** [comment]
@lilydjwg ruby-{,get}text 被你编辑掉了么？ rak 也是你的啊（剩下的都是基本都是我的了……）。

想尝试从 gems 更新 ruby 包，参考了一下 `ruby-text/lilac.py` 没看懂……

```
    if line.startswith('build()'):
      line = 'package() {'
```

这里的逻辑没有懂……

```python
      line = 'pkgver=' + s.get('https://rubygems.org/api/v1/versions/text.json').json()[0]['number']
```

这里获取 version 似乎完全没有根据 gem name 来啊……

**Comment by lilydjwg** [comment]
ruby-{,get}text 我昨天就 rebuild 了啊。
rak 这是什么我都不认识怎么是我的呢……

**Comment by lilydjwg** [comment]
rak 是一个不认识的人的……packager 是 lilac 旧式的写法。

**Comment by petronny** [comment]
剩下的我都rebuild了。。。
