### ISSUE TITLE
ueberzugpp为ARM可执行文件

### ISSUE THREAD

**Issue by CamaleH** [archlinuxcn/repo#3408]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* ueberzugpp
----

请在此补充说明。
$ file /usr/bin/ueberzug
/usr/bin/ueberzug: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=ddc156509896392b2c4cd57bb443fdef1f05e948, for GNU/Linux 3.7.0, stripped

**Comment by Integral-Tech** [comment]
Fixed in commit https://github.com/archlinuxcn/repo/commit/e18cd64ef99947ff8590f7925de9e4189ba5b09c
