### ISSUE TITLE
[package-req]joshuto

### ISSUE THREAD

**Issue by flame-222** [archlinuxcn/repo#3409]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    [ranger](https://github.com/ranger/ranger)-like terminal file manager written in Rust.

* 主要语言和工具链 / Main Languages and Toolchains

   rust

* 上游链接 / Upstream Link

    git:https://github.com/kamiyaa/joshuto
    AUR:joshuto

* 为何需要这个软件包 / Why Need This Package

    相比于ranger更加快速，自定义功能强大，支持模糊搜索

**Comment by Integral-Tech** [comment]
Package ```joshuto``` added.
x86_64: commit https://github.com/archlinuxcn/repo/commit/9302910bb0bb7ee50e7ae35dc9bbb8075ab4aa17
aarch64: commit https://github.com/archlinuxcn/repo/commit/6cebfd3b75cdb08a2ea6b8b5f5dcc1331de944e5
