### ISSUE TITLE
proton-ge-custom-opt fails to work

### ISSUE THREAD

**Issue by StarterX4** [archlinuxcn/repo#3413]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* proton-ge-custom-opt

----

When I try to run any windows game from Steam, it just throws this error:
```wine: could not load ntdll.so: /usr/share/steam/compatibilitytools.d/proton-ge-custom/files/lib//wine/ntdll.so: cannot open shared object file: No such file or directory```

Didn't ever experience this with any other proton-ge-custom builds (from other repos).
Setting `WINEDLLPATH=/usr/share/steam/compatibilitytools.d/proton-ge-custom/files/lib/wine/i386-unix` doesn't fix it as well, like that wrong path was hardcoded or something.

A faulty build?

**Comment by Zenvie** [comment]
Please refer to https://github.com/archlinuxcn/repo/issues/3578, where this package has been marked as abandoned and closed. Thank you for your understanding and cooperation.
