### ISSUE TITLE
telegram-desktop-megumifox 过期

### ISSUE THREAD

**Issue by tomyangsh** [archlinuxcn/repo#3423]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* telegram-desktop-megumifox

----

**Comment by everyx** [comment]
今天更新后就 telegram-desktop-megumifox 就打不开了，提示：

```console
❯ telegram-desktop 
telegram-desktop: error while loading shared libraries: libprotobuf-lite.so.23: cannot open shared object file: No such file or directory
```

**Comment by tomyangsh** [comment]
> 今天更新后就 telegram-desktop-megumifox 就打不开了，提示：
> 
> ```
> ❯ telegram-desktop 
> telegram-desktop: error while loading shared libraries: libprotobuf-lite.so.23: cannot open shared object file: No such file or directory
> ```

`protobuf` 升级到了24.2, 官方 `telegram-desktop` 进行了 rebuild.

**Comment by oldherl** [comment]
Triggering rebuild in a223acc38591a469ea5da94ec01bb4b82e9cc621
