### ISSUE TITLE
keepassx-reboot-git should be replaced with keepassxc-git

### ISSUE THREAD

**Issue by wangjiezhe** [archlinuxcn/repo#343]

**Comment by lilydjwg** [comment]
@ykelvis you can link pre-commit hook to your .git/hooks dir so that it catches errors like [this](https://github.com/KeepSafe/aiohttp/archive/1.3.1.tar.gz).

**Comment by ykelvis** [comment]
@lilydjwg erros like? is that link correct..?

**Comment by lilydjwg** [comment]
@ykelvis oops..fixed now.

**Comment by ykelvis** [comment]
(=￣▽￣"=)
