### ISSUE TITLE
v2ray 不再是 v2raya-git 的强制依赖

### ISSUE THREAD

**Issue by edward-p** [archlinuxcn/repo#3430]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* v2raya-git
* xray

----

v2raya 现在已经支持 xray, 用户可以自行选择使用 xray 还是 v2ray-core, 因此 `v2ray>=5.0.0` 不再是强制依赖， 考虑让 xray `provides=("v2ray>=5.0.0")` ?

**Comment by edward-p** [comment]
xray 已经 provides v2ray 了，但v2ray还是卸载不掉。因为 v2raya-git 依赖里面写了版本 "v2ray>=5.0.0" , 而xray版本号没那么大，应该改为依赖 "v2ray" 就好了

**Comment by CoelacanthusHex** [comment]
5.0 前后 cli 什么的都是不兼容的，不知道v2ray<5.0能不能工作

**Comment by edward-p** [comment]
> 5.0 前后 cli 什么的都是不兼容的，不知道v2ray<5.0能不能工作

但Arch仓库里面还有提供v2ray<5.0的v2ray包么？
