### ISSUE TITLE
Taisei

### ISSUE THREAD

**Issue by poly000** [archlinuxcn/repo#3437]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Touhou-like STG game

* 主要语言和工具链 / Main Languages and Toolchains

C, CMake/Meson

* 上游链接 / Upstream Link

https://github.com/taisei-project/taisei

* 为何需要这个软件包 / Why Need This Package

自行编译过于昂贵

**Comment by Integral-Tech** [comment]
```taisei```: commit https://github.com/archlinuxcn/repo/commit/dad57d5ea2304dc395db5c80c7b17b538c1a27da
```taisei-git```: commit https://github.com/archlinuxcn/repo/commit/96a310f2d1578d758a1afacfeeb863e151405da3
