### ISSUE TITLE
Require rebuild all kernels with gcc6.3

### ISSUE THREAD

**Issue by FlyGoat** [archlinuxcn/repo#344]
Archlinux have upgraded gcc to 6.3. But all the kernels in this mirror was built by gcc 6.2. It caused some dkms such as nivdia cannot be built correctly. So please rebuild it.

**Comment by lilydjwg** [comment]
linux-lily has been rebuilt with gcc 6.3.

**Comment by ykelvis** [comment]
- [x] linux-pf
- [x] linux-lily
- [x] linux-mainline
- [x] linux-surfacepro3

All four kernels have been built after gcc6.3 update, I think we can mark this as solved.
