### ISSUE TITLE
miktex在archlinuxcn的包安装启动出现问题，而aur直接构建正常

### ISSUE THREAD

**Issue by Jontyshaw** [archlinuxcn/repo#3445]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
miktex
----

请在此补充说明。
Please describe in detail here.
报错信息如下：
/opt/miktex/bin/miktex-console: error while loading shared libraries: libboost_locale.so.1.83.0: cannot open shared object file: No such file or directory

**Comment by hubutui** [comment]
看起来是 boost 版本更新之后没有重新打包导致的．但是看了一下 https://github.com/archlinuxcn/repo/blob/a65830c756215bec29f9e8a56e4a771990f555d3/archlinuxcn/miktex/lilac.yaml#L12 应该会自动触发打包的啊．

**Comment by heavysink** [comment]
Should be fixed now.
