### ISSUE TITLE
missing linux-amd-znver3-headers

### ISSUE THREAD

**Issue by specter119** [archlinuxcn/repo#3446]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* linux-amd-znver3
* linux-amd-znver3-headers

----
请在此补充说明。
Please describe in detail here.

`linux-amd-znver3` is built, and its `pkgrel` is greater than the current AUR version. However, its headers package (`linux-amd-znver3-headers`) is not available in archlinuxcn.

**Comment by Integral-Tech** [comment]
Fixed in commit https://github.com/archlinuxcn/repo/commit/aca24be740585fb6035dbe1d6c1f7e6b1db58a3b.
