### ISSUE TITLE
sublime-text out-of-date

### ISSUE THREAD

**Issue by kinazarov** [archlinuxcn/repo#345]
After adding your repository and update got this warning:
sublime-text: installed version (2.0.2-4)  newer than archlinuxcn (2.0.2-1)

**Comment by cuihaoleo** [comment]
You had installed the latest version from AUR before, while the version in our repo was out-of-date. So you got the warning.

**Comment by kinazarov** [comment]
Got it. Thank you!

**Comment by petronny** [comment]
This package is still out-of-date in our repo. We will update it in no longer than 2 weeks.
