### ISSUE TITLE
cn 源的 nekoray-git 在运行时出现错误

### ISSUE THREAD

**Issue by wuhang2003** [archlinuxcn/repo#3452]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* nekoray-git

----

在 cn 源下载安装 nekoray-git 运行时出现以下错误：

```bash
/usr/bin/nekoray: error while loading shared libraries: libyaml-cpp.so.0.7: cannot open shared object file: No such file or directory
```

怀疑是 libyaml 更新后依赖库名发生变动，卸载并安装 aur 的版本后可正常运行

**Comment by Integral-Tech** [comment]
Fixed in commit https://github.com/archlinuxcn/repo/commit/9bfc807b9a82154be341b0af52e74d8dd4dd209a.
