### ISSUE TITLE
用 wine-wechat-setup 安装微信后，微信的中文字体变为方块

### ISSUE THREAD

**Issue by otakutyrant** [archlinuxcn/repo#3474]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* wine-wechat-setup

----

试着往 `/home/otakutyrant/.wine/drive_c/windows/Fonts` 拷贝了 `/usr/share/fonts` 里面的若干字体，包括 sarasa 字体和 wqy-microhei.ttc，但还是没解决。

**Comment by lilydjwg** [comment]
放 ~/.local/lib/wine-wechat/default/drive_c/windows/Fonts 里。

**Comment by otakutyrant** [comment]
在 ~/.local/lib/wine-wechat/default/drive_c/windows/Fonts 放了 simsun.ttc，还是没解决。

**Comment by otakutyrant** [comment]
这问题可能没办法了，不过我后来改用 AUR 里的 com.qq.weixin.spark 了，没有字体方块问题。
