### ISSUE TITLE
vnote-git 缺少 conflicts 和 provides

### ISSUE THREAD

**Issue by Integral-Tech** [archlinuxcn/repo#3475]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* vnote-git

----

```vnote-git``` 和 ```vnote``` 互相冲突，应在 ```vnote-git``` 的 PKGBUILD 里添加
```shell
conflicts=('vnote')
provides=('vnote')
```

**Comment by heavysink** [comment]
搞好了
