### ISSUE TITLE
[btsync] 上游地址已更改

### ISSUE THREAD

**Issue by KaseiWang** [archlinuxcn/repo#348]
我们是应该drop掉btsync，加入rslsync包；还是应该继续更新btsync包？
如果继续更新btsync包的话，我稍微改了一下[PKGBUILD](https://gist.github.com/KaseiWang/4c2089126acfff69a9021a9092f5a380)，在我这里可以无痛更新，请求测试。

**Comment by petronny** [comment]
奇怪，btsync在nvchecker.ini中指的上游是AUR, 但是aur中已经不存在这个包了

**Comment by KaseiWang** [comment]
是的呀，aur 上已经已经改成 rslsync 了，我想我们也应该这么干，然后发布一个手动更新公告。

**Comment by SilverRainZ** [comment]
我们有公告这种东西么。

**Comment by petronny** [comment]
PKGBUILD里面的replace项有用吗？

**Comment by SilverRainZ** [comment]
我们有公告这种东西么。

**Comment by KaseiWang** [comment]
replace 也不能解决家目录配置文件的问题吧。需要写个脚本移动一下或者手动。公告可以发在 archlinuxcn.org ？不知道有没有人看……

**Comment by petronny** [comment]
我觉得先更新一下btsync.install，新发布一个包
这样用户更新时就会看到btsync已经不复存在了
但是装不装rslsync用户自己处理好了

**Comment by KaseiWang** [comment]
好主意。

**Comment by lilydjwg** [comment]
replace + echo in the install script

**Comment by KaseiWang** [comment]
@felixonmars 我刚发现 btsync 没有用 lilac。所以你能看一下 btsync.install (我在里面写了一个提示)，然后最后打一个包吗？我只修改了 pkgrel 和 .install。再过两周删掉 btsync 就好了。

**Comment by petronny** [comment]
自己加一个lilac.py就是了。。

**Comment by petronny** [comment]
@KaseiWang nvchecker.ini中的btsync仍在尝试track aur
需要指定令其track一个有效的上游
我觉得是指定其track一个永远不会更新的上游(比如自己开的一个空github repo)，然后通过bump pkgrel来触发lilac

**Comment by KaseiWang** [comment]
等我回到学校我会手动更新一下，反正这是最后一次更新了。

**Comment by lilydjwg** [comment]
> 我觉得是指定其track一个永远不会更新的上游(比如自己开的一个空github repo)，然后通过bump pkgrel来触发lilac

直接 manual = xxx 不就好了么

-- 
Best regards,
lilydjwg

**Comment by petronny** [comment]
诶。。manual已经实现了吗。。

**Comment by lilydjwg** [comment]
对啊，manual 就是手动指定版本号的意思。

**Comment by petronny** [comment]
@KaseiWang 帮你manual了。。应该已经build出来了
一个月以后把btsync删了应该就行了吧

**Comment by KaseiWang** [comment]
啥？我已经手动打包上传了，不需要 lilac 了。而且你把 .install 里的提示又改回去了……

**Comment by petronny** [comment]
`_(:3」∠)_`中枪无数

**Comment by KaseiWang** [comment]
……现在怎么办？快把提示加回去？还是把包从repo里直接删掉比较好？

**Comment by petronny** [comment]
把lilac.py删了，nvchecker.ini中移除对应项。更新一个pkgrel传上去

**Comment by KaseiWang** [comment]
你来改还是我来改？

**Comment by petronny** [comment]
你来吧。我根本就没传gpg key到keyring
