### ISSUE TITLE
ncurses5-compat-libs is out-of-date

### ISSUE THREAD

**Issue by psamim** [archlinuxcn/repo#351]

**Comment by petronny** [comment]
现在aur上的版本是6.0+20161224
貌似nvchecker还是lilac对pkgver/pkgrel带+号的处理不好

**Comment by psamim** [comment]
I do not know Chinese 😶

**Comment by lilydjwg** [comment]
@psamim Fortunately, it's for the maintainer, not you :-)

@petronny nvchecker 只要检测到变化就会触发的，并不比较大小。但我刚查过日志了，并没有 nvchecker 的相关日志。从 AUR 取得的版本号还是「6.0-4」。

**Comment by lilydjwg** [comment]
The package is expected to update soon.
