### ISSUE TITLE
Failed to run vnote-git

### ISSUE THREAD

**Issue by Integral-Tech** [archlinuxcn/repo#3517]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* vnote-git

----
Error log:
```
socket connect timeout
local server listening on "vnote"
guard succeeds to run
APPIMAGE ""
app folder "/usr/bin"
app config folder "/home/integral/.local/share/VNote/VNote"
user config folder "/home/integral/.config/VNote/VNote"
version "3.17.0" user version "3.17.0"
zsh: segmentation fault (core dumped)  vnote
```

**Comment by heavysink** [comment]
是用的wayland吗？我也遇到问题了。gdb报错:QHotkeyPrivateX11::nativeKeycode (this=<optimized out>, keycode=Qt::Key_U, ok=@0x7fffffffcfe0: false)
    at ../libs/QHotkey/QHotkey/../../../../libs/QHotkey/QHotkey/qhotkey_x11.cpp:135
135		Display *display = x11Interface->display();

好像QT_QPA_PLATFORM=xcb vnote可以运行。我需要向上游反映下。

**Comment by heavysink** [comment]
https://github.com/vnotex/vnote/issues/2448

**Comment by Integral-Tech** [comment]
> 是用的wayland吗？我也遇到问题了。gdb报错:QHotkeyPrivateX11::nativeKeycode (this=, keycode=Qt::Key_U, ok=@0x7fffffffcfe0: false) at ../libs/QHotkey/QHotkey/../../../../libs/QHotkey/QHotkey/qhotkey_x11.cpp:135 135 Display *display = x11Interface->display();
> 
> 好像QT_QPA_PLATFORM=xcb vnote可以运行。我需要向上游反映下。

嗯，是 Wayland

**Comment by lisuke** [comment]
> > 是用的wayland吗？我也遇到问题了。gdb报错:QHotkeyPrivateX11::nativeKeycode (this=, keycode=Qt::Key_U, ok=@0x7fffffffcfe0: false) at ../libs/QHotkey/QHotkey/../../../../libs/QHotkey/QHotkey/qhotkey_x11.cpp:135 135 Display *display = x11Interface->display();
> > 好像QT_QPA_PLATFORM=xcb vnote可以运行。我需要向上游反映下。
> 
> 嗯，是 Wayland

是的，Hyprland 下有同样的问题
```
Core was generated by `vnote'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  QHotkeyPrivateX11::nativeKeycode (this=<optimized out>, keycode=Qt::Key_U, ok=@0x7ffd9cd4ba90: false) at ../libs/QHotkey/QHotkey/../../../../libs/QHotkey/QHotkey/qhotkey_x11.cpp:135
135		Display *display = x11Interface->display();
[Current thread is 1 (Thread 0x7f35515f6040 (LWP 781351))]
```

**Comment by heavysink** [comment]
现在的问题是Qt6.7才刚刚得到支持...我先编译看看

**Comment by heavysink** [comment]
应该没问题了。
