### ISSUE TITLE
nvchecker incorrectly reports many packages need to be upgraded because pkgrel is lower on AUR

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#352]
For a variety of reasons, I have increased the pkgrel on packages I maintain in our repo compared to what it is in AUR. In the past, nvchecker has ignored the lower pkgrel on AUR. Now, all of sudden, it says all these packages need to be "upgraded" because AUR has a lower pkgrel:

clup cdu cla gtk-theme-config lib32-pangox-compat mkinitcpio-colors-git nautilus-data opentk opentk-docs setcolors-git tchrome gnome-search-tool-no-nautilus

These are just the AUR packages I build for our repo. I'm sure there are other AUR packages that nvchecker now incorrectly reports as needing an "upgrade".

**Comment by lilydjwg** [comment]
Then you can downgrade nvchecker-git to restore the old behavior.

It's a breaking change in nvchecker. The old behavior was to use version comparison to decide if a package has been updated upstream. It caused some problems on some packages (e.g. #351 and lilydjwg/nvchecker#45), so I changed it to treat any change in the version string as a signal that there is a new release. Upstreams use different version schemas and it's hard to recognize the orders of all of them.

Nvchecker is meant to discover new versions, not the packaging versions a packager should use. So you should not compare the reported versions to your packages.

**Comment by colinkeenan** [comment]
Could you change nvchecker to do version comparison in the case of AUR= packages, while keeping the new behavior on everything else?

**Comment by lilydjwg** [comment]
I prefer not. AUR versions may go back unexpectedly too. And even the old behavior had issues with AUR versions.

**Comment by colinkeenan** [comment]
Alright. I've put `IgnorePkg   = nvchecker-git` in `/etc/pacman.conf` and downgraded to nvchecker-git-v0.4.3.r4.g63a0161-1-any.pkg.tar.xz

I guess I'll keep it that way until it breaks.
