### ISSUE TITLE
xfce-theme-greybird 已經過期了

### ISSUE THREAD

**Issue by NeoChen1024** [archlinuxcn/repo#354]
xfce-theme-greybird 已經過期了

archlinuxcn/xfce-theme-greybird 3.20.1-1 (xfce-themes-shimmer-collection) [installed: 3.22.0-1]
    A grey and blue Xfce theme.
aur/xfce-theme-greybird 3.22.0-1 [installed] (255) (2.16)
    A grey and blue Xfce theme.

**Comment by ykelvis** [comment]
@xhduan

**Comment by dxhisboy** [comment]
好的，等我回学校吧。。。

**Comment by dxhisboy** [comment]
已经更新过了
