### ISSUE TITLE
Orphaning clash-verge

### ISSUE THREAD

**Issue by sukanka** [archlinuxcn/repo#3554]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* clash-verge

----
`clash-verge` 原版已经停止更新了，目前有多个比较活跃的分支, 见 https://github.com/archlinuxcn/repo/issues/3550
但是由于我本身不用 `clash-verge` 了， 决定弃置。希望有使用 clash-verge 的用户接手。

**Comment by wszqkzqk** [comment]
实际上是不是把verge和verge-rev分开好一些，因为后者drop了对Premium的支持
