### ISSUE TITLE
archlinuxcn-keyring 无法安装 / archlinuxcn-keyring can't be installed

### ISSUE THREAD

**Issue by Hanatomizu** [archlinuxcn/repo#3557]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* archlinuxcn-keyring

----

请在此补充说明。
Please describe in detail here.

运行 `pacman -Sy archlinuxcn-keyring` 时出现错误  
An error occurred while running `pacman -Sy archlinuxcn-keyring`  
```sh
$ sudo pacman -Sy archlinuxcn-keyring
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
 archlinuxcn                       3.4 MiB   964 KiB/s 00:04 [#################################] 100%
resolving dependencies...
looking for conflicting packages...

Package (1)                      New Version  Net Change  Download Size

archlinuxcn/archlinuxcn-keyring  20230923-1     0.36 MiB       0.26 MiB

Total Download Size:   0.26 MiB
Total Installed Size:  0.36 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 archlinuxcn-keyring-202309...   262.7 KiB   949 KiB/s 00:00 [#################################] 100%
(1/1) checking keys in keyring                               [#################################] 100%
(1/1) checking package integrity                             [#################################] 100%
error: archlinuxcn-keyring: signature from "Jiachen YANG (Arch Linux Packager Signing Key) <farseerfc@archlinux.org>" is marginal trust
:: File /var/cache/pacman/pkg/archlinuxcn-keyring-20230923-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
```

**Comment by lilydjwg** [comment]
```
sudo pacman-key --lsign-key "farseerfc@archlinux.org"
```

https://www.archlinuxcn.org/archlinuxcn-keyring-manually-trust-farseerfc-key/

**Comment by Hanatomizu** [comment]
> ```
> sudo pacman-key --lsign-key "farseerfc@archlinux.org"
> ```
> 
> https://www.archlinuxcn.org/archlinuxcn-keyring-manually-trust-farseerfc-key/

解决了，谢谢！
Solved, thank you so much!

**Comment by DawnMagnet** [comment]
> ```
> sudo pacman-key --lsign-key "farseerfc@archlinux.org"
> ```
> 
> https://www.archlinuxcn.org/archlinuxcn-keyring-manually-trust-farseerfc-key/

我存在此问题的同时，还无法导入密钥
```
gpg: 密钥 327DD5C2A01B4587 生成于未来的 11420 秒后（可能是因为时空扭曲或系统时钟的问题）
```
通过 <https://www.archlinuxcn.org/gnupg-2-1-and-the-pacman-keyring/> 可以解决

**Comment by kingcanfish** [comment]
> ```
> sudo pacman-key --lsign-key "farseerfc@archlinux.org"
> ```
> 
> [archlinuxcn.org/archlinuxcn-keyring-manually-trust-farseerfc-key](https://www.archlinuxcn.org/archlinuxcn-keyring-manually-trust-farseerfc-key/)
这个能否添加到 readme 中呢～

**Comment by lilydjwg** [comment]
不是有个链接吗？简要介绍是给不懂中文的人看的。

**Comment by lilydjwg** [comment]
也更新 README 了。等问题最终解决的时候，需要更新的地方又多了一个……
