### ISSUE TITLE
openblas-lapack-git is out-of-date

### ISSUE THREAD

**Issue by nopyhe** [archlinuxcn/repo#356]
archlinuxcn/openblas-lapack-git v0.2.17.r370.g0a4a7e18-1
    Optimized BLAS library based on GotoBLAS2 1.13 BSD
aur/openblas-lapack 0.2.19-1 (42) (1.70)
    Optimized BLAS library based on GotoBLAS2 1.13 BSD (providing blas, 
    lapack, and cblas)

**Comment by yuyichao** [comment]
It's not out of date.
