### ISSUE TITLE
chromium-dev and chromium-dev-vaapi out-of-date

### ISSUE THREAD

**Issue by KaseiWang** [archlinuxcn/repo#357]
Why not lilac? I think our build machine is powerful enough for this.

**Comment by fqj1994** [comment]
The auto build fails for missing dependencies: nodejs............
Restarting builds.

**Comment by KaseiWang** [comment]
@fqj1994 又该编译啦。AUR 上的 PKGBUILD 应该可以直接编译出来。我已经编译了一个 chromium-dev-vaapi，开 clang 和 vaapi-patch 的。

**Comment by fqj1994** [comment]
重启机器忘记开了。明天弄

**Comment by petronny** [comment]
呃。。还没有写lilac.py吗。。
