### ISSUE TITLE
goldendict-git 包已损坏，需重新编译。

### ISSUE THREAD

**Issue by yingziwu** [archlinuxcn/repo#3570]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* goldendict-git

----

goldendict-git 包已损坏，需重新编译。

```console
$ goldendict
goldendict: symbol lookup error: goldendict: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm, version Qt_5
```

![image](https://github.com/archlinuxcn/repo/assets/22741471/9c9b44ae-24d9-497c-83e2-4c16c0c29f0a)

@masakichi

**Comment by masakichi** [comment]
Hi @yingziwu 
Can you try again if the new package fixes the issue or not?
