### ISSUE TITLE
`genymotion` needs a rebuild. 

### ISSUE THREAD

**Issue by kuasha420** [archlinuxcn/repo#3575]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* genymotion

----

请在此补充说明。

The `genymotion` package is currently segfaulting when installed from archlinuxcn repo, but works fine when built locally from AUR. Probably system libs updated after it was built. Hopefully a rebuild will fix this. 

Cheers.

**Comment by Zenvie** [comment]
See https://github.com/archlinuxcn/repo/issues/3600. This software package is not officially authorized for distribution, so the issue is closed.
