### ISSUE TITLE
python-onnx available in official repos

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#3592]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

*  python-onnx

----

https://archlinux.org/packages/extra-testing/x86_64/python-onnx/

**Comment by Zenvie** [comment]
https://github.com/archlinuxcn/repo/commit/a0e2fd338f1a2e46ca4968f0480b786a0f1790ea
