### ISSUE TITLE
[Orphaning] gitkraken

### ISSUE THREAD

**Issue by axionl** [archlinuxcn/repo#3602]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* gitkraken
----

https://github.com/archlinuxcn/repo/issues/3600

**Comment by Zenvie** [comment]
Is the package officially approved for distribution by the upstream?

**Comment by Zenvie** [comment]
https://github.com/archlinuxcn/repo/commit/bfab6055629168d8bafa9c08262566a77e4d153c
