### ISSUE TITLE
hyprland-git: `systemd` flag should be enabled by default

### ISSUE THREAD

**Issue by horror-proton** [archlinuxcn/repo#3609]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* hyprland-git

----

请在此补充说明。
Please describe in detail here.

```patch
@@ -95,7 +95,8 @@ build() {
                -D b_lto=true \
                -D b_pie=true \
                -D default_library=shared \
-               -D xwayland=enabled
+               -D xwayland=enabled \
+               -D systemd=enabled
 
        ln -sf wlroots build/subprojects/wlroots/include/wlr
        meson compile -C build
```

otherwise environment variables will not get updated properly, ref:
https://github.com/hyprwm/Hyprland/blob/4d403dac3244aab217fb9bf17a68e9a009fcadd8/src/config/ConfigManager.cpp#L2188-L2191

related aur comment: https://aur.archlinux.org/packages/hyprland-git#comment-950330

**Comment by Integral-Tech** [comment]
Fixed in commit https://github.com/archlinuxcn/repo/commit/f29330dc5c21a584e74eba256369beccd5e23350.
