### ISSUE TITLE
some rust nightly package missing provides name of their stable version

### ISSUE THREAD

**Issue by rhjdvsgsgks** [archlinuxcn/repo#3627]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* rust-std-nightly-i686-unknown-linux-gnu
* rust-std-nightly-wasm32-unknown-unknown
* rust-std-nightly-x86_64-unknown-linux-musl

----

`rust-std-nightly-i686-unknown-linux-gnu` should provide `lib32-rust-libs`

`rust-std-nightly-wasm32-unknown-unknown` should provide `rust-wasm`

`rust-std-nightly-x86_64-unknown-linux-musl` should provide `rust-musl`

**Comment by lilydjwg** [comment]
Oops, there was a mistake. Should be fixed now.
