### ISSUE TITLE
Foxit Reader is out-of-date

### ISSUE THREAD

**Issue by legendtang** [archlinuxcn/repo#363]
It says 2.3 is available on boot.

**Comment by petronny** [comment]
WIP

**Comment by legendtang** [comment]
@petronny I think the aur maintainer cannot keep the version consistent to upstream. Shall we upgrade ourselves?

**Comment by petronny** [comment]
那就发一个orphan request干掉那个maintainer...
然后我再adopt

**Comment by petronny** [comment]
Updated in 9010e04
