### ISSUE TITLE
 sing-geoip 更新检查逻辑存在问题以及 Licenses 不正确

### ISSUE THREAD

**Issue by yingziwu** [archlinuxcn/repo#3632]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* sing-geoip-common
* sing-geoip-rule-set
* sing-geoip-db

----

**更新检查逻辑存在问题**

阅读  sing-geoip 的 github  workflows [文件](https://github.com/SagerNet/sing-geoip/blob/main/.github/workflows/release.yaml)，以及 [main.go](https://github.com/SagerNet/sing-geoip/blob/main/main.go)。

不难看出 sing-geoip 的 release tag 是基于 [Dreamacro/maxmind-geoip](https://github.com/Dreamacro/maxmind-geoip) Tag 生成与更新的。
因此更新还应检测 Dreamacro/maxmind-geoip 。

---------

**Licenses 不正确**

GPL-3.0-or-later 只是 sing-geoip 打包工具的 Licenses 。
实际生成的 geoip db 的数据来源其实是 MaxMind GeoLite2 ，参考 [geoip-database](https://archlinux.org/packages/extra/any/geoip-database/) 包，Licenses 应当为 ``custom:GeoLite2 End User License Agreement``。

**Comment by Integral-Tech** [comment]
Thanks for you correction.
I just added the [Dreamacro/maxmind-geoip](https://github.com/Dreamacro/maxmind-geoip) update source in commit https://github.com/archlinuxcn/repo/commit/1de543890e3bc9c062d70a582b0da3729a190c4a, and rectify the license in commit https://github.com/archlinuxcn/repo/commit/a8add08eb46b286b442e5b9d5ec9afb77d69b557.

**Comment by yingziwu** [comment]
https://github.com/archlinuxcn/repo/blob/6c48d35e962e44b23265c0893dcc4b3d07705b5a/archlinuxcn/sing-geoip/lilac.yaml#L8-L10

``update_on`` 中 ``SagerNet/sing-geoip`` 的 ``use_latest_release`` 可能需要去除。

``SagerNet/sing-geoip`` 的 release 完全是基于 ``Dreamacro/maxmind-geoip`` 。
因此应当是 ``SagerNet/sing-geoip`` 提供打包程序（检测 git commit）， ``Dreamacro/maxmind-geoip``  提供数据源（检测 github release）。
``SagerNet/sing-geoip`` 的 ``use_latest_release`` 完全是没有必要的，而且还会造成重复更新， ``Dreamacro/maxmind-geoip``  release 之后，一段时间后 ``SagerNet/sing-geoip`` 也随之 release，进而触发两次打包。
