### ISSUE TITLE
[Package Request] linux-xanmod-edge

### ISSUE THREAD

**Issue by JaHIY** [archlinuxcn/repo#3635]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

XanMod is a general-purpose Linux kernel distribution with custom settings and new features. Built to provide a stable, responsive and smooth desktop experience.

* 主要语言和工具链 / Main Languages and Toolchains

 C

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/linux-xanmod-edge/
https://xanmod.org/

* 为何需要这个软件包 / Why Need This Package

之前由于没人维护被删了 #3038 ，现在又回来了…
照搬一下 #2634 里的理由：linux-xanmod 集成了很多提高性能降低延迟的pathches, ，更适合linux 日常桌面使用。archlinuxcn 已经有了linux-zen，据网上评测，linux-xanmod比 linux-zen延迟更低。

**Comment by ykelvis** [comment]
e64f810c98862b53bc5d2004c4938acaae523ea7
