### ISSUE TITLE
chromium-dev-vaapi out of date 

### ISSUE THREAD

**Issue by BigEars431** [archlinuxcn/repo#364]
however chromium-dev package has been updated in the archlinuxcn repo

**Comment by fqj1994** [comment]
I won't work on this fail to link(ld) issue.....
And I don't handle any out-of-date issue if the upstream doesn't build at all.
I'm only providing a faster build resource for people who don't want to build chromium-dev with/without vaapi patch on his laptop.
If you want to tackle this, just send your patch to aur/chromium-dev, the script will pull any updates and try the rebuild.

**Comment by fqj1994** [comment]
Oh, actually it's a patch hunk failure. I can take a look but I don't take any time guarantee.

**Comment by fqj1994** [comment]
done
