### ISSUE TITLE
[Package request] sing-geosite

### ISSUE THREAD

**Issue by kidonng** [archlinuxcn/repo#3650]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    Geosite database and rule sets for sing-box.

* 主要语言和工具链 / Main Languages and Toolchains

    Go

* 上游链接 / Upstream Link

    https://github.com/SagerNet/sing-geosite

* 为何需要这个软件包 / Why Need This Package

   Required by `sing-box` and related packages (e.g. `nekoray`), like `sing-geoip` which is already in `archlinuxcn`.

**Comment by Integral-Tech** [comment]
Added in commit https://github.com/archlinuxcn/repo/commit/b77547e48c5bd647f1ba7c50a2e2722de1177718.
