### ISSUE TITLE
[Package request] autofs

### ISSUE THREAD

**Issue by agilexue** [archlinuxcn/repo#3661]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description
A kernel-based automounter for Linux
    （请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains
C
    （请在此填写）

* 上游链接 / Upstream Link
https://www.kernel.org/pub/linux/daemons/autofs
    （请在此填写）

* 为何需要这个软件包 / Why Need This Package
Autofs is a tool that allows you to automatically mount file systems as needed. It is commonly used to automatically mount network file systems, such as NFS or Samba shares, when they are accessed by users or applications. Autofs can greatly simplify the management of network file systems by mounting and unmounting them dynamically as needed, rather than requiring them to be mounted all the time.
    （请在此填写）

**Comment by lilydjwg** [comment]
What about [systemd.automount](https://man.archlinux.org/man/systemd.automount.5)?

**Comment by agilexue** [comment]
> What about [systemd.automount](https://man.archlinux.org/man/systemd.automount.5)?

It's probably a good alternative. I will take the time to test thanks.
