### ISSUE TITLE
neovim-git build error

### ISSUE THREAD

**Issue by ouuan** [archlinuxcn/repo#3683]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* neovim-git

----

https://build.archlinuxcn.org/packages/#/neovim-git/logs/1709875665

Error since 2024.1.26

**Comment by SilverRainZ** [comment]
现在依赖 tree-sitter-git 了，感觉 tree-sitter 的 API 不是很稳定，不知道以后会不会频繁不可用。
