### ISSUE TITLE
 installing libplacebo-git (1:6.338.0.r116.g14699044-1) breaks dependency 'libplacebo.so=347-64' required by ffmpeg-with-libplacebo-git

### ISSUE THREAD

**Issue by 3xploiton3** [archlinuxcn/repo#3692]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* libplacebo-git

----

请在此补充说明。
Please describe in detail here.

resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing libplacebo-git (1:6.338.0.r116.g14699044-1) breaks dependency 'libplacebo.so=347-64' required by ffmpeg-with-libplacebo-git
:: installing libplacebo-git (1:6.338.0.r116.g14699044-1) breaks dependency 'libplacebo.so=347-64' required by mpv-git
 -> error installing repo packages
 
 
 different than aur repo
![image](https://github.com/archlinuxcn/repo/assets/19517680/38dbdaee-f791-4c88-a234-fa4e89b2b213)

**Comment by CoelacanthusHex** [comment]
libplacebo-git has been removed. mpv-git use libplacebo now.
