### ISSUE TITLE
nekoray 3.26-4 program does not launch, error while loading shared libraries

### ISSUE THREAD

**Issue by jieran233** [archlinuxcn/repo#3708]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* `nekoray`

----

请在此补充说明。
Please describe in detail here.

After upgrading `nekoray` to `3.26-4`, the program cannot be started. There is no exception in the previous version (`3.26-3`):

```shell
$ nekoray
nekoray: error while loading shared libraries: libabsl_log_internal_check_op.so.2401.0.0: cannot open shared object file: No such file or directory
```

**Comment by Integral-Tech** [comment]
The library ```abseil-cpp``` in [extra] repository has been updated.
Just run ```sudo pacman -Syu``` to update the system and then retry.

**Comment by jieran233** [comment]
> The library `abseil-cpp` in [extra] repository has been updated. Just run `sudo pacman -Syu` to update the system and then retry.

Thanks for your help! This solved my problem!
