### ISSUE TITLE
sunshine 无法使用nvfbc / sunshine can not use nvfbc

### ISSUE THREAD

**Issue by detiam** [archlinuxcn/repo#3712]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* sunshine

----

根据sunshine仓库中的[注释](https://github.com/LizardByte/Sunshine/blob/934f81182ac54df2d072eb5c3560156d1c96dc26/docker/archlinux.dockerfile#L37)，cuda是个可选的编译依赖，需要[安装cuda后编译来启用nvfbc支持](https://github.com/LizardByte/Sunshine/issues/2205)。

**Comment by aimixsaka** [comment]
忽然感觉这个包不应该二进制分发了... ，我考虑下把这个包从 cn 里移掉吧

**Comment by detiam** [comment]
> 忽然感觉这个包不应该二进制分发了... ，我考虑下把这个包从 cn 里移掉吧

到现在还是没有删啊，每次更新nvfbc都掉一次
