### ISSUE TITLE
flutter: 缺少了拆分出的包

### ISSUE THREAD

**Issue by Kiri2002** [archlinuxcn/repo#3723]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* flutter

----

请在此补充说明。
Please describe in detail here.

archcn的flutter同步了aur的最新版。最新版将flutter拆分出了许多包：
```
flutter-devel
flutter-target-linux
flutter-target-android
flutter-target-web
flutter-intellij-patch"
```
并作为flutter的依赖。

但aur中可以搜到拆分出的包。但是archcn中的，没有提供拆出来的包，导致flutter缺少依赖：

```
resolving dependencies...
warning: cannot resolve "flutter-devel", a dependency of "flutter"
warning: cannot resolve "flutter-target-linux", a dependency of "flutter"
warning: cannot resolve "flutter-target-android", a dependency of "flutter"
warning: cannot resolve "flutter-target-web", a dependency of "flutter"
warning: cannot resolve "flutter-intellij-patch", a dependency of "flutter"
```

**Comment by Integral-Tech** [comment]
Fixed in commit https://github.com/archlinuxcn/repo/commit/7140d514c62734f4491762b4ecfdf1b3156c5e54.
