### ISSUE TITLE
plasma5-wallpapers-dynamic 已经移植到 Plasma 6

### ISSUE THREAD

**Issue by YHYJ** [archlinuxcn/repo#3725]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* plasma5-wallpapers-dynamic

----

应该重命名为 plasma6-wallpapers-dynamic 或者 plasma-wallpapers-dynamic

**Comment by zjuyk** [comment]
嗯，按照 https://wiki.archlinux.org/title/KDE_package_guidelines#KF6_package_naming 我们应该重命名为 plasma6-wallpapers-dynamic，但最好 upstream 也重命名，我之前给 zzag 发过邮件，再等一周吧，没有进展我就直接 rename，反正目前这个包可以在 KF6 使用。
