### ISSUE TITLE
qbittorrent-enhanced-nox-git 版本错误

### ISSUE THREAD

**Issue by HinataKato** [archlinuxcn/repo#3741]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* qbittorrent-enhanced-nox-git
----
源內的版本号是 4.6.4.10.r201.g0cf9d4918
AUR的版本号是 4.6.4.10.r0.g535a622c5-1
安装源内的软件包后版本号是v4.5.5.10
从AUR安装的版本号是v4.6.4.10

**Comment by oldherl** [comment]
This package is removed
