### ISSUE TITLE
plasma6-applets-window-title version invalid

### ISSUE THREAD

**Issue by LckHot** [archlinuxcn/repo#3747]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  plasma6-applets-window-title

----

请在此补充说明。
Please describe in detail here.

The latest upstream version should be v0.5 not v0.21. In this case, v0.21is a patch of version v0.2 and far older than v0.5.

**Comment by rocka** [comment]
f476091
