### ISSUE TITLE
go-musicfox版本与应用内显示不符

### ISSUE THREAD

**Issue by LckHot** [archlinuxcn/repo#3752]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* go-musicfox

----

请在此补充说明。
Please describe in detail here.

仓库中显示go-musicfox版本为v4.3.3-1，但使用musicfox时却有通知提示有新版本v4.3.3可用，使用musicfox -V显示当前版本得到的是v3.7.0。我尝试下载PKGBUILD自己编译，效果相同。

**Comment by rannj** [comment]
通过AUR构建得到的是最新版本

**Comment by zjuyk** [comment]
不好意思，现在才回，这是因为上游做的更改，现在推荐使用他们的 Makefile 来注入版本号，我之后会手动修改 PKGBUILD

**Comment by zjuyk** [comment]
[501cec7](https://github.com/archlinuxcn/repo/commit/501cec731db02550c89f87f646c2824bb4dbe40a) 已修复等打包，另外 https://github.com/go-musicfox/go-musicfox/issues/98 这个 lastfm 你们有需要吗？我一直不用所以没加，需要在编译的时候指定

**Comment by zjuyk** [comment]
https://github.com/archlinuxcn/repo/issues/3782
