### ISSUE TITLE
nvchecker 的结果不对，导致包不更新

### ISSUE THREAD

**Issue by rydesun** [archlinuxcn/repo#377]
比如 qtile 这个包追踪的是 aur 里的，在上个月 aur 里的 qtile 已经更新到 0.10.7 了，而社区仓库里的 qtile 还停留在 0.10.6
nvchecker 在不安装 python-pycurl 的情况下，qtile 的版本是 0.10.6，安装了 python-pycurl 后正确输出了 0.10.7；似乎是 nvchecker 自身的 bug？不清楚还有没有其他包受到影响。

**Comment by lilydjwg** [comment]
我禁用了 pycurl，检测到的版本并不差别。

社区仓库中的 qtile 在 2017-02-19 09:55:48 打包失败了。cc @farseerfc

**Comment by rydesun** [comment]
嗯嗯，AUR 的 qtile 在 2017-02-18 17:34:16 (GMT) 之后更新到了版本 0.10.7-1，但确实是不能打包的，因为 checksums 不对。2017-02-20 11:17:24 (GMT) 之后 AUR 的 PKGBUILD 改正了 checksums，但 pkgrel 没有相应 +1，是不是这个原因导致了社区编译机忽略了更新呢？

**Comment by rydesun** [comment]
还有关于 nvchecker，我在一个干净的 debian 里试了试，检测出的版本还是有差别。

在 **没有 pycurl** 的前提下，使用仓库中 **完整的** nvchecker.ini，会导致 nvchecker 出错提前退出，于是包括 qtile 在内的包就没有检测版本。一定要完整的 nvchecker.ini，应该是其中有些项有问题。

我是这样做的:
```shell
echo qtile 0.10.6-1.2 > old_ver.txt
rm -f new_ver.txt
curl https://raw.githubusercontent.com/archlinuxcn/repo/master/nvchecker.ini -O
nvchecker nvchecker.ini
grep qtile new_ver.txt    # output: qtile 0.10.6-1.2, 应该为 qtile 0.10.7-1
```

**Comment by petronny** [comment]
> 2017-02-20 11:17:24 (GMT) 之后 AUR 的 PKGBUILD 改正了 checksums，但AUR上的维护者没有把 pkgrel 相应得 +1，是不是这个原因导致了社区编译机忽略了更新呢？

是。 @lilydjwg 话说可不可以用[AUR查询结果](https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=yaourt)中的LastModified代替Version返回呢？

**Comment by lilydjwg** [comment]
@petronny 好主意。但这样的话我们的 pkgrel 怎么写呢？
@rydesun 出什么样的错误了呢？

**Comment by farseerfc** [comment]
qtile 修掉了
