### ISSUE TITLE
js-beautify 与 python-jsbeautifier 有冲突。

### ISSUE THREAD

**Issue by qwIvan** [archlinuxcn/repo#379]
js-beautify的包里面，包含着有css-beautify和html-beautify，我想用css-beautify

**Comment by qwIvan** [comment]
两个包都包含了/usr/bin/js-beautify

**Comment by petronny** [comment]
我不是很能理解。这两个包已经在PKGBUILD中标记冲突了。
直接装js-beautify删掉python-jsbeautifier不就有css-beautify了吗？
如果你还想用python-jsbeautifier你可以不用官方源的，自己pip在home下装一个就行了。
如果对/usr/bin/js-beautify有其他重命名建议请到AUR反馈

**Comment by qwIvan** [comment]
我需要用mitmproxy，這個包依賴python-jsbeautifier。所以我現在只能用npm裝js-beautify，最好還是用pacman來裝吧

**Comment by petronny** [comment]
我添加了一个叫js-beautify-archlinuxcn的包
如果编译成功了可以替换js-beautify
把所有的/usr/bin/*-beautify重命名成了/usr/bin/node-*-beautify
