### ISSUE TITLE
Fix for astrometry.net for py3.12

### ISSUE THREAD

**Issue by Universebenzene** [archlinuxcn/repo#3795]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* astrometry.net

----

看了眼astrometry.net的py3.12还没rebuild成功，今收到AUR通知才发觉是numpy.distutils的问题。修复方法我在[AUR评论区](https://aur.archlinux.org/packages/astrometry.net)给了一下

简单来说就是 `prepare()` 里加一句 `sed -e "/^from numpy/c import numpy" -e 's/get_numpy_include_dirs()/[numpy.get_include()]/' -i libkd/setup{-min}.py setup-libkd.py` ，然后 `makedepends` 里加上 `python-setuptools`

另外现在 `prepare()` 里那两句netpbm支持的sed现在用不着了，因为[0.94](https://github.com/dstndstn/astrometry.net/commit/d4760e2d25aa90b2817a02610b8daf10235b3cfb)现在已经可以自动检测到已安装的netpbm了

老海尔菊苣看看这样子行不行

**Comment by oldherl** [comment]
上游其实已经修复了，但是没有发release
https://github.com/dstndstn/astrometry.net/issues/286
我等几天看看他们会不会发，不会的话我再处理吧

**Comment by Universebenzene** [comment]
对了除了netpbm以外还有件事，cfitsio有个fitsverify的二进制文件又和astrometry冲突了，也得从bin里删个fitsverify

**Comment by Universebenzene** [comment]
[0.95](http://astrometry.net/downloads/astrometry.net-0.95.tar.gz) 来了

**Comment by oldherl** [comment]
Done in 688fb2528aa67b26f18bc9477342b0ee95defc99 and 566e230d3f8d13ce118cdc303014f407b75c39d1
