### ISSUE TITLE
Package hyper

### ISSUE THREAD

**Issue by snovey** [archlinuxcn/repo#380]
A terminal built on web technologies [https://hyper.is](https://hyper.is/)

The goal of the project is to create a beautiful and extensible experience for command-line interface users, built on open web standards.

In the beginning, our focus will be primarily around speed, stability and the development of the correct API for extension authors.

In the future, we anticipate the community will come up with innovative additions to enhance what could be the simplest, most powerful and well-tested interface for productivity.

**Comment by farseerfc** [comment]
Currently it still has poor support for Chinese characters:
<img width="454" alt="screenshot_20170318_222418" src="https://cloud.githubusercontent.com/assets/861563/24072359/b138c21c-0c29-11e7-9d06-c51f9e862729.png">
And  its menubar depends on global menu, which have several issues with eletron.
Will wait until it get more mature.

**Comment by snovey** [comment]
Thanks for your trial.
I hope it can join into arch repository in the near future.
