### ISSUE TITLE
zfs-dkms-git pkgbuild gets wrong source dir.

### ISSUE THREAD

**Issue by GoopyKibbles** [archlinuxcn/repo#3800]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* zfs-dkms-git

----

Description: 
The currently used PKGBUILD was modified in commit #3519c13 to "create missing directories in package()". 
![Screenshot_20240505_042734](https://github.com/archlinuxcn/repo/assets/155962259/e25f3a58-0d9c-4185-bdc8-e7e1d306d1d4)

the diff viewer suggests that the `dkmsdir` value was changed from `${pkgdir}/usr/src/zfs-${pkgver}` to `${pkgdir}/usr/src/zfs`. This change breaks the automatic dkms module build & install perfomed by pacman when the zfs-dkms-git package is installed.

![Screenshot_20240505_043653](https://github.com/archlinuxcn/repo/assets/155962259/d5c8d30b-7d15-4c1b-b4e4-a41b5679bfcb)

According to the DKMS package guideline in Archwiki, the source files should be installed to `/usr/src/$PKGNAME-$PKGVER`. In our case, it should be `dkmsdir="/usr/src/_MODULE_NAME_-_PKGVERSION_"`, which means `/usr/src/zfs-${pkgver}`. This should resolve this issue. (tested by modifying the PKGBUILD, it resolves the above issue.)

**Comment by Integral-Tech** [comment]
Fixed in commit https://github.com/archlinuxcn/repo/commit/8ae4acc5c5332ec4d213aec3f6eff323dfdf4dd0
