### ISSUE TITLE
python-sip4 replaces itself

### ISSUE THREAD

**Issue by oldherl** [archlinuxcn/repo#3806]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* python-sip4

----

```
package_python-sip4() {
  pkgdesc="Python SIP4 bindings for C and C++ libraries"
  depends=(python)
  provides=(python-sip4)
  replaces=(python-sip4)
```

This is strange. Package should not provides or replaces itself.

**Comment by Integral-Tech** [comment]
Fixed in commit https://github.com/archlinuxcn/repo/commit/7a46cc667f244ed1d2962b55aca76d1d76b39c13 & https://github.com/archlinuxcn/repo/commit/5716daf0d212fdbb79556af2e0f571d5c96178e2
