### ISSUE TITLE
mpv-git is out of date. should use github = mpv-player/mpv instead of aur =

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#381]
I have mpv-git installed, but it always complains that it was compiled against a different version of ffmpeg than what it's linked to. That's because it's almost never being updated.

```
[mpv-git]
aur =
```

should be replaced with 

```
[mpv-git]
github = mpv-player/mpv
```

And, similar changes should be made for the other git stuff by the same packager.

**Comment by lilydjwg** [comment]
All vcs packages should track upstream instead of AUR, because AUR packages almost never update in this case.
