### ISSUE TITLE
Unresolvable flutter-related dependencies

### ISSUE THREAD

**Issue by cuihaoleo** [archlinuxcn/repo#3814]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* flutter-common
* dart
* flutter-engine-android-google-bin
* flutter-engine-common-google-bin
* flutter-engine-linux-google-bin
* flutter-engine-web-google-bin
----

```
:: Starting full system upgrade...
resolving dependencies...
warning: cannot resolve "flutter-common=3.22.0", a dependency of "flutter-engine-common-google-bin"
warning: cannot resolve "dart>=3.4.0", a dependency of "flutter-engine-common-google-bin"
warning: cannot resolve "flutter-engine-common=3.22.0", a dependency of "flutter-engine-android-google-bin"
warning: cannot resolve "flutter-common=3.22.0", a dependency of "flutter-engine-common-google-bin"
warning: cannot resolve "dart>=3.4.0", a dependency of "flutter-engine-common-google-bin"
warning: cannot resolve "flutter-common=3.22.0", a dependency of "flutter-engine-common-google-bin"
warning: cannot resolve "dart>=3.4.0", a dependency of "flutter-engine-common-google-bin"
warning: cannot resolve "flutter-engine-common=3.22.0", a dependency of "flutter-engine-linux-google-bin"
warning: cannot resolve "flutter-common=3.22.0", a dependency of "flutter-engine-common-google-bin"
warning: cannot resolve "dart>=3.4.0", a dependency of "flutter-engine-common-google-bin"
warning: cannot resolve "flutter-engine-common=3.22.0", a dependency of "flutter-engine-web-google-bin"
:: The following packages cannot be upgraded due to unresolvable dependencies:
      flutter-engine-android-google-bin  flutter-engine-common-google-bin  flutter-engine-linux-google-bin
      flutter-engine-web-google-bin

:: Do you want to skip the above packages for this upgrade? [y/N]
```

**Comment by w568w** [comment]
Flutter 3.22.0 打包失败，因为当时声明依赖项 Dart 3.4.0 还未进入 extra：

```
==> Installing missing dependencies...
error: target not found: dart>=3.4.0
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> dart>=3.4.0
  -> dart<3.5.0
  -> jq
  -> gradle
  -> unzip
==> ERROR: Could not resolve all dependencies.
==> ERROR: Build failed, check /var/lib/archbuild/extra-x86_64/lilac-1/build
```

目前，该依赖项已就位，因此应当重新尝试打包。

**Comment by Integral-Tech** [comment]
Fixed.

**Comment by w568w** [comment]
Regressed in `3.24.0-1`: https://build.archlinuxcn.org/imlonghao-api/pkg/flutter/log/1723034499

**Comment by cuihaoleo** [comment]
@w568w 不要挖坟。新出问题就开新 issue。

另外我已经放弃 flutter 包了。直接装 home 就好（

**Comment by w568w** [comment]
> 不要挖坟。新出问题就开新 issue。

已经开到 #3985。

另外，我不记得 GitHub Issues 有中文互联网论坛的「挖坟」说法。如果这记录在任何本组织或仓库的书面规则中，请告诉我。

> 另外我已经放弃 flutter 包了。直接装 home 就好（

由于你是组织 member，我是否可以将此作为本仓库对 `flutter` 包的正式弃置声明？若如此，我就不会再发布任何相关 issue 报告了。

**Comment by cuihaoleo** [comment]
> 另外，我不记得 GitHub Issues 有中文互联网论坛的「挖坟」说法，在同一 issue 下报告回归是常见的。如果这记录在任何本组织或仓库的书面规则中，请告诉我。

我不认为在已解决/Closed issue 下报告新的问题是常见行为。[也并非只有中文互联网排斥挖坟](https://communitybuilding.stackexchange.com/questions/2632/why-do-internet-forums-tend-to-prohibit-responding-to-inactive-threads)。

没有书面规则，所以并没有强制力，是个人建议。但正确使用 issue 有助于您的问题受到关注。您可以预料到，维护者会优先关注 open or assigned issues，而 closed issues 默认是被排除掉的。尽管回复有邮件提醒，但这邮件提醒是埋没在大量 GitHub 通知之中的。

> 
> > 另外我已经放弃 flutter 包了。直接装 home 就好（
> 
> 由于你是组织 member，我是否可以将此作为本仓库对 `flutter` 包的正式弃置声明？若如此，我就不会再发布任何相关 issue 报告了。

并不能，因为我不是这个包的维护者。
