### ISSUE TITLE
llvm-git packages are not being added to the repo

### ISSUE THREAD

**Issue by SolarAquarion** [archlinuxcn/repo#3824]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----

请在此补充说明。
Please describe in detail here.

llvm-git packages are not being added to the repo.  I wonder if it's a bug with lilac or something.

**Comment by lilydjwg** [comment]
What do you mean? They are in the repo.

**Comment by oldherl** [comment]
This package is removed
