### ISSUE TITLE
qt5-webkit needs rebuild for newer icu

### ISSUE THREAD

**Issue by oldherl** [archlinuxcn/repo#3832]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* qt5-webkit

----
This does not build at the moment because newer icu requires C++17 while (dead) qt5-webkit uses C++11.

You might find these comments on AUR helpful, though: https://aur.archlinux.org/packages/qt5-webkit

**Comment by ykelvis** [comment]
Looks like latest aur commit fixed this. I tried with goldendict-git (depends on qt5-webkit) everything works fine.
