### ISSUE TITLE
Miktex启动错误

### ISSUE THREAD

**Issue by Jontyshaw** [archlinuxcn/repo#3833]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* miktex

----

无法启动，报错如下

/opt/miktex/bin/miktex-console: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /opt/miktex/bin/miktex-console)
/opt/miktex/bin/miktex-console: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /opt/miktex/bin/../lib/libmiktex-ui-Qt.so.2)
/opt/miktex/bin/miktex-console: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /opt/miktex/bin/../lib/libmiktex-packagemanager.so.11)
/opt/miktex/bin/miktex-console: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /opt/miktex/bin/../lib/libmiktex-core.so.30)
/opt/miktex/bin/miktex-console: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /opt/miktex/bin/../lib/libmiktex-trace.so.5)
/opt/miktex/bin/miktex-console: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /opt/miktex/bin/../lib/../lib/libmiktex-extractor.so.2)

**Comment by oldherl** [comment]
@Jontyshaw 你当前的 miktex 版本号是多少？

**Comment by waarmond** [comment]
@Jontyshaw libstdc++.so.6 is part of gcc-libs

**Comment by heavysink** [comment]
应该早就好了吧
