### ISSUE TITLE
wezterm-git-20240520.135708.b8f94c47-2-x86_64和ncurses6.5-2冲突

### ISSUE THREAD

**Issue by Kzinux** [archlinuxcn/repo#3838]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* wezterm-git

----

文件冲突导致更新无法完成。
![2024-05-24_10-12](https://github.com/archlinuxcn/repo/assets/7030257/10dccfdd-f31c-411e-8bf3-f570460f647d)

**Comment by ykelvis** [comment]
Related https://github.com/wez/wezterm/issues/5464

**Comment by oldherl** [comment]
@ykelvis You can just remove this file from the wezterm package and use the file from ncurses package

**Comment by Kzinux** [comment]
extra源的wezterm也是像oldherl说的那样不依赖wezterm-terminfo了。
https://gitlab.archlinux.org/archlinux/packaging/packages/wezterm/-/issues/2
