### ISSUE TITLE
aarch64版本的neovim-git和tree-sitter-git缺少签名文件

### ISSUE THREAD

**Issue by btstream** [archlinuxcn/repo#3848]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* neovim-git
* tree-sitter-git

----

请在此补充说明。

这两个包的arrch64仓库缺少签名文件

**Comment by lilydjwg** [comment]
gpg key 过期了，正在续期。

**Comment by lilydjwg** [comment]
修好了。
