### ISSUE TITLE
执行repo sync或git fetch或git clone拉取安卓仓库的大文件时，会出现Bad packet length xxxx错误，然后终端就一直输出Finished discarding for

### ISSUE THREAD

**Issue by yangbin1265712** [archlinuxcn/repo#3857]
### 问题类型 / Type of issues
我执行repo sync或git fetch或git clone拉取安卓仓库的大仓库时（有些仓库有60G左右），会出现Bad packet length错误，然后终端就一直输出Finished discarding for

* 其它 / other
repo sync或git fetch或git clone时无法下载大文件，每次下载到大的仓库时，都会出现bad packet length xxxx
![image](https://github.com/archlinuxcn/repo/assets/20549499/ca106318-f458-422f-af0e-caeb5c095b82)
![image](https://github.com/archlinuxcn/repo/assets/20549499/1b6f4587-8479-41d6-9399-ad881eef29b6)

### 受影响的软件包 / Affected packages
* 无

----

以下是一些系统信息：
system info："Ubuntu 20.04.6 LTS"
CPU: 32
Threads: 2
Memory:125G
$repo version

repo launcher version 2.45
(from /usr/bin/repo)
git 2.25.1
Python 3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0]
OS Linux 5.15.0-60-generic ([#66](https://github.com/archlinuxcn/repo/issues/66)~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023)
CPU x86_64 (x86_64)
Bug reports: https://issues.gerritcodereview.com/issues/new?component=1370071

**Comment by oldherl** [comment]
你这个问题和本仓库 (archlinuxcn 打包源) 看似没有任何关系。

**Comment by oldherl** [comment]
你这个名叫repo的软件，报bug的地址在你贴的信息的里写着呢：
> Bug reports: https://issues.gerritcodereview.com/issues/new?component=1370071

**Comment by yangbin1265712** [comment]
> 你这个名叫repo的软件，报bug的地址在你贴的信息里写着呢：
> 
> > Bug reports: https://issues.gerritcodereview.com/issues/new?component=1370071

好的，谢谢，那提错地方了
