### ISSUE TITLE
Iptv

### ISSUE THREAD

**Issue by taysonlzz** [archlinuxcn/repo#3867]

**Comment by taysonlzz** [comment]
#EXTM3U
#EXTINF:-1,Globo Nat Geo
https://live-as-11-31.video.globo.com/j/eyJhbGciOiJSUzUxMiIsImtpZCI6IjEiLCJ0eXAiOiJKV1QifQ.eyJjb3VudHJ5X2NvZGUiOiJCUiIsImRvbWFpbiI6ImxpdmUtYXMtMTEtMzEudmlkZW8uZ2xvYm8uY29tIiwiZXhwIjoxNzE4MzIyNjAwLCJpYXQiOjE3MTgyMzYyMDAsImlzcyI6InBsYXliYWNrLWFwaS1wcm9kLWdjcCIsIm93bmVyIjoiOWM3NTQ0YjAtMzM0Mi00NzQ5LTk0YzItNWMyMWVhYWQ1ZDIzIiwicGF0aCI6Ii9udS9mKGJNaW49MjAwMCkvZ2xvYm8tbmF0L3BsYXlsaXN0Lm0zdTgifQ.rKAzs0Uc676KgaWY4vuJAnARHdohQcc-RGx_IFl3unfv65OV6nelZ41IlHy8eS4e8Wj5dRkQB6DJCZyBt-q46WZDG1mmF57tUJLt7xW4f_Oyp199gXDnqRtiHsz_eu-RRbQeDao04cruShoHJrDkN-ep-w9XQefYR9ukQqnQVZA5XXR2Pkjs1GqWer-PDfC8a6t6GPNNShDdxNOmpRKQREO6sIklWKlk0tSoz-t4LlIwD0R_Yl78pJA3dCZHuXemD2yAxGulabySy8xtZgKUGVjpxcHypne6LTlqRm9UoOTVfLr5QrSm9O55Fhj-V5w3feQWmdyR2kLQ_gXzzXT14g/nu/f(bMin=2000)/globo-nat/globo-nat-audio_1=96000-video=3442944.m3u8

#EXTINF:-1,goku
https://mega.nz/file/RQlF3JRQ#kiRj7Nw6MC1okLkH-FnMLAtN-djqgnVP4TDp9jK8nbk

#EXTINF:-1,o dublê
https://drive.usercontent.google.com/download?id=1e4ypDqTix68kXDZO7SqhE5VhifYEFrQT&export=download&authuser=0&confirm=t&uuid=c9d21063-c047-40f9-9503-32a7deb0ab47&at=APZUnTXVYPqEEdkAkXvMqDHvXZUh%3A1718252175271

#EXTINF:-1,niro.
#EXTINSP:#000000
#EXTVLCOPT:http-skip=0,http-reconnect=1,http-max-redirect=100
#EXTURL:#https://mega.nz/file/UVsXybLT#YvyaLz9Z5nB0twpoFkIs_TiIEeJ-oBkvOStVxBqJLyI

#EXTINF:-1,niro.1
blob:https://mega.nz/befdca10-2cc9-49c1-9ad0-2aea86cff320

#EXTINF:-1,free fire
https://storage.googleapis.com/brandify-usercontent-dev/7ba00db3-6706-4fa1-9e8b-66c0bc091367?Expires=1718297999&GoogleAccessId=GOOG1EQYYUCN45RGYHGLHRS57FY5LN3ZFJOZEUIRTNHTBDZURLXQ4KVCAN4BI&Signature=QfqWRBzwsSBHTM6IZUsOYNe9BDs%3D%0A

**Comment by oldherl** [comment]
Spam.
