### ISSUE TITLE
Package Request: redlib

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [archlinuxcn/repo#3872]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    Reddit 的第三方前端，前身为 libreddit

* 主要语言和工具链 / Main Languages and Toolchains

    Rust / Cargo

* 上游链接 / Upstream Link

    * https://github.com/redlib-org/redlib
    * https://aur.archlinux.org/packages/redlib

* 为何需要这个软件包 / Why Need This Package

    现有实例有时速度不佳，想自建

**Comment by Integral-Tech** [comment]
x86-64: https://github.com/archlinuxcn/repo/commit/63e71d56a9cff3f447243529a4440c6a45d5d13e
aarch64: https://github.com/archlinuxcn/repo/commit/bf4c1bb330a61d05557e87e19434e31972a17066
