### ISSUE TITLE
cpu-x should add rebuild rule

### ISSUE THREAD

**Issue by oldherl** [archlinuxcn/repo#3873]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* cpu-x

----
should rebuild on libpci
```
~ $ cpu-x
pci_access 未正确初始化：这一问题在 CPU-X 由较低版本的 libpci 构建时很常见。
检查你的系统中存在 libpci 3.12.0 库。否则请重新构建 CPU-X。
路径  中没有驱动图形卡的内核驱动程序
您的 GPU 用户模式驱动程序对于供应商 AMD 是未知的: 4.6 (Compatibility Profile) Mesa 24.1.1-arch1.1
```

**Comment by Integral-Tech** [comment]
I have adopted the ```cpu-x``` package and fixed the issue in commit https://github.com/archlinuxcn/repo/commit/9c5e7eda45dd3317bc474b8f55b37cdace2e2a50.
