### ISSUE TITLE
hyprlang-git 需要 provide libhyprlang.so

### ISSUE THREAD

**Issue by moetayuko** [archlinuxcn/repo#3875]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* hyprlang-git

----

许多软件包的依赖项是 `libhyprlang.so` 而不是 `hyprlang`，因此 `hyprlang-git` 需要 provide libhyprlang.so

https://gitlab.archlinux.org/archlinux/packaging/packages/hyprlang/-/blob/main/PKGBUILD?ref_type=heads#L13
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hyprlang-git#n14

**Comment by moetayuko** [comment]
```
错误：无法准备事务处理 (无法满足依赖关系)
:: 安装 hyprlang-git (0.5.2.r2.gec6938c-1) 破坏依赖 'libhyprlang.so=2-64' （hyprcursor 需要）
:: 安装 hyprlang-git (0.5.2.r2.gec6938c-1) 破坏依赖 'hyprlang>=0.4.0' （hypridle-git 需要）
:: 安装 hyprlang-git (0.5.2.r2.gec6938c-1) 破坏依赖 'libhyprlang.so=2-64' （hyprland-hidpi-xprop-git 需要）
:: 安装 hyprlang-git (0.5.2.r2.gec6938c-1) 破坏依赖 'hyprlang>=0.4.0' （hyprlock-git 需要）
:: 安装 hyprlang-git (0.5.2.r2.gec6938c-1) 破坏依赖 'libhyprlang.so=2-64' （hyprpaper 需要）
```

**Comment by Integral-Tech** [comment]
Fixed in commit https://github.com/archlinuxcn/repo/commit/e52cba648dd3a3f109ff911bed340c69e2e01fb7.

**Comment by moetayuko** [comment]
@Integral-Tech 刚才忘了提，provide hyprlang 的版本号需要把 pkgver 里的 r 后面一截扔掉，具体参考 aur

**Comment by moetayuko** [comment]
> @Integral-Tech 刚才忘了提，provide hyprlang 的版本号需要把 pkgver 里的 r 后面一截扔掉，具体参考 aur

```
错误：无法准备事务处理 (无法满足依赖关系)
:: 安装 hyprlang-git (0.5.2.r2.gec6938c-2) 破坏依赖 'hyprlang>=0.4.0' （hypridle-git 需要）
:: 安装 hyprlang-git (0.5.2.r2.gec6938c-2) 破坏依赖 'hyprlang>=0.4.0' （hyprlock-git 需要）
```
