### ISSUE TITLE
hyprlang-git 提供的版本号需要去掉后缀

### ISSUE THREAD

**Issue by moetayuko** [archlinuxcn/repo#3878]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* hyprlang-git

----

provide hyprlang 的版本号需要把 pkgver 里的 r 后面一截扔掉
```
错误：无法准备事务处理 (无法满足依赖关系)
:: 安装 hyprlang-git (0.5.2.r2.gec6938c-2) 破坏依赖 'hyprlang>=0.4.0' （hypridle-git 需要）
:: 安装 hyprlang-git (0.5.2.r2.gec6938c-2) 破坏依赖 'hyprlang>=0.4.0' （hyprlock-git 需要）
```
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hyprlang-git#n13

**Comment by Integral-Tech** [comment]
Fixed in commit https://github.com/archlinuxcn/repo/commit/c8a5815d6a3f2c1e2be05d2e600b52af4bfcbd12.
