### ISSUE TITLE
python-cupy是否被移除了?

### ISSUE THREAD

**Issue by Shengyis** [archlinuxcn/repo#3886]
### 问题类型 / Type of issues
* 其它 / other
### 受影响的软件包 / Affected packages
* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* python-cupy
----
想确认python-cupy是否被移除? 几周前安装每问题. 现在pacman -Si python-cupy搜索不到了

**Comment by oldherl** [comment]
是
#3866
