### ISSUE TITLE
python-scikit-image needs rebuild with numpy 2.0

### ISSUE THREAD

**Issue by Universebenzene** [archlinuxcn/repo#3887]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* python-scikit-image
----

请在此补充说明。

numpy更新以后应该有很多包受到影响需要rebuild。目前我遇到cn源里的就有skimage，如果不重编译的话import一些模块会报错，如：

```python
import skimage.data 

# 报错
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

我试了下rebuild应该是能解决的

**Comment by oldherl** [comment]
python-scikit-image manually rebuilt.

**Comment by Universebenzene** [comment]
又发现了另一个包 `python-rasterio` ，这个倒不是np 2.0的问题，是gdal更新库版本变化了，目前报错：

```python
import rasterio._vsiopener

ImportError: libgdal.so.34: cannot open shared object file: No such file or directory
```

也是 @hubutui 提交的包

**Comment by oldherl** [comment]
> 又发现了另一个包 `python-rasterio` ，这个倒不是np 2.0的问题，是gdal更新库版本变化了，目前报错：
> 
> ```python
> import rasterio._vsiopener
> 
> ImportError: libgdal.so.34: cannot open shared object file: No such file or directory
> ```
> 
> 也是 @hubutui 提交的包

python-rasterio 1.4a3-3 rebuilt

**Comment by Universebenzene** [comment]
又遇到一个： `python-imagecodecs`

```python
import imagecodecs._ljpeg
# 报错
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

依然还是 @hubutui 的包
