### ISSUE TITLE
package kubernetes

### ISSUE THREAD

**Issue by emctoo** [archlinuxcn/repo#389]
Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications, more info at https://kubernetes.io/

USTC has setup a mirror, request for the support in archlinuxcn.

AUR at https://aur.archlinux.org/packages/kubernetes/

**Comment by SilverRainZ** [comment]
The PKGBUILD of Kubernetes on AUR can not be built :-(

**Comment by SilverRainZ** [comment]
FYI: http://paste.debian.net/975734/

**Comment by SilverRainZ** [comment]
No response, closed.
