### ISSUE TITLE
orphaning meta-rules-dat, tcp-brutal-dkms, python-ufonormalizer, afdko, v2ray-rules-dat for Zenvie

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#3897]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* meta-rules-dat
* tcp-brutal-dkms
* v2ray-rules-dat

----
Adopted:
* python-ufonormalizer
* afdko

These packages were cleaned up during the 2024 cleanup (#3849). If any maintainers want to adopt any of them, it's time to take action!

**Comment by oldherl** [comment]
Adopted    python-ufonormalizer and    afdko

**Comment by Kiri2002** [comment]
Adopted meta-rules-dat
