### ISSUE TITLE
orphaning pacman-pstatus, trilium-bin for renyuneyun

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#3912]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* pacman-pstatus
* trilium-bin

----

These packages were cleaned up during the 2024 cleanup (#3849). If any maintainers want to adopt any of them, it's time to take action!

**Comment by renyuneyun** [comment]
抱歉有一段时间没关注。这两个包我目前仍然在使用，所以也会继续维护。
似乎是直接关掉这个issue就可以了对吧？
