### ISSUE TITLE
orphaning 7 packages for ykelvis

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#3920]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* megasync
* obkey-git
* libpdfium-nojs
* makemkv
* opera-beta
* opera-developer
* sonixd

----

These packages were cleaned up during the 2024 cleanup (#3849). If any maintainers want to adopt any of them, it's time to take action!

**Comment by oldherl** [comment]
A new package megasync-oldherl (maintained by me) is added as a fork of megasync. It has removed PDF preview support and does not depend on libpdfium-nojs anymore.
