### ISSUE TITLE
libplacebo 更新导致 moonlight-qt 不可用

### ISSUE THREAD

**Issue by Aalivexy** [archlinuxcn/repo#3934]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* moonlight-qt

----

`extra/libplacebo 7.349.0-1` [更新](https://gitlab.archlinux.org/archlinux/packaging/packages/libplacebo/-/commit/1a609bedd9ac8e46b6b7a7f60045ebad2437b23a)之后，`moonlight-qt` 运行会报错：

```
moonlight: error while loading shared libraries: libplacebo.so.338: cannot open shared object file: No such file or directory
```

**Comment by hubutui** [comment]
rebuild一下就好了

**Comment by oldherl** [comment]
已经rebuild过了（我不是包维护者）

**Comment by privacyadmin** [comment]
New user here. I have the same problem

How do I rebuild moonlight?
