### ISSUE TITLE
Package paper-icon-theme-git 

### ISSUE THREAD

**Issue by Matrikslee** [archlinuxcn/repo#394]
warning: paper-icon-theme-git: local (729.579e9aab-1) is newer than archlinuxcn (545.e456a0d-1)
my local package installed from AUR.
the package of archlinuxcn repo version isn't new enough.

**Comment by SilverRainZ** [comment]
`Inkn <i at inkn dot ml>` 这位是谁啊？ @lilydjwg @farseerfc

**Comment by petronny** [comment]
这个人已经各种找不到了。。。我改了一下，明天看看吧

**Comment by petronny** [comment]
Updated in 16b71c1e78ddf
