### ISSUE TITLE
GitHub 用户 berberman 未公开 Email 地址

### ISSUE THREAD

**Issue by oldherl** [archlinuxcn/repo#3968]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* arch-hs-git

----
arch-hs-git 的 maintainers 信息有误

以下 maintainers 信息有误，请修正。

GitHub 用户 berberman 未公开 Email 地址

**Comment by berberman** [comment]
已修复。
