### ISSUE TITLE
qadwaitadecorations-qt is packaged by "Unknown Packager"

### ISSUE THREAD

**Issue by oldherl** [archlinuxcn/repo#3969]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* qadwaitadecorations-qt

----
qadwaitadecorations-qt is packaged by "Unknown Packager", probably uploaded manually. Please fix the packager name.
Also, it is failed when trying to build with lilac.

**Comment by tttturtle-russ** [comment]
I've dropped this package due to my personal reason, so it may be removed from archlinuxcn soon.

**Comment by oldherl** [comment]
fixed with #4002
