### ISSUE TITLE
Orphaning yuzu-early-access. yuzu-git, yuzu-mainline-git

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#3974]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* yuzu-early-access
* yuzu-git
* yuzu-mainline-git
----

 dmca'd by nintendo. They are no longer compiling and I cannot find a way to make it work.

**Comment by heavysink** [comment]
已救活。

**Comment by oldherl** [comment]
@heavysink 那么 #3674 解决了吗
