### ISSUE TITLE
Orphaning anbox-git, zarchive-git and libpthread-stubs

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#3977]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* anbox-git
* zarchive-git
* libpthread-stubs
----
anbox-git is deprecated long time ago...

zarchive is now provided in official repo

libpthread-stubs is not useful and cannot build a long time ago.

**Comment by oldherl** [comment]
Shouldn't anbox-image be deprecated as well?

**Comment by oldherl** [comment]
libpthread-stubs was deprecated in 4a555dc25e63639ccecb15932f510d17d078b815 and you don't need to orphan it again
