### ISSUE TITLE
Unable to build flutter due to unresolvable dependencies

### ISSUE THREAD

**Issue by w568w** [archlinuxcn/repo#3985]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* flutter
* flutter-common
* flutter-engine-android-google-bin
* flutter-engine-common-google-bin
* flutter-engine-linux-google-bin
* flutter-engine-web-google-bin

----

Logs: https://build.archlinuxcn.org/imlonghao-api/pkg/flutter/log/1723034499

这是 #3814 的回归。

**Comment by Integral-Tech** [comment]
[extra/dart](https://archlinux.org/packages/extra/x86_64/dart), which is in the official repository, hasn't been updated to 3.5.0. Therefore, we have to wait for its update.

**Comment by Aalivexy** [comment]
Before solving this problem, maybe we need to roll back the `flutter-*-bin` package in archlinuxcn that has successfully packaged version 3.24 to version 3.22?
Because the packages in the flutter meta-package are actually interdependent and can only be upgraded or downgraded together

**Comment by mzwing** [comment]
> [extra/dart](https://archlinux.org/packages/extra/x86_64/dart), which is in the official repository, hasn't been updated to 3.5.0. Therefore, we have to wait for its update.

[extra/dart](https://archlinux.org/packages/extra/x86_64/dart) was just updated to `3.5.1-1`, maybe it's time to resolve this issue?

**Comment by Aalivexy** [comment]
Well, in fact, this problem has not been solved yet. The delayed update of `dart` still leads to different versions of `flutter-*-bin` packages in archlinuxcn.
