### ISSUE TITLE
Hyprland-git should not depend on 500M vulkan-validation-layers

### ISSUE THREAD

**Issue by jilen** [archlinuxcn/repo#3986]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

hyprland-git

----

使用了archlinux官方的pgkbuild。
实际上hyprland不需要vulkan-validation-layer(装完500多兆)。
可以参考aur里PKGBUILD

**Comment by Integral-Tech** [comment]
But in the official repository, [extra/hyprland](https://archlinux.org/packages/extra-testing/x86_64/hyprland) depends on [vulkan-validation-layers](https://archlinux.org/packages/extra/x86_64/vulkan-validation-layers/)

**Comment by Integral-Tech** [comment]
Fixed in commit https://github.com/archlinuxcn/repo/commit/d5d66485d459259bb7f073633e3bb73fce4caab0.
