### ISSUE TITLE
Orphaning: qadwaitadecorations-qt

### ISSUE THREAD

**Issue by tttturtle-russ** [archlinuxcn/repo#3988]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* qadwaitadecorations-qt

----
I decide to stop maintaining this package due to my personal reason.

**Comment by everyx** [comment]
@tttturtle-russ 你好，我愿意接收此包，已提交 PR https://github.com/archlinuxcn/repo/pull/4002

**Comment by lilydjwg** [comment]
有 orphaning issue 的时候，直接改 maintainer、关 issue 就好啦。

**Comment by oldherl** [comment]
包没修好。请确认修好后再关。

**Comment by everyx** [comment]
已修复 cea6bfc646bcc2314abc757dd830c836eb1defb8
