### ISSUE TITLE
Package "toilet" is out of date

### ISSUE THREAD

**Issue by NeoChen1024** [archlinuxcn/repo#400]

**Comment by farseerfc** [comment]
Current version is `archlinuxcn/toilet 0.3.r155.3eb9d58-1` which is the same on AUR.
It is updated  by lilac https://github.com/archlinuxcn/repo/commit/5f68dcf47740cb617f17bbf734862de62881654b#diff-4568c103426a8464217007d9c4225caf .
Where is the newer version?

**Comment by NeoChen1024** [comment]
But I have 0.3.3eb9d58-2.

**Comment by zsrkmyn** [comment]
@NeoChen1024 check the mirror you use. Does it sync with upstream correctly? Have you tried `-Syy` with `pacman`? Which mirror are you using?
Please provide more details.

**Comment by farseerfc** [comment]
We have http://repo.archlinuxcn.org/x86_64/toilet-0.3.r155.3eb9d58-1-x86_64.pkg.tar.xz in our repo.
If you see the warning like:
`warning: toilet: local (0.3.3eb9d58-2) is newer than archlinuxcn (0.3.r155.3eb9d58-1)`
, please update it using `sudo pacman -Su toilet` or with double update: `sudo pacman -Syuu` .
The AUR packager of `toilet` changed the versioning schema, which caused this warning.
