### ISSUE TITLE
ncurses5-compat-libs 已经不在 archcn 仓库，为什么还要留着 lib32-ncurses5-compat-libs 呢？

### ISSUE THREAD

**Issue by unknowndevQwQ** [archlinuxcn/repo#4004]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* lib32-ncurses5-compat-libs

----

只是询问一下，因为 64 位版本并不存在于 archcn 仓库，想了解有哪个软件包在依赖 32 位的

**Comment by oldherl** [comment]
一个库不一定是被依赖才被放到 [archlinuxcn] 中来的。

至于还要不要留着那就看维护者还想不想维护吧
