### ISSUE TITLE
micromamba 遇到依赖版本冲突

### ISSUE THREAD

**Issue by handsomexdd1024** [archlinuxcn/repo#4017]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* micromamba

----

micromamba 依赖于libfmt.so-10, 但官方仓库已经把fmt包升级至11.0.2, 于是micromamba与其他依赖于fmt的包（如android-tools）产生依赖冲突。

**Comment by oldherl** [comment]
https://github.com/mamba-org/mamba/pull/3429
上游fix

**Comment by oldherl** [comment]
Fixed in d42ba19ad6fb44ca79e3815ab59501778a7c5bf8
