### ISSUE TITLE
The telegram-desktop need libicuuc.so.58

### ISSUE THREAD

**Issue by whoisnian** [archlinuxcn/repo#402]
When I use telegram-desktop, I get an error.   
`$telegram-desktop`  
`telegram-desktop: error while loading shared libraries: libicuuc.so.58: cannot open shared object file: No such file or directory`  
Then I run `sudo find . -name "libicuuc*" -print`, and I only find  
`./usr/lib/libicuuc.so.59`  
`./usr/lib/libreoffice/program/libicuuc.so.57`  
`./usr/lib/libicuuc.so.59.1`  
`./usr/lib/libicuuc.so`

**Comment by farseerfc** [comment]
We are rebuilding `telegram-desktop`.
Meanwhile you can switch to `telegram-desktop-systemqt` or  `telegram-desktop-systemqt-notoemoji`, those are not affected by the icu update.

**Comment by farseerfc** [comment]
fixed in f8a9d0a63f9602b206c4acef07a20c4fd7474ac0
