### ISSUE TITLE
Pandoc-bin doesn't provide pandoc-cli

### ISSUE THREAD

**Issue by wu-yufei** [archlinuxcn/repo#4038]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* pandoc-bin

----

Pandoc-bin 只 provides pandoc， [zettlr](https://archlinux.org/packages/extra/x86_64/zettlr/) 等软件包依赖 pandoc-cli，无法使用 pandoc-bin 满足依赖。而 [AUR 中的 pandoc-bin](https://aur.archlinux.org/packages/pandoc-bin) provides pandoc 和 pandoc-cli。

**Comment by heavysink** [comment]
#4110
