### ISSUE TITLE
redlib: 需要打 patch

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [archlinuxcn/repo#4040]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* redlib

----

最近 Redlib 实例无法从 Reddit 上获取内容，根据上游 issues [可能是依赖问题所致](https://github.com/redlib-org/redlib/issues/229#issuecomment-2358770760)，之后降级了相关依赖以解决相关问题（https://github.com/redlib-org/redlib/commit/793047f63f0f603e342c919bbfc469c7569276fa ）但截止目前尚未正式发版。

目前 AUR 包已经加入对应 patch，或许可以考虑从 AUR 上抓 PKGBUILD，或者追加一个/换成 -git 包。

**Comment by Integral-Tech** [comment]
- archlinuxcn/redlib-git added in https://github.com/archlinuxcn/repo/commit/ac9905f72bcef6b83ee3dbc7fe6c440501a5e81d.
- alarmcn/redlib-git added in https://github.com/archlinuxcn/repo/commit/526552556061cac703a4d01d7ff75bc4e5ee1a18
