### ISSUE TITLE
sentencepiece need to be rebuilt

### ISSUE THREAD

**Issue by scratch-er** [archlinuxcn/repo#4057]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* sentencepiece
* python-sentencepiece

----

sentencepiece in archlinuxcn is current built against libprotobuf-lite.so.27.3.0. However, the libprotobuf-lite.so in the official repo has been upgraded to 28.2.0-64, which breaks sentencepiece and python-sentencepiece in archlinuxcn. This package has to be rebuilt against the new version of protobuf.

**Comment by oldherl** [comment]
I just manually triggered a rebuild. Hope it fixes for now.

**Comment by oldherl** [comment]
@hubutui still needs to add the rule

**Comment by scratch-er** [comment]
> I just manually triggered a rebuild. Hope it fixes for now.

The problem is solved now. However I will not close this issue right now. Please close this issue after the rule is added.
