### ISSUE TITLE
A spotify's problem about openssl

### ISSUE THREAD

**Issue by ouyangshi** [archlinuxcn/repo#407]
/usr/share/spotify/spotify: /usr/lib/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /usr/share/spotify/spotify)
/usr/share/spotify/spotify: /usr/lib/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /usr/share/spotify/spotify)
/usr/share/spotify/spotify: /usr/lib/libcurl.so.3: no version information available (required by /usr/share/spotify/spotify)

**Comment by ykelvis** [comment]
Updated, should run well now.
