### ISSUE TITLE
miktex failing again 构建失败

### ISSUE THREAD

**Issue by bryango** [archlinuxcn/repo#4076]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
* miktex
----

请在此补充说明。
Please describe in detail here.

Build history: https://build.archlinuxcn.org/packages/#/miktex
Log not found, probably garbage collected?

Old version no longer works due to `boost-libs -> 1.86` bump:
```console
pdflatex: error while loading shared libraries: libboost_locale.so.1.83.0: cannot open shared object file: No such file or directory
```
~~Trying to build locally.~~ Local build success.
~~正在尝试本地构建。~~ 本地构建成功。

**Comment by bryango** [comment]
Friendly ping @heavysink

**Comment by heavysink** [comment]
目前是上游有问题，无法解决。

**Comment by heavysink** [comment]
修好了
