### ISSUE TITLE
orphaning python-ydata-profiling and its deps

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#4080]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* python-ydata-profiling
* python-dacite
* python-visions
* python-imagehash
* python-missingno
* python-multimethod
* python-tangled-up-in-unicode
* python-phik

----

* python-wordcloud taken by @lilydjwg

**Comment by lilydjwg** [comment]
I've taken python-wordcloud.
