### ISSUE TITLE
looking-glass-rc lacks a suitable '-march='

### ISSUE THREAD

**Issue by roaldclark** [archlinuxcn/repo#4083]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* looking-glass-rc

----

The looking-glass-rc package built on the packaging server cannot run on my computer (Intel i5-12400):
```
$ looking-glass-client
Illegal instruction (core dumped)
```

**Comment by merrkry** [comment]
Ok new build should be in the repo.

I currently don't have a way to test. So if it works you can close as you want.

btw, as the upstream isn't really keen on push their work to releases, maybe we should consider package `-git` instead.
