### ISSUE TITLE
hyprland-git 错误提示

### ISSUE THREAD

**Issue by Nojike** [archlinuxcn/repo#4090]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----hyprland-git

请在此补充说明。
Please describe in detail here.
![message1](https://github.com/user-attachments/assets/215c6a35-f0bb-4981-93c1-d87186db8f1a)
问题如图所述。

**Comment by Integral-Tech** [comment]
I have fixed it in commit https://github.com/archlinuxcn/repo/commit/0593d96ca46825cb6afc5ab05dbf8dc5c075b136.
After updating `hyprland-git` to `0.44.0.r126.e58e97b0-2`, let me know if the problem persists.

**Comment by sakarie9** [comment]
> I have fixed it in commit [0593d96](https://github.com/archlinuxcn/repo/commit/0593d96ca46825cb6afc5ab05dbf8dc5c075b136). After updating `hyprland-git` to `0.44.0.r126.e58e97b0-2`, let me know if the problem persists.

`hyprland-git-0.44.0.r126.e58e97b0-2`

错误：无法提交处理 (有冲突的文件)
hyprland-git: 文件系统中存在 /usr/share/xdg-desktop-portal/hyprland-portals.conf （由 xdg-desktop-portal-hyprland-git 所有）

**Comment by Integral-Tech** [comment]
> > I have fixed it in commit [0593d96](https://github.com/archlinuxcn/repo/commit/0593d96ca46825cb6afc5ab05dbf8dc5c075b136). After updating `hyprland-git` to `0.44.0.r126.e58e97b0-2`, let me know if the problem persists.
> 
> `hyprland-git-0.44.0.r126.e58e97b0-2`
> 
> 错误：无法提交处理 (有冲突的文件) hyprland-git: 文件系统中存在 /usr/share/xdg-desktop-portal/hyprland-portals.conf （由 xdg-desktop-portal-hyprland-git 所有）

Fixed in `0.44.0.r126.e58e97b0-3`
