### ISSUE TITLE
Rebuild needed for seafile-client

### ISSUE THREAD

**Issue by zodiacg** [archlinuxcn/repo#410]
After recent update, running seafile-applet will give:
`seafile-applet: relocation error: seafile-applet: symbol _Znwm, version Qt_5 not defined in file libQt5WebEngineCore.so.5 with link time reference`

According to [seafile-client on AUR](https://aur.archlinux.org/packages/seafile-client)

> eolianoe commented on 2017-05-05 08:30
>@gnacho: a rebuild should fix the issue.

**Comment by yuyichao** [comment]
AUR rel bumped. Wait for autoupdate.
