### ISSUE TITLE
shaderc-non-semantic-debug needs rebuild

### ISSUE THREAD

**Issue by Kimiblock** [archlinuxcn/repo#4102]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* shaderc-non-semantic-debug

----

The repo version of shaderc-non-semantic-debug hasn't been rebuilt in a while, and causes `mpv-git` to crash when playing audio with a cover art. Rebuilding does fix the issue. Thus this package needs a rebuild.

**Comment by lilydjwg** [comment]
Rebuild has failed.

**Comment by Kimiblock** [comment]
I don't think PCSX2 needs this package anymore. Regular shaderc should work and aur/pcsx2-git is using that.

**Comment by heavysink** [comment]
#4108
