### ISSUE TITLE
proton: error in lilac.yaml 

### ISSUE THREAD

**Issue by oldherl** [archlinuxcn/repo#4109]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* proton

----

In proton/lilac.yaml, `pre_build: aur_pre_build(maintainers=['loathingkernel'])` leads to an error:

> AttributeError: module 'lilac2.api' has no attribute 'aur_pre_build(maintainers=['loathingkernel'])'

It should be `pre_build_script`, not `pre_build`.

**Comment by oldherl** [comment]
As you can see, lilac can't even assign heavysink to this issue, because it can't parse this yaml.

**Comment by heavysink** [comment]
40a26f8
