### ISSUE TITLE
`chromium-dev-vaapi` fails to start

### ISSUE THREAD

**Issue by legendtang** [archlinuxcn/repo#411]
`/usr/lib/chromium-dev/chromium-dev: error while loading shared libraries: libwebp.so.6: cannot open shared object file: No such file or directory`

The libwebp library has updated and I found only `libwebp.so.7` exists. Please have a look! @fqj1994

**Comment by fqj1994** [comment]
Will rebuild tomorrow.
In the meanwhile, you can try ln it back to libwebp.so.6 if you need to use it urgently.

**Comment by legendtang** [comment]
Thank you for the response. I know ln will work and any updates?
