### ISSUE TITLE
fcitx5-pinyin-moegirl-rime 请求更名为 rime-pinyin-moegirl

### ISSUE THREAD

**Issue by DeepChirp** [archlinuxcn/repo#4113]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* fcitx5-pinyin-moegirl-rime

----

建议将`fcitx5-pinyin-moegirl-rime`更名为`rime-pinyin-moegirl`。因为当前的包名称具有误导性。rime不是fcitx独有的，ibus-rime也可以使用它。同时，官方仓库中有类似命名的[fcitx5-pinyin-zhwiki](https://archlinux.org/packages/extra/any/fcitx5-pinyin-zhwiki/)和[rime-pinyin-zhwiki](https://archlinux.org/packages/extra/any/rime-pinyin-zhwiki/)。

**Comment by DeepChirp** [comment]
@imlonghao 感谢更新，不过目前仓库中似乎没有对应的包了，可能得手动处理一下。

**Comment by imlonghao** [comment]
我已经触发了重新构建，稍后可再次观察一下构建情况

**Comment by DeepChirp** [comment]
> 我已经触发了重新构建，稍后可再次观察一下构建情况

似乎仍然没有正常生成对应的包，<https://repo.archlinuxcn.org/>中也没有找到。比rebuild晚的action所构建的包似乎都推送上去了。可能还得麻烦看一下。

**Comment by lilydjwg** [comment]
因为被触发的是定时器，还没到时候……我使用 [triggerabuild](https://build.archlinuxcn.org/triggerabuild/) 触发了一下，现在包已经打出来了。下次 @imlonghao 也可以用 triggerabuild 更及时地触发构建。
