### ISSUE TITLE
去除 albert 的多余的可选依赖

### ISSUE THREAD

**Issue by Sving1024** [archlinuxcn/repo#4115]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* albert
* albert-git

----

> Please remove the entire python-* dependencies. Since 0.26.3 the python env is entirely isolated. System packages are not considered anyway.

https://aur.archlinux.org/packages/albert?O=0#comment-989941

**Comment by Integral-Tech** [comment]
`albert` fixed in commit https://github.com/archlinuxcn/repo/commit/fb4c93c36515c1a1b99246286e92f21a52f9fac3
`albert-git` fixed in commit https://github.com/archlinuxcn/repo/commit/191ec77ee6536dde9c0fcd6b10c70037911889b1
