### ISSUE TITLE
python-dict2xml 打包错误

### ISSUE THREAD

**Issue by ouuan** [archlinuxcn/repo#4130]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* python-dict2xml

----

log:

- https://build.archlinuxcn.org/imlonghao-api/pkg/python-dict2xml/log/1734988114
- https://build.archlinuxcn.org/~imlonghao/#python-dict2xml

原因似乎是 https://aur.archlinux.org/packages/python-noseofyeti 和 https://aur.archlinux.org/packages/python-alt-pytest-asyncio 互相作为 check dependency，循环依赖处理出错。

**Comment by roaldclark** [comment]
The package has been updated, please check
