### ISSUE TITLE
Package android-support

### ISSUE THREAD

**Issue by psamim** [archlinuxcn/repo#414]
Hi,
Can we have this package?

https://aur.archlinux.org/packages/android-support/

Thanks

**Comment by lijinpei** [comment]
I wonder how (by archlinuxcn-x86_64-build, extra-x86_64-build or multilib-extra-build) to build a package A(android-support), which depends on a package B(android-sdk) which is in archlinuxcn repo and depends on multilib packages?
When I do archlinuxcn-x86_64-build, it can't find lib32 packages.

**Comment by farseerfc** [comment]
@lijinpei we have `multilib-archlinuxcn-build` for this, provided by `devtools-cn-git`

**Comment by lijinpei** [comment]
thx~ @farseerfc 
package added
51eb7027e50f5cefa8a31fc902b6b2d51129a83d
directly added from aur, **## not tested**, please use them with care and give feedback if any problem

**Comment by lilydjwg** [comment]
@lijinpei you can also use a `depends` variable to specify dependencies inside this repo. Using `archlinuxcn-*` may have delays and/or wrong build order.
