### ISSUE TITLE
请求添加软件包cockpit

### ISSUE THREAD

**Issue by Arondight** [archlinuxcn/repo#416]
[AUR](https://aur.archlinux.org/packages/cockpit/)

**Comment by lijinpei** [comment]
directly added 4 packages from aur
5ebe8558bf9d383c464707d4624f1f514953cc30
f1bcb7b52c5244a87457961e311892632233e559
b984cb85127c35b4c193129cc9df37d2ab4ecfd6
111a67450ab6d99b30024dc5f8980366534f274f
please give feedback if any problem
