### ISSUE TITLE
lib32-qt4请求添加

### ISSUE THREAD

**Issue by burningkernel** [archlinuxcn/repo#417]
https://aur.archlinux.org/packages/lib32-qt4/

**Comment by renyuneyun** [comment]
打算收養，不過自動化更新有個障礙：
`lib32-qt`依賴的`lib32-libmng`要用特別的key驗證完整性，不在keyring中。

如何讓lilac信任這個key以便自動更新呢？

**Comment by zsrkmyn** [comment]
如果指的是PKGBUILD里的validpgpkeys的话lilac会自动接收的应该。

2017年6月3日 01:47，"renyuneyun" <notifications@github.com>写道：

**Comment by renyuneyun** [comment]
嗯……那應該什麼都不用做了。

我先直接原封不動從aur拿到倉庫，如果不行的話看報錯再解決好了

**Comment by renyuneyun** [comment]
應該可以關了 6e5a5e3b9590afd337380280a548803f399aa2c7
