### ISSUE TITLE
cp something to /home/repo folder?

### ISSUE THREAD

**Issue by lijinpei** [archlinuxcn/repo#420]
When uploading something to cn repo(by cp something.pkg.tar.xz and something.pkg.tar.xz.sig to /home/repo), will something check that what I copied to /home/repo looks like package and signature? If someone mistakely copy other things to /home/repo, will there be some remediation?

**Comment by yuyichao** [comment]
I believe there's a white list pattern. Only packages that exists in this repo can be uploaded. I believe this is also a trusted environment and members are expected to do things reasonably

**Comment by lijinpei** [comment]
That's good, I think typo often happens: "cp something.pkg.tar.xz *"

**Comment by SilverRainZ** [comment]
https://github.com/archlinuxcn/misc_scripts/blob/master/pullpkg#L17

**Comment by lilydjwg** [comment]
The script just checks the filename. And packages that aren't in this repo will be removed soon.
If you put something there by mistake, just clean it up later.
