### ISSUE TITLE
希望添加xmind

### ISSUE THREAD

**Issue by sunraysun** [archlinuxcn/repo#429]
目前community中是老版本，新版本已经是 XMind 8。

**Comment by ouyangshi** [comment]
这个你应该去官方仓库里提 cn源里不会添加官方仓库已有的软件包

2017年5月24日 18:58，"孙登甲" <notifications@github.com>写道：

**Comment by ouyangshi** [comment]
@felixonmars 这只猫的包

**Comment by SilverRainZ** [comment]
@ouyangshi felix 已经 diown 这个包了，就看有没有其他 TU 收留它。

**Comment by ouyangshi** [comment]
没注意qwq

2017年5月29日 13:38，"谷月轩" <notifications@github.com>写道：

**Comment by SilverRainZ** [comment]
xmind 已经从官方源被移除了，而且在 AUR 也尚未有维护者，要是 AUR 有人主动维护的话再开 issue 吧……
