### ISSUE TITLE
Invalid or corrupted package

### ISSUE THREAD

**Issue by 3rso** [archlinuxcn/repo#430]
Hi,

Im trying to update sudo pacman -Syu, but im getting this error: 

File /var/cache/pacman/pkg/archlinuxcn-keyring-20170522-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.

If i say yes to delete it it doesnt work, who can i fix it?

**Comment by ouyangshi** [comment]
Try to update archlinux-keyring
sudo pacman -S archlinux-keyring

2017年5月25日 00:39，"3rso" <notifications@github.com>写道：

**Comment by farseerfc** [comment]
The `archlinuxcn-keyring` package is signed by me. Do you have any problem when installing my other packages in the community repo? [Here is a list of packages in community of mine](https://www.archlinux.org/packages/?sort=&q=&maintainer=farseerfc&flagged=)

**Comment by lilydjwg** [comment]
Keep the package then `sha1sum` it. It should be `d6647990f54050940598286be5d5a516642aef8b`.

**Comment by 3rso** [comment]
HI this works for me: sudo pacman -S archlinux-keyring

**Comment by gylove1994** [comment]
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/47300853/204107315-b81ab884-ba70-47f8-86cd-348c684fae6c.png">
I run ``sudo pacman -S archlinux-keyring`` and updated it but I still have this problem.

**Comment by SilverRainZ** [comment]
@gylove1994 it seems that you are running Pacman on steam deck. it would be better to file an new issue and provide more details (like above, your mirror, your repo, the package's checksum)

**Comment by gylove1994** [comment]
> @gylove1994 it seems that you are running Pacman on steam deck. it would be better to file an new issue and provide more details (like above, your mirror, your repo, the package's checksum)

Thanks for your reply! I opened a new issue with more info on #3047.
