### ISSUE TITLE
gnome-shell-extension-dash-to-dock-git-59.r20.g28d765a 右键弹出菜单位置错误

### ISSUE THREAD

**Issue by zhkailing** [archlinuxcn/repo#443]
gnome-shell-extension-dash-to-dock-git-59.r20.g28d765a 右键弹出菜单位置错误，并且弹出无法取消，恢复旧版正常

**Comment by petronny** [comment]
请到https://github.com/micheleg/dash-to-dock 反馈

**Comment by zhkailing** [comment]
请fetch最新代码
