### ISSUE TITLE
chromium-dev and chromium-dev-vaapi out of date

### ISSUE THREAD

**Issue by BigEars431** [archlinuxcn/repo#446]
[See Title]

Thank you guys :))

**Comment by chih7** [comment]
请问这两个包是怎么回事？aur已经更新了啊，这里不是自动构建的吗？

**Comment by SilverRainZ** [comment]
@chih7 这两个包并不是，包目录下包含 `lilac.py` 的才会自动更新。

**Comment by BigEars431** [comment]
The two packages are chromium-dev and chromium-dev-vaapi (I don't speak Chinese). Chromium-dev-vaapi is manually updated I believe...

**Comment by fqj1994** [comment]
Which means either
1) the 32-core VM used to build chromium related packages is down
or
2) The AUR ver doesn't build
I'll check on Monday.

**Comment by fqj1994** [comment]
Fixed. None of the 2 above. Installing dependencies failed...
