### ISSUE TITLE
AUR upstream not found for kvantum-kde4-colorscheme-svn

### ISSUE THREAD

**Issue by SilverRainZ** [archlinuxcn/repo#460]

**Comment by frantic1048** [comment]
AUR 那边他们已经把这个包删了，我们这边看起来也只能去掉这个包了。

话说去掉一个包大概是怎么操作呢？

**Comment by SilverRainZ** [comment]
从这个 repo 里面把这个包的相关文件以及 nvchecker.ini 的对应项删了就好。07.08.2017, 10:57, "Jiahao Guo" <notifications@github.com>:AUR 那边他们已经把这个包删了，我们这边看起来也只能去掉这个包了。
话说去掉一个包大概是怎么操作呢？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Best regards,Shengyu Zhang

**Comment by frantic1048** [comment]
https://github.com/archlinuxcn/repo/commit/fee7c176d4384a1fc8fb1e5166c713385a62fc8e

话说这 issue 应该可以关咯？

**Comment by SilverRainZ** [comment]
可以了。
