### ISSUE TITLE
firefox-kde-opensuse out of date

### ISSUE THREAD

**Issue by marhkb** [archlinuxcn/repo#463]
55.0-1 is available

**Comment by JiajunW** [comment]
最近没时间管理手上的包，有人接手吗？

另外有什么方法暂时 disown 掉我所有的包 @lilydjwg

**Comment by petronny** [comment]
看了一下你的4个包只有这个没有交给lilac
那就也交给lilac好了

**Comment by JiajunW** [comment]
firefox-kde-opensuse 也有 lilac.py 不知道为什么跑挂了，暂时没时间去看……

**Comment by petronny** [comment]
PKGBUILD有点问题，我反馈给AUR了，等上游修了应该就行了？

**Comment by lilydjwg** [comment]
@JiajunW 你要怎么 disown 呢？如果是希望有人接管的话，开个 issue。如果希望 lilac 不管的话，把 lilac.py 改名。

**Comment by petronny** [comment]
诶，我收到了一个空的报错邮件来着。。。一直没看。。。
居然打包成功了？

**Comment by lilydjwg** [comment]
空的报错？

嗯，我看最近一次打包成功了。
