### ISSUE TITLE
Package request: v2ray-core

### ISSUE THREAD

**Issue by axionl** [archlinuxcn/repo#468]
Pkgdesc: A platform for building proxies to bypass network restrictions.

---

[Github ->](https://github.com/v2ray/v2ray-core)

[AUR ->](https://aur.archlinux.org/packages/v2ray/)

But the AUR package is **out of date** and  the new release is released for more than one day.

[Latest release: 2.34 ->](https://github.com/v2ray/v2ray-core/releases)

**Comment by heavysink** [comment]
It is here.

**Comment by ouyangshi** [comment]
It is here 
[https://github.com/archlinuxcn/repo/commit/30ac0be770fddff44ce635ed33c4f38c4e6ec480](url)
