### ISSUE TITLE
Dropping atom-editor

### ISSUE THREAD

**Issue by felixonmars** [archlinuxcn/repo#47]
If anyone want to maintain atom-editor, please reply me here. Otherwise I am going to remove this package after 2 weeks.

**Comment by farseerfc** [comment]
adopting atom-editor.

But I may wait until v0.182 is tagged.

**Comment by farseerfc** [comment]
adopted by commit https://github.com/archlinuxcn/repo/commit/596c5ab67fa036868a1e870b8b1234d3cea00f77
