### ISSUE TITLE
pre-commit script skip some nvchecker.ini sanity checks

### ISSUE THREAD

**Issue by VOID001** [archlinuxcn/repo#470]
https://github.com/archlinuxcn/repo/blob/4365e806a70891232fc3d0f47ee97c2e87a508a6/pre-commit#L79
Here we skip the check,  and commented that "37 packages violate this"

But then we cannot use pre-commit hook to check nvchecker when adding new pacakges

Maybe we need to fix  37 violations then make it work again?

**Comment by lilydjwg** [comment]
fixed by 7df82f9cf8cac5312bce48ee2f608a4f67579359
