### ISSUE TITLE
firefox-nightly-zh-cn无法通过desktop文件启动

### ISSUE THREAD

**Issue by helmholts** [archlinuxcn/repo#473]
https://github.com/archlinuxcn/repo/blob/f3ba3506d7731529f01bfb0f3b5b45faa80e8929/firefox-nightly-zh-cn/firefox-nightly-zh-cn.desktop#L5

而`PKGBUILD`内的
```
pkgname=${_name}-${_channel}-zh-cn
ln -s "/${OPT_PATH}/${_name}" "${pkgdir}"/usr/bin/${pkgname}
```

希望修改`desktop`文件内的`Exec`部分

**Comment by zsrkmyn** [comment]
已反馈到 AUR。
https://aur.archlinux.org/packages/firefox-nightly-zh-cn/#comment-608644

**Comment by zeromake** [comment]
@helmholts @zsrkmyn 我看了一下你反馈的跟我aur上维护的根本不是一个东西。
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firefox-nightly-zh-cn#n45

**Comment by lilydjwg** [comment]
这个包已经不在了。
