### ISSUE TITLE
Package request: gnucash

### ISSUE THREAD

**Issue by psamim** [archlinuxcn/repo#479]
https://aur.archlinux.org/packages/gnucash/

**Comment by colinkeenan** [comment]
Wow - I didn't realize gnucash had been dropped from the official repos. I will definitely package this right now since I use it daily.

**Comment by colinkeenan** [comment]
`webkitgtk2` is quite a dependency. This is going to take a really long time to package. I'm doing it though.

**Comment by colinkeenan** [comment]
Done
