### ISSUE TITLE
Out-of-date {bin,lib}x32-* packages

### ISSUE THREAD

**Issue by felixonmars** [archlinuxcn/repo#48]
Most of {bin,lib}x32-* packages were never updated after their addition on over half a year ago.

@fantix Are you going to update them any time soon, or drop them altogether?

**Comment by fantix** [comment]
I'll update them.

**Comment by fantix** [comment]
Updated.

**Comment by felixonmars** [comment]
Thanks!

On Mon, Mar 2, 2015 at 5:37 PM, Fantix King <notifications@github.com>
wrote:

> Updated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archlinuxcn/repo/issues/48#issuecomment-76682231>.
>



-- 

Regards,
Felix Yan

**Comment by fantix** [comment]
Thanks for pushing too! :D
