### ISSUE TITLE
google-earth out of date，需要升级成google earth pro

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#491]
NOTE: The "Free" Google Earth has been dropped: https://support.google.com/earth/answer/168344?hl=en

All future updates go to Google Earth Pro (also free): https://aur.archlinux.org/packages/google-earth-pro/

升级成pro吧

**Comment by ouyangshi** [comment]
added [#1](https://github.com/archlinuxcn/repo/commit/62775c621ea4a19015c7878c0bca881735105277)
那个旧版的是不是得移除？

**Comment by heavysink** [comment]
不知道呢，先留着吧

**Comment by lilydjwg** [comment]
旧的 replace 掉呗。
