### ISSUE TITLE
[firefox-nightly] 设置默认语言匹配系统

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#493]
创建一个 vendor.js，设置

```javascript
pref("intl.locale.matchOS", true);
```

吧。这样不用手动改语言了。

**Comment by KenOokamiHoro** [comment]
added in commit https://github.com/archlinuxcn/repo/commit/79c566c6490364fb7d0adb2c9db015ddfa983e00 :smiley:

**Comment by lilydjwg** [comment]
@KenOokamiHoro 改动消失了。因为文件是从 AUR 上弄回来的。

**Comment by petronny** [comment]
你需要通过lilac.py修改

**Comment by KenOokamiHoro** [comment]
😂 那就是说咱该去AUR 提comment ？

**Comment by lilydjwg** [comment]
@KenOokamiHoro 嗯。

**Comment by KenOokamiHoro** [comment]
https://github.com/archlinuxcn/repo/commit/e1061c5e9720ec2b06dc02ced7b4c709c70ad1c6 AUR 的 maintainer 不理咱于是不管啦不让lilac 跟 AUR 啦 😂

**Comment by lilydjwg** [comment]
It works!
