### ISSUE TITLE
Rebuild needed for gnome-perl and some other perl packages

### ISSUE THREAD

**Issue by AstroProfundis** [archlinuxcn/repo#496]
`shutter` is broken on my system, complaining missing of Gnome2.pm. Accroding to the [comment](https://aur.archlinux.org/pkgbase/shutter/?comments=all) of AUR page, it's related to the recent perl path change and rebuild of perl packages are needed.

These 6 packages below are my output of `pacman -Qqo '/usr/lib/perl5/vendor_perl'`, and rebuilding them fixes the problem:

    gnome-perl
    gnome-vfs-perl
    gnomecanvas-perl
    perl-gnome2-wnck
    perl-gtk2-imageview
    perl-gtk2-unique

There might be more in the repo, for `shutter` or some other packages...

**Comment by lilydjwg** [comment]
gnome-perl is still broken @VOID001

**Comment by lilydjwg** [comment]
It's fixed.
