### ISSUE TITLE
chromium-dev-vaapi out of date

### ISSUE THREAD

**Issue by legendtang** [archlinuxcn/repo#499]

**Comment by petronny** [comment]
chromium-dev现在也过期了

**Comment by Chermnyx** [comment]
Vaapi is avalible by default in chromium 62, this package is not needed

**Comment by legendtang** [comment]
@Chermnyx Thank you. We should retire this package.

**Comment by petronny** [comment]
90cb64f

**Comment by legendtang** [comment]
@Chermnyx Is there any reference on how to enable that?

**Comment by Chermnyx** [comment]
You can enable this in `chrome://flags/#enable-accelerated-video` (`chromium-dev` package)
Only work with Intel GPU. It also can be used with `libva-vdpau-driver-chromium`, but `libva-vdpau-driver-chromium` is very unstable.
