### ISSUE TITLE
google-earth-pro的lilac.py需要把extra-x86_64换成archlinuxcn-x86_64

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#515]
否则ld-lsb的依赖无法满足～

**Comment by ouyangshi** [comment]
咦……… lilac怎么没邮件给我………疏忽了。包夜没自动打（回去补

2017年9月26日 05:00，"巨型沉箱" <notifications@github.com>写道：

**Comment by heavysink** [comment]
多打了个-build...
