### ISSUE TITLE
请加入moonplayer

### ISSUE THREAD

**Issue by levinit** [archlinuxcn/repo#521]
https://github.com/coslyk/moonplayer
该播放器使用mpv+you-get，播放和下载相关支持的网站的在线视频‘

另外有插件moonplayer-plugins 添加了一些网站如bilibili番剧 搜狐视频等等  https://github.com/coslyk/moonplayer-plugins

---
moonplayer和插件的aur包：
- https://aur.archlinux.org/packages/moonplayer
- https://aur.archlinux.org/packages/moonplayer-plugins/

**Comment by heavysink** [comment]
加了

**Comment by levinit** [comment]
@heavysink 
>错误：moonplayer：缺失签名
错误：无法提交处理 (软件包缺失签名)

还没加入到archlinuxcn-keyring?（是要加入这个吗？）

**Comment by heavysink** [comment]
@levinit 

我的签名怎么又崩了...等等我，我重新签一次
