### ISSUE TITLE
archlinuxcn-keyrings导入失败

### ISSUE THREAD

**Issue by updater1234** [archlinuxcn/repo#522]
==> ERROR: 5984EA8F3C6C92945EB2EE40BE378C0A19C6421B could not be locally signed.
  -> Locally signing key 7028E1F320C45EE98473B1C35F1BC1A1BF2B11D0...
==> ERROR: 7028E1F320C45EE98473B1C35F1BC1A1BF2B11D0 could not be locally signed.
  -> Locally signing key F905932C85D705FD2A3CC9E47C63370395FF0792...
==> ERROR: F905932C85D705FD2A3CC9E47C63370395FF0792 could not be locally signed.
  -> Locally signing key C41D545A576AC1FE4DBE90C9B6CF41D1879E8002...
==> ERROR: C41D545A576AC1FE4DBE90C9B6CF41D1879E8002 could not be locally signed.
  -> Locally signing key C7C94A10985C93D4A9141594D9458EF92FE6A447...
==> ERROR: C7C94A10985C93D4A9141594D9458EF92FE6A447 could not be locally signed.
  -> Locally signing key F357BC80BE28C292B40ECEC8997995DF61A0959A...
==> ERROR: F357BC80BE28C292B40ECEC8997995DF61A0959A could not be locally signed.
  -> Locally signing key 243C14E5339E1B88EDCB29C595FC83B3084A5ADD...
==> ERROR: 243C14E5339E1B88EDCB29C595FC83B3084A5ADD could not be locally signed.
  -> Locally signing key D2DE8CCA1E74D572369F4C699207632BD48BDDAA...
==> ERROR: D2DE8CCA1E74D572369F4C699207632BD48BDDAA could not be locally signed.
  -> Locally signing key D88390B2991F8242FABD2A3C07F45E2A1937DD32...
==> ERROR: D88390B2991F8242FABD2A3C07F45E2A1937DD32 could not be locally signed.
  -> Locally signing key 4FAE5F3EFB9ADABEE8753427A87A225CA0B4B1A4...
==> ERROR: 4FAE5F3EFB9ADABEE8753427A87A225CA0B4B1A4 could not be locally signed.
  -> Locally signing key AA0CBF3859E580B97D9F04638FDE3D8FC99F40AE...
==> ERROR: AA0CBF3859E580B97D9F04638FDE3D8FC99F40AE could not be locally signed.
  -> Locally signing key 70522E06662E87A6024E6A6EA22A42A4BA266106...
==> ERROR: 70522E06662E87A6024E6A6EA22A42A4BA266106 could not be locally signed.
  -> Locally signing key 00e716120987a801cd25070828d10c49a44f261e...
==> ERROR: 00e716120987a801cd25070828d10c49a44f261e could not be locally signed.
  -> Locally signing key 9BE836747F3533EAABA99F1485AEA2926167AD32...
==> ERROR: 9BE836747F3533EAABA99F1485AEA2926167AD32 could not be locally signed.
  -> Locally signing key 4CFF42599833CF3AE98A2F098850CBC20940E3F9...
==> ERROR: 4CFF42599833CF3AE98A2F098850CBC20940E3F9 could not be locally signed.
  -> Locally signing key 0285FB6900D102030550F20A34908FFBC0BFAC35...
==> ERROR: 0285FB6900D102030550F20A34908FFBC0BFAC35 could not be locally signed.
  -> Locally signing key 02E02B85AF209AA00F784A1DD48313B447CD9E46...
==> ERROR: 02E02B85AF209AA00F784A1DD48313B447CD9E46 could not be locally signed.
  -> Locally signing key 3167205DC1F2582F226007FAB012733142D79E59...
==> ERROR: 3167205DC1F2582F226007FAB012733142D79E59 could not be locally signed.
  -> Locally signing key 99399D88F7B752BF364CD485A85E3925A6211F05...
==> ERROR: 99399D88F7B752BF364CD485A85E3925A6211F05 could not be locally signed.
  -> Locally signing key 86EEEC214D245137446F4AB195304B04071CCDB4...
==> ERROR: 86EEEC214D245137446F4AB195304B04071CCDB4 could not be locally signed.
  -> Locally signing key 356690A1E7404E30D0E902B2E64D049594A54F54...
==> ERROR: 356690A1E7404E30D0E902B2E64D049594A54F54 could not be locally signed.
  -> Locally signing key B5971F2C5C10A9A08C60030F786C63F330D7CB92...
==> ERROR: B5971F2C5C10A9A08C60030F786C63F330D7CB92 could not be locally signed.
  -> Locally signing key 83F817213361BF5F02E7E124F9F9FA97A403F63E...
==> ERROR: 83F817213361BF5F02E7E124F9F9FA97A403F63E could not be locally signed.
  -> Locally signing key CF3271E49632068A5DCA9316719D54FFDDD310E2...
==> ERROR: CF3271E49632068A5DCA9316719D54FFDDD310E2 could not be locally signed.
  -> Locally signing key 708DFB13CBED9AB39449DBFB41C04120C297B594...
==> ERROR: 708DFB13CBED9AB39449DBFB41C04120C297B594 could not be locally signed.
  -> Locally signing key 4A6D297E6F74638E4D5F8E99152AC7B5F7608B26...
==> ERROR: 4A6D297E6F74638E4D5F8E99152AC7B5F7608B26 could not be locally signed.
  -> Locally signing key 2AC4CFDB42972D38F105800BC0EB1AA4536A8318...
==> ERROR: 2AC4CFDB42972D38F105800BC0EB1AA4536A8318 could not be locally signed.
  -> Locally signing key 1B53ED6B05A88B45FE02AE6186CC4303D870877E...
==> ERROR: 1B53ED6B05A88B45FE02AE6186CC4303D870877E could not be locally signed.
  -> Locally signing key 4B1DE545A801D4549BFD3FEF90CB3D62C13D4796...
==> ERROR: 4B1DE545A801D4549BFD3FEF90CB3D62C13D4796 could not be locally signed.
  -> Locally signing key CF73A9AE20AD483CE51130E0303A369BE11E4BE7...
==> ERROR: CF73A9AE20AD483CE51130E0303A369BE11E4BE7 could not be locally signed.
  -> Locally signing key 90403E12F4CE5E0E950E4AD2C96492E347202001...
==> ERROR: 90403E12F4CE5E0E950E4AD2C96492E347202001 could not be locally signed.
怎么解决？

**Comment by farseerfc** [comment]
1. 保證時鐘正確 ，檢查 `timedatectl status`
2. `rm -rf /etc/pacman.d/gnupg` 
3. `pacman-key --init `
4. `pacman-key --populate archlinux && pacman-key --populate archlinuxcn`

如果還不能解決，請發這裏 https://github.com/archlinuxcn/archlinuxcn-keyring/issues

**Comment by updater1234** [comment]
It works. Thank you.
