### ISSUE TITLE
kernel configuration

### ISSUE THREAD

**Issue by kinazarov** [archlinuxcn/repo#524]
Can you please explain to me how to use some kind of makemenuconfig if I has added your repository in arch linux?
Please direct me to a documentation on how to configure this kernel using some ncurses type utility.

**Comment by lilydjwg** [comment]
What's that? You don't need to change kernel configuration to use this repository.

**Comment by mahmoudhossam** [comment]
@kinazarov This repo provides pre-compiled kernels.

If you want to configure your own, go to https://www.kernel.org/ and download your own kernel, it provides an ncurses UI for configuring the kernel.
