### ISSUE TITLE
Perl 库路径变更

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#525]
以及 Perl 库需要重新构建，否则 shutter (#444) 跑不起来。

* [ ] gnome-perl 
* [ ] gnome-vfs-perl
* [ ] gnomecanvas-perl
* [ ] perl-gnome2-wnck
* [ ] perl-gtk2-imageview
* [ ] perl-gtk2-unique

**Comment by VOID001** [comment]
Got it, and sorry for the delay

**Comment by lilydjwg** [comment]
gnome-perl is still wrong.

**Comment by jeffrey4l** [comment]
同样的问题，又出现了。需要重新编译 gnome-perl 和  gnome-vfs-perl
