### ISSUE TITLE
webkitgtk的签名没了？

### ISSUE THREAD

**Issue by levinit** [archlinuxcn/repo#528]
archlinuxcn/webkitgtk  2.4.11-6  44.64 MiB

全部安装大小：  44.64 MiB

:: 进行安装吗？ [Y/n] 
(1/1) 正在检查密钥环里的密钥                        [##########################] 100%
(1/1) 正在检查软件包完整性                          [##########################] 100%
错误：webkitgtk：缺失签名
错误：无法提交处理 (软件包缺失签名)
发生错误，没有软件包被更新。

**Comment by lilydjwg** [comment]
@colinkeenan the webkitgtk lacks its signature.

**Comment by colinkeenan** [comment]
I only meant to upload webkitgtk2. In case that's the signature that's missing, I uploaded it again. I don't think anyone needs webkitgtk. If it was uploaded, can it be removed?

**Comment by levinit** [comment]
markdown editor  - remarkable need it

2017年10月10日 23:54于 Colin Keenan <notifications@github.com>写道：

I only meant to upload webkitgtk2. In case that's the signature that's missing, I uploaded it again. I don't think anyone needs webkitgtk. If it was uploaded, can it be removed?

―

**Comment by colinkeenan** [comment]
Ok. Since I didn't keep webkitgtk, I will have to build it again. This is an all day process. I'll start now.

**Comment by lilydjwg** [comment]
You can remove a package by removing its directory from this repo.

**Comment by colinkeenan** [comment]
I know, but the directory is needed for both webkitgtk2 and webkitgtk. Now that I realize both packages are actually needed, I'm rebuilding webkitgtk now and will upload it with signature.

**Comment by colinkeenan** [comment]
Done.
