### ISSUE TITLE
sublime-text-dev-imfix请求更新

### ISSUE THREAD

**Issue by fentensoft** [archlinuxcn/repo#531]
sublime-text-dev-imfix请求更新至3.3143版本

**Comment by farseerfc** [comment]
問題是我沒有 sublime-text 的 license ， dev channel 又要求得有 license 才能用了……我不知道怎麼測打包，怎麼更新 imfix ……

**Comment by lilydjwg** [comment]
那就 orphan 掉？

**Comment by farseerfc** [comment]
唔，我在考慮要不要買個 license … 讓我糾結下

**Comment by bianjp** [comment]
我个人维护的 [sublime-text-dev-imfix2](https://aur.archlinux.org/packages/sublime-text-dev-imfix2/) 一直在更新，供参考。

**Comment by qwIvan** [comment]
@bianjp 给你小心心

**Comment by phoenixlzx** [comment]
已有 License... 要怎么用？

**Comment by SilverRainZ** [comment]
这个陈年 issue 现在啥情况了？

**Comment by farseerfc** [comment]
我決定 drop 手上的這些包了

**Comment by farseerfc** [comment]
剛剛刪掉了這個包的文件夾並且在 AUR 上 orphan 了這個包，想要接手的人可以先去 AUR 上 adopt 然後這邊加回來。
