### ISSUE TITLE
{lib32-,}mesa-noglvnd{,-nogbm} should not replace

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#534]
It's causing upgrade problems on systems not using them.
Please drop all `replaces=` lines from PKGBUILDs.

**Comment by lilydjwg** [comment]
我们可以在 CI 上加个逻辑，不允许 replace 官方仓库里的包。另外在维护者相关的 wiki 里也要说明一下。

**Comment by heavysink** [comment]
擦...低级错误。
马上改！

**Comment by heavysink** [comment]
好了。
