### ISSUE TITLE
ruby-jekyll out-of-date，缺依赖

### ISSUE THREAD

**Issue by qwIvan** [archlinuxcn/repo#536]
缺依赖。
其中ruby-liquid、ruby-bundler、ruby-jekyll-feed在aur有，就minima没有。
不对，我应该去AUR找维护者。

**Comment by SilverRainZ** [comment]
jekyll 系列包看起来有进 [community] 的样子，所以我暂时就没修。

**Comment by SilverRainZ** [comment]
- AUR 的维护者失联了一个月
- [community] 至今也只有 ruby-jekyll-sass-converter 这一个 jekll 相关的孤立的包，在 `#archlinux` 问了也没有人回答

我尝试去请求 orphan AUR 的包，不行的话我再在 cn 源另外独立维护 jekyll。

**Comment by SilverRainZ** [comment]
鉴于：
* AUR 的维护者很不负责，只更新版本不修依赖
* 管理员过了两周都没有处理我的 orphan 请求

现在我在 AUR 维护了 [jekyll](https://aur.archlinux.org/packages/jekyll/) 这个包，修复了依赖问题，如果要从 AUR 自动安装的话，已经装过 ruby-jeyll 的用户可能需要在安装这个包之后手动把 `ruby-listen` 替换为 `ruby-listen-3-0`。 如果继续用  cn 源的话会自动提示 replace，大概明天或者后天可用。

**Comment by SilverRainZ** [comment]
https://github.com/archlinuxcn/repo/commit/7c3b244378d46ac7cfe4edd9c169fa84da1f09cb
