### ISSUE TITLE
Mesa-libgl-noglvnd causing problems for lilac autobuilding packages which depend on libGL and archlinuxcn packages

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#537]
在打包amdgpu-pro的时候，发现需要一个没有libglvnd和libgbm的Mesa,所以就把改动过的mesa发上来了。但是当我把改动过的mesa包发上来之后，所有依赖libgl的，build prefix=archlinuxcn_x86-64或者multilib-archlinuxcn的包都会默认选择archlinuxcn里的mesa-libgl-noglvnd（原本默认选择的是libglvnd),这样会造成很多问题。

Enter a number (default=1): 
:: There are 5 providers available for libgl:
:: Repository archlinuxcn
  1) mesa-libgl-noglvnd  2) mesa-libgl-noglvnd-nogbm
:: Repository extra
  3) libglvnd  4) nvidia-304xx-utils  5) nvidia-340xx-utils

有没有办法让它默认选择libglvnd而不是选择mesa-libgl-noglvnd?

**Comment by heavysink** [comment]
#539

**Comment by petronny** [comment]
自己添加libglvnd到depends或者makedepends

**Comment by heavysink** [comment]
好了。貌似已经删掉了
