### ISSUE TITLE
Add Pale Moon browser

### ISSUE THREAD

**Issue by notuxius** [archlinuxcn/repo#54]
Pale Moon is an Open Source, Firefox-based web browser...
http://www.palemoon.org/

**Comment by petronny** [comment]
If this request gets 5 more ![thumbup](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png) than ![thumbdown](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44e.png) before 2016-12-01, we will add this package.
Or else we will ignore this request.
