### ISSUE TITLE
[Package request] ieaseMusic

### ISSUE THREAD

**Issue by axionl** [archlinuxcn/repo#541]
# ieaseMusic

[Github Page](https://github.com/trazyn/ieaseMusic)

## Description:

Elegant NeteaseMusic desktop app, Rock with NeteaseMusic 🤘

Built by Electron, React, MobX, JSS

## Screenshot:

![img](https://github.com/trazyn/ieaseMusic/raw/master/screenshots/preview.gif)

**Comment by heavysink** [comment]
好了
