### ISSUE TITLE
Please update teamviewer

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [archlinuxcn/repo#543]
As GUI of teamviewer cannot open， please update it.

Related to [teamviewer](https://aur.archlinux.org/packages/teamviewer/)

**Comment by luozixiao1996** [comment]
Have you tried the solutions in the AUR comments? Seems it's a problem associated with the lib32-freetype2-2.8.* upgrade.

Please try
`yaourt -s lib32-freetype2-infinality-ultimate`

or
downgrade lib32-freetype2 to 2.7.*
`yaourt -S teamviewer
sudo pacman -U https://archive.archlinux.org/packages/l/lib32-freetype2/lib32-freetype2-2.8-2-x86_64.pkg.tar.xz`
OR:
`sudo downgrade lib32-freetype2` (if downgrade installed) 
Then add to pacman ignore pkg list in your preferred way.

or
just try rebuilding the teamviewer with the
[teamviewer-12.0.85001-7.zip](https://github.com/archlinuxcn/repo/files/1420668/teamviewer-12.0.85001-7.zip) BKGBUILD file provided by @max.bra which includes the proper version to run.

then
`sudo systemctl restart teamviewerd.service`

Hope this works.

**Comment by petronny** [comment]
dda80e00bb2615332a6d9c8200e951310dd554ab
