### ISSUE TITLE
Rebuild needed for anbox-git

### ISSUE THREAD

**Issue by AstroProfundis** [archlinuxcn/repo#545]
protobuf is updated and `anbox --help` outputs:

    anbox: error while loading shared libraries: libprotobuf-lite.so.13: cannot open shared object file: No such file or directory

Current version of the `.so` is `/usr/lib/libprotobuf-lite.so.14`. Rebuild with latest protobuf fixes the problem.

**Comment by heavysink** [comment]
I think it is OK now. Plz check.

**Comment by AstroProfundis** [comment]
fix confirmed, thank you.
