### ISSUE TITLE
Genymotion 无法运行

### ISSUE THREAD

**Issue by ZenQy** [archlinuxcn/repo#547]
运行时出错，弹框内容如下：
In order to work, Genymotion requires VirtualBox to be installed on your computer. You can download the latest version of VirtualBox from www.virtualbox.org/wiki/Downloads.

Genymotion log archive has been saved in /home/zenqy/genymotion-log.zip
Please contact Genymotion support for more help.

**Comment by lilydjwg** [comment]
你没装 virtualbox 啦……

**Comment by ZenQy** [comment]
安装了呀，这是安装记录
sudo pacman -S genymotion
resolving dependencies...
:: There are 2 providers available for VIRTUALBOX-HOST-MODULES:
:: Repository community
   1) virtualbox-host-dkms  2) virtualbox-host-modules-arch

Enter a number (default=1): 
looking for conflicting packages...

Packages (10) dkms-2.4.0-2  net-tools-1.60.20160710git-1  protobuf-3.4.1-1
              python2-2.7.14-1  qca-qt5-2.1.3-4  qt5-script-5.9.2-1
              sdl-1.2.15-9  virtualbox-5.2.0-1  virtualbox-host-dkms-5.2.0-1
              genymotion-2.11.0-1

Total Download Size:    68.45 MiB
Total Installed Size:  324.22 MiB

:: Proceed with installation? [Y/n]

**Comment by lilydjwg** [comment]
也许需要配置一下？我以前用过，不太记得细节了。

**Comment by ZenQy** [comment]
果然需要配置一下。已经修复了。
1.安装 linux-header
2.加载modules
3.启动 systemd-modules-load.service
前两个在安装过程中有提示，当时没仔细看。汗颜～
关闭吧
