### ISSUE TITLE
Sorry. I made a mistake.

### ISSUE THREAD

**Issue by leebut** [archlinuxcn/repo#548]
I made a mistake. Sorry,

**Comment by SilverRainZ** [comment]
Can not reproduce. `tor-browser` can be downloaded successfully via chinaunicom, beijing from ustc mirror; `tor-browser-en` even not in this repo.
Which mirror do you using?

**Comment by leebut** [comment]
Thank you for replying.

I made a mistake. I didn't have the CN repo in my pacman.conf file.
In Pamac, it shows 'Use mirrors from worldwide'.
