### ISSUE TITLE
mendeleydesktop

### ISSUE THREAD

**Issue by alienzj** [archlinuxcn/repo#552]
设置socks5代理同步文献后，mendeley 100% crash掉。

**Comment by xgdgsc** [comment]
好像不设置代理也能同步

**Comment by alienzj** [comment]
我这边不设置代理总是提示：
Sorry, there was a problem syncing your library: Socket operation timed out

**Comment by alienzj** [comment]
➜  ~ mendeleydesktop --log-to-stderr  
/opt/mendeleydesktop/bin/..//bin/install-mendeley-link-handler.sh:行73: : 未找到命令
/opt/mendeleydesktop/bin/..//bin/install-mendeley-link-handler.sh:行74: : 未找到命令
static QPlatformTheme* QKdeTheme::createKdeTheme(): Unable to determine KDE dirs

-- 2017-11-06 01:17:02.164 CrashReportGenerator::generate: Generating crash report /home/zhujie/.local/share/data/Mendeley Ltd./Mendeley Desktop/crash-reports/708e70d1-c1c1-4480-8f15-193cd2271dd2.zip
-- 2017-11-06 01:17:02.363 CrashReportUploader::upload: Uploading crash report /home/zhujie/.local/share/data/Mendeley Ltd./Mendeley Desktop/crash-reports/708e70d1-c1c1-4480-8f15-193cd2271dd2.zip QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv3_server_method

-- 2017-11-06 01:17:08.409 CrashReportUploader::reportSent: ID 2017-11-06-01-17-10-ca02d
-- 2017-11-06 01:17:08.410 main: startup took 6450 ms QLayout: Attempting to add QLayout "" to ToolBarActionWidget "", which already has a layout
QLayout: Attempting to add QLayout "" to ToolBarActionWidget "", which already has a layout
Qt WebEngine data directory not found at location /opt/mendeley/desktop/Qt/5.5.1/5.5/gcc_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location /opt/mendeley/desktop/Qt/5.5.1/5.5/gcc_64/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /opt/mendeleydesktop/lib/mendeleydesktop/libexec/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
[1106/091708:WARNING:resource_bundle.cc(304)] locale_file_path.empty()
Qt WebEngine data directory not found at location /opt/mendeley/desktop/Qt/5.5.1/5.5/gcc_64. Trying application directory...
Qt WebEngine Plugins directory not found. Trying fallback directory... Plugins as for example video codecs MAY NOT work.
Installed Qt WebEngine locales directory not found at location /opt/mendeley/desktop/Qt/5.5.1/5.5/gcc_64/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /opt/mendeleydesktop/lib/mendeleydesktop/libexec/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
[1106/091708:WARNING:resource_bundle.cc(304)] locale_file_path.empty()

-- 2017-11-06 01:17:12.934 SyncQueue::startSync: starting sync
-- 2017-11-06 01:17:14.499 SyncQueue::finished: sync completed in 1564 ms
-- 2017-11-06 01:17:14.499 SyncQueue::startSync: starting sync
-- 2017-11-06 01:17:15.269 RemoteDataStore::processModifiedFolder: folder 4eeed72d-6e83-47ec-a186-48f4ec283ce5 was modified on server
-- 2017-11-06 01:17:15.667 RemoteDataStore::processNewOrModifiedDocuments: received 0 updated documents from server
-- 2017-11-06 01:17:15.667 SyncTokenMapper::setSyncTokenFromISODate: Saving sync Token  2017-11-06T01:17:17.000Z  of type  3  and groupId =  0
-- 2017-11-06 01:17:16.057 SyncTokenMapper::setSyncTokenFromISODate: Saving sync Token  2017-11-06T01:17:17.000Z  of type  4  and groupId =  0
-- 2017-11-06 01:17:16.425 RemoteDataStore::processNewOrModifiedDocuments: received 0 updated documents from server
-- 2017-11-06 01:17:16.425 SyncTokenMapper::setSyncTokenFromISODate: Saving sync Token  2017-11-06T01:17:18.000Z  of type  5  and groupId =  0
-- 2017-11-06 01:17:17.183 PrepareFileSyncQueueSyncAction::start: Group:   Uploading: 17 Downloading: 1 Removing: 0 Examined: 35 documents
-- 2017-11-06 01:17:17.552 SyncTokenMapper::setSyncTokenFromISODate: Saving sync Token  2017-11-06T01:17:19.000Z  of type  1  and groupId =  0
-- 2017-11-06 01:17:17.910 SyncTokenMapper::setSyncTokenFromISODate: Saving sync Token  2017-11-06T01:17:19.000Z  of type  2  and groupId =  0
-- 2017-11-06 01:17:17.913 RemoteFilesProxy::get: fileUuid:  20696b8a-d9d3-2057-7228-e37d0334c36c  sha1:  4684b1fb0a5db8168f4fd61a60bb7fa0fc764b9b
-- 2017-11-06 01:17:17.916 ApiDownloadFileFromCatalogTasklet::run: Downloading file using fileUuid:  20696b8a-d9d3-2057-7228-e37d0334c36c
-- 2017-11-06 01:17:17.916 ApiDownloadFileTasklet::run: Downloading file with fileUuid:  20696b8a-d9d3-2057-7228-e37d0334c36c *** Error in `/opt/mendeleydesktop/bin/..//lib/mendeleydesktop/libexec/mendeleydesktop.x86_64': free(): invalid pointer: 0x00007fc9ca5993c0 ***
Crash handler wrote minidump /home/zhujie/.local/share/data/Mendeley Ltd./Mendeley Desktop/minidumps/4ff18fc4-4291-baf9-3057f4c7-200c6c3c.dmp

**Comment by alienzj** [comment]
不知道怎么分析这个.dmp文件:(，求助！

**Comment by petronny** [comment]
请到
https://aur.archlinux.org/packages/mendeleydesktop
反馈
