### ISSUE TITLE
维护者清理 / maintainer cleanup

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#557]
社区的包维护者已经有四十多名了，然而有一些维护者因为各种原因已经没有活动了，遗留下不少没有人管理的包。现在，请30天没有 git 提交的维护者，**在30天内在本 issue 下留言**表示依旧会维护其名下的包。留言表示离开者，或者30天后依旧没有回复者，我们会回收其权限，并 orphan 其名下的所有包。

PS: 如果不想收到本 issue 的通知，点一下右边的「Unsubscribe」吧。

**Comment by PeterCxy** [comment]
PeterCxy 会维护

**Comment by VOID001** [comment]
会继续维护

**Comment by swordfeng** [comment]
我会继续维护名下所有的包。

**Comment by fantix** [comment]
没有时间继续维护了 🙌  缴枪~~持续关注

**Comment by frantic1048** [comment]
frantic1048 会继续维护

**Comment by farseerfc** [comment]
farseerfc 會繼續維護

**Comment by petronny** [comment]
petronny 会继续维护

**Comment by Sasasu** [comment]
Sasasu 会继续维护

>

**Comment by ykelvis** [comment]
会继续维护

**Comment by ouyangshi** [comment]
稀释也会继续维护(

**Comment by zsrkmyn** [comment]
I'll keep maintaining the repo.

**Comment by wicast** [comment]
会继续

**Comment by SilverRainZ** [comment]
SilverRainZ 会继续维护其名下的软件包。

**Comment by heavysink** [comment]
heavysink已经lilac化并且将继续维护所有包。

**Comment by hzy199411** [comment]
会继续维护

**Comment by renyuneyun** [comment]
renyuneyun會繼續維護，各包已交lilac託管，但仍不時手動干預有故障的那些。
（好像看到其他30天內有提交也回覆的，跟着確認一下好了）

**Comment by cuihaoleo** [comment]
表示依旧会维护其名下的包

**Comment by kaseiwang** [comment]
我会继续维护名下的包

**Comment by lijinpei** [comment]
lijinpei会继续维护名下的包(

**Comment by lilydjwg** [comment]
@ouyangshi 你的 git 邮箱写错了。

1. [dxhisboy](https://github.com/dxhisboy) is removed
1. [fantix](https://github.com/fantix) is removed
1. [fbq](https://github.com/fbq) is removed
1. [fqj1994](https://github.com/fqj1994) is removed
1. [jack-lijing](https://github.com/jack-lijing) is removed
1. [JiajunW](https://github.com/JiajunW) is removed
1. [jokeryu](https://github.com/jokeryu) is removed
1. [mapleray](https://github.com/mapleray) is removed
1. [MarloweW](https://github.com/MarloweW) is removed
1. [sgsdxzy](https://github.com/sgsdxzy) is removed
1. [SteamedFish](https://github.com/SteamedFish) is removed
1. [stuarch](https://github.com/stuarch) is removed
1. [wxg4net](https://github.com/wxg4net) is removed
1. [zer4tul](https://github.com/zer4tul) is removed
1. [zhustec](https://github.com/zhustec) is removed

**Comment by lilydjwg** [comment]
好像有些人早就自行离开了。另外有几个人一个提交都没有……

**Comment by ouyangshi** [comment]
我好早就已经改了😊
