### ISSUE TITLE
Missing metadata in archlinuxcn-keyring-20171107-1 and google-chrome-62.0.3202.89-1-x86_64

### ISSUE THREAD

**Issue by gregodadone** [archlinuxcn/repo#558]
My pacman output is in spanish, but the problem is basically what the title says...

error: faltan los metadatos del paquete en /var/cache/pacman/pkg/archlinuxcn-keyring-20171107-1-any.pkg.tar.xz
error: '/var/cache/pacman/pkg/archlinuxcn-keyring-20171107-1-any.pkg.tar.xz': paquete no válido o dañado

**Comment by lilydjwg** [comment]
What the sha1sum of the downloaded packages? They may be actually damaged.

```sh
>>> sha1sum /var/cache/pacman/pkg/archlinuxcn-keyring-20171107-1-any.pkg.tar.xz
4090d904a0c6ca31673202056e24adc49643c64b  /var/cache/pacman/pkg/archlinuxcn-keyring-20171107-1-any.pkg.tar.xz
```
