### ISSUE TITLE
请求更新搜狗输入法  官方已经更新

### ISSUE THREAD

**Issue by copie** [archlinuxcn/repo#560]
今天我看到搜狗输入法在官网在11.2号已经更新了  AUR也也已经打包打包好了   不知道为什么  archlinuxcn 一直没有更新

**Comment by cuihaoleo** [comment]
hmm，因为 qtwebkit 移出官方源，自动打包失败了。我给 archlinuxcn 的 qtwebkit 加了 lilac.py，看看下一轮能不能打包成功吧。

**Comment by cuihaoleo** [comment]
已更新
