### ISSUE TITLE
update install script for v2ray

### ISSUE THREAD

**Issue by htfy96** [archlinuxcn/repo#561]
Since [2.46](https://github.com/v2ray/v2ray-core/releases), v2ray requires `geoip.dat` and `geosite.dat` placed under the same directory of `v2ray` program. Current install script does not copy these files into `/usr/bin` so its service won't start after 2.46. I suggest `v2ray` should be installed under `/opt` after this release.

**Comment by lilydjwg** [comment]
Why not just symlink those files from geoip-database?

**Comment by htfy96** [comment]
@lilydjwg The two files are [serialized in v2ray's own format](https://github.com/v2ray/v2ray-core/blob/d9ce03d25be959f19875f1a60872f405451f0eb5/common/net/ipnet_test.go#L75) and have nothing to share with `geoip-database`.

**Comment by petronny** [comment]
请到
https://aur.archlinux.org/packages/v2ray
反馈
