### ISSUE TITLE
Missing dependency for `python-telegram-bot`

### ISSUE THREAD

**Issue by knight42** [archlinuxcn/repo#564]
I got the following traceback since `python-certifi` was not installed on my host:

```
  File "/usr/lib/python3.6/site-packages/telegram/__init__.py", line 94, in <module>
    from .bot import Bot                        
  File "/usr/lib/python3.6/site-packages/telegram/bot.py", line 34, in <module>
    from telegram.utils.request import Request               
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 31, in <module>
    import certifi                   
ModuleNotFoundError: No module named 'certifi' 
```

**Comment by lilydjwg** [comment]
This is not missing dependency. certifi shouldn't be used in packages, ca-certificates should be used instead.

**Comment by Sherlock-Holo** [comment]
It is my mistake, I use `sed` to replace `patch`, but I forget to modify the codes about certifi, I will fix it tomorrow if I am not very busy

**Comment by Sherlock-Holo** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=python-telegram-bot&id=d557f2f66816cdb5d02e6436d76b82be8e6a348c

I have fixed it :-P

**Comment by knight42** [comment]
@Sherlock-Holo Maybe I missed something, but it seems that the `request.py` still `import certifi`.

**Comment by Sherlock-Holo** [comment]
oh shit…I think I must be too tired to fix it tonight😂
tomorrow I will delete `import certifi`

**Comment by knight42** [comment]
Never mind. There's no great hurry.

**Comment by Sherlock-Holo** [comment]
OK now I delete the codes import certifi

Jian Zeng <notifications@github.com> 于 2017年11月10日周五 08:54写道：
