### ISSUE TITLE
pycharm-community out of date

### ISSUE THREAD

**Issue by cclinet** [archlinuxcn/repo#566]
pycharm 最新版本为 2017.2.4
仓库版本为2017.2.3
https://blog.jetbrains.com/pycharm/2017/10/pycharm-2017-2-4-is-out-now/

**Comment by petronny** [comment]
请等待AUR更新

**Comment by SilverRainZ** [comment]
@xgdgsc  这个包和 community/pycharm-community-edition 有区别么？没有的感觉可以 drop 掉了。

**Comment by xgdgsc** [comment]
可以drop了
