### ISSUE TITLE
请求添加gcc5

### ISSUE THREAD

**Issue by qwIvan** [archlinuxcn/repo#568]
https://aur.archlinux.org/packages/gcc5/
自己编译太慢了。。

**Comment by yan12125** [comment]
If gcc5 is eventually added to archlinuxcn, may I add a link to the built package to https://aur.archlinux.org/packages/gcc5/?

(I'm the maintainer of the aforementioned package)

**Comment by qwIvan** [comment]
How are you going to add? The mechanism of compilation robot is just automatically using PKGBUILD from aur.

**Comment by yan12125** [comment]
For example:
```
You can find prebuilt binaries at the following URLs:
https://cdn.repo.archlinuxcn.org/x86_64/

Beware that those packages are not built by the maintainer of this AUR package.
```
By the way, there's [a comment](https://aur.archlinux.org/packages/gcc5/) mentioning a mirror maintained by students at TsingHua University a few minutes ago:
```
petronny [1] added the following comment to gcc5 [2]:

You can find the pre-compiled gcc5 from
https://mirrors.tuna.tsinghua.edu.cn/arch4edu/x86_64/

If you no longer wish to receive notifications about this package,
please go to the package page [2] and select "Disable notifications".

[1] https://aur.archlinux.org/account/petronny/
[2] https://aur.archlinux.org/pkgbase/gcc5/
```
Looks like the arch4edu repo is  maintained at https://github.com/arch4edu/arch4edu, which [also uses lilac](https://github.com/arch4edu/arch4edu/tree/master/gcc5) ;-)

**Comment by petronny** [comment]
尴尬。。。

**Comment by yan12125** [comment]
樓上是看到這個issue才去AUR那邊兒留言的嗎:D

**Comment by petronny** [comment]
是。。。
但是现在感觉我在搞不正当竞争一样。。。
总之我道歉并且我会处理这个package request。。。
