### ISSUE TITLE
请求添加firefox开发者专版（firefox developer edition）

### ISSUE THREAD

**Issue by levinit** [archlinuxcn/repo#570]
开发者专版比普通版本早一点 但并不仅仅是作为普通版本的提前测试小白鼠版 
它加入了许多转为web开发者的增强功能 （nightly版本实在是太小白鼠）

> - 最新的 Firefox 特性
> - 实验性开发工具
> 例如，开发者版本包含了 Firefox Tools Adapter，它可以帮你将 Firefox 开发工具 连接到其他平台的浏览器上
> - 单独的配置文件
> - 专为网页开发者而设

详参 https://developer.mozilla.org/zh-CN/Firefox/Developer_Edition 和 https://www.mozilla.org/zh-CN/firefox/developer/
- [firefox-dev](https://aur.archlinux.org/packages/firefox-developer) 
分语言版
- [firefox-dev-zh-cn](https://aur.archlinux.org/packages/firefox-developer-zh-cn/) 中文版 
- [firefox-dev-en-us](https://aur.archlinux.org/packages/firefox-developer-en-us/)  英文

请收录一个吧 ：D

**Comment by bennyyip** [comment]
我觉得[firefox-developer](https://aur.archlinux.org/packages/firefox-developer)比这两个包好一点，因为它已经维护两年了，而且更新也算及时，基本跟官方同步（https://aur.archlinux.org/cgit/aur.git/log/?h=firefox-developer）

**Comment by bennyyip** [comment]
Done.
https://github.com/archlinuxcn/repo/commit/40921d5a58d1b5ae711ac07617c945dfca4c8e15

**Comment by levinit** [comment]
@bennyyip  添加了吗？已更新了archlinuxcn-keyring 怎么没看到?

**Comment by bennyyip** [comment]
@levinit 需要等lilac自動打包，它每天運行三次，最近的一次是17:17，算上打包和鏡像同步的時間六點鐘應該就能用上了。

**Comment by jingyu9575** [comment]
现在已有community/firefox-developer-edition，系统更新时替换了这个包。

**Comment by bennyyip** [comment]
@jingyu9575 已移除
