### ISSUE TITLE
Megasync is outdated

### ISSUE THREAD

**Issue by bil-elmoussaoui** [archlinuxcn/repo#573]
Megasync was updated to v3.5 recently

**Comment by ykelvis** [comment]
Package Details: megasync 3.1.4.0-2
You should report to upstream, ie aur.

**Comment by levinit** [comment]
3.6 粗来了
而且在这里也可以下到https://mega.nz/linux/MEGAsync/Arch_Extra/x86_64/megasync-x86_64.pkg.tar.xz
不过还是从archlinuxcn下载安装爽啊  希望维护者更新一下

**Comment by lilydjwg** [comment]
@levinit 下次不要挖旧 issue，新开一个更好。

**Comment by levinit** [comment]
@lilydjwg 好的。

**Comment by ykelvis** [comment]
megasync是自动track aur的, 请去提醒aur maintainer更新 (

**Comment by ykelvis** [comment]
8617020
