### ISSUE TITLE
package request: perl-goo-canvas

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#581]
### 问题类型 / Type of issues

请只保留符合的行，删掉其它行。
Please keep only the line that suits and delete others.

* 软件打包请求 / package request

### 受影响的软件包 / Affect packages

请每行一个包名，开头加上 `* `。
Please write one package name per line, prefixing with `* `.

* perl-goo-canvas
* shutter

----

这是 shutter 的一个可选依赖，用于编辑图片。

**Comment by VOID001** [comment]
commit: 9189cdede7be91d49a378bdc791b34f7ac2191cd
Waiting for build

**Comment by VOID001** [comment]
Done, tested on my machine
