### ISSUE TITLE
gnucash: requires libenchant 1.6.1, arch moved to 2.1.2

### ISSUE THREAD

**Issue by hosaka** [archlinuxcn/repo#588]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* gnucash
----
This was raised in [bugs.archlinux](https://bugs.archlinux.org/task/56469) but was closed since gnucash is not supported. As Arch repos updated enchant to version 2.1.2, gnucash no longer starts:
```
gnucash: error while loading shared libraries: libenchant.so.1: cannot open shared object file: No such file or directory
```

Are there any plans to provide enchant 1.6.1 in archlinuxcn repo? It is also available in [AUR](https://aur.archlinux.org/packages/enchant1.6/), installing it works around the missing library issue.

**Comment by colinkeenan** [comment]
I am working on it now. The AUR maintainer added a package named enchant1.6 to AUR, and I've just added it to archlinuxcn. I'm rebuilding the latest version of AUR gnucash now.

**Comment by colinkeenan** [comment]
I have just pushed the latest version of gnucash and already did the new dependency before that. It will be available soon.
