### ISSUE TITLE
can't upgrade supertux-git

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#589]
### 问题类型 / Type of issues

请只保留符合的行，删掉其它行。
Please keep only the line that suits and delete others.
* 其它 / other

### 受影响的软件包 / Affect packages

请每行一个包名，开头加上 `* `。
Please write one package name per line, prefixing with `* `.

* supertux-git
----

When try to upgrade supertux-git that I just pushed to the repo, I get an error about the package file size exceeding the maximum allowed:

```
Packages (1) supertux-git-1:v0.5.0.r325.gf6fa35439-1

Total Download Size:    84.68 MiB
Total Installed Size:  134.13 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'supertux-git-1:v0.5.0.r325.gf6fa35439-1-x86_64.pkg.tar.xz' from cdn.repo.archlinuxcn.org : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
```

**Comment by lilydjwg** [comment]
The size in pacman database is wrong. It seems like a partial upload, followed by a complete one. You need to give it some time to resync. Try `pacman -Sy`?

**Comment by colinkeenan** [comment]
It works now. Thanks.
