### ISSUE TITLE
ppsspp-git need rebuild and update

### ISSUE THREAD

**Issue by Sasasu** [archlinuxcn/repo#591]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affect packages

* ppsspp-git
* ppsspp-qt-git

需要 rebuild: `error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory`
需要 update: [v1.5.4](https://github.com/hrydgard/ppsspp/releases/tag/v1.5.4)

**Comment by farseerfc** [comment]
done in 564f9017121639a93e01ac207cd59e1c5808f5df
