### ISSUE TITLE
sublime-text的AUR上游消失

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#606]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages
* lugaruhd-hg
* nixnote
* nixnote-beta
* qpdfview
* sublime-text
* visual-studio-code

----

nvchecker.ini中track aur但是其AUR上游已经消失
nixnote貌似已经改名nixnote2
sublime-text貌似已经改名sublime-text2
qpdfview已在[community]中

**Comment by petronny** [comment]
@farseerfc 
visual-studio-code最近貌似改名visual-studio-code-bin了

**Comment by lilydjwg** [comment]
sublime-text 好像已经很久很久没人管了，要不 orphan 掉吧。

**Comment by petronny** [comment]
换成sublime-text2吧

**Comment by petronny** [comment]
434d335c2d1cbc2183453fb40b3c06115a26f5aa
