### ISSUE TITLE
重新编译 dbus-cpp process-cpp

### ISSUE THREAD

**Issue by huiyiqun** [archlinuxcn/repo#608]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affect packages

* dbus-cpp
* process-cpp

----

boost-libs 升级，需要重新编译。

**Comment by petronny** [comment]
我新建了一个hooks-rebuild的label来替换原来
hooks的issue的rebuild label

这样rebuild时间过长的也可以转orphan了

**Comment by heavysink** [comment]
已经trigger rebuild了

**Comment by petronny** [comment]
dbus-cpp 没rebuild成功

**Comment by heavysink** [comment]
@petronny 彻底好了
