### ISSUE TITLE
iease-music需更新

### ISSUE THREAD

**Issue by updater1234** [archlinuxcn/repo#610]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affect packages
iease-music

----

**Comment by updater1234** [comment]
https://github.com/trazyn/ieaseMusic/releases的最新版是1.0.9 而repo里还是1.0.3，需更新。

**Comment by petronny** [comment]
请到
https://aur.archlinux.org/packages/iease-music
反馈

**Comment by petronny** [comment]
cdf7e7b
