### ISSUE TITLE
Is it OK to update AUR package before AUR maintainer?

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#617]
With the latest webkitgtk2 update, gnucash no longer needs enchant1.6. Also, the AUR package for gnucash is out of date. I have successfully updated gnucash and removed enchant1.6 on my own machine.

Should I remove the echant1.6 package and upgrade gnucash to 2.6.19 on this repo before the AUR maintainer updates gnucash?

**Comment by farseerfc** [comment]
I think it's OK. Some PKGBUILDs here are actually updated by lilac automatically, then pushed to AUR by lilacbot as a co-maintainer. Some packages here are not presented in AUR. Some have the same name package on AUR but using a modified PKGBUILD here.
BTW, please also flag out-of-date (even orphan) flag on AUR, as usual.

**Comment by lilydjwg** [comment]
It's perfectly OK. We are not a binary build of AUR; AUR is just one great source of PKGBUILDs. Keeping them in sync is good but deriving is better when needed.

**Comment by colinkeenan** [comment]
Ok. I've made those changes.
