### ISSUE TITLE
capnproto 与官方源重复

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#620]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affect packages

* capnproto
----

**Comment by petronny** [comment]
v2ray我昨天就通过 6e55b1cbc6a4 删了啊。。。

**Comment by lilydjwg** [comment]
哦哦，那就是 lilac 还没动手（或者我用的镜像还没同步）。等等就没了。
