### ISSUE TITLE
Missing dependency lib32-libldap for deepin-wechat

### ISSUE THREAD

**Issue by LER0ever** [archlinuxcn/repo#621]
### 问题类型 / Type of issues
* 其它 / other

### 受影响的软件包 / Affect packages
Deepin-wechat

----

在没有安装lib32-libldap的情况下微信会提示找不到WeChatWin.dll，因为那个库需要的libldap.so找不到，所以wine会拒绝加载。

**Comment by petronny** [comment]
啊哈，原来如此

**Comment by petronny** [comment]
这个问题困扰了我好一阵了，因为无法复现

**Comment by petronny** [comment]
94e4821446be
