### ISSUE TITLE
fakeroot-tcp shouldn't be in base-devel group

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#626]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* fakeroot-tcp
----

这样安装 base-devel 的用户都可能会装上它，而它应该只在用户确实需要的时候才安装，一般用户用不上，装了会取代 fakeroot，反而可能会出问题。

**Comment by KenOokamiHoro** [comment]
Fixed in https://github.com/archlinuxcn/repo/commit/5e99761df27492dd65fdf63e89832d55e6cd2791#diff-75d7dac00f430c5a1a741444ec5c4ea8

**Comment by yan12125** [comment]
可能需要rebuild或bump pkgrel? cdn.repo.archlinuxcn.org 上的包還是舊的

> fakeroot-tcp-1.21-2-x86_64.pkg.tar.xz              27-Nov-2017 06:38               83532

這個包仍然屬於base-devel

> $ tar -xOf fakeroot-tcp-1.21-2-x86_64.pkg.tar.xz .PKGINFO | grep group
group = base-devel

**Comment by lilydjwg** [comment]
对，需要 bump pkgrel 不然 lilac 不会重新打包的。

**Comment by yan12125** [comment]
請問可以reopen這個issue嗎？這個問題還沒有完全解決

**Comment by yan12125** [comment]
The upstream AUR package requires more fix than its groups. I've submitted [an orphan request](https://lists.archlinux.org/pipermail/aur-requests/2018-January/021723.html).

**Comment by SilverRainZ** [comment]
上游是有问题的，仅仅在仓库里修一次，之后的更改还是会将其覆盖：https://github.com/archlinuxcn/repo/commit/ccb40bc78db31a75728af9014c5bfa8a3df99e5b 请考虑在 AUR 上 orphan 上游或者不再 track AUR。

**Comment by petronny** [comment]
可以通过lilac.py修改PKGBUILD的

**Comment by yan12125** [comment]
As the package is updated, my orphan request is rejected. I leave a comment at https://aur.archlinux.org/packages/fakeroot-tcp/ and ask the maintainer remove the problematic line.

**Comment by 4679** [comment]
改好了，才知道我这包进了这个源，我还以为只在AUR上

**Comment by yan12125** [comment]
Many thanks!

**Comment by yan12125** [comment]
應該還要再bump pkgrel一次？

**Comment by 4679** [comment]
好了

**Comment by yan12125** [comment]
Fixed! https://cdn.repo.archlinuxcn.org/x86_64/fakeroot-tcp-1.22-2-x86_64.pkg.tar.xz

Thanks everyone that helped.

**Comment by SilverRainZ** [comment]
这个 closed 了吧。
