### ISSUE TITLE
archbuild -c breaks the build

### ISSUE THREAD

**Issue by yuyichao** [archlinuxcn/repo#627]
# WARNING

Don't run any of the command below on the build server without admin privilege. They could potentially make the build server unusable.

### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

There seems to be some problem during the step of synchronizing from the root copy to the personal copy which causes error like

```
==> Synchronizing chroot copy [/var/lib/archbuild/staging-x86_64/root] -> [yuyichao]...done
==> ERROR: /var/lib/archbuild/staging-x86_64/yuyichao/etc/makepkg.conf not found.
    Aborting...

==> ERROR: An unknown error has occurred. Exiting...
```

`archlinuxcn-x86_64-build` is affected and I might have killed `testing-x86_64-build` this way (i.e. `testing-x86_64-build` isn't working currently but I'm not sure if it was previously...). I've tested with `staging-x86_64-build` (hopfully no non-admin uses it) and confirmed that this is indeed caused by running the archbuild command with `-c` option (which cleans the root).

This seems to be an issue with the setup on the server (I remember seeing something similar previously that is gone after a reboot) since I can't reproduce this issue locally.

**Comment by lilydjwg** [comment]
*archlinuxcn-*-build had a bad repo and it was fixed yesterday (#625). Are there any other issues currrently?

**Comment by yuyichao** [comment]
The issue with the bad repo is not related. Yes, there are issues as described above.

**Comment by lilydjwg** [comment]
I saw the pacman.conf there. What should I do? Do a cleanup? Or never do that?

**Comment by yuyichao** [comment]
Well, the one missing is `makepkg.conf` ..... I have no idea what's causing it.....

**Comment by lilydjwg** [comment]
makepkg.conf is there too.

**Comment by petronny** [comment]
```
ERROR: /var/lib/archbuild/archlinuxcn-x86_64/lilydjwg/etc/makepkg.conf not found.
```
+1...

**Comment by lilydjwg** [comment]
@petronny 什么时候的事？

**Comment by zsrkmyn** [comment]
+1 for build of vim-youcompleteme-git in this morning.

**Comment by lilydjwg** [comment]
> downgrading package devtools (20171108-1 => 20170911-2)

**Comment by lilydjwg** [comment]
lilac 的日志里能看到的，都是关于 archlinuxcn-x86_64 和 multilib-archlinuxcn-x86_64 的。最早发生于 2017-12-31T01:17:01 那次。

**Comment by lilydjwg** [comment]
devtools 太娇嫩了啊……在 scope 里跑不动，改了 umask 也跑不动……
我把 umask 改回去了，不过不知道会不会生效。

**Comment by petronny** [comment]
我这mpv-git这个包没问题了

**Comment by yuyichao** [comment]
Didn't check if `-c` still break things but all the archbuild scripts mentioned above works for me again so I'm happy enough...........................
