### ISSUE TITLE
chrome-gnome-shell-git is old

### ISSUE THREAD

**Issue by WordlessEcho** [archlinuxcn/repo#629]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affect packages

* chrome-gnome-shell-git

----

> warning: chrome-gnome-shell-git: local (9.r34.g5463caa-1) is newer than archlinuxcn (9.r12.g792c135-1)

**Comment by lilydjwg** [comment]
The package should be chrome-gnome-shell-git.

**Comment by WordlessEcho** [comment]
Fix typo, sorry.

**Comment by ouyangshi** [comment]
Done
