### ISSUE TITLE
screengrab-git: need to be rebuilt

### ISSUE THREAD

**Issue by haruue** [archlinuxcn/repo#630]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* screengrab-git

----

```
$ pacman -Fl screengrab-git
screengrab-git usr/
screengrab-git usr/bin/
screengrab-git usr/bin/screengrab
screengrab-git usr/lib64/
screengrab-git usr/lib64/screengrab/
screengrab-git usr/lib64/screengrab/libextedit.so
screengrab-git usr/lib64/screengrab/libextedit.so.1.0.0
screengrab-git usr/lib64/screengrab/libuploader.so
screengrab-git usr/lib64/screengrab/libuploader.so.1.0.0
screengrab-git usr/share/
screengrab-git usr/share/applications/
```

`usr/lib64/` should never appear here, it is a symlink created by package `core/filesystem`. Rebuild this package may fix it. 
And there is a problem in PKGBUILD. Two or more dependencies are missed, see [this AUR comment](https://aur.archlinux.org/packages/screengrab-git#comment-502508).

**Comment by ykelvis** [comment]
screengrab-git is updated now, kwindowsystem&libqtxdg added to dependency.
sorry for the late update.
