### ISSUE TITLE
Request to add VNote to repo

### ISSUE THREAD

**Issue by tamlok** [archlinuxcn/repo#633]
### 问题类型 / Type of issues
* 软件打包请求 / package request

### 受影响的软件包 / Affect packages
* 简述 / Brief Description  
VNote is a note-taking application for Markdown, with pleasant Markdown experience. Instead of previewing the Markdown document side by side, VNote try to minimize the gap between the read and edit mode of Markdown by tuning highlihgts in edit mode. In one word, VNote knows the programmer and Markdown better.
* 主要语言和工具链 / Main Languages and Toolchains  
C++, Qt 5.9.1.
* 上游链接 / Upstream Link  
https://github.com/tamlok/vnote
* 为何需要这个软件包 / Why Need This Package
VNote provides yet another pleasant note-taking application with Markdown for Linux!

**Comment by heavysink** [comment]
added vnote-git

**Comment by tamlok** [comment]
@heavysink Hi, could you please to verify if the package in Arch Linux works? https://github.com/tamlok/vnote/issues/106

Thanks!!!

**Comment by heavysink** [comment]
vnote-git W: Dependency included and not needed ('qt5-svg')

qt5-svg is only needed when building. It might be used for generating icons.

**Comment by heavysink** [comment]
This package works in Arch.
