### ISSUE TITLE
dnsmasq-china-list-git lacks file

### ISSUE THREAD

**Issue by zsrkmyn** [archlinuxcn/repo#634]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* dnsmasq-china-list-git

----

`apple.china.conf` is missing in the package.

**Comment by petronny** [comment]
...上次出现类似问题的时候 #292 就是我修的。。。

**Comment by felixonmars** [comment]
Both added in the AUR package. Sorry for the delay.
