### ISSUE TITLE
kinder ninja, don't push load very high

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#635]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* [x] chromium-dev
* [x] corebird-git
* [ ] dbus-broker
* [ ] fcitx5-mozc-git
* [ ] gnome-mpv
* [ ] mozc
* [ ] paraview
* [ ] pamac-aur
* [ ] vivaldi-ffmpeg-codecs

----

ninja 默认并行任务数为 CPU 核数，导致有其他人在打包时，会将编译机的 load 推得很高（或者，如果另一方是 make 的话，会导致 make 很慢）。在[找到全局配置](https://github.com/ninja-build/ninja/pull/274#issuecomment-355812660)之前，请大家给 ninja 手动加上 `-l$(nproc)` 参数。

**Comment by lilydjwg** [comment]
另外你们提交用关联在 GitHub 的邮件地址比较好，lilac 能找到。

**Comment by petronny** [comment]
看起来只有 depot-tools-git 这个包每天都更新
别的可能不用改吧。。。

**Comment by lilydjwg** [comment]
还有 chromium-dev 更新也不少。

**Comment by yan12125** [comment]
depot-tools-git其實不用改，他build沒用ninja。ninja只是放一個symlink在那邊給其他程式(e.g. chromium)用

**Comment by yan12125** [comment]
BTW, 我是depot-tools-git的co-maintainer，我看目前archlinuxcn裡的包是track AUR的？如果有需要改上游，請和我說一聲，謝謝！

**Comment by lilydjwg** [comment]
@yan12125 ok. 我是按依赖找的，没有去看每个包具体是怎么在用它。

**Comment by heavysink** [comment]
pamac-aur 已经加上-l2

**Comment by lilydjwg** [comment]
`-l$(nproc)` 就好啦。`-l2` 你得小心它会等很长时间。
