### ISSUE TITLE
Orphaning linux-next-git amdgpu-pro-installer mesa-noglvnd-nogbm lib32-mesa-noglvnd-nogbm mesa-noglvnd lib32-mesa-noglvnd

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#642]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affect packages

* linux-next-git
* amdgpu-pro-installer
* mesa-noglvnd-nogbm 
* lib32-mesa-noglvnd-nogbm 
* mesa-noglvnd 
* lib32-mesa-noglvnd
----

**Comment by lilydjwg** [comment]
现在不需要把包名全部写在标题里了。

PS: 我改了一下，列表项的星号后边要加个空格，不然 github 的渲染有问题。

**Comment by heavysink** [comment]
It's done.
