### ISSUE TITLE
mendeleydesktop is out-of-date

### ISSUE THREAD

**Issue by zsrkmyn** [archlinuxcn/repo#645]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affect packages

* mendeleydesktop

----

https://desktop-download.mendeley.com/download/apt/pool/main/m/mendeleydesktop/mendeleydesktop_1.17.13-stable_amd64.deb
https://desktop-download.mendeley.com/download/linux/mendeleydesktop-1.17.13-linux-x86_64.tar.bz2

**Comment by petronny** [comment]
80473049796b ？

**Comment by zsrkmyn** [comment]
这么巧？今天刚装上，然后启动就崩溃了，看了下有新版本，就开issue了😂

2018年1月17日 23:09，"Jingbei Li" <notifications@github.com>写道：
