### ISSUE TITLE
skypeforlinux-bin upstream not found

### ISSUE THREAD

**Issue by SilverRainZ** [archlinuxcn/repo#647]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* skypeforlinux-bin

----

**Comment by heavysink** [comment]
I think now it is corrected. I changed the package to skypeforlinux-preview-bin and skypeforlinux-stable-bin.

**Comment by SilverRainZ** [comment]
Are you consider add a `replaces` statement for one of the new packages ?

**Comment by heavysink** [comment]
Added for preview package
