### ISSUE TITLE
webkitgtk needs to be rebuilt

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#648]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* webkitgtk

----

> error while loading shared libraries: libenchant.so.2: cannot open shared object file: No such file or directory

enchant 2.2.1 [renamed libenchant.so.2 to libenchant-2.so.2](https://www.archlinux.org/todo/enchant-221-rebuild/), so webkitgtk should be rebuilt. I've uploaded [a patch](https://aur.archlinux.org/cgit/aur.git/commit/?h=webkitgtk&id=e61d26228f7421c1e45172d67dfa2cd97740ca38) for webkitgtk compatibility with enchant 2.2.1. See the pinned comment at https://aur.archlinux.org/pkgbase/webkitgtk/ for more details.

**Comment by yan12125** [comment]
Now enchant 2.2 is in [extra]: https://www.archlinux.org/packages/extra/x86_64/enchant/

**Comment by colinkeenan** [comment]
I uploaded a version built against enchant 2.2 the same day it was available in extra.

**Comment by colinkeenan** [comment]
I actually built it against testing and then waited for it to reach extra before uploading it.

**Comment by colinkeenan** [comment]
I just checked, those uploads aren't available for some reason. I'll upload it again.

**Comment by colinkeenan** [comment]
Well, I uploaded it again, but now I see it's there since Jan 26, 2018.

**Comment by yan12125** [comment]
I tried updating [archlinuxcn] and it works fine! Sorry didn't notice there was an update.
