### ISSUE TITLE
Arch Linux CN Build Machine Maintenance

### ISSUE THREAD

**Issue by felixonmars** [archlinuxcn/repo#650]
You may have noticed that our build machine is not available since ~0:10 am today (UTC+8). I have rebooted the server but it never comes back.

Currently our service provider (online.net) has locked the server for hardware issue. I'll keep you updated on this.

**Comment by MaskRay** [comment]
编译机器辛苦了

**Comment by felixonmars** [comment]
Update: The problem was a faulty firmware update to address "meltdown". Our service provider has relaunched the update and the server is back online now.
