### ISSUE TITLE
anbox-git rebuild needed due to boost-libs version change

### ISSUE THREAD

**Issue by SanskritFritz** [archlinuxcn/repo#651]
### 问题类型 / Type of issues
* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affect packages
anbox-git

Rebuild needed due to boost-libs version change.

**Comment by heavysink** [comment]
declaration of io_service from /usr/include/core/dbus/asio/executor.h conflicts with boost. The only way that it can be built is ro delete the forward declaration of io_service in /usr/include/core/dbus/executor.h also without substitution.

So it is an Archlinux core issue. anbox cannot be built until this problem is solved.

**Comment by heavysink** [comment]
Done by modifing dbus-cpp.

**Comment by SanskritFritz** [comment]
Thanks. Now I get this error:
```
error: dbus-cpp: signature from "Winston Wu <winstonwu91@gmail.com>" is invalid                     
:: File /var/cache/pacman/pkg/dbus-cpp-5.0.0-3-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]                                                          
error: anbox-git: signature from "Winston Wu <winstonwu91@gmail.com>" is invalid             
:: File /var/cache/pacman/pkg/anbox-git-1:r717.b21e5d9-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).                                                                                    
```
```
root@HomeC ~# pacman-key --list-keys | grep --after-context 2 --before-context 2 'Winston Wu'
gpg: public key CF66D153D884358F is 16 seconds newer than the signature
pub   rsa2048 2017-08-14 [SC] [expires: 2019-08-14]
      90403E12F4CE5E0E950E4AD2C96492E347202001
uid           [  full  ] Winston Wu <winstonwu91@gmail.com>
sub   rsa2048 2017-08-14 [E] [expires: 2019-08-14]

root@HomeC ~# pacman-key --edit-key 90403E12F4CE5E0E950E4AD2C96492E347202001

pub  rsa2048/C96492E347202001
     created: 2017-08-14  expires: 2019-08-14  usage: SC  
     trust: marginal      validity: full
sub  rsa2048/AB4CF373BAC73556
     created: 2017-08-14  expires: 2019-08-14  usage: E   
[  full  ] (1). Winston Wu <winstonwu91@gmail.com>
```
Is this a problem on my side?

**Comment by zsrkmyn** [comment]
@SanskritFritz you may need to install archlinuxcn-keyring.

**Comment by SanskritFritz** [comment]
I did that already some time ago and I have several packages already installed from archlinuxcn. Sorry for not mentioning this.

**Comment by lilydjwg** [comment]
That signature is valid. What's your output of:

```
tar xzOf /var/lib/pacman/sync/archlinuxcn.db anbox-git-1:r717.b21e5d9-1/desc | grep -A1 -F '%PGPSIG%' | tail -1 | base64 -d | md5sum -
```

This should be `04a19680f68dc555c358f8c77a619f5b`. Also check the downloaded package file, which should have sha256sum `b6f4e333ea5479da20b4c5ddb7983ea5bac133ac7d38509f35cf25a1edcaf21e`.

Tips: use HTTPS if you didn't.

**Comment by SanskritFritz** [comment]
@lilydjwg Thanks, you opened my eyes and lead me to the solution: I didn't do pacman -Sy first. Basic mistake, sorry for the noise.
