### ISSUE TITLE
Some video output drivers for desktop is missing in mpv-git

### ISSUE THREAD

**Issue by wfwf1997** [archlinuxcn/repo#652]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* mpv-git

----

The package `mpv-git` probably is built in a nox environment, so some `vo` and `gpu-api` is missing. The desktop user may not use this awesome player with its cutting-edge features.
This is the executing result using the package from the Arch Linux CN repo:
```
mark@mark-pc ~ $ mpv --vo=help --ao=help
Available video outputs:
  gpu            : Shader-based GPU Renderer
  null           : Null video output
  image          : Write video frames to image files
  tct            : true-color terminals
  drm            : Direct Rendering Manager

mark@mark-pc ~ $ mpv --gpu-api=help
GPU APIs (contexts):
    auto (autodetect)
    opengl (drm)
```
And this is the executing result using the program built by myself (the same PKGBUILD used):
```
mark@mark-pc ~ $ mpv --vo=help --ao=help
Available video outputs:
  gpu            : Shader-based GPU Renderer
  vdpau          : VDPAU with X11
  xv             : X11/Xv
  vaapi          : VA API with X11
  x11            : X11 (slow, old crap)
  null           : Null video output
  image          : Write video frames to image files
  tct            : true-color terminals
  caca           : libcaca
  drm            : Direct Rendering Manager

mark@mark-pc ~ $ mpv --gpu-api=help
GPU APIs (contexts):
    auto (autodetect)
    opengl (x11probe)
    opengl (x11egl)
    opengl (x11)
    opengl (wayland)
    opengl (drm)
    opengl (vdpauglx)
    vulkan (waylandvk)
    vulkan (x11vk)
```
As the result suggests, there are no `x11` or `wayland` output drivers built, causing the video can only be output using legacy drm output driver (and for me, the drm way didn't work at all). The output quality is quite lower than `gpu`, `wayland`, etc.  
The same situation also happened on GPU APIS. Neither `vulkan API` nor `opencl` over `wayland` or `x11` can be used. 

`mpv` is a player featured **High quality video output**, so I suppose its necessary to make the build supporting these feature.

---
PS :  
The executing result using the package from the official Arch Linux repo:
```
mark@mark-pc ~ $ mpv --vo=help
Available video outputs:
  opengl         : Extended OpenGL Renderer
  vdpau          : VDPAU with X11
  wayland        : Wayland SHM video output
  xv             : X11/Xv
  vaapi          : VA API with X11
  x11            : X11 (slow, old crap)
  null           : Null video output
  image          : Write video frames to image files
  tct            : true-color terminals
  caca           : libcaca
  drm            : Direct Rendering Manager
```

**Comment by petronny** [comment]
Fixed. Please wait for the next update.

**Comment by petronny** [comment]
a397abe
