### ISSUE TITLE
请求设置build机并行压缩包

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#657]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

----

即设置`/usr/share/devtools/makepkg-x86_64.conf`中`COMPRESSXZ=(xz -T0 -c -z -)`

**Comment by lilydjwg** [comment]
这个更新之后会被覆盖的吧？

**Comment by petronny** [comment]
对。。。

**Comment by lilydjwg** [comment]
那你来写一个 hook？

**Comment by petronny** [comment]
是要给啥写hook呢。。。devtools吗

**Comment by lilydjwg** [comment]
给上边那个文件呀。每次它更新的时候就去改改。

**Comment by petronny** [comment]
我觉得devtools更新了时候手动改吧。。。

**Comment by lilydjwg** [comment]
行。哪天坏了你再说好了。

**Comment by lilydjwg** [comment]
这个选项以后不会加了，因为 xz 的多线程无法保证可重现，而肥猫经常用编译机给官方源推包，他们需要可重现。
