### ISSUE TITLE
Package Request: vnote-bin

### ISSUE THREAD

**Issue by amitbha** [archlinuxcn/repo#658]
### 问题类型 / Type of issues
* 软件打包请求 / package request

### 受影响的软件包 / Affect packages
vnote-git

* 简述 / Brief Description
已有使用代码编译的 aur 包，希望能提供二进制包。
* 上游链接 / Upstream Link
https://github.com/tamlok/vnote/releases
* 为何需要这个软件包 / Why Need This Package
现有的 vnote-git 编译时需要安装的依赖包很大，而 vnote 源是提供 appimage 的。所以直接安装二进制包就很方便。只需要额外提供 desktop 文件和图标。

**Comment by amitbha** [comment]
编译好了的二进制包吗？没看到啊
vnote-git 其实是从 github 下载代码，自己编译的。我就觉得编译环境安装麻烦。
建议加一个直接下载二进制包的 PKGBUILD

**Comment by petronny** [comment]
archlinuxcn/vnote-git v1.11.1.49.g17b5ac5-1
    A Vim-inspired note-taking application, especially for Markdown.

**Comment by amitbha** [comment]
哦，原来cn里都是编译好的包啊 ☻
