### ISSUE TITLE
petsc,glibc-wsl AUR上游消失

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#661]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages
* petsc
* glibc-wsl

----

如题

**Comment by zsrkmyn** [comment]
May I remove these two packages? Or just remove lilac.py of them? The nvchecker mail is really annoying...
Besides, glibc-wsl shouldn't be in base group.

**Comment by petronny** [comment]
...本来明天lilac就自动删了的。。。
你这一回复。。。

**Comment by zsrkmyn** [comment]
23333
