### ISSUE TITLE
gcc5: needs rebuilt against mpfr 4.0 (libmpfr.so.6)

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#662]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* gcc5
----

```
$ echo | gcc-5 -x c -
/usr/lib/gcc/x86_64-pc-linux-gnu/5.5.0/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory
$ ldd /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/cc1 | grep mpfr
        libmpfr.so.6 => /usr/lib/libmpfr.so.6 (0x00007f60288bf000)
```
Ref: https://www.archlinux.org/todo/mpfr-400/

Haven't had time to check if any patch is necessary. If this is the case, please tell me! (You know I'm the maintainer of gcc5 at AUR :)

**Comment by lilydjwg** [comment]
lilac 已经 rebuild 好了。

我在想，怎么让 lilac 来自动关掉这类 issue 呢？

**Comment by yan12125** [comment]
Parse commit message感覺可行？

https://github.com/archlinuxcn/repo/search?q=rebuild&type=Commits&utf8=%E2%9C%93

看要用哪種pattern，大家約定成俗一下

**Comment by petronny** [comment]
跟orphan的差不多。。？
如果build.log最后一条这个包的build成功时间>这个issue的时间就关了？

**Comment by petronny** [comment]
我pkgrel上次改得不对。。。再rebuild一次吧。。。
