### ISSUE TITLE
[nvchecker-git] wrong version

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#663]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages
* nvchecker-git

----

比如现在是 1.0.5，而 nvchecker 的最新版本明明是 1.0 然后加了5个 commit。应该是 1.0r5 之类的？或者用日期？

**Comment by petronny** [comment]
现在是不是1.1dev.10了？
这个可以关了吗。。？

**Comment by zsrkmyn** [comment]
啊！抱歉，才看到这个 issue……可是那个 `pkgver()` 明明是仙子写的呀 XD
那要不直接把最后那个`.`改成`r`？

**Comment by lilydjwg** [comment]
嗯，所以我好像已经给改好了吧。

2018年2月20日 01:56，"Stephen" <notifications@github.com>写道：

**Comment by lilydjwg** [comment]
88ea87f2ae57f04480dd618c26dcd2cde389364a

**Comment by yan12125** [comment]
cebc58963fa14760dc9e49ec44f846753ff7ccbe 加了epoch之後lilac似乎沒有重新打包？我還是會遇到以下的錯誤：
```
warning: nvchecker-git: local (1.1dev.10-1) is newer than archlinuxcn (1.1dev.r27-1)
```

**Comment by lilydjwg** [comment]
嗯……我让 lilac 重新打个包。
