### ISSUE TITLE
lxqt should be removed or renamed

### ISSUE THREAD

**Issue by qcts33** [archlinuxcn/repo#67]
lxqt is now available in [community] as a group name. Since the lxqt related packages are now accepted by the official repo, I think you should remove them now. If you don't want to do that, it's also a good idea to rename the "lxqt" to "lxqt-meta".

**Comment by ykelvis** [comment]
Thanks for the notice. I'm gonna remove all the lxqt packages this weekend, for they are already in arch official repo.
