### ISSUE TITLE
tilix has been moved to [community]

### ISSUE THREAD

**Issue by SilverRainZ** [archlinuxcn/repo#674]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affect packages

* tilix
* gtkd

----

ref: https://www.archlinux.org/packages/community/x86_64/tilix/

**Comment by SilverRainZ** [comment]
@heavysink FYI.

**Comment by lilydjwg** [comment]
我更新了一下。gtkd 是 tilix 的依赖，也进官方源了。

**Comment by SilverRainZ** [comment]
wow 现在对 pending orphaning 的包，liac 不会发 upstream not found 的邮件了么？

**Comment by SilverRainZ** [comment]
https://github.com/archlinuxcn/repo/commit/9b06edcebe0b3f97a5a959bd14bacb6a93a8c077
