### ISSUE TITLE
Package Request: Peek

### ISSUE THREAD

**Issue by axionl** [archlinuxcn/repo#680]
### 问题类型 / Type of issues

* 软件打包请求 / package request

### 受影响的软件包 / Affect packages

Peek

* 简述 / Brief Description
Peek - Simple animated GIF screen recorder with an easy to use interface.

* 主要语言和工具链 / Main Languages and Toolchains
Vala

* 上游链接 / Upstream Link
https://github.com/phw/peek

* 为何需要这个软件包 / Why Need This Package
Peek - an animated GIF recorder.

**Comment by SilverRainZ** [comment]
AUR: https://aur.archlinux.org/packages/peek/

**Comment by SilverRainZ** [comment]
Seems not work on my WM :-(.
