### ISSUE TITLE
Clang version problem in vim-youcompleteme-git

### ISSUE THREAD

**Issue by kosmosoahc** [archlinuxcn/repo#687]
### 问题类型 / Type of issues
* 其它 / other

### 受影响的软件包 / Affect packages
* vim-youcompleteme-git
* llvm-julia

----------------------------------
* **vim-youcompleteme-git** [**PKGBUILD** ](https://github.com/archlinuxcn/repo/blob/master/vim-youcompleteme-git/PKGBUILD)
`_CLANG_VERSION_MAX=5.1  _CLANG_VERSION_MIN=5.0`
`depends=("clang>=$_CLANG_VERSION_MIN" "clang<$_CLANG_VERSION_MAX")`

* Clang's version in archlinuxcn is limited to **5.0-5.1**，but the Clang splited from [lvvm](https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/clang) in offical [archlinux](https://www.archlinux.org/packages/extra/x86_64/clang/) was up to **6.0.0-1**，and there is only two version Clang in the archlinux —— 6.0 and 3.5

* The required **Clang** in _vim-youcompleteme-git_ is from archlinuxcn [lvvm-julia](https://github.com/archlinuxcn/repo/blob/master/llvm-julia/PKGBUILD) 
`archlinuxcn/clang-julia 5.0.1-1`
`C language family frontend for LLVM (with patch for julia)`

* **The problem is**：clang-julia and clang are in conflict. When installed _vim-youcompleteme-git_, I have to remove clang to continue. But the [upstream](https://github.com/Valloric/ycmd/commit/81daa298d82bc80f85a197710dcf8bbb5f37a9be) was already updated Clang to 6.0.0. So I don't konw why the vim-YCM PKGBUILD need to limit the Clang's version before and now?

**Comment by zsrkmyn** [comment]
Updated in 541d31fa1.

**Comment by zsrkmyn** [comment]
Does this issue imply that llvm-julia is out-of-date?
