### ISSUE TITLE
uget-integrator replaces uget-chrome-wrapper

### ISSUE THREAD

**Issue by ktamp** [archlinuxcn/repo#690]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* uget-integrator
* uget-chrome-wrapper

----

**uget-integrator** replaces **uget-chrome-wrapper**.
In your packages rules are set the other way round.

Current **uget** requires **uget-integrator**.
The way rules are set now, GUI pacman wrappers try to replace **uget-integrator** with **uget-chrome-wrapper**, breaking updates when **uget** is installed.

You should either remove **uget-chrome-wrapper** completely or at least set **uget-integrator** to replace **uget-chrome-wrapper**, not the other way round.

**Comment by Sasasu** [comment]
please note you should also install uget-integrator-$browser to use uget-integrator.

uget-chrome-wrapper will be removed after it has removed in AUR.

**Comment by ktamp** [comment]
The thing is **pacman -Syu** still asks every time if it should replace **uget-integrator** with **uget-chrome-wrapper**. At this point it should offer either to replace **uget-chrome-wrapper** with **uget-integrator** or nothing at all.

**Comment by Sasasu** [comment]
run *pacman -Suyuy* , I have fixed this in uget-integrator-1.0.0-2.
uget-chrome-wrapper will be replaced with uget-integrator now.

**Comment by ktamp** [comment]
I tried **pacman -Suyuy**. Still **pacman** asks about replacing **uget-integrator** with **uget-chrome-wrapper**. This is probably because **uget-chrome-wrapper** is listed first in the repository.

Then I looked up the ArchWiki page about PKGBUILD. Under **replaces** it says:

> If providing an alternate version of an already existing package or uploading to the AUR, use the **conflicts** and **provides** arrays, which are only evaluated when actually installing the conflicting package.

So perhaps keeping **conflicts** and removing **replaces** for now (while **uget-chrome-wrapper** is still around) from both PKGBUILDS would do the trick.

**Comment by Sasasu** [comment]
but it works for me...
I will delete uget-chrome-wrapper.

but I can't delete it in AUR, the only thing I can do is send a delete request.
