### ISSUE TITLE
webkitgtk needs to be rebuilt

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#694]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* webkitgtk

----

webkitgtk/webkitgtk2 needs to be rebuilt against extra/icu 61.1
```
$ ldd /usr/lib/libwebkitgtk-3.0.so.0.22.17 | grep icu
        libharfbuzz-icu.so.0 => /usr/lib/libharfbuzz-icu.so.0 (0x00007f7b244b7000)
        libicui18n.so.60 => not found
        libicuuc.so.60 => not found
        libicudata.so.60 => not found
        libicui18n.so.60 => not found
        libicuuc.so.60 => not found
        libicudata.so.60 => not found
        libicuuc.so.61 => /usr/lib/libicuuc.so.61 (0x00007f7b1c71b000)
        libicudata.so.61 => /usr/lib/libicudata.so.61 (0x00007f7b1556e000)
```
I've also added a commit https://aur.archlinux.org/cgit/aur.git/commit/?h=webkitgtk&id=ce860253f79acb92a1ac9469df1da304a020d6ad to force ICU 61.

**Comment by yan12125** [comment]
Oops, this seems the same issue as https://github.com/archlinuxcn/repo/issues/693. Sorry for the duplicate.

**Comment by colinkeenan** [comment]
This will be ready when I wake up maybe 8 hours from now.

**Comment by colinkeenan** [comment]
Done

**Comment by yan12125** [comment]
Hi - too lazy to open a new issue so I reuse the existing one. webkitgtk needs to be rebuilt against ICU 62 now. As usual, please tell me if patching is necessary.

**Comment by amishxda** [comment]
It appears that now only one package (gimp-git) from archlinuxcn needs this. But that is also an older version 2.10.2 whereas Arch official repo already has version 2.10.4.

**Comment by colinkeenan** [comment]
I'm building it now, but you should go ahead and build it the next time without opening an issue. I won't bother maintaining it anymore. This takes many hours to build even on a fast machine because it restricts building to one CPU.

**Comment by yan12125** [comment]
Thank you very much for all previous efforts. I'm fine to handle all future stuffs related to this package. Is it OK for you to move [the [webkitgtk] section in nvchecker.ini](https://github.com/archlinuxcn/repo/blob/57d7c72946322de1240e55dbb072150af5e35de0/nvchecker.ini#L1368-L1369) to under my name?

> This takes many hours to build even on a fast machine because it restricts building to one CPU.

Unfortunately, there are reports that parallel building is broken...

**Comment by colinkeenan** [comment]
Yes. I will move it under your name in nvchecker.ini once I've uploaded this build. Of course, nvchecker won't ever find that it needs to be updated, but you're on top of that.

**Comment by colinkeenan** [comment]
I just realized that I forgot to set the epoch for this. I had been increasing the epoch in the past when I was updating it before AUR did. The current epoch is 3, so it should be increased to 4. I'm going to stop the build, move it under your name, and let you build it starting today.

Please take over as of today.

**Comment by yan12125** [comment]
Got it! Building now.

**Comment by yan12125** [comment]
Done.
