### ISSUE TITLE
[RFC] 改进更新配置方式

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#703]
### 问题类型 / Type of issues
* 其它 / other
----

像 @petronny 在 https://github.com/archlinuxcn/repo/commit/d9d0056f682262eca683a894e73382bee4a9d140#commitcomment-28473281 说的，把更新信息写在 lilac.py 里，比如：

```py
update_on = [{
  'pypi': 'trio',
}, {
  'archpkg': 'python',
  'from_pattern': r'^(\d+\.\d+)\..*',
  'to_pattern': r'\1',
}]
```

这样，一个包的更新可以被多个来源的更新所触发。比如 Python 的库不仅跟踪 PyPI，而且在官方 python 包进行版本升级时也可以得到更新。

依赖：
* https://github.com/lilydjwg/nvchecker/issues/67

使无效：
* 使用 nvchecker.ini 中的信息寻找维护者。把维护者信息写于 lilac.py 中？

----
* [x] 解决 https://github.com/lilydjwg/nvchecker/issues/67
* [x] lilac 更新 nvchecker 版本
* [x] lilac 使用上述特性
* [x] lilac 兼容两种配置方案
* [x] pre-commit 兼容两种配置方案
* [x] 迁移少量 lilac.py 测试
* [x] 迁移所有 lilac.py
* [x] lilac 去除使用 nvchecker.ini 的方案
* [x] pre-commit 去除使用 nvchecker.ini 的方案
* [x] 清理脚本中去除 nvchecker.ini 的操作

**Comment by petronny** [comment]
之前应该还要解决lilac.py只load一次的问题。。。

**Comment by lilydjwg** [comment]
@petronny 啊，那个是什么问题来着？

**Comment by petronny** [comment]
就是现在检测依赖会读一次lilac.py
build包读pre_build时也会读一次lilac.py

然后 https://github.com/archlinuxcn/lilac/pull/48 尝试设置time_limit时也会读一次lilac.py

现在这个depends检测估计也会。。。

**Comment by lilydjwg** [comment]
读多次会有什么问题呢？

**Comment by petronny** [comment]
除了做了重复劳动就没了吧。。。

**Comment by lilydjwg** [comment]
那就不管它好了……

**Comment by petronny** [comment]
我试试

**Comment by lilydjwg** [comment]
@farseerfc 你可以开始改 pre-commit 啦。

**Comment by farseerfc** [comment]
改好啦，現在 pre-commit 支持 update_on 寫在 lilac.py 裏或者出現在 nvchecker.ini ，也順便合併了之前整個放進子目錄 archlinuxcn 的那個 patch 。
不過因爲需要 `ast.parse` 所有的 lilac.py ，而且這些 lilac.py 讀自 `git cat-file` 而非工作目錄，所以會比之前慢一點。現在我這邊跑一次大概 4s 左右。

**Comment by lilydjwg** [comment]
另见 https://github.com/archlinuxcn/repo/issues/883。我打算把 update_on 完全迁移到 lilac.yaml 里去。

**Comment by farseerfc** [comment]
pre-commit 移除了關於 nvchecker.ini 的檢查 b4248549f6474bdbedd4eedf159929738976698d
