### ISSUE TITLE
Package Request: firefox-beta

### ISSUE THREAD

**Issue by nopyhe** [archlinuxcn/repo#706]
### 问题类型 / Type of issues

* 软件打包请求 / package request

### 受影响的软件包 / Affect packages
* firefox-beta

----

* 简述 / Brief Description
Firefox beta version
* 上游链接 / Upstream Link
https://www.mozilla.org/en-US/firefox/channel/#beta
https://aur.archlinux.org/packages/firefox-beta/
https://aur.archlinux.org/packages/firefox-beta-bin/
* 为何需要这个软件包 / Why Need This Package
``firefox-nightly`` is already in repo, but it updates sooooo fast and more unstable. I think ``firefox-beta`` is just right.

**Comment by yan12125** [comment]
Done~
```
$ pacman -Ss firefox-beta
archlinuxcn/firefox-beta 60.15-1.1
    Standalone web browser from mozilla.org, with telemetry and signing disabled
archlinuxcn/firefox-beta-bin 60.0b16-1.1 [installed]
    Standalone web browser from mozilla.org - Beta
```
