### ISSUE TITLE
Package request: albert

### ISSUE THREAD

**Issue by amitbha** [archlinuxcn/repo#713]
### 问题类型 / Type of issues

* 软件打包请求 / package request

### 受影响的软件包 / Affect packages

* 简述 / Brief Description
Albert 是一个类似 macos 下 Alfred 的强力启动工具，能够快速运行程序、打开文件、打开浏览器书签、搜索、计算等，并支持自定义扩展

* 主要语言和工具链 / Main Languages and Toolchains
C++、Qt

* 上游链接 / Upstream Link
https://github.com/albertlauncher/albert.git

* 为何需要这个软件包 / Why Need This Package
很方便

**Comment by Sasasu** [comment]
upstream: https://aur.archlinux.org/packages/albert/
