### ISSUE TITLE
Package Request: python-numpy-mkl

### ISSUE THREAD

**Issue by dianlujitao** [archlinuxcn/repo#718]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

NumPy automatically maps operations on vectors and matrices to the BLAS and LAPACK functions wherever possible. Since Intel® MKL supports these de-facto interfaces, NumPy can benefit from Intel MKL optimizations through simple modifications to the NumPy scripts.

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/python-numpy-mkl/
http://www.numpy.org/
https://software.intel.com/en-us/articles/numpyscipy-with-intel-mkl

* 为何需要这个软件包 / Why Need This Package

NumPy is widely used in many computer science areas, especially machine learning. As seen in Intel's document, it runs much faster on Intel processors when built with Intel® Math Kernel Library. However, the [toolchain](https://aur.archlinux.org/packages/intel-compiler-base/) is large and not frequently used. A prebuilt version can help a lot.

**Comment by zsrkmyn** [comment]
我估计不会有人打包。因为依赖 `intel-mkl`，这个包需要注册 intel 账户并且手动下载 source binary，老麻烦了。

不过之前我倒是写过一篇帖子，可以把系统里的 lapack/blas/cblas/fftw 都换成 mkl 的，这样编译时依赖这堆线型库的程序默认都会使用 mkl。 http://bbs.archlinuxcn.org/viewtopic.php?id=4418

**Comment by dianlujitao** [comment]
`intel-mkl`这个依赖包是mkl的预编译库，不需要注册intel账户，aur直接打包安装即可，不过体积十分巨大。
`intel-compiler-base`这个包是intel的工具链，只在编译过程需要，也可以aur直接打包安装，不过需要注册intel账户并申请授权。
以上两个包都是`intel-parallel-studio-xe`的分包。

**Comment by zsrkmyn** [comment]
哦，忘了，年代久远可能记错了吧……

**Comment by dianlujitao** [comment]
这个numpy的并行能力与官方源的相比有肉眼可见的巨大提升，官方的基本是一核有难七核围观。。非常希望archlinuxcn能提供prebuilt版本，不过如果的确部署困难或者eula不允许mkl再分发或者其他原因导致不能收录，请关闭这个issue。

**Comment by farseerfc** [comment]
或者考慮讓 arch4edu 加？他們已經有打包 intel-parallel-studio-xe 了或許會容易點。 https://github.com/arch4edu/arch4edu

**Comment by zsrkmyn** [comment]
[arch4edu](https://mirrors.tuna.tsinghua.edu.cn/arch4edu/x86_64/) 倒是提供 icc 全家桶，不过好像没有 numpy-mkl。如果在源里有人收养 icc 全家桶和 numpy-mkl 前你要用到的话，可以先暂时用下那边的 mkl XD。

**Comment by dianlujitao** [comment]
https://github.com/arch4edu/arch4edu/issues/14
