### ISSUE TITLE
libqtshadowsocks 和 shadowsocks-qt5 需要重新编译？

### ISSUE THREAD

**Issue by xgdgsc** [archlinuxcn/repo#72]
我今天更新系统后，ss-qt5会segfault，重新编译 libqtshadowsocks 和 shadowsocks-qt5 解决。

**Comment by ykelvis** [comment]
具体表现是用libqtshadowsocks后端，点start就segmentation？我在本地也是这样。。后来重新编译好了，我以为是Syu的问题来着......

**Comment by lilydjwg** [comment]
又是哪个库改了 ABI 没 bump SONAME 么……

**Comment by ykelvis** [comment]
不知道...刚又编译了下新版没问题了..你们试试有问题不...

**Comment by xgdgsc** [comment]
新版没问题了
