### ISSUE TITLE
lxd is out of date

### ISSUE THREAD

**Issue by haruue** [archlinuxcn/repo#720]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affect packages

* lxd

----

The package in official repos `community/lxc` has been upgraded to `1:3.0.0-1`, while `archlinuxcn/lxd` is still `2.20-1`. 

Now no container can be launched and all operation produce following error.

```
error: Failed to set LXC config: lxc.console.buffer.logfile=/var/log/lxd/updater/console.log
```

Please upgrade `archlinuxcn/lxd` to 3.0

Refer: https://github.com/lxc/lxd/issues/4490#issuecomment-384011669

**Comment by haruue** [comment]
However, lxd is still 2.20 after 5 days. 
It seems that @lilacbot makes a update only when AUR changed, rather than comparing the repo version with AUR anytime. 
So maybe some more action should be taken manually.

**Comment by zsrkmyn** [comment]
yes, lilac does:
https://github.com/archlinuxcn/repo/blob/master/nvchecker.ini#L1657

**Comment by kaseiwang** [comment]
I do manually update lxd. Which mirrors are you using?

**Comment by haruue** [comment]
Oh, sorry, my mistake...
So this issue can be closed now.
