### ISSUE TITLE
Package Request: annie

### ISSUE THREAD

**Issue by amitbha** [archlinuxcn/repo#723]
### 问题类型 / Type of issues

* 软件打包请求 / package request

### 受影响的软件包 / Affect packages

* 简述 / Brief Description
视频下载器，可取代 you-get

* 主要语言和工具链 / Main Languages and Toolchains
go

* 上游链接 / Upstream Link
https://aur.archlinux.org/packages/annie/

* 为何需要这个软件包 / Why Need This Package
you-get开始下坡路了

**Comment by a-wing** [comment]
Added eccd80d
