### ISSUE TITLE
reqpkg & upgpkg

### ISSUE THREAD

**Issue by OriginCode** [archlinuxcn/repo#728]
### 问题类型 / Type of issues

* 软件打包请求 / package request
* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affect packages
* linux-macbook

----
reqpkg `linux-macbook-docs` `linux-macbook-headers`
對 `linux-macbook` 包的額外補充

**Comment by ykelvis** [comment]
a2160e8
d32740c

**Comment by zsrkmyn** [comment]
lilac 對一個 issue 只能解析一個 type，出現多個會以最後一個爲準。下次分開寫吧。
