### ISSUE TITLE
xfce*-devel out-of-date

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#73]
好像有一大波 XFCE4 的东西过期了啦，比官方源里的还旧呢。

**Comment by ykelvis** [comment]
那些包都是跟着aur升级的，等等我看下和官方重的删了吧...

**Comment by colinkeenan** [comment]
I was the one to ask for the xfce*-devel packages, before I was maintaining
packages for archlinuxcn. I've updated my own system to all the xfce 4.12
stuff. There are issues with the xfce 4.12 panel that the devel version did
not have, so the out of date devel version may be useful for a while.

I don't care if the packages are removed from archlinuxcn though.

**Comment by lilydjwg** [comment]
@colinkeenan maybe it should be repackaged anyway; they may be using different versions of libraries.
