### ISSUE TITLE
Package Request: qownnotes  

### ISSUE THREAD

**Issue by LinArcX** [archlinuxcn/repo#730]
* package request
Hi. Please provide [qownnotes](https://aur.archlinux.org/packages/qownnotes/) package.

For package requests, please add the following info:
* 简述 / Brief Description :  QOwnNotes is a open source notepad and todo list manager with markdown support and ownCloud integration. This package is the "official" release of QOwnNotes on AUR.
* 主要语言和工具链 / Main Languages and Toolchains: ---
* 上游链接 / Upstream Link: http://www.qownnotes.org/
* 为何需要这个软件包 / Why Need This Package: the compile process is too long.
-->

**Comment by axionl** [comment]
Added on commit: [0abf50d](https://github.com/archlinuxcn/repo/commit/0abf50d5733314ed93d2d3ec48281b9ee104a44a)
