### ISSUE TITLE
Package Request: pkgbrowser

### ISSUE THREAD

**Issue by LinArcX** [archlinuxcn/repo#733]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / [A utility for browsing pacman databases and the AUR](https://aur.archlinux.org/packages/pkgbrowser/)

* 上游链接 / https://bitbucket.org/kachelaqa/pkgbrowser/wiki/Home

* 为何需要这个软件包 / for time saving for pull source from upstream.

**Comment by axionl** [comment]
Added on: https://github.com/archlinuxcn/repo/commit/ac54d63014405d79ec198d457b0d913dcf29212f
