### ISSUE TITLE
yay-git PKGBUILD depends

### ISSUE THREAD

**Issue by kosmosoahc** [archlinuxcn/repo#738]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages
* yay-git

----

AUR 作者之前将 git 从 makedepends 改换到 depends ，我看这里的PKGBUILD还是之前没改的版本，不过还是能自动update使用的。

**Comment by axionl** [comment]
Added: https://github.com/archlinuxcn/repo/commit/5d9c0b6bfa459e2fc50c0712d86bf2cea758841f
