### ISSUE TITLE
Package Request: otf-fira-code and ttf-fira-code

### ISSUE THREAD

**Issue by axionl** [archlinuxcn/repo#740]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Monospaced font with programming ligatures

* 主要语言和工具链 / Main Languages and Toolchains

shell

* 上游链接 / Upstream Link

[otf-fira-code]

> [AUR](https://aur.archlinux.org/packages/otf-fira-code/)
> [Github](https://github.com/tonsky/FiraCode)

[ttf-fira-code]

> [AUR](https://aur.archlinux.org/packages/ttf-fira-code/)
> [Github](https://github.com/tonsky/FiraCode)

* 为何需要这个软件包 / Why Need This Package

A useful programming font.

**Comment by axionl** [comment]
https://github.com/archlinuxcn/repo/commit/4831c51b8fd339452531dc0cbaaf7146b3c84efe

**Comment by frantic1048** [comment]
community 仓库里应该已经有了这俩？ https://www.archlinux.org/packages/?q=fira-code
