### ISSUE TITLE
请求添加electron-ssr-source

### ISSUE THREAD

**Issue by lsblk** [archlinuxcn/repo#746]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description
这是一个跨平台（支持Windows MacOS Linux系统）的ShadowsocksR客户端桌面应用，它功能丰富，支持windows版大部分功能，更有更多人性化功能。它是开源的，它来源于开源，回馈以开源。
* 主要语言和工具链 / Main Languages and Toolchains

* 上游链接 / Upstream Link
https://github.com/erguotou520/electron-ssr
* 为何需要这个软件包 / Why Need This Package
这是linux下仅有的shadowsocksr的图形界面客户端，希望收录。

**Comment by axionl** [comment]
This software is not suitable for included now, because of the following reasons:

- The number of votes is less than 10.
- It seems to have some bugs on other DE except GNOME according to the [README](https://github.com/erguotou520/electron-ssr#%E5%B7%B2%E7%9F%A5bug).
- Do you really need it as an archlinux user?

Well, if you really wanna use it, you can try it from [AUR](https://aur.archlinux.org/packages/electron-ssr-source/) even though it's not a stable way.

**Comment by SilverRainZ** [comment]
> The number of votes is less than 10.

CN 源哪有关于票数的限制……

> Do you really need it as an archlinux user?

Arch Linux 不主张帮用户选择，所以没有真正的 "really need"。

**Comment by lsblk** [comment]
> The number of votes is less than 10.
使用的人好像确实不多。。这个客户端年初重写才到可用的程度，所以说名气不是很大。

> It seems to have some bugs on other DE except GNOME according to the README.
这个只是那个系统代理功能，貌似ss-qt5也没有什么好的实现。所以说不能算bug吧。。只能说功能不完整。

> Do you really need it as an archlinux user?
这是仅有的linux下的ssr图形客户端了，我的服务商还在使用ssr，其他人应该也有这种需求。毕竟ssr的订阅功能还是很适用于商业运行的。

**Comment by axionl** [comment]
> Usually, at least 10 votes are required for something to move into community. However, if a TU wants to support a package, it will often be found in the repository. 

Well, it's my mistake.

**Comment by axionl** [comment]
@lsblk 但是无论是 AUR 本身的质量还是包内自带的 ssr 下载，抑或是 electron 都让我没有打包的欲望。:joy: 另外上游提供了 AppImage 也不是不能用（逃 :cry:

**Comment by lsblk** [comment]
@axionl 好吧，那我就关掉issue了，

**Comment by axionl** [comment]
我重新写了个 AUR，是从源码编译的，原来的那个 electron-ssr-source 一点也不 source (逃
但是打出来的包还是太大，本身 ssr 的占用还是挺小的，结果搞个 electron 版本的出来，打出来的包都 130 Mb+ 了，感觉还是不太实用，通过在群里讨论，考虑诸多因素，不少开发者也认为并不适合去做这样一个打包工作，所以暂时没有加入 archlinuxcn 源的计划，抱歉，另外可能会有 BUG。

> [AUR 地址](https://aur.archlinux.org/packages/electron-ssr/)

![image](https://user-images.githubusercontent.com/8396456/40586499-45b000b4-61f5-11e8-922e-01a87ba7a693.png)

**Comment by lsblk** [comment]
@axionl 感谢你们做了这么多的工作，麻烦你们了
