### ISSUE TITLE
 unity-editor

### ISSUE THREAD

**Issue by xuehrs** [archlinuxcn/repo#749]
### 问题类型 / Type of issues

* 软件打包请求 / unity-editor unity-editor-doc unity-editor-standardassets unity-editor-example unity-editor-android unity-editor-ios unity-editor-mac unity-editor-webgl unity-editor-windows unity-editor-facebook
* 为何需要这个软件包 / aur源下载太慢，建议添加到archlinuxcn的仓库中。完整安装快20G了

**Comment by Sasasu** [comment]
我想做这个，但是unity有没有分发问题？

**Comment by xuehrs** [comment]
可惜了，中国环境～～，谢谢你的回答
