### ISSUE TITLE
ttf-google-fonts-git不包含字体？

### ISSUE THREAD

**Issue by wongsyrone** [archlinuxcn/repo#75]
贴吧有人报告 “今天更新时发现这个包只有0.02MB大小，其中不包含任何字体”
链接：http://tieba.baidu.com/p/3644412676
我没有用这个包，所以不太清楚具体情况，菊苣们检查一下？

**Comment by lilydjwg** [comment]
因为原上游仓库里确实没有任何字体了，只有一个 README.md 说字体转移到 GitHub 了…………

**Comment by lilydjwg** [comment]
今天晚上机器人应该会自动更新这个包。
