### ISSUE TITLE
rebuild package-query

### ISSUE THREAD

**Issue by huiyiqun** [archlinuxcn/repo#752]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affect packages

* package-query

----

pacman 升级之后 libalpm.so 升级到了 libalpm.so.11，而 package-query 依然依赖 libalpm.so.10

**Comment by AstroProfundis** [comment]
Same problem here, package-query is looking for `libalpm.so.10`.
