### ISSUE TITLE
将软件包的目录移到 archlinuxcn/ 子目录

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#753]
### 问题类型 / Type of issues
* 其它 / other
----

为了让 github 仓库首页整洁些，方便查阅非软件包的文件。

### 步骤

* [x] 确认对 lilac 的影响（修改配置后应当无问题）
* [x] 确认 lilac 打包程序没有在运行，并阻止其运行
* [x] 调整 lilac 打包程序的配置
* [x] 调整 lilac issuebot 的配置
* [x] 调整 lilac webhooks 的配置
* [x] 更新 cleanup-package-files
* [x] 调整 pre-commit 脚本
* [x] 调整清理脚本
* [x] 移动文件（包括 .gitignore）
* [x] 修改 lilac 的数据，跳过此提交
* [x] 更新编译机上的仓库
* [x] 放行 lilac

**Comment by farseerfc** [comment]
需要在某個步驟加入
- [ ] 调整  `.gitignore` 

看起來 pre-commit 只需要調整這些 https://fars.ee/Lp3k/diff 就能用了，同時兼容有沒有子文件夾的情況。

**Comment by lilydjwg** [comment]
这个等 #703 完成之后再继续。

**Comment by lilydjwg** [comment]
It's done :tada:.
