### ISSUE TITLE
mpv not working

### ISSUE THREAD

**Issue by BurhanDanger** [archlinuxcn/repo#754]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

mpv-git
ffmpeg-git

----

请在此补充说明。
Please describe in detail here.

```
$ mpv
ffmpeg library versions:
   libavutil       56.18.102
   libavcodec      58.19.102 (runtime 58.19.104)
   libavformat     58.16.100 (runtime 58.17.100)
   libswscale      5.2.100
   libavfilter     7.24.100
   libswresample   3.2.100
ffmpeg version: N-91189-gea0010bf9c

mpv was compiled against a different version of FFmpeg/Libav than the shared
library it is linked against. This is most likely a broken build and could
result in misbehavior and crashes.

mpv does not support this configuration and will not run - rebuild mpv instead.

Exiting... (Fatal error)

$ pacman -Q mpv-git ffmpeg-git
mpv-git 0.28.0_583_gfae9d7744c-1
ffmpeg-git 4.1.r91189.gea0010bf9c-1

```

**Comment by petronny** [comment]
4c5ba8d

**Comment by BurhanDanger** [comment]
I'm happy with https://github.com/archlinuxcn/repo/commit/4c5ba8d482eeeefe3f00e7caaaac5b31891a224f but It's going to break for someone who wants to have both mpv-git and ffmpeg-git

**Comment by zsrkmyn** [comment]
ffmpeg-git `provides` ffmpeg, and thus it would be okay to both keep mpv-git and ffmpeg-git.

**Comment by petronny** [comment]
@zsrkmyn 但是这样mpv-git不会工作的。。。mpv-git貌似只能用编译时装的那个ffmpeg，git版多一个commit都不行。。。

**Comment by zsrkmyn** [comment]
Orz
Then we need mpv-ffmpeg, mpv-ffmpeg-git, mpv-git-ffmpeg, mpv-git-ffmpeg-git.
