### ISSUE TITLE
Package Request: polybar

### ISSUE THREAD

**Issue by U2FsdGVkX1** [archlinuxcn/repo#755]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

polybar 是一个快速和易用的状态栏（copy官方介绍）

* 主要语言和工具链 / Main Languages and Toolchains

C++

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/polybar

* 为何需要这个软件包 / Why Need This Package

现在有很多 i3+polybar 的搭配，不过一直没收录到 community 仓库，导致每次安装都需要编译

AUR 数据：

> 得票：99
> 受欢迎度：7.230871

**Comment by a-wing** [comment]
感觉这个不错哦

**Comment by a-wing** [comment]
Add 2617edde22d3d97ea55033563364c3d27cdd4990

> 这包编译是够慢的
