### ISSUE TITLE
swig & xpra are in official repos

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#757]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* swig
* xpra

----

* swig is added to archlinuxcn yesterday (https://github.com/archlinuxcn/repo/commit/2587137013398451bc53131d0862b7d72c70c4e6), while it has been in [extra] [since long time ago](https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/swig)
* xpra is just added to [community]: https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/xpra

**Comment by renyuneyun** [comment]
已移除swig及清理相關腳本。

swig is removed, and relevant scripts are cleaned up.

**Comment by yan12125** [comment]
Thanks! You may want to un-assign yourself the next time.

**Comment by farseerfc** [comment]
xpra 也已經刪掉了呀 https://github.com/archlinuxcn/repo/commit/5fe1d54543a5187c92ff2303b8720a3520cb3517 對應二進制包會每日定期清理
