### ISSUE TITLE
perl-rpc-xml timeout

### ISSUE THREAD

**Issue by renyuneyun** [archlinuxcn/repo#759]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* perl-rpc-xml

----
受上游腳本問題(rjray/rpc-xml#14)影響，該包在打包時會檢查無法通過，並會停在錯誤處直至超時。

是否應該移除該包的lilac.py，改爲純手動管理（直到上游解決問題）？
（該包是另一包apparmor的依賴，而apparmor受lilac管理，所以有此一問。）

更多信息，見[社區論壇上這一主題](http://bbs.archlinuxcn.org/viewtopic.php?id=5593)。

**Comment by renyuneyun** [comment]
Hmm... 我手動打一下這兩個包吧。好奇怪的，之前上傳上去的（打包好簽名好的）perl-rpc-xml這麼多天了沒出現在倉庫中。。。

`lilac.py`中的`depends=[]`一句是告訴lilac打包時**一定要**先去打包列表中的包麼？
還是說會告訴lilac**傾向於**先打列表中的包？（這決定了apparmor如果交給lilac自動來打要不要寫這句……我感覺要是我手動管理的話，apparmor絕對會落後至少好幾個星期。。。除非有人提交報告）

**Comment by lilydjwg** [comment]
嗯，一定要先处理的。所以你这样只能用 archlinuxcn-* 然后不写 depends 了。不过目前的新包被 lilac pick 到的延迟已经降低到十几秒，所以你只要不在那十几秒内上传包 lilac 都是能 pick 到的。

> 之前上傳上去的（打包好簽名好的）perl-rpc-xml這麼多天了沒出現在倉庫中。。。

ls ~/repo 看一下，它们还在那里没有被 pick 走，因为没压缩啊……签名的扩展名也不对。

**Comment by renyuneyun** [comment]
誒？這個警告是什麼時候的？
我在幾分鐘前剛使用`extra-x86_64-build -- -I path/to/perl-rpc-xml`測試打包apparmor，但還沒放到`~/repo`呢（還沒簽名呢）……

如果是更早的，那應該是lilac自己打包時候最後報錯的？但lilac的郵件一直跟我說是perl-rpc-xml沒打包成功，所以apparmor失敗了啊。。。

**Comment by renyuneyun** [comment]
（忽略上一條）剛剛眼花看成/home/repo了，但仔細一看是/data/repo。。。

看來是lilac動作很快啊，這就打包好了（1:11分的時候上傳的perl-rpc-xml，1:18就打好了apparmor）？……那麼這個錯誤就不確定了。。。

**Comment by lilydjwg** [comment]
tar 包里第一个文件不是 .PKGINFO。不过没太大关系，那个包里它是第二个文件。也许是 makepkg 的逻辑有些不一样了。

**Comment by renyuneyun** [comment]
不知道，沒注意這點。這個“.PKGINFO是tar中第一個文件”的表現是在哪裏說明的麼？

其他的split package有過類似表現麼？

（該issue應該算是解決了，先關掉它。）

**Comment by lilydjwg** [comment]
没有说明……只是 archrepo2 要读 .PKGINFO 所以希望拿到的是优化的包罢了。不过其实在开头都还好，哪天遇到问题再说轻。
