### ISSUE TITLE
grub2-theme-arch-leap AUR upstream not found

### ISSUE THREAD

**Issue by SilverRainZ** [archlinuxcn/repo#761]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* grub2-theme-arch-leap

**Comment by ykelvis** [comment]
在aur-requests没搜到 官方源里也没有..... 这个包到底去哪了= =

**Comment by axionl** [comment]
AUR 那个不知道是不是删掉了。

https://github.com/i3wm/grub2-theme-arch-leap

**Comment by petronny** [comment]
我先改成manual了。。。这样就没有报错邮件了

**Comment by petronny** [comment]
14天没有新动静了，orphan掉?

**Comment by ykelvis** [comment]
改成track github吧 github=i3wm/grub2-theme-arch-leap 这样写吗？

**Comment by SilverRainZ** [comment]
是的。
