### ISSUE TITLE
[package-request] thelounge

### ISSUE THREAD

**Issue by axionl** [archlinuxcn/repo#763]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

The Lounge — Modern self-hosted web IRC client 

* 主要语言和工具链 / Main Languages and Toolchains

nodejs
npm
yarn

* 上游链接 / Upstream Link

[AUR](https://aur.archlinux.org/packages/thelounge/)
[Github](https://github.com/thelounge/thelounge)

* 为何需要这个软件包 / Why Need This Package

A beautiful IRC client.

**Comment by a-wing** [comment]
这个 package-request 是给你自己立的吗？

**Comment by axionl** [comment]
不不不，偷偷塞给彼得（x:
