### ISSUE TITLE
python-requests-cache

### ISSUE THREAD

**Issue by mfk530** [archlinuxcn/repo#766]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Persistent cache for requests library

* 主要语言和工具链 / Main Languages and Toolchains

python

* 上游链接 / Upstream Link

[aur](https://aur.archlinux.org/packages/python-requests-cache)

* 为何需要这个软件包 / Why Need This Package

最新的netease-musicbox-0.2.5.0依赖

**Comment by axionl** [comment]
有 0.2.5.0 版本了？求个链接（

**Comment by axionl** [comment]
@mfk530 但是沒有推 releases :joy:

**Comment by axionl** [comment]
已经添加：
https://github.com/archlinuxcn/repo/commit/899f5091a730230eb13bc3cf53f4e96554297855
https://github.com/archlinuxcn/repo/commit/e162ef19a64e4aaf4ada6225d9542a1ad077950d

但是由于 releases 还没有推出新版本，所以暂时不会更新。如要使用最新版本，请使用 netease-musicbox-git, 这个近期就会打出包。
