### ISSUE TITLE
netease-musicbox-git

### ISSUE THREAD

**Issue by mfk530** [archlinuxcn/repo#767]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* netease-musicbox-git

----

请在此补充说明。
新版改动太大， PKGBUILD里面的依赖也需要改动了。
目前手动打包测试发现只需要以下依赖就行了：
> python  mpg123  python-requests  python-setuptools  
> python-future  python-pycryptodomex  python-requests-cache

**Comment by axionl** [comment]
所需的依赖昨天已经添加了，只是没有上游 commit 触发更新，我手动改个版本号。

**Comment by mfk530** [comment]
@axionl  额， 我的意思是现在的PKGBUILD文件里的依赖是错误的，只需要依赖python mpg123 python-requests python-setuptools python-future python-pycryptodomex python-requests-cache

**Comment by axionl** [comment]
Fixed: https://github.com/archlinuxcn/repo/commit/7b3ab738c9e787532440105ca4c3787276619394

**Comment by mfk530** [comment]
@axionl 依赖mpg123缺失，安装时不会安装依赖mpg123
[7b3ab73](https://github.com/archlinuxcn/repo/commit/7b3ab738c9e787532440105ca4c3787276619394)里把mpg123去掉了

**Comment by axionl** [comment]
depends=('mpg123') 没起作用？

**Comment by mfk530** [comment]
从安装来看，确实没有用
pacman -Qi netease-musicbox-git
依赖于         : python  python-requests  python-setuptools  python-future  python-pycryptodomex
                 python-requests-cache
