### ISSUE TITLE
Recompile fcitx5

### ISSUE THREAD

**Issue by meijieru** [archlinuxcn/repo#768]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* fcitx5
* fcitx5-*

----

As boost update, these package should be recompiled.

Error information
`E addonloader.cpp:40] Failed to load library for addon punctuation on /usr/lib/fcitx5/punctuation.so. Error: libboost_iostreams.so.1.67.0: cannot open shared object file: No such file or directory`

**Comment by farseerfc** [comment]
what is your version of boost-libs ?
My version of extra/boost-libs is 1.67.0-4 ,which should be compatible with fcitx5-* packages

**Comment by meijieru** [comment]
Sorry as I use manjaro.
Manjaro has delay to update, thus these packages' requirement has been broken.
Last update from manjaro fix this problem.
