### ISSUE TITLE
[PKG REQUEST] lice: a fast cli open-source license generator for dev

### ISSUE THREAD

**Issue by kmahyyg** [archlinuxcn/repo#769]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Lice generates license files. No more hunting down licenses from other projects.

* 主要语言和工具链 / Main Languages and Toolchains

Python3.  Licensed under BSD

Deps: SetupTools, Argparse, [Unittest2] 

* 上游链接 / Upstream Link

https://github.com/licenses/lice

* 为何需要这个软件包 / Why Need This Package

Every time when I dig a new hole to open-source project, I have to find license file everywhere. Why not use this tool to generate one.

Just install it and try it with:

```$ lice agpl3```
```$ lice agpl3 --header```

**Comment by SilverRainZ** [comment]
AUR upsteam: https://aur.archlinux.org/packages/lice-git/
