### ISSUE TITLE
请将我做好的clrmamepro-zh放到仓库

### ISSUE THREAD

**Issue by xuehrs** [archlinuxcn/repo#771]
https://github.com/xuehrs/clrmamepro-zh
这是我仓库，请根据情况修改和添加相关内容

**Comment by xuehrs** [comment]
哦哦哦，我明白了，你们没模板，看不到内容。那么要重开一个帖子吗？

**Comment by lilydjwg** [comment]
看了半天，完全不知道它是个什么东西，也没看到使用的什么许可证。

**Comment by zsrkmyn** [comment]
故事很感人，但是我覺得您還需要整理您製作的內容，讓它更適於發佈。

**Comment by xuehrs** [comment]
那个@zsrkmyn 能帮我优化下，做成合适的版本，顺便我参考下有什么不足的地方。不然我不会这样发帖提问了。谢谢

**Comment by axionl** [comment]
您的心情我可以理解，有幾個問題我想您完善一下：

- 此中文包以何種許可發佈（鑑於原作者已故，添加開源許可可能需要爭得其家屬同意）
- 是否需要添加到本社區源（個人建議如果沒有強烈要求的話可以先行上傳到 [AUR](https://aur.archlinux.org/)）
- 原版遊戲是否允許再分發（暫時沒有在上游[主頁](https://mamedev.emulab.it/clrmamepro/#docs)上找到相關開源計劃或許可，而上傳 AUR 只是相當於安裝腳本，中文翻譯則可以當作補丁加入）

**Comment by xuehrs** [comment]
你也可以根据情况修改，并且我并没有通过相关方式来获利。所有权利全部归属是已故的原作者所有，我个人只是解决mame 的rom工具中文打包的问题。今天我刚刚给原作者的朋友留言，咨询打包问题，请等待消息，明天会收到。原作者的朋友是外国人，注意时差哦

**Comment by xuehrs** [comment]
那个原作者就是给clrmamepro做中文化的人

**Comment by xuehrs** [comment]
尽量把它做好，算是感谢这些年使用过这个工具。我相信，原作者心血不会白费的

**Comment by petronny** [comment]
请您先参考下述模板修改一下您的issue内容
```
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

（这个是干啥的软件，使用的何种协议）

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写，不需要编译的就写有哪些主要依赖就行）

* 上游链接 / Upstream Link

（请在此填写）

* 为何需要这个软件包 / Why Need This Package

（请在此填写）
```

**Comment by lilydjwg** [comment]
@axionl 本仓库的包不需要是开源软件，但不能侵权（不包含盗版之类的内容），并且需要有分发许可（无论是对所有人授权的，还是针对我们仓库授权的）。

**Comment by xuehrs** [comment]
@lilydjwg  大哥，这个工具最近几个月没有更新。估计做这个工具和中文化应该同样的人。论坛里应该有人接手了，也是，我不能急
@petronny  根据您的要做，我重开了一个贴。做好了相关的补充

**Comment by axionl** [comment]
@lilydjwg 嗯，確實不需開源，後面再分發方面的也說了。
