### ISSUE TITLE
Package Request: clrmamepro-zh

### ISSUE THREAD

**Issue by xuehrs** [archlinuxcn/repo#772]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

这是MAME的Rom管理工具，可以管理很多模拟器Rom文件，比如FC、GBA、Fba、Fbas、WinKawaks等等模拟器。

* 主要语言和工具链 / Main Languages and Toolchains

wine、wqy-microhei

* 上游链接 / Upstream Link

http://f.ppxclub.com/686177-1-1  
https://github.com/xuehrs/clrmamepro-zh

* 为何需要这个软件包 / Why Need This Package

这个工具比较复杂，如果只是简单的分离，合并ROM，没有那么多的设置。如果你需要管理MAME的很多周边文件。那么必须将其记牢，有时候我很长时间还忘了某些必须的设置。要知道光是MAME的Rom管理工具所文件大小超过500G(压缩文件4w多，里面有很多小文件)，更别说MAME的其它周边几十万文件。文件一次操作不当，可能要花费不少的时间和资源才能处理好（看数据破损情况，有时十几分钟做好，有时还要挂几天）。

我最近登录PPX论坛才知道作者去世了，在去世前一个星期还在为我们这些街机爱好者做中文包。鉴于这些事，我就有了做clrmamepro中文化打包的想法，希望作者所做一切才不会白费，也希望方便使用clrmamepro工具的新人。

**Comment by petronny** [comment]
我有几个问题：

1. 这个与clrmamepro的关系是什么，clrmamepro-zh是clrmamepro的一个mod组件还是修改版？
1. clrmamepro-zh的汉化原理是什么，有没有违反clrmamepro的协议？  
clrmamepro 3.x的协议可以在[这里](https://mamedev.emulab.it/clrmamepro/docs/index.htm)找到  
clrmamepro 4.x的协议没有，但是很可能与这个相同  
若有违反的话，您需要与clrmamepro的作者联系取得相应的许可

**Comment by xuehrs** [comment]
@petronny 就是同一家的东西。ppx论坛里面好多人向作者请求出中文的。不是修改版，也不是mod组件。就是原作者为中国街机爱好者做的。（后来被原作者的朋友接手了，将其完整中文化了）。
在windows环境下，如果你安装好这个包，这工具可是完美中文 ，没有任何毛病。我更喜欢的是解压即用。也就是说可以支持绿色运行
由于我要将它安装到LInux上，那么你必须安装到window环境上，没办法，只能安装到wine。为了安装到linux，我借鉴了aur里的clrmamepro相关脚本资料
如果你解压这个工具，打开之后，你会发现中文乱码。经过我多次测试和研究，你可以将它在那个脚本前面添加命令，使其自动支持中文语言包``’wine regedit /usr/share/clrmamepro-zh/wqy-microhei.reg  `` 这是你已经安装完毕的情况
参考wiki(https://wiki.archlinux.org/index.php/Wine_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87) 有什么好处，～/.wine 的文件随便你删，反正打开它会自动解决中文不支持问题（乱码）。
实际上，我在https://github.com/xuehrs/clrmamepro-zh 留下了脚本。
你们看不懂吗？

**Comment by xuehrs** [comment]
@petronny  如果原作者还在就好，而且我发现英文版clrmamepro比中文版clrmamepro的版本要低。别忘了，作者可是外国人。以前只有英文版，中文版的只是英文修改而来的。然而这个版本就不是这样的，原作者的朋友自己已经在PPX说过了。我可以告诉你，这个工具没有收费方面服务。我也不会从其获利。

**Comment by xuehrs** [comment]
@petronny 
作者已经同意
我在ppx论坛提问：关于您在“ClrMame Pro 4.034 (18.03.02) 繁體中文化”的帖子
老大，我想获得 你的clrmamepro 相关打包权限，特点就是支持中文。并没有获得相关金钱利益，只是打包了clrmamepro这个工具
参考连接 https://github.com/xuehrs/clrmamepro-zh

然后作者回复：
沒問題,中文化就是要給人使用的,請盡量

图片(https://raw.githubusercontent.com/xuehrs/clrmamepro-zh/master/%E6%88%AA%E5%9B%BE_2018-06-12_09-46-46.png)

**Comment by xuehrs** [comment]
@petronny 不过你可以先等等，看看clrmamepro作者怎么说。

**Comment by zsrkmyn** [comment]
I don't think the package is suitable for this repo. Reasons are listed but not restricted to below:

1. The PKGBUILD is really awful: 
    * useless `pkgdesc`;
    * space-tab-mixed indent;
    * The `url` should be the upstream but not a link to a forum;
    * and why `sha256sums` are all `SKIP`?

2. Whether clrmamepro 4.x can be reproduced and redistributed remains unknown.
3. The copyright of clrmamepro 3.x said: `Don't distribute clrmamepro with any extra files`. I don't think the modified archive in your repo is free to redistribute.
4. I don't think the `-zh` upstream maintainer (you) have the capability to provide a stable, usable and continuously maintained version.

But we can still leave the issue open to continue discussion and to see if any maintainer would like to adopt the package :-)

**Comment by xuehrs** [comment]
@zsrkmyn  你可以先等待PPX论坛哪位行动怎么样。请等待。

**Comment by Sasasu** [comment]
[/usr/bin/clrmamepro-zh](https://github.com/xuehrs/clrmamepro-zh/blob/master/pkg/clrmamepro-cn-zh/usr/bin/clrmamepro-zh) 这个脚本会改 `$HOME/.wine` 的注册表.
你不能假设用户希望在 `$HOME/.wine` 里安装 clrmamepro, 不要动用户的 wine
建议看一下 [aur/osu-wine-git](https://aur.archlinux.org/packages/osu-wine-git/)

**Comment by petronny** [comment]
@Sasasu 这个PKGBUILD的问题实在是不能看了，肯定得重写。。。
现在还是先关注分发权限的问题吧

**Comment by xuehrs** [comment]
@Sasasu 你的问题我想到好办法了.一句话,把它分成俩个包.把那个注册表当成必须的依赖.但是如果你不装这个依赖会乱码..我也在尝试请问作者是否大力支持分发问题.还有Linux方面的
作者连接:https://www.emulab.it/forum/index.php?topic=4230.0

**Comment by xuehrs** [comment]
如果这东西做得不错的话.也许以后不用担心扫档太慢的问题了.毕竟我只用Linux玩MAME.嗯,手感好.

**Comment by xuehrs** [comment]
人家已经回复该程序是免费的.但不会出Linux版本,也不出多语言版本,而且按照官方的意思
这意味着只要你提供完整的档案，你就可以复制这个程序，
不允许修改档案或程序，包括：重命名，重新编译，反汇编！
具体请参考请cmpro包中的copyright.txt文件：
但是,你可以出中文版.因为这里并没有涉及到程序重新编译,反汇编方面.只是提供多语言以适合国人需要

**Comment by xuehrs** [comment]
我感觉,不如出个wine可选依赖包: 解决中文字体环境问题的包.可以根据情况确定是否使用注册表注册来支持什么字体.甚至调节dip什么,甚至一键添加game运行环境等等.

**Comment by xuehrs** [comment]
emulab论坛版主说了,官方将来会出多语言的.包括Linux版本..建议不要修补或操纵官方CMPRO包的内容.也就是说没戏了,建议需要这个工具的人可以等等或者使用其它Rom管理工具.
我只能自己用了,我不得不说一句话.Linux没window好用.但是Rom游戏管理工具就它最好用的.别的就是太慢了,还老坏档.但是linux运行定制版MAME手感却是最好的.

**Comment by xuehrs** [comment]
也许,将来我还能看到clrmamepro上架Linux平台. window和mac平台有了.Linux还远吗?
