### ISSUE TITLE
Out-of-date: libheif

### ISSUE THREAD

**Issue by gojpdchx** [archlinuxcn/repo#774]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* libheif
----
1.3.0 has been released on 2018/06/15 at 12:05 UTC:
https://github.com/strukturag/libheif/releases/tag/v1.3.0

**Comment by heavysink** [comment]
Done. Just wait the build machine for updating.

Now both libheif and libde265 will track github release instead of AUR.
