### ISSUE TITLE
intellij-idea-ultimate-edition out of date

### ISSUE THREAD

**Issue by bianjp** [archlinuxcn/repo#776]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* intellij-idea-ultimate-edition

----

**Comment by lilydjwg** [comment]
你改回来也没有用，lilac 还不会重新解析。

```
[2018-05-22 18:02:01] intellij-idea-ultimate-edition 2018.1.4-1 successful
```

看起来 lilac 的打包没出问题的。

@Sherlock-Holo

**Comment by bianjp** [comment]
还没解决呢？

**Comment by Sherlock-Holo** [comment]
没有看出来lilac.py跟别的包的有什么不同，ini文件里看起来也一切正常，要不管理员手动触发他的打包？

**Comment by axionl** [comment]
https://github.com/archlinuxcn/repo/commit/6789efc6580a967b6b89866d4eb1f7c55aa325da
