### ISSUE TITLE
libheif and libde265 are in [extra]

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#777]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* libheif
* libde265
----

https://www.archlinux.org/packages/extra/x86_64/libheif/
https://www.archlinux.org/packages/extra/x86_64/libde265/

**Comment by heavysink** [comment]
弄好了。
