### ISSUE TITLE
Package Request(packer)

### ISSUE THREAD

**Issue by LinArcX** [archlinuxcn/repo#780]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description : Bash wrapper for pacman and aur

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link : http://github.com/keenerd/packer

（请在此填写）

* 为何需要这个软件包 / Why Need This Package 

（请在此填写）

**Comment by axionl** [comment]
This aur helper is discontinued or problematic.

https://wiki.archlinux.org/index.php/AUR_helpers
