### ISSUE TITLE
dolphin-emu-git contains /usr/lib64 in a way which conflicts with `filesystem`

### ISSUE THREAD

**Issue by aphirst** [archlinuxcn/repo#787]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* dolphin-emu-git
----

When attempting to `-Syu`, I get the following error:
```
(8/8) checking for file conflicts                                                                                [###################################################################] 100%
error: failed to commit transaction (conflicting files)
dolphin-emu-git: /usr/lib64 exists in filesystem (owned by filesystem)
Errors occurred, no packages were upgraded.
```
The package is thus uninstallable (unable to update).

**Comment by aphirst** [comment]
I forgot to mention the versions.

The issue occurred earlier when trying to install:
`dolphin-emu-git 5.0.r8246.86edf7f848-1`
And also occurs after another -Syu with:
`dolphin-emu-git 5.0.r8248.2debe9e9d1-1`

**Comment by aphirst** [comment]
The offending file in the package seems to be a `/usr/lib64/libdiscord-rpc.a`.

**Comment by aphirst** [comment]
Issue persists in `5.0.r8251.beeb6754d2-1`.

**Comment by heavysink** [comment]
I have fixed it. Try again for 5.0.r8251.beeb6754d2-2?

**Comment by aphirst** [comment]
That works now. Thanks! What was going on, then?

**Comment by heavysink** [comment]
@aphirst Well, in Archlinux, /usr/lib64 is a symlink to /usr/lib. However, when dolphin-emu is installing library, it installs into /usr/lib64, which need to create a new lib64 directory. Creating this directory will result in a conflict between the symlink and the directory.
