### ISSUE TITLE
Freecad out of date

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#789]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* freecad
----
0.17 is out

**Comment by yuyichao** [comment]
.... https://github.com/archlinuxcn/repo/issues/839 和 https://github.com/archlinuxcn/repo/issues/696 我打算直接等 LLVM 7.0 了. 这个忘了.....................

**Comment by SilverRainZ** [comment]
@yuyichao llvm 7.0 了。

**Comment by SilverRainZ** [comment]
@yuyichao llvm 8.0 了。

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/pull/31508
