### ISSUE TITLE
[package request] sky

### ISSUE THREAD

**Issue by j16180339887** [archlinuxcn/repo#791]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

    * Skype for business/Lync alternative for Linux

* 主要语言和工具链 / Main Languages and Toolchains

    * Qt

* 上游链接 / Upstream Link

     * https://aur.archlinux.org/packages/sky/

* 为何需要这个软件包 / Why Need This Package

    * Skype 企業版的 Linux 替代方案，雖然有 pidgin-sipe，但是 pidgin 無法傳輸檔案

    * Sky 雖然不是開源的，但是軟件成熟問題少，設定簡單好用

**Comment by heavysink** [comment]
https://tel.red/guides/eula_tel.red.pdf

不知道能不能redistribute

**Comment by j16180339887** [comment]
>  Except as expressly provided in this EULA, you may not otherwise
>  make copies of the SOFTWARE PRODUCT or the printed materials accompanying the
>  SOFTWARE PRODUCT.

粗略翻譯

>  除非 EULA 有所表示, 否則你(們)不可
>  複製軟件或印刷出包含軟件訊息的刊物

這意思似乎是不行

**Comment by petronny** [comment]
AUR上的这个包的提交者就是这个软件的开发者吧？
去留言申请一下如何？

**Comment by j16180339887** [comment]
![](https://i.imgur.com/gVXnqTb.png)

尚未得到官方回應

鏈接在此 https://telred.atlassian.net/servicedesk/customer/portal/4/SLS-3665

**Comment by heavysink** [comment]
@j16180339887 最好注明非盈利性分发。如果16号没得到回应，就打包上来看看吧。

**Comment by heavysink** [comment]
@j16180339887 有回应了吗？

**Comment by j16180339887** [comment]
@heavysink  依然沒有

**Comment by heavysink** [comment]
开ticket人家不一定回。

发了个邮件给对方(ask@tel.red)

Dear Sir/Madam,

I am from Arch Linux Chinese community (ArchlinuxCN), a non-profit community that provides a variety of extra packages for Arch Linux/Manjaro/Antergos users. I would like to port  Linux package of sky to the repository of ArchlinuxCN using the official packaging script (PKGBUILD) here : https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sky. It will make the installation of sky easier for Archlinux users.

The repository is open source. See https://github.com/archlinuxcn/repo.

Could you please tell me if it is possible to get a permission for it?

Kindly regards, 

XXX

===
等吧。毕竟是闭源专利软件，分发最好还是拿到permission，万一擅自分发之后被追责，真的不好。
