### ISSUE TITLE
展示打包历史

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#794]
### 问题类型 / Type of issues
* 其它 / other
----

通过网页展示：

* 目前所有自动构建包的最后一次打包时间、版本（nvchecker 检测结果）和状态（成功或者失败）
* 每个包的构建历史时间、版本和状态
* 「成功指数」：使用滑动平均值来展示最近这个包有多么成功（或者不成功）

RFC: 记录每次打包所花费的时间？

**Comment by a-wing** [comment]
好棒，不过 lilac 目前没把数据存到数据库里吧？

**Comment by lilydjwg** [comment]
嗯。不过 lilac 有记 build.log 哦。可以从那里解析出数据存数据库里去。

**Comment by a-wing** [comment]
这东西现在在做吗？。~~我(ˇˍˇ) 想～ 做~~。。。。还有 build.log 在哪看？

**Comment by lilydjwg** [comment]
还没开始做呢。build.log 位于 ~lilydjwg/.lilac/build.log。

建议的读取方式是拿 inotify 去读取这个文件的更新，存到 sqlite3 数据库里，然后记录一下读到的文件偏移（方便重启后继续）。

**Comment by a-wing** [comment]
我读不了那个文件。。。。

分成三部分岂不更好
1. 解析并发送程序
2. 后台api服务端
3. 前端页面

inotify 读取文件并解析，发个服务端，服务端提供标准的api接口，前端使用api并呈现

**Comment by lilydjwg** [comment]
可以读的啊：
![tail build.log](https://user-images.githubusercontent.com/440661/42383012-961a9dba-8168-11e8-8fc7-28e041f6f01c.png)

不要想着列我家里的东西啦。

PS: 切到你的用户时 nodejs 报了一堆错呢……

**Comment by a-wing** [comment]
日志好简单。。。我还以为多复杂那。。这么简单，解析应该丢后端（写文件时触发事件，丢给服务端）

数据库我推荐PostgreSQL。。。（en，两张表应该就足够了）

日志可以软连接到 /var/log/ 下吗？

PS: 暴露了我在家目录装 nodejs 的事了。。。

**Comment by lilydjwg** [comment]
为什么要软链接到 /var/log？
我懒得维护数据库服务啊喵。

**Comment by a-wing** [comment]
额。。第一反应找 lilac 的日志应该在这里

**Comment by a-wing** [comment]
百合百合
以这条数据为例`[2018-07-07 18:12:17] python-git 20180707.062835 successful after 292s`
- `[2018-07-07 18:12:17]` time 时间 （具体什么时间？写入时间？）
- `python-git` pkgname 包名
- `20180707.062835` time_ 这是什么时间
- `successful` building_status 状态 布尔型？True or False
- `after` (舍掉？)
- `292s` building_time 构建时长

两张数据表：
  - building_latest
  - building_log

**Comment by lilydjwg** [comment]
开头的是日志的写入时间，也就是打包完成的时间（CST）。包名后边那个是 nvchecker 报告的版本号（可能有空格）。结果是「successful」或者「failed」。「after」子句有可能没有的。

**Comment by lilydjwg** [comment]
表名叫「build_xxx」比较好吧。

你大概需要在 building_latest 里记录当前成功了几次失败了几次，方便在总览页面展示。

**Comment by a-wing** [comment]
关于解析还有几个问题
1. 时间都是 +0800 时区吧？好像是。。问的好像多余。。。
2. after 是和构建时长一定是同时出现的吗？
3. 构建时长 的时间的单位一定是秒吗？好像是

**Comment by lilydjwg** [comment]
1. 对。我之前说了。
2. 是。
3. 是。

**Comment by a-wing** [comment]
今天肝不动了。。。差不多下周日上线吧（做解析数据的功能花时间有点多）

- 发送的端 shell 脚本。。。
- 后端 ruby on rails 一把梭（功能还差点）
- 前端准备用 vue.js 全家桶写那。。。。

https://github.com/a-wing/KISS2U

**Comment by lilydjwg** [comment]
WOW 好快，也有好多文件啊……

**Comment by lilydjwg** [comment]
你在编译机上跑起来试试看？

**Comment by a-wing** [comment]
其实我想要个PostgreSQL 的数据库权限喵。还有要用sqlite3 来做数据库？。。。

还有要不要在在编译机上装个bundle。。。还是在我家目录下搞个虚拟的ruby 环境

**Comment by lilydjwg** [comment]
编译机上就没有 PosstgreSQL 的吧。

**Comment by a-wing** [comment]
http://build.archlinuxcn.org:22333/packages/

添加了三条测试数据。。。还行

**Comment by lilydjwg** [comment]
还没有前端呀？

`building_status` true 是什么鬼……注意语义，用「success」和「failure」之类的比较好。

**Comment by a-wing** [comment]
前端还没开始写那（有种周日要跳票的感觉）。。。building_result 还行。。。布尔型，从数据库取出来肯定是 T 或 F 啊。转换成「success」和「failure」应该在前端实行啊。

**Comment by lilydjwg** [comment]
不对。你的数据应当在每一个地方都尽力做到自解释，这样无论以后维护还是别人学习都不会弄错。

**Comment by a-wing** [comment]
要不 building_result 改成 building_success 值为「true」和「false」 ，这样就清晰了

**Comment by lilydjwg** [comment]
叫 building_successful 比较符合语法。不过 building_ok 比较短？

**Comment by a-wing** [comment]
百合百合。。编译机有 nginx 吧。。。

把我家下的这个目录当静态网站
.service/KISS2UI/

然后应该就可以看到效果了。。。。

或许该缕一缕前端页面的需求了。。

PS：明天不想写代码了。。。明天想出去玩 喵。。。（先上线，再迭代。。）逃

**Comment by lilydjwg** [comment]
哪能直接把 git 仓库放 nginx 呢。另外准备一个目录来 serve 静态文件吧。另外为了安全起见，用户家目录都是 700 的，nginx 进不去。所以我给你建了一个 /srv/packages 目录，你可以把静态文件复制过来。

**Comment by a-wing** [comment]
git 仓库。。。额。我 travis-ci 加上不用 git 仓库了。。。（<== 暴露安全意识薄弱）

还有他会异步加载 http://build.archlinuxcn.org:22333/packages/ 里的数据。。。然后那个没https。。浏览器会禁止加载（做个代理吧。。。）

**Comment by lilydjwg** [comment]
可是我代理到哪个路径下呢？

**Comment by a-wing** [comment]
要不前端静态用 package/
RoR 后端用 packages/


RoR 安全隐患。。。。(应该没有。。。)
不觉得麻烦的话就 `单独的用户 + 限制权限来跑` (我自己部署RoR 项目的时候都是新建用户来跑的。。。)

**Comment by lilydjwg** [comment]
你就不会 api/packages/ 么……

**Comment by a-wing** [comment]
可以啊。。。。。

**Comment by lilydjwg** [comment]
好了。

**Comment by a-wing** [comment]
百合百合。。。你忘记把 /api/packages/ 重写成 /packages/ 了。。。。
```
Started GET "/api/packages/" for <手动打码> at 2018-07-14 22:56:56 +0800
ActionController::RoutingError (No route matches [GET] "/api/packages"): 
```

**Comment by lilydjwg** [comment]
好了。

**Comment by lilydjwg** [comment]
前端页面上的排序完全无效啊。

我在想，前端主页面的展示
* 排序默认最近的最先
* 可以按包名搜索
* 可以只显示打包失败者
* 时间显示为几小时几分钟这样
* 成功率感觉没太大意义，因为打包次数不一样

然后每个包一个专门的展示历史的页面，就像 Travis-CI 的 build history 那个样子？

**Comment by axionl** [comment]
对于 Pkgver 等若干字段，建议加上 filter 实现，不然排序意义不大。

顺便补上一个 Build history 图：

![image](https://user-images.githubusercontent.com/8396456/42748865-3e97b5ce-8914-11e8-88fc-0f7d4be38edd.png)

**Comment by a-wing** [comment]
前端页面上的排序完全无效啊。（有效啊，1K多条数据有点延时很正常）
- 包名目前没实现排序（没找着合适的给包名排序的算法）
- 成功率也没法实现排序（成功率是动态计算的）不过这个要去掉了

- [ ] 排序默认最近的最先 enen。目前是最新的数据在最下面，反转一下就好

- 数据搜索：
  - [ ] 可以按包名搜索
  - [ ] 可以只显示打包失败者

- [ ] 时间显示为几小时几分钟这样。（JavaScript 的控制时间的库很蛋疼。要不定死 +0800 时区？）
- [ ] 然后每个包一个专门的展示历史的页面，就像 Travis-CI 的 build history 那个样子？
- [ ] 太老的信息就不要展示 （要不把build.log 最后 1K 条数据作为基础数据？）

**Comment by a-wing** [comment]
@axionl 

> 对于 Pkgver 等若干字段，建议加上 filter 实现，不然排序意义不大。

你说的是搜索的功能吗？

**Comment by axionl** [comment]
@a-wing 搜索功能也不错（但是实际上我表达的是过滤出某个包/组的历史

**Comment by yan12125** [comment]
Build Status的按鈕是預計加入顯示build log的功能嗎？

**Comment by lilydjwg** [comment]
@a-wing 那个时间，我说的是打包用时啦。
可以从最后1k条开始导入数据库，但是以后呢？好像过滤掉已经从仓库中删除的包比较合理（那么就需要定理检查并在数据库里标记包状态了）。

@yan12125 好主意。不过得先等 lilac 那边改进日志的记录。

**Comment by a-wing** [comment]
@axionl @yan12125 单个包的building log 后端有接口 比如：获取mpv-git 的构建历史
```bash
curl https://build.archlinuxcn.org/api/packages/mpv-git
```
显示历史 build log 是要加的功能（我还想加个统计的图表那。。。）
`Build Status的按鈕 ` 我就是借用一下人家写好的样式喵。。。。

@lilydjwg 过滤掉已删除包。。。KISS2U 并没实现这个功能。。。（还要加张表。。。把nvchecker.ini导入进去。。。）

**Comment by yan12125** [comment]
> 单个包的building log 后端有接口 比如：获取mpv-git 的构建历史

啊 我一開始心中想的是makechrootpkg的輸出0.0 常常要登入ssh看log覺得挺麻煩xd

**Comment by lilydjwg** [comment]
@a-wing 不用啊。你可以定期读取软件包列表（读 archlinuxcn.db 好了），然后生成一个文件留着用的。

**Comment by lilydjwg** [comment]
@yan12125 等 lilac 把日志分开记之后，这个就简单了啦。

**Comment by a-wing** [comment]
这个编译机上没装啊。。。。

`inotifywait.sh: line 11: /usr/bin/inotifywait: No such file or directory`

**Comment by lilydjwg** [comment]
@ felixonmars 帮忙装一下？我现在外出，访问不了编译机。

metal A-wing <notifications@github.com> 于 2018年7月20日周五 20:10写道：

**Comment by a-wing** [comment]
@felixonmars

**Comment by felixonmars** [comment]
Installed.

**Comment by a-wing** [comment]
- [x] 排序默认最近的
- [x] 数据搜索：
    - [x] 可以按包名搜索（可以用正则）
    - [ ] 可以只显示打包失败者 (好像没必要，有排序)
- [x] 时间显示为几小时几分钟这样。（根据浏览器时区来显示）
- [x] 然后每个包一个专门的展示历史的页面，就像 Travis-CI 的 build history 那个样子？
- [x] 太老的信息就不要展示

待完成：
- [ ] UI 太丑。。。
- [ ] 爪机端的支持
- [ ] 还有什么？？？

**Comment by lilydjwg** [comment]
包名不要折行啦。

**Comment by a-wing** [comment]
都拖了一个月了。。。。该关掉了

kiss2u 地址（最主要的地址）：https://build.archlinuxcn.org/packages/

关于 Archlinux CN KISS2U 的介绍：https://a-wing.top/archlinux/2018/08/05/kiss2u.html

- kiss2u API ：https://build.archlinuxcn.org/api/packages/
- Github KISS2UI（前端）： https://github.com/a-wing/KISS2UI
- Github KISS2U（后端）： https://github.com/a-wing/KISS2U
