### ISSUE TITLE
Package Request(android-emulator )

### ISSUE THREAD

**Issue by LinArcX** [archlinuxcn/repo#802]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description = Google Android Emulator

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link = https://developer.android.com/studio/releases/emulator.html

（请在此填写）

* 为何需要这个软件包 / Why Need This Package = Because denied iranian users.

（请在此填写）

**Comment by yan12125** [comment]
I'm interested in this!

**Comment by yan12125** [comment]
Done! http://repo.archlinuxcn.org/x86_64/android-emulator-27.3.8-2-x86_64.pkg.tar.xz
