### ISSUE TITLE
请求添加 nautilus-dropbox

### ISSUE THREAD

**Issue by dongfengweixiao** [archlinuxcn/repo#81]
nautilus-dropbox 需要从 dropbox 下载源码，导致可能无法正常的安装。

https://aur.archlinux.org/packages/nautilus-dropbox/

**Comment by petronny** [comment]
话说这个包用的时候需要代理吗？

PS. #80 不用关闭的，你可以编辑那个issue的正文。

**Comment by dongfengweixiao** [comment]
理论上在使用的时候是需要代理的。

难道是，需要代理的软件一律都不可以添加吗？

**Comment by petronny** [comment]
当然没这个意思。。我就是问问。。

**Comment by farseerfc** [comment]
已經推了我簽名的x86_64包到源裏，等源服務器同步更新就有啦，如果你需要i686包請告訴我。
剩下的更新這個包的工作會交給lilac同步aur上的更新。
