### ISSUE TITLE
[Crash] Qt 5.11 causing crash of mendeley-desktop (SEGV_MAPERR), built-in Qt libs needed.

### ISSUE THREAD

**Issue by heavysink** [archlinuxcn/repo#814]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* mendeley-desktop

----
Qt 5.11升级，以至于mendeley-desktop一打开pdf文档就会崩溃并报SEGV_MAPERR。AUR上有讨论解决方法，需要保留自带的Qt库. 参见https://github.com/mchwalisz/mendeleydesktop_aur/commit/53f6d475313da04ac3b7e7a281fbf62e0e6e0406

**Comment by lilydjwg** [comment]
This package is no longer in repo, closing.
