### ISSUE TITLE
polybar 少了好多模块

### ISSUE THREAD

**Issue by yadex** [archlinuxcn/repo#815]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----

请在此补充说明。
Please describe in detail here.

**Comment by yadex** [comment]
原先我是在aur安装，一切正常，竟然更新覆盖GG了

**Comment by lilydjwg** [comment]
@yadex 为什么你们就是不肯按模板填写呢…………

**Comment by a-wing** [comment]
或许这个包应该 orphaning 掉。。。我可能修不好。。。
有几个问题。那个模块是根据可选依赖来编译的。。。
1. 如果打包时不用可选依赖。有些功能会没有。。
2. 如果打包时用全部的可选依赖。有些依赖找不到会报错。无法启动。可选依赖就变成了必选依赖。。

那么多可选依赖每个人情况都不一样。。。还是在AUR里根据安装的包来编译比较好

**Comment by petronny** [comment]
我觉得是默认全开，如果有比较大的可选依赖，比如cuda，分拆成两个包

**Comment by heavysink** [comment]
@a-wing 我一般是这样：默认makedepends全开，然后用一次devtools，看一下日志文件，如果出现E:Dependency needed but missing的话根据情况放进depends或者舍弃, 如果出现W:Dependency needed but optional的话放进optdepends.

**Comment by a-wing** [comment]
现在把全部的 optdepends 变成 depends 了。。如果是 makedepends 有些包找不到会无法启动。。。。

**Comment by y6yuan** [comment]
最近更新的polybar i3和pulseaudio模块没了，aur安装正常

**Comment by a-wing** [comment]
@y6yuan Please see https://github.com/archlinuxcn/repo/issues/1224
