### ISSUE TITLE
rr-git 包含了 /usr/lib64

### ISSUE THREAD

**Issue by yejingchen** [archlinuxcn/repo#817]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* rr-git

----

rr-git-5.2.0.r33.g34d5bd23-1-x86_64 包含了 /usr/lib64 这一目录，在 Arch 里 /usr/lib64 应当是到 lib 的软链接，猜测是 cmake 未针对 Arch 设置。

```
(8/8) 正在检查文件冲突             [########################################] 100%
错误：无法提交处理 (有冲突的文件)
rr-git: 文件系统中存在 /usr/lib64 （由 filesystem 所有）
rr-git: 文件系统中已存在 /usr/lib64/rr/librrpreload.so 
rr-git: 文件系统中已存在 /usr/lib64/rr/librrpreload_32.so 
发生错误，没有软件包被更新。
```
检查了一下发现是 CMakeLists.txt:440 处的 `GNUInstallDirs` 导致的：
```
if(UNIX)
  include(GNUInstallDirs)
else()
  set(CMAKE_INSTALL_LIBDIR "lib")
  set(CMAKE_INSTALL_BINDIR "bin")
（省略）
```
经过试验，在 build() 里加上 `-DCMAKE_INSTALL_LIBDIR=lib` 可以绕过这一问题。
这一点也报给了 aur 仓库。

**Comment by yuyichao** [comment]
Ref https://github.com/mozilla/rr/pull/2228
