### ISSUE TITLE
gimp-git does not "conflict" with gimp, despite actual conflicts

### ISSUE THREAD

**Issue by aphirst** [archlinuxcn/repo#818]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

gimp-git

----

请在此补充说明。
Please describe in detail here.

The main executable in the `gimp-git` package is `gimp-2.99`, so it seems that it was intended (either by gimp devs, or you guys) for gimp and gimp-git to coexist. Indeed, there is no "provides" or "conflicts" set up between these two packages.

However, the `gimp-git` package contains files which are provided by `gimp`, which prevents them from being able to coexist:
```
error: failed to commit transaction (conflicting files)
gimp-git: /usr/share/applications/gimp.desktop exists in filesystem (owned by gimp)
gimp-git: /usr/share/icons/hicolor/16x16/apps/gimp.png exists in filesystem (owned by gimp)
gimp-git: /usr/share/icons/hicolor/22x22/apps/gimp.png exists in filesystem (owned by gimp)
gimp-git: /usr/share/icons/hicolor/24x24/apps/gimp.png exists in filesystem (owned by gimp)
gimp-git: /usr/share/icons/hicolor/256x256/apps/gimp.png exists in filesystem (owned by gimp)
gimp-git: /usr/share/icons/hicolor/32x32/apps/gimp.png exists in filesystem (owned by gimp)
gimp-git: /usr/share/icons/hicolor/48x48/apps/gimp.png exists in filesystem (owned by gimp)
gimp-git: /usr/share/metainfo/gimp-data-extras.metainfo.xml exists in filesystem (owned by gimp)
gimp-git: /usr/share/metainfo/org.gimp.GIMP.appdata.xml exists in filesystem (owned by gimp)
Errors occurred, no packages were upgraded.
```

**Comment by aphirst** [comment]
Additionally, the fact that `gimp-git` does not "provide" `gimp` means that packages such as e.g. `xsane-gimp` are not usable with it.

**Comment by petronny** [comment]
gimp/lilac.py就不用vcs_update了吧
直接aur_pre_build就行了

**Comment by SilverRainZ** [comment]
感觉就是加个 conflict 就好？ @heavysink

**Comment by heavysink** [comment]
Now I think this is finally solved... just wait for the most recent git.
