### ISSUE TITLE
besttrace 被给予了过高的权限

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#822]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* besttrace

----

setcap cap_net_raw=ep besttrace 就可以了，不需要 suid。

**Comment by ouyangshi** [comment]
昂  刚看到 晚上改

**Comment by ouyangshi** [comment]
aur已经更新，等待lilac自动拉取
