### ISSUE TITLE
Minikube

### ISSUE THREAD

**Issue by mahmoudhossam** [archlinuxcn/repo#823]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description
Minikube is a local kubernetes cluster written in Go.

* 主要语言和工具链 / Main Languages and Toolchains
Minikube is written in Go.

* 上游链接 / Upstream Link
https://aur.archlinux.org/packages/minikube/

* 为何需要这个软件包 / Why Need This Package
Developers using kubernetes often need to test things locally first before deploying to production, minikube is a tool that helps them achieve this.

**Comment by axionl** [comment]
> This package should use the `-bin' naming convention.

I can help to package the `minikube-bin` if you don't mind. Actually, they are the same things on the AUR Repo now.

**Comment by mahmoudhossam** [comment]
@axionl I think it would be okay since they're the basically same package.

**Comment by axionl** [comment]
@mahmoudhossam The minikube-bin is comming :smile:

_Sent from my MI 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mahmoudhossam** [comment]
@axionl Thank you!
