### ISSUE TITLE
orphaning linux-lily

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#827]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* linux-lily

----

这个包一直是跟随 Arch Linux 官方 linux 包的。由于最近 Arch Linux 官方的大量改动，造成 linux-lily 原有的工作流无法继续。考虑到本人使用 linux-lily 最多的特性仅仅是 uksm，cjktty 都很少使用（userns 也已经在官方内核中启用了，aufs 也早已被 overlay 取代），以及完成此次迁移所需要的精力，我决定放弃此包，回归官方内核。

六年时光逝去，现在早已物是人非。感谢还在支持和使用 linux-lily 的朋友，然而它要结束了。

**Comment by zodiacg** [comment]
我刚想发个issue请求rebuild（因为gcc升级dkms又挂了）

感谢仙子一直以来的维护

**Comment by lilydjwg** [comment]
我可能还得继续维护这个，因为它是和 zfs 同步的。现在我要么没 nvidia 可用，要么没 zfs 可用……

**Comment by lilydjwg** [comment]
Updated :-)
