### ISSUE TITLE
deepin.com.wechat被恶意合并了，更新不了了

### ISSUE THREAD

**Issue by Skywol** [archlinuxcn/repo#830]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages
* deepin.com.wechat

----

**Comment by zsrkmyn** [comment]
虽然我觉得其他人在没有得到你同意的情况下 merge 你的包不礼貌，但是并没有违法 [AUR 规定](https://wiki.archlinux.org/index.php/Arch_User_Repository#Other_requests)。

相反，
1. 维护 deepin-wine 不代表有让别人依赖/不依赖 deepin-wine，如果不想让别人使用，可以不提交到 AUR；
2. AUR 不鼓励有重复的包；
3. 在英文邮件列表里[用中文](https://lists.archlinux.org/pipermail/aur-requests/2018-August/025800.html)非常不礼貌；
4. 请不要 top-posting。
5. 请检查拼写和语法；

**Comment by petronny** [comment]
[简直闹剧](https://lists.archlinux.org/pipermail/aur-requests/2018-August/025800.html
)。。。
哪有往这发中文的

你完全没有向AUR的人讲清楚发生了什么事。
我帮你说几句话吧，你自己翻译一下发给AUR的人

我是最早提交deepin-wechat的人，你是提交deepin.com.wechat的人。
虽然你在我之后提交的，但是当时deepin-wechat和deepin.com.wechat是不一样的包。
deepin-wechat依赖于wine，deepin.com.wechat依赖于deepin-wine。
最近我orphan了deepin-wechat，然后被这个xtrm0接管了。
这个xtrm0修改了deepin-wechat使其依赖deepin-wine，从而使得deepin-wine和deepin.com.wechat看上去duplicate了。
然而deepin-wine的PKGBUILD中还存在有很多问题，比如有多余的wine依赖的问题。
所以至少在这个xtrm0修好之前，我是不赞同merge这两个包的。

**Comment by zsrkmyn** [comment]
:o 原来是这么复杂的关系……

**Comment by xtrm0** [comment]
Your package was still a duplicate, it was exactly the same software as the one of petronny, except the petronny version didn't depended on deepin-wine because the PKGBUILD was different. I think you shouldn't had created it in the first place,  that's why I submited the merge request. (I agree that it shouldn't had been merged so quickly, but submiting a delete request for deepin-wechat is childish).

If you want to own deepin-wechat, I can make you the maintainer

**Comment by farseerfc** [comment]
Please do **NOT** use Chinese for aur-requests https://lists.archlinux.org/pipermail/aur-requests/2018-August/025799.html
請不要在 aur-requests 使用中文。

**Comment by Renz2018** [comment]
deepin.com.wechat 这个包还有吗？ 现在搜不到了

**Comment by jhoneybee** [comment]
> 虽然我觉得其他人在没有得到你同意的情况下 merge 你的包不礼貌，但是并没有违法 [AUR 规定](https://wiki.archlinux.org/index.php/Arch_User_Repository#Other_requests)。
> 
> 相反，
> 
> 1. 维护 deepin-wine 不代表有让别人依赖/不依赖 deepin-wine 的权利，如果不想让别人使用，可以不提交到 AUR，这点并不构成你反对别人 merge 的理由；
> 2. AUR 不鼓励有重复的包；
> 3. 在英文邮件列表里[用中文](https://lists.archlinux.org/pipermail/aur-requests/2018-August/025800.html)非常不礼貌；
> 4. 请不要 top-posting；
> 5. 请检查拼写和语法。

而且我觉得在邮件里面使用中文非常不礼貌, 能否提高一下个人素养 ?
