### ISSUE TITLE
Perl5.28 rebuild 

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#831]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

----
Perl5.28 entered `[core]` repo, so we need to rebuild all the perl packages:

- [x] apparmor-libapparmor @renyuneyun 
- [x] gnome-perl
- [x] gnome-vfs-perl
- [x] gnomecanvas-perl
- [x] pcp
- [x] perl-gnome2-wnck
- [x] perl-goo-canvas
- [x] perl-gtk2-imageview
- [x] perl-gtk2-unique
- [x] perl-rpc-xml @renyuneyun 

Please click the checkbox after rebuild is done.
The above is generated using the command `sudo pacman -Fyo "/usr/lib/perl5/5.26/" | grep "archlinuxcn/" | sed 's|^.*archlinuxcn/||;s| .*$||'`

**Comment by VOID001** [comment]
gnome-perl & gnome-vfs-perl will try build again, other packages are not belong to me

**Comment by VOID001** [comment]
@renyuneyun for perl-rpc-xml apparmor-libapparmor
@lijinpei for pcp 
Just a hint

**Comment by SilverRainZ** [comment]
@renyuneyun 剩下你的两个包了。

**Comment by renyuneyun** [comment]
天吶……我居然沒看郵件……下午去做

**Comment by renyuneyun** [comment]
Done.
Shall I close the issue?
