### ISSUE TITLE
Python3.7 rebuild

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#832]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

----

Python3.7 has entered `[extra]` repo. We need to rebuild all packages that were build by python3.6.
Here is a list of packages by the command `sudo pacman -Fyo "/usr/lib/python3.6/" | grep "archlinuxcn/" | sed 's|^.*archlinuxcn/||;s| .*$||'`:

- [x] 3to2
- [x] apparmor-libapparmor @renyuneyun 
- [x] apparmor-utils @renyuneyun
- [x] blockify
- [x] kwplayer
- [ ] leo @farseerfc
- [x] libunity
- [x] netease-musicbox
- [x] netease-musicbox-git
- [x] pcp
- [x] ptpython
- [x] python-cli_helpers
- [x] python-fakeredis
- [x] python-lhafile
- [x] python-libclang @petronny 
- [x] python-pgspecial
- [x] python-plotly
- [x] python-pushbullet.py
- [x] python-pymysql
- [x] python-telethon
- [x] remarkable
- [x] solaar-git
- [x] suplemon
- [x] virtualbox-sdk-svn

Please click the checkbox after rebuild is done.

**Comment by Universebenzene** [comment]
How about vim-youcompleteme-git?

**Comment by Sasasu** [comment]
#828 python-sonnet-cuda-git python-sonnet-git 正在 orphaning

**Comment by petronny** [comment]
python-tabulate 进[community]了

**Comment by petronny** [comment]
建议rebuild后一段时间再检测一次
有的包PKGBUILD里写死3.6了
这些需要到AUR反馈

**Comment by PeterCxy** [comment]
@heavysink Maybe the `pkgrel` of `solaar-git` should also be manually bumped to force rebuild since the upstream repository does not seem to be updating very actively?

**Comment by bennyyip** [comment]
`python-tabulate` 移除了，因为现在在 [community]：https://github.com/archlinuxcn/repo/commit/3c38839fc172e3b34a1bb55834f2d100e5f11516
`cppman-git` bump了`pkgrel`：https://github.com/archlinuxcn/repo/commit/d9ae2f2eb2a8712306425259280457e3accb703b

**Comment by petronny** [comment]
重新用 @farseerfc 的命令更新了列表

**Comment by axionl** [comment]
`netease-musicbox` 已经更新，其依赖 python-requests-cache 已经 patch 掉了，同时弃置源内的包
`netease-musicbox-git` 暂时不打算更新，因为保留了 python2 版本的依赖和包，个人建议还是放弃 python2 版本的比较方便

**Comment by lilydjwg** [comment]
这个还剩下好些包呢。

**Comment by axionl** [comment]
没注意到的话可以 Assignees  一下？

**Comment by yan12125** [comment]
Link到libpython3.6m.so的也需要rebuild，例如#868：
```
$ readelf -d /usr/lib/albert/plugins/libpython.so | grep python3
 0x0000000000000001 (NEEDED)             共享函式庫：[libpython3.6m.so.1.0]
```
這種感覺很難在不安裝的情況下檢測出來？

**Comment by lilydjwg** [comment]
只解包不安装也可以。只是挺费事的，另外有些包可能会自带这些 so。

**Comment by yan12125** [comment]
的確，光跑一次花的時間可能就不少。不知Arch Linux官方怎麼整理Python升即時需要rebuild的包。

> 另外有些包可能会自带这些 so。

我倒沒想到這點。不過這應該是比較少見的false positive。

**Comment by Sasasu** [comment]
我的锅, 这个我还在用. 只不过我最近没arch开机 (捂脸

**Comment by lilydjwg** [comment]
我把仓库里的包全部检查了一遍，还有以下两个包链接到了 libpython3.6m。

* srain
* apparmor-libapparmor

**Comment by SilverRainZ** [comment]
诶 srain 没有 rebuild 成功么。

**Comment by lilydjwg** [comment]
> 有script可以分享下嗎？

在这里： https://github.com/archlinuxcn/misc_scripts

**Comment by lilydjwg** [comment]
> 诶 srain 没有 rebuild 成功么。

```
>>> pacman -Si srain
...
打包者         : lilac (on behalf of Shengyu Zhang) <i@srain.im>
编译日期       : 2018年03月01日 星期四 18时09分47秒
```

**Comment by yan12125** [comment]
> 在这里： https://github.com/archlinuxcn/misc_scripts

who_depends_this_lib嘛？有空來研究下

**Comment by SilverRainZ** [comment]
@renyuneyun 这边也顺便解决了？

**Comment by farseerfc** [comment]
抱歉 leo 我在等上游解決這個 https://github.com/leo-editor/leo-editor/issues/968 和 5.8 的 final release ，大概快出來了

**Comment by SilverRainZ** [comment]
@farseerfc 5.8 发了：https://github.com/leo-editor/leo-editor/releases/tag/5.8

然而这个issue 依然没有解决的样子？
