### ISSUE TITLE
建议修改 electronic-wechat 的上游为新的 fork

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#836]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* electronic-wechat
----

原作者已经一年未更新，建议考虑更换为这个 [fork](https://github.com/kooritea/electronic-wechat).

**Comment by hubutui** [comment]
这里有写好的一个 [PKGBUILD](https://gist.github.com/BruceZhang1993/62a6c8fa8c93735d5a755e517fdde655)．

**Comment by xgdgsc** [comment]
https://aur.archlinux.org/packages/electronic-wechat-bin/ 可以先用这个，我在aur上提醒  https://aur.archlinux.org/packages/electronic-wechat/ @cuihaoleo 没反应

**Comment by hubutui** [comment]
@updater1234 Arch Linux 也是可以用的啊．当然，如果有其他 fork 可用也行啊．原 repo 已经不再更新了嘛．

**Comment by updater1234** [comment]
哦，这样子啊

**Comment by cuihaoleo** [comment]
@hubutui @xgdgsc 谁去收了这个包吧，AUR 上 orphan 了。不懂 npm 依赖，不会改 PKGBUILD…… 现在也没有 Linux 环境可用。
archlinuxcn repo 这边应该不用改，AUR 上改好了这边就更新了。
