### ISSUE TITLE
monero

### ISSUE THREAD

**Issue by Equim-chan** [archlinuxcn/repo#841]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Monero: the secure, private, untraceable currency - release version (includes daemon, wallet and miner)

* 主要语言和工具链 / Main Languages and Toolchains

C++, CMake

* 上游链接 / Upstream Link

  * AUR: https://aur.archlinux.org/packages/monero/
  * 上游仓库: https://github.com/monero-project/monero

* 为何需要这个软件包 / Why Need This Package

AUR 那边票数和人气都可以，打包者也是上游作者之一。Debian 那边也正在收录到源中。

**Comment by VOID001** [comment]
monero is in repo now
