### ISSUE TITLE
Palemoon (II)

### ISSUE THREAD

**Issue by antifa-ev** [archlinuxcn/repo#842]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Open source web browser based on Firefox focusing on efficiency.

* 主要语言和工具链 / Main Languages and Toolchains

cpp

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/palemoon/
https://www.palemoon.org/

* 为何需要这个软件包 / Why Need This Package

Build Process is too long.

**Comment by heavysink** [comment]
好了

**Comment by uswoods** [comment]
@heavysink Why have you closed and not fixed this?

**Comment by heavysink** [comment]
59ad8f9
