### ISSUE TITLE
firefox-nightly-*消失了

### ISSUE THREAD

**Issue by Kurobac** [archlinuxcn/repo#844]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* firefox-nightly-zh-cn
* firefox-nightly-en-us
* firefox-nightly-ja
* firefox-nightly-zh-tw
----

请在此补充说明。
repo中软件包还是在的，但archlinuxcn.db里面没有这几个包的信息……

**Comment by a-wing** [comment]
现在已经有了，临时消失了一下下 `_(:3」∠)_`

https://build.archlinuxcn.org/packages/#/firefox-nightly
> 引用：
> [TINYLILY] cn 源的数据库好久没更新了呢，你们都没有发现么

PS：
 lilac 怎么没解析？

**Comment by lilydjwg** [comment]
是昨晚 archrepo2 修复之后还在赶工的中间状态吧。

lilac 没有找到这几个包……（因为仓库里的目录名是 firefox-nightly。）
