### ISSUE TITLE
Package request ( pulseeffects )

### ISSUE THREAD

**Issue by BruceZhang1993** [archlinuxcn/repo#845]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Limiter, compressor, reverberation, equalizer and auto volume effects for Pulseaudio applications  

限幅器，压缩器，混响，均衡器和自动音量效果 （简单来说：软件音效  

* 主要语言和工具链 / Main Languages and Toolchains

C++,Meson GTK

* 上游链接 / Upstream Link

https://github.com/wwmm/pulseeffects
https://aur.archlinux.org/packages/pulseeffects/

* 为何需要这个软件包 / Why Need This Package

功能实现比较完整的 pulseaudio 软件音效，可以对单个应用或全部应用调节音效（~~没钱买好音箱~~

**Comment by a-wing** [comment]
过几天包就出来了
> optdepends 可能会出问题。。我可能又接了个大锅）。
