### ISSUE TITLE
[投票] 关于 caddy 的插件

### ISSUE THREAD

**Issue by axionl** [archlinuxcn/repo#846]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* caddy
* caddy-full

----
是否能够为其选出一些能用和常用的插件将二者合并，如果开启全部插件的话有部分插件疏于维护可能会导致打包错误或者下载失败，再而下载的体积和打包的体积也比较大。当然如果有更好的拆分方法，欢迎提交。

**如有需求请在本页回复，checkbox 已有内容无需重复提交，有人正在使用的插件会尽力加入和维护**

- [x] dns
- [ ] docker
- [ ] dyndns
- [ ] hook.service
- [ ] http.authz
- [ ] http.awses
- [ ] http.awslambda
- [x] http.cache
- [ ] http.cgi
- [x] http.cors
- [ ] http.datadog
- [ ] http.expires
- [x] http.filebrowser
- [ ] http.filter
- [ ] http.forwardproxy
- [x] http.geoip
- [ ] http.git
- [ ] http.gopkg
- [ ] http.grpc
- [ ] http.hugo
- [ ] http.ipfilter
- [ ] http.jekyll
- [ ] http.jwt
- [ ] http.locale
- [ ] http.login
- [ ] http.mailout
- [ ] http.minify
- [ ] http.nobots
- [ ] http.prometheus
- [ ] http.proxyprotocol
- [ ] http.ratelimit
- [ ] http.realip
- [ ] http.reauth
- [ ] http.restic
- [ ] http.upload
- [x] http.webdav
- [ ] net
- [ ] tls.dns.auroradns
- [ ] tls.dns.azure
- [x] tls.dns.cloudflare
- [ ] tls.dns.cloudxns
- [ ] tls.dns.digitalocean
- [ ] tls.dns.dnsimple
- [ ] tls.dns.dnsmadeeasy
- [ ] tls.dns.dnspod
- [ ] tls.dns.dyn
- [ ] tls.dns.exoscale
- [ ] tls.dns.gandi
- [ ] tls.dns.gandiv5
- [ ] tls.dns.godaddy
- [ ] tls.dns.googlecloud
- [ ] tls.dns.lightsail
- [ ] tls.dns.linode
- [ ] tls.dns.namecheap
- [ ] tls.dns.ns1
- [ ] tls.dns.otc
- [ ] tls.dns.ovh
- [ ] tls.dns.powerdns
- [ ] tls.dns.rackspace
- [ ] tls.dns.rfc2136
- [ ] tls.dns.route53
- [ ] tls.dns.vultr

**Comment by Sherlock-Holo** [comment]
请求打开http.webdav插件

**Comment by axionl** [comment]
> 请求打开http.webdav插件

https://github.com/archlinuxcn/repo/commit/3e69f2def8920fab7abd84056faf713f339eab60

**Comment by xiayesuifeng** [comment]
加上http.filemanager？

**Comment by axionl** [comment]
> 加上http.filemanager？

filemanager 的話之前開發者已經獨立出來了，並且改名叫做 filebrowser ，所以 caddy 那個很可能沒更新。filebrowser 的話，AUR 上面的 filebrowser-bin 都是我維護的，也可以下載使用

**Comment by Sherlock-Holo** [comment]
加上 cors 插件支持如何

**Comment by axionl** [comment]
> 加上 cors 插件支持如何

https://github.com/archlinuxcn/repo/commit/82a65706695c1a66fd3c7bc15facf6b41392e0e6

**Comment by kmahyyg** [comment]
- http.forwardproxy
- http.nobots

**Comment by axionl** [comment]
>     * http.forwardproxy
> 
>     * http.nobots

https://github.com/archlinuxcn/repo/commit/da13b11d2aaac5fb7ad2919f0295663a3b8414e4

**Comment by Sherlock-Holo** [comment]
```
caddy -plugins
Server types:
  http

Caddyfile loaders:
  short
  flag
  default

Other plugins:
  http.basicauth
  http.bind
  http.browse
  http.errors
  http.expvar
  http.ext
  http.fastcgi
  http.gzip
  http.header
  http.index
  http.internal
  http.limits
  http.log
  http.markdown
  http.mime
  http.pprof
  http.proxy
  http.push
  http.redir
  http.request_id
  http.rewrite
  http.root
  http.status
  http.templates
  http.timeouts
  http.websocket
  on
  tls
  tls.cluster.file
```

由此可见编译后的版本是没有打开 cache 和 webdav 支持，自己测试过这两个插件是可以正常开启，也是使用同样的 PKGBUILD，区别仅在于插件打开的不同
```
caddy -plugins
Server types:
  http

Caddyfile loaders:
  short
  flag
  default

Other plugins:
  http.basicauth
  http.bind
  http.browse
  http.cache
  http.errors
  http.expvar
  http.ext
  http.fastcgi
  http.gzip
  http.header
  http.index
  http.internal
  http.limits
  http.log
  http.markdown
  http.mime
  http.pprof
  http.proxy
  http.push
  http.realip
  http.redir
  http.request_id
  http.rewrite
  http.root
  http.status
  http.templates
  http.timeouts
  http.upload
  http.webdav
  http.websocket
  on
  tls
  tls.cluster.file
```
所以是否是在编译机打包时出现了问题？

**Comment by yan12125** [comment]
caddy is dropped in https://github.com/archlinuxcn/repo/commit/6ba42c044b8074f6ed37e83efcd7e7a9b9bf8ca7. I think this issue can be closed.
