### ISSUE TITLE
nixnote2 包过期

### ISSUE THREAD

**Issue by kitech** [archlinuxcn/repo#852]
### 问题类型 / Type of issues
过期软件包
* 过期软件包 / out-of-date packages
nixnote2
### 受影响的软件包 / Affected packages
nixnote2
* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
nixnote2
----

nixnote2 repo 有一个更活跃的fork，他们发布了 v2.1: https://github.com/baumgarr/nixnote2/issues/456
也许可以考虑更新到这个fork。

**Comment by a-wing** [comment]
这个一直在关注。。。要不等他发布个稳定版再换 ？

**Comment by kitech** [comment]
原来是个beta。。。可以等

**Comment by a-wing** [comment]
Oh, Great

cc @ykelvis

**Comment by cnwangjie** [comment]
It still cannot work well for me. Have you tried it?

**Comment by robert7** [comment]
@cnwangjie I'm using it daily for few months... so of course I have tried it :) ... but I will reply to your ticket https://github.com/robert7/nixnote2/issues/55 and we may try to find out what wrong for you...

**Comment by cnwangjie** [comment]
Tried to build with aur, it is now ready for use. :+1:

**Comment by a-wing** [comment]
`archlinuxcn/nixnote2 2.1.0-1`
