### ISSUE TITLE
emacs-git should not replace emacs

### ISSUE THREAD

**Issue by yuyichao** [archlinuxcn/repo#853]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* emacs-git

----

请在此补充说明。
Please describe in detail here.

See title.

**Comment by SilverRainZ** [comment]
@ykelvis 这个 issue 现在是啥情况？

**Comment by ykelvis** [comment]
我觉得 -git 版本就应该 conflict/replace 稳定版的吧

**Comment by yuyichao** [comment]
应该 conflict 而不 replace

**Comment by yuyichao** [comment]
> [replaces](https://wiki.archlinux.org/index.php/PKGBUILD#replaces)
> An array of obsolete packages that are replaced by the package

`emacs` 并没有被废弃.

`conflicts` 的意思是两个包只能装一个, `replaces` 的意思是所有用旧包的人都得换成这个包.

**Comment by ykelvis** [comment]
06b581d96e0da8a64 lilac更新好了
