### ISSUE TITLE
pgcli 打包失败

### ISSUE THREAD

**Issue by Sasasu** [archlinuxcn/repo#857]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* pgcli

----
pgcli 编译失败  [log](https://build.archlinuxcn.org/packages/#/pgcli) [aur](https://aur.archlinux.org/packages/pgcli) 

依赖 cn 源两个包 `build_prefix = 'archlinuxcn-x86_64'` 就可以了.
同时 lilac.py 似乎没加 x

要是 @qwIvan 比较忙的话我可以接手 = =

**Comment by petronny** [comment]
depends也加一下？

**Comment by Sasasu** [comment]
编译机上直接 `archlinuxcn-x86_64-build` 就可以了, 应该不用加依赖吧 = =

**Comment by lilydjwg** [comment]
`archlinuxcn-x86_64-build` 有延迟。在同一批次的打包中依赖也不会被排序到此包之前。

**Comment by qwIvan** [comment]
https://github.com/archlinuxcn/repo/blob/6e772434fba69afcbb26c96cbd0f710608d7e00b/pgcli/lilac.py#L9
已改
