### ISSUE TITLE
Take over android-ndk

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#859]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* android-ndk
----
     
I'm the maintainer of the [android-ndk](https://aur.archlinux.org/packages/android-ndk) package on AUR. I'd like to take over the corresponding package in [archlinuxcn] for easier maintenance (e.g., configure lilac to update the AUR repo automatically).

**Comment by lilydjwg** [comment]
你拿去吧。
这个包最初是 @felixonmars 提交的，后来 @farseerfc 维护了一段时间，然后有两个你的提交。不知道为什么会在我的名下……

**Comment by yan12125** [comment]
Done :)
