### ISSUE TITLE
pandoc-static requires icu<55

### ISSUE THREAD

**Issue by Hexcles** [archlinuxcn/repo#86]
And icu has been updated to 55.1-1 now.

**Comment by colinkeenan** [comment]
I tried to update the PKGBUILD myself. I also removed pandoc-static from my
system so I could upgrade icu to 55.1-1. Then I tried to makepg, but the
build fails. I don't understand this package well enough to fix it, so will
need to wait for the AUR maintainer of pandoc-static to update the PKGBUILD.

**Comment by colinkeenan** [comment]
Updated.
