### ISSUE TITLE
electronic-wechat 应该加上依赖 electron 吧？

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#861]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* electronic-wechat

----

直接安装的 electronic-wechat，发现无法运行，从终端启动才发现是缺了 electron．
see https://github.com/archlinuxcn/repo/blob/master/electronic-wechat/PKGBUILD#L12

**Comment by axionl** [comment]
不是有吗？

**Comment by xgdgsc** [comment]
直接去aur comment一下就行吧
