### ISSUE TITLE
wps-office是不是应该加上依赖xorg-mkfontscale

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#862]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* wps-office

----

安装后的脚本里执行了 `mkfontscale`，这个命令由 `xorg-mkfontscale` 提供，后面还有一个 `mkfontdir`，由 `xorg-mkfontdir` 提供．

**Comment by petronny** [comment]
和 #338 重复
请去AUR反馈给 @Universebenzene

**Comment by Universebenzene** [comment]
看来是我没配置打包环境的锅所以不知道需要这个依赖……
多谢提醒
真不应该接这个包的锅T_T

**Comment by petronny** [comment]
根据 #338 
好像是要从*.install中把和fontconfig xorg-mkfontdir相关的都去掉
同时保持对fontconfig/xorg-mkfontdir的依赖

**Comment by Universebenzene** [comment]
@petronny 好像理解了，只要把.install里那两行给去掉就行，依赖里有fontconfig就没事

**Comment by petronny** [comment]
建议你最后chroot打包测一下。同时把安装包做个对比，然后装上试试看正不正常。。。

我这一直没有带GUI的arch所以一直没法修。。。

**Comment by Universebenzene** [comment]
……有点麻烦……我试试好了
