### ISSUE TITLE
xonsh is in [community]

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#867]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* xonsh
* pulseeffects

----

最近TU們挺勤快，搬了好多包進[community]。或許是該來寫個腳本每天檢查是否有包進官方源了？

我目前是用這個指令檢查：

```
$ pacman -Slq core extra community multilib archlinuxcn | sort | uniq -c | grep -v ' 1 '
      2 dbus-broker
      2 pulseeffects
      2 python-svgwrite
      2 xonsh
```

(dbus-broker已於 https://github.com/archlinuxcn/repo/issues/860 回報)

**Comment by yan12125** [comment]
Let me reuse this existing issue instead of opening a new one - I don't want to flood the archlinuxcn tracker with such issues!

@lilydjwg: [python-svgwrite is in [community]](https://www.archlinux.org/packages/community/any/python-svgwrite/)

**Comment by lilydjwg** [comment]
[python-svgwrite removed](b8c8e714584c0fb5a8ff0882307d4e308000f2d9).

**Comment by qwIvan** [comment]
[xonsh removed](https://github.com/archlinuxcn/repo/commit/db3e98f52dc9033102c7366bb3225a35711a7273).
