### ISSUE TITLE
Boost 1.69 rebuilds

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#871]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

- [ ] anbox-git
- [x] blender-2.8-git
- [x] fcitx5-chinese-addons-git
- [x] freecad-oce
- [x] monero
- [x] nheko-git
- [x] pcl
- [x] rstudio-desktop-git
- [ ] supertux-git @colinkeenan 
- [x] trojan-git

(generated by @lilydjwg's script at https://github.com/archlinuxcn/misc_scripts/blob/master/who_depends_this_lib)

----

Boost 1.68 is now in [testing]. Many packages should be rebuild once it enters [extra]. You can try to rebuild your own packages with `testing-x86_64-build` first to see if there's incompatibility with boost 1.68.

Boost 1.68進[testing]了。進[extra]後會需要重打好多包，大家可以先用testing-x86_64-build測測自己的包和boost 1.68是否相容。

**Comment by lilydjwg** [comment]
我的脚本有误，刚重新跑了一下，已更新。

**Comment by axionl** [comment]
* [x] trojan-git
* [x] nheko-git

**Comment by petronny** [comment]
把1L的list改成了checkbox...

**Comment by swordfeng** [comment]
https://github.com/archlinuxcn/repo/blame/master/nvchecker.ini#L1792
Not my package lol @VOID001

**Comment by axionl** [comment]
@SilverRainZ @ 了我还以为已经出了:joy: 到时候我再加个版本号好了，反正 -git

**Comment by yan12125** [comment]
Sorry for the confusion. Maybe I shouldn't post this before boost actually enters [extra].

**Comment by lilydjwg** [comment]
有没有兴趣利用这个来测试 lilac 的新特性？在 lilac.py 中使用 `update_on`，即可在 boost 库更新时自动触发自动打包（注意更新 pkgrel，有个 `update_pkgver_and_pkgrel` 函数可以很方便地搞定）。

例子：

```python
update_on = [{
  'github': 'mujx/nheko',
}, {
  'archpkg': 'boost-libs',
  'from_pattern': r'^(\d+\.\d+)\..*',
  'to_pattern': r'\1',
}]
```

[文档](https://github.com/archlinuxcn/lilac/blob/master/docs/lilac-py-fields.md)。

**Comment by yan12125** [comment]
Now we can move on!

https://git.archlinux.org/svntogit/packages.git/commit/?h=packages/boost&id=e7f37b05eb10e0d266c0ef5c64803bcb2c5facee

> db-move: moved boost from [testing] to [extra] (x86_64)

**Comment by kaseiwang** [comment]
PCL need a patch to upgrade to boost 1.68. I will submit the patch to AUR maintainer.

**Comment by VOID001** [comment]
monero repackaged done, but not tested yet

**Comment by yan12125** [comment]
How about upload the new monero package to [archlinuxcn] to let monero users test it?

**Comment by yan12125** [comment]
For unknown reasons, the anbox-git rebuild at 2018-09-22T02:01:01 still pulls boost 1.67, and thus version 1:r1028.c8a760c-2 still links to the old boost:
```
$ anbox
anbox: error while loading shared libraries: libboost_log.so.1.67.0: cannot open shared object file: No such file or directory
```
@heavysink

**Comment by SilverRainZ** [comment]
@colinkeenan Don't forget your supertux-git ;-)

**Comment by lsblk** [comment]
似乎amule-dlp-git需要rebuild，
![2018-11-12 21-35-36](https://user-images.githubusercontent.com/11588373/48350679-eb44d200-e6c2-11e8-8d69-43a9eba4851d.png)

**Comment by yan12125** [comment]
@yk seems this package is maintained by you. Could you have a look?

**Comment by yk** [comment]
> @yk seems this package is maintained by you. Could you have a look?

I'm flattered, but I think you've mixed me up :)

**Comment by yan12125** [comment]
Oops, sorry! I should mention @ykelvis instead.

**Comment by yan12125** [comment]
Boost 1.69 enters [extra]!

**Comment by yan12125** [comment]
是的～可以參考我的neovim-youcompleteme-core-git。VCS包記得要在vcs_update()前面加update_pkgrel()，這樣rebuild的包pkgrel才會是新的。

**Comment by yan12125** [comment]
補充說明一下VCS包裡update_pkgrel()和vcs_update()的先後順序關係。如果pre_build這樣寫：
```
def pre_build():
    vcs_update()
    update_pkgrel()
```
那麼無論是git上游更新或是rebuild，pkgrel都會是至少2以上。而如果這樣寫：
```
def pre_build():
    update_pkgrel()
    vcs_update()
```
如果git上游更新，那麼vcs_update在更新pkgver的同時會讓pkgrel回到1，而rebuild的時候如果上游沒更新，那update_pkgrel()增加的pkgrel就會保留。

實用上兩種寫法都不會出錯，只是VCS包的pkgrel從2起跳有點怪。
