### ISSUE TITLE
Apparmor is in community

### ISSUE THREAD

**Issue by renyuneyun** [archlinuxcn/repo#875]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* apparmor
* apparmor-libapparmor
* apparmor-pam
* apparmor-parser
* apparmor-profiles
* apparmor-utils
* apparmor-vim

----

**Comment by SilverRainZ** [comment]
貌似第一次的时候格式没填对 lilac 就不会再次解析了。感觉需要 @renyuneyun 手动删下包？

**Comment by renyuneyun** [comment]
已手動解決，應該不需要其他動作了。

所以說正確的格式是什麼？ @SilverRainZ

**Comment by SilverRainZ** [comment]
现在的格式就是对的吧，只是现在要求「第一次就写对」？

**Comment by lilydjwg** [comment]
这种包没什么问题的话直接删掉就好了。

lilac 目前打标签和指派任务时不会重新解析。对于 orphaning 标签会在到期的时候解析。

**Comment by renyuneyun** [comment]
@SilverRainZ 然而第一次就是對的啊。。。

無所謂了，反正手動刪掉就好了，也算不上麻煩
