### ISSUE TITLE
try to overwrite libidn .so file

### ISSUE THREAD

**Issue by yuhaim** [archlinuxcn/repo#876]
### 问题类型 / Type of issues
* 打包错误 / packaging error

### 受影响的软件包 / Affected packages
*fcitx-sogoupinyin-2.2.0.0108-5

### Conflict With libidn
$ sudo pacman -S fcitx-sogoupinyin
resolving dependencies...
looking for conflicting packages...

Packages (4) opencc-1.0.5-1  qtwebkit-2.3.4-7  xorg-xprop-1.2.3-1
             fcitx-sogoupinyin-2.2.0.0108-5

Total Download Size:   31.61 MiB
Total Installed Size:  97.00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 xorg-xprop-1.2.3-1-...    25.2 KiB   838K/s 00:00 [######################] 100%
 opencc-1.0.5-1-x86_64   1184.5 KiB  3.73M/s 00:00 [######################] 100%
 qtwebkit-2.3.4-7-x86_64    8.7 MiB  3.91M/s 00:02 [######################] 100%
 fcitx-sogoupinyin-2...    21.7 MiB  6.27M/s 00:03 [######################] 100%
(4/4) checking keys in keyring                     [######################] 100%
(4/4) checking package integrity                   [######################] 100%
(4/4) loading package files                        [######################] 100%
(4/4) checking for file conflicts                  [######################] 100%
error: failed to commit transaction (conflicting files)
fcitx-sogoupinyin: /usr/lib/libidn.so.11 exists in filesystem (owned by libidn)
Errors occurred, no packages were upgraded.

**Comment by cuihaoleo** [comment]
Try update your system first:

```$ pacman -Ql libidn | grep libidn.so
libidn /usr/lib/libidn.so
libidn /usr/lib/libidn.so.12
libidn /usr/lib/libidn.so.12.6.0```

**Comment by yuhaim** [comment]
Perhaps manjaro did not update so fast, actually I encountered this after recent updates.
Would it be possible to package the sogou-im to use libidn as it is in the system, i.e. do not require certain version libidn.

**Comment by cuihaoleo** [comment]
符号链接的方法的确不太好，不过你得给 AUR 维护者反映：
https://aur.archlinux.org/packages/fcitx-sogoupinyin/

这里只是原样打包，并且优先考虑 Arch Linux……
