### ISSUE TITLE
ttf-iosevka-term-slab

### ISSUE THREAD

**Issue by VanLaser** [archlinuxcn/repo#879]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

（请Hi, great repository! Could you also add the AUR package `ttf-iosevka-term-slab` (Serif) ?  
You already have `ttf-iosekva-term` (Sans Serif), so it should not be too difficult.

* 主要语言和工具链 / Main Languages and Toolchains

（请`fontconfig`, `xorg-font-utils`

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/ttf-iosevka-term-slab/

* 为何需要这个软件包 / Why Need This Package

This is the **Serif** version of the TTF Iosevka font, it's a very nice font alternative to the default monospace version.

**Comment by axionl** [comment]
Added:

- `ttf-iosevka-term-slab`
- `ttf-iosevka-cc-slab`
- `ttf-iosevka-cc`
- `ttf-iosevka-type-slab`
- `ttf-iosevka-type`
- `ttf-iosevka`

Commit:

- https://github.com/archlinuxcn/repo/commit/3ae58a663527e4d3c145e4aca2b51fe73dccf3ad
- https://github.com/archlinuxcn/repo/commit/9a698aa1fc3ae8ed9ce7e700a5f2798decdab48f

**Comment by VanLaser** [comment]
Hi @axionl (and sorry to bother you again) - do I have to do something special to view the new font in the archlinuxcn repo, or the package 'ttf-iosevka-term-slab' is still missing? I can see all the other `ttf-iosevka-...  ` variants from your post above, but still no 'ttf-iosevka-term-slab'. Thanks!

**Comment by axionl** [comment]
> Hi @axionl (and sorry to bother you again) - do I have to do something special to view the new font in the archlinuxcn repo, or the package 'ttf-iosevka-term-slab' is still missing? I can see all the other `ttf-iosevka-...` variants from your post above, but still no 'ttf-iosevka-term-slab'. Thanks!

Sorry, I forgot the `lilac.py`.

https://github.com/archlinuxcn/repo/commit/753bdbaebe6126007e7a82d55a90983895711a65
