### ISSUE TITLE
Package request for pandoc-bin, pandoc-citeproc-bin and pandoc-crossref-bin

### ISSUE THREAD

**Issue by problem233** [archlinuxcn/repo#881]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

打包 Pandoc 及其两个官方 filter 的二进制包。

* 主要语言和工具链 / Main Languages and Toolchains

不需要工具链，直接从上游下载二进制包。

* 上游链接 / Upstream Link

Github：
- [pandoc](https://github.com/jgm/pandoc)
- [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc-bin)
- [pandoc-crossref](https://github.com/jgm/pandoc-crossref-bin)

AUR：
- [pandoc-bin](https://aur.archlinux.org/packages/pandoc-bin)
- [pandoc-citeproc-bin](https://aur.archlinux.org/packages/pandoc-citeproc-bin)
- [pandoc-crossref-bin](https://aur.archlinux.org/packages/pandoc-crossref-bin)

* 为何需要这个软件包 / Why Need This Package

Pandoc 是一个常用的文档格式转换器，官方仓库里的包依赖一堆 Haskell 库，对于不用的人来说是累赘；aur 上的 PKGBUILD 需要从 Github 下载，国内下载比较困难。

**Comment by lilydjwg** [comment]
咦我记得以前有 pandoc-static 的，现在没了。
