### ISSUE TITLE
Package request for stack-bin

### ISSUE THREAD

**Issue by problem233** [archlinuxcn/repo#882]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

打包 AUR 上的 stack-bin。

* 主要语言和工具链 / Main Languages and Toolchains

不需要工具链，直接从上游下载二进制包。

* 上游链接 / Upstream Link

Github：[stack](https://github.com/commercialhaskell/stack)
AUR：[stack-bin](https://aur.archlinux.org/packages/stack-bin)

* 为何需要这个软件包 / Why Need This Package

Stack 是现在常用的 Haskell 开发工具，官方仓库里的包依赖一堆 Haskell 库，对于只用 Stack 管理 Haskell 环境的用户来说过于累赘；AUR 上的 PKGBUILD 需要从 Github 下载，国内下载比较困难。

**Comment by problem233** [comment]
最大的问题就是依赖太多了啊……

**Comment by TobiichiAmane** [comment]
commit d9cccf0618f0f8306f5879aea8ce17ffded3dfb9。请等待丁香自动打包完成，这通常需要不超过8小时。

**Comment by TobiichiAmane** [comment]
打包完成。
