### ISSUE TITLE
gnome-shell 增加 epoch 导致 gnome-shell-extension-dash-to-dock-git 依赖无法满足

### ISSUE THREAD

**Issue by magicshield** [archlinuxcn/repo#885]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* gnome-shell-extension-dash-to-dock-git

----

gnome-shell-extension-dash-to-dock-git 指定了依赖的 gnome-shell 版本小于 3.31。
但现在 gnome-shell 的版本变成了1:3.30.1-1。
实际上 gnome-shell 可以忽略扩展里面的 gnome-shell 版本要求强制加载，是否还有必要指定扩展依赖特定版本的 gnome-shell ？

**Comment by swordfeng** [comment]
这……是对epoch的判断逻辑有问题？ 3.30 < 3.31 这没有问题啊

**Comment by magicshield** [comment]
错误：无法准备事务处理 (无法满足依赖关系)
:: 安装 gnome-shell (1:3.30.1-1) 破坏依赖 'gnome-shell<3.31' （gnome-shell-extension-dash-to-dock-git 需要）
pacman 抱怨破坏依赖了。

**Comment by swordfeng** [comment]
嗯，跟 AUR 维护者说了。暂时可以用 -Sdd 顶着，如果 AUR 上没有更改的话我再加个 patch 。

**Comment by swordfeng** [comment]
patch 了，我自己测试没有问题了
