### ISSUE TITLE
请求增加 / Package Request: nautilus-typeahead

### ISSUE THREAD

**Issue by bryango** [archlinuxcn/repo#886]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

恢复 / patch 文件管理器 Nautilus 的输入选取（typeahead）功能；曾经非常好用，可惜在新版 Nautilus 中被广为诟病的搜索功能替代，故有此 AUR. 每次升级都要自己重新编译，希望能加入 archlinuxcn repo. 

* 主要语言和工具链 / Main Languages and Toolchains

不懂 / No idea... 参见：https://aur.archlinux.org/packages/nautilus-typeahead/

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/nautilus-typeahead/
-> git+https://gitlab.gnome.org/GNOME/nautilus.git
-> https://aur.archlinux.org/cgit/aur.git/tree/nautilus-restore-typeahead.patch?h=nautilus-typeahead

* 为何需要这个软件包 / Why Need This Package

生活必需品...

**Comment by TobiichiAmane** [comment]
Commit d2c9938025b91a55b33572f16454a261f18fba7a。请等待紫丁香打包完成，这通常需要8小时。

**Comment by TobiichiAmane** [comment]
包已位于软件源中。请等待你所使用的镜像站同步。
