### ISSUE TITLE
Package requests for DataGrip

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [archlinuxcn/repo#888]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Smart SQL Editor and Advanced Database Client Packed Together for Optimum Productivity

* 主要语言和工具链 / Main Languages and Toolchains

Java
No toolchain needed.
* 上游链接 / Upstream Link

URL: http://www.jetbrains.com/datagrip/
AUR: [datagrip](https://aur.archlinux.org/packages/datagrip/)

* 为何需要这个软件包 / Why Need This Package

As intelliJ, pycharm & clion, I would like to use pacman + archlinuxcn to manage it.

**Comment by axionl** [comment]
https://github.com/archlinuxcn/repo/commit/631116d3d67418faa500555f75da4e1e0bbc94e5
