### ISSUE TITLE
google chrome out-of-date

### ISSUE THREAD

**Issue by wongsyrone** [archlinuxcn/repo#89]

**Comment by lilydjwg** [comment]
It should be updated tonight ;-)

**Comment by wongsyrone** [comment]
Thanks.

**Comment by xgdgsc** [comment]
@lilydjwg Why didn' t it get updated last night?

**Comment by lilydjwg** [comment]
On Fri, Apr 17, 2015 at 07:16:36PM -0700, xgdgsc wrote:
> @lilydjwg Why didn' t it get updated last night?

最近 lilac 坏掉了，正在修。本来以为已经修好了的，结果忘记更新编译机上的
代码了…………

-- 
Best regards,
lilydjwg
