### ISSUE TITLE
systemd-sysvcompat-git被列入base组

### ISSUE THREAD

**Issue by yw662** [archlinuxcn/repo#890]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* systemd-sysvcompat-git

----

这使得pacstrap /mnt base 时，systemd-sysvcompat-git被安装，而systemd-sysvcompact因为冲突而不安装

**Comment by axionl** [comment]
https://github.com/yurikoles-aur/systemd-git/commit/5ec93ff8a60a324861c11fb904474fa0e3f9ff22
 fixed here and waiting for the new packages.

**Comment by yw662** [comment]
emm………不是systemd-git, 是systemd-sysvcompact-git

**Comment by axionl** [comment]
@yw662 知道，是我之前看錯了，所以後來就刪了，大概今明兩天之內應該能好

**Comment by axionl** [comment]
Done: https://github.com/yurikoles-aur/systemd-git/commit/ff929b11a9235c6d552bdc2b3c958be8e3c4821d
