### ISSUE TITLE
Brave package is now on  0.55.20

### ISSUE THREAD

**Issue by Drose221193** [archlinuxcn/repo#894]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----

**Comment by lilydjwg** [comment]
Why can't you follow the template and fill in the replace relevant info?

**Comment by wi24rd** [comment]
原来仓库 PKGBUILD 里的 github.com/brave/browser-laptop 弃置了，新的在 https://github.com/brave/brave-browser 可能需要重新写 PKGBUILD? 
不过的确发 issue 的那位态度不端正。

**Comment by heavysink** [comment]
#949 Please try to use brave-bin instead. Brave is obsolete at AUR and it seems that no one want to update it.

**Comment by yan12125** [comment]
brave in [archlinuxcn] is deleted.
