### ISSUE TITLE
keybase-gui & keybase & kbfs in community now

### ISSUE THREAD

**Issue by BruceZhang1993** [archlinuxcn/repo#900]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* keybase-bin

----

keybase-gui & keybase & kbfs in community now, they should replace keybase-bin.

**Comment by yan12125** [comment]
The `keybase-bin` package is completely valid IMO. It offers a choice for those who trust upstream packagers more than Arch Linux packagers.

**Comment by yan12125** [comment]
Well, In My Opinion...

**Comment by BruceZhang1993** [comment]
Well, it make sense.

**Comment by yan12125** [comment]
OK. Let's keep it here until there's a bigger problem.
