### ISSUE TITLE
Package request for osu-lazer

### ISSUE THREAD

**Issue by IsoaSFlus** [archlinuxcn/repo#901]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

一款 ~~益智~~ 的音乐节奏类游戏，客户端开源。

* 主要语言和工具链 / Main Languages and Toolchains

.NET Core

* 上游链接 / Upstream Link

Source: https://github.com/ppy/osu
AUR: https://aur.archlinux.org/packages/osu-lazer/

* 为何需要这个软件包 / Why Need This Package

打音游可以锻炼身体QAQ。

**Comment by petronny** [comment]
opsu 还有人用没？

**Comment by IsoaSFlus** [comment]
你是说那个java客户端？

**Comment by zsrkmyn** [comment]
编译机上运行 dotnet build 那步会报
```
Failed to initialize CoreCLR, HRESULT: 0x8007001F
```
但是我本地编译是好的，不然我应该很早之前就加这个包了。

**Comment by TobiichiAmane** [comment]
https://github.com/dotnet/source-build/issues/285#issuecomment-399949984
按照这个上古issue，应该是我们用devtool打包的时候的那个chroot无权使用mlock的锅？

**Comment by TobiichiAmane** [comment]
已经手动打包。
