### ISSUE TITLE
Packages contains "replaces" or "groups" in official repo

### ISSUE THREAD

**Issue by farseerfc** [archlinuxcn/repo#905]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* [x] baka-mplayer-git
* [x] gdm-plymouth @SilverRainZ 
* [x] gnome-screenshot-heavy-shadow
* [x] libgdm-plymouth @SilverRainZ 
* [x] nautilus-typeahead @TobiichiAmane 
* [x] python2-pyside2
* [x] python2-pyside2
* [x] vim-fcitx @petronny 
* [x] vim-pathogen @petronny 
* [x] vim-ripgrep-git
* [x] vim-tern
* [x] vim-youcompleteme-git
* [x] xfce4-linelight-plugin
* [x] xfce4-mpc-plugin-update
* [x] xfce4-windowck-plugin
* [x] xfdesktop-devel
----

请在此补充说明。
Please describe in detail here.

完整包列表可以通過 `./pre-commit --all` 查詢。請打包者刪除上述包的 PKGBUILD 中， replaces 或 groups 包含了官方源的包或組的描述，然後在上面的列表中打勾。
今後新加包時 pre-commit 會對這類情況報錯。

相關討論參見：  archlinuxcn/lilac#84 #853 #896 #626 #228

**Comment by farseerfc** [comment]
@TobiichiAmane 可以在 lilac.py 的 pre_build 裏面修改 PKGBUILD 比如這樣 https://github.com/archlinuxcn/repo/commit/8e81562fac368c73acf53c8f6f37d67d0f4e0abe

**Comment by axionl** [comment]
> 如果上游是AUR，若原作者不愿意修改的话，是不是每次更新都需要手动修一遍啊，，
> [9266b49](https://github.com/archlinuxcn/repo/commit/9266b4948a05f93cf385481e90568eef0c625c64) 和 [929a0a3](https://github.com/archlinuxcn/repo/commit/929a0a390e1e8fad4a988f7353c59e6536913bfe)

大概可以直接从上游更新，比如 github，不过先通知一下 AUR 比较好

**Comment by TobiichiAmane** [comment]
> @TobiichiAmane 可以在 lilac.py 的 pre_build 裏面修改 PKGBUILD 比如這樣 [8e81562](https://github.com/archlinuxcn/repo/commit/8e81562fac368c73acf53c8f6f37d67d0f4e0abe)

若存在其和别的第三方包作为一个独立第三方包组的存在，这种方式就不合适了；
不过，对于nautilus-typeahead包，是可行的。

**Comment by TobiichiAmane** [comment]
aa7343e4c8f4954d7ef1131ead127c5a03c76cfd

**Comment by SilverRainZ** [comment]
不好意思拖了这么久，改了。

**Comment by farseerfc** [comment]
@yan12125  `PKGBUILD of package "xfwm4-devel" contains "groups = xfce4" in "extra" repo`

**Comment by yan12125** [comment]
Thanks for notifying me. The issue should have been fixed with the latest commit.
