### ISSUE TITLE
ArchCN维护者常用工具元数据包

### ISSUE THREAD

**Issue by tobiichiamane** [archlinuxcn/repo#906]
### 问题类型 / Type of issues

* 软件打包请求 / package request

archcn-tools-meta

----

* 简述 / Brief Description

考虑建立一个软件包，包含ArchCN维护者常用的工具。

* 主要语言和工具链 / Main Languages and Toolchains

未构建

* 上游链接 / Upstream Link

无

* 为何需要这个软件包 / Why Need This Package

帮助新维护者迅速上手 && 方便某些工具的依赖确定

**Comment by TobiichiAmane** [comment]
统计一下我们经常用到哪些包？
官方源：openssh, devtools
CN源：devtools-cn-git, lilacinfo（厚颜无耻）, precommit（或pre-commit）

**Comment by lilydjwg** [comment]
我本地不用 devtools* 的耶。

**Comment by TobiichiAmane** [comment]
> 我本地不用 devtools* 的耶。

嘛，，，感觉一般都会有的来着（
总是要现在本地试试的

**Comment by farseerfc** [comment]
pre-commit 在 repo 裏面不需要單獨裝，不過 pre-commit 有兩個依賴 python-yaml 和 python-jsonschema ，要用的話需要單獨裝。
pacman-contrib 裏面的 updpkgsums 那些可能會比較有用。

**Comment by farseerfc** [comment]
pre-commit 現在加了一項 pyalpm 的依賴。沒它的話會下載編譯機上的 dump-groups.gz ，有它的話直接用 pyalpm 讀 pacman syncdb 數據庫。

**Comment by swordfeng** [comment]
可以先把这个包加进来？之后有update就继续跟进
