### ISSUE TITLE
package request : games_nebula

### ISSUE THREAD

**Issue by LinArcX** [archlinuxcn/repo#907]
### 问题类型 / Type of issues

* 软件打包请求 / package request : games_nebula

----

* 简述 / Brief Description : Unofficial Linux client for GOG

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link : https://aur.archlinux.org/packages/games_nebula/

（请在此填写）

* 为何需要这个软件包 / Why Need This Package : because sourceforge is blocked in my country.

（请在此填写）

**Comment by TobiichiAmane** [comment]
1a3fb1285b31a81808c4238fc8b4a4365e1d5d54 dependency: htmlcxx
