### ISSUE TITLE
希望能打包monodevelop

### ISSUE THREAD

**Issue by 210hcl** [archlinuxcn/repo#908]
### 问题类型 / Type of issues
* 软件打包请求 / package request
希望能打包monodevelop
beta git stable都可以
* 简述 / Brief Description
linux下c#的默认IDE，但是一直是在aur里面，自己同步代码非常吃力。
* 主要语言和工具链 / Main Languages and Toolchains
c#和f#
* 上游链接 / Upstream Link
git://github.com/mono/monodevelop.git
* 为何需要这个软件包 / Why Need This Package
个人希望能在archlinux下开发c#或者f#编写的程序，却苦于无法使用monodevelop

**Comment by TobiichiAmane** [comment]
作为monodevelop的更强替代版，vscode已经可以完美进行C#和F#开发；但如果你对monodevelop有硬需求，我会考虑检查它的上游并，在上游没有任何问题的情况下，打包至CN源。

**Comment by 210hcl** [comment]
monodevelop可以提供快速gui设计，vscode明显没有这个功能。如果可以，还请把monodevelop打包下。
