### ISSUE TITLE
prettyping,ld-lsb,python-wand now in community repo

### ISSUE THREAD

**Issue by attenuation** [archlinuxcn/repo#911]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* prettyping

----

**Comment by farseerfc** [comment]
還有:

* [ ] ld-lsb @ykelvis 
* [ ] python-wand @lilydjwg

**Comment by TobiichiAmane** [comment]
28fc3d286107d85ceaea013ed3b6b68e3b6f1bf9 删掉了ld-lsb和prettyping

**Comment by lilydjwg** [comment]
python-wand: 599af32c745bd31d8629b24ca052d2ff2a2a8a7b
