### ISSUE TITLE
ptpython depends on aur/python-prompt_toolkit-2 and not available in repos

### ISSUE THREAD

**Issue by lizr2004** [archlinuxcn/repo#913]
### 问题类型 / Type of issues

* 打包错误 / packaging error
* 其它 / other

### 受影响的软件包 / Affected packages

* ptpython
* ptpython2

----

ptpython depend on python-prompt_toolkit-2>=2.0.6 and pacman cannot solve it!

pacman 找不到 ptpython 的依赖 python-prompt_toolkit-2>=2.0.6

应为 python-prompt_toolkit ?

**Comment by lizr2004** [comment]
python-prompt-toolkit-2 存在于 aur 中但是安装 python-prompt_toolkit-2 需要卸载 python-prompt_toolkit.
而卸载 python-prompt_toolkit 会波及 community/ipython 等包

**Comment by qwIvan** [comment]
新版 `ptpython` 依赖于 prompt_toolkit 2，而 `ipython`、`mycli`、`pgcli` 等需要依赖于 prompt_toolkit 1。AUR上的 `python-prompt_toolkit-2` 无法与 `python-prompt_toolkit` 兼容。最好的解决方式应该是让两个不同版本的 prompt_toolkit 共存。

**Comment by lizr2004** [comment]
solved!
