### ISSUE TITLE
use mendeleydesktop-bundled instead of mendeleydesktop

### ISSUE THREAD

**Issue by specter119** [archlinuxcn/repo#914]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

mendeleydesktop

### 受影响的软件包 / Affected packages

* mendeleydesktop-bundled

----

mendeleydesktop will always crash when opening a pdf file on my machine, and I use mendeleydesktop-bundled instead can fix this issue. Then, how about orphaning mendeleydesktop and adding mendeleydesktop-bundled instead?

**Comment by specter119** [comment]
@zsrkmyn 主Zotero，搭配Mendeley搜全文还行？

**Comment by lilydjwg** [comment]
@zsrkmyn 嗯。求 pr。

**Comment by heavysink** [comment]
上端aur已经改成pkgbase了，同时包含mendeleydesktop(去Qt)和mendeleydesktop-bundled(不去Qt)两个package，只是没有及时把pkgver更新。
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mendeleydesktop
