### ISSUE TITLE
Package request(nyx)

### ISSUE THREAD

**Issue by LinArcX** [archlinuxcn/repo#915]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description : Command-line status monitor for tor

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link : https://aur.archlinux.org/packages/nyx/

（请在此填写）

* 为何需要这个软件包 / Why Need This Package : tor is blocked in my country.

（请在此填写）

**Comment by TobiichiAmane** [comment]
If TOR is blocked and you cannot connect to tor network, why do you need a tool that monitors another tool which simply won't work?

**Comment by LinArcX** [comment]
If tor works and connect, i can use this tool.

**Comment by TobiichiAmane** [comment]
> If tor works and connect, i can use this tool.

The `if` statement is invalid unless you know it *WILL* work in the future. 

Anyway, I'll package it. Just to mention, please make sure your issue makes sense before opening it.

**Comment by TobiichiAmane** [comment]
Wait a minute, why not using `pip` to install it since it's a `python` project?

**Comment by LinArcX** [comment]
ok, i install it from pip and its not working.

**Comment by TobiichiAmane** [comment]
`nyx` is a python3 project. Please use pip or pip3 instead of pip2. And, in order to use nyx to manage your tor daemon, you need to specify a control port in your torrc.
