### ISSUE TITLE
Pls add ghdl

### ISSUE THREAD

**Issue by dongfengweixiao** [archlinuxcn/repo#92]
https://aur.archlinux.org/packages/ghdl/

此程序需要下载gcc，实际反馈为，群里有人无发编译通过，他是32位系统，也不想在自己的64位系统上帮他编译，所以请求帮助编译。

此软件稳定性不错，Deb系已经收录。

**Comment by farseerfc** [comment]
如果只是想幫朋友編譯i686的包，可以用 devtools 裏的 extra-i686-build 命令，用起來和 makepkg 差不多，只是會在獨立的容器裏用 i686 的工具鏈編譯出 i686 的包。

**Comment by zsrkmyn** [comment]
On Mon, Apr 20, 2015 at 04:33:59AM -0700, 东风唯笑 wrote:
> https://aur.archlinux.org/packages/ghdl/
> 
> 此程序需要下载gcc，实际反馈为，群里有人无发编译通过，他是32位系统，也不想在自己的64位系统上帮他编译，所以请求帮助编译。
> 
> 此软件稳定性不错，Deb系已经收录。
> 

Added. both i686 and x86_64 are available. Since I am studying in EE
school and use FPGA sometimes, this software is useful for me as well.

-- 
Regards,
Stephen

**Comment by petronny** [comment]
群？什么群？
