### ISSUE TITLE
Package Request(ulauncher)

### ISSUE THREAD

**Issue by LinArcX** [archlinuxcn/repo#920]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description : Application launcher for Linux

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains : python

（请在此填写）

* 上游链接 / Upstream Link :http://ulauncher.io

（请在此填写）

* 为何需要这个软件包 / Why Need This Package : the build and install process getting too long in my computer.

（请在此填写）

**Comment by TobiichiAmane** [comment]
The -git version is out-dated. I'll package the [official version](https://aur.archlinux.org/packages/ulauncher/) for you.

**Comment by TobiichiAmane** [comment]
eb5146f207b399de2543ccb1695d33e6e941f5a9

**Comment by LinArcX** [comment]
@TobiichiAmane Thank you so much.

**Comment by TobiichiAmane** [comment]
> @TobiichiAmane Thank you so much.

It's a nice piece of software. Thanks for the recommendation.
