### ISSUE TITLE
migrate from nvchecker.ini to lilac.yaml

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#923]
### 问题类型 / Type of issues
* 其它 / other
----

Please migrate from nvchecker.ini to lilac.yaml for all packages. You can use [nvchecker2yaml](https://github.com/TobiichiAmane/nvchecker2yaml) to help you. Note any configurations that contain special characters. Here is [the documentation for lilac.yaml](https://archlinuxcn.github.io/lilac/).

Packages that are not updated by lilac should also be migrated with the `maintainers` field filled in.

**After two weeks**, other people can help migrate packages **without consent** from the package maintainers.

See also #703 and #883.

**Comment by petronny** [comment]
转移到lilac.py中可以不。。。

**Comment by TobiichiAmane** [comment]
使用n2y的时候 **一定要** 检查每一个生成/修改的文件。

**Comment by lilydjwg** [comment]
@petronny 可以是可以，只是 update_on 里那么多引号什么的写着烦啊。

**Comment by petronny** [comment]
bf9cdad7fb1e3b0704f481f557bbd97eac6a6f09

**Comment by lilydjwg** [comment]
各位记得写 maintainers 字段呀。

**Comment by TobiichiAmane** [comment]
> 各位记得写 maintainers 字段呀。

如果使用n2y，无论如何都会帮你填上maintainers字段（

**Comment by zsrkmyn** [comment]
看起来 n2y 里可以选择不指定 `github`，但是 `lilac-yaml-schema.yaml` 里要求 `github` 字段是必须的。

**Comment by zsrkmyn** [comment]
n2y 里应该强制填写 `github` 字段，`email` 字段选填，若不填则按照 GitHub 公开的 `email`。

**Comment by zsrkmyn** [comment]
还有个问题，如果在 yaml 里指定 `build_prefix`，那么 lilac.py 就没有 `build_prefix` 了，也就不能执行 `single_main(build_prefix)` 了，如果要在编译机上测试会很不方便，因为 `single_main()` 不带参数默认执行 `makepkg`，但是编译机上没法 `makepkg`。

是否考虑 `single_main()` 默认从 yaml 里读取 `build_prefix` 呢？

**Comment by yan12125** [comment]
個人不喜歡一個包產生兩個commit，以及修改後的檔案一堆註解，因此改了下nvchecker2yaml，有興趣的可以拿去用：https://github.com/yan12125/nvchecker2yaml

**Comment by tobiichiamane** [comment]
> 個人不喜歡一個包產生兩個commit，以及修改後的檔案一堆註解，因此改了下nvchecker2yaml，有興趣的可以拿去用：https://github.com/yan12125/nvchecker2yaml

我将其处理成琐碎的commit的目的是，万一n2y弄坏了某个包可以很方便地回退更改。

**Comment by yan12125** [comment]
我的libsysstat-git lilac一直打出相同版本的包，是否我的lilac.yaml寫法有問題呢？
```
update_on:
  - aur: libsysstat-git
  - github: lxqt/libsysstat
```
(excerpted from https://github.com/archlinuxcn/repo/blob/master/libsysstat-git/lilac.yaml)

Lilac打包記錄：https://build.archlinuxcn.org/packages/#/libsysstat-git

**Comment by axionl** [comment]
> 我的libsysstat-git lilac一直打出相同版本的包，是否我的lilac.yaml寫法有問題呢？
> 
> ```
> update_on:
>   - aur: libsysstat-git
>   - github: lxqt/libsysstat
> ```
> 
> (excerpted from https://github.com/archlinuxcn/repo/blob/master/libsysstat-git/lilac.yaml)
> 
> Lilac打包記錄：https://build.archlinuxcn.org/packages/#/libsysstat-git

大概不再需要從 AUR 更新了

**Comment by lilydjwg** [comment]
是个 bug，已修正。

Chih-Hsuan Yen <notifications@github.com> 于 2018年11月24日周六 23:42写道：

**Comment by yan12125** [comment]
@lilydjwg 今天早上1點這一波libsysstat-git還是rebuilt了，是不是編譯機上nvchecker需要更新？

@axionl 謝謝建議。這個包在AUR上的維護者並不是我。我希望archlinuxcn/libsysstat-git仍然能夠追蹤AUR上PKGBUILD的更新。

**Comment by yan12125** [comment]
我好像知道原因了。lilac對於rebuild但不是update的包不會跑nvtake，而update_on除了第一項屬於update外，其餘都是rebuild。

https://github.com/archlinuxcn/lilac/commit/cc05d505b1d2e3fa3fbb56f094dcd2020d2396ac#diff-f5704182e75d12316f5b729e89a499dfR306

libsysstat-git就是這種情況。這一類應該也要納入nvtake？

**Comment by lilydjwg** [comment]
nvtake 的问题已经修了： a5e9540b55ba4043e5933adf686689583ba1208d

**Comment by yan12125** [comment]
謝謝！看來問題都解決了。

**Comment by lilydjwg** [comment]
@zsrkmyn 现在 lilac.yaml 先于 lilac.py 加载，并且 lilac.py 中能使用 lilac.yaml 解析出来的值了，所以 `build_prefix` 也可以用了。

**Comment by zsrkmyn** [comment]
@lilydjwg 谢谢！

**Comment by yan12125** [comment]
I've migrated all remaining packages with sections in nvchecker.ini. All commits look good to me at the first glance. Please tell me if any of them breaks something.
