### ISSUE TITLE
linux-pf and related outdate and credit removed

### ISSUE THREAD

**Issue by Thaodan** [archlinuxcn/repo#929]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages
nvidia-pf
linux-pf

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----
Hey I'm the maintainer of both linux-pf and nvidia-pf.
I like that you mirror my packages but please don't remove the credit to me.
Otherwise its like stealing.
If you make changes mark your pkg as modified to don't irritate the user that this pkg is the original one
from the aur.
Also please update them or take the pkgs from my offical repo.

**Comment by tobiichiamane** [comment]
Sorry for removing the credit. We always keep those credits but I don't know why this maintainer removed them. I've assigned him to this issue, maybe he'll reply in a short time.

**Comment by hzy199411** [comment]
@Thaodan, this linux-pf packages is not the same as AUR, you can refer to the commit history about the PKGBUILD, There is no your credit because the PKGBUILD is forked from aur in 2014, I remember that you are not the maintainer in 2014.
Sorry for make confuse here, I think I should orphan and delete the related packages here since I have less time to maintain it.

**Comment by Thaodan** [comment]
First @tobiichiamane no problem. 

@hzy199411 It is in way shure its a fork but it has the same name and syncs some of my changes.
I was the maintainer in 2014 in fact I was it since 2013. I see no problem here just sync all changes and mark your changes.
A clean way is to use a submodule from the AUR or from gitlab if you want.

If you still want to include your pkg in this repo and want to reduce the work needed than you can either just sync my changes with a submodule or take my binaries from my repo:
https://thaodan.de/home/bidar/home-thaodan/x86_64/

**Comment by hzy199411** [comment]
@Thaodan , Thanks for your quickly apply and advice, I made a mistake about the linux-pf maintainer, I found that you are actually the maintainer in 2014 but the credit in not include in PKGBUILD in 2014.

**Comment by petronny** [comment]
@Thaodan Are you also the maintainer of `firefox-kde-opensuse`?

I'm maintaining `firefox-kde-opensuse` in archlinuxcn.
So I have the same issue about syncing your binaries or building it myself.
There are the problems of syncing your binaries:
1. We don't have your key in `archlinuxcn-keyring`.
2. We don't know how you build your packages.  
AFAIK, just building with `makepkg` on PC always has issues, like missing dependency or using personal configurations.

Until these two has been solved, we have to build the packages ourselves.

My suggestions:
1. Would you like to be a maintainer in archlinuxcn?  
Then you can add your key and take over your packages.
And archlinuxcn has more mirror site which is better for users to download packages.
If not,
1. Could you build your packages with something like `archlinuxcn-x86_86-build` in `devtools-archlinuxcn`? If so, we can know the package is built in a clean chroot environment. Then we can add your key and sync your binaries.

**Comment by Thaodan** [comment]
@petronny Yes I am. But I don't maintain kmozillahelper (the depency of firefox-kde-opensuse).

1. Yes sure however I don't speak any Chinese (just German additionally if that could help).
     But I'd prefer to add my pkg as a submodule to sync it with the AUR/Gitlab.
2. Sure I could do. I have no issue using those scripts.

**Comment by petronny** [comment]
@Thaodan You can use `thaodan-x86_86-build` and `devtools-thaodan` by creating them yourself if you like to.
Or just `extra-x86_86-build -- -I /path/to/unofficial-depends.pkg.tar.xz` (from `extra/devtools`).

Building in clean chroots is important. And we may help you in the others.

**Comment by petronny** [comment]
#930
