### ISSUE TITLE
Package request: xournalpp

### ISSUE THREAD

**Issue by amitbha** [archlinuxcn/repo#938]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

作为一个手写笔记软件，xournalpp是xournal的重构增强版，加了很多新特性，优化了性能

* 主要语言和工具链 / Main Languages and Toolchains

C++

* 上游链接 / Upstream Link

https://aur.archlinux.org/packages/xournalpp-git

* 为何需要这个软件包 / Why Need This Package

某些方面强于ms的onenote，但又很轻量

**Comment by amitbha** [comment]
默默的等，等你在网络中...

**Comment by tobiichiamane** [comment]
bf05b652d748639b812702354c6a766c4f286138

**Comment by tobiichiamane** [comment]
这东西打包有点问题，你在本地能正常打包嘛？

**Comment by amitbha** [comment]
依赖 texlive-core 太大了，400+M，因为不用  LaTeX，所以我没装，原以为 texlive 只是编译依赖...

**Comment by amitbha** [comment]
> 这东西打包有点问题，你在本地能正常打包嘛？

我试了下，本地打包没问题，已经装好了。因为没用 latex，我把 pkgbuild 里的相关编译选项关掉了，然后去除了 texlive 依赖，包体积大大减小。
`-DENABLE_MATHTEX="OFF"`

**Comment by tobiichiamane** [comment]
奇怪了，，，我这里和 Arch CN 的打包机上都没法正常打包。你是 `makepkg` 打包的，还是 devtools 用 `extra-x86_64-build` 打包的？

**Comment by amitbha** [comment]
`makepkg`

**Comment by tobiichiamane** [comment]
那我需要研究为何 devtools 无法打包。这可能需要一段时间，而且这个包可能并不会被加入。

**Comment by tobiichiamane** [comment]
这个包的打包过程存在争议。无法用 devtools 打包的软件包存在过重的手动维护负担，所以还需要一段时间的研究。而且不要对此抱有任何希望。我先关闭这个 issue，等我精力充足的时候再来看，抱歉。
