### ISSUE TITLE
PkgReq: flightgear

### ISSUE THREAD

**Issue by FlyGoat** [archlinuxcn/repo#943]
### 问题类型 / Type of issues

* 软件打包请求 / package request

flightgear, flightgear-data

* 简述 / Brief Description

一个模拟飞行游戏

* 主要语言和工具链 / Main Languages and Toolchains

C++, cMake based build system

* 上游链接 / Upstream Link

http://home.flightgear.org/

AUR: https://aur.archlinux.org/packages/flightgear/

* 为何需要这个软件包 / Why Need This Package
Have fun :)

**Comment by zsrkmyn** [comment]
it seems simgear is hard to successfully compile.

**Comment by tobiichiamane** [comment]
这东西很巨大，，，我在怀疑会不会撑爆源（

**Comment by lilydjwg** [comment]
@tobiichiamane 1.5G 应该还好，不过不知道打包的时候那个 tmpfs 够不够用。

**Comment by VOID001** [comment]
> it seems simgear is hard to successfully compile.

Yeah, I tried and it generates lots of errors. I think the upstream need to fix it first

**Comment by VOID001** [comment]
After I downgrade the openscenegraph to openscenegraph34, simgear can pass the build.

**Comment by farseerfc** [comment]
我的 darkmod 有 2.83GiB ，也沒啥問題（

2018年12月3日(月) 11:49 Sakuraba Amane <notifications@github.com>:

**Comment by VOID001** [comment]
ea015998555dda18e24430798962fe5437f05411
```
Repository      : archlinuxcn
Name            : flightgear
Version         : 2018.2.2-3
Description     : An open-source, multi-platform flight simulator
Architecture    : x86_64
URL             : http://www.flightgear.org/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : libxmu  openscenegraph34  openal
Optional Deps   : qt5-base: fgfs --launcher
                  qt5-declarative: fgfs --launcher
                  flightgear-data
Conflicts With  : None
Replaces        : None
Download Size   : 9.96 MiB
Installed Size  : 42.75 MiB
Packager        : lilac (on behalf of Jianqiu Zhang) <zhangjianqiu13@gmail.com>
Build Date      : Wed 12 Dec 2018 02:50:35 AM CST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
