### ISSUE TITLE
Orphaning chromium-dev

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#944]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* chromium-dev

----

#893

chromium-dev这次无法通过lilac打包了，我也实在找不出fix的办法。
故弃置之。希望大家救援一下。。。

附最后一次build失败的报错邮件如下
[chromium-dev.txt](https://github.com/archlinuxcn/repo/files/2639099/chromium-dev.txt)

**Comment by kaseiwang** [comment]
看起来新版本编译过程需要 java，我在 makedeps 里添加了 'java-runtime' 编译出来了。
我放在这里了，你可以测试下
https://build.kasei.im/chromium-dev-72.0.3595.2-1-x86_64.pkg.tar.xz
https://build.kasei.im/chromium-dev-72.0.3595.2-1-x86_64.pkg.tar.xz.sig

**Comment by petronny** [comment]
@kaseiwang 感谢！我加上让lilac试一试

**Comment by petronny** [comment]
c21c21928c38c958e0dc1a4708b27e2e0ab57c2d
打包成功了~

不过此处先不关，欢迎大家接手或者共同维护。
如果快到期了我再关掉接着维护。。。

**Comment by farseerfc** [comment]
現在換用 lilac.yaml 之後 maintainers 可以寫多個人了，可以推進多人合作維護一個包。
