### ISSUE TITLE
fmt is now in [community] 

### ISSUE THREAD

**Issue by Xuanwo** [archlinuxcn/repo#945]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* fmt

----

https://www.archlinux.org/packages/extra/x86_64/fmt/

**Comment by farseerfc** [comment]
deleted in 89b2ca2fe39f011cf0a9d8b5a0dd4aefca6b3e70
