### ISSUE TITLE
copyq is available in official repos

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#947]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* copyq

----
https://travis-ci.org/archlinuxcn/repo/builds/463299281?utm_source=github_status&utm_medium=notification

**Comment by KenOokamiHoro** [comment]
removed in ddc31e3e38ba75067fa6334966e03764eace2cc.
