### ISSUE TITLE
Package request: pulseaudio-modules-bt(-git)

### ISSUE THREAD

**Issue by BruceZhang1993** [archlinuxcn/repo#960]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

a fork of pulseaudio bluetooth modules with LDAC, APTX, APTX-HD, AAC support

* 主要语言和工具链 / Main Languages and Toolchains

C CMake

* 上游链接 / Upstream Link

https://github.com/EHfive/pulseaudio-modules-bt

* 为何需要这个软件包 / Why Need This Package

AAC/APTX/APTX-HD/LDAC encoding and decoding for pulseaudio

**Comment by BruceZhang1993** [comment]
2018/12/17 18:19:31 Success pulseaudio-modules-bt-git r72.7c3b700-2

**Comment by nicholascw** [comment]
ArchlinuxCN 源打这个包之后滚系统报错 `安装 pulseaudio-modules-bt-git (r81.48fdbbcd-1) 破坏依赖 'pulseaudio-bluetooth' （gnome-bluetooth 需要）`

**Comment by BruceZhang1993** [comment]
@nicholascw 恩，PKGBUILD 里面没有加 provides ...  我添加一下

**Comment by BruceZhang1993** [comment]
r81.48fdbbcd-2 seems fixed.
