### ISSUE TITLE
Ownership request: dropbox-cli

### ISSUE THREAD

**Issue by frealgagu** [archlinuxcn/repo#962]
### 问题类型 / Type of issues
Ownership request
* 过期软件包 / out-of-date packages
dropbox-cli
### 受影响的软件包 / Affected packages
dropbox-cli
* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
dropbox-cli
----
I'm the current maintainer in AUR of package dropbox-cli and it appears to be outdated in this repo. Can I become the new maintainer of this package in order to add lilac.yaml and keep it updated?

**Comment by felixonmars** [comment]
Thanks. Please do!

**Comment by yan12125** [comment]
Done in https://github.com/archlinuxcn/repo/commit/e55c8721c58414cff78c86b721e62515d4405374 😃
