### ISSUE TITLE
Amarok

### ISSUE THREAD

**Issue by mahmoudhossam** [archlinuxcn/repo#964]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

Amarok is an audio player for KDE

* 主要语言和工具链 / Main Languages and Toolchains

Amarok is written in C++ and uses the Qt toolkit

* 上游链接 / Upstream Link

https://amarok.kde.org/en

* 为何需要这个软件包 / Why Need This Package

Amarok is a very popular player, it used to be bundled with KDE until recently.

**Comment by mahmoudhossam** [comment]
Sorry, I just saw this package in the repo.

Should I expect it to show up on pacman tomorrow?

**Comment by lilydjwg** [comment]
Probably not. It failed to build a few hours ago. @frealgagu

**Comment by frealgagu** [comment]
It will be soon in archlinuxcn repo. I'm going to remove an unused validpgpkeys in AUR PKGBUILD. No .asc or .sig files are provided because building is done cloning the git repository (until a new stable version supporting qt5 is released).

**Comment by frealgagu** [comment]
amarok is now in archlinuxcn repo. Building has passed successfully.
