### ISSUE TITLE
libxpresent: 软件包被官方仓库收录

### ISSUE THREAD

**Issue by BruceZhang1993** [archlinuxcn/repo#967]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* libxpresent

----

libxpresent now in community/libxpresent 1.0.0-1

**Comment by yan12125** [comment]
Thanks for the notification. BTW, I've opened https://bugs.archlinux.org/task/61138 for the following issue

> warning: libxpresent: local (1.0.0+3+g9d31d21-1) is newer than community (1.0.0-1)
