### ISSUE TITLE
python2-gevent-websocket: 软件包被官方仓库收录

### ISSUE THREAD

**Issue by BruceZhang1993** [archlinuxcn/repo#969]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* python2-gevent-websocket

----

https://www.archlinux.org/packages/community/any/python2-gevent-websocket/

**Comment by farseerfc** [comment]
removed in 85f56389ca1b883a59b161107346dbf99e3e27c8
