### ISSUE TITLE
PR: obexftp

### ISSUE THREAD

**Issue by amitbha** [archlinuxcn/repo#970]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

 蓝牙文件传输命令行程序

* 主要语言和工具链 / Main Languages and Toolchains

C

* 上游链接 / Upstream Link

https://aur.archlinux.org/obexftp.git
https://aur.archlinux.org/packages/obexftp/

* 为何需要这个软件包 / Why Need This Package

在终端下通过蓝牙收发文件

**Comment by MarvelousBlack** [comment]
e742d8f37f1b4116db65fd630322d348036216dd
