### ISSUE TITLE
package request: fex

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#971]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

fex is a flexible field/token extraction utility.

* 主要语言和工具链 / Main Languages and Toolchains

C

* 上游链接 / Upstream Link

https://github.com/jordansissel/fex

* 为何需要这个软件包 / Why Need This Package

It's much easier to use for most cases than awk. See https://voidlinux.org/news/2018/12/advent-fex.html.

**Comment by frealgagu** [comment]
fex is now in archlinuxcn repository.

**Comment by lilydjwg** [comment]
Thanks!
