### ISSUE TITLE
python-telegram-bot is in Community now

### ISSUE THREAD

**Issue by tobiichiamane** [archlinuxcn/repo#973]
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affected packages

* python-telegram-bot
----

**Comment by lilydjwg** [comment]
咦，lilac 不干活了……

**Comment by tobiichiamane** [comment]
> 咦，lilac 不干活了……

日常罢工，，，不要难为人家 lilac 小萝莉了（

**Comment by farseerfc** [comment]
manually removed in a25acefdd87b0321909fcef0248a0fc4cd405358
