### ISSUE TITLE
希望添加 poetry 这个包

### ISSUE THREAD

**Issue by leetking** [archlinuxcn/repo#978]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description

  Python 的打包和包依赖管理工具 [poetry](https://github.com/sdispater/poetry)

* 主要语言和工具链 / Main Languages and Toolchains

  - Python

* 上游链接 / Upstream Link

  [poetry](https://github.com/sdispater/poetry)

* 为何需要这个软件包 / Why Need This Package

**Comment by tobiichiamane** [comment]
ff73b1d2cf4a71c33662926d7f700848655839b0
