### ISSUE TITLE
Package Request(aseprite)

### ISSUE THREAD

**Issue by LinArcX** [archlinuxcn/repo#981]
### 问题类型 / Type of issues

* 软件打包请求 / package request

----

* 简述 / Brief Description: Create animated sprites and pixel art

（请在此填写）

* 主要语言和工具链 / Main Languages and Toolchains

（请在此填写）

* 上游链接 / Upstream Link: https://aur.archlinux.org/packages/aseprite/

（请在此填写）

* 为何需要这个软件包 / Why Need This Package: The build process is too long.

（请在此填写）

**Comment by LinArcX** [comment]
Up!

**Comment by farseerfc** [comment]
I am concerned with whether we can redistribute the requesting software as binary form in our repository. It is not an open-source project and it's EULA prohibits redistribution.

**Comment by BruceZhang1993** [comment]
EULA: https://raw.githubusercontent.com/aseprite/aseprite/master/EULA.txt

`You may not distribute copies of the SOFTWARE PRODUCT to third parties. Evaluation versions available for download from the Licensor's websites may be freely distributed.`

**Comment by MarvelousBlack** [comment]
right, we can't distribute this software.
