### ISSUE TITLE
DockBarX out of date

### ISSUE THREAD

**Issue by ntd** [archlinuxcn/repo#988]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* dockbarx
----
DockBarX is still stuck on 0.92 but 0.93 has been released in AUR since 2018-02-17.

**Comment by lilydjwg** [comment]
FYI this package is not managed by lilac due to lack of lilac.py.

**Comment by ykelvis** [comment]
11bb759d0521d07d44d48d5b98fcf5ee011eb8f3
