### ISSUE TITLE
[投票] 自动删除 PKGEXT

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/repo#996]
### 问题类型 / Type of issues

* 其它 / other

----
Vote: automatically delete PKGEXT in PKGBUILD?

Vote up with 👍 and down with 👎.

**Comment by lilydjwg** [comment]
Do we have a lot of such PKGBUILDs? Maybe we can add a function for this and maintainers decide whether to call it. If we are doing it automatically, we need to handle every case so that we won't delete lines not setting it (but using it in some way).

**Comment by farseerfc** [comment]
目前能 grep 到大概 5 個包提到 PKGEXT ，兩個包的 AUR 有在用 （intel-parallel-studio-xe 和
vmware-workstation），都已經處理掉了。

2019年1月23日(水) 15:12 Jingbei Li <notifications@github.com>:

**Comment by lilydjwg** [comment]
@petronny 好主意～我待会实现一下。

**Comment by petronny** [comment]
当然是build的时候加上，最后再把它删了😂

**Comment by lilydjwg** [comment]
On Wed, Jan 23, 2019 at 12:06:23AM -0800, Jingbei Li wrote:
> 当然是build的时候加上，最后再把它删了😂

好麻烦，要不你来实现？

-- 
Best regards,
lilydjwg

**Comment by lilydjwg** [comment]
@petronny 获取应该使用的 PKGEXT 似乎不是那么容易。
可能提供一个 API 用于删 PKGEXT 更可靠一些？

**Comment by petronny** [comment]
那就等同于每个包逐个处理了。。。

**Comment by lilydjwg** [comment]
是的。毕竟也只有来自 AUR 上的 PKGBUILD 需要这样处理。

**Comment by petronny** [comment]
那这个issue就没啥意义了。。。关了吧。。。
