### ISSUE TITLE
Package Request: mcpelauncher-linux-git

### ISSUE THREAD

**Issue by rocka** [archlinuxcn/repo#997]
### 问题类型 / Type of issues

* 软件打包请求 / package request

   * mcpelauncher-msa-git
   * mcpelauncher-msa-ui-qt-git
   * mcpelauncher-linux-git
   * mcpelauncher-ui-git

----

* 简述 / Brief Description

This project allows you to launch Minecraft: Bedrock Edition on GNU/Linux.

* 主要语言和工具链 / Main Languages and Toolchains

`gcc` `qt` `cmake`

* 上游链接 / Upstream Link

repo: https://github.com/minecraft-linux/mcpelauncher-manifest
doc: https://mcpelauncher.readthedocs.io/en/latest/index.html

* 为何需要这个软件包 / Why Need This Package

Oh It's Minecraft ...

**Comment by OriginCode** [comment]
These packages are now in the ``archlinuxcn`` repo.
>  OriginCode 2019-1-27
