### ISSUE TITLE
dropbox: Don't package it as it's not redistributable

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#998]
### 问题类型 / Type of issues

* 弃置软件包 / orphaning packages

### 受影响的软件包 / Affected packages

* dropbox
* dropbox-cli
* nautilus-dropbox
* nemo-dropbox

----

A Dropbox support staff said that unless I apply the Dropbox Reseller Program, I shouldn't redistribute Dropbox desktop client files. As a result, this package should be removed from [archlinuxcn]. However, there are two issues preventing me from just deleting the `dropbox/` folder:

* Some packages in [archlinuxcn] depend on dropbox (nautilus-dropbox, nemo-dropbox, dropbox-cli)
* I love lilac for automatic checking and updating PKGBUILD for dropbox

The second issue can be easily resolved - I can just run lilac periodically on my server. For the first issue, two options come to my mind:

1. Remove dropbox and all dependent packages
2. Modify lilac so that it can package nautilus-dropbox, nemo-dropbox, dropbox-cli without dropbox. I guess these packages does not actually use dropbox during packaging, so `--assume-installed` should be helpful.

I prefer option 2. Any other ideas?

UPDATE: changing this issue into an orphaning issue as option 1 is preferred by more developers.
UPDATE 2: change the issue type back after the vote.

**Comment by farseerfc** [comment]
For option 2, modify lilac.py for each package to remove hard dependency on dropbox from PKGBUILD should be enough.

**Comment by yan12125** [comment]
Thanks for the feedback. As those packages do require the dropbox package, I'm hesitated to do such a change in fear of confusing users, considering some AUR helpers prompt no longer needed packages after each system upgrade.

**Comment by farseerfc** [comment]
can be added as optdepends, so that it will be considered during `pacman -Qtd`

**Comment by yan12125** [comment]
> can be added as optdepends, so that it will be considered during `pacman -Qtd`

Hmm, after seeing this line, the second idea jumps out of my head - add a field `no_distribute` in lilac.yaml to ask lilac not to copy built packages to the repo. For example:
```Diff
diff --git a/lilac b/lilac
index cdeb266..3beff4f 100755
--- a/lilac
+++ b/lilac
@@ -93,7 +93,8 @@ def build_package(package: str, mod: LilacMod) -> bool:
     except TimeoutError:
       kill_child_processes()
       raise
-    sign_and_copy()
+    if not getattr(mod, 'no_distribute', False):
+      sign_and_copy()
     built_successfully = True
     assert _G.pkgver is not None
     assert _G.pkgrel is not None
```
Building dropbox-cli appears fine. nautilus-dropbox and nemo-dropbox uses `archlinuxcn-x86_64` as build_prefix, so they still pull the dropbox package from [archlinuxcn]. If this is the way to go, both packages should be modified to use `extra-x86_64` as existing dropbox packages on [archlinuxcn] will be removed.

**Comment by lilydjwg** [comment]
I prefer to remove all of them as it doesn't work for many people who decide that ext4 isn't as great as whatever they are currently using.

**Comment by yan12125** [comment]
Let's ask whether maintainers of affected packages want their packages to be kept in [archlinuxcn] or not.

* dropbox-cli @frealgagu 
* nemo-dropbox @heavysink 

And @farseerfc, you already know nautilus-dropbox is yours :)

**Comment by MarvelousBlack** [comment]
I also prefer to remove all of them.  if user install  the packages , they need install dropbox by themselves at first, otherwise pacman will point out lack depends.

**Comment by frealgagu** [comment]
I would consider to remove all of them, there is no reason to install dropbox-cli if dropbox is not installed, and dropbox-cli at least is not time consuming so if dropbox is going to be dropped from repo, dropbox-cli should be dropped as well.

**Comment by yan12125** [comment]
Great points! It's indeed embarrassing to have a binary repo with out-of-repo dependencies, even for optional ones [1]. I'll mark those packages orphaned and let the repocleaner bot to remove them all.

[1] https://www.archlinux.org/todo/packages-with-out-of-repositories-dependencies/

**Comment by farseerfc** [comment]
+1 for removing all of them.

**Comment by petronny** [comment]
There is another option to solve the dependency issue if we have a another `[private]` repository.
This repository should contain `dropbox`, and should be listed in `/usr/share/devtools/pacman-arch4edu.conf`. So `nautilus-dropbox` and the others can be built. But all the packages in `[private]` won't be pushed to `repo.archlinuxcn.org`. So we won't break the license.

This also means we will have binaries with out-of-repo dependencies.
But for me, having binaries with out-of-repo dependencies is acceptable.

**Comment by yan12125** [comment]
IMO introducing private repositories is not a good idea. First, technically private repositories are not necessary if lilac is extended as per my previous comment https://github.com/archlinuxcn/repo/issues/998#issuecomment-453410535. Second, maintaining private repositories is quite complicated. The infrastructure needs many changes to be able to handle both public and private repositories.

> But for me, having binaries with out-of-repo dependencies is acceptable.

You got the first controversial issue! Maybe we will have a vote over that. Anyway, I'd like to hear some comments from @heavysink before further actions.

**Comment by yan12125** [comment]
Seems heavysink is too busy to have a look here. Let's start the vote!

Please vote :+1: **on this comment** if you want to remove all packages depending on dropbox (dropbox-cli, nautilus-dropbox, nemo-dropbox), or :-1: if you want to remove dropbox only and keep depending packages.

**Comment by yan12125** [comment]
I'd like to postpone the orphaning process, so I modified the original issue, but seems lilacbot does not handle such a case, so I remove the label manually.

**Comment by yan12125** [comment]
Looks like few people in Arch Linux Chinese Community care about dropbox and related packages. Let's remove them all after 14 days!
